src/txn/txn_ckpt.c

Fix recovery after a fake checkpoint with logging enabled

---

examples/java/com/wiredtiger/examples/ex_async.java
examples/java/com/wiredtiger/examples/ex_call_center.java
examples/java/com/wiredtiger/examples/ex_cursor.java
examples/java/com/wiredtiger/examples/ex_log.java
examples/java/com/wiredtiger/examples/ex_schema.java
examples/java/com/wiredtiger/examples/ex_stat.java
examples/java/com/wiredtiger/examples/ex_thread.java
lang/java/src/com/wiredtiger/db/PackFormatInputStream.java
lang/java/src/com/wiredtiger/db/PackInputStream.java
lang/java/src/com/wiredtiger/db/PackOutputStream.java
lang/java/wiredtiger.i
src/cursor/cur_log.c
src/include/cursor.h

Fix errors in java examples preventing them from running.

---

src/btree/bt_page.c
src/include/btree.i
src/include/cache.i
src/include/cursor.i
src/include/txn.i
src/include/wt_internal.h
src/lsm/lsm_cursor.c
src/session/session_api.c
src/txn/txn.c
src/txn/txn_log.c

Fixes for some MongoDB pauses

---

src/btree/bt_debug.c
src/btree/bt_split.c

@michael, I think this one is ready to merge if you agree with the change.

Slow deepen split

---

src/btree/bt_split.c

During the process of doing a split we switch the ref to WT_REF_MEM - after which it's no longer safe to refer to the page. Shuffle the code so that we don't.
SERVER-16868

Don't look at a page after it may be freed during split.

---

src/cursor/cur_stat.c

Refs #1575 and JIRA SERVER-16738

Fix a deadlock opening statistics cursors.

---

test/suite/run.py

Put the local build directories to the front of the sys path.

---

src/txn/txn_recover.c

Don't assert that we see a checkpoint complete in the available log: if the application crashes in between syncing the metadata and writing the final checkpoint record, there is no need to roll anything forward but we don't have the final checkpoint.
refs #1529

Change recovery to start from the checkpoint LSN in the metadata

---

src/btree/bt_split.c

We were doing this when a page spontaneously became empty, but not if the "fast truncate" code kicked in.
refs SERVER-16921

Free WT_REFs deleted by truncate

---

src/log/log.c
src/log/log_slot.c

Avoid yielding in logging: it causes problems with large numbers of threads

---

src/reconcile/rec_track.c

Otherwise, we could free structures that are still hooked into the skiplist.
refs #1615

Use a copy of the oldest transaction ID when sweeping cached overflow items

---

src/include/btree.i
src/reconcile/rec_track.c

@michaelcahill, please skim & merge when things are quiet enough.

rec-track cleanup

---

src/docs/install.dox
src/docs/spell.ok

Here is some documentation on how to build on Windows that @keithbostic asked for. I added several features to the build PR #1606 in order to bring the Windows build closer to the Posix build.

Windows Install Documentation

---

tools/template/README.md

some small clarifications and documentation for UI of wtstats tool.

added documentation for wtstats UI

---

src/reconcile/rec_write.c
test/suite/test_split.py

@agorrod, here's a slightly different approach, what do you think?
(It's probably simplest to compare it to develop, and not to the rec-split-fix branch.)

A slightly different approach to fixing the reconciliation split bug.

---

src/btree/bt_split.c

@agorrod, it occurred to me, we have a count of the deleted items, there's no reason to continue after we've found them all.

shorten pass over deleted items

---

src/evict/evict_lru.c
src/include/btree.i

@michael, this change helps with SERVER-17183.

Fast-path eviction of dead pages

---

src/block/block_open.c
src/conn/conn_handle.c
src/conn/conn_open.c
src/include/block.h
src/include/connection.h
src/include/os.h
src/os_posix/os_open.c
src/os_posix/os_remove.c
src/os_win/os_open.c
src/os_win/os_remove.c

@sueloverso, I'm guessing this is what you were really thinking about in your question about tail inserts -- if so, then I think we agree TAILQs aren't necessary, here's the obvious change for your consideration.

Switch the block and file-handle from TAILQ structures to SLIST structures

---

src/lsm/lsm_work_unit.c

minor error handling cleanups to __wt_lsm_get_chunk_to_flush

---

src/btree/bt_cursor.c
src/session/session_api.c

@michaelcahill, here's the change we discussed for your review.

Force forward traversal in WT_SESSION.truncate.

---

src/btree/bt_compact.c
src/btree/bt_sync.c
src/evict/evict_file.c
src/evict/evict_lru.c
src/include/extern.h

@michaelcahill, for your consideration. These aren't bug fixes (well, maybe the compaction change is a bug fix?), but I think they clarify things.

Clean up a couple of hard corners.

---

src/evict/evict_lru.c

If eviction is walking a file with only one live page (e.g., the last page), be careful to step over it, or eviction's hazard reference can make forced eviction stall.
SERVER-17344

Avoid eviction pinning the last page of append-only trees

---

src/btree/bt_page.c

Changes in page-acquisition handling of forced-eviction

---

src/log/log.c
test/format/recover.sh

Also, fix recover.sh to grep the CONFIG.  #1700
@michaelcahill Please review.

If the LSN given doesn't exist, don't return an error, but do force recovery

---

test/format/config.c
test/format/config.h
test/format/format.h
test/format/ops.c
test/format/t.c

@agorrod, here's what I was thinking we could do that would use `timer` as the maximum time instead of adding a new `timeout` variable.

Format compression config

---

src/log/log.c

@michaelcahill Please review.  I added fsync calls where we close the logging file handles anytime they may have been written and after writing the header.  For the header, it is important that most log files are pre-allocated so that we're not fsyncing on the mainline path.  But I believe that is not generally a problem.

Add fsync before closing log files and after header. #1717

---

src/lsm/lsm_work_unit.c

We are only accessing one page at a time, and allowing the bloom create to block can lead to LSM not making progress.
Refs: #1720

Don't allow LSM bloom create to block waiting for space in the cache.

---

src/btree/bt_walk.c

@michaelcahill, fixes for the walk code, reference SERVER-17345.

Fix for the walk code

---

src/btree/bt_sync.c

refs SUPPORT-1248, SERVER-17506

When skipping a dirty page during a checkpoint, make sure the tree is marked dirty

---

src/block/block_ckpt.c
src/block/block_compact.c
src/block/block_open.c
src/include/block.h
src/include/extern.h

@michaelcahilll, for your review.

Change checkpoints to do first-fit allocation

---

src/btree/bt_split.c

Minor cleanups to @michaelcahill's "no-cache-ikey-before-splitting" branch, ref #1747.

Minor cleanups.

---

src/btree/bt_handle.c
src/btree/bt_page.c
src/btree/bt_read.c
src/btree/bt_slvg.c
src/btree/bt_split.c
src/include/extern.h

@agorrod, here's what I was suggesting for your consideration, just toss it if you don't like it.

Pass a length with the image.

---

src/include/cursor.i
src/include/txn.i

Look at whether a transaction ID is pinned, not whether the TXN_SNAPSHOT flag is set.
Found by inspection when debugging a hung test/format config.

Fix read-uncommitted cache checks

---

src/evict/evict_lru.c
src/include/btree.i
src/support/hazard.c
test/suite/test_bug011.py

So far only a test case - need to code up a fix.

Eviction server running out of hazard references.

---

dist/api_data.py
src/config/config_def.c
src/conn/conn_api.c
src/conn/conn_sweep.c
src/include/connection.h
src/include/extern.h
src/include/session.h
src/include/wiredtiger.in
src/session/session_dhandle.c
test/suite/test_reconfig.py
test/suite/test_sweep01.py
test/suite/test_sweep02.py

Not yet ready for merge - needs some test code.

Sweep api config

---

src/conn/conn_api.c

@michaelcahill Please review this change for SERVER-17571.

Fsync after writing WiredTiger file. #1775

---

src/session/session_dhandle.c

Only wait for ebusy if requesting exclusive access.

Update the session get btree busy check:

---

SConstruct

Adds LZ4 support to SCons. Verified it compiles and links on with VS 2013.

Add LZ4 support to SCons

---

src/evict/evict_lru.c

Close the main eviction thread first, so the number of helper threads can be read safely.
Partial fix for #1698

Fix a race closing eviction helper threads

---

src/block/block_open.c
src/conn/conn_api.c
src/conn/conn_handle.c
src/conn/conn_log.c
src/conn/conn_open.c
src/include/extern.h
src/log/log.c
src/meta/meta_turtle.c
src/os_posix/os_open.c
src/os_win/os_open.c

@agorrod, a quick cleanup, would you be kind enough to review?
Thanks!

simplify __wt_close calls

---

src/conn/conn_dhandle.c

The sweep server was holding a handle exclusive and waiting on the handle list lock (in order to remove the handle from the list), a checkpoint was holding the handle list lock waiting for a read lock on the handle.  Found by examining a hang during automated testing.

Avoid a deadlock between the sweep server and a checkpoint.

---

ext/compressors/lz4/lz4_compress.c

We rely on it to detect errors, which can make fast mode segfault.
refs #1800

Switch to using "safe mode" LZ4 decompression

---

src/include/column.i
test/suite/test_colgap.py

Add a test case for a new bug in variable length column stores.

---

src/reconcile/rec_write.c

@agorrod, would you please do the review?
#1852 can be closed when this one is merged.

Reconciliation can access free'd memory.

---

src/conn/conn_dhandle.c
src/os_posix/os_open.c
src/os_posix/os_remove.c
src/os_win/os_open.c
src/os_win/os_remove.c

@sueloverso, would you please do the review?

Fix places where we were using the wrong link for traversing hash buckets.

---

dist/dist.py
src/os_win/os_errno.c
src/os_win/os_once.c

Now style.py checks the Windows files also.

KNF for Windows files

---

src/async/async_worker.c
src/log/log.c
src/txn/txn_recover.c

@sueloverso, would you please do the review?
Thanks!

Remove unnecessary error labels

---

dist/api_data.py
src/config/config_def.c
src/conn/conn_stat.c
src/conn/conn_sweep.c
src/docs/upgrading.dox
src/include/connection.h
src/include/stat.h
src/include/wiredtiger.in
src/os_posix/os_open.c
src/os_win/os_open.c
test/suite/test_sweep01.py

@agorrod, here are the changes for #1856, that issue can be closed with the merge of this branch.

Sweep file handle minimum

---

bench/wtperf/wtperf.c
bench/wtperf/wtperf_opt.i
src/docs/wtperf.dox

Helps figure out how long a drop takes. Refs #1876

Add functionality to drop files at the end of a wtperf run.

---

build_posix/Make.subdirs
build_posix/configure.ac.in
dist/s_string.ok
test/format/Makefile.am
test/format/bulk.c
test/format/format.h
test/format/ops.c
test/format/t.c
test/format/wts.c

@michaelcahill, I wanted to divorce format from Berkeley DB installations, now that we're running on Windows. I don't think there's anything controversial in here, but a quick skim would be appreciated.

Change to build format without installing Berkeley DB.

---

dist/api_config.py
src/config/config_def.c

Generated tables for config subcategories are qualified by referencing method name.

---

src/conn/conn_cache.c
src/conn/conn_open.c
src/evict/evict_lru.c

Shut down the eviction server before closing file handles to avoid a race

---

src/btree/bt_io.c
test/suite/test_encrypt01.py

The errors came to light when running a 'nop' encryptor with a 'nop' compressor.  Test case included.

Fixes for decrypting blocks

---

src/evict/evict_lru.c

Reference #1900.
@michaelcahill, @agorrod, can one of you look at this branch?
If you like it, merge it, otherwise feel free to simply discard it.

Create a "clear a single walk" function.

---

examples/c/ex_all.c
src/config/config_api.c
src/include/wiredtiger.in
src/support/err.c

@michaelcahill, here are the changes to add a WT_EVENT_HANDLER to `wiredtiger_config_validate`.

Change wiredtiger_config_validate to take a WT_EVENT_HANDLER as an argument

---

src/conn/conn_dhandle.c
src/cursor/cur_file.c
src/include/schema.h
src/session/session_api.c
src/session/session_dhandle.c

@michaelcahill, this is my review from #1923.

Handle open locking review

---

src/include/txn.i

Move eviction outside transactions.

---

test/utility/test_util.i

Fix for covert tests

---

dist/log.py
src/btree/bt_io.c
src/conn/conn_log.c
src/include/extern.h
src/include/log.h
src/log/log.c
src/log/log_auto.c
src/support/crypto.c

Clean up log temporary buffer handling.

---

dist/api_data.py
src/docs/tune-cache.dox
src/include/wiredtiger.in
src/lsm/lsm_tree.c

Disallow the cache_resident flag on LSM trees.

---

src/btree/bt_debug.c
src/btree/bt_discard.c
src/btree/bt_split.c
src/btree/bt_sync.c
src/evict/evict_page.c
src/include/btmem.h
src/reconcile/rec_write.c

Fix checkpoint visiting a page that was rewritten in memory

---

src/conn/conn_cache.c
src/include/btree.i

More issues remain.
Refs WT-1885

Fix some issues with cache leaf size accounting for statistics.

---

test/checkpoint/test_checkpoint.c
test/fops/t.c
test/huge/huge.c
test/thread/t.c
test/utility/test_util.i

As per suggestion by @keithbostic

Change all testutils functions to have a void return

---

src/txn/txn_ckpt.c

@michaelcahill Please review this fix for SERVER-18316.  I have asked Jonathan to try a patch with the failing script.

Sync the metadata file before updating turtle file. SERVER-18316

---

src/txn/txn_ckpt.c

It's not safe to commit the transaction before the files have been
synced to disk - if we do that the checkpoint can be rolled forward
in recovery before the checkpoint in the file has been updated.
Refs SERVER-18316

Fix a bug in checkpoint where we committed the transaction too early.

---

src/support/filename.c
test/bloom/test_bloom.c
test/checkpoint/test_checkpoint.h
test/fops/thread.h
test/format/format.h
test/huge/huge.c
test/salvage/salvage.c
test/thread/thread.h
test/utility/test_util.i

Make cleanup check before deleting

---

dist/api_data.py
src/config/config_def.c
src/conn/conn_log.c
src/include/txn.h
src/include/wiredtiger.in
src/txn/txn.c

Change to commit_transaction for background sync.

---

src/include/extern.h
src/schema/schema_list.c
src/schema/schema_open.c
src/schema/schema_rename.c

@agorrod, just a couple of (really) minor cleanups, would you please review whenever the develop branch is open again? Thanks!

Stuff i noticed

---

SConstruct
examples/c/ex_encrypt.c
src/os_win/os_dlopen.c
test/suite/test_encrypt06.py

@markbenvenuto, can you review these changes please?

Encryption related fixes for windows

---

src/conn/conn_sweep.c

Disable eviction in a tree while it is being marked dead.

---

src/lsm/lsm_manager.c

@agorrod Here's one change for closing the window on LSM shutdown for your consideration.  Feel free to toss if you don't like it or disagree with my earlier concern that the window exists.

Increment queue_ref count before checking flag. WT-1935

---

src/block/block_open.c

@michaelcahill, as discussed.
refs WT-1932

block manager and already-existing files.

---

build_posix/Make.subdirs
dist/extlist
dist/s_string.ok
ext/extractors/csv/Makefile.am
ext/extractors/csv/csv_extractor.c
src/conn/conn_api.c
src/include/extern.h
src/schema/schema_open.c
test/suite/test_schema04.py
test/suite/test_schema05.py

Added extractor tests and a small fix for customized extractors.

---

dist/log.py
src/btree/bt_debug.c
src/log/log_auto.c
src/txn/txn_log.c

@ddanderson, would you please review and merge this one?
It's a trivial cleanup, but there's a change in dist/log.py that I thought might be worth a few seconds.
Thanks!

Replace calls to fprintf in the logging and transaction code.

---

src/evict/evict_page.c

We were checking the wrong flags value for WT_SKIP_UPDATE_RESTORE

---

src/block/block_compact.c
src/btree/bt_compact.c

Compact early exit

---

test/suite/suite_random.py

@ddanderson, for your consideration:
* use the standard seed values if no values specified,
* this isn't thread safe, check for seed values that have gone to 0 (that's probably sufficient),
* minor changes to make the code look like the C code.

Python PRNG update

---

src/session/session_dhandle.c

@michaelcahill, just getting rid of a compiler/lint complaint, if you don't mind, no real change.

Avoid compiler complaints

---

lang/python/wiredtiger/intpacking.py
lang/python/wiredtiger/packing.py
test/packing/intpack-test3.c
test/suite/test_intpack.py

Here are some fixes along with some tests for python.

WT-1985 integer packing fixes for Python

---

src/reconcile/rec_write.c

row-store __rec_txn_read() optimization

---

src/meta/meta_track.c

@michaelcahill, @agorrod: for review and merge.

WT-1992: clean up metadata tracking error handling

---

test/suite/helper.py
test/suite/test_backup05.py
test/suite/test_durability01.py

Added copy_live_wiredtiger_home function, with two callers.

Minor test suite refactor

---

src/block/block_open.c

block_open.c:200: Returning without unlocking "conn->block_lock.lock".

WT-1993 Coverity CID 1310061: Program hangs (LOCK)

---

src/conn/conn_handle.c
src/conn/conn_log.c
src/cursor/cur_backup.c
src/include/connection.h
src/txn/txn_ckpt.c

@michaelcahill please review this branch that changes the hot_backup_lock to a rwlock.

WT-1962 Make the hot_backup_lock a read/write lock.

---

dist/s_all

WT-1970
@agorrod, `read -d` is a bash extension, and I don't think we actually need it if we use a default xargs configuration.
For your review.

WT-1970: read -d command

---

dist/s_all

@agorrod, a few more cleanups, for your review, just discard anything you don't want.

s_all cleanup pass

---

src/btree/bt_walk.c
src/include/btree.i

WT-1969 WT_REF.pindex_hint cleanup

---

src/block/block_read.c

WT-2020: ready for review & merge by anybody.

WT-2020: clarify checksum error failure messages.

---

src/block/block_open.c

WT-2015: ready for review & merge by anybody.

WT-2015: error path failure during block open.

---

src/os_posix/os_mtx_rw.c

@ddanderson, @michaelcahill, for your review.

WT-2023: Avoid the CAS instruction in the trylock functions.

---

src/evict/evict_lru.c

WT-2028 minor __evict_walk_file cleanup

---

src/include/serial.i

@michaelcahill, for your consideration.

row-insert-nolock review

---

src/btree/row_srch.c
test/suite/test_cursor_random.py

WT-2032: WT_CURSOR.next configured with next_random=true on insert-only pages

---

src/include/serial.i

They may re-read arguments and race.

WT-2025 Pass simple arguments to compare-and-swap macros

---

src/conn/conn_open.c
src/include/connection.h
src/txn/txn_recover.c

recovery with an error.
@michaelcahill Please review.

WT-2037 Only write a checkpoint to the log on close if it wasn't

---

dist/stat.py
src/btree/bt_handle.c
src/conn/conn_dhandle.c
src/conn/conn_handle.c
src/include/extern.h
src/support/stat.c

@michaelcahill, I forgot to move the data-handle statistics initialization out of the btree code into the data-handle initialization code.
Please merge if you agree.

WT-2029, minor cleanups.

---

src/block/block_open.c

Reference WT-2048.
@michaelcahill, ready for review & merge.

WT-2048 Quiet a Coverity complaint.

---

test/format/smoke.sh
test/format/t.c

@michaelcahill, ready for review & merge.

WT-2049 don't start format's RNG at the same place every time.

---

src/btree/bt_split.c

Only give up if a checkpoint is in progress.

WT-2062 Try harder to make progress on in-memory splits

---

src/evict/evict_lru.c

A thread may be holding that lock (e.g., verify) and waiting for the eviction server to clear a walk, leading to deadlock.

WT-2064 Don't spin indefinitely waiting for the handle list lock in eviction

---

src/os_win/os_mtx_cond.c

@markbenvenuto, can you review & merge if this is correct?

Avoid losing errors from the underlying Windows functions.

---

src/btree/bt_split.c
src/include/btree.i

@michaelcahill, I created this branch while responding to your comments on WT-2089, probably not interesting until those discussions wrap up.

WT-2089 relax restrictions on multiblock eviction, in-memory splits

---

src/btree/bt_read.c

Reverts part of 0af2b62e6fa8abb968f0847691f18e5b9c79b11f

WT-2097 Reintroduce immediate waits when forced eviction is necessary.

---

src/btree/row_srch.c
src/docs/cursor-random.dox

@michaelcahill, for review & merge.

SERVER-20385: WT_CURSOR.next(random) more random

---

src/include/serial.i

@michaelcahill, just a couple of things I noticed by inspection this morning -- please review, maybe I'm just misreading the code!

SERVER-20193 Fix obsolete transaction check

---

bench/wtperf/runners/1bn-lsm-50r50u.wtperf
bench/wtperf/runners/1bn-lsm-80r20u.wtperf
bench/wtperf/runners/1bn-lsm-populate.wtperf
bench/wtperf/runners/1bn-lsm-rdonly.wtperf
bench/wtperf/runners/2bn-lsm-50r50u.wtperf
bench/wtperf/runners/2bn-lsm-80r20u.wtperf
bench/wtperf/runners/2bn-lsm-populate.wtperf
bench/wtperf/runners/2bn-lsm-rdonly.wtperf
bench/wtperf/runners/500m-btree-50r50u.wtperf
bench/wtperf/runners/500m-btree-80r20u.wtperf
bench/wtperf/runners/500m-btree-populate.wtperf
bench/wtperf/runners/500m-btree-rdonly.wtperf
bench/wtperf/runners/500m-lsm-50r50u.wtperf
bench/wtperf/runners/500m-lsm-80r20u.wtperf
bench/wtperf/runners/500m-lsm-populate.wtperf
bench/wtperf/runners/500m-lsm-rdonly.wtperf
bench/wtperf/runners/50m-lsm-50r50u.wtperf
bench/wtperf/runners/50m-lsm-80r20u.wtperf
bench/wtperf/runners/50m-lsm-populate.wtperf
bench/wtperf/runners/50m-lsm-rdonly.wtperf

As per the email discussion with Sue. Renamed the test1-4 suite and added a few extra comments

Re-organize and rename WT riak/basho tests.

---

src/btree/bt_slvg.c

@sueloverso, another Coverity fix for review & merge, please!

WT-2112: Coverity 73704, 73705, memory leak in salvage

---

dist/stat_data.py
src/conn/conn_log.c
src/include/extern.h
src/include/stat.h
src/include/wiredtiger.in
src/log/log.c
src/log/log_slot.c
src/support/stat.c

@michaelcahill Please review this code cleanup.  I enhanced some verbose messages, cleaned up a lot of comments and some of the logging code.

WT-2088  Clean up log verbose messages and comments.  Some code cleanup.

---

src/btree/bt_misc.c

The code is used via diagnostics and salvage.

WT-2132 Be more defensive in code used to debug address structures.

---

src/meta/meta_track.c

@michaelcahill, just a minor cleanup, but ought to be reviewed.

WT-2141: __meta_track_apply, __meta_track_unroll have unnecessarily complex error handling.

---

src/conn/conn_log.c

@michaelcahill Please review.  After being able to repro the failure, I have fixed it similarly to your analysis.  I also did reduce the wait time to 100msec.  I repro'ed in about 20 iterations of running the test and this has run successfully a few hundred.

WT-2137 Check the sync_lsn is in the correct file before moving it forward.

---

src/log/log.c

@sueloverso, I'm hoping we can shut Coverity/lint up about some log.c code.
Feel free to reject any of these changes you don't want, there's nothing wrong here that I can see.

SERVER-20543: Coverity/lint cleanups.

---

src/include/btree.i

I'm concerned that the first version of this change could split if a single large item is appended to a page.  This version reduces the required count, but only splits if we hit the count *and* the size condition.  
Further, it makes it more explicit that we are sampling by looking at level 2 in the tree.

SERVER-20303 Require a minimum item count for in-memory splits.

---

src/include/btree.i

@michaelcahill, @agorrod: ready for review and merge.

SERVER-20303: tuning in-memory splits for when inserting large objects

---

src/config/config.c

@agorrod or @sueloverso, ready for review & merge.

WT-2159: don't check the config twice in one path.

---

src/block/block_ckpt.c
src/include/block.h

@sueloverso, here's the change to detect if the live system is re-opened. I've smoke-tested it, but not much more.

WT-2068: complain if the live system is re-opened.

---

src/btree/bt_cursor.c

@agorrod, @michaelcahill, for review and merge.

WT-2180: remove cursor.{search,search-near,remove} key size validation

---

src/lsm/lsm_work_unit.c

@sueloverso, yours for review, merge, or discard.

WT-2164: minor cleanups to __wt_lsm_checkpoint_chunk

---

src/evict/evict_page.c

There is a race between checking whether all children are in state
WT_REF_DISK and whether the internal page is modified.

WT-2192 Fix the logic around checking whether internal page is evictable.

---

src/btree/bt_sync.c

@michaelcahill, for your consideration.

WT-2204: Don't take a local copy of page->modify until we know the page is dirty.

---

src/cursor/cur_backup.c

@keithbostic  Please review this change to cur_backup.c for the two issues that were listed in the ticket.  In particular I moved the initialization of cb->list_next earlier next to where we initialize cb->list.

WT-2135 Fix log_only setting for backup cursor. Fix initialization.

---

dist/s_string.ok
src/conn/conn_sweep.c
src/include/connection.h
src/include/extern.h
src/include/misc.i
src/os_posix/os_time.c
src/os_win/os_time.c
src/session/session_dhandle.c

@agorrod, I just noticed we were misusing time_t in a few places, for your review.

WT-2220: time_t cleanup.

---

src/block/block_ckpt.c
src/cursor/cur_join.c
src/evict/evict_lru.c
src/log/log.c

@sueloverso, would you please do a quick skim?
Thanks.

Minor __wt_errx cleanup.

---

src/cursor/cur_join.c
src/cursor/cur_stat.c
src/include/cursor.h
src/include/extern.h
src/session/session_api.c

@keithbostic, can you review and check with lint?  Thanks!

WT-2227 Resolve lint errors in join implementation

---

src/include/txn.i

It had a major perf impact on parallel populate workloads including YCSB.

WT-2237 Avoid yields if we race allocating transaction IDs.

---

src/btree/bt_discard.c
src/btree/bt_split.c
src/include/extern.h

@agorrod, @michaelcahill, for your consideration/review.

WT-2230: multi-split error path

---

src/log/log_slot.c

@keithbostic Here's the minor change for the logging stat.  Please review and merge when develop is open again.

WT-2250 Minor fix.  Use SET instead of INCRV for stat.

---

src/btree/bt_discard.c
src/btree/bt_slvg.c
src/btree/bt_split.c
src/evict/evict_page.c
src/include/btree.i
src/reconcile/rec_write.c

There was a lot of repeated code to check for offpage and free ref->addr, create an inlined function.

WT-2251 Free addresses when we discard deleted page references.

---

src/btree/bt_delete.c
src/btree/bt_discard.c
src/btree/bt_slvg.c
src/btree/bt_split.c
src/btree/bt_walk.c
src/evict/evict_page.c
src/include/btree.i
src/reconcile/rec_write.c

Also includes fixes for:
SERVER-21568 - use after free
WT-2251 - addr structure leak

SERVER-21553 3.0 backport

---

bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
bench/wtperf/wtperf_truncate.c

WT-2245 - Add a multiplier to the truncate stones to deal with very high throughput cases

---

dist/stat_data.py
src/btree/bt_io.c
src/include/log.h
src/include/misc.i
src/include/stat.h
src/include/wiredtiger.in
src/log/log.c
src/support/stat.c

@keithbostic Here are changes to generalize the tracking functions and add it into logging for your consideration.

WT-2229 Add compression skipping to log compression.

---

src/btree/row_srch.c

WT-2291: fix for sampling in newly created trees.

---

src/btree/bt_compact.c
src/include/session.h
src/reconcile/rec_write.c
src/session/session_compact.c
test/suite/test_compact02.py

@agorrod, @sue, ready for review/merge.

WT-2290: don't reuse previous multi-block write blocks when compacting

---

src/block/block_mgr.c
src/block/block_open.c
src/btree/bt_cursor.c
src/conn/conn_dhandle.c
src/cursor/cur_stat.c
src/include/block.h
src/include/extern.h

@agorrod, just a minor cleanup for your consideration/review.

WT-2299: upper-level WiredTiger code is  reaching into the block manager

---

examples/c/ex_data_source.c
src/block/block_ext.c
src/include/extern.h
src/utilities/util_list.c
tools/wt_ckpt_decode.py

`wt list -c` now decodes checkpoints.  Also created a python utility to do the same.

WT-2276 decode checkpoints via 'wt list -c' and via standalone Python utility.

---

dist/s_copyright

Builds on another change that was pushed directly to develop branch: 00c2116d630416dbc871b539b5e234c14248f5b6

WT-2320 Only check copyright as part of cutting a release.

---

bench/wtperf/config.c

Fixes for some of the recently found coverity issues.

WT-2305 - Fix coverity issues

---

bench/wtperf/config.c
bench/wtperf/misc.c
bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
bench/wtperf/wtperf_truncate.c
dist/s_string.ok

and replace all existing malloc, calloc and strncpy calls

WT-2326 - Add dcalloc, dmalloc and dstrdup to wtperf 

---

test/format/format.h
test/format/wts.c

WT-2287: WT_SESSION.rebalance

---

src/btree/bt_debug.c
src/evict/evict_lru.c
src/include/btmem.h

WT-2321: race between eviction and worker threads on the eviction queue
@agorrod, @michaelcahill, for your review/consideration.

WT-2321: race between eviction and worker threads on the eviction queue

---

lang/python/wiredtiger/packing.py
src/docs/schema.dox
src/include/packing.i
test/packing/packing-test.c
test/suite/test_config06.py

WT-1517: schema format edge cases
@michaelcahill, a branch for the fixes for WT-1517.

WT-1517: schema format edge cases

---

SConstruct
bench/wtperf/Makefile.am
bench/wtperf/config.c
bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
bench/wtperf/wtperf_throttle.c
bench/wtperf/wtperf_truncate.c

Follow on from https://github.com/wiredtiger/wiredtiger/pull/2395
Change has been squashed down to one commit and rebased against master.

WT-2267 - WTPERF Throttle implementation

---

src/btree/bt_rebalance.c
src/btree/bt_vrfy.c

WT-2339: format post-rebalance verify failure

WT-2339: format post-rebalance verify failure

---

src/conn/conn_log.c
src/log/log.c

WT-2340: Add logging guarantee assertions, whitespace

WT-2340: Add logging guarantee assertions, whitespace

---

bench/wtperf/idle_table_cycle.c
dist/s_string.ok
src/btree/bt_rebalance.c

WT-2344: OS X compiler warning

WT-2344: OS X compiler warning

---

dist/s_all
dist/s_copyright
dist/s_style

WT-2348: xargs -P isn't portable

WT-2348: xargs -P isn't portable

---

src/btree/bt_split.c

@michaelcahill, @agorrod, for your review/consideration.

WT-2371: parent split cannot access the page after page-index swap

---

src/btree/row_srch.c

WT-2368: row-store can pass garbage keys to collator functions
@ddanderson, this is the fix for WT-2368.

WT-2368: row-store can pass garbage keys to collator functions

---

examples/c/ex_encrypt.c
examples/c/ex_log.c
src/conn/conn_log.c
src/cursor/cur_log.c
src/include/log.h
src/include/log.i
src/include/wiredtiger.in
src/include/wt_internal.h
src/log/log.c
src/log/log_slot.c
src/meta/meta_ckpt.c
src/txn/txn_log.c
src/txn/txn_recover.c

@michaelcahill Here is a new branch that implements the LSN changes as a union, getting rid of the macros from the earlier version.  This is off develop and replaces the other branch.  Please review.

WT-2215 Use 32-bit LSN file and offsets. Set LSNs as a 64-bit value.

---

src/btree/bt_curprev.c
src/btree/row_srch.c
src/include/column.i
src/include/extern.h

@michaelcahill, @agorrod for your review/consideration.

WT-2367: WT_CURSOR.next out-of-order returns failure

---

src/cursor/cur_join.c
src/cursor/cur_stat.c
src/packing/pack_impl.c

Remove a few unnecessary error handling labels.

WT-2393: Unnecessary error handling labels.

---

dist/s_string.ok
test/recovery/random-abort.c
test/recovery/truncated-log.c

WT-2407: recovery lint

---

test/cursor_order/cursor_order_file.c
test/cursor_order/cursor_order_ops.c

WT-2406: cursor_order lint, minor bug fixes

---

bench/wtperf/config.c
bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
src/conn/conn_api.c

@keithbostic If you're around please review a small diff to fix a few of the Jenkins failures from the readonly merge.

WT-2349 Fix Jenkins memory failures

---

src/block/block_mgr.c
src/cursor/cur_backup.c
src/cursor/cur_config.c
src/cursor/cur_ds.c
src/cursor/cur_dump.c
src/cursor/cur_file.c
src/cursor/cur_index.c
src/cursor/cur_join.c
src/cursor/cur_log.c
src/cursor/cur_metadata.c
src/cursor/cur_stat.c
src/cursor/cur_std.c
src/cursor/cur_table.c
src/include/cursor.h
src/include/extern.h
src/lsm/lsm_cursor.c
src/session/session_api.c
src/session/session_compact.c

WT-2410: Casting function pointers to different types

---

test/bloom/test_bloom.c
test/checkpoint/test_checkpoint.c
test/cursor_order/cursor_order.c
test/fops/t.c
test/format/format.h
test/format/t.c
test/huge/huge.c
test/readonly/readonly.c
test/recovery/random-abort.c
test/recovery/truncated-log.c
test/salvage/salvage.c
test/thread/t.c
test/utility/test_util.i

WT-2422: multiple definitions of custom die function

---

src/session/session_dhandle.c

The code has diverged a lot between 3.0 and the latest develop, and
a backport included half of a reference counting change. This
patches up the reference counting in 3.0. The problem being solved
is:
There are two phases to opening a handle in a session for the first
time. First retrieve or open the handle from the connection cache,
then add it to the session cache. The code was structured to split
those into two separate phases (one while holding a lock the other
after the lock had been released). The reference count needs to be
bumped while the lock is being held, the session cache doesn't need
to be updated while holding the lock.
This change does both while holding the lock to keep reference count
tracking sane and correct.

SERVER-22554 Fix a reference counting bug in dhandles.

---

dist/s_string.ok
src/btree/bt_walk.c

@agorrod, @michaelcahill, for your review/consideration.
Please look at this one fairly closely, it's a minor change, but to the walk code.

SERVER-22784: Coverity analysis defect 77722: Unused value

---

src/evict/evict_lru.c
src/evict/evict_page.c

WT-2173: test/format cache stuck full

WT-2173: test/format cache stuck full 

---

examples/c/Makefile.am
examples/c/ex_all.c
examples/c/ex_event_handler.c
examples/java/com/wiredtiger/examples/ex_all.java
src/docs/error-handling.dox
src/docs/spell.ok
src/include/wiredtiger.in

WT-2107: Add example code including an event handler

---

src/session/session_dhandle.c

@agorrod, I tried a different approach, for your review/consideration.

WT-2423 Cleanup on error when opening a session handle.

---

dist/s_string.ok
src/evict/evict_lru.c

WT-2425: evict-btree read through performance drop

---

src/evict/evict_lru.c

Unless we get aggressive, putting internal pages on the LRU queue is
counterproductive.  That is particularly true for workloads that
transition to read-only, where some tables are not being queried.  In
that case, all of the leaf pages are evicted, and eviction wastes a lot
of effort walking and queuing internal pages that are not actually
evicted.

SERVER-22831 Queue more leaf pages than internal pages for eviction.

---

bench/wtperf/wtperf.c
src/cursor/cur_join.c

WT-2444: broken flag test in wtperf, whitespace

WT-2444: broken flag test in wtperf, whitespace

---

src/btree/bt_sync.c
src/txn/txn_ckpt.c

WT-2454: checkpoint_sync=false does not prevent flushes/sync to disk

---

bench/wtperf/runners/log.wtperf
build_posix/Make.subdirs
build_win/filelist.win
dist/filelist
dist/s_string.ok
dist/stat_data.py
src/conn/conn_cache.c
src/conn/conn_log.c
src/cursor/cur_log.c
src/evict/evict_lru.c
src/include/extern.h
src/include/mutex.h
src/include/stat.h
src/include/wiredtiger.in
src/log/log.c
src/log/log_slot.c
src/support/cond_auto.c
src/support/stat.c
test/manydbs/Makefile.am
test/manydbs/manydbs.c
test/manydbs/smoke.sh

Where the amount of time spent waiting varies depending on whether work is being done between timeouts.

WT-2318 Add implementation for auto adjusting condition variables.

---

test/recovery/truncated-log.c

WT-2469: Coverity 1352897: Integer overflowed argument

---

test/recovery/truncated-log.c

WT-2470: Coverity 1352898: Resource leak

---

test/readonly/readonly.c

WT-2468: Coverity 1352896: Explicit null dereferenced

---

test/fops/fops.c

Update the mod value to reflect the addition of a new operation.

WT-2467: Coverity 1352894: Logically dead code

---

test/readonly/Makefile.am
test/readonly/readonly.c

WT-2466: Coverity 1352893 Buffer not null terminated

---

src/btree/bt_cursor.c
src/schema/schema_truncate.c

SERVER-23040: Coverity analysis defect 98151: Dereference after null check

---

src/async/async_op.c
src/btree/bt_discard.c
src/btree/bt_read.c
src/btree/bt_slvg.c
src/btree/bt_split.c
src/conn/conn_open.c
src/cursor/cur_join.c
src/log/log.c
src/lsm/lsm_tree.c
src/meta/meta_ckpt.c
src/os_posix/os_stdio.c
src/packing/pack_stream.c
src/schema/schema_open.c

WT-2494: review calls to __wt_free, plus minor bug in an error path.

---

dist/s_string.ok
src/btree/bt_cursor.c
src/btree/col_srch.c
src/cursor/cur_join.c
src/include/cursor.h
test/suite/test_bug008.py

@michaelcahill, for your review/consideration.

WT-2490: search_near() returns wrong key for column-store

---

src/lsm/lsm_tree.c
test/suite/test_drop.py

WT-2498 Fix a bug in LSM where table drop could hang.

---

src/txn/txn_ckpt.c

WT-2502 Free local allocation.

---

src/os_win/os_fs.c

WT-2522: Incorrect format code in message

---

src/include/extern.h
src/meta/meta_table.c
src/meta/meta_turtle.c
src/os_common/filename.c
src/os_common/os_fhandle.c
src/os_common/os_fs_inmemory.c
src/os_posix/os_fs.c
src/os_win/os_fs.c

@sueloverso, @agorrod: for your review/consideration.

WT-2525: in-memory configurations: miscellaneous cleanups

---

src/include/os.h

WT-2532: WT_STREAM_APPEND and WT_STREAM_LINE_BUFFER flag overlap.

---

src/os_win/os_fs.c

It introduced some odd failures on debug MongoDB builds. Switch to using fopen instead.

SERVER-23588 Stop using _open_osfhandle on Windows.

---

test/bloom/Makefile.am
test/cursor_order/Makefile.am
test/huge/Makefile.am
test/manydbs/Makefile.am
test/manydbs/manydbs.c
test/readonly/Makefile.am
test/recovery/Makefile.am
test/salvage/Makefile.am
test/salvage/salvage.c
test/thread/Makefile.am

WT-2508: test programs should remove test directories on the "clean" target

---

src/btree/bt_slvg.c

WT-2450: salvage releases pages, then explicitly evicts them.

---

src/btree/bt_split.c
src/conn/conn_cache_pool.c
src/conn/conn_log.c
src/cursor/cur_join.c
src/cursor/cur_std.c
src/evict/evict_lru.c
src/log/log.c
src/lsm/lsm_cursor.c
src/lsm/lsm_merge.c
src/utilities/util_backup.c
src/utilities/util_dump.c
src/utilities/util_main.c

@agorrod, for your consideration.

WT-2505: Review clang analyzer warnings

---

src/block/block_vrfy.c

WT-2520: WT_SESSION::verify should not alter tables

---

build_win/filelist.win
dist/filelist
src/include/extern.h
src/os_common/os_fhandle.c
src/os_common/os_fs_init.c
src/os_common/os_fs_inmemory.c
src/os_common/os_fs_stdio.c
src/os_posix/os_fs.c
src/os_win/os_fs.c

@agorrod, @michaelcahill, for your consideration.

WT-2540: Separate stream and file handle methods

---

bench/wtperf/wtperf.c
dist/stat_data.py
src/conn/conn_cache.c
src/evict/evict_lru.c
src/include/cache.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

See initial discussion in #2648.

WT-2546 Evict server decides whether or not to evict

---

examples/java/com/wiredtiger/examples/ex_all.java

WT-2556: typo in the Java example code

---

test/format/backup.c

WT-2557:  format test program should discard log files after incremental backup

---

src/cursor/cur_join.c

In a join cursor, a key that passes the conditions is in 'raw' format, and when the join cursor is not raw, it must be converted to 64bit in the recno case.
This occurs only for non-raw join cursors, which is why it wasn't detected by the test suite (Python is always in raw mode).  The case that fails is ex_schema, which does not produce any keys from the join when it fails.

WT-2549 Fix for recno keys in cursor joins

---

test/suite/test_reconfig02.py

@agorrod Please review this change for the reconfig02 failures.

WT-2562 Add sleep loop to adapt for slow machines like PPC.

---

src/reconcile/rec_write.c

See #2669 for discussion, this is an alternate approach to that branch.

WT-2565: limit the amount of data passed to raw compression

---

src/conn/conn_log.c

@keithbostic Please review this change.  I was able to repro the original segfault on my AWS box.

WT-2567 Check if logging is enabled for truncate.

---

src/cursor/cur_join.c
src/session/session_api.c

@ddanderson, some minor touch ups for your consideration.

WT-2570: Minor lint cleanups

---

test/format/config.c
test/format/recover.sh

WT-2572: don't select an in-memory format run if incompatible options configured

---

test/format/config.c

WT-2574: format doesn't free all allocated configure memory

---

src/reconcile/rec_write.c

WT-2577: core dump discarding non-existent addresses

---

src/btree/bt_split.c

WT-2576: variable-length column-store out-of-order return

---

src/reconcile/rec_write.c

@michaelcahill, I think this change is pretty safe, so I'm going to merge it after it passes the tests so we can get the stress tests going again.
Michael, would you please do a quick review next chance you get?

WT-2581: assert multi->disk_image == NULL

---

src/cursor/cur_join.c
test/suite/test_join01.py
test/suite/test_join08.py

This is a followup for WT-2360. Renaming and reordering functions (big diffs!), and some reorganization of test cases to use scenarios.  (Use this pull request instead of #2681)

WT-2571 Join code clean up

---

test/packing/Makefile.am
test/packing/intpack-test.c
test/packing/intpack-test2.c
test/packing/intpack-test3.c
test/packing/packing-test.c

While here switch from using asserts to test util functions.

WT-2595 Fix compiler warning in packing test.

---

test/format/backup.c
test/format/format.h
test/format/ops.c
test/format/t.c

WT-2615: Enabling checkpoints in test/format leads to reduced concurrency

---

src/config/config_collapse.c
src/cursor/cur_join.c
src/meta/meta_turtle.c
src/os_common/os_fstream.c

Ready for review/merge.
Dear reviewer: there's a complaint Coverity has where I can't spot the error, and I don't see why Coverity would get it wrong. If you have the time to take a look at it, it's [Coverity complaint 1355027](https://scan6.coverity.com/reports.htm#v27510/p10746). I've simplified the code in 224a88d to try and clarify the issue.

WT-2627: Coverity complaints

---

src/reconcile/rec_write.c
test/format/util.c

WT-2628: reconciliation can return without unlocking the page lock

---

bench/wtperf/config.c

WT-2651: Coverity 1355591 resource leak

---

dist/api_data.py
src/config/config_def.c
src/include/wiredtiger.in
src/session/session_api.c

WT-2646 - Allow drop without waiting for checkpoints

---

examples/c/ex_file_system.c
test/csuite/wt1965_col_efficiency/main.c
test/csuite/wt2246_col_append/main.c
test/utility/parse_opts.c
test/utility/test_util.h

@sueloverso, @agorrod, Coverity complaints about test/csuite.

Wt 2661 coverity

---

src/evict/evict_lru.c
src/include/cache.i

WT-2660 Fill in pct_full before returning.

---

src/log/log.c

(cherry picked from commit 6b3553003)
Backport - Open a local log file handle for sync.

WT-2559 Open a local log file handle for sync backport to MongoDB 3.0

---

src/conn/conn_dhandle.c
src/include/dhandle.h

This reverts commit fa4b0916bcbeca210f98d4dd0ee86fd199050c2b.

WT-2491 Revert - Remove the handle close_lock (#2745)

---

src/btree/bt_handle.c

@agorrod, some trivial lint from a recent change.

WT-2673 Stop automatically increasing memory page max

---

src/conn/conn_api.c
src/conn/conn_dhandle.c
src/include/connection.h
src/include/dhandle.h
src/include/extern.h
src/include/meta.h
src/meta/meta_table.c

@michaelcahill, @sueloverso, here are the metadata changes extracted out of #2711.

WT-2674 simplify metadata file check

---

src/evict/evict_lru.c

Add missing WT_WITH_PASS_LOCK with call to clear walks on shutdown.
Add an assertion in evict_clear_walk to confirm the lock is held.

WT-2685 Fix clear walk hazard pointer failure.

---

src/support/global.c
test/format/bdb.c

WT-2682 add option to configure WiredTiger with strict compiler flags

---

src/conn/conn_dhandle.c
src/evict/evict_lru.c
src/include/cache.h

@michaelcahill or @agorrod This is ready for review.  I converted the flag into an atomically set counter.  I have not been able to reproduce the original hang running the recover.sh script before the fix however, so I haven't been able to verify the fix of the deadlock.

WT-2698 Change flag into atomically manipulated field to avoid deadlock.

---

src/log/log_slot.c
test/recovery/random-abort.c

@michaelcahill Not ready to merge as I don't have the test committed yet, but this is the code fix.

WT-2696 Wait if we find an unbuffered flag without the size set yet.

---

test/csuite/wt2447_join_main_table/main.c
test/csuite/wt2592_join_schema/main.c

@ddanderson, a couple of Coverity complaints in the csuite join tests.

WT-2712 Coverity 1356928 and 1356929: ASSERT_SIDE_EFFECT

---

test/csuite/wt2447_join_main_table/main.c
test/recovery/random-abort.c

@sueloverso, @ddanderson, some lint in the csuite test programs.

WT-2714 lint

---

src/docs/custom-file-systems.dox

WT-2713 document WT_PANIC so pluggable filesystems can panic.

---

src/conn/conn_cache_pool.c

WT-2709 connection reconfigure segfault in __wt_conn_cache_pool_destroy

---

src/evict/evict_lru.c
src/include/cache.h

@agorrod or @michaelcahill please review this change to detect the stuck cache, dump it and abort.  I tested it with the failing CONFIG in the ticket and it correctly dumped the cache.

WT-2704 Fix bug in diag code detecting duration of stuck cache.

---

src/block/block_ext.c

WT-2732 Coverity analysis defect 99665: Redundant test

---

bench/wtperf/runners/multi-btree-zipfian-populate.wtperf
bench/wtperf/runners/multi-btree-zipfian-workload.wtperf
bench/wtperf/wtperf.c
bench/wtperf/wtperf_opt.i
dist/stat_data.py
src/btree/bt_stat.c
src/btree/bt_sync.c
src/conn/conn_cache.c
src/docs/wtperf.dox
src/evict/evict_lru.c
src/include/btree.h
src/include/btree.i
src/include/cache.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
tools/wtstats/stat_data.py

Randomize visits to trees that use a tiny fraction of the cache.

WT-2729 Focus eviction on the largest trees in cache.

---

src/conn/conn_dhandle.c
src/conn/conn_sweep.c
src/evict/evict_lru.c

Cherry picks of WT-2313 and WT-2434

WT-2733 Backport fixes for races between eviction and dead handle cleanup

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/include/cursor.i

WT-2730 column-store incorrectly matches key slots on new pages

---

src/log/log.c

@agorrod Please review this change.  It is a small piece to reduce an unnecessary read/verify of the log file header on every `log_flush` call.

WT-2728 Only verify the log file header during recovery.

---

bench/wtperf/runners/multi-btree-zipfian-populate.wtperf
bench/wtperf/runners/multi-btree-zipfian-workload.wtperf

@agorrod Please review these changes to the new zipfian workload.  Looking at that config, I believe there are errors and these changes reflect the actual intent.

WT-2752 Fix errors in wtperf config

---

src/conn/conn_stat.c

If there's no server running, discard any configuration information so
we don't leak memory during reconfiguration.

WT-2711 Change statistics log configuration options

---

src/btree/bt_split.c
src/cursor/cur_backup.c
src/cursor/cur_config.c
src/cursor/cur_ds.c
src/cursor/cur_dump.c
src/cursor/cur_file.c
src/cursor/cur_log.c
src/cursor/cur_metadata.c
src/cursor/cur_stat.c
src/include/cursor.h
src/include/extern.h
src/lsm/lsm_cursor.c
src/reconcile/rec_write.c

@sueloverso, I think this one is probably yours -- there's some tricky stuff in here, happy to talk through anything that's confusing.

WT-2693 Check open_cursor error paths for consistent handling

---

src/cursor/cur_backup.c

@agorrod, for your consideration/review.
FTR, here's the original commit: 69bc7d1

WT-2759 Releasing the hot-backup lock doesn't require the schema lock.

---

src/cursor/cur_table.c
src/include/wiredtiger.in
test/suite/test_bug016.py

WT-2757 Column tables behave differently when column names are provided

---

tools/wtstats/wtstats.py

@keithbostic Please review this small change to handle a Y in the wtperf monitor file.

WT-2762 Handle 'Y' from wtperf monitor file.

---

src/async/async_api.c

@keithbostic Thanks for the prompt to make this change.  Please review.  I was able to reproduce the hang, forcing an error, and confirm this fixes it.

WT-2353 Don't flush async ops if threads aren't started.

---

dist/s_string.ok
examples/c/ex_file_system.c
src/block/block_open.c
src/btree/bt_huffman.c
src/conn/conn_api.c
src/conn/conn_stat.c
src/cursor/cur_backup.c
src/include/extern.h
src/include/os_fs.i
src/include/os_fstream.i
src/include/wiredtiger.in
src/log/log.c
src/lsm/lsm_work_unit.c
src/meta/meta_track.c
src/meta/meta_turtle.c
src/os_common/filename.c
src/os_common/os_fhandle.c
src/os_common/os_fs_inmemory.c
src/os_common/os_fstream.c
src/os_posix/os_fs.c
src/os_win/os_fs.c
src/schema/schema_rename.c

WT-2760 Backup file removal requires ordering, so needs to sync the directory

---

dist/api_data.py
src/config/config_def.c
src/conn/conn_ckpt.c
src/docs/upgrading.dox
src/include/connection.h
src/include/extern.h
src/include/wiredtiger.in
src/txn/txn_ckpt.c
test/format/wts.c
test/suite/test_reconfig01.py

Remove the checkpoint=(name=FOO) configuration.

WT-2738 checkpoint=(name=FOO) configuration

---

src/include/wiredtiger.in
src/log/log.c

@keithbostic Please review these minor comment and doc changes.

WT-2782 Minor text changes for file system functions

---

bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
bench/wtperf/wtperf_throttle.c

@agorrod, @sueloverso, for review/merge.

WT-2737 Fix a set of places where we ignored the return value of a function.

---

src/reconcile/rec_write.c

@agorrod, @michaelcahill, for your review/consideration.

WT-2737 Scrub dirty pages rather than evicting them

---

src/evict/evict_page.c

WT-2737 page scrubbing: more fixes

---

bench/wtperf/runners/log.wtperf

Self-review.  Remove comment from config file.

WT-2772 Remove bigval run.

---

src/evict/evict_lru.c
src/txn/txn_ckpt.c

@michaelcahill, Sue & I were talking about the leaked memory and using the WT-2764 branch, so I built it. Here's some random stuff, hope it saves you 5 minutes. :)

WT-2764 Release checkpoint transaction before syncing

---

src/evict/evict_lru.c
src/include/btree.i

Reverts some of 0136888b3b677d67ff929c6f5b1f8d6aa6793b13.

WT-2725 Prevent eviction of read-only pages with recent updates.

---

src/btree/bt_sync.c
src/txn/txn_ckpt.c

Only update btree->checkpoint_gen during a full checkpoint operation
that is holding the checkpoint lock.  Otherwise, updates in the
metadata by a running checkpoint can pass the "visible_all" test and be
evicted.
Followup to WT-2798.

WT-2801 Prevent eviction of metadata updates by a running checkpoint.

---

src/txn/txn_ckpt.c

Also fix the statistic measuring the total time for checkpoint
scrubbing.

WT-2764 Fix a bug calculating the dirty percentage of cache.

---

src/txn/txn_ckpt.c
test/suite/test_reconfig03.py

It can be zero during reconfigure.

WT-2812 Verify cache_size before dividing.

---

src/include/txn.i

Also make sure there is always a read barrier between reading the
oldest ID and the pinned checkpoint ID.

WT-2811 Include the checkpoint transaction if there is no btree.

---

bench/wtperf/wtperf_opt.i
bench/wtperf/wtperf_truncate.c
src/docs/wtperf.dox

Enabled via new truncate_single_ops option.

WT-2814 Add new single op truncate mode to wtperf

---

src/include/btree.i

WT-2826 clang38 false positive on uninitialized variable.

---

src/block/block_ckpt.c
src/block/block_ext.c
src/block/block_slvg.c
src/block/block_write.c
src/conn/conn_log.c
src/include/error.h
src/include/log.h
src/log/log.c
src/os_common/os_fhandle.c
src/os_common/os_fs_inmemory.c

Changes to support file systems without file truncate support.

WT-2823 support file handles without a truncate method

---

test/suite/test_config04.py

WT-2832 Python test uses hard-coded temporary directory

---

src/cursor/cur_metadata.c

@ddanderson, for your review/consideration.

WT-2839 lint: Ignoring return value of function

---

src/cursor/cur_metadata.c

@ddanderson, for your review/consideration.

WT-2840 clang analysis: garbage values

---

dist/api_config.py
src/config/config_def.c

@michaelcahill, would you be willing to take a fast look at the changes here? I think it's correct, but you wrote all of this code and I'd take comfort from your agreement.
cc: @agorrod

WT-2678 The metadata should not imply that an empty value is true

---

build_posix/configure.ac.in
build_win/wiredtiger_config.h
dist/s_win
src/os_posix/os_fs.c

WT-2857 POSIX ftruncate calls should be #ifdef'd HAVE_FTRUNCATE

---

src/os_posix/os_fallocate.c

@keithbostic Please review this fix that is fallout from the ftruncate changes.

WT-2857 Check for ftruncate function.

---

test/csuite/wt2853_perf/main.c

Added testutil_assert for failure condition and reduced test run length. Also cosmetic changes: remove unneeded vars, var declaration reordering, var renaming.

WT-2853 test improvements

---

src/include/btree.i

SERVER-25843 Coverity analysis defect 99856: Redundant test

---

dist/s_prototypes
src/btree/bt_slvg.c
src/include/misc.i
src/include/os_fhandle.i
src/include/os_fs.i
src/include/os_fstream.i

WT-2871 __wt_verbose has the wrong GCC format attributes

---

bench/wtperf/config.c
bench/wtperf/config_opt.h
bench/wtperf/doxy.c
bench/wtperf/idle_table_cycle.c
bench/wtperf/misc.c
bench/wtperf/track.c
bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
bench/wtperf/wtperf_opt.i
bench/wtperf/wtperf_truncate.c
dist/s_docs

Reverts wiredtiger/wiredtiger#2971

Revert "WT-2842 split wtperf's configuration into per-database and per-run parts"

---

src/conn/conn_ckpt.c
src/include/connection.h
src/include/extern.h
src/log/log.c

WT-2885 __wt_checkpoint_signal lint

---

src/include/extern.h
src/include/misc.i
src/support/err.c

WT-2878 Verbose changes affected performance

---

src/btree/bt_split.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/reconcile/rec_track.c
src/reconcile/rec_write.c
src/support/thread_group.c

WT-2881 Add -Wpedantic to clang compiler warning flags

---

bench/wtperf/runners/mongodb-secondary-apply.wtperf
bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
bench/wtperf/wtperf_opt.i
src/docs/wtperf.dox

In an attempt to be able to simulate secondary replica nodes.

WT-2876 Add an oplog like ability to wtperf utility.

---

test/utility/misc.c

WT-2896 Coverity #1362535: resource leak

---

src/block/block_ckpt.c
src/block/block_mgr.c
src/include/extern.h

WT-2897 Checkpoints can become corrupted on failure

---

build_posix/configure.ac.in
examples/c/ex_event_handler.c
src/checksum/arm64/crc32-arm64.c
test/readonly/readonly.c

WT-2900 scons gcc flags collide with ARM8 CRC32 implementation

---

src/block/block_write.c

WT-2912 make --enable-strict run on the zseries test box

---

build_posix/aclocal/strict.m4
build_posix/configure.ac.in
test/format/rebalance.c

WT-2911 add support for gcc6

---

test/csuite/wt2695_checksum/main.c

WT-2914 Added explicit call to initialize WT library to satisfy some linkers

---

src/evict/evict_lru.c

We could be in a situation with a tiny number of pages in cache, all of
which are already queued.  The queue needs to be re-sorted so that some
of those entries can become candidates.  This caused hangs in some
test/format configs.

WT-2913 Re-sort eviction queues if we find no new candidates.

---

test/suite/test_compact01.py

@agorrod, @daveh86, for your review/consideration.

WT-2874 test_compact01 can throw WT_ROLLBACK

---

src/btree/bt_compact.c
src/btree/bt_walk.c

@michaelcahill, @agorrod, for your review/consideration.

WT-2923 heap-use-after-free on address in compaction

---

test/csuite/wt2719_reconfig/main.c

@agorrod, for your review/consideration, I thought this might be a reasonable way to attack the problem in WT-2864.

WT-2864 Reconfiguring the checkpoint server can lead to hangs

---

src/include/thread_group.h

WT-2925 WT_THREAD_PANIC_FAIL is a WT_THREAD structure flag

---

src/conn/conn_api.c

WT-2926 WT_CONNECTION.reconfigure can attempt unlock of not-locked lock

---

src/evict/evict_lru.c
src/include/btree.i
src/include/cache.h

@michaelcahill, for your review/consideration.
There are a couple of different things in here that I noticed reading the code, you may want to cherry-pick them into whatever you end up merging.

WT-2924 Ensure we are doing eviction when threads are waiting for it

---

bench/wtperf/config.c
bench/wtperf/idle_table_cycle.c
bench/wtperf/misc.c
bench/wtperf/track.c
bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
bench/wtperf/wtperf_throttle.c
bench/wtperf/wtperf_truncate.c
dist/s_string.ok
src/conn/conn_cache.c
test/utility/test_util.h

@agorrod, the next chunk of work, there should be no real changes in this one.

WT-2858 rename wtperf's CONFIG structure

---

dist/s_string.ok
src/btree/bt_stat.c
src/evict/evict_stat.c
src/include/extern.h
test/csuite/wt2403_lsm_workload/main.c
test/utility/test_util.h

WT-2974 lint

---

src/os_posix/os_time.c

WT-2988 __wt_epoch potentially returns garbage values.

---

src/cursor/cur_table.c
test/suite/test_bug017.py

WT-2987 opening a cursor on an incomplete table drops core

---

src/conn/conn_stat.c
src/include/extern.h
src/lsm/lsm_manager.c
src/os_posix/os_mtx_cond.c
src/os_win/os_mtx_cond.c

WT-2945 Occasional hang running reconfigure fuzz test

---

src/cursor/cur_backup.c
test/suite/test_backup06.py

Reduce number of tables created by half because zseries jenkins job hit the open file limit.

WT-2968 Fix Jenkins failures from merge.

---

src/include/extern.h
src/include/mutex.h
src/support/mtx_rw.c
src/txn/txn.c

Even if it appears to be available, we're burning CPU.

SERVER-26753 Don't spin indefinitely trying to get a read lock.

---

dist/s_string.ok
src/log/log.c
test/recovery/random-abort.c
test/recovery/smoke.sh

Not yet ready to merge.  Just pushed the test changes to reproduce the problem.

WT-3000 Fix missing records at end of previous log file

---

src/block/block_ckpt.c
src/block/block_read.c
src/block/block_slvg.c
src/conn/conn_api.c
src/cursor/cur_config.c
src/log/log.c
src/os_common/os_fs_inmemory.c
src/os_posix/os_dir.c
src/os_posix/os_fallocate.c
src/os_posix/os_fs.c
src/os_win/os_dir.c
src/txn/txn_ckpt.c
src/txn/txn_recover.c
test/recovery/random-abort.c

WT-3018 lint

---

test/suite/test_compact02.py

Not quite ready for merge. Will test using new wiredtiger-linux-no-ftruncate jenkins job.

WT-3016 Change test to allow it to work without ftruncate support

---

src/btree/bt_walk.c

WT-3030 alternative loop for finding the matching slot.

WT-3030 alternative loop for finding the matching slot.

---

src/btree/bt_debug.c
src/cursor/cur_json.c
src/include/misc.h
src/include/misc.i
src/support/hex.c

WT-3051 Remove external __wt_hex symbol.

WT-3051 Remove external __wt_hex symbol.

---

build_posix/Make.subdirs
dist/s_string.ok
test/format/Makefile.am
test/format/backup.c
test/format/bdb.c
test/format/bulk.c
test/format/compact.c
test/format/config.c
test/format/config.h
test/format/format.h
test/format/lrt.c
test/format/ops.c
test/format/salvage.c
test/format/smoke.sh
test/format/t.c
test/format/util.c
test/format/wts.c
test/utility/Makefile.am
test/utility/misc.c
test/utility/parse_opts.c
test/utility/test_util.h
test/utility/thread.c

WT-3049 Backport test format

---

bench/wtperf/idle_table_cycle.c
lang/java/wiredtiger.i
lang/python/wiredtiger.i
src/include/extern.h
src/include/extern_posix.h
src/os_common/os_alloc.c
src/os_posix/os_sleep.c
src/support/err.c

Reverts wiredtiger/wiredtiger#3174

WT-3053 Revert: Python and Java support use internal WiredTiger functions

---

lang/java/src/com/wiredtiger/db/PackOutputStream.java

WT-3054 Fix Java test compilation errors

---

dist/s_void
src/async/async_op.c
src/block/block_compact.c
src/btree/bt_debug.c
src/cursor/cur_json.c
src/include/txn.i
src/lsm/lsm_cursor.c
src/lsm/lsm_tree.c
src/os_win/os_fs.c
src/os_win/os_utf8.c
src/reconcile/rec_track.c
src/reconcile/rec_write.c
src/session/session_api.c
src/txn/txn_nsnap.c

WT-3066 lint

---

api/leveldb/basho/perf_count.cc
api/leveldb/hyper_wt.cc
api/leveldb/leveldb_wt.h

WT-3069 LevelDB APIs no longer build.

WT-3069 LevelDB APIs no longer build.

---

src/os_posix/os_mtx_cond.c

Flush the caller's flags before reading the condition information, we may not write anything before joining the exiting thread, and a write-barrier() would not necessarily have any effect.

WT-3078 test reconfiguration hang in the statlog server.

---

ext/datasources/helium/helium.c
ext/test/kvs_bdb/kvs_bdb.c

Fix some places using data sources to include alter.  Found after merge.

WT-283 Fix data source examples to include alter.

---

build_posix/aclocal/options.m4
lang/python/Makefile.am
src/cursor/cur_std.c
src/include/extern.h

WT-3092 Quiet autogen.sh, change local Python build permissions

WT-3092 Quiet autogen.sh, change local Python build permissions

---

test/format/config.c
test/format/config.h
test/format/format.h

test bug: format is weighted to delete, insert, then write operations.

WT-3100 test bug: format is weighted to delete, insert, then write operations.

---

dist/s_docs
src/docs/spell.ok
src/docs/tune-page-size-and-comp.dox
src/evict/evict_lru.c
src/utilities/util_dump.c

lint: static function declarations, non-text characters in documentation

WT-3099 lint: static function declarations, non-text characters in documentation

---

src/evict/evict_lru.c

WT-2898 Improve performance of eviction-heavy workloads by dynamically controlling the number of eviction threads

---

SConstruct
build_posix/Make.base
src/docs/command-line.dox
src/docs/upgrading.dox
src/utilities/util.h
src/utilities/util_main.c
src/utilities/util_truncate.c
test/suite/test_util14.py

Not ready for review yet. Need to fix some comments and update documentation.

WT-3106 Add wt utility truncate operation

---

test/suite/test_util15.py
test/suite/test_util16.py
test/suite/test_util17.py

Not 100% ready yet.
I need to think about what else can be done with stats.

WT-3110 New WT Utility tests

---

test/recovery/random-abort.c

@agorrod Please review this change to the random-abort test program to wait for the table to exist before starting the timeout waiting.  It runs fine on my systems.  I manually added in a sleep at the beginning of the child process to simulate the delay and reproduce the original problem and test this change.

WT-3118 Protect test against unexpectedly slow child start.

---

bench/wtperf/wtperf.c
test/recovery/random-abort.c
test/recovery/truncated-log.c

@sulabhM, for your consideration.

WT-3134 Coverity scan reports 1368529 and 1368528

---

build_posix/Make.subdirs
dist/s_void
ext/test/fail_fs/Makefile.am
ext/test/fail_fs/fail_fs.c
src/conn/conn_handle.c
src/conn/conn_open.c
src/include/extern.h
test/csuite/Makefile.am
test/csuite/wt3120_filesys/main.c

@michaelcahill, this is ready for review.  I have a test case (extension file system + caller), but it's somewhat integrated in work I'm doing for WT-2909.  If you'd like it as part of this one, I can include it.

WT-3120 Fix ordering problem in connection_close for custom filesystem loaded via shared lib

---

src/log/log.c

@ddanderson Please review this fix for the error-path problem you reported.

WT-3156 Add check in assertions for errors.

---

src/evict/evict_lru.c

In particular, don't have the eviction server give up all walks each
time it is interrupted, and only wait for requesting threads to make
progress: don't go to sleep.

WT-3150 Reduce impact of checkpoints on eviction.

---

src/txn/txn_ckpt.c

@keithbostic Please review this new pull request for the checkpoint error path.  I believe it needs to go into develop instead of @ddanderson 's branch.  Otherwise it is the same as the other branch.

WT-3157 Fix checkpoint error path

---

src/txn/txn_ckpt.c

@agorrod Please review this more aggressive branch (since the other was merged).

WT-3157 More aggressive error handling.

---

src/btree/bt_split.c

Review split barriers.
@michaelcahill, here is my suggested change for the barriers in the split code.

WT-3170 Change how eviction walk point is saved during walk.

---

src/btree/bt_split.c
test/csuite/wt3135_search_near_collator/main.c

WT-3174 Coverity/lint cleanup

---

ext/test/fail_fs/fail_fs.c
test/csuite/wt2909_checkpoint_integrity/main.c

Make gcc 4.7 work again, general lint.

WT-2909 Create automatable test verifying checkpoint integrity after errors

---

test/csuite/wt2909_checkpoint_integrity/main.c

Also fixed some uint64 values/parameters that were declared as uint32.

WT-3180 bug fix: disable long tests in the top-level main program, disable core files for subtests

---

ext/test/fail_fs/fail_fs.c

This should fix the clang address sanitizer build failure.

WT-3179 test bug: clang sanitizer failure in fail_fs

---

src/evict/evict_lru.c
src/include/btree.h
src/include/cache.h
src/log/log_slot.c
test/bloom/test_bloom.c
test/checkpoint/test_checkpoint.c
test/checkpoint/test_checkpoint.h
test/csuite/wt3184_dup_index_collator/main.c
test/cursor_order/cursor_order.c
test/fops/t.c
test/format/config.c
test/format/format.h
test/format/ops.c
test/format/t.c
test/format/wts.c
test/huge/huge.c
test/manydbs/manydbs.c
test/readonly/readonly.c
test/recovery/random-abort.c
test/recovery/truncated-log.c
test/salvage/salvage.c
test/thread/t.c
test/utility/misc.c
test/utility/parse_opts.c
test/utility/test_util.h

Alex, this one needs your review because of dfee9c8. I think your original code is legal, but requires multiple casts to/from "ints" because of the default types for arithmetic operations. It was making my head hurt trying to figure it out, so I turned it into a switch statement.

WT-3191 lint

---

src/btree/bt_cursor.c
src/btree/bt_handle.c
src/btree/bt_random.c
src/btree/bt_rebalance.c
src/btree/bt_slvg.c
src/btree/bt_vrfy.c
src/btree/bt_walk.c
src/evict/evict_file.c
src/evict/evict_lru.c
src/include/btree.h
src/include/extern.h
src/include/session.h
src/session/session_api.c
src/session/session_dhandle.c

@agorrod, can we return not-found on this failure instead of success?

WT-3193 Close a race between verify and the eviction server

---

src/btree/bt_cursor.c
src/btree/bt_handle.c
src/btree/bt_read.c
src/evict/evict_file.c
src/evict/evict_lru.c
src/include/btree.h
src/include/btree.i

@michaelcahill, for your consideration.

WT-3203 bulk-load state changes can race

---

src/btree/bt_split.c

We use split generations to detect when readers may be looking at
structures that are replaced by a split.  For correctness, we should
only increment the global split generation *after* a split becomes
public.  Only then can we safely check that no thread is still reading
with the old generation.
Previously, a split could increment the global split generation, then a
thread could start reading with the new split generation but see the old
index structure.
This issue was introduced by WT-3088, where we wanted a way to ensure
that newly-allocated pages don't split until it is safe.  That is solved
here by having the split code pin a split generation in the ordinary way
(without allocating a new one) for the duration that splits of new
pages need to be prevented.

WT-3206 Fix a race allocating split generations.

---

src/txn/txn_ckpt.c

@michaelcahill Here's the change we discussed.  Please review.

WT-3207 Use config to determine checkpoint force value.

---

src/meta/meta_turtle.c

Panic if there's an error in reading/writing from/to the turtle file, there's no point in continuing. This change avoids user confusion when the turtle file is corrupted or zero'd out by the filesystem.

SERVER-28168 Cannot start or repair mongodb after unexpected shutdown.

---

src/include/mutex.h
src/include/mutex.i

@agorrod and @michaelcahill Here are my suggested changes for the spin lock fix.

WT-3250 Have one function initializing the WT portion of the spinlock.

---

test/suite/test_reconfig02.py

WT-3254 Fix typo in reconfig string

---

src/support/thread_group.c

@keithbostic or @agorrod Do you want to review this?

WT-3266 Drop lock while joining threads.

---

src/include/cache.i

Also don't check for a full cache while holding the table lock (we're
likely reading the metadata in that case, just being extra careful).

WT-3262 Don't check if the cache is full when accessing metadata.

---

src/lsm/lsm_cursor.c

If an update, remove or reserve operation required a search it was possible for a race with eviction to cause a segfault between the lookup and requested operation.

WT-3275 Fix a bug in LSM cursor semantics.

---

src/os_win/os_fs.c
src/support/err.c

Replacement for pull-request #3392.

WT-3288 fix error codes for event_handler to be consistent in file operations

---

examples/java/com/wiredtiger/examples/ex_cursor.java
lang/java/Makefile.am
lang/java/wiredtiger.i
lang/python/wiredtiger.i
test/suite/test_cursor12.py

@keithbostic, here's the Java API.

WT-2972 Make partial updates more efficient - Java support

---

bench/workgen/runner/example_simple.py
bench/workgen/runner/example_txn.py
bench/workgen/runner/insert_test.py
bench/workgen/runner/multi_btree_heavy_stress.py
bench/workgen/runner/runner/latency.py
bench/workgen/runner/small_btree.py
bench/workgen/workgen/__init__.py
dist/s_copyright.list

Fix up some copyright notices.

WT-3142 Add a workload generator application

---

dist/api_err.py
dist/s_style
examples/c/ex_event_handler.c
src/docs/error-handling.dox
src/include/wiredtiger.in

@agorrod, @ddanderson, for your consideration, the additional error handling documentation we talked about.

WT-3314 clarify error handling

---

src/conn/conn_log.c
src/include/extern.h
src/log/log.c
src/log/log_slot.c
src/txn/txn_recover.c
test/suite/test_txn09.py
test/suite/test_txn16.py

WT-3264 Fix log file cleanup when toggling logging.

---

src/os_common/os_fhandle.c

Closing the file handles that remain open at database close will attempt to unlock a lock that's not currently held.

WT-3343 WiredTiger database close can attempt unlock of a lock that's not held.

---

.gitignore
build_posix/aclocal/strict.m4
dist/s_copyright.list
src/block/block_compact.c
src/block/block_ext.c
src/evict/evict_lru.c
src/include/error.h
src/include/os_windows.h
src/log/log.c
src/reconcile/rec_write.c
src/support/huffman.c
test/format/wts.c
test/utility/test_util.h
test/windows/windows_shim.h

@michaelcahill, the Windows complaints have been growing over the past year or so, and I haven't done a lint/housekeeping run in a few weeks, so I did a pass.
@markbenvenuto, Would you please review this branch? I've built this on `windows-64-vs2015-small` and `windows-64-vs2013-compile`.

WT-3348 Lint, Windows warnings.

---

src/log/log.c

self reviewing once PR tests are done.

WT-3351 Fix assertion condition.

---

bench/workgen/runner/runner/__init__.py
bench/workgen/runner/runner/core.py
bench/workgen/wtperf.py

@agorrod, this could be merged or not, your choice.  There is plenty more potential work to be done on this ticket, but it may be quite useful as is.  wtperf.py currently generates valid Python code for 17 out of 59 of wtperf/runners/*.wtperf.  The others fail gracefully, complaining about wtperf directives that we don't yet support.  I've run a few of the good ones, they run successfully.  I think the next step should be to pick one or two Jenkins jobs that currently use wtperf that we could run in parallel and get that set up.

WT-3326 Added wtperf.py script to run wtperf files.

---

bench/workgen/runner/workgen_stat.sh
bench/workgen/workgen.cxx
bench/workgen/workgen.h
bench/workgen/workgen_func.c
bench/workgen/workgen_func.h
bench/workgen/workgen_int.h

Also added a script to merge workgen and WT outputs.

WT-3346 create JSON output for latency sampling.

---

src/reconcile/rec_write.c

Reverts wiredtiger/wiredtiger#3453

Revert "WT-3251 remove interim buffer when splitting during reconciliation "

---

src/btree/bt_split.c

@agorrod, @michaelcahill: I believe this is a minimal fix for WT-3373.

WT-3373 Access violation due to a bug in internal page splitting

---

SConstruct
examples/c/Makefile.am
examples/c/ex_all.c
examples/c/ex_smoke.c

Fix a typo in some not-normally-compiled code.

WT-1939 Improve error handling in example code

---

src/txn/txn.c
src/txn/txn_timestamp.c

@keithbostic Please review this change.  I looked at all calls to `wt_timestamp_set*` and the two we both already found were the only ones missing the locking.  One thing to note, in `wt_txn_release` I left in the `WT_PUBLISH` and the barrier even though we're holding the lock.
@milkie You could try this branch with your test and see if it solves your problem.  Also let me know if you think including some new assertions would be helpful going forward.  Adding them into this change would be easy and convenient.

WT-3415 Add locking around setting txn_state timestamp

---

src/include/extern.h
src/include/txn.h
src/txn/txn.c
src/txn/txn_ckpt.c
src/txn/txn_timestamp.c

Reverts wiredtiger/wiredtiger#3511

Revert "WT-3381 Improve timestamp concurrency."

---

dist/api_data.py
src/evict/evict_lru.c
src/include/wiredtiger.in
src/txn/txn_timestamp.c

@agorrod, there's a bug in the new timestamp code (b06db73), so I did "full-build Friday" a few days early.

WT-3439 lint cleanup

---

src/session/session_api.c
test/suite/test_readonly03.py

@agorrod Please review this small change to correctly handle alter in a readonly connection.

WT-3433 Add support for alter and readonly.  Add test case.

---

test/suite/test_timestamp03.py

@agorrod This case didn't seem covered in any of the other tickets.  I added a phase to the timestamp test that makes a backup without first doing a checkpoint, recovering from the previous checkpoint.  Please review.

WT-3463 Add test phase to take backup without a checkpoint.

---

src/docs/upgrade.dox

@keithbostic Here are some text changes for upgrade/downgrade in the docs.  Please review.

WT-3422 Add upgrade/downgrade doc text

---

.gitignore
src/btree/bt_split.c
src/evict/evict_lru.c
src/evict/evict_stat.c
src/include/bitstring.i
src/include/btmem.h
src/include/buf.i
src/include/serial.i
src/log/log.c
src/session/session_api.c
src/support/time.c

WT-3467 Minor lint/cleanup

---

src/btree/bt_read.c

@agorrod, a minor change that occurred to me that might be helpful in some workloads.
Feel free to simply discard the branch without discussion if you don't think it's worth doing.

WT-3486 Discard obsolete updates as part of re-instantiating updates based on the lookaside table.

---

src/btree/bt_read.c

Reverts wiredtiger/wiredtiger#3557

Revert "WT-3486 Discard obsolete updates as part of re-instantiating updates based on the lookaside table."

---

src/lsm/lsm_merge.c

when choosing chunks for a merge.

WT-3481 Fix an LSM bug where expected chunks size could be overestimated

---

dist/api_data.py
examples/c/ex_all.c
src/config/config_def.c
src/include/wiredtiger.in
src/txn/txn_timestamp.c
test/suite/test_timestamp02.py

Reverts wiredtiger/wiredtiger#3562

Revert "WT-3489 Add an API to set the tracked commit_timestamp."

---

src/include/txn.i
src/txn/txn.c
test/suite/test_timestamp05.py

@milkie Let me know if this fixes your issue as well.  I've repro'ed with @michaelcahill 's test and reviewed the proposed fix.  If it works for you then I'll get this merged.

WT-3483 Keep timestamps out of metadata.

---

test/csuite/time_shift_test.sh

This script will test the WT for clock shift.
Currently this is standalone and need to decide 
1. When this test to be initiated
a) make check
b) separate test job
2. How to handle libfaketime source / libraries on which this test is dependent.

WT-3459 Clock shifting WT test

---

dist/api_data.py
src/include/wiredtiger.in
src/txn/txn_timestamp.c
test/suite/test_timestamp01.py

@michaelcahill or @agorrod Please review.

WT-3528 Txn must be running to call timestamp_transaction

---

test/suite/test_timestamp07.py

self-review once PR testing is done.

WT-3525 Disable 500 keys until LAS and reconciliation changes complete.

---

src/include/connection.h

A good hash function should give us good distribution no matter what modulo we use, and we use a good hash function.

WT-3527 Use power of two hash table size.

---

src/include/connection.h
src/txn/txn_rollback_to_stable.c

Reverts wiredtiger/wiredtiger#3623

Revert "WT-3544 Fix memory stomping during rollback_to_stable."

---

src/conn/conn_sweep.c

We need to acquire the global table lock before the table handle lock.

WT-3549 Fix a deadlock sweeping table handles.

---

src/txn/txn_ckpt.c
test/suite/test_timestamp03.py
test/suite/test_timestamp06.py
test/suite/test_timestamp07.py
test/suite/test_timestamp08.py

WT-3511 timestamp partway change multistep transaction

---

src/block/block_ckpt.c

@agorrod, this was an error I didn't expect to happen, obviously it does. This is a fix to ensure we don't panic in this case (there's no reason to panic as far as the block manager is concerned). I'm chasing the root cause, as I said, I didn't expect this failure.
Update: the root cause is discussed in the [JIRA ticket](https://jira.mongodb.org/browse/WT-3581?focusedCommentId=1671385&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1671385).
I believe this change is correct and ready for merge.

WT-3581 format: unexpected checkpoint resolution

---

src/log/log.c

(cherry picked from commit d4986a2b851a7e507c3748d660845cc32b21e3c1)

WT-3351 Fix assertion condition. (#3452)

---

src/conn/conn_reconfig.c

@agorrod Please review.  I found this by inspection while looking at the compatibility code for another ticket.

WT-3606 Set connection fields after error checking.

---

src/txn/txn_timestamp.c
test/suite/test_timestamp09.py

We don't actually need commit timestamps to move forward within a transaction as long as the first timestamp used is the oldest one (it determines the transaction's order in a list sorted by timestamp).

WT-3610 Only require that the first commit_timestamp is oldest.

---

.gitignore
dist/s_copyright.list
dist/style.py
src/btree/bt_read.c
src/btree/bt_split.c
src/evict/evict_lru.c
src/reconcile/rec_write.c
src/txn/txn_ext.c
test/csuite/wt2909_checkpoint_integrity/main.c
test/format/format.h
test/format/ops.c
test/format/t.c

@nehakhatri5, since you're on the East Coast, can I ask you for review, please?
Thanks!

WT-3614 Full-build Friday lint

---

src/reconcile/rec_write.c

This can't happen at snapshot isolation (where only one update can be uncommitted per record), but can happen at lower isolation levels.  Since update/restore has to discard updates from the stable (on-page) update and older, it can't cope with an uncommitted update after the stable update.

WT-3617 Fail update/restore with uncommitted updates after stable.

---

src/txn/txn_timestamp.c
test/suite/test_timestamp01.py

Reverts wiredtiger/wiredtiger#3687

Revert "WT-3600 Improve timestamp parsing to validate characters passed"

---

src/btree/bt_read.c
src/btree/bt_sync.c
src/btree/col_srch.c
src/btree/row_srch.c
src/cache/cache_las.c
src/conn/conn_ckpt.c
src/conn/conn_sweep.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/extern.h
src/include/session.h
src/include/thread_group.h
src/include/txn.i
src/reconcile/rec_write.c
src/session/session_api.c
src/support/thread_group.c
src/txn/txn_rollback_to_stable.c

@michaelcahill, some suggested changes from review, the individual commits should be descriptive.
Feel free to discard/cherry-pick without further discussion.

WT-3435 lookaside with timestamps lookaside cursor

---

src/btree/bt_io.c
src/btree/bt_page.c

Reverts wiredtiger/wiredtiger#3706

Revert "WT-3640 Fix bytes-read and bytes-written statistics."

---

src/reconcile/rec_write.c

Previously, the minimum timestamp was tracked incorrectly, which meant that checkpoints as-of a timestamp would incorrectly skip some pages with lookaside entries.

WT-3650 Fix minimum timestamp tracking in lookaside.

---

src/btree/bt_handle.c
src/conn/conn_dhandle.c
src/evict/evict_page.c
src/include/btree.h
src/reconcile/rec_write.c
test/suite/test_inmem01.py
test/suite/test_las.py

cherry pick b9bfe41b26db9acb53d37f5919b7d2bbe29db275 into mongodb-3.4

WT-3296 BACKPORT-1135 Port LAS improvements to mongodb-3.4

---

dist/stat_data.py
src/btree/bt_read.c
src/btree/bt_split.c
src/conn/conn_cache.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btmem.h
src/include/cache.h
src/include/cache.i
src/include/stat.h
src/include/wiredtiger.in
src/reconcile/rec_write.c
src/support/stat.c

Reverts wiredtiger/wiredtiger#3744

Revert "WT-3652 Skip unnecessary lookaside reads / writes."

---

test/mciproject.yml

(It also invokes Python to sanitize the build).

WT-3630 Send the test environment to "make check".

---

test/csuite/random_abort/main.c
test/csuite/timestamp_abort/main.c

@keithbostic Same change as yesterday added to the random_abort test program. Please review.

WT-3711 Add signal handler to random_abort.

---

src/include/extern.h
src/txn/txn.c

@michaelcahill Here are some changes that I made to address the issues I commented on in your branch.  The test runs to completion and shows some performance improvements (see ticket for details). This branch is forked off your branch.  Merge or discard as you see fit.

WT-3745 Don't allow an error late in commit path. Fix readonly check.

---

src/reconcile/rec_write.c

A slightly different approach, routing all of the built keys through the
"current" buffer.

WT-3751 Allow splits when no data is visible.

---

src/include/btree.i

When an application performs a truncate operation, WiredTiger marks pages deleted.  If such a page is subsequently read with a view earlier than the truncate, the page is reinstantiated and all records deleted (as if truncate had taken the slow path).
Such a page cannot be evicted: if the truncate is rolled back, it expects to find the page and any tombstones so it can roll them all back.  If the page is evicted or split, the rollback will fail.
This change takes two approaches: don't allow checkpoints to queue pages for urgent eviction, since checkpoints use special rules to determine whether eviction is permitted.  In addition, check for uncommitted truncate operations before allowing any page to be evicted.

WT-3765 Prevent eviction of pages being truncated.

---

SConstruct
src/docs/build-windows.dox
src/docs/spell.ok

Minor cleanup of recent changes to SConstruct.

WT-3753 Added --enable-java to documentation for building windows.

---

src/btree/bt_cursor.c
src/btree/bt_delete.c
src/btree/bt_discard.c
src/btree/bt_random.c
src/btree/bt_read.c
src/btree/bt_walk.c
src/btree/col_modify.c
src/btree/row_modify.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btmem.h
src/reconcile/rec_write.c
src/support/hazard.c
src/txn/txn_rollback_to_stable.c

@michaelcahill and @agorrod I pushed this branch off of the WT-3767 branch changing the name from `AMNESIA` to `LIMBO`. It is mostly for consideration with the visual context. Feel free to drop this if you don't like it.

Change AMNESIA to LIMBO

---

SConstruct
build_posix/aclocal/options.m4
build_win/wiredtiger_config.h
dist/api_data.py
lang/python/wiredtiger.i
src/block/block_ckpt.c
src/block/block_compact.c
src/block/block_vrfy.c
src/btree/bt_handle.c
src/btree/bt_read.c
src/btree/bt_slvg.c
src/cache/cache_las.c
src/conn/conn_api.c
src/docs/build-posix.dox
src/docs/build-windows.dox
src/evict/evict_lru.c
src/include/cache.h
src/include/error.h
src/include/misc.h
src/include/wiredtiger.in
src/os_common/os_fhandle.c
src/os_win/os_map.c
src/reconcile/rec_track.c
src/txn/txn.c
src/txn/txn_ckpt.c
src/txn/txn_timestamp.c
test/csuite/wt2719_reconfig/main.c
test/mciproject.yml
test/suite/test_txn06.py

Not ready for review yet.
Need to check the performance implications.

WT-3587 Remove HAVE_VERBOSE conditional compilation

---

test/packing/intpack-test.c
test/packing/intpack-test2.c
test/packing/intpack-test3.c
test/packing/packing-test.c

This resolves the problem on my laptop OS/X.

WT-3828 Add a function reference to resolve a link error on some systems

---

src/evict/evict_lru.c

Remove some old code that changed the target_pages calculation.

WT-3079 Further backport fix.

---

src/evict/evict_lru.c

Make sure the eviction server thread doesn't stop on a limbo page (blocking exclusive access to the page if eviction is no longer necessary).

WT-3844 Avoid a checkpoint deadlock after lookaside eviction.

---

src/cache/cache_las.c

@sueloverso, here's my review comments in more tangible form -- feel free to discard this branch without further discussion.

WT-3766 Remove LAS entries if they're visible and no longer needed.

---

src/txn/txn.c
test/suite/test_assert04.py

@agorrod and @dgottlieb one more time!

WT-3881 Add more test cases and complete checking on commit timestamp.

---

src/txn/txn_timestamp.c

@agorrod There are fixes for the commit timestamp queue bugs that the mongodb tests found. First we need to modify the `first_commit_timestamp` under the lock and later than it was before. Also we want to remove ourselves from the queue first because our timestamp may be smaller than it was last time and we could end up with a list loop. The alternative would have been to walk the entire queue removing all to-be-cleared transactions from the list but we want to minimize the walks.

WT-3895 Fixes to manage the timestamp queue.

---

test/format/ops.c

@agorrod, I introduced a bug in the last set of format changes, the result is we're doing almost nothing other than remove operations in our format runs.
I'd like to push this as soon as we can, and then I'll watch format testing overnight.

WT-3925 format: salvage dump comparison failure

---

src/btree/bt_delete.c
src/include/txn.h
src/txn/txn.c
src/txn/txn_log.c

@michaelcahill, the changes in 2c697cd and c984903 are the only ones that should require careful review, the others are comment clarification and code shuffling to make it easier to make the fix.

WT-3952 page-delete update list traversed after it has been discarded.

---

dist/api_data.py
src/config/config_def.c
src/include/txn.h
src/include/wiredtiger.in
src/txn/txn_ckpt.c
src/txn/txn_timestamp.c
test/suite/test_timestamp10.py

@agorrod or @keithbostic please review.

WT-3958 Add last checkpoint timestamp to query_timestamp.

---

test/suite/test_bug019.py

@keithbostic I created a test that passes on linux. It should fail on Windows but I don't know for sure. And it should pass once the fix is in. This branch is off of your branch.

Add test of pre-allocated log files.

---

src/include/btree_cmp.i

This is a contribution for adding AArch64 FTS fast byte vector support & NEON support for row search operations.

WT-4008 Add ARM NEON support for row search operations

---

src/include/btree_cmp.i

Reverts wiredtiger/wiredtiger#4016

Revert "WT-4008 Add ARM NEON support for row search operations"

---

build_posix/aclocal/strict.m4
src/txn/txn.c

Test old branch PR Jenkins jobs

WT-3994 Avoid GCC-7 and Clang errors for mongodb-3.4 branch

---

src/cache/cache_las.c

We now "pre-allocate" the lookaside entry count by incrementing it by 100 as records are inserted.  At the end, we need to fix up the final count to match the number that were actually inserted.  That is always a decrement.

WT-4012 Fix lookaside entry count.

---

src/cache/cache_las.c

Reverts wiredtiger/wiredtiger#4024

Revert "WT-4012 Fix lookaside entry count."

---

src/evict/evict_lru.c

Later walks assume there is a clear range of the queue and interrupts could violate that assumption.

WT-4014 If eviction walk is interrupted, clean up the queue.

---

src/evict/evict_page.c

If eviction has to pull pages into cache (generally because they have lookaside history that is relevant to the checkpoint), we try to evict those pages immediately, writing the correct version to disk in the process.
However, if the eviction causes the page to split (which can happen because a different set of data is visible to the checkpoint than was visible when the page was previously evicted and the lookaside entries written), then splitting up the tree could invalidate the internal page image already calculated by the checkpoint.
The solution taken here is to give up on eviction if it would cause a page to split during a checkpoint.  The pages will stay in cache a little longer (though this should be rare in real workloads), but a valid snapshot of data will be written to disk.

WT-4017 When evicting during a checkpoint, avoid splits.

---

test/suite/test_schema06.py

@ddanderson Please review this minor change to a test you wrote a (very) long time ago. I noticed it wasn't actually doing the drop.

WT-4015 add drop index calls to test.

---

dist/api_data.py
dist/s_string.ok
src/config/config_def.c
src/conn/conn_api.c
src/conn/conn_dhandle.c
src/cursor/cur_backup.c
src/include/extern.h
src/include/meta.h
src/include/txn.h
src/meta/meta_ckpt.c
src/txn/txn_ckpt.c
src/txn/txn_recover.c
src/utilities/util_list.c
test/suite/test_backup08.py
test/suite/test_timestamp10.py

WT-3959 Manage recovery timestamp via a new schema entry.

---

src/btree/bt_split.c
src/include/btree.i
src/include/extern.h
src/support/generation.c

Alex, feel free to discard without further discussion if you don't like it.

WT-4044 add API to return if a generation is active

---

src/log/log_slot.c

@agorrod Please review this change. After the user opened the ticket and questioned this, I believe this is safe. I have been running on this branch for a few hours in both the `wiredtiger-test-recovery-stress` and `wiredtiger-perf` jobs and have not seen any problems.
Other uses of `wt_log_release` do not hold any locks so that function does not require it.

WT-4058 Release a slot outside of the lock.

---

src/bloom/bloom.c
src/cursor/cur_join.c
src/include/extern.h
src/log/log.c
src/optrack/optrack.c
src/support/huffman.c

@sueloverso, I was chasing a `WT_ERROR` return today that didn't have an associated message, and so I went looking. I'm asking you for the review because `log.c` is involved.
Thanks!

WT-4023 naked error returns

---

src/log/log_slot.c

This reverts commit 38f494b08419017e3c7c06fc3b41be9ea7e95a6f.

WT-4077 Revert a change to release logging slot outside of the lock. (#4074)"

---

build_win/wiredtiger.def
dist/s_export.list
dist/s_funcs.list
examples/c/ex_all.c
src/checksum/arm64/crc32-arm64.c
src/checksum/power8/crc32_wrapper.c
src/checksum/x86/crc32-x86.c
src/checksum/zseries/crc32-s390x.c
src/conn/conn_api.c
src/include/extern.h
src/include/wiredtiger.in
test/csuite/Makefile.am
test/csuite/wt4117_checksum/main.c

Alex, I took a run at exposing the WiredTiger crc32c checksum functions for MongoDB.

WT-4117 Expose WiredTiger crc32c functions

---

src/conn/conn_reconfig.c
src/include/error.h
src/log/log.c
test/suite/test_compat02.py
test/suite/test_compat03.py

@agorrod @dgottlieb Here are the changes for adding a prefix, and I changed the unit tests to reflect it.

WT-4127 Add compatibility prefix.

---

src/docs/config-strings.dox
src/docs/upgrading.dox

@agorrod and @lukech here are upgrading changes from WT-4029. I fixed a couple typos I saw in the docs also.

WT-4168 Doc changes for upgrading. Typos.

---

test/csuite/schema_abort/main.c

@agorrod This fixes the failures on tinderbox that result from very slow IO on that machine and a false positive timeout. Please review.

WT-4210 Start timer after checkpoint completes.

---

bench/workgen/runner/split_stress.py

A workload to stress page splits.

WT-3735 Split stress test workgen

---

src/evict/evict_page.c

Elsewhere we assume that flipping `ref->state` from `DELETED` to `LOCKED` makes it safe to free `ref->page_del`.  If we're attempting to evict an internal page, we have it locked, so no thread can descend into it, but a walk could be attempting to couple into a child page, so we can't assume exclusive access to all of the children.

WT-4262 In eviction of internal pages, lock deleted children.

---

test/csuite/random_abort/main.c

Waiting for the table to exist was insufficient as that was created before the threads were started.
Instead wait for the record files that each thread creates for itself.

WT-4268 Random abort should wait until record files exist before starting timer.

---

src/conn/conn_api.c

@agorrod Here are a couple minor fixes debugging with Louis. Please review.

WT-4288 Don't let return value of closing conn overwrite WT_TRY_SALVAGE.

---

test/suite/test_backup02.py
test/suite/test_backup03.py
test/suite/test_bug010.py
test/suite/test_bug019.py
test/suite/test_config07.py
test/suite/test_intpack.py
test/suite/test_sweep01.py
test/suite/test_sweep03.py
test/suite/test_timestamp07.py

By reducing runtime for longest running tests.

WT-4281 Reduce Python test suite runtime

---

src/include/extern.h
src/schema/schema_alter.c
src/schema/schema_create.c
src/schema/schema_drop.c
src/schema/schema_rename.c
src/schema/schema_util.c
src/txn/txn.c
test/csuite/random_directio/main.c

WT-4328 Use an internal session handle for schema operations in a txn.

---

src/conn/conn_dhandle.c
test/csuite/wt3363_checkpoint_op_races/smoke.sh
test/utility/parse_opts.c
test/utility/test_util.h
test/utility/thread.c

There was a bug in that change that we don't fully understand yet. Also add a test enhancement that lets us see the bug quickly.

WT-4339 Revert part of a previous commit that simplified handle locking

---

test/format/ops.c

It should retry until a different result is seen.

WT-4366 Fix how test/format handles prepare conflict errors

---

test/format/ops.c

Reverts wiredtiger/wiredtiger#4325

Revert "WT-4366 Fix how test/format handles prepare conflict errors"

---

bench/workgen/workgen.cxx
bench/workgen/workgen.h
bench/workgen/wtperf.py

Not yet ready for review. There is still one more area that needs fixing.

WT-4298 Workgen fixes. Retry on WT_ROLLBACK. Clear ops after warmup.

---

bench/wtperf/wtperf.c

@ddanderson please review these small fixes for issues that Coverity found.

WT-4412 Fix Coverity issues.

---

dist/stat_data.py
src/cursor/cur_std.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_cursor16.py

Renamed data source statistic for current total.  Tweeked descriptions
of other cache cursor statistics.  Added test to verify new statistic.

WT-4411 Added connection statistic for current total of cached cursors.

---

ext/compressors/zstd/zstd_compress.c

update zstd compression level from 3 to 6.
I believe this will not have any compatibility issues. If I am wrong, request to comment.

WT-4434 modify zstd compression level from 3 to 6

---

src/conn/api_calc_modify.c
test/csuite/wt3338_partial_update/main.c

@michaelcahill, @sulabhM, when I was looking at WT-4421 today, I hooked the new API into the `csuite/wt3338_partial_update` test program (that's code that tests if the underlying WiredTiger modify API does the right thing).
This branch fixes a minor problem, if the old/new data sizes are 0, in commit b023cb0.

WT-4421 wiredtiger calc modify test

---

src/btree/bt_handle.c
src/docs/compression.dox

Enable dynamic compression for snappy

WT-4433 Enable dynamic compression for snappy

---

src/log/log.c
src/log/log_slot.c

Unlock when sleeping to allow other log threads to make progress.
(cherry picked from commit 8d7847c1837d484d618f52ac0fb4cba825767b54)
Please note the original changes to `test/csuite/timestamp_abort/main.c` was skipped here, to avoid dependency to WT-4342 and WT-3995.

WT-4343 Fix a hang in logging can when overwhelmed (#4336) (v3.6 backport)

---

dist/wtperf_config.py

Fix contributed by github user spease.

WT-4549 Fix wtperf_config.py to work with python2/3.

---

dist/stat_data.py
src/conn/conn_open.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

A stat variable "dh_conn_handle_size" takes the size of dhandle structure.

WT-4053 Add statistic for data handle size

---

src/conn/conn_cache_pool.c

@agorrod you've done the most work in the shared cache pool area. Please review this change. I've kicked off a run on tinderbox to see if it fixes the failure seen (after 10 hours, sadly). I'll let it run at least 24 hours.
I discovered the global reference count is not incremented under the same lock that it is decremented, and all the insert/remove calls are done on the connection list. I fixed that by dropping the process lock, acquiring the cache pool lock, and then re-acquiring the process lock (it is necessary to acquire in that order to avoid deadlock with other code taking them in that order).
While I believe I've maintained the original intent, I'm wondering why we hold the `wt_process` lock for the entire function. Looking later in the function, AFAICT we don't modify or access …

WT-4501 Increment cache_pool ref count under lock.

---

src/conn/conn_log.c
src/os_win/os_fs.c

(cherry picked from commit c1bb21ef3c16eb6f68f3e4fd51224dd4dcfec439)

WT-4528 Move remove/rename retry into Windows fs code (v4.0 backport)

---

src/lsm/lsm_work_unit.c

@sueloverso, @agorrod, this change reverts the functional part of the changes for WT-4561 (commit 6aafde0c).
The race that commit was supposed to fix doesn't exist:
```
__lsm_free_chunks() ->
__lsm_drop_file() ->
__wt_schema_drop() ->
__schema_drop() ->
__drop_file() ->
__wt_schema_backup_check() acquires the hot-backup lock.
```
The original code was:
```
/*
* Don't remove files if a hot backup is in progress.
*
* The schema lock protects the set of live files, this check
* prevents us from removing a file that hot backup already
* knows about.
*/
if (S2C(session)->hot_backup)
break;
```
which is wrong because the check can race with the backup cursor, the check doesn't do anything meaningful (other than maybe skipping a schema drop attempt that's likely to fail). I don't know enough …

WT-4577 test/format LSM deadlock

---

tools/optrack/find-latency-spikes.py

Used to display callstacks incorrectly.

WT-4568 Fix operation tracking visualization.

---

tools/optrack/find-latency-spikes.py
tools/optrack/wt_optrack_decode.py

This patch updates the visualization script to run the most time-consuming part of the visualization in parallel. Measurements show roughly 30% speedup in total processing time.

WT-4587 Parallelized the diagram-generating part of the visualization script.

---

tools/optrack/find-latency-spikes.py
tools/optrack/sample.config

This should help to track down the root causes of latency spikes.

WT-4599 Show latency threshold violations in operation visualizations.

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
test/suite/test_prepare_cursor02.py

This fix is related to BF-12253.

WT-4617 Prepare conflict is returned only once.

---

test/csuite/wt4333_handle_locks/main.c

@agorrod, @lukech, here are changes to skip the `wt4333_handle_locks` test on OS X, I see no evidence there's a real problem here.
I can't reproduce the problem on any of the 3 test systems I tried, and I don't think it's worth any additional effort to figure out.

WT-4613 Processes stuck on 'WT_TEST.wt4333_handle_locks' files on Mac hosts

---

src/meta/meta_turtle.c

`__wt_turtle_init()` isn't freeing memory returned from `__wt_turtle_read()`.

WT-4619 Coverity 111398: leaked memory

---

src/cursor/cur_backup.c

(cherry picked from commit b68fbf75c1f73467dcb5cce8eac8de67df89a431)

WT-4615 Sync backup file before closing. (v4.0 backport)

---

dist/s_string.ok
src/btree/bt_huffman.c
src/btree/bt_vrfy.c
src/conn/conn_capacity.c
src/conn/conn_reconfig.c
src/include/gcc.h
src/include/posix.h
src/include/swap.h
src/include/wiredtiger.in
src/log/log.c
src/meta/meta_ckpt.c
src/os_posix/os_fs.c
src/reconcile/rec_write.c
src/support/hash_city.c
src/txn/txn_recover.c
src/txn/txn_timestamp.c

This PR is to fix or suppress any warnings from Clang Tidy and Clang Scan.

WT-4602 Clang Tidy and Clang Scan fixes

---

src/conn/conn_api.c
src/txn/txn_rollback_to_stable.c

Cherry picked from commit e727b72.

WT-4532 Fix shared access to the default session. (v4.0 backport)

---

test/salvage/salvage.c

@sueloverso, I don't see the problem, so I just tried to quiet the complaint.
Please check me!

WT-4646 Coverity false positive on fopen calls

---

src/cursor/cur_backup.c

(cherry picked from commit b68fbf75c1f73467dcb5cce8eac8de67df89a431)
(cherry picked from commit 9308f8a02c7a3f8cd5e816c7f1e6374d43332db0)
Please note `WT_SESSION_BACKUP_CURSOR` was introduced since mongodb-4.0, and the line that sets the session type was removed by git cherry-pick.

WT-4615 Sync backup file before closing. (v3.6 backport)

---

src/txn/txn_timestamp.c
test/suite/test_timestamp16.py

WT-4631 Setting read timestamp to WT_TS_NONE in clear readtimestamp

---

src/btree/bt_vrfy_dsk.c
src/txn/txn_timestamp.c

@bvpvamsikrishna, can you please look at c29e5c1?
Just in case we should be doing something with the `ts` assignment.

WT-4668 lint

---

src/reconcile/rec_write.c

Sometimes we attempt eviction of a page by writing the most recent
versions of updates.  If such a page remains dirty in cache, it must be
visited by the next checkpoint to make sure the data that appears in the
checkpoint is a consistent cut of versions.
(cherry picked from commit d344940895bbf0232ea02e1e56fefac65d1eb2ae)

WT-4324 BACKPORT-4.0 Ensure checkpoints rewrite pages with data in the future (#4521)

---

src/cursor/cur_backup.c

(cherry picked from commit b68fbf75c1f73467dcb5cce8eac8de67df89a431)
(cherry picked from commit 9308f8a02c7a3f8cd5e816c7f1e6374d43332db0)
(cherry picked from commit 3291c2cbf682f52c88f1b3394c9a94bd80d6a4d6)

WT-4615 Sync backup file before closing. (v3.4 backport)

---

src/include/extern.h
src/log/log.c
src/os_common/os_fhandle.c
test/csuite/wt4156_metadata_salvage/main.c

Also code movement to refactor zero'ing part of a file into fs code.

WT-4317 Remove portion of test not guaranteed to work with salvage.

---

src/cache/cache_las.c
src/reconcile/rec_write.c

Enabled durable timestamp assertions.

WT-4598 Enable durable timestamp assertions.

---

src/cursor/cur_index.c
src/cursor/cur_json.c
src/cursor/cur_table.c
src/include/extern.h
test/csuite/Makefile.am
test/csuite/wt4699_json/main.c
test/evergreen.yml

Added a test showing the original problem.

WT-4699 Save a copy of column list for JSON dump.

---

src/conn/conn_reconfig.c
test/suite/test_compat01.py

…e downgraded. (#4546)
(cherry picked from commit b16d36ef0932a36ebcae950ef68e873f0514d5f8)

WT-4693 v3.6 Backport

---

src/btree/bt_handle.c
src/cache/cache_las.c
src/include/cache.h
src/include/extern.h

@keithbostic and @michaelcahill for consideration.

WT-4750 Remove our id from the LAS dropped list on reopen if it's on it.

---

src/include/txn.h
src/include/txn.i
src/txn/txn.c
src/txn/txn_log.c

Reverts wiredtiger/wiredtiger#4627

Revert "WT-4719 Txn prepared update resolution validation"

---

src/btree/bt_compact.c
src/btree/bt_delete.c
src/btree/bt_handle.c
src/btree/bt_read.c
src/btree/bt_slvg.c
src/btree/bt_split.c
src/cache/cache_las.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btmem.h
src/include/extern.h
src/include/txn.i
src/reconcile/rec_child.c
src/reconcile/rec_write.c

Include atomic CAS transitions as well as setting state.

WT-4796 Enhance diagnostics that track ref state transitions

---

src/include/txn.h
src/include/txn.i
src/txn/txn.c
src/txn/txn_log.c

Reverts wiredtiger/wiredtiger#4640

Revert "WT-4719 Modifying prepared update resolution logic"

---

src/btree/bt_compact.c
src/btree/bt_delete.c
src/btree/bt_handle.c
src/btree/bt_read.c
src/btree/bt_slvg.c
src/btree/bt_split.c
src/cache/cache_las.c
src/evict/evict_file.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btmem.h
src/include/btree.i
src/include/cache.h
src/include/extern.h
src/include/txn.i
src/reconcile/rec_write.c
src/txn/txn_rollback_to_stable.c

Tagged with a ticket to get PR testing started.

WT-4352 Backport data corruption fixes

---

dist/stat_data.py
src/cache/cache_las.c
src/include/meta.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

(cherry picked from commit f654ed4c4d474309c59f05431138d15a5ed88f2d)

WT-4706 Add a statistic to track the lookaside table size (v4.0 backport)

---

src/log/log.c

(cherry picked from commit 88359b9facf9e8e60576ce0caed990e912857577)

WT-4817 Fix off-by-one error. (v4.0 backport)

---

dist/api_data.py
dist/s_void
dist/stat_data.py
src/cache/cache_las.c
src/config/config_def.c
src/conn/conn_open.c
src/conn/conn_reconfig.c
src/include/btree.h
src/include/cache.h
src/include/extern.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/csuite/Makefile.am
test/csuite/wt4803_cache_overflow_abort/main.c
test/evergreen.yml
test/suite/test_las04.py

Clean cherrypick of 1be63c5 off `develop`.

WT-4803 Implement file_max configuration for Cache Overflow mechanism (v4.0 backport)

---

dist/api_data.py
dist/s_void
dist/stat_data.py
src/cache/cache_las.c
src/config/config_def.c
src/conn/conn_open.c
src/conn/conn_reconfig.c
src/include/btree.h
src/include/cache.h
src/include/extern.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/csuite/Makefile.am
test/csuite/wt4803_cache_overflow_abort/main.c
test/suite/test_las04.py

Unclean cherrypick of 0434b61 off `mongodb-4.0`.

WT-4803 Implement file_max configuration for Cache Overflow mechanism (v3.6 backport)

---

src/txn/txn.c

WT-4875 fix commit timestamp assert to consider non transactional

---

src/btree/bt_cursor.c
src/conn/api_calc_modify.c
src/include/btmem.h

(cherry picked from commit 40e3225e55ffbf0c9819af138fa4a014c0639c72)

WT-4848 Performance tuning for calculating and caching diffs. (#4673)

---

dist/api_data.py
dist/s_string.ok
src/btree/bt_split.c
src/cache/cache_las.c
src/config/config_def.c
src/conn/conn_api.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btree.i
src/include/cache.h
src/include/wiredtiger.in
src/reconcile/rec_write.c
src/txn/txn_log.c
test/suite/test_debug_mode04.py

(cherry picked from commit 10963a7deb9b520fe0c44e6b55dc390b845ce06d)

WT-4477 Add eviction debug mode and extra checks. (#4663) (v4.0 backport)

---

test/suite/test_prepare04.py

Modified the test to ensure that it verifies the returned
error messages for the operations

WT-4805 Modify test verification of error messages

---

SConstruct

Two sets of trivial changes. 
1. print statement to print function
2. Fix a bad indent
Python 2 will be still supported since this such a simple file.

WT-4910 Python 3 Windows support

---

src/btree/bt_cursor.c
src/conn/api_calc_modify.c
src/include/btmem.h

(cherry picked from commit 40e3225e55ffbf0c9819af138fa4a014c0639c72)
(cherry picked from commit e0ba3bc3e1e1c8efd93e144d4df4392bfbabc031)

WT-4848 Performance tuning for calculating and caching diffs. (v3.6 backport)

---

src/txn/txn.c

__wt_verbose_dump_txn_one function is enhanced to dump additional
transaction structure fields for more verbose infomration of the
transaction.

WT-4889 Dumping additional transaction fields

---

src/support/modify.c

http://build.wiredtiger.com:8080/job/wiredtiger-configure-combinations/4593/console

WT-4460 Optimize for in-order, non-overlapping modifications

---

src/include/reconcile.h
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c

Reverts wiredtiger/wiredtiger#4792

Revert "WT-4943 Fix  a bug where uncommitted updates could be discarded (BACKPORT - 4.0)"

---

src/reconcile/rec_visibility.c

Reverts wiredtiger/wiredtiger#4791

Revert "WT-4940 Reconciliation should set prepared/uncommitted for each updat…"

---

src/btree/bt_read.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btmem.h
src/include/cache.h
src/reconcile/rec_write.c
src/support/hazard.c

Reverts wiredtiger/wiredtiger#4804

Revert "WT-4869 / WT-4881 / WT-4893 v3.6 backport"

---

dist/s_string.ok
src/btree/bt_debug.c
src/include/extern.h
test/format/format.h
test/format/snap.c
test/format/util.c

@keithbostic for any suggestions of other/additional places to call this new function. Not yet ready for merge.

WT-5040 Add dumping of cursor's page on a mismatch.

---

dist/stat_data.py
src/evict/evict_lru.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

(cherry picked from commit e0cbcd88a122510d8d4b20bff738e5c29cdd6e27)

WT-4792 Add stat to track pages queued for eviction after LRU sorting (#4748) (v4.0 backport)

---

src/btree/row_key.c
src/evict/evict_lru.c
src/include/api.h
src/reconcile/rec_write.c

WT-5088 Refine clearing and setting of debug timer.

---

src/btree/bt_read.c
src/btree/bt_sync.c
src/evict/evict_lru.c
src/include/btree.i
src/include/cache.h
src/reconcile/rec_write.c

This pull request includes the above mentioned tickets which satisfy:
- BACKPORT-4712
- BACKPORT-4765
- BACKPORT-5033
- BACKPORT-5034
- BACKPORT-5043

WT-4869 WT-4881 WT-4898 WT-4957 WT-5050 v4.0 Backport clang formatted

---

src/btree/bt_read.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btmem.h
src/include/cache.h
src/reconcile/rec_write.c
src/support/hazard.c

This is a reopening of the previous pull request that was reverted:
https://github.com/wiredtiger/wiredtiger/pull/4804
That PR was approved so I think these are all good to go straight away.

WT-4869 WT-4881 WT-4893 v3.6 backport

---

src/btree/bt_sync.c
src/include/btree.i

Keith please take a look, if these backports look good to you please merge the PR and close the related jiras as I won't be online tomorrow.

WT-4898  WT-4957 WT-5050 backport v3.6

---

build_posix/Make.base
build_posix/reconf
dist/s_clang-format

Unclean cherry-pick of 7ff6a3e.

WT-5074 Fix "make check" on exotic architectures (v4.0 backport)

---

test/evergreen.yml

Evergreen patch build: https://evergreen.mongodb.com/version/5d8513777742ae189e690148

WT-4702 Switch to ubuntu1804-test Evergreen distro

---

dist/s_string.ok
src/btree/bt_debug.c
src/include/btmem.h
src/include/btree.i
src/include/serial.i
src/reconcile/rec_write.c

Unclean cherry-pick of 4c72fee.
Mostly just had to resolve some stylistic changes between these 3.6 and 3.4.

WT-4956 Handle the case where 4 billion updates are made to a page without eviction (v3.4 backport)

---

src/include/time.i

New branch, I had the wrong name/ticket number on the first one. Otherwise no changes.

WT-5149 Clear the debugging field value so it cannot get stale.

---

test/evergreen.yml

Add --enable-silent-rules and CFLAGS="-ggdb" to the default settings.
Extract default configure_env_vars.

WT-5184 Set default configure_env_vars

---

src/cache/cache_las.c

This reverts commit a74b4299f9cd5701c580cae502a3f81585a4d89f.

WT-5193 Revert "WT-5150 Fix the check to find out whethere LAS is empty (#4908)"

---

test/evergreen.yml

Added a task "test-checkpoint" & respective function "test checkpoint for filetype" in the evergreen.yml file to migrate "wiredtiger-test-checkpoint" job from jenkins to evergreen.

WT-4987 Migrate Jenkins test-checkpoint job to Evergreen

---

dist/api_data.py
examples/c/ex_all.c
src/btree/bt_read.c
src/btree/bt_sync.c
src/cache/cache_las.c
src/evict/evict_page.c
src/include/btmem.h
src/include/btree.i
src/include/reconcile.h
src/include/txn.h
src/include/wiredtiger.in
src/reconcile/rec_child.c
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c
src/txn/txn_ckpt.c
src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c
test/suite/test_las01.py
test/suite/test_timestamp04.py
test/suite/test_timestamp06.py
test/suite/test_timestamp11.py
test/suite/test_timestamp16.py

…#4835)
(cherry picked from commit 2c9ad42e85083a45670a9a2515e00d34c66bf2ad)

WT-4961 WT-5160 Backport v4.0

---

test/evergreen.yml

Reverts wiredtiger/wiredtiger#4960

Revert "WT-4990 Migrate Jenkins “wiredtiger-test-unit-ppc” job to Evergreen"

---

test/evergreen.yml

Created a new buildvariant to support "ubuntu1804-power8-test" machine and running the unit-test on it.

WT-4990 Migrate Jenkins wiredtiger-test-unit-ppc job to Evergreen

---

test/evergreen.yml

Added a new buildvariant "ubuntu1804-zseries-test" to support zseries unit test.

WT-4991 Migrate Jenkins wiredtiger-test-unit-zseries job to Evergreen

---

test/evergreen.yml

Set LD_LIBRARY_PATH environment variable in test_env_vars

WT-5252 Fix Ubuntu 18.04 PPC "unit-test" and Ubuntu 18.04 zSeries "unit-test" evergreen jobs.

---

test/evergreen.yml

Added a new task "test-wtperf" under Ubuntu 18.04 buildvariant

WT-4995 Migrate Jenkins wiredtiger-test-wtperf job to Evergreen

---

test/csuite/time_shift_test.sh
test/evergreen.yml

Created compile-enable-strict and time-shift-sensitivity-test task

WT-5033 Migrate Jenkins wiredtiger-test-time-shift-sensitivity job to evergreen

---

dist/s_clang-format

(cherry picked from commit 6ed72590b7446185a734640e88c9c8a8f9fa88f2)

WT-5106 v4.0 backport

---

test/csuite/random_directio/util.c

@ddanderson Please review. The ticket and the comment explain the failure case.

WT-5077 Handle ENOENT without failure when copying the directory.

---

src/include/btree.i

Reverts wiredtiger/wiredtiger#5041

Revert "WT-5319 Avoid clearing the saved last-key when no instantiated key"

---

dist/api_data.py
examples/c/ex_all.c
src/config/config_def.c
src/include/wiredtiger.in
src/txn/txn_timestamp.c
test/csuite/timestamp_abort/main.c
test/suite/test_timestamp02.py
test/suite/test_timestamp14.py

Reverts wiredtiger/wiredtiger#5040

Revert "WT-4968 remove all committed and connection level commit timestamps"

---

bench/wtperf/wtperf.c
dist/s_goto.py
src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/btree/bt_read.c
src/btree/bt_slvg.c
src/btree/bt_vrfy.c
src/btree/bt_vrfy_dsk.c
src/btree/row_key.c
src/btree/row_srch.c
src/cursor/cur_stat.c
src/reconcile/rec_col.c
src/reconcile/rec_row.c
test/csuite/schema_abort/main.c
test/format/ops.c

I updated the regex in `s_goto.py` and the `./s_all` run updated the other files.

WT-5112 Format goto multi-word labels 

---

src/docs/devdoc-glossary.dox
src/docs/devdoc-index.dox

There is no real content yet, but I thought I'd get it started.

WT-5360 Add template for a glossary in developer docs

---

src/include/txn.i
src/txn/txn.c

Reverts wiredtiger/wiredtiger#5019

Revert "WT-5145 v4.0 Backport"

---

src/cache/cache_las.c

(cherry picked from commit a68760eb307a0dd7ccd6bef41c37fbd99d35c433)

WT-5135 v4.0 backport

---

test/evergreen.yml

Jira ticket - [here](https://jira.mongodb.org/browse/WT-5199)
Evergreen patch build [here](https://evergreen.mongodb.com/build/wiredtiger_rhel80_patch_5bd9fdfc0bb7f8fcf791e234b6e436c79dfe1fee_5e1517b6d1fe0737244a691b_20_01_07_23_44_13)

WT-5199 adding correctness tasks into rhel80 evergreen - Part 1

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/btree/bt_random.c
src/btree/bt_read.c
src/btree/bt_ret.c
src/btree/bt_split.c
src/btree/col_modify.c
src/btree/col_srch.c
src/btree/row_modify.c
src/btree/row_srch.c
src/cache/cache_las.c
src/include/cursor.i
src/include/extern.h
src/include/wiredtiger.in
src/reconcile/rec_write.c

Backports both WT-5120 and WT-5277 and WT-5135.
JIRA: https://jira.mongodb.org/browse/BACKPORT-5489

WT-5120 Checkpoint hangs when reconciliation doesn't release the eviction generation (#4943) #5018 #5071 [BACKPORT-v3.6]

---

src/cache/cache_las.c

ticket: https://jira.mongodb.org/browse/WT-5380
Made the requested change, updating `cursor_insert` to be `cursor_update`

WT-5380 Changed cursor_insert to cursor_update

---

test/suite/test_calc_modify.py

Changed the array accessing logic as requested. Had to change (potentially fixed, honestly) the conditional logic to be an `or` instead of an `and`, as accessing the diff properly was impossible when i was 0.

WT-5041 Test calc modify test is not properly distributing the modifications

---

bench/workgen/runner/evict-btree-lookaside.py

Increasing the stress on lookaside/history store by increasing the number of search and insert op threads, and by removing the throttle setting on insert threads.

WT-5449 Increase contention in History Store stress workload

---

dist/s_string.ok
src/block/block_ckpt.c
src/conn/conn_api.c
src/cursor/cur_backup_incr.c
src/include/block.h
src/include/cursor.h
src/include/extern.h
src/meta/meta_ckpt.c

Here's a PR based off of the WT-5206 branch.

WT-5465 Implement incremental granularity and use a bitmap for block storage.

---

src/txn/txn_rollback_to_stable.c

During rollback to stable walk of all objects in WT, the trees and pages
with their aggregated max durable timestamp is compared against stable
timestamp to find out whether they have any updates newer than stable timestamp.

WT-5417 Ignore trees or pages with modifications less than stable

---

test/suite/test_inmem01.py

See JIRA for details, this test was fixed by way of two separate fixes.

WT-5386 Re-enabling test inmem01

---

test/evergreen.yml

Evergreen patch build [here](https://evergreen.mongodb.com/build/wiredtiger_rhel80_patch_549a573c208cdf2c5c3c7a4c2dc40b5f086fce4c_5e3b5665c9ec4479e5435362_20_02_05_23_57_43)

WT-5398 Adding more correctness tasks into rhel80 buildvariant

---

src/include/txn.i

as per https://github.com/wiredtiger/wiredtiger/pull/5216#discussion_r374984109

WT-5529 Improve usage of upd in txn.i

---

src/btree/bt_ret.c
src/include/extern.h
src/reconcile/rec_col.c
src/reconcile/rec_row.c

I haven't run the performance test yet. Jenkins performance tests can tell us how much we can gain from this.

WT-5526 Remove visibility check in __wt_value_return_upd

---

src/conn/conn_api.c
src/include/extern.h
src/meta/meta_ckpt.c
src/meta/meta_turtle.c

Tried on WT-5461 branch. The backup tests are fixed.

WT-5516 Aggregate max write gen when starting from backup

---

dist/s_string.ok
examples/c/ex_backup_block.c
src/cursor/cur_backup_incr.c
src/include/extern.h
src/log/log.c

@ddanderson primarilly I'd like you to review the example program changes. They're not pretty, but allowed me to test this with a log path to reproduce Gregory's issue and test the fix. 
@keithbostic please review the library change. If you think of a more elegant way to do it, let me know. This doesn't feel horrible, but maybe there's a better interface I'm not remembering.

WT-5554 Account for logpath when retrieving file size.

---

test/format/ops.c
test/format/t.c

WT-5521 Cache stuck during format initial load, configured with library checkpoints

---

test/format/config.c

Fix testing fallout from WT-5538.

WT-5584 Change format to ignore Evergreen timestamps in configuration files.

---

src/cursor/cur_backup.c
test/suite/test_backup11.py

There was a commented out error case for incremental that I debugged/fixed today.

WT-5589 Fix verification of force_stop configuration setting.

---

test/evergreen.yml

Evergreen Patch build [link](https://evergreen.mongodb.com/version/5e45de313e8e86781c2bd9db)

WT-5001 Migrate jenkins wiredtiger-test-format-stress-sanitizer-ppc

---

src/btree/bt_vrfy.c

WT-5598 __verify_timestamp_to_pretty_string returns local buffer to the caller

---

src/btree/bt_split.c

@agorrod, @bvpvamsikrishna, can one of you please assign a reviewer?

WT-5518 Split-parent code can race with other threads when checking the WT_REF.state

---

test/suite/test_backup12.py

This test is now updated to use the blocks returned by incremental. It was only doing full-file copy all the time.

WT-5624 Fix test_backup12.py to use range incremental backup.

---

src/txn/txn_ckpt.c

(cherry picked from commit a19d2bff3d30fdd83086172b29161527aefc28e3)
(cherry picked from commit 58baf804dd6e5a72c4e122cfb696e2d06a9fc888)

WT-5587 Limit how many checkpoints are dropped by a subsequent checkpoint #5261

---

src/support/mtx_rw.c

(cherry picked from commit 580d0c4f255b245e1a79ab56023e224117c32c90)

WT-5395 Fix a bug in the read lock implementation when there is a lot of contention (#5140)

---

test/evergreen/compatibility_test_for_mongodb_releases.sh

* Update compatibility_test_for_mongodb_releases.sh for durable history integration into MongoDB
* Remove the deprecated --enable-page-version-ts flag

WT-5434 Update compatibility_test_for_mongodb_releases.sh for durable history integration into MongoDB

---

src/btree/bt_slvg.c

Verified this fixed test_wt4156_metadata_salvage in WT-5595

WT-4868 Aggregate btree write gen from leaf pages in salvage

---

examples/c/ex_backup_block.c
src/meta/meta_ckpt.c
test/suite/test_backup12.py

WT-5719 Add quotes to the metadata string. Modify example to use special

---

src/reconcile/rec_row.c

@kommiharibabu, @luke-pearson: b6244af is a fix for the problems described in the WT-5684 ticket. I may be misunderstanding what you were doing in changes you made for WT-5476, so feel free to push back hard.
@tetsuo-cpp, while I was in the area, I think I spotted a problem with your changes for WT-5641 (specifically, the changes in `src/reconcile/rec_row.c`, [here](https://github.com/wiredtiger/wiredtiger/pull/5295/files)), the fact that we're using `tmpkey` is going to mess up prefix compression because the next loop in reconciliation won't have `tmpkey.size` set to 0. The fix in e3cf67b moved the chunk of code you added, I didn't see any reason we needed to wait on updating the HS file until subsequent, inserted key/value pairs have been written.

WT-5684 overflow values must be discarded when there is no update for a key

---

test/suite/test_txn06.py

This test was supposed to generate a verbose message, but either never
worked consistently or was broken at some point.  Fix the test so it
(a) consistently generates the message; and
(b) expects the message so the test doesn't fail when it is generated.

WT-3821 Fix a test for verbose transaction messages

---

src/include/txn.i

* Cache the WT_UPDATE.type field so that it can't change underneath us after the visibility checks.
(cherry picked from commit 168c7f1b3859516115721868f312544abb0caf5b)

WT-5376 WT_UPDATE.type field can race with visibility checks when returning key/value pairs (#5173) [Backport to 4.0]

---

src/block/block_open.c
test/suite/test_txn19.py

Reverts wiredtiger/wiredtiger#5399

Revert "WT-5831 Fix test_txn19"

---

test/csuite/incr_backup/main.c

Verify that remove(3) successfully deletes file

WT-5729 Check remove(3) return value in incr_backup test

---

test/csuite/incr_backup/main.c

Add check of return value from close(2) when reopening a file

WT-5730 check return value from close(2).

---

test/format/backup.c

WT-5858 Fix incremental backups both log/block based for first time

---

src/btree/bt_page.c

WT-5754 Ensure the value is globally visible before encode it into WT_ROW

---

lang/python/wiredtiger.i

Fix SWIG interface wrappers for async ops.  
When allocating and freeing memory for the python callback, we don't have a readily available WT_SESSION to pass to wt_calloc() and wt_free(), respectively.  So just pass NULL.  This means we won't be able to update statistics for these operations. But this is acceptable since the python wrappers are mostly (only?) used for our unit tests.
Also added a new method --- asyncopFreeHandler() --- to find the python callback that needs to be freed.

WT-4523 Fix type incompatibilities during alloc and free of memory for async ops

---

src/txn/txn_rollback_to_stable.c

For in-memory databases, even after writing an update to disk,
it still retian all the older updates in the memory until they
are obsolete because there is no history store involved for
in-memory databaes. For rollback to stable to work on in-memory
databases, we need to clear the on-disk update whenever there
are no visible updates found in the update list according to
the stable timestamp.

WT-5932 RTS Aborting on-disk updates for in-memory database

---

src/btree/bt_handle.c
src/btree/bt_page.c
src/conn/conn_api.c
src/include/cell.h
src/include/cell.i
src/include/connection.h
src/include/extern.h
src/include/reconcile.i
src/reconcile/rec_col.c
src/reconcile/rec_row.c
src/reconcile/rec_write.c

@agorrod, only lightly tested, I'm working on the testing framework next.

WT-5966 4.4 downgrade can result in 4.2 core dumps if cells are ignored

---

src/docs/eviction.dox
src/docs/programming.dox

I'm no expert of everything in eviction and I'm only documenting the things I currently understand. Also this document is only an overview of how eviction generally works and only gives details to an extent to help understanding the general picture. Feel free to ping me if you think I missed any important content or detail.

WT-5941 Overview documentation for eviction

---

src/docs/command-line.dox
src/utilities/util.h
src/utilities/util_alter.c
src/utilities/util_backup.c
src/utilities/util_compact.c
src/utilities/util_create.c
src/utilities/util_downgrade.c
src/utilities/util_drop.c
src/utilities/util_dump.c
src/utilities/util_import.c
src/utilities/util_list.c
src/utilities/util_load.c
src/utilities/util_loadtext.c
src/utilities/util_main.c
src/utilities/util_misc.c
src/utilities/util_printlog.c
src/utilities/util_read.c
src/utilities/util_rebalance.c
src/utilities/util_rename.c
src/utilities/util_salvage.c
src/utilities/util_stat.c
src/utilities/util_truncate.c
src/utilities/util_upgrade.c
src/utilities/util_verify.c
src/utilities/util_write.c

Fix up a few problems encountered along the way.

WT-5661 WiredTiger utilities should be self documenting

---

test/suite/test_backup14.py

* Added incremental backup data validation python test suite
* Addressed review comments
(cherry picked from commit b4ff0ee630e29398d08164f7f76ad3cbc2c2d7ff)

WT-5212 Incremental backup data validation test (#5304)

---

test/suite/test_backup11.py
test/suite/test_backup12.py
test/suite/test_backup13.py

Cherry picked from 96084abca789e41b95e0329829d1f3be842418c5

WT-5214 Add more incremental error cases (#5289) (v4.2 backport)

---

src/cursor/cur_backup.c
test/suite/test_backup11.py

(cherry picked from commit cd5e0047a41a98e5699fcc0d817aa6bfe0daf281)

WT-5589 Fix verification of force_stop configuration setting. (#5258) (v4.2 backport)

---

test/csuite/random_abort/main.c

@sueloverso Sorry for merging the PR without waiting your review. I address your comment in this ticket.

WT-6045 Minor cleanup for test_random_abort

---

src/cursor/cur_backup_incr.c

(cherry picked from commit 907640ededf071b9effd369cb5350d758c155a6c)

WT-5699 Refactor incremental cursor next code. (#5331)

---

test/csuite/Makefile.am
test/csuite/incr_backup/main.c
test/csuite/incr_backup/smoke.sh
test/evergreen.yml

Cherry-picked from f188ed87859121bd1fb9d2031e9ee9670356f118

WT-5215 Add basic randomized test for doing incremental backups. (#5297) (v4.2 backport)

---

dist/s_clang-scan.diff
src/btree/bt_debug.c
src/btree/bt_vrfy.c
src/btree/bt_vrfy_dsk.c
src/include/cell.i

Verify the added durable timestamps that are part of the both
value and address cells.

WT-5673 Verify durable timestamp that are part of cell

---

src/block/block_ckpt.c

* WT-5834 Clear memory if we extend the bitmap buffer.
* Assert and comment that number of bytes must be multiple of 8.
(cherry picked from commit 1648fdd3bc95c93c4f882f6205b5a98654885d81)

WT-5834 Clear memory if we extend the bitmap buffer. (#5409) (v4.2 backport)

---

test/format/ops.c

This is so that more prepared updates are in memory.

WT-5677 test/format changes to add occasional delays after prepare.

---

src/block/block_open.c
src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_ret.c
src/btree/bt_sync.c
src/evict/evict_page.c
src/history/hs.c
src/include/cell.i
src/reconcile/rec_col.c
src/txn/txn_timestamp.c
test/csuite/random_abort/main.c
test/csuite/wt4105_large_doc_small_upd/main.c
test/csuite/wt4333_handle_locks/main.c
test/evergreen.yml

This PR is to:
- Remove stale FIXMEs.
- Tag existing FIXMEs with a more relevant PM or WT ticket (a lot were tagged with the "write newest" project).
- Tag existing FIXMEs with a new WT ticket.

WT-5928 Cleanup stale FIXMEs from durable history

---

src/include/extern.h
src/include/txn.h
src/meta/meta_ckpt.c
src/txn/txn_recover.c
src/txn/txn_timestamp.c
test/suite/test_timestamp19.py

Reverts wiredtiger/wiredtiger#5603

Revert "Revert WT-5679"

---

test/evergreen.yml
test/suite/run.py

Order the tests in a batch to prioritize the full breadth of individual tests.

WT-6097 test/suite runner: Add -b (batch) option, to run a single batch from the set of tests

---

src/btree/bt_debug.c
src/btree/bt_page.c
src/btree/bt_rebalance.c
src/btree/bt_slvg.c
src/btree/bt_stat.c
src/btree/bt_vrfy.c
src/btree/bt_vrfy_dsk.c
src/include/cell.i

@quchenhao, d16afa2 is the interesting commit, 9204656 is just semantic sugar to simplify some function calls.

WT-6166 KEY/VALUE short cells have to handle copy cells

---

src/reconcile/rec_visibility.c

@kommiharibabu Coverity catches an interesting bug and I think there is a concurrency issue with the prepared case.

WT-6210 Add an assert to make coverity happy

---

dist/api_data.py
src/conn/conn_api.c
src/include/wiredtiger.in
src/os_posix/os_fs.c
test/format/config.c

@fedorova, wanted to let you know about the configuration changes.

WT-6177 direct I/O configurations fail with combined with mmap configurations

---

test/checkpoint/Makefile.am
test/checkpoint/smoke.sh
test/evergreen.yml

The Evergreen patch build link
https://evergreen.mongodb.com/task/wiredtiger_ubuntu1804_checkpoint_test_patch_7812adc84fee863cb2b1f594938f18a28572aa2b_5eba2af2d6d80a69d4cb00d6_20_05_12_04_50_13

WT-6083 Enable checkpoint-test and fix __wt_txn_set_commit_timestamp failure

---

src/txn/txn.c
test/suite/test_prepare09.py

…on disk prepared update reverted

WT-6224 Adding globally visible tombstone to the key when an on disk prepared update is reverted

---

test/evergreen.yml

Updated the WiredTiger waterfall page to order build variants.

WT-6286 Update Evergreen waterfall page to order jobs

---

src/history/hs.c

It's not 100% clear whether this fixes WT-6257 but this is definitely a bug.

WT-6318 Stop assuming exclusive access when writing to history store pages

---

src/conn/conn_api.c

is enabled in configuration.
This contains two fixes:
1. Moves where we do compatibility testing to just before opening the turtle file so all configuration processing is complete. This would fail if log files are encrypted.
2. Only do compatibility testing of logging is enabled in the configuration.
This is fallout from WT-6015.

WT-6324 Check compatibility after encryption and only check if logging

---

src/conn/conn_api.c

Reverts wiredtiger/wiredtiger#5725

Revert "WT-6324 Check compatibility after encryption and only check if logging"

---

src/btree/bt_import.c
src/conn/conn_api.c
src/conn/conn_log.c
src/conn/conn_open.c
src/conn/conn_reconfig.c
src/include/connection.h
src/include/extern.h

Reverts wiredtiger/wiredtiger#5700

Revert "WT-6015 Check compatibility after logpath and extensions are set up."

---

test/suite/test_checkpoint04.py

The test test_checkpoint04.py used to take ~0.12 seconds, I have updated the code to run the test in a loop and increase the data size until it passes.
Evergreen patch build https://evergreen.mongodb.com/version/5ed09ac02fbabe2d6baf9058

WT-6297 test checkpoint04 increase data size

---

test/format/format.h
test/format/ops.c

@keitharnoldsmith, a trivial cleanup if/when you resolve this ticket.

WT-6336 Minor cleanup in test/format buffer handling.

---

src/txn/txn.c

Reverts wiredtiger/wiredtiger#5746

Revert "WT-5769 Remove remaining usage of ignore visibility flag"

---

test/format/smoke.sh

Reverts wiredtiger/wiredtiger#5740

Revert "WT-6301 Add short running stress jobs"

---

src/include/btree.i

patch build for macos
https://evergreen.mongodb.com/task/wiredtiger_macos_1012_compile_patch_1799c524d79e9f2a7a108b3a818ce3baa1986ea8_5ed997177742ae5a920b4201_20_06_05_00_52_13

WT-6378 Fix MacOS build

---

test/format/config.c

Reverts wiredtiger/wiredtiger#5799

Revert "WT-6414 Block running rebalance with timestamps in test format"
