lang/python/wiredtiger.i
This should fix the deadlock issue seen during test_async.py by Mark Benvenuto and Jonathan Reams.
=> Release Python's global lock (GIL) during sleep.

lang/python/wiredtiger.i
This code in wiredtiger.i looks wrong:
```
/* Cursor compare can return any of -1, 0, 1 or WT_NOTFOUND. */
%define COMPARE_OK(m)
%exception m {
$action
if ((result < -1 || result > 1) && result != WT_NOTFOUND)
SWIG_ERROR_IF_NOT_SET(result);
}
%enddef
```
I don't think compare can return WT_NOTFOUND -- but, COMPARE_OK is used for search-near, too, not just compare.
=> Python: include WT_NOTFOUND as an error returned from CURSOR->compare.

mciproject.yml, test/mciproject.yml
This PR adds a MCI project file so we can add the wiredtiger develop branch into our CI system. The work is being tracked in https://jira.mongodb.org/browse/BUILD-479. Let me know if you have any questions or concerns.
=> Add MCI project definition

src/schema/schema_open.c
Fix memory leak: WT_TABLE.nindices wasn't being incremented in all cases, reference #1474.
@michaelcahill, this one is probably yours to review.  This fixes the test case in #1474, and passes the test suite, but I'm not 100% sure it's correct. Basically, the test case results in our opening an index but not incrementing `table->nindices`, resulting in failure to discard the index when the table is closed.
=> Fix memory leak: WT_TABLE.nindices wasn't being incremented in all cases.

src/btree/bt_split.c, src/include/txn.h, src/txn/txn.c
When restoring updates that could not be evicted, mark pages with the oldest possible first dirty transaction.  This guarantees that such pages can never be skipped by a checkpoint.
refs #1521
=> Fix test/checkpoint skipping dirty pages

dist/stat_data.py, src/btree/bt_delete.c, src/btree/bt_split.c, src/btree/bt_walk.c, src/include/btree.i, src/include/stat.h, src/include/wiredtiger.in, src/support/stat.c
Workloads that delete repeatedly from the beginning of the tree can leave many references to deleted pages. There was a bug where truncate was re-creating those pages as empty pages.
There is another issue that we never clean up internal pages with those deleted refs. This patch adds code into the internal split routine to clean up those refs if splitting a page. We could do this in a more general place (possibly when setting a WT_REF_DELETED in the normal path?).
For now this helps with my workload (SERVER-16775). I was seeing quite a deep tree in this workload, so I think it's also worth testing SERVER-16697 with this branch.
=> Free deleted internal pages

src/btree/bt_split.c
Special-case the root; if it's putting cache pressure on the system, split it even if there aren't many entries.
Drop __split_deepen_per_child back to 100, that way if we split, we split big.
=> Special case the root when deepening the tree.

src/btree/bt_split.c, src/include/btmem.h
Add a temporary hack to quit splitting a page if we're not making progress.
=> Add a temporary hack to quit splitting a page if we're not making progress.

src/conn/conn_log.c, src/log/log.c, src/txn/txn_log.c
Update the sync_lsn after sync'ing and closing an earlier log file and
make sure archive doesn't try to remove a file that is still in use.
Refs #1555 .
@michaelcahill We should talk this over.  Please review.
=> Update the sync_lsn after sync'ing and closing an earlier log file.

src/btree/bt_split.c
When deepening the tree, force the new parent page memory size to 5% of its current value, reference #1564.
=> When deepening the tree, force the new parent page memory size to 5% of its current value.

src/include/btree.i
Involves some complexity due to atomic operations.
References #1587 and BF-773
=> Don't allow cache tracking to wrap negative.

src/schema/schema_open.c, test/suite/helper.py, test/suite/test_drop.py
Fix drop index on a newly opened session - #1567.
Fix opening a cursor on a index name that doesn't exist.
Test cases to trigger these.
=> Fixes related to indices.

src/block/block_compact.c, src/include/block.h
@michaelcahill, this change is for your consideration -- basically, I changed compaction in the develop branch to make more passes over the object, as long as it looks like there's work to be done.
This change tries to compensate by making compaction move more data in each pass if it looks like that might work.
=> Aggressive compaction

src/txn/txn_ckpt.c
This avoids a potential deadlock during compact operations and/or checkpoints with a target list (and an assertion about lock ordering in diagnostic builds).
Note that nested locking is not ideal: the medium-term fix here is #1598.
refs #1589
=> Grab the table list lock while building the list of handles to checkpoint

src/os_win/os_map.c, src/os_win/os_open.c, src/os_win/os_thread.c
On Windows after a thread exits, there is still one last remaining reference to the thread handle, and a program is required to call CloseHandle to free the last reference otherwise there is handle leak. The last reference allows thread creators to check on the status of thread, etc.
Fixes SERVER-17025
=> Close Thread Handle after thread join on Windows

dist/api_data.py, src/config/config_def.c, src/docs/tune-durability.dox, src/include/wiredtiger.in
@michaelcahill This restores the old defaults of in-memory buffering instead of write-no-sync.  Please review.  It restores the performance of the `log_append.wtperf` workload also.
=> Restore default transaction_sync values. #1585 #1586

src/btree/bt_page.c, src/conn/conn_cache_pool.c, src/include/btree.i, src/include/cache.h
We previously tracked writes, which were skewed by checkpoints.
refs #1569
=> Use reads to measure cache pressure with shared caches

SConstruct, build_win/wiredtiger.def, src/include/wt_internal.h, test/mciproject.yml, test/windows/windows_shim.h
This is a set of improvements to the Windows build that @keithbostic asked for
1. Add various build flags to bring Windows build closer to parity like attach, diagnostic, and verbose.
2. Renamed --enable-swig to --enable-python and update MCI config.
3. Add a DLL, and linked some examples against it. @keithbostic Check the list of exported functions to see if they what you want
4. Ensure python is 64-bit
5. Add "*scons check*" for unit tests, and "*scons install*" targets
=> Scons Improvements

src/txn/txn_recover.c
... regardless of whether there are any updates to roll forward.
Previously, we tracked the largest file ID that was updated in the logs being rolled forward.  It was usually the case that the most recently created file was also the most recently updated, so that calculation usually worked and wasn't detected until the repro in SERVER-17142 that created tables, did a clean shutdown and restart, then created more tables and did a dirty shutdown and restart, which was rolling forward updates into the wrong tables.
refs SERVER-17142, SERVER-17131(?)
=> In recovery, track the maximum file ID in the metadata

src/btree/bt_cursor.c, src/btree/bt_debug.c, src/btree/bt_handle.c, src/btree/bt_slvg.c, src/btree/bt_split.c, src/btree/bt_stat.c, src/lsm/lsm_cursor.c
@michaelcahill Using your split-gen branch, I wrapped all the places I saw that were vulnerable with `WT_WITH_PAGE_INDEX`.
=> Wrap calls to functions using pindex with WT_WITH_PAGE_INDEX.

src/btree/bt_huffman.c, test/suite/test_huffman01.py, test/suite/test_huffman02.py
@keithbostic  Please review these changes for huffman.  I added a test for all the valid huffman config settings as well as invalid ones.
There was one minor bug fix to reset `ret` after reading the utf file.
One outstanding issue is I found in my test that I could not use hex in the frequency file as shown in the docs.  SCNu64 does not read hex.  You'll notice `test_huffman01.py` writes decimal.  We can fix the documentation or assume the values are hex, fix the code and document that requirement.
http://source.wiredtiger.com/2.5.0/huffman.html
=> Fix huffman config and add huffman tests. #1536

src/btree/bt_split.c
@agorrod, would you please check me on this one? It seems to me we can skip a pass over the page index in the common case. Sorry about the re-format, but I had to shuffle things a little to avoid getting really deep clauses.
=> Don't do a pass over the page index looking for deleted entries unless we found some in our initial pass.

src/btree/bt_handle.c, src/btree/bt_read.c
@agorrod, I think that if `__wt_delete_page_instantiate` fails in `__wt_cache_read`, we'll free the allocated disk image twice, and no good will come from that. Would you please take a look and see if I've missed anything?
=> Don't free the disk image twice on error.

dist/log.py, src/log/log_auto.c, src/txn/txn_log.c
Without that, any tool that parses JSON is almost certain to merge successive values of repeated fields.
Refs #1438.
=> For wt printlog, make operations into a JSON array.

src/block/block_open.c, src/conn/conn_handle.c, src/include/block.h, src/include/connection.h, src/include/os.h, src/os_posix/os_open.c, src/os_posix/os_remove.c, src/os_win/os_open.c, src/os_win/os_remove.c
Using hash buckets for the file handle and block lists saves us about 1.5-2.0 seconds off the test.  It was about 15.6 seconds and is now 13.6-14.0 seconds.
=> Add name_hash and hash bucket queues for fh and block. #1634

src/block/block_open.c
Refs SERVER-17204
The bug is that we weren't doing an fsync of the file after it was
created. Recovery assumes that if there are records for a particular
file, then it will exist on disk.
=> Fix a bug in table create. A crash could cause recovery to break.

src/reconcile/rec_write.c
=> Don't double-count the on-disk header size when setting split boundaries

src/reconcile/rec_write.c
(allowing room for a header).
refs #1655, #1656
=> Anothing split fixup: don't create a remnant larger than the split size

src/lsm/lsm_cursor.c
The bug caused us to re-open more cursors than necessary in open.
Related to fix: 439a655e
=> Fix a bug in LSM cursor open.

dist/api_data.py, src/config/config_def.c, src/include/wiredtiger.in
@agorrod When I looked at the change, it seemed odd that this was documented as a string type rather than an integer.  I explicitly set it to `type=int`.  Please review.
=> New chunk_count_limit is an integer. #1658 #1652

src/conn/conn_ckpt.c, src/conn/conn_stat.c, src/conn/conn_sweep.c
Check that we're still running before waiting.  This makes more sense to me, but also fixes a problem introduced recently where the checkpoint server could hang on shutdown if the signal from the closing thread got lost.
=> Move server thread waits to the beginning of their loops

src/include/api.h
@michaelcahill, Coverity complains about the `ret == 0` test at the end of the TXN_API_END_RETRY macro in half-a-dozen places in the code.
I'm pretty sure we don't need the `ret == 0`, I think the only path to the loop's test is the `ret = 0; continue` statement above it, but please check me.
=> TXN_API_END_RETRY cleanup.

dist/api_data.py, src/conn/conn_cache.c, src/evict/evict_lru.c, src/include/cache.h, src/include/cache.i, src/include/connection.h, src/include/wiredtiger.in
Flip cache overhead to apply to the allocated bytes rather than the total size.  Include the overhead in stats so that tools (e.g., mongostat) report accurate cache full and dirty percentages.  This also makes eviction triggers and targets meaningful: with the default trigger of 95% and overhead 8%, eviction was previously never triggered until the cache was completely full.
=> Flip cache overhead to apply to the allocated bytes

src/btree/bt_page.c, src/include/btree.i
@michaelcahill, feel free to discard anything you don't like, it's all semantic sugar.
=> Mongo eviction whitespace, minor cleanup.

src/evict/evict_lru.c, src/include/connection.h
This was previously permitted by the API, but the array of thread contexts was not correctly resized, leading to segfaults.
refs SERVER-17293
=> Allow the maximum number of eviction threads to be reconfigured

src/schema/schema_truncate.c
=> Get a local copy of the start/stop cursor keys before calling truncate.

src/reconcile/rec_write.c
In cases where we decide to squeeze one more large entry onto a page,
we could have attempted to decrement space available negative.
=> Fix a bug in reconciliation.

src/conn/conn_dhandle.c, src/include/extern.h, src/schema/schema_worker.c
The case that could return EBUSY was when checkpointing with a
specific target, while that target was open exclusively or for a bulk
load.
Refs #1404 #1589
=> Fix a bug in checkpoint, where it could get an EBUSY return.

src/cursor/cur_index.c, test/suite/test_dump.py
This fixes `wt dump` when the uri is an index.
=> When dumping indices, use raw mode

src/btree/bt_handle.c, src/btree/bt_page.c, src/conn/conn_dhandle.c, src/evict/evict_lru.c, src/evict/evict_page.c, src/include/btree.i, src/include/cache.h
* Don't update the read generation on page in if it's set to oldest.
* Clear the walk positions before the eviction server sleeps.
* If only looking for pages that would block add them all to the queue.
* If evicting dirty pages use the worker threads, not the server.
=> Several optimizations to large page eviction:

src/include/btree.i, src/reconcile/rec_write.c
When reconciling column store internal pages, deal with the "ignore" case.
=> Ignore empty child pages in column stores

src/async/async_worker.c, src/include/extern.h, src/os_posix/os_mtx_cond.c, src/os_posix/os_sleep.c, src/os_win/os_mtx_cond.c, src/os_win/os_sleep.c
Change the usage of long to uint64_t since long is platform specific. Also, fix the __wt_cond_wait code to ensure we handle integer overflow when converting from 64-bit to 32-bit types.
=> SERVER-17471: Use uint64_t instead of long since long is compiler specific

test/suite/test_txn10.py
File locks on Windows are not advisory like they are on Posix so skip the copy of WiredTiger.lock.
=> Fix file sharing error in test_txn10

src/evict/evict_file.c, src/evict/evict_page.c, src/include/btree.i, src/include/session.h, src/session/session_api.c
@michaelcahill, you wanted me to review empty-page handling in the context of support-1248 branch, and I did that -- I don't see any problems.
While I was looking at it, I thought I'd take a run at removing the special processing for `WT_PM_REC_EMPTY` pages in the `WT_SYNC_CLOSE` case. Since that's the last use of parent/child page merging in eviction, a whole bunch of complexity in `evict_file.c` seems like it can go away.
=> Eviction processing simplification.

src/btree/bt_huffman.c, src/config/config.c, src/docs/config-strings.dox, src/docs/spell.ok, src/docs/upgrading.dox, src/include/misc.h, src/include/os_windows.h, src/lsm/lsm_meta.c, test/suite/test_huffman01.py
@michaelcahill, we talked about getting case-sensitivity consistency for WiredTiger configuration strings, and you indicated you'd prefer being globally case-sensitive rather than case-insensitive.
Here are the changes to remove the relatively few places where we did case-sensitive comparisons of configuration strings.
Obviously, this raises portability questions, but those won't get better if we wait to make this change, and since we just recently modified the Huffman configuration code, it seems like making the change now is the right thing to do.
=> Remove pockets of case-sensitivity for configuration strings.

src/btree/bt_split.c
=> Don't cache an ikey before winning the race to split into a parent.

src/docs/command-line.dox, src/utilities/util_main.c
Here's a small change and doc changes (also fixes a typo in current docs which say `-r` and the real arg is `-R`) to turn off logging for debugging purposes.  @michaelcahill Please review.
=> Support no-logging mode in wt command for debug. #1732

src/btree/bt_handle.c, src/btree/bt_split.c
Allow a page that it using more than 1/4 of the cache to be split.
Refs #1759
=> Update the split deepen sanity check.

src/os_win/os_sleep.c
@markbenvenuto and @keithbostic can you review this change?  Mark, please compile to make sure I didn't mess anything up.  It seems that sleep with a 0 value has special meaning that does not seem to be what we intend with a small timeout value. 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686298%28v=vs.85%29.aspx
Or if I'm off-base we can just toss this branch.
=> Fix microsecond to millisecond conversion if small value given. #1764

src/session/session_dhandle.c
The sweep server relies on there being a retry loop if an exclusive operation such as verify conflicts with a sweep.
refs #1404
=> If the session-level attempt to lock a handle gets EBUSY, fall back to the slow path

src/packing/pack_stream.c
Lower layers treat size == 0 as unchecked.
refs #1714
=> Add length checks to the WT_PACK_STREAM API

src/session/session_api.c, src/session/session_dhandle.c
=> Avoid EBUSY errors from truncate caused by checkpoints.

bench/wtperf/runners/parallel-pop-stress.wtperf, src/evict/evict_lru.c
When only looking for pages to force out, the cache isn't really stuck.
The trouble is that if we set stuck the eviction server doesn't clear walks
which can lead to it always holding a reference t othe page we (really) want
to evict.
Refs: #1777
=> Update the eviction server to not set stuck if it isn't full.

SConstruct, src/include/os_windows.h
VS 2015 defines timespec, but VS 2013 does not define it.
By using MSVC_USE_SCRIPT, you can choose which MSVC compiler to target.
=> Visual Studio 2015 Preview support

test/format/s_dumpcmp.sh
@michaelcahill, it occurred to me, with the base config file format's dump script no longer needs to configure all of the shared libraries explicitly?
My shared-library-fu is weak, though, and I'm not sure how format is run everywhere, does this look correct to you?
=> format dump script cleanup

dist/api_data.py, src/config/config_def.c, src/cursor/cur_index.c, src/include/schema.h, src/schema/schema_list.c, src/schema/schema_open.c
While in the area, add support for WT_CURSOR::compare and WT_CURSOR::equal to index cursors.
refs #1714
=> Use the configured collator when index cursor need to compare keys.

src/include/error.h
@michaelcahill, I got bitten today because `WT_ERR_TEST` doesn't clear ret (`WT_ERR_BUSY_OK` and `WT_ERR_NOTFOUND_OK` do).
I changed `WT_ERR_TEST` to clear `ret` and then implemented the other functions using it.
I don't feel strongly about this, if you don't like it, I'm good with just throwing it away.
=> Clear "ret" in WT_ERR_TEST.

src/conn/conn_dhandle.c
Reverts wiredtiger/wiredtiger#1808
The change looks solid to me, but appears to be causing Jenkins failures. I can't reproduce them locally. Revert for now.
=> Revert "Avoid a deadlock between the sweep server and a checkpoint."

src/conn/conn_dhandle.c, src/conn/conn_sweep.c
One pass walks the handle list without locking and finds candidate handles to close, and the second pass holding the handle list lock that removes dead handles.
refs #1814, #1811, #1808
=> Split sweep into two passes

ext/compressors/zlib/zlib_compress.c
@michaelcahill, saw a way to decrease the number of deflateCopy/deflateEnd calls, figured it might help when you benchmarked this against the other version.
=> Decrease the number of deflateCopy/deflateEnd calls.

lang/java/Makefile.am, lang/python/setup.py
@keithbostic noticed that an internal file that does `#include <3rdparty/...>` causes the python/java builds to fail. This is because the java `Makefile` and python `setup.py `did not have `-Isrc/include` on the build line. This commit this fixes that.
It probably worked up to now because the SWIG modules use `#include "src/include/wt_internal.h"` and the top level directory is on the build line and other include files are found directly on that directory. Blame the complexity of gcc/clang include rules for why including a file in a subdirectory behaves differently.
=> Fix include file paths in lang/{java,python}

dist/s_string.ok, ext/compressors/zlib/zlib_compress.c
We need to copy zlib streams for rollback in case the compressed size is too large.  It is not safe to do that by simply making a copy of the structure: use `deflateCopy` instead.
refs SERVER-17713
=> Use deflateCopy to copy zlib streams

src/include/packing.i
If all bytes are consumed and the next field is an integral type, we could read beyond the end of the buffer.
refs #1714
=> Add explicit size checks to public pack/unpack code

SConstruct
LZ4 is not on by default in scons. It can only be enabled if a user specifies `--enable-lz4=<path_to_lz4_files>` where path_to_lz4_files contains these files
`<path_to_lz4_files>\include\lz4.h`
`<path_to_lz4_files>\lib\lz4.lib`
=> Revert "Make LZ4 default off in scons builds for now."

ext/compressors/zlib/zlib_compress.c
Use the Standard C type uint64_t for zlib_compress.c instead of the posix type u_long.
=> Use Standard C type uint64_t for zlib

src/btree/bt_split.c
It doesn't make sense for us to call split free while blocking it from freeing the memory immediately ourselves.
=> Add an assert to the split free method.

build_posix/configure.ac.in, build_win/wiredtiger_config.h, dist/s_string.ok, src/include/btree_cmp.i, src/include/wt_internal.h
Changes to remove the `pthread_np.h` include file from WiredTiger's build, and use the `x86intrin.h` include file to configure the vectorization instructions.
@sueloverso, would you please confirm this build works on your laptop, and if it does, merge it?
@agorrod, @michaelcahill: I added `pthread_np.h` to the build in commit 562ae1f, to support the use of `pthread_timedjoin_np`, as far as I can tell, we no longer use any pthread_XXX_np functions.
=> Build fixes

src/log/log.c, test/suite/test_cursor07.py
@michaelcahill Please review.  The fix specifically for the test failure is reseting `eol` if we read the next log file.  I also added a fix so that if a checksum doesn't match and we asked specifically for a record we return `WT_NOTFOUND` (the case of a log cursor setting an invalid LSN and calling search()).  I also bumped up the keys in `test_cursor07.py` that showed the problem.
=> Reset eol if we continue.  Return NOTFOUND if checksum mismatch. #1840

src/os_win/os_fallocate.c, test/format/config.c, test/format/util.c, test/format/wts.c
- Fixed an issue where fallocate was setting fh->size (incorrectly copied from ftruncate implementation)
- Send delete and copy output to :nul (aka /dev/null)
- Skip BDB verification for now
=> test/format for Windows

SConstruct, test/fops/t.c, test/fops/thread.h, test/mciproject.yml, test/windows/windows_shim.c, test/windows/windows_shim.h
Added Windows shim for gettimeofday
fops is added to CI system. Also, used cheaper test machines.
BTW, on Windows, setvbuf does not accept 0 as a valid value.
(New pull request because I forgot to run s_all on this branch, and force pushing the previous PR closed it.)
=> Enable test/fops for Windows, and add to CI

bench/wtperf/config.c, bench/wtperf/wtperf.c, bench/wtperf/wtperf_opt.i, src/docs/wtperf.dox
The option causes wtperf to create table_count_idle tables before
populate, and to open/close a cursor on each of those tables at
the start of the workload phase.
=> Add a table_count_idle option to wtperf.

src/os_win/os_fallocate.c
The Windows fallocate call will now ignore requests to truncate the file by checking if the new requested size is less than the current size of the file.
=> fallocate should ignore requests to truncate the file

src/os_win/os_fallocate.c
Since SetEndofFile does not ignore truncation requests like POSIX fallocate, after discussions with @keithbostic, we decided it was best to disable fallocate on Windows.
With #1873, and the change, I was able to get ~700 successful runs of test/format.
=> Disable fallocate on Windows

src/conn/conn_api.c
Reconfiguring sweep and then reconfiguring something else will cause the sweep configuration to fall back to its base values.
@michaelcahill, we have made this mistake before, so I thought I'd re-use `cfg` instead of a local variable. I think that's OK, but can you take a quick look?
=> Fix a bug in sweep reconfiguration

src/cursor/cur_bulk.c, src/cursor/cur_file.c
We were missing a decrement that kept bulk-loaded files pinned.  Found by @agorrod while testing #1878.
=> Merge bulk cursor close with regular file cursor close

src/btree/bt_curnext.c, src/btree/bt_curprev.c, src/btree/bt_cursor.c, src/btree/bt_ret.c, src/btree/bt_split.c, src/btree/row_srch.c, src/cursor/cur_file.c, src/include/cursor.h, src/include/cursor.i, src/include/extern.h
@michaelcahill, here's the fix for #1887.
It may be worth looking at why LSM is doing this and there may be an improvement to make there: I think this failure only happens if a search is repeated, that is, a search on a key returns an exact match, and the search is repeated without resetting the key (so I think the cursor is guaranteed to end up in the same location).
=> Defend against row-search calls using a returned key

src/lsm/lsm_cursor.c, test/suite/test_bug013.py
References JIRA BF-829
The issue was that we were not looking in all chunks of an LSM
tree before deciding whether to apply an update (insert or remove).
=> Fix a bug in LSM where updates with overwrite could be skipped.

src/include/schema.h
There is special code in LSM to co-ordinate schema operations on
tables (drop, rename, etc). The code does a dance dropping and
acquiring locks, to allow utility operations to drain for the tree
while waiting for it to close.
We were doing the dance with the schema and dhandle list locks. We
needed to include the table lock, or parallel cursor opens could block:
The cursor open is waiting for the table lock:
__wt_spin_lock src/include/mutex.i:175
__schema_add_table src/schema/schema_list.c:26
__wt_schema_get_table src/schema/schema_list.c:98
__wt_curtable_open src/third_party/wiredtiger/src/cursor/cur_table.c:875
__wt_open_cursor src/session/session_api.c:240
The LSM table drop is waiting for the schema lock:
__wt_spin_lock src/include/mutex.i:175
__lsm_tree_close src/lsm/lsm_tree.c:107 …
=> Fix a deadlock in LSM with schema operations.

src/lsm/lsm_cursor.c
If an LSM search-near operation lands on a deleted item, make a copy of the key before stepping to the next record.
refs WT-1891
=> Fix LSM search_near landing on a deleted record

dist/api_data.py, src/include/wiredtiger.in
This allows users to account for internal WiredTiger session handle usage. We already allocate additional handles for those we use unconditionally. This allows users to do specific calculations based
on their session_max setting.
=> Update API documentation to tell explain session usage.

src/conn/conn_open.c
@michaelcahill Please review this change to run recovery earlier in the wiredtiger_open path.  I moved it before the async and sweep threads were started.
=> Run recovery earlier. WT-1897

src/include/extern.h, src/include/txn.i, src/txn/txn.c
@michaelcahill, would you please review this change?
Some of my zoom profiles show us spending time in `__wt_config_gets_def` when creating auto-commit transactions, and it's pretty easy to avoid.
There's one subtle change here, I moved the `F_SET(txn, TXN_RUNNING);` code after the handling of `txn->isolation == TXN_ISO_SNAPSHOT`.
It looked safe and I think it's cleaner, but I wanted to call it out in case there was something I missed (in which case, I think it needs a comment).
=> Split __wt_txn_begin into two parts

SConstruct, build_posix/aclocal/options.m4, build_win/wiredtiger_config.h, dist/s_string.ok, src/os_posix/os_alloc.c, src/os_win/os_fallocate.c
After considerable investigation, the default Windows allocator takes a critical section for allocators >= 16 KB which significantly impacts performance as compared to an alternate malloc implementation. I have added support for TCMalloc because it is what MongoDB vendors. This has shown improvement on several workloads for MongoDB. I did not investigate JEMalloc.
See  Jira WT-1904, SERVER-18079 for performance investigations.
=> TC Malloc for WT

src/conn/conn_sweep.c
exceed the minimum configured number.
Tidy some comments/naming/control flow in the sweep server at the
same time.
=> Allow dead handles to be closed even if open handle count doesn't

lang/python/wiredtiger.i
Starting to make "pydoc wiredtiger" give better results.
=> Fix a typo, add what will be a description section for pydoc

src/include/misc.h, src/txn/txn.c
@michaelcahill, we're spending cycles calling qsort() on typically small numbers of items, so I inlined the case where we have 2 items (wtperf's common case), and less than 11 items. A good implementation of qsort will simply do an insertion sort on small numbers of items anyway, but that still requires the qsort setup and then repeated calls to the qsort callback function.
=> Add insertion-sort to sort snapshots

dist/s_string.ok, src/conn/conn_log.c
@sueloverso, if @michaelcahill takes the `sort-snapshot-insertion` branch, here are the changes (entirely untested!) to switch the log slot sort from qsort to insertion sort.
=> Change the sort of the log's slot array from qsort to insertion sort

src/txn/txn.c
@michaelcahill, this instruction is about 5% of the in-memory wtperf run-time.
I'm guessing this change might not be safe, so I put it on a separate branch to make it easy to discard.
=> The checkpoint ID is volatile, cache it so we don't keep reading it.

dist/s_docs, src/docs/command-line.dox
This removes a doubling of the word "Version" in the "wiredtiger" and "wt" manpages, and makes the section headers for the "wt" manpage more normal. I wanted to do the same for the wiredtiger manpage, but it'd be more disruptive to the structure of the docs they're generated from (so it remains a very weird looking manpage). Other options:
1) Remove the wiredtiger.3 manpage
2) Replace it with a pointer to generated docs in another format
3) Generate both manpages a more traditional way - I'm willing to do the work on this
=> Manpage improvements

dist/s_string.ok, src/include/connection.h
=> Use a prime number as the hash table size

src/btree/row_modify.c, src/include/btmem.h, src/include/extern.h, src/include/serial.i
There can potentially be long chains of updates that cannot be freed: there is no point repeatedly scanning them.
refs WT-1913
=> Avoid obsolete update checks during long-running transactions

src/btree/bt_handle.c, src/conn/conn_dhandle.c
Hopefully this will fix a hard-to-reproduce leak found recently by valgrind.
refs WT-1598
=> If we get part way through a btree open then fail, make sure the checkpoint is unloaded

src/btree/bt_handle.c, src/conn/conn_dhandle.c
Specifically if closing a checkpoint handle. This manifested by a
segfault opening a handle for a merge in LSM.
Refs WT-1915
=> Fix a bug in handle close, where we could fail to clear WT_DHANDLE_OPEN.

src/btree/bt_cursor.c
(Or the last record in the table if there is no valid record after the search point).  This avoids a call to search_near when there may be no key set.
refs WT-1921
=> If a random lookup lands on a deleted item, move to the next valid record

src/btree/bt_page.c, src/conn/conn_open.c, src/evict/evict_file.c, src/evict/evict_lru.c, src/include/extern.h, src/lsm/lsm_work_unit.c, src/txn/txn.c, src/txn/txn_ckpt.c
In case eviction isn't running (e.g., during forced eviction checks).
refs WT-1907
=> Add a "soft update" of the oldest ID from application threads

src/lsm/lsm_cursor.c, src/lsm/lsm_cursor_bulk.c, src/lsm/lsm_tree.c, src/schema/schema_drop.c, src/schema/schema_rename.c
Otherwise races with metadata operations can fail.
Refs WT-1924
=> Ensure the metadata is flushed when closing an LSM bulk cursor.

src/conn/conn_api.c, src/include/extern.h, src/schema/schema_create.c, src/schema/schema_open.c, test/suite/test_bug012.py
@michaelcahill, you said:
> the usual pattern is to create the object, including setting the metadata, then try to open it (which does the validation). If the open fails, the create is rolled back.
This backs out a change to detect unknown extractors during WT_SESSION.create.
=> Ignore unknown extractors during WT_SESSION.create.

src/txn/txn_ckpt.c
If we're closing a dirty tree in order to verify it (or any other exclusive operation), make sure the changes are stable on disk in case there is a crash.
refs SERVER-18316
=> Add an fsync before verifying tables

src/lsm/lsm_tree.c, src/lsm/lsm_work_unit.c
The recent bulk load change meant that we sometimes created a bloom
filter on the oldest chunk when running compact.
Caused performance to drop by 50% in wtperf medium lsm compact job.
=> Don't create bloom filters on the oldest chunk unless configured.

src/evict/evict_lru.c
Found via a stack trace in the referenced issue, but not the cause of the crash.
refs SERVER-18460
=> Never evict during an LRU walk, including when clearing the walk point.

src/conn/conn_dhandle.c, test/fops/file.c, test/fops/fops.c, test/fops/thread.h
We've seen failures that look like this:
```
2015-05-15T06:30:02.354+0000 E STORAGE  WiredTiger (2) [1431671402:354440][6611:0x2b3e7dfe7940], checkpoint-server: checkpoint server error: No such file or directory
2015-05-15T06:30:02.354+0000 E STORAGE  WiredTiger (-31804) [1431671402:354533][6611:0x2b3e7dfe7940], checkpoint-server: the process must exit and restart: WT_PANIC: WiredTiger library panic
```
This branch enhances `test/fops` to randomly do forced drops to exercise this path (it quickly reproduced the failure), plus adds the fix.
=> Don't checkpoint dead handles

test/format/config.c, test/format/config.h, test/format/format.h, test/format/wts.c
Stress testing had block compression, this change adds log compression, with some refactoring.  Likewise, overall 'system' encryption is added.
=> Add encryption and log compression to stress testing

src/lsm/lsm_manager.c, src/lsm/lsm_tree.c
A worker thread could push a new work unit during shutdown, which
could lead to a work unit being processed after the underlying tree
was freed.
refs WT-1935
=> Fix a race on shutdown in LSM.

src/include/log.h
Mark log slot state volatile so optimizing compilers don't cache the first read value and get stuck.
refs WT-1938
=> Fix a hang in __wt_log_slot_join

src/log/log_slot.c
Otherwise the compiler can decide not to refresh a local variable
and we never see a state update.
refs WT-1938
=> Add a read barrier to __wt_log_slot_join to avoid a hang.

src/include/btree.i
@michaelcahill, I took a look today at clearing WT_REF.page during page release -- in short, it's not going to happen, there's too much sync and eviction code that knows hazard pointers aren't necessary once the WT_REF is locked or the file is single-threaded, and expect WT_REF.page to be available.
I did make the change so there's no chance a software bug will release a non-existent hazard pointer after WT_REF.page has been cleared.
And, a couple of trivial cleanups I spotted along the way, both for your review.
=> Minor cleanups to page-release.

src/include/txn.i, src/reconcile/rec_track.c
Export a function to get the oldest transaction ID that needs to be tracked for a given tree.  Managing cached overflow items was using the oldest transaction ID, but the meaning of that field changed.
This fixes a bug that was introduced by WT-1745, that requires a combination of many overflow values, eviction and checkpoints, but can lead to unexpected WT_NOTFOUND errors during reconciliation.
=> Export a function to get the oldest transaction ID

src/cursor/cur_log.c
http://build.wiredtiger.com:8080/job/wiredtiger-test-format/4201/console
refs WT-1936
=> Map ENOENT to WT_NOTFOUND in log cursors.

src/os_posix/os_open.c
The logging code is the only caller of `__wt_open` with `WT_FILE_TYPE_DIRECTORY` and it passes in the correct path, but `__open_directory` was stripping the last component.
refs WT-1941
=> Sync the log directory when creating log files, not its parent

src/lsm/lsm_cursor_bulk.c
Otherwise LSM tends to choose poor merges after a bulk load,
which leads to degraded performance.
Refs WT-1947
=> Calculate a merge generation for bulk loaded LSM chunks.

src/conn/conn_api.c, src/cursor/cur_backup.c, src/meta/meta_turtle.c
@michaelcahill, this is a set of changes around database creation. The bug fixes are:
1. WT-1943, don't write the base configuration file if not also creating the database.
2. Don't create the lock file unless also creating the database, so mis-typing a home directory to the `wt` command or other WiredTiger application doesn't litter a random directory with a lock file (this necessitated an additional change, backups now have to copy the lock file to the backup directory).
3. Change "is-new" to test for the final result of database initialization (the creation/rename of the turtle file) instead of the creation of the WiredTiger lock file, so that if we crash in the middle of the process, a subsequent open doesn't incorrectly NOT set is-new.
Some comments:
* By not creating the WiredTiger …
=> Database creation

src/txn/txn.c
Release is the last thing a transaction does - so all state should
be cleared upon release.
=> Clear all transaction flags on release, not a subset.

build_posix/aclocal/ax_func_posix_memalign.m4, build_posix/configure.ac.in
Add code from the autoconf archive to detect `posix_memalign` instead of relying on AC_CHECK_FUNCS.
refs WT-1951
=> Fix configure checks for posix_memalign

src/include/txn.i, src/txn/txn.c
refs  WT-1949
@michaelcahill Although this is a tiny diff, please carefully review.  I explain what is happening in the Jira ticket.  This feels a tiny bit hacky to me, but some of that is due to how the config code assumes the inheritance from the connection, and changes defaults based on that.
=> If we have no config, explicitly check for flushing and clear txn_logsync

src/include/btree.h, src/include/extern.h, src/log/log.c, src/txn/txn_ckpt.c, src/txn/txn_log.c
WT-1944
@michaelcahill I have put the flag back in to only skip idle checkpoints if it was actually skipped, not just based on the modified flag.  Your change in changeset ff56ae5dd686c is causing the second issue in WT-1944.  That change is too broad.  The symptom is that repeated runs of recovery are not forcing a metadata update even though the recovery code uses "force=1".  The change you put in loses the "force" setting and we never updated the metadata, and its checkpoint LSN never advanced.  Please review again.  If you don't like this approach we can discuss alternatives.
=> Only skip metadata checkpoint if we really skipped it, not force.

src/conn/conn_api.c
@sueloverso, for your review.
I don't see any easy way to create a configuration string to do this work, but it's only in one place, so it's probably OK to inline it?
=> Strip out the "log=(recover=)" configuration from the base configuration file.

ext/compressors/lz4/lz4_compress.c
The new LZ4 code will not compile under windows as we are missing an override of "inline" to avoid C2054 errors.
@agorrod and @markbenvenuto can you have a look at this? The logic here is the same as for zlib.
=> Add fix for C2054 to lz4_compress

dist/api_data.py, src/config/config_def.c, src/cursor/cur_stat.c, src/include/connection.h, src/include/wiredtiger.in, src/lsm/lsm_stat.c, test/suite/test_stat01.py
Add a "statistics=(size)" mode to statistics cursors that just gets the filesize without opening anything.
refs SERVER-17078
=> Add a "statistics=(size)" mode to statistics cursors

build_posix/aclocal/ax_func_posix_memalign.m4
@michaelcahill, did you have a test you ran to integrate the AX_FUNC_POSIX_MEMALIGN macro, could we re-run that test?
=> AC_TRY_RUN is obsolete.

src/block/block_open.c, src/cursor/cur_stat.c, src/include/extern.h
@michaelcahill, I think this work should be in the block manager, for clarity.
Thoughts?
=> Move the statistics=(size) support into the block manager

dist/api_data.py, src/block/block_mgr.c, src/block/block_vrfy.c, src/btree/bt_vrfy.c, src/config/config_def.c, src/docs/upgrading.dox, src/include/block.h, src/include/extern.h, src/include/wiredtiger.in, test/format/wts.c
=> Change WT_SESSION.verify to not error on leaked blocks, by default.

src/btree/bt_page.c, src/evict/evict_lru.c, src/include/cache.h, src/include/cache.i
Also make sure that when eviction first needs to run, it can find some pages to
evict.
=> SERVER-18829 Have pages start in the middle of the LRU queue for eviction

src/include/gcc.h
Based on patch submitted in WT-1942
I haven't tested that this even compiles on PPC64 - we need to figure
out how to do that regularly before merging this change.
=> Add atomic implementations for PPC64 architecture.

src/conn/conn_log.c, src/log/log.c
@michaelcahill Please review this fix.  As I was not able to repro the failure, I found this by code inspection.
=> WT-1975 Wait for sync_lsn of earlier log files to complete for forced sync.

src/conn/conn_log.c, src/log/log.c
@michaelcahill or @agorrod please review this small diff.  While investigating WT-1962, I discovered we were clearing log->prep_missed at the wrong time.  I also moved where we incremented it to where a clearer, more readable location.
=> WT-1962 Fix usage of log->prep_missed.

lang/java/wiredtiger.i, test/java/com/wiredtiger/test/AutoCloseTest.java
Limit when we use a saved JNIEnv pointer (basically the JNI abstraction of a Java thread). When we have a JNIEnv pointer available from an explicit close call, use that. When we are implicitly closing a session or cursor, use the connection's JNIEnv pointer.  Add tests for this, and some code comments.
=> WT-1964: In Java fix session/cursor close in different thread than open

test/format/config.h, test/format/format.h, test/format/salvage.c, test/format/wts.c
This can be handy when reproducing failures that aren't uncovered
with verify/salvage, since it decreases the runtime for a single pass.
=> Add ability to turn verify and salvage off in test/format.

test/suite/test_backup05.py
@michaelcahill Please review this PR to implement a test for the fsyncLock strategy.  In particular I currently do a shutil.copytree and that may have problems on Windows (based on the comment in test_durability01.py that I based this on).  I updated the doc because if skipping the WiredTiger.lock file is going to be an issue, it'll need to be documented in some clear way (non-Windows can do 'cp -r', Windows will have to walk over each file name and skip that one).
=> SERVER-18899 Add unit test to simulate fsyncLock.

src/btree/bt_sync.c, src/evict/evict_lru.c, src/evict/evict_page.c, src/include/btmem.h, src/include/txn.h, src/include/txn.i, src/reconcile/rec_write.c, src/txn/txn.c, src/txn/txn_ckpt.c
... leading to reconciliation failing with WT_NOTFOUND.
=> WT-1982 Track down cached overflow items that are being freed too early

src/btree/bt_sync.c, src/reconcile/rec_write.c
@michaelcahill, I was staring at this code this morning, and it seemed like it would be easier (safer?) to set the tree's maximum transaction ID when we set/update the page's maximum transaction ID.
The "safer" part may be a misunderstanding on my part: the WT_BTREE.rec_max_txn field is used by sweep and close, but it's only set as part of the checkpoint operation.
But what if, by the time we get to checkpoint (WT_SYNC_CHECKPOINT), there aren't any leaf pages to write. Is it possible we won't update the tree's maximum transaction ID, since internal pages don't have a maximum transaction ID?
=> track the tree's max-txn-ID in reconciliation, where the page's max-txn-ID is set.

src/conn/conn_cache_pool.c, src/evict/evict_lru.c, src/include/cache.h
The old code implicitly assumed at least 10 members. The new
code uses a pressure based on a percentage of the most active
member.
refs WT-1966
=> WT-1966 Change how the shared cache assigns priority to participants.

src/include/txn.i
Fix a 64-to-32-bit conversion warning while in the area.
=> WT-1982 Avoid unnecessary read barriers in transaction code

test/suite/helper.py, test/suite/test_backup05.py, test/suite/test_durability01.py
This commit makes a small change, but the main function is to put the correct JIRA ticket into the comment stream (the previous commit used a bad ticket id in the comment).
@sueloverso, can you review?  This is the best I can do to fix the errant comment comment reference.  When develop is merged into master, perhaps the previous commit can be squashed into this one.
=> SERVER-18899 followup to abstract copying a WT home directory into a function.

lang/java/Makefile.am, lang/java/src/com/wiredtiger/db/PackFormatInputStream.java, lang/java/src/com/wiredtiger/db/PackInputStream.java, lang/java/src/com/wiredtiger/db/PackOutputStream.java, lang/java/wiredtiger.i, lang/python/wiredtiger/packing.py, test/java/com/wiredtiger/test/ExceptionTest.java, test/java/com/wiredtiger/test/PackTest.java, test/java/com/wiredtiger/test/PackTest02.java, test/java/com/wiredtiger/test/PackTest03.java, test/java/com/wiredtiger/test/WiredTigerSuite.java
This set of commits adds more extensive packing tests (PackTest02, PackTest03) for Java and fixes various problems that came up in resolving the new tests:
* The basic PackTest does positive/negative numbers, so needs to use 'q' (signed format).
* Fixed bugs in packing/unpacking bytearrays: we must be aware of 'U' format; when length is provided in format, use it; do padding.
* Fixed signed checking for getInt/Long/Short.
* Added special case encoding for 8256 (to match Python and C), this is the original problem reported in WT-1985.
* Fixed bugs in packing strings: embedded nulls; use length when provided.  Logic copied from packing.py.
* Java's Cursor.reset() more completely resets the cursor - removes the state of any incompletely packed/unpacked items.
=> WT-1985. Integer packing and other fixes for Java

dist/s_copyright
WT-2006
@agorrod, for your review.
`s_copyright` wasn't running on FreeBSD, and checking it over I think I found some problems.
Note, the final commit isn't a bug fix, but it reworks the script so we only create a single copy of the copyright template files.
One thing I didn't change: in the check() function, there's this code:
```
if expr "$1" : '*3rdparty*' > /dev/null; then
return;
fi
if expr "$1" : '*node_modules*' > /dev/null; then
return;
fi
```
There's already code in the parent find that uses sed to remove directories from the copyright list we check:
```
(cd .. && find [a-z]* -name '*.[chi]' \
-o -name '*.cxx' \
-o -name '*.in' \
-o -name '*.java' \
-o -name '*.py' |
sed -e '/Makefile.in/d' \
-e '/^build_posix\//d' \
-e '/api\/leveldb\/basho\//d' \
-e …
```
=> WT-2006: s_copyright fixes

dist/stat_data.py, src/include/extern.h, src/include/log.h, src/include/stat.h, src/include/wiredtiger.in, src/log/log.c, src/log/log_slot.c, src/support/stat.c
@agorrod, please review this branch for log slot buffer memory.  This one uses the same 256kb max size, but just statically allocates that right away.  It removes a bunch of code.  Please compare to #2061.  Only one (or none if we want another approach for now) should be merged.  The other should be closed and rejected.
I tested both with a wtperf config that used value sizes of 100k to force log slot overflow.
=> WT-2007 Statically allocate log slot buffers to a maximum size.

test/format/Makefile.am, test/format/config.h, test/format/format.h, test/format/lrt.c, test/format/ops.c
WT-1967: Add support for a long-running, isolation=snapshot, reader.
@agorrod, if you want to see the long-running reader in action, this branch can do that.
Here's the CONFIG:
```
cache=2
checkpoints=0
compression=none
data_source=file
file_type=row
internal_page_max=9
leaf_page_max=9
logging=0
long_running_txn=1
ops=1000000
rows=10000
runs=1
salvage=0
threads=2
verify=0
write_pct=80
```
Do a quick mod like this:
```
diff --git a/test/format/lrt.c b/test/format/lrt.c
index a00a4e0..3b9b856 100644
--- a/test/format/lrt.c
+++ b/test/format/lrt.c
@@ -69,6 +69,8 @@ lrt(void *arg)
/* Sleep for some number of seconds. */
period = mmrand(NULL, 1, 10);
+               fprintf(stderr, "\n" "%s " "%u" "\n",
+                   pinned ? "pinned" : "unpinned", period);
/* Sleep for short periods so …
```
=> WT-1967: Add support for a long-running, isolation=snapshot, reader thread

src/block/block_open.c
The problem was that a hard system crash could cause a file to not
be created, even though it had been synced. The solution is to do a
directory sync each time a new file is created.
=> WT-2008 Fix a bug in recovery where a file create went missing.

src/txn/txn.c
This will help keep the oldest tracked transation ID from falling too far
behind, particularly in single-threaded workloads.  That means we can keep
trimming obsolete updates, preventing pages from growing too large.
=> SERVER-19445 Have the oldest transaction update the oldest tracked ID.

src/meta/meta_track.c
In particular, don't remove dropped files until the metadata changes are durable.
=> WT-2009 Apply tracked metadata operations post-commit

src/btree/bt_io.c, test/suite/test_encrypt04.py
Fix to detect the case when encryption is specified when reopening, but the system was originally started without encryption.  Also added tests for the same.
=> Encryption mismatch checks

dist/stat_data.py, src/conn/conn_log.c, src/include/extern.h, src/include/log.h, src/include/stat.h, src/include/wiredtiger.in, src/log/log.c, src/log/log_slot.c, src/support/stat.c
@michaelcahill Please review this diff. It is essentially the "patch2" with a few changes.  With this patch, compared to develop I see the following performance (ops/sec) running Bruce's workload (on the AWS SSD).
Client threads:|Dev|Branch|difference
--------------------|---|-----|---------------
8 | 109 | 92 | -16%
16 | 125 | 151 | +21%
24 | 117 | 143 | +22%
32 | 121 | 126 | +4%
64 | 120 | 111 | -8%
=> WT-1989 Log scalability

src/include/log.h, src/log/log_slot.c
Fixes:
log/log_slot.c:62:3: error: conversion to 'size_t' from 'wt_off_t' may change the sign of the result [-Werror=sign-conversion]
=> WT-1989 Use size_t for the log slot size in memory.

src/include/gcc.h
Developed by analogy, particularly with:
http://lxr.free-electrons.com/source/arch/x86/include/asm/barrier.h
http://lxr.free-electrons.com/source/arch/arm64/include/asm/barrier.h
and
http://lxr.free-electrons.com/source/arch/x86/include/asm/processor.h#L692
http://lxr.free-electrons.com/source/arch/arm64/include/asm/processor.h#L130
Interestingly, linux doesn't seem to use sleep on x86.
=> WT-2013 Add gcc asm definitions for ARM64

src/include/mutex.h, src/os_posix/os_mtx_rw.c
@keithbostic Here is a really trivial change to nest the `us` member in a struct in the union. I need this so that I can add padding into the struct for big-endian systems.
=> WT-2016: wt_rwlock_t union packing

src/meta/meta_track.c, src/txn/txn_ckpt.c
For WT-2014 and WT-2009, which came from durability testing with MongoDB.
=> WT-2014 Checkpoint file fixes

src/evict/evict_lru.c
Once there has been enough workload for threads to be started leave
them running. Stopping/starting is expensive and distracting in a
debugger.
=> WT-2017 Don't shutdown eviction server threads during runtime.

src/txn/txn.c
We weren't checking that the oldest ID doesn't move past the oldest named snapshot ID.
Found by inspection.
=> WT-2012 Fix a bug updating the oldest ID

src/btree/bt_walk.c
@michaelcahill, this is for your review, take it if you like it, discard it if you don't.
In short, I had to stare at this to convince myself `page` was safe, and I can see a future change where using `page` in some other way in this function would get us into trouble.
=> Minor lint and clarification.

src/reconcile/rec_write.c
SERVER-19522, WT-2024
Alex, Michael: I think there's a bug in reconciliation locking. I opened WT-2024 to explain it, and this is what I'd suggest as a fix. (I might be completely wrong about the bug, though, I may have missed something?)
The other change here is to lift the split-locking out of the internal-page reconciliation functions and into the upper-level function, so it's done with the rest of the locking, that seems safer and cleaner to me.
For your review and consideration, feel free to just discard all of this if I'm wrong.
@michaelcahill, @agorrod
=> reconciliation locking

dist/s_string.ok, src/include/mutex.h, src/os_posix/os_mtx_rw.c
I hope this doesn't muddy the waters, but I've wondered this before.  Is there any reason not to avoid the shift operations entirely?
=> WT-2023 Avoid bit shifts during read-write lock operations.

src/btree/col_modify.c, src/btree/row_modify.c, src/include/cursor.i, src/include/serial.i
Fix a possible race between two threads inserting into a clean page.
=> WT-2025 Assert that cursors are positioned for inserts

src/conn/conn_sweep.c, src/include/dhandle.h
Clear time-of-death in handles with more than one reference, don't sweep handles with the exclusive flag set.
=> WT-2036 Make handle sweeps more robust

bench/wtperf/config.c, bench/wtperf/wtperf.h, bench/wtperf/wtperf_truncate.c, dist/s_style, src/async/async_api.c, src/async/async_worker.c, src/block/block_open.c, src/conn/conn_api.c, src/conn/conn_dhandle.c, src/conn/conn_handle.c, src/conn/conn_open.c, src/conn/conn_sweep.c, src/evict/evict_lru.c, src/include/async.h, src/include/block.h, src/include/connection.h, src/include/dhandle.h, src/include/os.h, src/include/schema.h, src/include/session.h, src/include/txn.h, src/os_posix/os_open.c, src/os_posix/os_remove.c, src/os_win/os_open.c, src/os_win/os_remove.c, src/schema/schema_list.c, src/session/session_api.c, src/session/session_dhandle.c, src/txn/txn.c, src/txn/txn_nsnap.c
Otherwise remove is O(N), which may not show up until running real workloads (while holding locks).
=> WT-2038 Use TAILQ for all lists.

SConstruct
Add missing file in SConstruct.
=> WT-2044: Fix Windows wtperf.exe build

src/include/connection.h, src/include/txn.i, src/txn/txn.c
There are readers of the handle list that don't acquire the mutex: add a write barrier before handles are inserted.
=> SERVER-19989 Add a write barrier before handles become public

src/support/rand.c
Reference WT-2047.
@michaelcahill, ready for review and merge.
=> The __wt_random code to handle an uninitialized random state is broken.

examples/python/ex_access.py, examples/python/ex_stat.py
Light changes to fit PEP8 (py-RFC) and best practices of Python language
More about it here: http://legacy.python.org/dev/peps/pep-0008/
=> Pythonic way for samples

src/conn/conn_api.c
WT-2057: The verbose configuration is being written to the base configuration file, which means all subsequent runs (including wt command runs), inherit the verbose flags from the initial run.
Strip the verbose configuration as part of writing the base configuration file.
@michaelcahill, ready for review & merge.
=> WT-2057: Strip the verbose configuration as part of writing the base configuration file.

src/include/btree.i, src/include/gcc.h, src/include/lint.h, src/include/msvc.h
Add atomic functions for size_t type, rework btree.i to use size_t functions when updating WT_PAGE.memory_footprint and WT_PAGE_MODIFY.bytes_dirty.
@michaelcahill, @ddanderson, ready for review and merge.
=> WT-2052: OS X clang compiler warnings.

src/evict/evict_lru.c
Also, when clearing eviction walk points before the eviction server goes to sleep, clear *all* walks, not just ones that sessions are waiting to be have cleared.
=> SERVER-20008 Don't reset eviction walks when hitting a busy page.

src/btree/bt_read.c, src/cache/cache_las.c, src/include/btmem.h, src/reconcile/rec_write.c
@michaelcahill, I haven't tested this extensively yet, but this is the direction I'm heading (it seems to run, fwiw).
This removes the flag byte from the beginning of the lookaside table records, I don't see any way to support multiple formats in that table.
=> Specify a key-format to simplify creating lookaside table records.

dist/api_data.py, src/config/config_def.c, src/conn/conn_cache_pool.c, src/include/cache.h, src/include/wiredtiger.in
That provides the ability to limit how much cache a single participant in a shared cache can be allocated.
=> WT-2065 Add a quota to shared cache configuration.

src/include/btree.i
The alternate compile builder for Windows was failing with these warnings.
=> WT-2067: Fix unused variable warnings

src/include/error.h
../src/reconcile/rec_write.c: In function '__rec_split_write':
../src/reconcile/rec_write.c:3252: warning: 'upd' may be used uninitialized in this function
Make it really obvious to dumb compilers that we're not going to continue after an illegal value.
=> WT-1967 fix an "uninitialized variable" warning.

src/conn/conn_cache_pool.c
Update the code to be less aggressive towards application evictions
and application stalls. Being so aggressive led to unfair treatment
of read only workloads, and also more jitter in allocations over time.
=> WT-2034 Fine tune weighting of operations in shared cache balancing.

src/conn/conn_log.c, src/include/extern.h, src/include/misc.i, src/os_posix/os_mtx_cond.c, src/os_win/os_mtx_cond.c
than others.  In particular, flush the log slot 20x per second.
@keithbostic Would you please review?  I added a new API for waiting on conditions.  This change allows the log slot to be forced out more frequently than other operations in the same worker thread rather than having to create a new thread.
=> WT-2085 Run some of the log_server threads operations more frequently

src/evict/evict_page.c, src/reconcile/rec_write.c
@michaelcahill, I hate to maintain a count of LAS evictions in progress, and wait for that to drain.
What do you think of checking the generation values before/after the reconciliation?
=> WT-2074: fix a race between lookaside table reconciliation and checkpoints.

src/conn/conn_log.c
Prevents any possible races when shutting down log utility threads.
=> WT-2092 Free log condition variables after all threads are joined.

src/os_win/os_errno.c
This assert was wrong when I shifted the WIndows error range. It should just be < 0.
Also fixed an issue where a buffer was not correctly null-terminated by switching from `__wt_buf_set` to  `__wt_buf_fmt` during this testing.
Tests:
Windows build
Adhoc fault injection into __wt_read to ensure it is printed correctly.
=> Fix incorrect assert in Windows error handling

dist/stat_data.py, src/conn/conn_log.c, src/cursor/cur_log.c, src/include/extern.h, src/include/log.h, src/include/stat.h, src/include/wiredtiger.in, src/log/log.c, src/log/log_slot.c, src/support/stat.c
This avoids hangs when rapidly filling log files so that in progress
writes can actually finish.
@michaelcahill Please review this branch to solve the hang with many threads and very few records per log file.  There are a couple things of note:
1.  Performance generally is a bit better than currently because by detecting these different conditions, there actually is less slot churn.
2.  Please consider the places where I used `*_BUSY_OK` and if it would be otherwise appropriate to loop/wait for a forced write to complete.  In particular, log cursors could still see a written log record still buffered if it happens when another thread is in the middle of its write.
=> WT-2075 When closing a slot, detect, return and handle different values.

dist/s_string.ok, src/cursor/cur_file.c, src/lsm/lsm_cursor_bulk.c
The feature allows us to stop worrying about schema lock interactions when building LSM indexes on existing tables.
=> WT-147 Add undocumented bulk=unordered for LSM cursors.

src/include/extern.h, src/log/log.c, src/log/log_slot.c
All paths check whether they have closed the slot and need to retry
creating a new slot if they get EBUSY.
@michaelcahill Please review this.  This solves the hang and it is better to have a single function doing this work.
=> WT-2102 Combine the switch and force_write functions.

src/conn/conn_log.c, src/txn/txn_log.c
It can race with archive.  Metadata LSNs may not be updated on clean shutdown.
@michaelcahill Please review.  This fixes the missing file errors with `test_txn11`.  Also a minor KNF I saw along the way.
=> WT-2101 Don't update the logging ckpt_lsn on clean shutdown.

dist/s_label, examples/c/ex_sync.c, src/async/async_op.c
@sueloverso, would you please do the review and merge on this one?
One note, it looked to me like it was OK to simply set `WT_CURSOR.saved_err` (potentially clearing it), in this case.
=> WT-2111: coverity complaint

dist/api_data.py, src/config/config_def.c, src/docs/durability.dox, src/docs/tune-durability.dox, src/include/wiredtiger.in
Also add large default value for transaction_sync.
@keithbostic and @michaelcahill Please review these changes.  I added a large, real default value for the `transaction_sync` method.  I also wrote up the options for `commit_transaction` and `log_flush`.  They're a bit redundant.  Let me know if there is enough information about the `background` setting.
=> WT-2104 Write up commit and log_flush options.

src/log/log.c, src/txn/txn.c, test/suite/test_txn13.py
@michaelcahill Please review this change and unit test for handling attempts to log > 4Gb.  In particular I'm open to modifying which error is returned (per comment, which will need to be removed once decided).  If the error changes, the `msg` in the unit test needs to be updated too.
=> WT-2039 Add error check and unit test for log records over 4Gb.

src/block/block_ckpt.c, src/btree/bt_compact.c, src/btree/bt_handle.c, src/conn/conn_api.c, src/conn/conn_ckpt.c, src/conn/conn_log.c, src/conn/conn_stat.c, src/cursor/cur_backup.c, src/cursor/cur_stat.c, src/evict/evict_lru.c, src/include/api.h, src/include/block.h, src/include/btree.h, src/include/connection.h, src/include/cursor.h, src/include/os.h, src/include/schema.h, src/include/session.h, src/include/txn.h, src/lsm/lsm_work_unit.c, src/os_posix/os_fallocate.c, src/os_win/os_fallocate.c, src/reconcile/rec_write.c, src/session/session_compact.c, src/txn/txn_log.c
@michaelcahill, this is the last of the boolean conversions, I think I've looked at everything now.
I didn't touch `WT_BTREE.modified` or `WT_LSM_TREE.modified` out of sheer paranoia.
=> WT-2112: Boolean conversion pass over include.

src/btree/bt_page.c, src/btree/bt_read.c, src/btree/bt_split.c, src/evict/evict_file.c, src/evict/evict_lru.c, src/evict/evict_page.c, src/include/btmem.h, src/include/btree.i, src/reconcile/rec_write.c
Another approach: track if an internal page has any on-page overflow keys.
=> WT-2119: don't evict clean multiblock pages with overflow items during checkpoints.

src/log/log_slot.c
They introduced a performance regression, due to log slot states
being setup at the wrong time.
=> WT-2143 Revert part of the recent log cleanup changes.

src/btree/bt_compact.c, src/btree/bt_debug.c, src/btree/bt_discard.c, src/btree/bt_split.c, src/include/btmem.h, src/include/hardware.h, src/include/mutex.h, src/include/mutex.i, src/include/serial.i, src/reconcile/rec_write.c
The main purpose is to keep a single lock for all page operations.
=> WT-2131 Switch all WT_PAGE_RECONCILIATION locks to fair locks.

src/conn/conn_log.c, src/include/connection.h
@michaelcahill Please review this bug fix.  I found it when adding tests for reconfiguration in PR #2229.  But it is a bug on its own and deserved its own ticket.
=> WT-2153 Fix bug. Now we always need to start the log_server thread.

src/conn/conn_api.c, src/conn/conn_dhandle.c, src/conn/conn_open.c, src/evict/evict_lru.c, src/include/extern.h, src/txn/txn_recover.c
The lookaside table has to be created after recovery has completed because it needs a file ID and otherwise recovery could overwrite its entry in the metadata.  However, recovery needs eviction threads running because recovery could touch more data than fits in cache.
Resolve this ordering problem by having recovery start a special set of eviction threads without lookaside table cursors.  Once it is done, they are shut down, the lookaside table can be created, and a new set of eviction threads started.
=> WT-2149 Fix the order of creation of the lookaside table

src/conn/conn_cache_pool.c, src/include/cache.h, src/include/hardware.h
It's not trivial to remove all atomic flags primitives, since the page flags rely on them. This part of the change is simple, so it might as well be done quickly.
=> WT-2155 Remove last use of F_CAS_ATOMIC and the associated macro.

src/schema/schema_open.c, test/suite/test_bug015.py
The WT_TABLE.indices array is zeroed after an index is dropped, and is filled on demand. Null pointer checks are needed unless __wt_schema_open_indices() is called first, which repopulates the array.
Did a review to verify that all uses of WT_TABLE.indices guard against null pointers or call __wt_schema_open_indices first.
=> WT-2162.  Add null pointer check, needed after an index is dropped.

src/include/extern.h, src/meta/meta_track.c, src/session/session_dhandle.c
The change in WT-147 to allow a session to lock the same handle exclusive multiple times makes this unnecessary.
=> SERVER-19954 Don't scan tracked handles during checkpoints.

src/txn/txn_recover.c
It used to open and close a session handle that wasn't marked
internal. No functional change since recovery closes the handle
when it is done and the primary difference between internal and
non-internal sessions is during connection close.
=> WT-2167 Switch recovery to using an internal session.

src/os_posix/os_fallocate.c
@keithbostic Please review this small change to remove the use of the `FALLOC_FL_KEEP_SIZE` flag.  I ran the log-append.wtperf test with 5 sets of populate threads (8, 16, 32, 64, 96) multiple times on both this branch and develop and this branch is within the variation of the develop branch.
=> WT-2165  Remove FALLOC_FL_KEEP_SIZE flag.

src/block/block_ckpt.c, src/include/block.h
@keithbostic and @michaelcahill - after thinking about this for a while, I still feel that this code really should be under HAVE_DIAGNOSTIC and an assertion.  I have not heard that we want to move away from that for things like this.  But this seems cleaner to me.  I made it a sub-branch off Keith's so it can be tossed if you want.
I definitely think we want some form of this because it quickly uncovered WT-2068 and we may need it again as we come up with a fix.
=> WT-2068 Put live_open usage under HAVE_DIAGNOSTIC and an assert.

src/btree/bt_split.c
@michaelcahill, I'm open to going the other way, doing a panic in both `__split_parent` and `__split_deepen`. It's unclear how long we're going to run after this failure anyway.
Maybe we should just quit when malloc fails? That would simplify a lot of error handling, and once we're out of memory we're almost certainly taking rarely tested error paths, nothing good is going to happen.
=> WT-2126: __split_deepen() doesn't really need to panic

src/schema/schema_stat.c
When there are lots of tables being created and dropped it can take a long time to get the table lock.
=> WT-2174 Avoid the table list lock when creating a size only statistics cursor.

dist/s_string.ok, src/lsm/lsm_work_unit.c, src/txn/txn_ckpt.c
Otherwise insufficient locks are held to keep checkpoint handles alive.
Also add assertions into checkpoint to avoid running into this again
in the future.
=> WT-2164 Have LSM enable metadata tracking prior to checkpointing a chunk.

src/include/lsm.h, src/lsm/lsm_work_unit.c
@agorrod Please review this change.  It avoids the bus error by not allowing two LSM workers to checkpoint the same chunk.
=> WT-2164 Prevent another chunk checkpoint while the first is still in progress.

src/btree/bt_handle.c, src/btree/row_srch.c, src/include/btree.h, src/include/btree_cmp.i
This makes the branch more generally applicable, rather than being a special case for one type of key.  It was just as fast in my testing.
I tried several variations on the core of #2223 but didn't find any way to make it faster, and my attempts to simplify it made it slower.
@keithbostic, if you're happy with this change, can you please merge it, then merge #2223?
=> WT-2146 Do quick searches based on search key size

src/btree/bt_cursor.c, src/btree/bt_sync.c, src/evict/evict_file.c, src/include/extern.h, src/include/txn.h, src/include/txn.i, src/meta/meta_table.c, src/meta/meta_track.c, src/schema/schema_open.c
Lock down visibility checks so we never try to use a snapshot without one being allocated.
=> WT-2170 Add a macro perform an operation at an isolation level.

src/evict/evict_page.c
The ovfl_lock may already have been freed.
=> WT-2185: Don't do reverse splits when closing a file.

src/btree/bt_split.c, src/evict/evict_file.c, src/evict/evict_page.c
Fix reverse splits to keep the original child ref locked until we have a hazard pointer on the parent page, as we do for regular splits.
Otherwise, a reverse split could race with eviction of the internal page.
=> SERVER-21027 Fix reverse splits to keep the original child ref locked

src/evict/evict_page.c, src/include/misc.h
That way it can't accidentally be used in place of F_ISSET.
=> WT-2189 Make F_SET (and F_CLR) into a void expression.

src/conn/conn_log.c, src/log/log.c
@michaelcahill Please review these changes that implement the fixes we discussed last night.  I am in the process of writing a test program similar to the failing case to put in the tree but that is not complete.  I have a similar diff that fixes it in the 2.6.1 tree they're using also.  We can chat about it tonight.
=> WT-2184 Fix log scan bug when final record has many trailing zeros

src/btree/bt_split.c
We aren't doing an awesome job of balancing trees built via append
workloads, especially when splitting the root. Avoid splitting the
root until it grows large.
The work in WT-2182 should help with our tree shape.
=> WT-2127 Back out some of a change to split internal pages sooner.

src/btree/bt_discard.c, src/btree/bt_split.c, src/include/btmem.h, src/reconcile/rec_write.c
@agorrod, @michaelcahill, I think this is ready for review and merge.
956cc66 is the fix, 0818fc3 is a general naming change.
=> WT-2191: in memory disk image no longer the same as saved updates

src/include/log.h, src/log/log.c, src/log/log_slot.c
so that we locally handle write_lsn rather than waiting for a worker thread, similar to sync.
@michaelcahill Please review this change for the performance issue reported with write-no-sync.  With this change, I see the current logging code perform the same (one populate thread) or 50% faster (8 threads).
=> WT-2187 Add flag for flushing a slot

src/block/block_open.c, src/lsm/lsm_tree.c, src/os_posix/os_filesize.c, src/os_win/os_filesize.c, src/schema/schema_stat.c
It used to generate an error message when attempting to open a
statistics=(size) cursor on an LSM tree.
=> WT-2196 Fix size-only statistics when there are LSM tables.

lang/java/wiredtiger.i, src/session/session_api.c
This can now happen, as WiredTigerLAS.wt is opened internally.
=> WT-2194: Java close callbacks should handle cursors that Java code did not open.

src/schema/schema_stat.c, test/suite/test_stat02.py, test/suite/test_stat05.py
Error codes from failed calls to __wt_filesize_name should not be propagated.
Also add a new test case to test fast stats.
=> WT-2196 Fix error handling in size only statistics.

src/btree/bt_split.c
Release the allocated page on error when creating a new in-memory page as part of instantiating a page based on a multiblock reconciliation.
@agorrod, @michaelcahill, would one of you please do a review? Thanks!
=> WT-2203: release an allocated page on error

src/btree/row_srch.c
We're releasing the "current" page if (leaf != NULL), and that's wrong, we should only release the current page if no leaf-page WT_REF was specified.  The test could be (leaf == NULL), but I think (leaf != current) is a little more obvious.
@agorrod, @michaelcahill, would one of you please do a review? Thanks!
=> WT-2202: release of the "current" page is wrong.

SConstruct, dist/api_data.py, src/config/config_def.c, src/conn/conn_api.c, src/docs/tune-system-buffer-cache.dox, src/include/connection.h, src/include/wiredtiger.in, src/os_win/os_open.c
This change splits out `direct_io` into two options on Windows. `direct_io` now controls OS buffering while `write_through` controls disk buffering. This allows consumers like MongoDB to have fine grain control over how they write to disk.
I updated the documentation to reflect the new options.
Lastly, I now define `HAVE_POSIX_MEMALIGN` since TCMalloc provides it.
**Note:** I have aligned the python and text to 80 columns. I was not sure if it was supposed to be 80 or some other limit.
=> WT-2200 Change WiredTiger caching strategy on Windows

src/btree/bt_split.c, src/btree/col_srch.c, src/btree/row_srch.c, src/evict/evict_page.c, src/include/btree.i
@agorrod, this makes the race I was seeing (append-only workload, column-store), much less likely to hit, but it still occasionally hits.
=> WT-2182: detect internal page split races.

src/session/session_dhandle.c
Previously, this was only tracked for newly-opened handles, but the change for
SERVER-19954 relies on always detecting when a session has a handle exclusive,
regardless of whether it was the first to open the handle.
=> WT-2207 Track whenever a session has a handle exclusive.

src/btree/bt_split.c, src/include/btmem.h, src/include/btree.i
@michaelcahill, this branch is for your review.
I stared at the code that fixes up the moved WT_REF structures today, and found what I think are 3 problems:
* setting WT_PAGE_MODIFY.mod_split_txn as the page is created, see 7dded31,
* only fixing up moved WT_REF's that are in the WT_REF_MEM state when we look at them, see 9464fe3,
* allowing newly created internal pages to split before we fix up the WT_REFs we moved there, see 9464fe3.
I might be wrong on any or all of these, of course, but I hoped coding up an approach to fixing them would help me fully understand the problems and give you something concrete to look at. I put big honkin' comments all over the place.
=> WT-2182: fixes for splitting up the tree.

src/reconcile/rec_write.c
If we allocate raw structures for a row-store and then re-use them for a column-store, we might not have allocated the record-number array, r->raw_recnos. Allocate the record-number array regardless of the type of object we're reconciling.
@agorrod, for your review.
=> WT-2210: raw compression fails if row-store recovery precedes column-store recovery

examples/c/ex_scope.c, src/cursor/cur_file.c, src/cursor/cur_table.c, src/docs/cursor-ops.dox, src/docs/upgrading.dox, src/lsm/lsm_cursor.c, test/huge/huge.c, test/suite/helper.py, test/suite/test_autoclose.py, test/suite/test_bug009.py, test/suite/test_cursor06.py, test/suite/test_cursor09.py, test/suite/test_stat03.py, test/suite/test_stat05.py
Wording changes to clarify when applications can discard memory passed to set-key/set-value.
@michaelcahill, some minor cursor wording changes to clarify when application-memory is used.
One suggestion that came out of the discussion was we could change `WT_CURSOR.insert` to unset the key/value, so not only would the cursor not be positioned after insert returned, it would also not have a set key/value.
I think it's unlikely for an insert cursor to be intentionally re-used without also doing a fresh set-key/set-value call, so I don't think the change would impact real applications and clearing the key/value would mean we'd get a clean error message instead of dropping core.
If you like that idea, let me know and I'll open a ticket and get it done.
=> WT-2217: change WT_CURSOR.insert to clear "set" key/value on return

bench/wtperf/wtperf.c, src/btree/bt_read.c, src/conn/conn_cache_pool.c, src/conn/conn_ckpt.c, src/conn/conn_stat.c, src/evict/evict_lru.c, src/include/misc.h, src/include/mutex.i, src/include/os.h, src/log/log.c, src/log/log_slot.c, src/lsm/lsm_cursor.c, src/lsm/lsm_merge.c, src/lsm/lsm_tree.c, src/os_posix/os_mtx_cond.c, src/os_posix/os_mtx_rw.c, src/os_posix/os_sleep.c, src/os_posix/os_time.c, src/os_win/os_sleep.c, src/reconcile/rec_write.c, src/support/err.c
@agorrod Here's a branch for your consideration.  I added `WT_TIMEDIFF_US` which included creating `WT_THOUSAND`.  Most of this diff is actually fixing the use of that and other constants.
=> WT-2220 Create WT_TIMEDIFF_US and fix use of constants.

src/evict/evict_page.c, src/include/cache.i
Also only write into the lookaside file from internal (aka eviction) threads, so application threads don't pay the performance cost.
It is possible that the cache stuck check is too restrictive, but using only the eviction aggressive flag can result in writing a lot of content to the lookaside file when pages can still be evicted.
=> SERVER-21585 Don't use the lookaside file until the cache is stuck full.

src/btree/bt_split.c, src/include/txn.h, src/include/txn.i, src/lsm/lsm_tree.c, src/reconcile/rec_track.c, src/txn/txn.c
Previously, WiredTiger avoided locking in the transaction subsystem by having
threads race to allocate transaction IDs. Only one thread wins the race, but
losing threads could temporarily leave a transaction ID published in the global
state table.  If the winning thread completed its transaction quickly enough,
its changes may not become visible immediately to readers (until the losing
threads have woken up and allocated a new ID).
This change separates ID allocation from the notion of a shared "current"
value.  Every thread gets a unique transaction ID, and spins to update the
current value.
=> WT-2237 Have threads publish unique transaction IDs so that updates always become visible immediately on commit

ext/extractors/csv/csv_extractor.c, src/cursor/cur_join.c
In __wt_config_gets_def() there is a conditional reference of cfg[2]. Presumably this means that cfg strings are de facto required to have at least 3 entries. If so, would never manifest as a runtime bug, but it's easy enough to satisfy Coverity.
=> WT-2234: Coverity analysis warnings 

src/include/txn.h, src/include/txn.i, src/txn/txn.c
We still need to make sure that transaction IDs are published in the state
table before the current ID is incremented so that snapshot reads don't see
uncommitted updates.  However, a lock simplifies the code and performs better
in testing than the initial fix.
=> WT-2241 Use a lock to protect transaction ID allocation.

src/btree/bt_delete.c, src/btree/bt_discard.c, src/btree/bt_slvg.c, src/evict/evict_file.c, src/evict/evict_lru.c, src/evict/evict_page.c, src/include/btree.i
It leads to problems where eviction attempts to write back to a file after the block manager is already closed.
=> SERVER-21619 Don't do internal page splits after a tree is marked DEAD.

src/reconcile/rec_write.c
@agorrod, @michaelcahill, @sueloverso: for review/consideration.
=> WT-2228: avoid unnecessary raw-compression calls.

src/btree/bt_delete.c, src/btree/bt_split.c
A truncate operation attempts to mark leaf pages deleted without reading them
into cache.  One of the conditions that has to be met for that fast-path
truncate of pages is that the leaf page not contain overflow items (or we would
need to read it in order to delete the overflow items).
The "no overflow" flag was not being preseved across internal page splits, so
recent changes to splits were defeating fast-path truncation.
Add tracking of the "no overflow" flag for in-memory page addresses so
fast-path truncates work after internal pages are split.
=> SERVER-21553 Enable fast-path truncate after splits.

src/session/session_api.c
@michaelcahill, can you do a quick sanity check on this one?
I think it's safe (I'm using the same trick as in `__conn_close`), but wanted to be sure.
The repro is watching `WT_SESSION.name` change as we work our way through `__wt_connection_close`.
=> WT-2248: WT_SESSION.close is updating WT_CONNECTION_IMPL.default_session

src/btree/bt_handle.c, src/btree/bt_read.c, src/btree/bt_split.c, src/evict/evict_file.c, src/evict/evict_lru.c, src/evict/evict_page.c, src/include/btmem.h, src/include/btree.h, src/include/btree.i, src/reconcile/rec_write.c
Specifically, do an in-memory split when we hit 80% of memory_page_max.
=> WT-2244 - Trigger in-memory splits sooner.

src/evict/evict_lru.c
Fix a real bug: STUCK is a cache flag, not a cache->state flag.
Don't try to do eviction when dumping the cache, and only kill processes if no
pages have been evicted since the STUCK flag was first set.
=> WT-2249 Keep eviction stuck until cache usage is under 100%.

src/evict/evict_lru.c
Include pages over the in-memory splits threshold when in the "would block" phase of eviction.
=> WT-2553 Evict pages left behind by in-memory splits.

bench/wtperf/wtperf.c
@daveh86 or @agorrod Please review this change that fixes throttling.  We need to set the timer to the post-sleep time.  This is what was causing the nearly 2x number of ops.
=> WT-2256 Fix interval timer for wtperf throttling.

bench/wtperf/runners/mongodb-oplog.wtperf
@agorrod, can you have a quick look at this change.
It fixes the regression we have seen in the WTPERF truncate workload in jenkins noticed by @sueloverso in https://jira.mongodb.org/browse/WT-2245
=> WT-2265 - increase mongodb-oplog wtperf workload throttle to compensate for fix

src/evict/evict_lru.c
Calling code generally expects the clear to work.
=> WT-2272 Flag an error if there is a failure clearing the eviction walk point.

bench/wtperf/wtperf.c, bench/wtperf/wtperf_opt.i, src/docs/wtperf.dox
@daveh86 Please review this change to add a warning/failure selection to the max_latency and min_throughput.  It may be useful to crash or warn in the test framework you're working on.
=> WT-2266 Add max_latency_fatal and min_throughput_fatal settings.

bench/wtperf/wtperf.c, dist/s_funcs, src/include/extern.h, src/support/rand.c
From @fedorova.
Added a function to optionally initialize a seed, used by __wt_random(), from a random number. Added a call to this function to wtperf. Please take a look.
=> WT-2177 Add an optional random seed to WiredTiger rand implementation

src/cursor/cur_table.c, src/session/session_api.c, src/utilities/util_main.c
@michaelcahill, @agorrod: two problems. First, we weren't closing a cursor in a table-cursor open error path (commit 2cc1025), and second, we were looking at `WT_CURSOR.uri` in a cursor close path and it hadn't yet been initialized (commit 5196a17).
Please check the table-cursor open change carefully, I'm not that comfortable with the table cursor code, I might have gotten it wrong.
Alex, commit 5196a17 is because `WT_CURSOR.uri` is the last thing we fill in when initializing a cursor, and we were using it inside WiredTiger cursor close code. What would you think of disallowing the use of `WT_CURSOR.uri` inside the WiredTiger library, and only allow using `WT_CURSOR.internal_uri`?
=> WT-2275: core dump when "wt dump" fails.

src/btree/bt_page.c, src/btree/bt_split.c, src/btree/row_srch.c
Reverts wiredtiger/wiredtiger#2325, which introduced a segfault.
=> Revert "WT-2231: check the leaf page's parent keys before doing the full binary search"

src/txn/txn.c
@michaelcahill Please review and we should chat about this fix for the EBUSY return during truncate01.  This fix passes all of my repro cases and I have confirmed that it hit the race during those runs.
=> WT-2113 Retry updating the oldest id if we race.

src/reconcile/rec_write.c
that get appended to the update list in page->memory_footprint.
@michaelcahill Please review the fix we discussed last night.  I have run this fix with the failing configuration and made sure we took that path but did not get underflow.
=> WT-2099 Account for overflow update structures

src/txn/txn.c
@michaelcahill This fixes the hang I was seeing in my test/format run.  It hung 100% of the time without this fix and has passed/completed several iterations with it.  However it may be a band-aid like fix as the {{scan_count}} usage is taking the place of read/write lock.
=> WT-2283 Add yield to avoid tight looping.

src/txn/txn.c
@michaelcahill Here's a simple fix but you should review it.  I removed the ``last_running_moved`` part of the conditional.  Or is the "pinned" verbose message more subtle than that and it needs to be moved or copied up into the other part of the new "want to update" part?
=> WT-2282 Remove last_running_moved from verbose conditional.

dist/s_string.ok, src/include/gcc.h
Use the cheaper `lwsync` for read and write barriers on PPC64. `lwsync` only allows
store#load re-ordering.
See Book 2, section 4.4.3 in Power ISA 2.07B manual for more details. In figure 5, the manual says that `mbll` and `mbss` map to `lwsync`.
Test: Builds on POWER8 ppc64le, and runs examples.
=> WT-2265: Correct PPC64 barriers

build_posix/configure.ac.in
A variable name changed as part of ecc674b8f5fc58c1df9a1c6b957491d73a27603d.
=> WT-2285: configure should set BUFFER_ALIGNMENT_DEFAULT to 4kb on linux

src/block/block_addr.c, src/block/block_ext.c, src/include/extern.h, src/utilities/util_list.c
@ddanderson, some suggestions for how this change might be structured inside WiredTiger, feel free to discard it if you don't like it better.
Entirely untested (but it builds & lints cleanly).
=> WT-2276 decode checkpoints via 'wt list -c' and via standalone Python utility.

src/btree/col_srch.c, src/btree/row_srch.c
This is a fix for the code added in WT-2231 (#2383).
=> WT-2289: fix for the fast key check

src/btree/col_srch.c, src/btree/row_srch.c
Reverts wiredtiger/wiredtiger#2391
Which caused a Jenkins stress test failure.
=> Revert "WT-2289: fix for the fast key check"

src/btree/bt_huffman.c
Line-numbers are one-based, so reading a Huffman configuration file with 256 lines would result in an complaint that the file had more than 255 lines.
=> WT-2297: Fix off-by-one error in Huffman config file parsing

build_win/filelist.win, dist/filelist, dist/s_string.ok, dist/s_win, src/conn/conn_api.c, src/include/connection.h, src/include/extern.h, src/os_posix/os_map.c, src/os_posix/os_pagesize.c, src/os_win/os_pagesize.c
Mmap requires page aligned addresses. The VM page on most architectures, and operating systems is 4kb. Some of the exceptions to this are Solaris on Sparc (8kb), and Linux on PowerPC LE (64kb).
It is simple and cheap to just query the OS for the page size as part of connection init instead of hard coding it.
Tested: Windows, Mac OS X, Linux x86, and Linux ppc64le.
=> WT-2281: Dynamically query OS for VM page size

src/btree/row_srch.c, test/suite/test_cursor_random02.py
It is currently failing. The test is currently targeted at small in-memory trees (i.e: the skiplist random code).
=> WT-2291: Update random walk in a skip list to improve it's randomness.

bench/wtperf/wtperf.c, bench/wtperf/wtperf.h, bench/wtperf/wtperf_opt.i, src/docs/wtperf.dox
@agorrod Please review this change.  In particular, is there some obvious error in my change? I am not seeing it.
The config I tested was based off `mongodb-oplog.wtperf` and was:
```
conn_config="cache_size=2GB,checkpoint=(wait=60)"
table_config="type=file"
icount=50000
report_interval=5
run_time=300
populate_threads=1
read_range=true
threads=((count=3,inserts=1,throttle=4000),(count=1,reads=1))
```
It fails very quickly with this error in `test.stat` anytime I run a workload that involves reads and either inserts or updates:
```
Starting 1 populate thread(s) for 50000 items
Finished load of 50000 items
Load time: 0.07
load ops/sec: 0
Starting workload #1: 3 threads, inserts=1, reads=0, updates=0, truncate=0, throttle=4000
Starting workload #2: 1 threads, inserts=0, reads=1, updates=0, …
```
=> WT-2301 Add reading a range of keys to wtperf.

bench/wtperf/config.c
This inits a new config object, thus being always empty and not running afoul of the config_free function.
=> WT-2304 - Fix memory leaking issue in config dump when there are multiple databases

src/schema/schema_stat.c
Merge pull request #2256 from wiredtiger/stat-fast-no-table-lock
(cherry picked from commit 497b744d6)
WT-2174 Backport - Enhance size statistics to not wait for the table lock
=> WT-2174 Backport - Enhance size statistics to not wait for the table lock

dist/s_string.ok, src/btree/bt_split.c, src/btree/bt_walk.c
@agorrod, for your review/consideration, we can talk this through at your convenience.
=> WT-2307: Fix for cursor iteration bug when pages are splitting

src/btree/bt_split.c, src/include/btmem.h
@agorrod and @keithbostic here's a pass at creating a single enum.  I did leave the long comment in both functions with the more thorough description.  Please review and merge if you like it.
=> WT-2307 Use single enum for split error handling phases.

dist/s_string.ok, src/include/gcc.h, src/support/hash_city.c
On UltraSparc IIIi (2003) and later (also likely earlier), Sun/Oracle Sparc chips uses TSO. This means that we only need `membar` when we need to prevent `StoreLoad` reorderings as all others are NOPs on Sparc (See TABLE 8-1 in UltraSparc IIIi manual).
=> WT-2311 Support Sparc

dist/s_copyright
(cherry picked from commit 051ab40)
Builds on another change that was pushed directly to develop branch: 00c2116
=> WT-2320 Backport to 3.0. Only check copyright as part of cutting a release.

src/block/block_open.c, src/include/extern.h, src/lsm/lsm_tree.c, src/os_posix/os_filesize.c, src/os_win/os_filesize.c, src/schema/schema_stat.c, test/suite/test_stat02.py, test/suite/test_stat05.py
Make error handling more robust and fix size only statistics for LSM trees.
=> WT-2196 MongoDB 3.0 backport fixes for size only statistics

src/evict/evict_lru.c
(cherry picked from commit 4fc3e39)
WT-2253 Backport to 3.0. Evict pages left behind by in-memory splits.
=> WT-2253 Backport to 3.0. Evict pages left behind by in-memory splits.

src/btree/bt_sync.c, src/conn/conn_open.c, src/include/connection.h, src/include/extern.h, src/meta/meta_track.c
(cherry picked from commit 2f0b3e2)
=>  WT-2193 Backport 3.0. Handle read-committed metadata checkpoints during snapshot transactions

src/evict/evict_file.c, src/evict/evict_page.c, src/include/extern.h
Coverity analysis defect 77699: Unchecked return value, problem
introduced in SERVER-21619 change, commit 354c031.
Instead of calling __wt_evict_page_clean_update() when discarding pages,
call __wt_ref_out() directly, __wt_evict_page_clean_update() doesn't do
any useful additional work.
This allows __wt_evict_page_clean_update() to be static in evict_page.c,
rename to __evict_page_clean_update().
=> SERVER-22064: Coverity, function return value not checked for error

src/block/block_open.c, src/include/extern.h, src/meta/meta_track.c
WT-2328: schema drop does direct unlink, change to a block manager interface
@agorrod, @michaelcahill: a small restructuring to put the block manager into the drop-file path.
If/when we have multiple block managers, this will change, but for now I think it's correct.
=> WT-2328: schema drop does direct unlink, change to a block manager interface

src/conn/conn_dhandle.c, src/conn/conn_sweep.c, src/evict/evict_lru.c
@keithbostic Please review and run this on  your machine with `verbose=(temporary)` turned on.  If you see the `clear_open...` message and it successfully completes then it took the original code path.  This is not ready to merge until the debug verbose message is removed.
=> WT-2313 Wrap clearing of WT_DHANDLE_OPEN with eviction exclusive calls.

src/packing/pack_impl.c, src/session/session_api.c, test/suite/test_join01.py
Additionally add tests to verify that cursors that merely have a key set, or
that have failed a positioning API (search), not be usable in a join.  Give
a better error message in all these cases.
Add a check in __wt_struct_repack so that an empty or shorter than expected
input array give an error, and not be interpreted as unbounded size.
=> WT-2331 Require that reference cursors that are joined be positioned

src/config/config.c, test/suite/test_config04.py
WT-2335: crash in config_check_search with invalid configuration string
@michaelcahill, would you please do the review?
=> WT-2335: crash in config_check_search with invalid configuration string

src/schema/schema_create.c, test/suite/test_index01.py, test/suite/test_schema02.py
These commits fix the test case for populating indices attached to WT-2295.
Also fixes exclusive create for "index:", and disallows calling create on an existing index with a different configuration string.
Added explicit tests for exclusive create and recreating index with a different configuration.  It's probably not possible in python to create a test that detects that existing indices are not repopulated, at least not without help in C.
=> WT-2295 On index create, do not populate existing indices.

src/log/log.c
@michaelcahill Please review this change.  Although 2.7 and develop don't have the original bug, I believe adding in the assertions from this ticket are worthwhile.
=> WT-2332 Add logging guarantee assertions.

src/conn/conn_log.c, src/include/extern.h, src/log/log.c
@michaelcahill Please review this change that eliminates the performance hit in the 2.7 release for write-no-sync mode.  In fact, this code, in write-no-sync, now runs at 3x the (fixed from WT-2332) 2.6 code (on Linux, it runs equal on my Mac).  This may have a good impact on in-memory log configuration too because the change is in the `wrlsn_server` thread.  This yield code existed in 2.6 and earlier logging code and changed during the rewrite.
=> WT-2296 Yield instead of sleep if the wrlsn thread is finding work.

src/conn/conn_log.c, src/log/log.c
@michaelcahill Please review this fix for WT-2338 which is from BF-1399 - skip using pre-allocated log files if a backup is in progress.  This does not include a test for forcing that specific scenario.  I can add one if you want.
=> WT-2338 Skip pre-allocated log files if backup cursor is open.

bench/wtperf/Makefile.am, bench/wtperf/idle_table_cycle.c, bench/wtperf/runners/checkpoint_stress_schema_ops.wtperf, bench/wtperf/wtperf.c, bench/wtperf/wtperf.h, bench/wtperf/wtperf_opt.i, src/docs/wtperf.dox
Works on idle tables. Gives us a way to ensure that schema operations don't get blocked during high throughput workloads.
=> WT-2342 Add background create/drop to wtperf.

lang/java/Makefile.am, lang/java/src/com/wiredtiger/db/PackOutputStream.java, test/java/com/wiredtiger/test/ConfigTest.java, test/java/com/wiredtiger/test/WiredTigerSuite.java
This is the Java fix corresponding to fixes in WT-1517.  Included is a Java test that matches test_config06.py from the test suite.
=> WT-2347 Java fix for unsized 's' schema format

src/log/log.c
@keithbostic Please review and merge this minor change to use `wt_buf_grow`
=> WT-2355 Use wt_buf_grow instead of free/alloc for scratch buffer.

build_posix/aclocal/options.m4, build_posix/configure.ac.in
WiredTiger's options.m4 uses the C++ compiler instead of the C compiler to check for several C headers:
* snappy.h
* lz4.h
* gperftools/tcmalloc.h
`snappy.h` is a C++ header while `snappy-c.h` is the C equivalent, and the one included by `snappy_compress.c`.
By only using the C compiler for both header file checking and compilation, a user only needs to specify `CCFLAGS` instead of both `CCFLAGS` and `CXXFLAGS` during configure.
In order to support the `api/leveldb` directory, we need the C++ compiler. Previously the `AC_LANG_PUSH` macro was adding a dependency on it and now we need to be explicit the C++ compiler.
=> WT-2369 Use C compiler to detect headers instead of C++ compiler

SConstruct, bench/wtperf/wtperf.h
as it is not supported on MSVC.
Looks like my regex that was to replace spaces with tabs as part of a copy/paste found a formatting nit, I suspect that it can be left as is.
=> WT-2377 - change wtperfs dstrndup to not call strndup

src/conn/conn_dhandle.c, src/conn/conn_stat.c, src/conn/conn_sweep.c, src/cursor/cur_backup.c, src/include/schema.h, src/lsm/lsm_cursor.c, src/lsm/lsm_stat.c, src/lsm/lsm_tree.c, src/lsm/lsm_work_unit.c, src/schema/schema_drop.c, src/schema/schema_rename.c, src/schema/schema_worker.c, src/session/session_dhandle.c, src/txn/txn_ckpt.c
That is, the "lock_wait=false" configuration to WT_SESSION::drop does
not apply to the handle list lock.  The reason is code (specifically in
LSM) that acquires the handle list lock to get an LSM tree, does some
work, then acquires the handle list lock again when discarding the tree.
If the first acquire happens to succeed and the second acquire fails,
the tree is left in the system with its reference count bumped.
=> WT-2378 Always wait for the handle list lock.

src/include/misc.h, src/reconcile/rec_write.c
The value is passed in via the API, and rounding makes it likely we
won't split as the user expects. Especially if the split percentage
is high, when we'll likely round up to 100%.
=> WT-2130 Don't round the split_pct to an allocation size.

src/conn/conn_log.c
```
src/conn/conn_log.c:636:16: error: implicit conversion loses integer precision: 'wt_off_t' (aka 'long long') to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
slot->slot_last_offset;
```
=> WT-2390 Fix OS X warning.

src/cursor/cur_join.c, src/include/cursor.h, src/include/extern.h, src/packing/pack_impl.c, test/suite/test_join03.py
This includes fixes:
- resolved "'u' at end of format" by forcing 'u' to be used always.
- fixed some logic around when repacking needs to be done.
- fixed error path in __curjoin_extract_insert.
- when the first index is just 'eq', finish iteration when it becomes
non-equal.
In additions, some cleanups related to these fixes, see commit log for more details.
To test collator/extractors, extended test_join03 to use collators.  It needs the sample collator in pull request #2473 (WT-2375) to run.  For now, the collator part of the test is disabled.
This runs successfully against the test program in WT-2382.
=> WT-2382 Resolve 'u' vs. 'U' format mismatches for cursor joins in collators/extractors.

src/session/session_api.c
Since database-wide checkpoints have references to all handles in the
system, drops are generally not possible during a checkpoint regardless
of this change.  This prevents a deadlock where checkpoint waits on the
handle list lock after it has some handles locked exclusive.
A better longer-term solution would be to have checkpoint gather all
handles (including locking old checkpoints) at the beginning so it
doesn't have to acquire the handle list lock after locking handles.
=> WT-2396 Grab the checkpoint lock around drops and renames.

src/btree/bt_walk.c, src/btree/col_srch.c, src/btree/row_srch.c, src/include/btree.i
Positioning a cursor at the end of the tree can race with page splits.
During the initial descent of the tree in the cursor.prev case, do the
same tests for races we do for a search past the end of the tree.
=> WT-2397: Cursor traversal from end of the tree skips records.

src/schema/schema_create.c, test/suite/test_index01.py, test/suite/test_schema02.py
We added the check in WT-2295 as part of another fix. We have never
checked before and it makes maintaining backward compatability more
complex in the future for limited gain.
=> SERVER-22676 Don't check duplicated create calls for matching configurations

build_posix/Make.subdirs, test/cursor_order/Makefile.am, test/cursor_order/cursor_order.c, test/cursor_order/cursor_order.h, test/cursor_order/cursor_order_file.c, test/cursor_order/cursor_order_ops.c
Based loosely on the test/checkpoint implementation. Hopefully we can
refactor, so code is shared between the two via test_util.i.
=> WT-2399 Add initial implementation for cursor traversal test application

src/meta/meta_turtle.c
If we find a file that needs to be created, use its metadata config
in case it sets its own allocation size.
@michaelcahill or @agorrod please review this change.  I have confirmed it fixes the issue with the ticket and the test passes and continues.  Basically it allows it to create the LSM chunk with the correct allocation size.
=> WT-2395 Use allocation_size from metadata.

test/format/backup.c, test/format/ops.c, test/format/rebalance.c, test/format/wts.c, test/utility/test_util.i
Add testutil_checkfmt, a macro that supports additional error output.
=> WT-2405: test utility error handling.

src/include/wiredtiger.in
@keithbostic Please review this 5 character change!
=> WT-2412 Truncate should not return EBUSY any longer.

dist/s_export, dist/s_export.list, ext/compressors/lz4/lz4_compress.c, ext/compressors/snappy/snappy_compress.c
@agorrod, for your review consideration, the changes to not include `wt_internal.h` in the compression modules.
=> WT-2376: Modules should compile without including wt_internal.h header file

src/include/extern.h, src/packing/pack_impl.c
Commit a6c183b removed the only caller of `__wt_struct_unpack_size`.
=> WT-2382: Problem with custom collator for 'u' format with join cursor

src/btree/bt_compact.c, src/reconcile/rec_write.c, src/session/session_compact.c, test/suite/test_compact02.py
Move compact start/stop into the session layer so all operations on the
file during compaction (including checkpoints) use first-fit allocation.
=> WT-2394: Have pages split as part of compact checkpoints use first-fit

src/lsm/lsm_work_unit.c
Having the checkpoints wait for a lock instead of looping round and retrying later had a positive performance impact  - to the tune of 10%.
=> WT-2409 - Have LSM checkpoints wait for locks.

src/btree/bt_compact.c, src/include/extern.h, src/include/session.h, src/session/session_compact.c
This allows us to set the "first fit" flag once and clear it consistently.  It also prevents drop or other exclusive operation during compact without reentering the schema lock each time.
=> WT-2394 Gather handles for compact at the beginning.

src/cursor/cur_stat.c, test/suite/test_join01.py
This fix is relevant for getting statistics on join cursors.  This fixes the user submitted test case, and also passes a new test case, which is derived from the user submitted one.
=> WT-2430 Ensure that statistics cursor is always positioned at the first 'set' of statistics.

src/conn/conn_stat.c, src/docs/readonly.dox, test/suite/test_readonly02.py
@michaelcahill Here are changes for allowing statistics logging even in read-only mode.  This is helpful for debugging the performance differences.  Please review.
=> WT-2433 Allow statistics logging in readonly mode.

src/conn/conn_dhandle.c, src/conn/conn_sweep.c, src/evict/evict_lru.c
During a forced drop, trees are marked dead but remain in cache
temporarily.  The sweep thread is aggressive about trying to discard
dead trees from cache.
If sweep found a tree marked dead before the drop operation had
completed, they could race setting / clearing the "no eviction" flag on
the tree, allowing eviction to run concurrent with sweep's discard.
This could cause a segfault where pages are discarded underneath
eviction.
The fix is to move setting / clearing the "no eviction" flag inside the
spinlock that protects against concurrent close operations.  That way,
even if sweep does find a tree before drop has finished closing it,
sweep will block on the close lock before attempting to discard it.
While in the area, tighten up other checks relating to the "no
eviction" flag.
=> WT-2434 Fix a race between forced drops and sweep.

bench/wtperf/runners/evict-btree-readonly.wtperf, bench/wtperf/runners/evict-btree.wtperf, bench/wtperf/runners/evict-lsm-readonly.wtperf, bench/wtperf/runners/evict-lsm.wtperf
Turn off mmap for readonly.
@michaelcahill Here are the changes for the eviction configurations to wtperf, per our discussion.
=> WT-2432 Add eviction worker threads to eviction configs.

test/suite/test_backup05.py, test/suite/test_checkpoint01.py, test/suite/test_cursor06.py, test/suite/test_cursor_random.py, test/suite/test_join01.py, test/suite/test_readonly01.py, test/suite/test_readonly02.py, test/suite/test_readonly03.py
Look for WT-specific portion of the message or detect Posix/Windows.
@michaelcahill Here is a change to fix the test failures on Windows.
I modified the tests to look for non-Posix portions of error messages.  It does bring up again whether we need a translation layer.
=> WT-2437 Adjust expected error messages to support Windows.

src/support/power8/crc32.S
Per the PPC64 ABI, v20-v31 are non-volatile registers. See http://refspecs.linuxfoundation.org/ELF/ppc64/PPC-elf64abi.html#REG
for calling convention.
In experiments under GDB, we see that after crc32_vpmsum is called that
registers v20-v31 are modified. We discovered this issue after
integrating the crc32_vpmsum code into our C++ code base which targeted
POWER8 for code generation, see
https://jira.mongodb.org/browse/SERVER-22773 for repro.
=> Wt 2440 Fix POWER8 CRC32

bench/wtperf/config.c, bench/wtperf/runners/update-delta-mix1.wtperf, bench/wtperf/runners/update-delta-mix2.wtperf, bench/wtperf/runners/update-delta-mix3.wtperf, bench/wtperf/runners/update-grow-stress.wtperf, bench/wtperf/runners/update-shrink-stress.wtperf, bench/wtperf/wtperf.c, bench/wtperf/wtperf.h, bench/wtperf/wtperf_opt.i, dist/s_string.ok, src/docs/wtperf.dox
Via a new update_delta setting in the thread group which takes either
a signed number of "rand" as an argument. Defaults to 0 (disabled).
There is also a new value_sz_max configuration option to limit how
large values can grow.
=> WT-2366 Extend wtperf to support changing record sizes in update ops

src/cursor/cur_join.c, src/include/cursor.h, test/suite/test_join05.py
For cursor joins, joining the first index with only compare=le/lt (without a gt/ge) requires us to create another cursor internally to get results in order.  Previously we weren't returning any results.
This fixes the given test case.
=> WT-2384 Fix cursor joins with compare=le or lt in first index

src/cursor/cur_join.c
Fixes the submitted test case.
=> WT-2436 For cursor joins with lt/le, fix how Bloom filters are populated

src/cursor/cur_join.c, src/session/session_api.c, test/suite/test_join06.py
Since it might be hard to predict the results of having read-uncommitted with bloom filters, we shouldn't permit it.  This pull request includes a couple of small fixes and a test case for read uncommitted with/without bloom filters.
=> WT-2322 Do not permit read-uncommitted with bloom filters

src/cursor/cur_stat.c, test/suite/test_join01.py
This is relevant to getting a complete set of statistics (for every participating index) for a join cursor.
=> WT-2443 Fix how a statistics 'set' is initialized.

src/btree/bt_read.c, src/conn/conn_cache.c, src/evict/evict_lru.c, src/include/btmem.h, src/include/cache.h, src/include/cache.i
@agorrod, @michaelcahill: I spent a bunch of time chasing what I thought was the problem in WT-2391, but it turned out to be a red herring. Anyway, along the way I accumulated some changes that I think are a minor improvement over the current page read-generation code.
I cleaned them up and created this branch.
If you like this better than the current code, great, if you don't, then just discard the branch. As I said, it's a minor set of cleanups at most, and if you don't like them that's fine with me.
=> WT-2391: De-prioritize eviction from indexes

src/support/power8/crc32.S
Update CRC32 Power8 after the PR for the non-volatile registers was accepted. The new code is more efficient at saving and restoring registers.
=> WT-2456 Update CRC32 Power8 Code

test/suite/test_rebalance.py
Fix a test cut-and-paste error, we're testing WT_SESSION.rebalance here,
not WT_SESSION.drop.
=> WT-2418: test_rebalance failing with EBUSY

src/meta/meta_table.c, test/suite/test_schema07.py
Switch from making eviction impossible to merely unlikely.  This allows
metadata pages to split and for eviction to discard deleted data.
Without this change, the trivial test added in test_schema07.py hangs
because the metadata fills the cache.
=> WT-2451 Allow eviction of WiredTiger metadata.

test/suite/test_sweep01.py
@keithbostic Can you please review this minor change to the timeout value `sweep01`?  It was failing on the PPC machine and this fixes it there.
=> WT-2461 Adjust sweep timeout values.

test/manydbs/smoke.sh
It's causing problems with valgrind testing.
=> WT-2463 Disable manydbs failure mode for now.

examples/c/ex_config_parse.c
This reverts commit 0b2766c1db03e96d5c7bfbb1eae66a9df790e301.
=> Revert "WT-2473: MSVC doesn't support PRId64"

bench/wtperf/wtperf.h
@daveh86, for your review/consideration.
=> WT-2465: Coverity 1352899: Dereference before null check

src/btree/bt_handle.c, src/btree/bt_rebalance.c, src/btree/bt_sync.c, src/conn/conn_cache.c, src/conn/conn_dhandle.c, src/evict/evict_file.c, src/evict/evict_lru.c, src/include/btree.h, src/include/cache.h, src/include/cache.i, src/include/extern.h
@agorrod, @michaelcahill, for your review/consideration.
This was the simplest approach I saw for reference counting requests for eviction disable/enable on a file. A few comments:
* I moved the `WT_CACHE.evict_walk_lock` to `WT_BTREE.evict_lock` in the btree handle, so now there's a cache `evict_lock` and a per-handle `evict_lock`. The reason is because reference counting eviction disable/enable requests requires we hold the no-eviction lock a lot longer than before, and I didn't want file close to stall eviction. We could avoid this part of the change by doing a try-lock call on the global lock, but this seemed better to me.
* I left the `WT_BTREE_NO_EVICTION` flag in place. If you like this change, we might want to take a run at removing that flag in favor of just a reference count …
=> WT-2435: __wt_evict_file_exclusive_on/off cleanups

src/cache/cache_las.c
It was attempting to save which flags were set by checking F_ISSET (which returns a boolean). Should have been using WT_MASK.
This was leading to the WT_SESSION_NO_EVICTION flag being cleared unexpectedly and WT_SESSION_CAN_WAIT being set as well.
=> WT-2460 Fix a flags test in LAS code to use mask not is-set.

src/utilities/util_dump.c
Coverity thinks we can overflow a buffer -- we can't, but clarify the
code to avoid the false positive.
=> WT-2482: Coverity 1353015, 1353016, out-of-bounds access

bench/wtperf/wtperf.h
Explicitly discard the sscanf return value, hopefully that will quiet
Coverity.
=> WT-2484: Coverity 1345809: unchecked return value

test/manydbs/manydbs.c, test/manydbs/smoke.sh
Fix manydbs.c to use WT statistics instead of system CPU usage for more consistent runs.
=> WT-2463 Change manydbs test to use WT statistics

src/cursor/cur_join.c, src/include/cursor.h, test/suite/test_join01.py, test/suite/test_join02.py
This also reduces main table reads from about 24M of pread data size to about 45K using a slightly modified version of the submitted test case.
=> WT-2447 For cursor joins, avoid main table reads during iteration and bloom initialization

src/btree/bt_handle.c, src/conn/conn_cache.c, src/evict/evict_lru.c, src/include/btree.h, src/include/cache.h
@keithbostic, this is a change i put together when looking into WT-2476.
If you think moving back towards a cache lock rather than a btree lock is the way to go, then this may be suitable.
=> WT-2476 - Revert changing the cache evict_walk_lock to the btree evict_lock

src/lsm/lsm_merge.c, src/lsm/lsm_meta.c
@agorrod or @michaelcahill here is one potential fix and an added assertion.  This fix has run over 300 iterations on both CONFIGs.
=> WT-2485 Adjust lsm_tree->merge_min when we read the metadata.

src/lsm/lsm_meta.c
@agorrod Please review this fix for correctly setting memory_page_max in LSM.  Note that the performance issue won't be fixed until WT-2485 is fixed.
=> WT-2481 Set memory_page_max after we read chunk_max.

dist/s_string.ok, src/config/config.c, src/include/gcc.h, src/include/lint.h, src/include/msvc.h
Windows doesn't like "td" for ptrdiff_t
=> WT-2492 Change printf format specifier to be Windows compatible.

src/include/lsm.h, src/lsm/lsm_cursor.c, src/lsm/lsm_tree.c, src/lsm/lsm_worker.c, test/suite/test_lsm03.py
Otherwise we can return EBUSY unexpectedly. Fixed several outstanding
bugs along the way.
This change isn't ready for review yet - it needs further testing and a round of cleanup.
=> WT-2457 Wait for LSM work units to drain when getting exclusive access.

src/cursor/cur_join.c, src/include/cursor.h
When iterating cursor joins, take advantage of the fact that we have the index key for the first index available.  We don't need to extract it again.
=> WT-2414 Avoid main table reads and extractions for the first index

src/os_posix/os_alloc.c
Otherwise we can free memoy with tcmalloc that was allocated
with the system allocator.
=> WT-2495 Make malloc calls use tcmalloc when configured.

src/cursor/cur_backup.c
In particular, a checkpoint could mark and lock an old checkpoint for
deletion before a hotbackup starts.  The hotbackup could then write
metadata referencing that old backup which the checkpoint goes on to
delete.
The fix is crude: don't allow a hotbackup to start while a checkpoint
is in progress.
=> WT-2496 Fix a race between checkpoint and starting a hot backup.

test/format/backup.c, test/format/format.h, test/format/util.c
@keithbostic This is for your consideration.  It is only a debugging aid so that if/when a failure happens on a backup directory we have an exact version of the backup directory before WT did anything like removed the `WiredTiger.backup` file, ran recovery, etc.
=> WT-2497 Create second backup copy.

build_win/filelist.win, dist/filelist, dist/log.py, src/btree/bt_debug.c, src/conn/conn_api.c, src/conn/conn_handle.c, src/evict/evict_lru.c, src/include/connection.h, src/include/extern.h, src/include/misc.i, src/include/os.h, src/include/wt_internal.h, src/log/log_auto.c, src/os_posix/os_getline.c, src/os_posix/os_inmemory.c, src/os_posix/os_open.c, src/os_posix/os_posix.c, src/os_posix/os_stdio.c, src/support/err.c, src/txn/txn_log.c
@sueloverso, @michaelcahill, for your review/consideration.
The idea here is to check the initial inputs we have (the wiredtiger_open config string and the WIREDTIGER_CONFIG environment variable), for either read-only or in-memory configurations, before looking at any of the on-disk information.
Also, there's this code:
```
/* Ignore the base_config file if config_base_set is false. */
if (config_base_set || F_ISSET(conn, WT_CONN_READONLY))
WT_ERR(
__conn_config_file(session, WT_BASECONFIG, false, cfg, i1));
```
I didn't touch it, but it looks wrong to me -- why are we ignoring the base configuration file if we're configured read-only?
=> WT-2330: in-memory configurations should not create on-disk collection files

src/include/lsm.h, src/lsm/lsm_manager.c, src/lsm/lsm_merge.c, src/lsm/lsm_tree.c, src/lsm/lsm_work_unit.c
Tree close relies on any state change being visible immediately. Found
by inspection, but could cause the symptom seen in this ticket.
=> WT-2499 Fix a race in LSM between setting and checking WT_LSM_TREE_ACTIVE

bench/wtperf/misc.c, bench/wtperf/wtperf.c, src/btree/bt_debug.c
@agorrod, @sueloverso, for your review/consideration.
=> WT-2517: wtperf uses setvbuf in a way that isn't supported on Windows

src/include/misc.i, src/os_posix/os_fs.c, src/os_win/os_fs.c, test/readonly/smoke.sh
Since assertions call fsync on the standard I/O channel regardless of whether the connection is open read only.
=> WT-2529 Be less aggressive asserting in readonly connections

src/cursor/cur_backup.c
Don't leak the variable value if the call to __wt_fprintf fails.
@agorrod, for your review.
=> SERVER-23504: Coverity analysis defect 98177: Resource leak

src/block/block_ckpt.c, src/os_common/os_fs_inmemory.c
=> WT-2531: in-memory tables are wasting space in truncation

src/os_common/os_fs_inmemory.c
Returning a zero size breaks MongoDB replication. Return a non-zero
size for now until SERVER-23526 is resolved.
=> WT-2533 Don't let in-memory tables return a zero size.

src/block/block_open.c, src/btree/bt_huffman.c, src/conn/conn_api.c, src/include/os.h, src/meta/meta_turtle.c, src/os_common/filename.c, src/os_common/os_fhandle.c, src/os_posix/os_fs.c, src/os_win/os_fs.c
@agorrod, here are the changes to default to opening file handles read/write (unless the database is configured readonly).
For your review.
=> WT-2526: mixing and matching readonly and read/write handles

src/include/log.h
@michaelcahill Please review this change for the reported bug when running recovery with a database that contained an old INIT_LSN in the metadata.
=> WT-2537 Check for an old and new uninitialized LSN for recovery.

src/btree/bt_debug.c, src/btree/bt_ret.c, src/include/bitstring.i, src/reconcile/rec_write.c
@agorrod, @michaelcahill, this is the one I've been chasing in WT-2535.
The problem is fixed-length column-store  reconciliation was updating the original page any time a transaction was globally visible, and that gets snapshot isolation wrong because earlier readers in the system subsequently see the wrong value.
The only interesting commit is 93059b7, ready for review/merge.
=> WT-2542: fixed-length column store reconciliation overwrites original values

src/log/log.c
The one in the log structure may change and point to a different log
file than the one we expect.  Open our own to the correct file.
@keithbostic Please review this change.
=> WT-2559 Open a local log file handle for sync.

src/conn/conn_api.c
It was a remnant from early development.
@keithbostic Can you review this small change?
=> WT-2504 Remove READONLY conditional for base config.

ext/compressors/zlib/zlib_compress.c, src/reconcile/rec_write.c
Previously, we had special case code for zlib to bound the compression
ratio to an arbitrary factor.  This is driven by synthetic workloads
where data can be compressed on disk to 1% or less of the in-memory
size.  If WiredTiger allows such on-disk pages to grow, they can end up
larger than the maximum page size permitted in memory and either
immediately force eviction or in extreme cases grow larger than the
total cache size.
This change bounds the amount of data handed to raw compression based on
the maximum page size in memory before attempting in-memory splits.
=> WT-2548 Cap the amount of data handed to raw compression.

test/format/backup.c
@keithbostic Please review this change for the incremental log truncating log files.  The truncate/archive needs to be done before closing the backup cursor.  I should have caught this when I reviewed it yesterday.  It is the cause of the heap-use-after-free sanitizer failure.
=> WT-2557 Need to truncate logs before closing backup cursor.

src/os_win/os_fs.c
When `ReadFile` returns an error on Windows, `nr` is always set to 0. Therefore we always return `WT_ERROR` instead of calling `GetLastError` and lose valuable error information.
*Tests*:
By injecting a fault via `SetLastError(ERROR_QUORUM_DISK_NOT_FOUND)` and some code modifications, we now get more useful information in the logs when `ReadFile` fails:
*Sample log*:
```
2016-04-20T16:57:22.786-0400 E STORAGE  [initandlisten] WiredTiger (-23914) [1461185842:786997][19764:140725103342688], txn-recover: journal/WiredTigerLog.0000000001 read error: failed to read 511102156800 bytes at offset 2105728: The quorum disk could not be located by the cluster service.
2016-04-20T16:57:22.797-0400 E STORAGE  [initandlisten] WiredTiger (-23914) [1461185842:797033][19764:140725103342688], txn-recover: …
```
=> WT-2569 __win_handle_read needs to call GetLastError()

lang/java/src/com/wiredtiger/db/PackInputStream.java
This fixes java's PackTest (and potentially other code) that may have been affected by changing a constructor in WT-2550.
Aside: Apparently our pull request tester doesn't build java, and I didn't see it because I didn't rebuild from scratch when testing.
=> WT-2568 Add a backward compatible constructor for PackInputStream.

src/btree/bt_curnext.c, src/btree/bt_curprev.c, src/btree/bt_cursor.c, src/btree/bt_debug.c, src/btree/bt_delete.c, src/btree/bt_discard.c, src/btree/bt_handle.c, src/btree/bt_page.c, src/btree/bt_read.c, src/btree/bt_rebalance.c, src/btree/bt_ret.c, src/btree/bt_slvg.c, src/btree/bt_split.c, src/btree/bt_vrfy.c, src/btree/col_modify.c, src/btree/col_srch.c, src/btree/row_key.c, src/btree/row_modify.c, src/include/bitstring.i, src/include/btmem.h, src/include/btree.i, src/include/column.i, src/include/extern.h, src/reconcile/rec_write.c, test/salvage/salvage.c
@agorrod, @michaelcahill, for your consideration, I thought it likely reducing the size of the `WT_PAGE` structure to 64B could help our malloc fragmentation. (The `WT_PAGE_MODIFY` structure remains at 104B.)
This one needs relatively careful review -- I'm happy to do that myself, this week, if you want the change.
=> WT-2558 WT_PAGE structure reorganization

src/btree/bt_split.c
=> WT-2573: free of stack-allocated WT_REF

src/cursor/cur_join.c
cursor/cur_join.c:664:41: error: implicit conversion loses integer precision: 'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
=> WT-2360 Fix a build warning.

test/format/config.c
test/format/config.c:415:16: error: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
=> WT-2553 Fix implicit size_t conversion in test/format.

src/txn/txn.c
The default backoff sleeps cause severe performance regressions due to
contention between readers trying to scan.
=> WT-2560 Spin on transaction locks.

test/format/config.c
It can if an option is specified in the configuration file and
the command line.
=>  WT-2574 Ensure test/format doesn't leak memory

test/format/config.c
Rework format configuration to use config_single() more, that way we
discard allocated memory when in-memory configurations turn off previous
configurations.
=> WT-2574: format doesn't free all allocated configure memory

src/btree/bt_split.c
@michaelcahill, @agorrod, another column-store record-number fix.
I think this change is pretty safe, so I'm going to merge it after it passes the tests so we can get the stress tests going again.
=> WT-2582: cache eviction server error: WT_RESTART

src/bloom/bloom.c, src/conn/conn_api.c, src/cursor/cur_index.c, src/lsm/lsm_merge.c, src/meta/meta_turtle.c, src/session/session_api.c, src/txn/txn.c, src/txn/txn_nsnap.c, test/suite/test_backup05.py, test/suite/test_txn04.py
Periods followed by colons looks bad, remove periods from error messages.
=> WT-2584: don't use periods in error messages

src/btree/bt_debug.c, src/evict/evict_lru.c, src/include/os.h, src/os_common/os_fstream.c
@michaelcahill, @agorrod: I want to give up trying to run the debugging functions through the pluggable I/O functions, it's too hard.
This also removes the need for the `WT_STREAM_LINE_BUFFER` flag.
=> WT-2579: in-memory configurations break debugging support

src/conn/conn_log.c, src/cursor/cur_backup.c, src/include/os_fs.i, src/log/log.c
@keithbostic This should fix the runaway creation of pre-allocated log files.  Please review
=> WT-2593 Free the dirlist at the end of the function.

test/suite/test_backup05.py
@keithbostic Please review this change to a backup test that verifies we cannot change the file names via rename or drop while a backup cursor is open.
=> WT-2343 Add test to make sure we cannot rename/drop when a backup cursor is open.

src/utilities/util_dump.c
This also fixes a malloc leak in dump_table_config_complex().
Compared JSON output from all jsondump runs in test/suite, all identical modulo a difference arising from using a `metadata:create` cursor previously, now we use a (regular) `metadata:`.   The differences will be tracked in WT-2591.  For JSON dump the difference appears to be benign: 1) the test cases run normally 2) the previous values dumped for key_format/value_format of column groups appeared to be wrong, with this commit they are right 3) the key_format/value_format for a column group is likely to be ignored on input (it's normally not specified), since it can be derived from the formats given for the `table:`.
=> WT-2479 Refactored json dump to eliminate duplicate code.

src/cursor/cur_join.c
This fixes a rather fundamental problem.  Any joins written in C that do not use recno were not seeing results.  Internally we are using raw keys, but our final 'main' cursor may not be in raw mode, so we may not be able to retrieve the values using the key we have.
Unfortunately, the bulk of the test cases for join are in Python, which use RAW mode, so unaffected.  Our C example uses recno, which took a different path.
=> WT-2592 Fix joins for the non-recno, non-raw case

src/cursor/cur_join.c
A comment in cursor/cur_join.c contains "return WT_NOTFOUND", which is triggering a complaint from the scripts that check for returns that skip error labels.
=> WT-2609: Incorrect "skips API_END call" error.

src/btree/row_srch.c
@michaelcahill, calling `__wt_page_evict_soon` works well, in my tests it brings $sample of newly created collections down to about the same time as a re-opened collection.
I ended up with a pretty stupid "should we evict this page" test of "greater than 5MB". That performed as well as anything else I tried, and it didn't seem unreasonable to use the page's memory footprint for this purpose, once we know the page's footprint reflects just the one big skiplist.
Ready for review/merge.
=> SERVER-23661: $sample takes disproportionately long time on newly created collection

src/os_common/os_fs_inmemory.c
Eliminate a race where the handle could be removed between the search
and the size check.
=> WT-2616: Fix a deadlock with in-memory size lookups.

examples/c/ex_access.c, examples/c/ex_all.c, examples/c/ex_async.c, examples/c/ex_backup.c, examples/c/ex_call_center.c, examples/c/ex_config_parse.c, examples/c/ex_cursor.c, examples/c/ex_data_source.c, examples/c/ex_encrypt.c, examples/c/ex_event_handler.c, examples/c/ex_extending.c, examples/c/ex_extractor.c, examples/c/ex_file_system.c, examples/c/ex_hello.c, examples/c/ex_log.c, examples/c/ex_pack.c, examples/c/ex_process.c, examples/c/ex_schema.c, examples/c/ex_scope.c, examples/c/ex_stat.c, examples/c/ex_sync.c, examples/c/ex_thread.c
@agorrod, the only thing I can find here is the file system example didn't separate the concepts of "buffer data size " and "buffer memory size", so the read of the file was somehow getting confused. I don't see the exact path that would cause it, but I think there's a potential problem there.
If you merge 461c63d, I think we can close the JIRA ticket until it appears again.
=> WT-2617: Bug in pluggable file system example

src/include/btree.i
Avoid a path to the checkpoint thread performing eviction.
=> WT-2633 Don't allow eviction of the metadata during checkpoints in MongoDB 3.0

test/format/config.c
Change test/format to not choose bzip compression.
=> WT-2635: Test/format on 3.0 attempts to use bzip compression

src/docs/custom-file-systems.dox, src/docs/spell.ok, src/os_posix/os_fs.c
The file-extension documentation doesn't cover not-supported cases.
Public domain the POSIX file system implementation, it's a natural starting point for anyone writing their own implementation.
=> WT-2637: The file-extension documentation doesn't cover not-supported cases

test/format/ops.c
@keithbostic Please review this change.
=> WT-2632 Tolerate EBUSY when a checkpoint cursor is open.

bench/wtperf/config.c, dist/s_string.ok
This simple solution allows backquotes to get into the WT config parsing, where they are accepted but not transformed (see the JIRA comments), and then unescape them when we get them back from the parser.  
Question for reviewer: it may be preferred to put the unescape code in the config parsing within WiredTiger.  If we go that route, we probably need to allocate a buffer when needed (probably hanging off of WT_CONFIG) to hold the unescaped text.
Also wanted to make sure I wasn't missing some other way of escaping quotes before I went for a more involved solution.
=> WT-2611 Modify wtperf to handle escaped quotes.

test/csuite/wt1965_col_efficiency/main.c, test/csuite/wt2535_insert_race/main.c, test/utility/misc.c, test/utility/test_util.h, test/utility/thread.c
@sueloverso, @agorrod, I pointed lint at the new csuite tests, just some minor cleanup.
I added a new macro, `testutil_assert`, to make it easy to assert stuff and die if it's not true.
=> WT-2659: csuite tests, assorted lint and cleanup.

src/evict/evict_lru.c, src/include/cache.i
@michaelcahill Please review this change.  I added a condition to have the app thread helping with eviction return if it notices we're closing.  You'll see by my first commit (reverted in the second) that I tried to encourage the situation, but have so far been unable to reproduce the original hang.
One consideration for this change is whether we could hit one of the conditionals in `conn_cache_destroy` but I think it is okay.  I just want someone else to think about it for a minute too.
=> WT-2660 Fix a hang between eviction and connection close

src/cursor/cur_dump.c, src/cursor/cur_json.c, src/include/extern.h, src/include/packing.i, src/utilities/util_dump.c, src/utilities/util_dump.h, src/utilities/util_load_json.c, test/suite/test_jsondump01.py, test/suite/test_jsondump02.py
This version of JSON load/dump is incompatible with older versions.  The issue is that older JSON dump tried to dump 's' and 'S' strings as Unicode.  If the byte sequence ... 0x03 0xC0 ... appeared, then this is a valid Unicode escape sequence and we showed '...\u03c0...'.  All fine if the string is Unicode, but if not (e.g. ... 0xFF 0xFE ...), there is no Unicode sequence that we can emit that will map back to these bytes when we reload. It seemed to me the simplest way to solve this was to treat every character in a string as a raw byte (that is, not interpreted as Unicode), but emit a unicode value between '\u0000' and '\u00ff'.  If the byte is printable, we show the printable character in the string.  Byte arrays (schema type 'u') are dumped using the same rules, except that we don't …
=> WT-2268 WT-2597 JSON load/dump Unicode fixes

src/cursor/cur_json.c, src/include/extern.h
The root cause is a sign extension error that shows up on systems
that have a signed 'char'.
=> WT-2677 Fix JSON output so only printable ASCII is produced.

dist/s_string.ok, src/include/os.h, src/os_posix/os_dir.c, src/os_posix/os_fs.c, src/os_posix/os_map.c, src/os_win/os_fs.c
@michaelcahill, I tried coding up your suggestion, and I agree it's better than #2757.
I think we should review how we're using SYSCALL_RETRY, though. We're calling it for things that aren't worth retrying (gettimeofday), and we're not calling it for things that might reasonably need to be retried (pread, pwrite). I could see using retry for open(2) calls, but I don't think it has much value outside of that, since pread/pwrite clearly don't need it.
=> WT-2672 handle system calls that don't set errno

dist/api_data.py, src/config/config_def.c, src/include/wiredtiger.in, src/session/session_api.c
* Default checkpoint_wait is true. This change is useful because it means concurrent create/drop calls don't generate EBUSY returns.
* Mark lock_wait and checkpoint_wait as undoc
(cherry picked from commit 4b48ad6fb787a8b8662b5eacad6840d0b3ae9fb5)
=> WT-2646 Add checkpoint_wait configuration option to drop (#2736)

src/cache/cache_las.c
@keithbostic Please review this change.  I tried a handful of wtperf configs with statistics turned on but didn't find any that set the LAS stats.  If you have a workload, let me know.
=> WT-2589 Clear the cursor statistics for LAS when 'clear' is set.

src/include/log.h, src/log/log.c
@michaelcahill Please review this change to improve the error message if there's an error reading a log record at startup.
=> SERVER-23659 Improve log error message at startup.

src/utilities/util_load.c, src/utilities/util_load_json.c, test/suite/suite_subprocess.py, test/suite/test_dump.py, test/suite/test_jsondump02.py, test/suite/test_util02.py, test/suite/test_util07.py, test/suite/test_util12.py, test/suite/test_verify.py
@ddanderson, would you please do the review on this one?
Also, this change doesn't pass the test suite:
```
% pyt test_jsondump02.test_jsondump02.test_json_cursor
FERROR in test_jsondump02.test_jsondump02.test_json_cursor
======================================================================
FAIL: test_jsondump02.test_jsondump02.test_json_cursor
----------------------------------------------------------------------
Traceback (most recent call last):
File "/b/bostic/wt.small/test/suite/test_jsondump02.py", line 288, in test_json_cursor
self.runWt(['load', '-jf', 'jsondump-all.out'])
File "/b/bostic/wt.small/test/suite/suite_subprocess.py", line 162, in runWt
str(procargs) + '": exited ' + str(returncode))
AssertionError: expected success: "['/b/bostic/wt.small/wt', 'load', '-jf', …
```
=> WT-2687 test suite should verify the exit status of the wt utility

src/include/log.h, src/log/log.c
Don't use a flag on the log structure: we may not have one if logging
is disabled, but we still scan log files if they exist.
=> WT-2686 Report an error any time we fail to scan the log.

src/cursor/cur_table.c
@agorrod Please review this.  This fixes the bug reported.  However, I went through the error path code of all `cur_*.c` for `open_cursor` and there is a lot of variation.  Some just free, some just call `wt_cursor_close`, some set `*cursorp = NULL` and some do not.  I'm not convinced in `cur_table.c` that the conditional for `*cursorp` is needed at all.
=> WT-2689 Fix heap-use-after-free on cursor error path.

src/checksum/checksum.c, src/checksum/power8/crc32_wrapper.c
@agorrod, @sueloverso, this should make --enable-strict compile cleanly on the PPC.
=> WT-2682 fix --enable-strict warnings when building on PPC.

dist/s_string.ok, src/log/log.c
Also make file length the actual maximum set, not the maximum plus the header record.  Fix s_string.ok.
@michaelcahill or @agorrod Please review these changes for minor fixes to the logging code.  The fallocate and ftruncate calls were not obeying the log file maximum.  The manual zero-fill does.
=> WT-2652 Remove unnecessary wt_ftruncate call.

dist/api_data.py, src/config/config_def.c, src/include/wiredtiger.in, test/suite/test_config04.py
@keithbostic Please review this change to set the default log path to '.' rather than an empty string.  I also added a section to the config test for it.
=> WT-2514 Fix logging to not use an empty path name.

build_posix/configure.ac.in
Fix for AWS, compiler reports: "cc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)"
=> WT-2682 add option to configure WiredTiger with strict compiler flags

examples/c/ex_file_system.c, src/include/os.h, src/os_common/os_fs_inmemory.c
Probably a left-over from when stdio was still part of the pluggable API.
=> WT-2710 WT_FILE_HANDLE_INMEM no longer needs an off field

src/conn/conn_log.c, src/include/log.h, src/log/log.c, test/recovery/random-abort.c
without writing a log record.
@michaelcahill and @agorrod Please review.  This has been running for a few hundred iterations with both the mongoDB reproducer and random-abort and is ready to merge I believe.
* There was an incorrect assertion where we'd read a slot and fail the assertion because the fields of the slot were changing.
* I added some randomization to the random-abort program.  The minimums are the old values but I let it also run longer and with more threads too.
* There is the fix for the log_fh which is the real fix for the data loss.
* I changed the conditional in `wt_log_write` and added a flag instead of looking at the `log_fh`.  I could have gone either way, adding a `flags` field to the log structure or adding in a log state flag into the connection flags instead.
=> WT-2706 Fix lost log writes when switching files

src/os_common/os_fs_inmemory.c
Commit 62575b5 broke in-memory support, it didn't include either
WT_FILE_HANDLE.lock or WT_FILE_HANDLE.sync. Add stub functions;
I don't think we call either of them enough that it's going to be
a performance problem.
=> WT-2692 Fix race in file system example

src/evict/evict_lru.c
We aren't guaranteed that the cache structure is populated yet, and the value is initialized on cache create regardless.
=> WT-2704 Don't re-initialize pages evicted on eviction thread start.

dist/s_label
Regular expression meta-character needed to be escaped so that egrep works consistently on all systems.
=> WT-2722 s_label fix for false positve

src/btree/bt_debug.c, src/conn/conn_api.c, src/cursor/cur_dump.c, src/cursor/cur_json.c, src/cursor/cur_std.c, src/include/packing.i, src/schema/schema_project.c, src/support/hex.c, src/utilities/util_load_json.c, src/utilities/util_misc.c, test/format/ops.c, test/salvage/salvage.c
gcc 4.7, clang 3.4 and clang 3.8 all complain about different things; cast the arguments to our new wrapper functions, hopefully that makes all of the complaints go away.
=> WT-2691 Use wrappers for ctype functions to avoid sign extension errors

src/btree/bt_split.c
@michaelcahill, this one is probably yours for review.
=> WT-2708 split child-update race with reconciliation/eviction

dist/stat_data.py, src/btree/bt_stat.c, src/btree/bt_sync.c, src/evict/evict_lru.c, src/include/btree.h, src/include/btree.i, src/include/cache.h, src/include/stat.h, src/include/wiredtiger.in, src/support/stat.c, tools/wtstats/stat_data.py
Randomize visits to trees that use a tiny fraction of the cache.
(cherry picked from commit 1d58fe48c7eeefcbe5ee0412daea3c8c16177432)
=> WT-2729 Focus eviction on the largest trees in cache (mongodb-3.2).

dist/s_all
@daveh86, @agorrod, I replaced part of the 083b69b commit with a more portable construct.
It's fine with me if we want to commit to only running scripts under bash, but I think we should make that decision explicitly, and in that case, we should change the shell script interpreter from `/bin/sh` to `/bin/bash` to enforce it.
FTR, this broke under FreeBSD 10.2.
=> WT-2380 Add option to s_all to return an error code when tests fail

src/evict/evict_lru.c
evict_lru.c  Warning 574: Signed-unsigned mix with relational
evict_lru.c  Info 737: Loss of sign in promotion from int to unsigned int
=> WT-2665 Limit allocator fragmentation from the WiredTiger cache

dist/s_string.ok, src/include/wiredtiger.in
Document that readonly pluggable file systems may fail attempts to open
files read/write with EACCES.
Document that pluggable file systems should fail attempts to open
non-existent files with ENOENT.
=> WT-2739 pluggable file systems documentation cleanups

test/recovery/random-abort.c
@keithbostic Please review this change to the random-abort test to check for a partial line.
=> WT-2744 Detect and ignore partial line.

src/btree/bt_curnext.c, src/btree/bt_curprev.c, src/include/cursor.i
@agorrod, I think `WT_CURSOR_BTREE.rip_saved` potentially has the same problem.
I've never seen it happen, this is just by inspection.
=> WT-2730 column-store incorrectly matches key slots on new pages

dist/stat_data.py, src/include/os_fhandle.i, src/include/stat.h, src/include/wiredtiger.in, src/support/stat.c
The increment and decrement were backward, so they never reported positive values.
While I was there make the statistics macros consistent.
=> WT-2743 Fixup new I/O thread count statistics.

src/btree/bt_stat.c, test/suite/test_stat04.py
> Also Alex made some changes to delete some keys and then use wt utility to get stats on the database, and the wt utility shows wrong number of key/val pairs.
@sulabhM, @agorrod, this is the fix for the wt utility mistake.
=> WT-2751 column-store statistics incorrectly calculates the number of entries

bench/wtperf/runners/evict-btree-stress-multi.wtperf
@agorrod This branch only contains a new wtperf config.  I have added some commands to the Jenkins perf-stress job that are commented out.  Once this config exists, I want to turn that on and create a latency plot.  This is the config from WT-2705 primarily.  I used a warning threshold of a quarter second, which is commonly hit on my AWS box (same instance type as the perf jobs).  Please review.
=> WT-1162 Add a latency specific test

build_posix/aclocal/ax_pkg_swig.m4
@sulabhM, @agorrod, swig 3.0 is out.
I upgraded the swig autoconf archive package and added a check for swig 3.0.
=> WT-2756 the autoconf archive package doesn't check for swig 3.0.

ext/compressors/zlib/zlib_compress.c, src/block/block_ext.c, src/block/block_session.c, src/conn/conn_api.c, src/include/intpack.i, src/include/wiredtiger.in, src/txn/txn_log.c, test/cursor_order/cursor_order_ops.c
My flexelint configuration thought size_t was 4B, fix it and clean up the result.
=> WT-2755 flexelint configuration treats size_t as 4B type

src/conn/conn_dhandle.c, src/include/queue.h
@agorrod, @michaelcahill confirmed we shouldn't need write barriers in the TAILQ macros any more, so I've upgraded to the current FreeBSD sys/queue.h file and removed the write-barriers we had in those macros.
I reviewed our TAILQ macro usage and don't see any problems, but Michael suggested the PPC test instance on Jenkins would do a good job of figuring out if we're relying on these barriers anywhere. Maybe we could run this branch overnight on that platform?
=> WT-2578 remove write barriers from the TAILQ_INSERT_XXX macros

src/include/hardware.h
@agorrod, I think this is all we need to do for this ticket.
We might want to consider if we're wasting too much space at some point (the zSeries alignment is 256B, and we align transaction states, for example), but for now I think we should make this change.
=> WT-2648 cache-line alignment for new ports

examples/c/ex_file_system.c, src/block/block_open.c, src/include/os_fs.i, src/include/wiredtiger.in, src/os_common/os_fs_inmemory.c, src/os_posix/os_fs.c, src/os_win/os_fs.c
@agorrod, @michaelcahill, something occurred to me today, I thought I'd run it by you.
As you know, we have a file-system directory-sync method, provided for Linux filesystems that require the enclosing directory to be synced for durability during file create, remove and rename. Currently, only Linux needs the directory-sync method.
First, by having a separate method, we're making it significantly harder to write pluggable filesystems. Imagine a pluggable filesystem that has to do something for durability, but it's nothing like directory-sync. That filesystem can either not specify a directory-sync method and make all operations durable (which might be expensive), or it can specify a directory-sync method and somehow match WiredTiger's call of the directory-sync method to a previous …
=> WT-2760 Backup file removal requires ordering, so needs to sync the directory

src/btree/bt_split.c, src/evict/evict_lru.c, src/include/btree.i, src/meta/meta_track.c
Otherwise there is a race between when we add a page to the queue
and when the page is pulled off the queue - where the updates on
the page may have changed, thus violating transactional constraints.
=> WT-2725 Enforce visibility constraints before evicting a page for mongodb-3.0.

src/utilities/util_dump.c, test/suite/helper.py, test/suite/test_dump.py, test/suite/test_jsondump01.py
This fixes a problem where a table with 1 or more indices, and no column groups would not have any dump output lines for the indices.  Added associated tests for dump and JSON dump.
=> WT-2765 wt dump: indices need to be shown in the dump output

src/evict/evict_lru.c, src/evict/evict_page.c, src/reconcile/rec_write.c, test/format/ops.c
@michaelcahill, I realized I had a bunch of random stuff tucked away in #2874 (and that branch is probably never going to be merged), so I pulled those changes out into this branch.
It's mostly noise, but I do want the enhanced `__wt_cache_dump` output (33e1aca) and the rework of your e41c3e5 commit, in c608c00.
(It occurred to me it would be better to clean up the reconciliation structures when reconciliation finishes, rather than in `__wt_evict`, and then it occurred to me we were already doing that, so I went looking. Long-story short, I merged your change -- which would repeat some of the cleanup we were already doing in reconciliation -- into the existing cleanup code in `__wt_reconcile`. Sorry for not noticing that when you first asked me for review.)
=> WT-2774 minor cleanups/improvements

src/cursor/cur_index.c, test/suite/test_index02.py
More specifically, if search_near is called with a key that appears in
an index, the cursor should be positioned on the first matching key and
`cmp` should be set to zero.
=> WT-2773 search_near in an index should find exact matches.

src/evict/evict_page.c, src/reconcile/rec_write.c
clang 3.4.1 doesn't like this:
```
rec_write.c:1975:46: error: implicit conversion loses integer precision: 'unsigned long' to
'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
```
Also, minor cleanup in `__wt_evict()`.
=> WT-2731 Finer adjustment for page size with raw compression

test/suite/run.py, test/suite/wtscenario.py, test/suite/wttest.py
Several complimentary changes to make life easier for testing:
- Added -s N option to restrict the run to a scenario with a given number or name.
- When showing the name of the test (for example, with -v 2, or when a test fails), if there is a scenario, print as 'fulltestname -s scenario_number' so it can be easily copied for another command run.
- Created a 'testname.txt' file in the test directory with the name of the test (and '-s NNN', if appropriate).
- Fixed the ordering of the symbolic name of a scenario (e.g. 'file.recno.hex'), it was reversed before.
=> WT-2767 in test/suite/run.py, add -s N option to run an individual scenario

src/reconcile/rec_write.c
We can have a saved record of a disk image in page->modify, but with
multi->disk_image == NULL.  In that case, we don't want to copy the
new data over the top: for one thing, it may be compressed.
=> WT-2773 Fix for reusing page images that are not in cache.

src/lsm/lsm_cursor.c, src/lsm/lsm_tree.c
@michaelcahill and @agorrod Please review this change to fix the assertion failure as we discussed last night.  I have see it detect the assertion-triggering situation a few times and continue on with the fix on bengal.
=> WT-2239 Make sure LSM cursors read up to date dsk_gen, it was racing with compact.

src/block/block_write.c, src/evict/evict_page.c, src/reconcile/rec_write.c
* Swap endianness of the page header back after writing (for zSeries).
* Deal with restoring updates when the WT_EVICT_SCRUB flag is not set:
we want to save disk images for only those pages that have updates to
restore.  Unfortunately, that isn't easy to figure out down in the
guts of raw compression.
=> WT-2737 Page scrubbing: more fixes.

bench/wtperf/idle_table_cycle.c, bench/wtperf/runners/checkpoint_schema_race.wtperf, src/include/txn.h, src/lsm/lsm_cursor.c, src/reconcile/rec_write.c, src/txn/txn.c, src/txn/txn_ckpt.c
When logging is disabled, a create operation (and potentially other
metadata updates) could write partially completed checkpoint metadata,
leaving on-disk files inconsistent until the checkpoint completes.
=> WT-2798 Fix data consistency bug with table creates during a checkpoint.

src/evict/evict_page.c, src/reconcile/rec_write.c
(This was introduced in WT-2737).
=> WT-2796 Fix a memory leak when using the lookaside table.

src/session/session_api.c, src/txn/txn.c
When committing a transaction with cursors positioned, copy values
before releasing the transaction snapshot.  Otherwise, there is a window
where the oldest transaction ID could move past the committing
transaction, and the values it needs to copy get freed by another
thread.
This only applies when logging is enabled, and only in applications that
commit transactions with positioned cursors.
=> WT-2802 Copy values during commit before releasing snapshot.

src/support/err.c
Previously, if both a custom and the default error streams failed to
write it caused infinite recursion.
=> WT-2805 Avoid infinite recursion on error stream failure.

src/include/api.h, src/reconcile/rec_write.c, src/session/session_api.c
Improve two recent assertions, one from WT-2798 relating to writing
metadata updates to disk that are part of a running transaction, and
another from WT-2802 that checks that we don't try to copy values from a
cursor without a transaction pinned.  The latter doesn't apply to
cursors on checkpoints (including chunk cursors in an LSM tree).
=> WT-2804 Don't read values in a tree without a snapshot.

build_posix/configure.ac.in
Instead of getting errors like this:
```
(cd /Users/dda/wt/git/wt-2808-configure-swig/lang/java && \
-Wall -v -java -nodefaultctor -nodefaultdtor -package com.wiredtiger.db -I/Users/dda/wt/git/wt-2808-configure-swig/build_posix -outdir src/com/wiredtiger/db -o wiredtiger_wrap.c wiredtiger.i)
/bin/sh: -Wall: command not found
```
you get errors like this:
```
(cd /Users/dda/wt/git/wt-2808-configure-swig/lang/java && \
SWIG_NOT_FOUND_DURING_CONFIGURE -Wall -v -java -nodefaultctor -nodefaultdtor -package com.wiredtiger.db -I/Users/dda/wt/git/wt-2808-configure-swig/build_posix -outdir src/com/wiredtiger/db -o wiredtiger_wrap.c wiredtiger.i)
/bin/sh: SWIG_NOT_FOUND_DURING_CONFIGURE: command not found
```
=> WT-2688 improve build error messages when SWIG is unavailable.

src/include/txn.i
There is a sanity check in reconciliation that transaction IDs always
move forward. The tracked ID is updated by both the checkpoint session
and reconciliation in service of eviction. Recent changes in when
a btree is open for eviction mean that interleaving reconciliation
between eviction and checkpoint made it look like time went backwards.
=> WT-2811 The checkpoint session should not ignore it's own transaction ID

test/format/wts.c
@agorrod please review.  Your comment in the ticket was a bit confusing, but I changed the settings if the chosen cache size is less than 20Mb as well as if it is using LSM.  This allows the two CONFIGs in the ticket to repeatedly complete now.
=> WT-2813 Configure eviction dirty settings explicitly for LSM.

src/evict/evict_lru.c, src/include/btree.i
The existing check discards pages that could potentially have
some reconciliation done on them. This change allows workloads
to make more progress when running with constrained cache sizes.
=> WT-2818 Change the page visibility check when queuing pages for eviction

src/os_win/os_fs.c, test/suite/test_txn07.py
Logging relies on being able to extend files, and the code shuffling for splitting fallocate and truncate meant that it was no longer working on Windows.
=> WT-2638 Add extension to the Windows file system implementation.

src/conn/conn_api.c
This is potentially part of WT-2650, I separated it out.  It shows how we can allow for escapes in configuration values (whether we really need it this particular case, I'm not sure).
To illustrate, consider `blorg.wtperf`:
```
$ cat blorg.wtperf
conn_config="cache_size=500MB,error_prefix=\"hello,\\\"world\\\": \""
sess_config="BLORG"
$ ./wtperf -O blorg.wtperf
[1470334114:635446][3704:0x7fff70dde000], hello,"world": , WT_CONNECTION.open_session: unknown configuration key: 'BLORG': Invalid argument
Error opening a session on WT_TEST Error: Invalid argument
```
=> WT-2650 Allow for backslash escapes in the configuration value for "error_prefix"

dist/api_data.py, src/conn/conn_ckpt.c, src/include/wiredtiger.in, test/suite/test_reconfig03.py
@agorrod Please review this change.  If a user sets a small `log_size` it will use the log file size.  We may or may not want this semi-silent change to the user's config.
=> WT-2827 Set a reasonable minimum for log_size.

src/btree/row_modify.c, src/include/buf.i
@agorrod, I believe that I have clean Evergreen runs, so this should be ready to merge.
=> WT-2631 nullptr is passed for parameters marked with attribute non-null

src/btree/bt_discard.c
=> WT-2835 WT_CONNECTION.leak-memory can skip memory map and cache cleanup

src/conn/conn_open.c
@agorrod, I'm giving up on SERVER-25247, I just don't see it.
Here's a workaround that I think will at least avoid the symptom, and given the number of sessions MongoDB allocates, it's a useful change to make.
=> SERVER-25247 MongoDB primary node crashes after SIGINT (ctrl+c)

dist/s_string.ok, src/cursor/cur_join.c, test/csuite/Makefile.am, test/csuite/wt2834_join_bloom_fix/main.c
This fixes an error in cursor join evaluations that may occur with bloom filters that are shared when false positives are found.  Things to note:
The problem only happens when Bloom filters are specified for parts of the join.  It is less likely when Bloom filters are oversized, and more likely when Bloom filters are undersized. That is the problem occurs with the handling of false positives, which become less likely as the Bloom filter is sized larger. The problem only happens when Bloom filters are shared; that occurs when Bloom filters are specified for multiple parts of a conjunction, and the filters have been given the same size parameter.
The problem will never result in an item not being returned that should be returned.  It will result in item(s) being returned that do not satisfy …
=> WT-2834 Shared bloom filters allow only a partial shortcut.

build_posix/configure.ac.in
@agorrod, @daveh86, as @michaelcahill said, people shouldn't try to build against our source tree -- assuming they're not building the WiredTiger library over and over, requiring a separate install step shouldn't be a big deal.
That said, this particular user is looking at implementing a custom filesystem, so unlike everybody else, he might be repeatedly building the WiredTiger library.
I can't imagine we're going to rename error.h, it's just one of 40 include files, many of which have generic names: api.h, block.h, config.h, extern.h, flags.h, misc.h, posix.h, queue.h and others are all common names, and we're not going to rename all of them.
Here's a possibility: have the configuration step copy wiredtiger_ext.h into the top-level directory along with wiredtiger.h, so you can use `-I …
=> WT-2787 Include src/include/wiredtiger_ext.h is problematic

src/txn/txn_ckpt.c
This initialization was inadvertently removed in WT-2764
=> WT-2841 Initialize verbose checkpoint timer at start of checkpoint

bench/wtperf/config.c, bench/wtperf/wtperf.c, bench/wtperf/wtperf.h
@sulabhM, I didn't realize you owned the JIRA ticket until I was already done, I thought it was a backlog ticket. I apologize for that, my mistake.
@agorrod, we could also just agree we're never going to use wtperf to test for memory leaks, and remove every memory free call from the program -- we're playing relatively fast-and-loose with memory in wtperf at the moment and that would make the whole thing a non-issue.
=> WT-2783 wtperf multi-btree.wtperf dumps core on Mac

src/docs/readonly.dox
Explicitly state that parallel read-only handles depend on WT home directory write permission.
@agorrod please review this change to the read-only documentation.
=> WT-2795 Update read-only documentation

test/recovery/truncated-log.c
@michaelcahill or @agorrod Please review this change to the `test/recovery/truncate-log` test.  It adds a step of adding a log record and then reading it back.  This passes in the current (with truncate) tree and fails when using `configure ac_cv_func_ftruncate=no`.
This only is the test portion.  Logging still has assumptions built in that it can truncate.
=> WT-2843 Modify test for logging if truncate doesn't exist.

src/include/thread_group.h, src/support/thread_group.c
@agorrod This fixes the leak and allows the failing `test/format` config finish successfully.
=> WT-2846 Add flags and fix for destroying thread group.

src/log/log.c
@michaelcahill or @agorrod please review this change to handle log files when truncate is not available.  The change is actually pretty small since `log_zero` already exists.  I'm not thrilled with the goto in there but didn't want to make the code ugly to handle the first-time case.
This passes the new `truncated-log` test both with and without truncate configured.  We need to discuss where/how to get that setting into one of the Jenkins jobs to test this regularly.
=> WT-2843 If there is no truncate available, manually zero the log file.

SConstruct, dist/filelist, dist/s_string.ok, src/include/extern_win.h, src/os_win/os_dir.c, src/os_win/os_dlopen.c, src/os_win/os_fs.c, src/os_win/os_map.c, src/os_win/os_utf8.c, test/mciproject.yml
WT on Windows assumes ASCII file names. I am changing it to support UTF-8 by translating all strings that refer to file names to UTF-16, and calling the Unicode Windows API.
=> WT-2863 WT on Windows does not work with UTF-8 paths

src/evict/evict_lru.c, src/support/thread_group.c
If it were safe there would be no point locking. The test could fail if a reconfigure races with the eviction server starting a new thread.
=> WT-2846 Fixes for new thread group code

src/include/thread_group.h, src/support/thread_group.c
If the thread group was not fully utilized before the shrink happened.
=> WT-2846 Fix a bug in thread group shrink where it could leak memory.

src/evict/evict_lru.c
Recent changes to the eviction server led to a WT_NOTFOUND being propagated unexpectedly.
This isn't ready for merge yet - I'm still working on reproducing the original failure to confirm the fix.
=> WT-2865 Fix a bug where the eviction server could panic after a WT_NOTFOUND

src/btree/bt_read.c, src/btree/bt_split.c
Don't try to repeatedly evict pages if the eviction state hasn't moved
forwards.
=> WT-2869 Fix a performance regression on secondaries.

src/async/async_api.c, src/include/extern.h, src/os_posix/os_mtx_cond.c, src/os_win/os_mtx_cond.c, src/support/thread_group.c
@sueloverso, would you please review & merge?
=> SERVER-25846 Coverity analysis defect 99861: Dereference after null check

src/btree/row_modify.c
=> SERVER-25845 Coverity analysis defect 99859: Explicit null dereferenced

lang/java/Makefile.am, lang/java/wiredtiger.i, test/java/com/wiredtiger/test/ConcurrentCloseTest.java
Also added a test case for the problem.
=> WT-2788 Do not touch memory already freed during a close API call.

src/block/block_compact.c, src/evict/evict_lru.c, src/reconcile/rec_write.c
OS X clang in particular is fussy about size_t vs uint64_t vs uintmax_t.
=> WT-2871 Make verbose formats and argument types match.

bench/wtperf/doxy.c
Reverts wiredtiger/wiredtiger#3002
=> Revert "WT-2842 Add explicit include in wtperf to resolve build warning."

src/evict/evict_lru.c
Only count the queue being empty towards the calculation of whether the server should evict pages if eviction is needed.
=> WT-2866 Don't set eviction stuck unless the cache is full.

src/evict/evict_lru.c
src/evict/evict_lru.c  977  Warning 438: Last value assigned to
variable 'other_queue' (defined at line 830) not used
@keithbostic Please review this change to fix the warning.
=> WT-2866 Fix warning.

src/include/extern.h, src/lsm/lsm_manager.c, src/lsm/lsm_tree.c
@agorrod, I took a look at this, and the ticket is correct, the barrier should be a full-barrier, not a read-barrier.
I also cleaned up a couple of routines that can return void, not int.
EDIT: I backed out the tricky change -- on second thought, it was incorrect, and this change is now really vanilla.
=> WT-2867 Review and fix barrier usage in __lsm_tree_close

SConstruct, dist/s_string.ok, src/include/wt_internal.h, test/format/format.h, test/format/rebalance.c, test/format/util.c, test/mciproject.yml, test/utility/misc.c, test/utility/parse_opts.c, test/utility/test_util.h, test/windows/windows_shim.c, test/windows/windows_shim.h
This PR adds support for running `test/format` on Windows.
1. Build format without Berkley DB,
2. Fix up various commands to run on Windows. In some cases, I needed to `ifdef` the test code.
3. Add one more pthread function to the test windows shim.
4. Random minor compilation fixes (`wt_internal.h`, `format.h`)
In terms of MCI integration, I put in an example task but I have not enabled it until there is a solution for handling crashes & hangs in Evergreen in general.
=> WT-2555 Make Format run on Windows

dist/api_data.py, dist/stat_data.py, src/config/config_def.c, src/conn/conn_cache.c, src/docs/upgrading.dox, src/evict/evict_lru.c, src/include/cache.h, src/include/cache.i, src/include/stat.h, src/include/wiredtiger.in, src/support/stat.c, src/txn/txn_ckpt.c
Also avoid eviction of dirty pages entirely in the eviction server if
worker threads are configured.
=> WT-2901 Make checkpoint scrubbing configurable.

bench/wtperf/runners/multi-btree-read-heavy-stress.wtperf
Via use a high thread count and throttled operations.
=> WT-2894 Add wtperf stress workload that tries to induce negative scaling

src/conn/conn_cache.c, src/evict/evict_lru.c
Also, don't relax the clean / dirty requirements when we get aggressive:
if application threads are blocked by the dirty limit, evicting a clean
page doesn't unblock them so there's no point trying.
=> WT-2910 When running in-memory, only evict dirty pages.

dist/s_all, dist/s_export, dist/s_tags
I'm seeing complaints when I run the dist scripts about `.c` files in dist. The `s_export` script creates the file `__a.c` and shouldn't, the `s_tags` script can avoid creating a `.c` file.
Random minor cleanups along the way.
Ready for review/merge.
=> WT-2918 the dist scripts create C files s_whitespace complains about

dist/s_all, dist/s_c_test_create, dist/s_copyright, dist/s_define, dist/s_docs, dist/s_export, dist/s_funcs, dist/s_label, dist/s_lang, dist/s_longlines, dist/s_prototypes, dist/s_python, dist/s_readme, dist/s_stat, dist/s_string, dist/s_style, dist/s_typedef, dist/s_void, dist/s_whitespace, dist/s_wtstats
@agorrod, when fixing `s_tags` today, I noticed we were forcing script exits of 0 almost everywhere (we probably just cut-and-pasted from one place it made sense). This doesn't clean up error handling completely, but I think it makes it incrementally better.
I'm pointing you at this one because I thought there might be something in the `s_all` changes you made awhile back that require scripts to always exit 0?
Anyway, feel free to simply discard this one without further discussion if you don't like it, entirely up to you.
=> WT-2919 dist scripts force exit 0 on error

dist/api_data.py, src/conn/conn_cache.c, src/include/wiredtiger.in
Reverts WT-2886 commit ac1f7401dcb8be345973f7787d9121c5c321bf7b.
=> WT-2931 Enforce limits on dirty data for in-memory.

test/java/com/wiredtiger/test/ConcurrentCloseTest.java
Additionally some minor code cleanup.
Confirmed that the test still passes.
=> WT-2907 Fixed java concurrent close test to have both insert threads and scan threads.

src/async/async_worker.c, src/btree/bt_sync.c, src/config/config_collapse.c, src/reconcile/rec_write.c, src/support/thread_group.c, src/txn/txn.c
@keithbostic Please review this minor change to remove extraneous newlines from the new thread group verbose messages.
=> WT-2942 Verbose messages should not have newlines.

src/btree/bt_sync.c, src/evict/evict_lru.c, src/include/cache.i, src/include/txn.h, src/include/txn.i, src/lsm/lsm_cursor.c, src/session/session_api.c, src/txn/txn.c, src/txn/txn_ckpt.c, src/txn/txn_nsnap.c, test/format/lrt.c
The changes in WT-2798 introduced a bug into the allocation of named
snapshots when a checkpoint is running.  This bug should not have led to
invalid reads or data corruption but violated some sanity checking in
diagnostic builds.
=> WT-2933 Fix a race between named snapshots and checkpoints.

test/format/util.c
@agorrod, since it made a difference for wtperf, might as well speed up format, too.
=> WT-2941 format should use faster key-generation functions

dist/s_docs
@ddanderson, my apologies for the failure, I don't usually build documentation on my OS X box.
This change fixes the problem for me, for your review/consideration.
cc: @sueloverso
=> WT-2946 dist/s_docs incompatible with OS X Xcode installation

dist/stat_data.py, src/evict/evict_lru.c, src/include/stat.h, src/include/wiredtiger.in, src/support/stat.c
It occurs to me usecs is an awfully small unit for an aggregated statistic, but it is what we use elsewhere, so I guess it makes sense for consistency.
=> WT-2920 New eviction statistics

dist/api_data.py, src/btree/bt_handle.c, src/config/config_def.c, src/evict/evict_lru.c, src/include/api.h, src/include/btree.h, src/include/wiredtiger.in, test/suite/test_inmem02.py
Only available for in-memory configurations, designed to be used for
applications that maintain a small amount of content that is required
for correctness.
=> WT-2932 Add a configuration option allowing tables to ignore cache limits

src/evict/evict_lru.c
../src/evict/evict_lru.c:1081:29: error: implicit conversion loses integer precision: 'unsigned long long' to 'u_int' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
WT_MIN(max_entries, 1 + __wt_cache_pages_inuse(cache) / 2);
~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/include/misc.h:62:42: note: expanded from macro 'WT_MIN'
^
../src/evict/evict_lru.c:1084:29: error: implicit conversion loses integer precision: 'unsigned long long' to 'u_int' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
WT_MIN(max_entries, 1 + cache->pages_dirty_leaf / 2);
~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/include/misc.h:62:42: note: expanded from macro 'WT_MIN'
=> WT-2937 Fix a warning.

bench/wtperf/wtperf.c, test/bloom/test_bloom.c, test/checkpoint/test_checkpoint.c, test/csuite/wt1965_col_efficiency/main.c, test/csuite/wt2246_col_append/main.c, test/csuite/wt2323_join_visibility/main.c, test/csuite/wt2447_join_main_table/main.c, test/csuite/wt2535_insert_race/main.c, test/csuite/wt2592_join_schema/main.c, test/csuite/wt2695_checksum/main.c, test/csuite/wt2719_reconfig/main.c, test/csuite/wt2834_join_bloom_fix/main.c, test/csuite/wt2853_perf/main.c, test/cursor_order/cursor_order.c, test/fops/t.c, test/format/t.c, test/huge/huge.c, test/manydbs/manydbs.c, test/packing/intpack-test.c, test/packing/intpack-test2.c, test/packing/intpack-test3.c, test/packing/packing-test.c, test/readonly/readonly.c, test/recovery/random-abort.c, test/recovery/truncated-log.c, test/salvage/salvage.c, test/thread/t.c, test/utility/misc.c, test/utility/parse_opts.c, test/utility/test_util.h
=> WT-2956 utility tests -h option is always overridden by the default setup

src/include/extern.h, src/session/session_api.c, src/txn/txn.c
@agorrod, I managed to get a core dump with an experimental change I was playing with, and the reason is we're using the WT_SESSION_IMPL we're initializing before we've finished initializing it.
Feel free to throw this away if you don't like it, it wouldn't have fired if I hadn't been modifying session initialization.
=> WT-2959 don't use WT_SESSION_IMPL before it's initialized

src/block/block_ckpt.c, test/format/config.c
We weren't adjusting the rolling checkpoint size for the size of the root page.
=> WT-2904 reported checkpoint size many times data size

src/block/block_ckpt.c
It broke backward compatability.
=> WT-2904 Revert overly strong assertion.

src/support/mtx_rw.c, src/txn/txn.c
We could be starving a thread that we are waiting on of CPU.
=> SERVER-26753 Don't spin on a read-lock in a tight loop.

dist/log.py, dist/log_data.py, src/include/wiredtiger.in
@keithbostic and @michaelcahill  Please review.  I added comments in log_data.py to remind people to add them to the include file.  Is it clear and visible enough?  Is there an easy way to verify they did add the `#define` in one of the`s_` scripts?
=> WT-3003 Don't generate log record and op types.  They must be static.

ext/collators/revint/revint_collator.c, ext/compressors/zlib/zlib_compress.c, ext/compressors/zstd/zstd_compress.c, ext/datasources/helium/helium.c, ext/encryptors/nop/nop_encrypt.c, ext/encryptors/rotn/rotn_encrypt.c, ext/extractors/csv/csv_extractor.c, ext/test/kvs_bdb/kvs_bdb.c
@michaelcahill, I noticed we were naming `WT_EXTENSION_API` objects inconsistently when I was working on the zstd changes (probably because you and I each wrote a chunk). The core code consistently uses `wt_api`, so I switched the extension code to match.
There's no other change in this branch.
=> WT-3001 WT_EXTENSION_API references are named inconsistently.

src/btree/bt_split.c
Fix 552a33b (cherry-picked from 521270d). When the commit was merged, a line was dropped.
@michaelcahill, for your review: you can see the difference if you compare 521270d and 552a33b, the line `ref->addr = addr;` should have been removed and wasn't. I think the result is `ref->addr` can potentially point to freed memory.
=> SERVER-26889 Got signal: 11 (Segmentation fault) in 3.0.13

src/schema/schema_util.c
We were clearing the shared pointer to the list of filenames in the
backup, then releasing the hotbackup lock before clearing the hotbackup
flag.  That means drops need to check both the flag and that the pointer
is non-NULL.
=> WT-2968 Fix a segfault when a drop races with closing a backup cursor.

src/cursor/cur_join.c, src/cursor/cur_json.c
@ddanderson, this one is for you, please.
Two changes.
First, Coverity had a false positive about some code in `__wt_curjoin_open()`, and while looking at it, I noticed we were storing `table:xxx` in the cursor's `internal_uri` field rather than `join:table:xxx`, which looks wrong to me. By happy coincidence, this change should also keep Coverity quiet.
Second, there was one thing I noticed awhile ago was that the __wt_json_token() error handling was a little strange. All but one error wrote out a message and then  fell out of the switch statement to fail (setting the returned token type to -1), and the one other error simply returned (not setting the returned token type). I switched all of the errors to immediately return instead of falling out of the switch statement.
If I'm …
=> WT-3011 __wt_curjoin_open() saves the wrong URI in the cursor.

dist/api_data.py, examples/c/ex_all.c, examples/c/ex_file_system.c, ext/compressors/zlib/zlib_compress.c, ext/compressors/zstd/zstd_compress.c, ext/datasources/helium/helium.c, ext/encryptors/rotn/rotn_encrypt.c, src/config/config.c, src/config/config_def.c, src/config/config_ext.c, src/conn/conn_api.c, src/include/extern.h, src/include/wiredtiger.in, src/include/wiredtiger_ext.h, test/format/config.c
While in the area, fix sending "config={values}" to extensions: just
the values should be passed in.
=> WT-2962 Allow configuration of builtin extensions.

src/btree/bt_handle.c, src/conn/conn_dhandle.c, src/conn/conn_open.c, src/conn/conn_sweep.c, src/include/meta.h, src/include/txn.h, src/include/txn.i, src/session/session_dhandle.c, src/txn/txn.c, src/txn/txn_ckpt.c
Since we treat the checkpoint transaction specially, we also have to
track the amount of history required for the metadata specially.
Previously, there was a window where a query started while a checkpoint
was running could fail to see the results of the checkpoint when it
queried the metadata.
=> WT-2984 Keep sufficient history in the metadata for queries.

src/include/btree.i
Reverts a bug introduced in WT-3012.
=> WT-3020 Always make LSM chunks evictable when they are switched out.

src/log/log.c
@michaelcahill Please review this minor fix.  While doing WT-3000 I noticed this bug in the error path.
=> WT-3025 Fix error path in log_force_sync.

src/btree/bt_split.c, src/evict/evict_page.c
Fixes part of WT-3023, which was only supposed to avoid counting page
rewrites as progress...
=> WT-3028 Count eviction of dirty pages as progress.

dist/s_void, src/btree/bt_cursor.c, src/include/btree.h
WT-3048 WiredTiger maximum size warning uses the wrong format.
=> WT-3048 WiredTiger maximum size warning uses the wrong format.

examples/java/com/wiredtiger/examples/ex_log.java, lang/java/src/com/wiredtiger/db/PackOutputStream.java, lang/java/wiredtiger.i, src/cursor/cur_log.c
Here are a set of fixes needed to get java log example to fully work.
=> WT-3021 fixes for java log example, raw mode in java, and raw mode in log cursors

bench/wtperf/idle_table_cycle.c, lang/java/wiredtiger.i, lang/python/wiredtiger.i, src/include/extern.h, src/include/extern_posix.h, src/os_common/os_alloc.c, src/os_posix/os_sleep.c, src/support/err.c
Remove calls to internal WiredTiger functions from the Java and Python APIs, meaning we no longer need to expose a few more internal WiredTiger functions.
=> WT-3053 Python and Java support use internal WiredTiger functions

lang/python/wiredtiger.i
Since we aren't going to make allocation functions hidden, revert
changes to the Python API in WT-3014 so it uses internal memory
allocation functions, matching the Java API.
=> WT-3053 Make Python use internal memory allocation again.

lang/java/wiredtiger.i
When an AsyncOp (java object) is created, cache whether the cursor is "Raw".
Later, when an application is fetching keys/values from the AsyncOp,
the JAVA_CALLBACK object may be detached from the (java) AsyncOp, which makes
finding out information about the cursor impossible.  See the JIRA for more detailed info.
=> WT-3055 Fix timing related failures in Java AsyncOp tests

src/btree/bt_discard.c, src/btree/bt_read.c, src/btree/bt_split.c, src/evict/evict_page.c, src/include/btmem.h, src/include/btree.i, src/include/extern.h, src/include/session.h, src/support/hazard.c
@michaelcahill, this is the change we talked about, I think it turned out to be as simple as we thought.
I didn't drive the change down as deeply into the split code as I probably should have, but trying to was relatively messy: code that needs to lock both WT_REF structures and WT_PAGE structures is inherently messy in our code.
=> WT-3057 WiredTiger hazard pointers should use the WT_REF, not the WT_PAGE.

.gitignore, NEWS, dist/s_string.ok
WT-3064 minor tree cleanups: .gitignore, NEWS misspelling
=> WT-3064 minor tree cleanups: .gitignore, NEWS misspelling

test/syscall/syscall.py, test/syscall/wt2336_base/base.run
Not 100% if this is the best way to proceed here, re pwrite vs pwrite64.
If it is, then we would have to exclude some of the Jenkins machines from testing. The alternative is to find a way to check if the system has pwrite or pwrite64 registered in strace.
=> WT-3061 Ensure checkpoint syncs are run as part of syscall testing

lang/java/wiredtiger.i, lang/python/setup.py
These changes allow a tree to be built with -Werror=sign-conversion along with Java and Python enabled.
=> WT-3071 Fixed sign-conversion errors in Java SWIG code

src/cursor/cur_index.c, test/suite/test_index02.py
Since WT-2773, the sign of the `exact` result was flipped and
WT_NOTFOUND was returned for search_near calls with a key past the end
of the index.
=> WT-3070 Fix search_near on indexes.

build_posix/configure.ac.in, test/format/util.c
@michaelcahill, @agorrod, @daveh86: I ended up turning off `std=c11` on Solaris, everything else was just too painful, and involved setting compiler flags that weren't strictly documented.
I also made a pass through `configure.ac.in` to try and clean up how we were setting flags as well as the order in which we set them.
I haven't yet tested this as much as I'd like, but I wanted to push it so you folks have a chance to see where I'm heading and say "no".
=> WT-2402 Misaligned structure accesses lead to undefined behavior

test/suite/wttest.py
This does increase the amount of console output, but having an effective way to reduce the test suite time seems worth it.
=> WT-3080 Python test suite: add elapsed time for tests

test/suite/test_backup03.py, test/suite/test_config03.py, test/suite/test_intpack.py, test/suite/test_join01.py, test/suite/test_lsm01.py, test/suite/test_truncate01.py, test/suite/test_truncate02.py, test/suite/test_txn07.py
Tests that have lots of scenarios will have the number of scenarios pruned in the default case.  Running with --long restores the previous larger number of scenarios.
This runs about 25% faster in my standalone testing.
=> WT-3082 Python test suite: shorten default run to avoid timeouts.

src/cursor/cur_index.c, src/cursor/cur_json.c, src/cursor/cur_table.c, src/include/extern.h, src/utilities/util_dump.c, test/suite/test_dump.py, test/suite/test_jsondump02.py, test/suite/wtdataset.py
When dumping with a projection, the dumped metadata associated with the table is modified so that the list of columns matches the list from the projection, and the value format corresponds to projected format.  We use an open cursor using the projection to obtain the value format to show, that requires a slight reordering of when cursors are opened in the dump utility.
Also fix a problem in the JSON dump cursor which did not handle projections.
=> WT-2833 Add projections to wt dump utility

src/evict/evict_lru.c, src/include/mutex.i, src/include/schema.h
@keithbostic Please review this change to add the locking stats to the try-lock path.  I ran the evict-btree.wtperf workload on develop and this branch.  Develop acquires the dhandle list lock 47 times.  This branch is 116721 acquisitions.
=> WT-3112 Add lock statistics to try_lock path.

src/evict/evict_lru.c, src/include/mutex.i
@agorrod  Please review this change to make try-lock stats not perform timing per-attempt, but overall in the eviction code per our discussion.
=> WT-3112 Time the eviction try-lock for the dhandle overall, not per-attempt

src/evict/evict_lru.c, src/include/connection.h
@agorrod Here's the change to allocate and create all the eviction thread sessions at the start to avoid the deadlock,
=> WT-3105 Create all eviction sessions initially to avoid deadlock.

dist/log_data.py, src/include/extern.h, src/include/log.h, src/include/wiredtiger.in, src/log/log.c, src/log/log_sys.c, src/txn/txn_log.c, test/recovery/truncated-log.c
@michaelcahill and @agorrod Here's a slightly different take on the new prevlsn log record.  I've renamed it to `system` and included a currently unused WT_ITEM in the record.  The thought is that we may want to include other information in this record someday and then all the plumbing is there (if the "other information" maps only to a WT_ITEM).  This is a branch off the other branch, wt-3039-prevlsn, so can be merged if you like it.
=> WT-3039 Make new log record more general for potential future expansion.

dist/s_all
bug: dist/s_all script has misplaced quote causing bad error reporting
=> WT-3126 bug: dist/s_all script has misplaced quote causing bad error reporting

src/txn/txn_log.c, test/suite/test_reconfig02.py, test/suite/test_txn02.py, test/suite/test_txn05.py
@agorrod Please review this change.  It was smaller than I originally thought it would be even.  Essentially one line and a few archiving related tests.  This will avoid archiving log files after recovery until after the first "ongoing" checkpoint is written.
=> WT-3114 Avoid archive immediately after recovery.

src/evict/evict_lru.c, src/support/thread_group.c
@agorrod Please review this.  Unfortunately I've been running both the format CONFIG and the evict btree wtperf workload on develop without reproducing the deadlock.  So while I think this fixes the deadlock, I have not been able to confirm either way.  The branch runs fine too for my testing.
=> WT-3105 Avoid thread group deadlock on close.

src/os_posix/os_yield.c, src/os_win/os_yield.c
bug: CPU yield calls don't necessarily imply memory barriers
Add a full-barrier as part of the yield call.
=> WT-3127 bug: CPU yield calls don't necessarily imply memory barriers

src/conn/conn_cache.c, src/include/connection.h, test/suite/test_reconfig01.py
@agorrod Please review this omission from the original change.  I discovered that reconfigure was not fixed and that we had no test to eviction thread changes.  I did run the new test the first time with `verbose=(thread_group)` to confirm the right stuff is happening.
=> WT-3105 Fix the thread group usage on eviction reconfigure and add test.

src/log/log.c
Add a verbose message if we don't find any log files, it's likely the user pointed us at the wrong directory.
@sueloverso, would you please review this change?
=> WT-3128 wt printlog returns operation-not-supported if it doesn't find any log files

src/conn/conn_api.c
@agorrod, for your consideration.
I changed it so `WT_CONNECTION.get_home()` will work before we load the extensions. I also configure error handling a little earlier, I thought that made sense to do before loading extensions.
=> WT-3130 Proposal to change initialization of custom filesystem

bench/wtperf/wtperf.c
Coverity 1369053: assigning values that are never subsequently used.
=> WT-3143 Coverity scan report 1369053

src/btree/bt_debug.c, src/btree/bt_split.c
Now the WT_REF is the primary "page" reference, we should print it instead of WT_REF.page in verbose/debugging output.
=> WT-3144 bug fix: random cursor returns not-found when descending to an empty page

examples/c/ex_file_system.c, ext/test/fail_fs/fail_fs.c, src/conn/conn_api.c, test/csuite/wt3120_filesys/main.c
Lint/Coverity. Some of the code was copied from example code, which is why there are changes there as well.
=> WT-3120 Fix ordering problem in connection_close for filesystem loaded in an extension

test/suite/test_sweep01.py
Ready for review once testing on evergreen completes.  After looking at some debugging statistics during a failure, I realized there is a lag between when sweep closes files and when it can remove data handles from the connection list.  On slow machines, we can hit the test failure if we catch it between those two.  So I modified the test where it looks at statistics to look for any change in the removed statistic instead of closed files.
=> WT-2790 Look at removed statistics instead of files closed.

src/include/log.h, src/log/log_slot.c
Lint:
Don't print int32_t's with %d.
WT_LOGSLOT.slot_error is an int, not an int32_t.
Don't print off_t's as 32-bits, use the maximum size unsigned object.
=> WT-3137 Fix a hang in logging due to a race condition

bench/wtperf/config.c, bench/wtperf/stress/btree-split-stress.wtperf, bench/wtperf/wtperf.c, bench/wtperf/wtperf.h, bench/wtperf/wtperf_opt.i, src/docs/wtperf.dox
@agorrod I took a pass at implementing my suggestions and I think it is a bit cleaner and requires less new code than your original implementation.  I didn't take it any further than testing the one `stress` workload I found using `read_range`.  Review and merge if you like this better (it is based off your branch).
=> WT-3139 Implement scans as read_range.

src/evict/evict_lru.c, src/include/cache.h, src/include/extern.h, src/include/thread_group.h, src/support/thread_group.c
@agorrod Here are the changes to make the thread group code the wrapper for the activate and pause of threads.  It required a bunch of changes.  I think conceptually it is cleaner, but in some ways the eviction code is a bit less intuitive since it is no longer a server loop.  I had to add both a check function and a stop function for threads to call.  Let me know what you think.
=> WT-3123 Have thread active/pause wrapper in thread group code.

src/txn/txn_ckpt.c
@agorrod and @ddanderson Here is a fix for WT-3164 that is based off develop, but tested with Don's branch.  With this fix (and my hand placed error per the ticket) the command now proceeds further and fails with the same error as WT-3165.  Without any hand-injected error at that specific location the test command succeeds.  But the fix needs to be in develop and can then be merged into Don's branch.  Please review.
=> WT-3164 Reset ckpt field on error.  Add error reset function.

src/checksum/power8/crc32_wrapper.c, src/checksum/zseries/crc32-s390x.c
The CRC32 hardware support for s390x is only available on z13 processors and later and require a Linux kernel version which support the vector extensions. Runtime detection can be accomplished by querying `auxv` for the `HW_CAP` of `HWCAP_S390_VX`.
Change:
`zseries/crc32-s390x.c` :
- Move `wt_internal.h` header to top for consistency and to get the `HAVE_CRC32_HARDWARE` define.
- Include `sys/auxv.h` to call `getauxval` and access `HW_CAP` which reads `/proc/PID/auxv`.
- Define `HWCAP_S390_VX` if not defined, this is needed on RHEL 7.1 which has the kernel support for the VX extensions but not the glibc support. This constant is define in the Linux kernel header `asm/elf.h` for s390.
`power8/crc32_wrapper.c`:
- Move `wt_internal.h` header to top for consistency
**Tests:**
Passes MongoDB …
=> WT-3173 Add runtime detection for s390x CRC32 hardware support

dist/s_string.ok, dist/s_void, src/cursor/cur_index.c, src/include/packing.i, src/txn/txn_log.c, test/csuite/Makefile.am, test/csuite/wt3135_search_near_collator/main.c
As part of the fix for search_near, this includes a fix for how format 'U' is interpreted.  'U' should always include the size, before this change, it did not if the 'U' appeared at the end of the format. As a side effect of this change, WT-3159 is also fixed.
=> WT-3135 WT-3159 Fix search_near() with custom collators for index keys of variable length.

src/btree/bt_split.c
Reverts part of 7f5d0f9981214c723f2ed90cf4533887ed406176.
Fixes a deadlock in diagnostic mode.  Also revert a change that could
cause diagnostic code to read pages into cache: we don't want diagnostic
adding cache pressure and we already verify pages as they are evicted.
=> WT-3175 Don't verify children during splits up the tree.

ext/test/fail_fs/fail_fs.c
FreeBSD's backtrace is the outlier, everybody else (OS X, Solaris, Linux is using int types, not size_t).
=> WT-2909 Create automatable test verifying checkpoint integrity after errors

ext/test/fail_fs/fail_fs.c
@keithbostic noticed these issues:
* there’s a fprintf to stderr in fail_fs.c.
* The fail_file_truncate() function calls `ftruncate`, and I don't think `ftruncate` is always thread-safe, does that matter here?
* There's an access(2) call that uses and argument of 0, instead of F_OK.
This commit has fixes for first and last.  I don't know the answer for ftruncate, but I see that the truncate function in the default posix file system (see `os_posix/os_fs.c`) also calls ftruncate here. If it matters here, it will matter there as well.
=> WT-3179 test bug: clang sanitizer failure in fail_fs

src/include/extern.h, src/log/log.c, src/log/log_slot.c
@agorrod Here is a fix for one path I found looking at the stack from the failure.  I have not been able to reproduce the hang even with some simple error injection directly but based on the stack and errors, this is definitely a problem path.  This fixes two loops that didn't break and weren't checking for panic.
=> WT-3186 Fix error path and panic detection in logging loops.

src/cursor/cur_index.c, src/cursor/cur_std.c, src/include/wiredtiger.in, test/csuite/Makefile.am, test/csuite/wt3184_dup_index_collator/main.c
In this case, we must use the entire (raw) key to duplicate the position,
instead of truncating to the visible part.
=> WT-3184 bug fix: duplication needs special case searching an index that has a custom collator.

src/log/log.c, src/log/log_slot.c
@agorrod Here are a few more panic checking changes.  I had another similar hang today.  I went through all of the logging source files looking at loops where we're waiting for something and added a check rather than fault them in.
=> WT-3188 More log loops needing to check panic.

src/conn/conn_cache_pool.c
We could get into situations where no participants looked like good candidates.
Also put a failsafe into the balance loop, to ensure future failures to reduce usage won't lead to hang on shutdown.
=> WT-3187 Ramp up aggressiveness in reducing cache pool usage

src/btree/bt_random.c
A NULL page could be encountered when traversing a tree that is
being used by exclusive access.
=> WT-3189 Fix a segfault in eviction random page search.

src/evict/evict_lru.c, src/include/btree.h
Choosing a random point isn't very efficient in append only workloads.
=> WT-3149 Use a range of eviction walk start points.

src/evict/evict_lru.c
src/evict/evict_lru.c:1683:2: error: default label in switch which covers all enumeration values [-Werror,-Wcovered-switch-default]
=> WT-3149 Fix a compiler warning on OS X.

test/checkpoint/smoke.sh, test/csuite/wt2246_col_append/main.c, test/csuite/wt2323_join_visibility/main.c, test/csuite/wt2535_insert_race/main.c, test/csuite/wt2834_join_bloom_fix/main.c, test/csuite/wt2853_perf/main.c, test/csuite/wt2909_checkpoint_integrity/main.c, test/utility/misc.c, test/utility/test_util.h
@agorrod, here's a first cut at this one.
I think this is all that's necessary in the source code, but maybe I'm missing the big picture!
Let me know if you agree -- we can merge, which will just turn off long tests everywhere.
We can talk over what test harnesses should enable long tests and I'll make/test those changes.
=> WT-3182 Switch make-check to run the short test suite by default

src/btree/bt_handle.c
@agorrod, I think this change fixes a core dump on the zSeries today:
```
Backtrace:
build_posix/../src/evict/evict_lru.c:103 (discriminator 1)(__evict_entry_priority)[0x800386e2]
build_posix/../src/evict/evict_lru.c:1521(__evict_push_candidate)[0x8003c212]
build_posix/../src/evict/evict_lru.c:2272 (discriminator 1)(__wt_page_evict_urgent)[0x8003e7d4]
build_posix/../src/evict/evict_lru.c:1778(__evict_walk_file)[0x8003cb3e]
build_posix/../src/evict/evict_lru.c:1444(__evict_walk)[0x8003bef4]
build_posix/../src/evict/evict_lru.c:1167(__evict_lru_walk)[0x8003b558]
build_posix/../src/evict/evict_lru.c:664(__evict_pass)[0x80039e82]
build_posix/../src/evict/evict_lru.c:387(__evict_server)[0x8003933e]
build_posix/../src/evict/evict_lru.c:308(__wt_evict_thread_run)[0x80038f56] …
```
=> WT-3193 Close a race between verify opening a handle and eviction visiting it

test/format/config.c
@keithbostic Please review this small fix to allow the generated CONFIG to be used on the next run.
=> WT-3213 Only error if fixed-length and long_running_txn is set.

src/docs/upgrading.dox, src/txn/txn_ckpt.c, test/fops/file.c, test/fops/t.c
Continue to return EBUSY. Have test/fops handle EBUSY returns from forced checkpoints.
=> WT-3207 Report a message for conflicting forced checkpoints, rather than an error

bench/wtperf/runners/many-table-stress.wtperf, src/conn/conn_dhandle.c
Recheck for existence after acquiring write lock when creating a new dhandle.
=> WT-3218 Avoid adding duplicate handles to connection dhandle list

lang/python/setup_pip.py, lang/python/wiredtiger/pip_init.py
This pull request is currently for discussion, as it has a caveat in how it works.  That is, this version will not create a wheel (the preferred method for the pip installer), but it will fall back to an older way of building/installing the distribution. [JIRA description of the issue.](https://jira.mongodb.org/browse/WT-2978?focusedCommentId=1517052&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1517052) I'm going to continue to work on a better way to solve this.
Then, to create a distribution do: `cd lang/python; python setup_pip.py sdist`, that creates a `.tar.gz` file in `lang/python/dist`.
To test it out on a target machine, you need pip, and it's helpful to have virtualenv (so you don't need to install anything as root).  [If you don't have virtualenv …
=> WT-2978 Python: make a pip-compatible installer.

src/btree/bt_read.c, src/btree/bt_sync.c, src/evict/evict_page.c, src/include/btree.h, src/include/btree.i
Don't do in-memory splits on the LSM primary.
=> WT-3224 LSM assertion failure pindex->entries == 1

src/lsm/lsm_work_unit.c
Once an LSM primary is known to be on disk, we expect readers to use the
checkpoint.  The original page image for the primary will then be
discarded by an LSM worker thread.
We previously allowed the LSM primary to be evicted in between so that
eviction workers can deal with cache pressure ahead of the LSM worker
threads discarding the chunk.  However, that leads to cases where
application threads end up evicting a 100MB page, and also means that
discarding the chunk needs to worry about split generations (the cause
of the assertion failure here).
The solution suggested here is simple: never enable eviction in LSM
primaries, which also means we never need to fix up cache accounting.
=> WT-3196 Prevent eviction in LSM primaries after they are flushed.

src/lsm/lsm_work_unit.c
@keithbostic Please review this change.  The merge of the changes for WT-3196 removed using the dhandle lock (I don't know why).  Restoring the use of this lock fixes my repro case.
=> WT-2990 Restore use of dhandle lock in LSM.

test/format/ops.c
The real change is 1cf0ba0, cf573d6 is just code shuffling.
The fix is in format, so I'm going to go ahead and merge this change once it passes testing.
=> WT-98 Update the current cursor value without a search

bench/wtperf/wtperf.c, dist/s_style
Add a style check for local snprintf/vnsprintf calls, fix a wtperf snprintf call I missed.
This only changes test and style code, I'm going to merge as soon as it passes the tests.
=> WT-3136 bug fix: WiredTiger doesn't check sprintf calls for error return

bench/wtperf/wtperf.c, src/config/config_api.c, src/os_common/filename.c, src/utilities/util_dump.c, src/utilities/util_load_json.c, src/utilities/util_main.c
Coverity reports based on the new `__wt_snprintf` errors.
=> WT-3240 Coverity reports

lang/java/Makefile.am, lang/java/wiredtiger.i, test/java/com/wiredtiger/test/CursorTest03.java, test/java/com/wiredtiger/test/WiredTigerSuite.java
Non-zero int values for these functions should not raise exceptions.
This commit includes various tests for compare/equals.
=> WT-3238 Java: Fix Cursor.compare and Cursor.equals to return int values.

src/btree/bt_handle.c
@michaelcahill, turning off in-memory cache-full checks on the metadata file is obviously a relatively big hammer.
If that's too dangerous, we could turn off the cache checks on just the unroll operations? Let me know what you prefer.
=> WT-3244 metadata operations failing in in-memory configurations

src/include/mutex.i
A MongoDB user on Windows noticed the "LSM: application work units currently queued" statistic was changing in a configuration that involved no LSM code. This was caused by a bug in code that tracks time spent in spinlocks incrementing the wrong statistic.
In particular, spinlocks contain fields describing which statistics should be used to track time spent in that spinlock.  A value of -1 indicates that the spinlock should not be tracked, but a value of zero is the first statistic in the array for a connection, which happens to be the "LSM: application work units currently queued" statistic.  The Windows implementation of spinlocks was not setting these fields to -1, leading to the bug.
This bug was introduced by WT-2955 and also meant that every WiredTiger spinlock on Windows was being …
=> WT-3250 Fix spinlock statistics tracking on Windows.

src/include/extern.h, src/log/log.c, src/log/log_slot.c
We could race an in-progress switch that set a new, empty active slot
but has not yet released the previously active slot and get an
incorrect LSN.
=> WT-3249 Look at slot_state during force while holding lock.

test/recovery/truncated-log.c
@michaelcahill Please review these changes.  I don't recall what Jenkins job prompted this.  However when I run `develop` I get a core file generated and with this change I do not, as expected and the test passes.  This test is not a randomly aborting test.
=> WT-3247 Test should exit instead of abort to avoid a core dump.

test/suite/test_txn02.py, test/suite/test_txn05.py, test/suite/test_txn07.py
@ddanderson Please review this changes to a few txn tests.  If we are only writing log records in memory we need to flush the log before making a backup to make sure all records are there before copying.  This bug has been in there a long time but recent changes widened a window.
=> WT-3253 Update Python transaction tests to have correct flush configuration

src/async/async_worker.c, src/conn/conn_log.c
@sueloverso, the log threads didn't panic on unexpected exit, the async worker threads checked for panic (unlike the other server threads).
Can you please review?
=> WT-3245 Avoid hangs on shutdown when a utility thread encounters an error

src/include/btree.i
When pages split in WiredTiger, internal pages cannot be evicted
immediately because there is a chance that a reader is still looking at
an index pointing to the page.  We check for this when considering pages
for eviction, and assert that we never evict an internal page in an
active generation.
However, if a page splits and then we try to get exclusive access to
the tree (e.g., to verify it), we could fail to evict the tree from
cache even though we have guaranteed exclusive access to it.
Relax the check on internal pages to allow eviction from trees that are
locked exclusive.
=> WT-3265 Allow eviction of recently split pages when tree is locked.

src/checksum/arm64/crc32-arm64.c, src/checksum/zseries/crc32-s390x.c
getauxval is a Linux system call, don't attempt to call it unless we're running on a Linux system.
=> WT-3197 aarch64 CRC32C support fails to compile on non-linux ARM platforms

src/include/btree.i, src/txn/txn_log.c
It's simpler/faster to take the row-store log key from the cursor instead of getting it from the page.
=> WT-3278 log the row-store cursor key instead of page key

examples/c/ex_file_system.c, ext/test/fail_fs/fail_fs.c, src/async/async_api.c, src/async/async_worker.c, src/conn/conn_api.c, src/conn/conn_dhandle.c, src/conn/conn_sweep.c, src/include/misc.h, src/lsm/lsm_manager.c, src/lsm/lsm_tree.c, src/os_common/os_fhandle.c, src/os_common/os_fs_inmemory.c, src/schema/schema_list.c, src/session/session_api.c, src/session/session_dhandle.c
@sulabhM, this was a great catch!
Here's a possible solution for your review -- I found two related infinite loops and fixed them as well.
What makes this change a little messy is there wasn't a single change that matched the problems: I added a generic pair of macros that wrap the TAILQ walk, so if we hit the same element twice in the walk, we remove it from the queue, and used that in two cases. I think that approach is appropriate for walks where there are a variety of underlying functions that are expected to remove the element from the queue, where we won't know if the element was removed after they fail.
In a third case, I added a force flag to an underlying function so it always removes the queue element.
And, there was one restructuring that just cleaned up some messy code in a …
=> WT-3268 Failure to close cursor can get wiredtiger stuck in a cursor-close loop

src/support/thread_group.c
Discard any allocated thread structure on error.
=> SERVER-28835 Coverity analysis defect 101330: Resource leak

src/btree/bt_compact.c, src/btree/bt_sync.c, src/cache/cache_las.c, src/conn/conn_log.c, src/log/log.c, src/lsm/lsm_manager.c, src/lsm/lsm_tree.c, src/os_posix/os_sleep.c, src/os_win/os_sleep.c, src/session/session_compact.c, src/txn/txn_ckpt.c
@michaelcahill, I reviewed the places where we use full-barriers after our discussions last week, intending to remove the places I'd been (unnecessarily) using them for visibility.
There's only one "real" fix in this branch, commit 13b9f16. It ensures calls to `__wt_sleep` are barriers (similarly to the barrier we added in `__wt_yield`).
Feel free to discard this branch without further discussion if you don't want it. I incrementally made these changes while convincing myself things were correct, and most of the changes involve fixing comments or other similar cleanups.
@sueloverso, I've included the logging change we discussed.
=> WT-3292 review/cleanup full-barrier calls in WiredTiger

src/include/connection.h, src/txn/txn_log.c, src/txn/txn_recover.c, test/recovery/random-abort.c, test/suite/test_txn02.py, test/suite/test_txn05.py
Revert test changes that needed a checkpoint for archiving.
@agorrod This is ready for review.
=> WT-3263 Allow recovery log file archiving on clean shutdown.

src/conn/conn_cache_pool.c, src/evict/evict_lru.c, src/include/cache.h
@agorrod Here's the branch for your review.  All the tests are still running.  This is ready to merge after they have run for another day or two.  But you can see the changes now.
I decided to split the flags into a separate field rather than use the {{flags_atomic}} macros for this fix.  The cache pool flags are rarely used/modified and I didn't want to impose atomic operations on every eviction use of the flags.
=> WT-3282 Split cache flags and cache_pool flags.

src/btree/row_key.c, src/os_common/os_alloc.c, src/os_posix/os_dir.c, src/session/session_api.c
Quiet the four remaining clang-analyzer complaints.
=> WT-3219 Make the clang-analyzer job fail when lint is introduced

src/session/session_api.c
False positive, but explicitly checking the stop variable should make the complaint go away.
=> WT-3300 Coverity 1374542: Dereference after null check

src/log/log.c
@agorrod Please review this change.  It adds a few error messages for some paths in `log_scan` to know why we got `WT_NOTFOUND` including the path in the ticket.
=> SERVER-28820 Add a few error path messages.

lang/java/wiredtiger.i, lang/python/wiredtiger.i, src/include/wiredtiger.in, test/suite/test_cursor12.py
@keithbostic, this should support Python (there's a little bit more I might do there), and I ignored the new interfaces in Java in this commit.  Will work on Java next.
=> WT-2972 Make partial updates more efficient - Python support

dist/s_style, src/include/btmem.h
We use a pragma on Windows to force a struct to be packed, but were
missing the "end" pragma that restores normal layout.  The result was
that most structs were being packed, leading to poor performance for
workloads (particularly when accessing session structures).
=> WT-3158 Fix structure layout on Windows.

dist/s_string.ok, src/evict/evict_lru.c, src/include/btree.h
Don't acquire the eviction walk-lock when releasing exclusive eviction access to a file, it can deadlock. Instead, atomically decrement the counter.
=> WT-3303 Deadlock during first access to lookaside table

dist/stat_data.py, src/include/misc.i, src/include/session.h, src/include/stat.h, src/include/wiredtiger.in, src/os_posix/os_time.c, src/os_win/os_time.c, src/support/stat.c
@agorrod and @michaelcahill here's a version of fixing the time problems in `wt_epoch` instead of in `WT_TIMEDIFF`.  @keithbostic you might want to look at it too.  I prefer this version over the one I created yesterday in `WT_TIMEDIFF` for a few reasons:
* It allows us to add in a statistic easily to detect and record this situation.
* It is equally as compact and localized for backporting.
* It deals with it at the source rather than in the use of timestamps.
By keeping it in the session, users of `wt_epoch` with a NULL session do not get the benefit of this change but that is only `wtperf` and other local test programs so I'm okay with that.
=> WT-3327 Check for backward time in wt_epoch

lang/python/wiredtiger.i, test/suite/test_cursor12.py
To transmit the length of the WT_MODIFY array from the typemap to the call site in SWIG, we put the length into an (otherwise unused) first element.  Changed from using a blank entry as a sentinel, as a blank can legally appear in an list of Modify elements.
=> WT-2972 partial updates: fix Python to allow a no-op modify.

src/os_posix/os_time.c, src/os_win/os_time.c
@agorrod Here's a fix for the LSM failure seen over the weekend.  The new clock check was reading the location passed in by the caller and that was getting set/reset out from under it.  I now read the time into a local variable to do all of the new time checks.
It seems that it could be dangerous to have timestamps being freely overwritten and its possible we could get parts of two timestamps set into a field.  My new checks, reading the same location over and over, was seeing different values each time and was storing a value into the session that was not one it read.
=> WT-3331 Get time into a local variable so we can read and use a consistent time

test/suite/wtdataset.py
The static test suite's BaseDataSet class has 'u' value format bugs, should return a string, not an integer.
=> WT-3334 static test suite's BaseDataSet class has 'u' value format bugs

src/cursor/cur_ds.c, src/cursor/cur_file.c, src/cursor/cur_table.c, src/include/api.h, src/lsm/lsm_cursor.c
Split CURSOR_UPDATE_API_CALL into two versions, one of which expects a btree handle, one of which doesn't.
=> WT-3339 The CURSOR_UPDATE_API_CALL macro will dump core on a NULL btree handle

src/btree/row_modify.c, src/lsm/lsm_tree.c, src/lsm/lsm_work_unit.c, src/support/mtx_rw.c
* two cases where error checking for rwlocks should goto the error label for cleanup.
* LSM code not restoring isolation if a checkpoint fails part way through
=> WT-3354 Fix bugs found by Coverity.

SConstruct, bench/wtperf/idle_table_cycle.c, bench/wtperf/wtperf.c, bench/wtperf/wtperf.h, examples/c/ex_thread.c, src/include/extern_posix.h, src/os_posix/os_thread.c, src/support/err.c, test/checkpoint/checkpointer.c, test/checkpoint/test_checkpoint.c, test/checkpoint/test_checkpoint.h, test/checkpoint/workers.c, test/cursor_order/cursor_order.c, test/cursor_order/cursor_order.h, test/cursor_order/cursor_order_ops.c, test/fops/fops.c, test/fops/t.c, test/fops/thread.h, test/format/backup.c, test/format/compact.c, test/format/format.h, test/format/lrt.c, test/format/ops.c, test/format/util.c, test/recovery/random-abort.c, test/thread/rw.c, test/thread/t.c, test/thread/thread.h, test/windows/windows_shim.c
@markbenvenuto, there's only a minor change to the WiredTiger library itself, the rest is boilerplate to deal with test program portability.
@michaelcahill, with these changes, Windows builds without warnings.
=> WT-3361 Resolve Windows build warnings, build more test programs on Windows

src/conn/conn_dhandle.c, src/session/session_dhandle.c
Testing has uncovered another case where drops can spin trying to lock a checkpoint handle until a checkpoint completes.  This change fixes that in two ways: attempting to lock (but not open) a handle won't spin, and drop will always attempt to lock the live tree before locking any checkpoint handles.
=> WT-3362 Checkpoints shouldn't block drops.

src/meta/meta_table.c, src/meta/meta_turtle.c
I believe the problem was that MongoDB reads the metadata file, and that potentially races with checkpoints. I never caught it in the act, but it fits all the symptoms.
=> SERVER-29439 WiredTiger turtle file "MoveFileExW: Access is denied." error.

test/mciproject.yml
Evergreen is moving all OSX machines from 10.10 to 10.12 to support XCode 8.
I updated wiredtiger to use 10.12 but ran into issues with DYLD_LIBRARY_PATH that I needed to use `install_name_tool` to workaround.
=> WT-3367 Move to macOS 10.12

src/txn/txn_recover.c
@michaelcahill Please review this fix.  I considered getting rid of `metafile` and just using the array each time, but chose to just reset it as well as clear it out when we're done so future code that might use the variable later needs to pay attention.
=> WT-3370 Reset metafile after it could be re-allocated.

SConstruct
The exception is the SWIG-generated Python wrapper code.
I removed the `/weXXX` lines as well, they're all covered by `/W3` and `/WX`.
=> WT-3371 Make Windows/MSVC build warnings fatal.

src/evict/evict_page.c, src/reconcile/rec_write.c
@michaelcahill, I wrote up what I think is going on, and ordered the tests to try and group tests with the same purpose together.
Feel free to discard this -- it's really, really wordy. (But, on the other hand, I think I really understand it now.)
=> WT-3379 Avoid a performance regression on secondaries.

src/log/log.c
@keithbostic Please review this change.  It should fix the zseries failures from my merge.
=> WT-3039 Swap checksum if needed before comparing.

test/suite/test_compat01.py, test/suite/test_reconfig02.py, test/suite/test_txn02.py, test/suite/test_txn05.py, test/suite/test_txn11.py, test/suite/test_txn16.py
This accounts for case insensitivity.
@keithbostic Please review.  The new `test_compat01.py` is the first test to need to know how many log files there were and *Log* is case insensitive on Windows and was also grabbing the pre-allocated log files causing the test to fail on Windows.
=> WT-3039 Add uniqueness to python list of log files.

src/cursor/cur_backup.c, src/include/extern.h, src/lsm/lsm_cursor.c, src/session/session_api.c, src/session/session_compact.c, src/support/err.c
@sueloverso, I changed in-memory configurations to ignore `WT_SESSION.rebalance`.
I suspect you'll need to do the same thing for `WT_SESSION.alter` in WT-3310 branch. I don't see a simple alternative, and absent a reason to make a `__wt_schema_worker` based operation work in-memory, I'm inclined to leave it alone.
=> WT-3398 in-memory configurations don't support schema_worker operations

src/support/generation.c
Panic if we self-deadlock in the generation code.
=> WT-3409 WiredTiger generations can silently self-deadlock.

src/log/log.c
self-review - the panic message code was incorrectly removed sometime during WT-3039.  Restore it.
=> WT-3403 Restore panic if writing a log record fails.

test/format/compact.c, test/format/util.c
@keithbostic Please take a look at this.  This fixes the several test/format failures when alter, LSM and compact are configured.  In that case, it is normal that EBUSY could be returned and test/format should not die in that case.
=> WT-3310 Fix test/format to tolerate EBUSY with LSM.

examples/c/ex_backup.c, examples/c/ex_encrypt.c, examples/c/ex_log.c, examples/c/ex_sync.c
Printing out an "int" takes 20 characters.
=> WT-3424 additional gcc 7.1 compile warnings.

src/include/extern.h, src/include/txn.h, src/txn/txn.c, src/txn/txn_ckpt.c, src/txn/txn_timestamp.c
Removes timestamps from `WT_TXN_STATE` as a step towards merging `WT_TXN_STATE` with `WT_TXN`.
This change has transactions add themselves to global, sorted lists (one ordered by commit timestamp, the other ordered by read timestamp).  Each list has its own rwlock, and scans have been replaced by peeking at the first (oldest) transaction in the list.  The list's lock protects the
relevant fields in `WT_TXN` (i.e., no thread will read `txn->commit_timestamp` unless the transaction is in the `commit_timestamp` list).
This should reduce contention for `txn_global->rwlock`, which can be further decomposed in future (e.g., eliminating the scan for `__wt_txn_update_oldest` and replacing `__wt_txn_get_snapshot` with a loop that makes a copy of running transaction IDs in order).
=> WT-3381 Improve timestamp concurrency.

src/conn/conn_dhandle.c, src/include/dhandle.h, src/include/extern.h, src/lsm/lsm_work_unit.c, src/session/session_api.c, src/session/session_dhandle.c, src/txn/txn_ckpt.c
@sueloverso, for your consideration.
I don't see any reason not to delay setting the `WT_DHANDLE_DEAD` flag until after the block object is discarded, it's a cheap operation.
I don't think this helps with WT-3232 because my reading of that ticket was the cache blocks themselves need to be discarded (although I don't understand why that's the case).
=> WT-3418 Fix a block manager race in tree close/open

build_posix/aclocal/strict.m4, build_posix/configure.ac.in, dist/s_style, src/btree/bt_curnext.c, src/btree/bt_curprev.c, src/btree/bt_debug.c, src/btree/bt_ovfl.c, src/btree/bt_ret.c, src/btree/row_modify.c, src/include/btmem.h, src/include/cursor.i, src/include/misc.h, src/include/verify_build.h, src/include/wt_internal.h, src/reconcile/rec_write.c, src/txn/txn_log.c
@michaelcahill, @sulabhM, here's a different change.
The fundamental change is adding `uint8_t data[3]` at the end of the `WT_UPDATE` structure: that means we can allocate `sizeof(WT_UPDATE)` without wasting bytes and it gives us a field name to use, we can replace `WT_UPDATE_DATA(upd);` with the more natural `upd->data;`
The only downside I see is we potentially waste 3 bytes on `WT_UPDATE` structures with no data package (so, `WT_UPDATE_DELETED`, `WT_UPDATE_RESERVED`, or zero-length values), but because we calculate the memory use of a `WT_UPDATE` structure as aligned to 32B, I don't think there's any actual loss.
Also, I tucked in a separate change in 14d3d0a, which locates the declaration of the `WT_UPDATE` timestamp. If you don't do that, using a non-8B timestamp (for example, …
=> WT-3380 Remove packed attribute from WT_UPDATE.

src/include/txn.h, src/txn/txn.c, src/txn/txn_timestamp.c
Recent changes cleared the `WT_TXN_HAS_TS_READ` flag in the special handling of the checkpoint transaction in `__checkpoint_prepare`.  This change splits the functional flag (HAS_TS_READ) from the flag indicating whether the information has been published by hooking the transaction into a list (PUBLIC_TS_READ).
=> WT-3387 Fix checkpoint support for read_timestamp.

build_posix/configure.ac.in, build_win/wiredtiger_config.h, dist/filelist, src/include/extern.h, src/include/extern_posix.h, src/include/extern_win.h, src/include/misc.i, src/os_posix/os_mtx_cond.c, src/os_posix/os_time.c, src/os_win/os_time.c, src/support/time.c
Regardless, don't adjust the realtime clock before calculating when a timed sleep should end.  Otherwise, we can sleep for longer than expected by however much the clock changed.
=> WT-3461 Use CLOCK_MONOTONIC for pthread_cond_timedwait if possible.

src/include/txn.h, src/txn/txn_timestamp.c
In particular, if a commit_timestamp is set via `WT_SESSION::timestamp_transaction` and again later via `WT_SESSION::commit_transaction`, there was a window where `session->txn.commit_timestamp` was zero, which caused `WT_CONNECTION::query_timestamp` to return incorrect results.
Similarly, the shared list of transactions with commit timestamps should be sorted by the first commit timestamp: we don't (and shouldn't) re-sort that list if a transaction's commit_timestamp is updated.
=> WT-3466 Track the first commit_timestamp set in a transaction.

src/meta/meta_table.c, src/schema/schema_open.c
@agorrod, in short, `__schema_open_table` holds the metadata cursor pinned across a call to `__wt_schema_open_colgroups`, which calls `__wt_metadata_search`, and so is forced to open an additional metadata cursor.
There's a similar case when dropping a table: `__wt_metadata_remove` opens a metadata cursor, and then calls `__wt_meta_track_update` which also opens a metadata cursor, forcing drop to open a second metadata cursor. I'm less comfortable with this change, but I think it's safe.
=> WT-3470 table open/drop always open a metadata cursor

src/cursor/cur_std.c
Instead of using CURSOR_UPDATE_API_CALL/CURSOR_UPDATE_API_END, use CURSOR_API_CALL/API_END_RET, we're not doing an update, we're only calling an update function.
Replace an API_END/return (ret) pair with API_END_RET().
=> WT-3472 WT_CURSOR.modify has incorrect API wrapping macros

src/include/extern.h, src/include/session.h, src/schema/schema_list.c, src/session/session_api.c
During `WT_SESSION::reset`, if there has been a schema change (such as a `WT_SESSION::drop` operation) since the last sweep, do a pass through the table cache and remove any obsolete table handles.
=> WT-3471 Sweep the table cache after schema changes.

dist/api_data.py, src/include/wiredtiger.in, src/txn/txn_ckpt.c, test/suite/test_timestamp03.py
When logging is enabled for a table, that indicates that updates should become durable immediately, since they will be unconditionally rolled forward by recovery after a crash.  Since checkpoints with a timestamp are intended to create a version on disk that does not include newer changes, it doesn't make sense with immediately durable tables.
=> WT-3458 Checkpoint timestamps only apply to non-logged tables.

src/include/cursor.i
Found as a bug in the Helium port.
=> WT-3494 __cursor_needvalue() calls __cursor_localkey(), not __cursor_localvalue()

src/include/txn.h, src/txn/txn.c, src/txn/txn_log.c
@michaelcahill and @agorrod here's a branch that solves the visibility and checkpoint issue that my test uncovered.  Please review.  It solves the problem even with my aggressive sleep repro case.  I am going to point the perf jobs at this branch for the day too.
=> WT-3499 Add a visibility rwlock between transactions and checkpoints.

src/btree/bt_debug.c, src/include/extern.h, src/include/txn.i, src/txn/txn.c, src/txn/txn_timestamp.c
@michaelcahill, there's one minor change here that might be of interest. I changed `__wt_timestamp_to_hex_string()` to return the string "0" in the case of a zero timestamp.
That's potentially interesting if `__wt_txn_global_query_timestamp()` calls that function with a zero timestamp as we'll return "0" instead of the empty string. I think that's a bug fix, if anything (unless we document somewhere that an empty string is the same as a "0" string), but wanted to call it to your attention.
=> WT-3493 wt_verbose_dump_txn should display timestamp information

dist/api_data.py, dist/filelist, src/conn/conn_api.c, src/conn/conn_reconfig.c, src/include/extern.h, src/include/txn.i, src/include/wiredtiger.in, src/txn/txn.c, src/txn/txn_rollback_to_stable.c
Fail upgrade / downgrade if the system isn't quiescent.  Document that applications must wait for an upgrade / downgrade to complete before starting any new operations.  Handle WiredTiger's checkpoint thread carefully: make sure no checkpoint is in progress when the compatibility version changes, and the checkpoint thread is already restarted by reconfigure.
Split out the reconfigure functionality into its own source file.
=> WT-3417 Check for active transactions during upgrade/downgrade.

dist/api_data.py, src/config/config_def.c, src/txn/txn_ckpt.c, test/suite/test_timestamp03.py
Prior to this change, there was a window in between checkpoint reading the stable timestamp and using it to start a transaction.  In that window, the application could update timestamps, making it invalid for checkpoint's transaction to start.
Remove the undocumented "read_timestamp" config to WT_SESSION::checkpoint, and instead copy the stable timestamp directly into checkpoint's transaction while holding the global transaction state locked.
=> WT-3514 Fix checkpoint's use of stable_timestamp.

src/cursor/cur_file.c, src/cursor/cur_table.c, src/include/misc.h, src/schema/schema_create.c, src/schema/schema_drop.c, src/schema/schema_list.c, src/schema/schema_open.c, src/schema/schema_rename.c, src/schema/schema_worker.c
These changes speed up a focused benchmark by 13%.  The benchmark is a single threaded application that does cursor_open in a loop.
=> WT-3516 Optimize schema operations when we are certain of URI prefixes.

test/suite/test_timestamp07.py
@keithbostic Please review this small test change.  I hope it is sufficient.  Instead of checking the stats after segments of the test I only left in the one at the end of the test.  The test is supposed to be testing eviction so the original intent was to make sure eviction happened (or not based on a boolean).
=> WT-3525 Remove eviction stats check.

test/checkpoint/checkpointer.c, test/checkpoint/smoke.sh, test/checkpoint/test_checkpoint.c, test/checkpoint/test_checkpoint.h, test/checkpoint/workers.c
Coverage in test/recovery/timestamp-abort instead.
=> WT-3386 Remove support for timestamps in test/checkpoint.

test/suite/test_reconfig02.py
I can't reproduce this failure, but I do see the test taking over 10 seconds for the pre-allocated log files to appear, so I don't think it's unlikely that periodically some runs take even longer.
=> WT-3541 Python test_reconfig02 timeout on the PPC

test/recovery/random-abort.c
Needed to start debugging the evergreen failure.
=> WT-3540 Add copying of pre-recovery database for debugging.

test/suite/test_stat_log02.py
Still seeing timeout failures on the PPC: rewrite to not use timers at all.
=> WT-3542 Python test_stats_log_on_json_with_tables timeout on the PPC

src/include/connection.h, src/txn/txn_rollback_to_stable.c
This was caused by an off-by-one bug calculating the size of a bitstring, leading to writes past the end of the array when the largest active file ID was a multiple of 8.
=> WT-3544 Fix memory stomping during rollback_to_stable.

test/recovery/random-abort.c, test/recovery/timestamp-abort.c
Tables can be so large that they fill test machine file systems.
=> WT-3540 For debugging only copy log files.

src/conn/conn_log.c, src/cursor/cur_log.c, src/include/connection.h
@agorrod Please review this.  It avoids the ftruncate if there are log cursors open.  Other than test programs log cursors are very rarely used so I don't think it has much user-visible impact.
=> WT-3495 Don't ftruncate if log cursors are open

src/txn/txn_ckpt.c
It is better to return a WT_ROLLBACK so the checkpoint can be retried.
=> WT-3558 Disable metadata visibility assertion in checkpoints

dist/s_string.ok, src/include/lsm.h, src/lsm/lsm_manager.c, src/lsm/lsm_work_unit.c
@agorrod Please review.  I implemented a form of @michaelcahill 's suggestions.  I have an atomic work unit counter and only the server thread looks for idleness and keeps track of how long a tree has been idle.
I've run `make check` and all the `run.py lsm` and `test/format` with `data_source=lsm` for over 100 iterations.  But I do not know for sure whether or not the lsm manager idle settings have kicked in or not.
=> WT-3468 Avoid shared timespec usage in LSM

src/evict/evict_lru.c
Updated the eviction workers tune algorithm to improve the eviction rate
and minimize the impact of re-tuning on the IOs. 
* Remove just one eviction worker forcefully every retune cycle to 
  avoid the situation of less numbers of eviction workers evicting
* Perform retune more frequently i.e. every 25 seconds to increase the 
  dynamism of the parallel eviction workers.
* Reduce the time period of collecting the datapoints to 60ms and
  increase the number of datapoints so that there is sufficient data 
  about eviction rate to settle on a stable number of workers. This also
  minimizes the time spent in retuning.
While at it, remove the restriction of thread[0] doing the retune. Any
of the thread in the eviction worker thread group could be an eviction 
server and can do the retune.
=> WT-3437 Improvements to tuning of number of eviction workers

src/cursor/cur_std.c, src/cursor/cur_table.c, src/include/schema.h, src/include/wiredtiger.in, src/schema/schema_open.c
This change results in a consistent 20% improvement for my focused benchmark that repeatedly calls WT_SESSION->open_cursor/close_cursor in a single thread.
=> WT-3555 Streamline open_cursor for simple tables.

test/bloom/test_bloom.c, test/csuite/random_abort/main.c, test/csuite/timestamp_abort/main.c, test/csuite/truncated_log/main.c, test/cursor_order/cursor_order.c, test/cursor_order/cursor_order_file.c, test/cursor_order/cursor_order_ops.c, test/fops/file.c, test/fops/t.c, test/format/salvage.c, test/huge/huge.c, test/readonly/readonly.c, test/thread/file.c, test/thread/rw.c, test/thread/stats.c, test/thread/t.c, test/utility/misc.c
@bvpvamsikrishna, Sulabh, Sue & I have all been incrementally replacing patterns in the test code that look like this:
```
if ((ret = call(args)) != 0)
testutil_die(ret, message);
```
with:
```
testutil_check(call(args));
```
I started running lint on some test programs that hadn't been linted before, and while I was in the area I did a pass over the test suite to find examples of that pattern and fix them. (I didn't replace them all, specifically, I tried to leave alone any place where the "message" to `testutil_die` actually provided some additional value.)
There are a few bug fixes here as well: places where we reported an error using `errno` paired with calls that don't set `errno`, places where we ignored possible error returns from functions, and places where we set variables that …
=> WT-3589 replace return checks and testutil_die() pairs, with testutil_check().

test/format/config.h, test/format/format.h, test/format/ops.c
While looking at one of the WT-3435/#3644 failures, I realized all of the format threads were pounding on the same key/value pairs. Interestingly enough, if you change that, the failure goes away.
I think we generally want the format threads to work different parts of the RNG space, but clearly we also want to stress the same key/value pairs as well.
=> WT-3603 format threads always traverse the same RNG space.

src/conn/conn_api.c
@michaelcahill or @agorrod Please review this change.  It only addresses fixing the compatibility in the `basecfg` file on database creation.  It does not address whether we should modify the `basecfg` file on a `conn->reconfigure()` call.  Currently the `basecfg` file is static after creation and that change would be a new path to modifying it later, unless we come up with some other solution.
=> WT-3602 Write the compatibility version given into the basecfg file.

lang/python/run-ex_access
Having site dependent directories searched may mean that a shared objects from a previous build may be mistakenly used.
=> WT-3595 When running the python example, remove site-dependent dirs from sys.path

src/docs/lsm.dox, src/lsm/lsm_tree.c, test/csuite/scope/main.c, test/suite/test_cursor12.py, test/suite/test_cursor_compare.py, test/suite/test_lsm04.py, test/suite/test_overwrite.py, test/suite/wtscenario.py
@agorrod, I took a look at WT-3605 (because it was a user question), and here's a branch that I hope makes things better.
It looks to me like LSM doesn't currently support anything other than 'S' or 'u' because the underlying file format is always 'u' (and 'S' is the only other format than  'u' that naturally looks like 'u' when it's stored in a WT_ITEM structure).
That said, it seems LSM could support other formats? (For example, couldn't a record-number be packed and stored in a WT_ITEM as format 'u'?)
I'm also unclear on how this connects to more complex tables schemas, that can presumably be configured to store in LSM tables.
Anyway, I hope this branch is moving in the right direction. Happy to wrap this up if you can give me a little guidance, or happy to have it handed off to …
=> WT-3605 LSM doesn't support type 'r'

test/mciproject.yml
sorry if this PR is unorthodox, MCI (our evergreen deployment) no
longer has solaris support, and it'll make things easier on our end if
we remove this.
=> WT-3618 remove solaris support

src/cursor/cur_file.c, src/txn/txn_ckpt.c, test/fops/file.c, test/fops/t.c, test/fops/thread.h
Checkpoint will skip the tree if it sees more recent version due to contention between checkpoint and DDL operations on that tree.
enhanced fops test as well for detection of this issue with -i option
=> WT-3559 Checkpoint contention with metadata content

src/reconcile/rec_write.c
We can ignore this branch until WT-3435/#3644 is merged, it should be an easy fix-up afterward.
=> WT-3599 reconciliation calculates block matching checksums too frequently.

src/bloom/bloom.c
On error, the bloom cursor is positioned at whatever key it was on from the
search. As a general practice a cursor should be reset after its use. So reset
this cursor after a failed search too.
=> WT-3200 Reset the bloom filter cursor after failed search

test/suite/test_backup07.py
@agorrod Please review this new test.  It was a scenario we didn't test that came out of discussions about backup and schema operations.  The good news is that we pass gracefully and we don't have a bug that would cause recovery to fail.  We already test drop and rename in another test but not explicitly create like this.
=> WT-3621 Add a new test for a full backup followed by a table create.

src/btree/bt_handle.c, src/btree/bt_page.c, src/btree/bt_read.c, src/btree/bt_rebalance.c, src/btree/bt_slvg.c, src/btree/bt_split.c, src/conn/conn_cache.c, src/include/extern.h
@agorrod, @michaelcahill, I did some review today based on talking to Bruce Lucas about HELP-5066, and found a couple of problems in our page-image accounting. I don't believe this would lead to eviction problems, but in the presence of mapped files, I think our statistics for page-image bytes would grow without bound.
=> WT-3636 Account for page image sizes in cache consistently

src/btree/bt_split.c
Reconciliation selects an update as the "on-page" version that is correct as-of the reconciliation.  If that update is a tombstone, no value will appear on the page.  Our API permits a modify of a deleted record, so we can't discard a tombstone if it was chosen as the on-page update, or a later modify update will have no starting value.
=> WT-3638 When restoring updates, don't discard on-page tombstones.

src/btree/bt_cursor.c, src/btree/bt_read.c, src/btree/bt_split.c, src/btree/bt_sync.c, src/conn/conn_cache.c, src/evict/evict_lru.c, src/include/btmem.h, src/include/btree.i, test/suite/test_colgap.py
Previously, checkpoint attempted to push out any page requiring forced eviction.  With this change, pages read into cache by checkpoint are marked with a different read generation, so that checkpoint can distinguish between pages it read (from lookaside) and big / hot pages that happen to be in cache when a checkpoint runs.
=> WT-3646 Don't trigger eviction from checkpoints in write heavy workloads

src/btree/bt_read.c, src/btree/bt_split.c, src/evict/evict_page.c, src/include/btree.i, src/reconcile/rec_write.c, test/suite/test_timestamp07.py
In particular,
* fix the optimization for checkpoints so most lookaside pages can be skipped when the stable timestamp is lagging.
* allow row store leaf pages to split when evicting and no values are visible (currently using a dumb heuristic of splitting as soon as 100 records need updates saved).
* allow use of lookaside and splits when checkpoints do eviction.
=> WT-3646 Improve performance when lookaside eviction is required.

src/btree/bt_read.c, src/btree/bt_split.c, src/conn/conn_ckpt.c, src/evict/evict_page.c, src/include/btree.i, src/include/cache.i, src/reconcile/rec_write.c, src/txn/txn_ckpt.c, test/suite/test_timestamp07.py
We recently changed eviction to try using the lookaside table sooner. For some workloads, this can lead to poor performance and runaway growth in the lookaside table size.
=> WT-3646 Only use lookaside when operations are blocked waiting for cache

src/reconcile/rec_write.c
Previously, we would split pages once reconciliation saw 100 saved updates.  Apart from suffering from the same problems as other naive split approaches (e.g., creating a new page with a single saved update each time a new insert plus eviction happens), the previous approach also doubled the size of the buffer passed to raw compression each time splits were triggered by the saved update count, leading to attempts to allocate unexpectedly large amounts of memory.
=> WT-3657 Use saved update size for splits, don't grow raw buffer.

src/docs/basic-api.dox
That method is no longer available, replaced by WT_CURSOR::reset.
=> WT-3660 WiredTiger documentation refers to WT_CURSOR::first.

test/format/config.c, test/format/config.h, test/format/format.h, test/format/ops.c, test/format/wts.c
@sueloverso, the reason I wanted a review from you is the library checkpoint configuration.
When configuring the library checkpoint thread, I'm waiting between 1 and 20 MB of log file between checkpoints (max 1024MB), and between 5 and 100 seconds (max 3600). Does that sound reasonable to you?
=> WT-3665 change format to configure the WiredTiger checkpoint thread

src/conn/conn_api.c
@michaelcahill Please review this.  There is explanation in the ticket as well.  Basically on the error path out of wiredtiger_open, we were checkpointing the metadata file, updating the checkpoint LSN causing us to ignore and never recover the data.  This is one approach, because having panic set means we discard the dhandle.  Given it is the error path of `wiredtiger_open` it seemed cleaner than drilling more special case connection checking down into the dhandle code.
=> WT-3643 Set panic on error path if recovery needed.

src/include/extern.h, src/txn/txn.c, src/txn/txn_timestamp.c, test/format/ops.c, test/format/util.c
FTR, I can't reproduce this one, but I think there is a way format can race.
=> WT-3672 Test format failure with commit timestamp older than oldest timestamp

src/async/async_api.c, src/async/async_worker.c, src/block/block_ckpt.c, src/block/block_open.c, src/btree/bt_compact.c, src/btree/bt_discard.c, src/btree/bt_page.c, src/btree/bt_read.c, src/btree/bt_vrfy.c, src/btree/row_srch.c, src/config/config.c, src/config/config_api.c, src/conn/conn_cache.c, src/conn/conn_cache_pool.c, src/conn/conn_sweep.c, src/cursor/cur_join.c, src/evict/evict_lru.c, src/include/btmem.h, src/include/btree.i, src/include/cache.h, src/include/cache.i, src/include/connection.h, src/include/serial.i, src/include/txn.i, src/log/log.c, src/log/log_slot.c, src/lsm/lsm_manager.c, src/lsm/lsm_work_unit.c, src/lsm/lsm_worker.c, src/os_posix/os_dir.c
@agorrod, there are two changes here.
48cc54c sets a flag when a page is read on behalf of checkpoint, and then doesn't count evicting that page towards eviction progress. I am hesitant to not count "normal" eviction of metadata or lookaside pages towards eviction progress, it's not impossible that those pages could consume a reasonable piece of the cache and evicting them could be progress. So instead, I don't count the eviction of pages read on behalf of a checkpoint as eviction progress. (To be clear, I'm not excited about this approach, and it's a special case I'd rather not have, I just couldn't think of anything I liked better.)
4d8c187 restructures `__evict_server()` to remove the `WT_CACHE.pages_evicted` field.  In summary, I think `WT_CACHE.pages_evicted` can be more replaced …
=> WT-3616 format failed to report a stuck cache

src/log/log.c
@michaelcahill Please review this change.  The real fix is checking if `rd_lsn` is less than the `trunc_lsn`.  I also fixed verbose messages.
=> WT-3681 Only truncate a log if we're less than the trunc_lsn.

src/meta/meta_track.c
Alex, I don't know what happened in BF-6928, but my guess is an operation did a checkpoint and then subsequently failed, and we don't clean up checkpoints when unrolling tracked operations.
I've added code to do that, and I've also added code to panic if we fail to successfully either apply or unroll any set of tracked operations.
=> WT-3680 metadata unroll should discard in-process checkpoints

test/csuite/timestamp_abort/main.c
@keithbostic Please review this change to `timestamp_abort` to install a signal handler.
=> WT-3707 Install signal handler to detect child unexpectedly failing.

test/csuite/timestamp_abort/main.c
@michaelcahill Here's a fix that makes the output from timestamp_abort more concise and readable.
=> WT-3713 Make error output more concise.  Some refactoring.

src/cursor/cur_std.c, src/cursor/cur_table.c, src/include/schema.h, src/include/wiredtiger.in, src/schema/schema_open.c
Reverts "WT-3555 Streamline open_cursor for simple tables. (#3637)"
This reverts commit 982121f68b336eb58edfbae26300ef46935277b8.
=> WT-3730 For simple tables, do not use table dhandle after it is released.

src/btree/bt_split.c
When a page split is in progress it is possible to get another split on this
page through its child in another thread. Acquire a page lock on the page
undergoing the split to prevent concurrent split on same page.
=> WT-3710 Get page-level lock to ensure single threaded page-split

test/csuite/timestamp_abort/main.c, test/format/util.c
@agorrod Please review.  This should fix the failure seen in `timestamp_abort` and fixes the similar usage in `test/format`.
=> WT-3648 Read the thread's timestamp information once.

src/lsm/lsm_tree.c
@agorrod Here are fixes for the LSM issue where an update sees an LSM cursor with read-only settings.  There really are three different but related fixes in here.  Please review this.  The fixes are:
1.  In `wt_lsm_compact` we should hold the `lsm_tree` writelock until after we set the `WT_LSM_TREE_COMPACTING` flag. There could be a race with another compact and the existing code could end up with two threads in compact.
2. The LSM alter code should do a full discard on the tree.  The code that was there was a "mostly discard" and that wasn't clean and left things in a weird state.  I modified that to discard to force a tree open after an alter.  The alter was forcing the tree to be fully flushed to disk.
3. The LSM compact code should only push a flush work unit if the primary chunk …
=> WT-3444 Don't try to flush LSM if already in compact.

src/log/log.c
@agorrod please review this small change.  With this 1 msec sleep it eliminates nearly all extraneous calls to `log_force_write`.  The tests I have run show no impact on performance and in MongoDB there is an independent thread calling log flush.
=> WT-3746 Add sleep if we need to wait for writes to complete.

dist/stat_data.py, src/btree/bt_compact.c, src/btree/bt_curnext.c, src/btree/bt_curprev.c, src/btree/bt_read.c, src/btree/bt_split.c, src/cache/cache_las.c, src/conn/conn_cache.c, src/conn/conn_cache_pool.c, src/evict/evict_lru.c, src/evict/evict_page.c, src/include/btmem.h, src/include/btree.i, src/include/cache.h, src/include/cache.i, src/include/cursor.i, src/include/extern.h, src/include/stat.h, src/include/txn.i, src/include/wiredtiger.in, src/reconcile/rec_write.c, src/support/stat.c, src/txn/txn.c
There are several behavior changes here to avoid situations where oplog
reads can block when a primary is under severe cache update pressure.
In particular:
* don't block if a scan encounters a large page;
* don't stall reads when the dirty limit of cache is reached;
* mark pages read from lookaside clean if it is safe to do so.
=> WT-3745 Favor oplog reads when under cache pressure.

src/btree/row_modify.c
Obsolete update discards look for a contiguous block of obsolete updates at the end of an update chain.  Previously, we reset the search each time we saw a modify update.  That is not what we want: it is fine to discard obsolete modify updates as long as there is a complete value somewhere after them in the list.
=> WT-3752 Allow trimming of obsolete modify updates.

src/reconcile/rec_write.c
In particular, when reconciling insert lists on row store leaf pages, we also need to check for splits.  Now that we are handling this case correctly, we are seeing splits with empty page images, which requires further changes in reconciliation to track the last key associated with a page (even if that key wasn't written to the page image).
=> WT-3751 Allow splits when no data is visible.

src/include/btmem.h
To turn on snappy by default for LAS.
This improves the performance of insert-heavy workloads that end up disk-bound writing lookaside records.
=> WT-3758 Turn on snappy by default for LAS

dist/s_string.ok, src/docs/schema.dox, src/include/misc.i, src/include/packing.i
When the format 'S' is preceded by a size, that indicates the maximum number of
bytes the string can store. This does not include the terminating NULL byte.
Hence strlen cannot be used to determine the length of the string. Instead use
custom version of strnlen.
=> WT-3658 Fix the string length calculation when size is given

src/include/btree.i
Queue the page for urgent eviction when application thread is not supposed to do
it. This is done to allow splitting the pages to maintain the performance of
write operations.
=> WT-3761 Queue page for urgent eviction on page release

src/include/btree.i
It is an optimization that tickles a corner case with checkpoints and the fast truncate path.
=> WT-3761 Don't immediately evict pages even if they look clean

src/btree/bt_split.c, src/include/btmem.h, src/include/btree.i, src/reconcile/rec_write.c
Rather than on whether transaction visibility is moving forward, this should help since transaction visibility isn't as simple as it was before timestamps.
=> WT-3763 Decide whether to retry eviction based on eviction activity

src/btree/bt_read.c, src/evict/evict_lru.c, src/include/btree.i
When we're not under cache pressure, retrying eviction of pages can waste effort if the global transaction state hasn't changed.  However, lookaside eviction allows pages to be evicted even when a timestamp or transaction ID is stuck, so we should retry in that case.
=> WT-3763 Retry eviction if we're using lookaside.

src/btree/bt_read.c, src/btree/bt_split.c, src/cache/cache_las.c, src/evict/evict_lru.c, src/evict/evict_page.c, src/include/btmem.h, src/include/btree.i, src/reconcile/rec_write.c
In particular, balance primary inserts, overflowing the cache to use the lookaside table, secondary inserts and secondary reads of the oplog (assuming the oplog is at least partially stored in the lookaside table).
=> WT-3763 Tune eviction for various MongoDB workloads.

src/btree/bt_read.c, src/btree/bt_ret.c, src/cache/cache_las.c, src/include/btmem.h, src/include/extern.h, src/reconcile/rec_write.c
Previously, when evicting a page with modify updates, some of the modifications could be skipped when calculating the complete value to write to the new page.  This could lead to updates being lost.
=> WT-3773 Fix a bug calculating on-disk images for modify updates.

SConstruct
SConstruct update to support building wiredtiger_java.dll.
-> wiredtiger.jar is created inside lang/java/**wiredtiger.jar**
-> **wiredtiger_java.dll** is created in root repo folder.
Usage example from cmd:
c:\Python27\python.exe c:\Python27\Scripts\scons.py --enable-java=c:/Users/paco/Downloads/swigwin-3.0.12/swig.exe,"C:/Program Files/Java/jdk1.8.0_151/"
=> WT-3753 Building on Windows --enable-java

src/conn/conn_dhandle.c, src/evict/evict_lru.c, src/include/cache.h
Record how many pages we want and how many pages we have queued so far in a tree, then resume the walk next iteration.  This avoids a single tree with a target larger than the queue size being walked completely before the eviction server moves on to the next tree.
=> WT-3079 Resume eviction walks per tree.

dist/s_style, src/cache/cache_las.c, src/include/btree.i, test/csuite/timestamp_abort/main.c
@michaelcahill, can you please look at dfd2c6f?
I think we're setting `las_session->txn.isolation = WT_ISO_SNAPSHOT`, because `WT_TXN_ISO_READ_UNCOMMITTED` == 2.
=> WT-3783 Fix transaction isolation to use the correct enum

dist/s_string.ok, src/btree/bt_debug.c
Change page debug dump functions for integer keys so we see:
```
0x801c518d0: row-store leaf
disk 0x807480000, dsk_mem_size 1066, entries 99, clean, memory_size 1938, disk-alloc
K {1}
V {VALUE-H}
```
instead of:
```
0x801c518d0: row-store leaf
disk 0x807480000, dsk_mem_size 1066, entries 99, clean, memory_size 1938, disk-alloc
K {#81}
V {VALUE-H}
```
=> WT-3793 WiredTiger page debug dump functions should unpack integer keys

test/suite/test_compact02.py, test/suite/wttest.py
@ddanderson, is there a way to change this code to only ignore failure in the case of `EBUSY`, rather than ignoring all errors?
=> WT-3787 test_compact02 failed as compaction halted due to eviction pressure

src/btree/bt_curnext.c, src/btree/bt_debug.c, src/include/extern.h, src/support/scratch.c
@michaelcahill, @bvpvamsikrishna suggested a couple of weeks ago we should crack complex key/value pairs when dumping pages for debugging, and it's a good idea. I ended up implementing it when I was working on WT-3768, it made it a lot easier to figure out what the lookaside table was doing.
First, I ended up using the streaming pack/unpack APIs, is there anything that would be simpler?
Second, it mostly works, but there's a problem with zero-length `u` formats. I'm  using the pack stream APIs you added, and there's some magic around zero-length `U/u` formats that I don't understand.
The lookaside `__wt_las_insert_block()` code has no problem inserting zero-length items, and obviously we can subsequently read them, but when I try and call `wiredtiger_unpack_item()` on the "QuBu" format it …
=> WT-3812 debugging page output should handle complex key/value items.

test/csuite/wt2834_join_bloom_fix/main.c, test/csuite/wt2853_perf/main.c
I created this branch against the fix in the WT-3800 branch for debugging the hang and having artifacts after a failure.
=> WT-3800 Add debugging to retain database directories.

src/btree/bt_io.c, src/btree/bt_read.c, src/btree/bt_sync.c, src/conn/conn_api.c, src/conn/conn_log.c, src/cursor/cur_file.c, src/evict/evict_lru.c, src/evict/evict_page.c, src/include/connection.h, src/include/extern.h, src/include/misc.i, src/include/mutex.i, src/include/os.h, src/include/os_fhandle.i, src/include/wt_internal.h, src/log/log.c, src/log/log_slot.c, src/session/session_api.c, src/support/global.c, src/support/mtx_rw.c, src/support/time.c, src/txn/txn_ckpt.c
@keithbostic and @agorrod here's a change that moves the tsc calibration into the `__wt_process` global instead of the connection.
=> WT-3824 Move tick calibration early - into global process structure.

test/suite/test_compact02.py
Increase the retry time to a minute, 10 seconds wasn't enough.
=> WT-3827 test_compact02 failure

test/csuite/random_abort/main.c
@keithbostic Please review this defensive change for the file system issue. Interestingly enough, `timestamp-abort` already had a similar change in it for when `ret == 0`.
=> WT-3826 Consider anything other than fscanf success to be EOF.

src/txn/txn.c, src/txn/txn_timestamp.c, test/suite/test_timestamp09.py
1. txn_global->rwlock was not acquired as access of txn_global->oldest_timestamp & txn_global->stable_timestamp is for printing in error msg purpose only.
=> WT-3775 Improve set timestamp error message

test/format/config.h
@keithbostic This is a simplistic fix for the bug that a generated CONFIG gives an error when reused. You added the `cache_minimum` setting. I'm happy to close this branch if you have a better informed solution.
=> WT-3833 Allow 0 as cache minimum.

src/conn/conn_stat.c
@sueloverso,  here's the valgrind failure: http://build.wiredtiger.com:8080/job/wiredtiger-valgrind/2664/valgrindResult/pid=34127,0x0/
=> WT-3831 uninitialized buffer value in statlog server path comparison

src/txn/txn.c, test/suite/test_timestamp10.py
Rather than gating it unconditionally on HAVE_DIAGNOSTIC, the condition
won't flag an error to the application, but can generate a log message,
which should be seen in the MongoDB log if verbose=timestamp is enabled.
=> WT-3597 Change WT_UPDATE ordering check to be part of verbose timestamp.

bench/wtperf/runners/evict-fairness.wtperf
Added a new file to wtperf/runners, to test the eviction fairness in walking active trees.
Automation will be done in jenkins, which will use this configuration for test.
=> WT-3074 Automate a test to stress eviction walk

src/reconcile/rec_write.c
Remove invalid diagnostic assertion.
=> WT-3862 invalid diagnostic assertion during checkpoint reconciliation

src/btree/bt_walk.c, src/support/hazard.c
WT_REF.state is a volatile, avoid pounding on memory in the heavily-used tree-walk and hazard pointer functions.
@michaelcahill, feel free to discard this branch without further discussion if you don't think it's worth doing. (I made a note to myself based on some debugging in WT-3767 to review if WT_REF.state should really be declared non-volatile -- after reviewing that today, I think it's better being volatile, but we are forcing a bunch of cache misses in some heavily-used code.)
=> WT-3865 avoid cache misses in WiredTiger tree-walk and hazard functions

test/format/format.h, test/format/ops.c, test/format/util.c
@michaelcahill, in thinking about the upcoming work in WT-3766 and WT-3805, I thought it would be useful to explicitly read from a timestamp and verify we're seeing the record we expect to see.
=> WT-3871 format should read from a timestamp

src/txn/txn.c, test/suite/test_assert04.py
@agorrod and @dgottlieb here's a PR that solves an issue Dan saw over the weekend when the commit timestamp is set in the middle or the end of the transaction, the new validate code was comparing against updates from earlier in the transaction. I modified the validation to skip updates from its own transaction. The code does not set the timestamp in the update structures until much later in the commit process, long past the time where we're allowed to error. So we need to skip them.
=> WT-3881 Skip validating update structures from this txn.

src/btree/bt_cursor.c, src/btree/bt_read.c, src/lsm/lsm_cursor.c, test/format/bdb.c, test/format/format.h, test/format/lrt.c, test/format/ops.c
@agorrod, @michaelcahill, the changes in this branch (so far) are only changes to `format` to validate that cursor next/prev always returns keys in order after an operation that positions the cursor. With these testing changes, the configurations associated with WT-3766 testing will fail.
=> WT-3878 Iteration can lose its position when updating a limbo page

src/block/block_ckpt.c, src/block/block_mgr.c, src/block/block_read.c, src/btree/bt_io.c, src/include/block.h, src/include/extern.h, src/support/err.c
@agorrod, I ended up increasing the stack buffer size from 2KB to 4KB, and I added an error complaint, if we truncate a message we should notice it.
=> WT-3840 Dump more information on data corruption in diagnostic mode
