src/cache/cache_las.c
src/txn/txn_rollback_to_stable.c

@michaelcahill my run hit a place where I needed to also use the sweepwalk rwlock. @agorrod I also added it to the rollback to stable code. While in there, I noticed that the entry count is not being updated after the removal like it is in all the other remove loops. I fixed that. Please let me know if my change is not correct.

WT-3891 A couple more places needing the sweep walk rwlock.

---

src/include/extern.h
src/include/optrack.h
src/optrack/optrack.c
src/session/session_api.c
tools/optrack/wt_optrack_decode.py

Flushing the operation tracking memory buffer to the file works as follows:
1. We remember the old value of the file offset.
2. We flush the buffer, opening the file if it has not been open yet.
3. We add the return value to the remembered offset.
The problem occurs in the situation when we flush to a file that has not been open yet. Here is what happens:
1. We remember the old value. It is 0, because the file has not been opened yet.
2. As we flush the buffer, the file is opened. BUT: opening the file writes some metadata to it and advances the offset to 12. We flush the buffer at offset 12. We return the number of bytes flushed.
Upon return we should add the number of bytes flushed to 12, the previous offset, but:
3. We add the returned value (number of bytes flushed) to the remembered …

WT-3901 Fixed the log corruption bug.

---

dist/api_data.py
src/config/config_def.c
src/include/extern.h
src/include/txn.h
src/include/wiredtiger.in
src/meta/meta_ckpt.c
src/txn/txn.c
src/txn/txn_ckpt.c
src/txn/txn_recover.c
src/txn/txn_timestamp.c
test/csuite/timestamp_abort/main.c
test/suite/test_timestamp09.py
test/suite/test_timestamp10.py

@michaelcahill Here are the changes to store the timestamp that checkpoint is using in the metadata. @agorrod for your review also. And @dgottlieb mostly FYI for API usage. Some considerations:
1. I write a `checkpoint_stable` record into the metadata. This is written for all file records, not just the record in the turtle file.  The record in the turtle file is the only one used to store the timestamp on restart.  I did this for a couple reasons:
- It allows us to see timestamps in other metadata records in a `wt list -v` that may give helpful information in debugging.
- It allows us to extend querying the recovery timestamp in the future to an individual table if we ever wanted.
2. I named it `query_timestamp("get=recovery")`.
3. One benefit of this is that it allowed me to use it in …

WT-3905 Save the checkpoint timestamp in metadata. Use it in tests.

---

src/conn/conn_log.c
src/evict/evict_lru.c
src/include/os.h

@agorrod Here is the small change to allow the log server thread to retry on a permission error. We record a message and retry up to 10 times. We reset if it soon succeeds and it if doesn't we will eventually panic. Please review.

WT-3904 Allow log server thread to retry on permission error.

---

src/cursor/cur_join.c
src/cursor/cur_std.c
src/cursor/cur_table.c
src/include/extern.h
src/session/session_api.c
src/txn/txn.c

@agorrod, I noticed some functions were calling `__wt_txn_context_prepare_check()` explicitly (probably because they didn't call `API_XXX` macros?).
Anyway, that won't work because `__wt_txn_context_prepare_check()` uses `WT_SESSION.name`.
I added `API_XXX` macros in a few places, I don't see any reason that's not safe.

WT-3923 __wt_txn_context_prepare_check() requires API initialization

---

src/conn/conn_open.c
src/include/session.h
src/session/session_api.c

In 043f61e, we embedded hash tables for cursors and data handles directly in the WT_SESSION_IMPL structure.  That is problematic because we allocate all configured session handles in a single block of memory on startup, and the hash tables grew the structre from just over 1KB to ~18KB.

WT-3932 Move hash tables out of session handles.

---

dist/api_data.py
src/config/config_def.c
src/include/extern.h
src/include/wiredtiger.in
src/txn/txn.c
src/txn/txn_timestamp.c

Decoupling these means setting a read_timestamp will not be blocked due to a full cache, so is reasonable to do while holding an application lock (which may be necessary to allocate a valid timestamp).

WT-3926 Allow read_timestamp to be set after begin_transaction.

---

src/btree/bt_delete.c
src/include/btree.i
src/include/extern.h
src/include/txn.i
src/txn/txn.c
src/txn/txn_rollback_to_stable.c

@michaelcahill, setting `WT_REF.page_del.txnid` to `WT_TXN_ABORTED` allows the page to be evicted and the `WT_REF.page_del` structure to be discarded.
So, making that change before marking the updates are aborted means we can drop core accessing the updates, making the change after we swap in the WT_REF's previous state means we can drop core getting to the `WT_REF.page_del.txnid` field.

WT-3933 test/format failure illegal WT_REF.state rolling back deleted page

---

test/suite/test_txn14.py

Increase the timeout to 30 seconds, it's been periodically failing on the PPC at 10 seconds.

WT-3939 test_txn14.test_txn14.test_log_flush timeout

---

src/cursor/cur_file.c
src/cursor/cur_std.c
src/include/wiredtiger.in
src/session/session_api.c
test/suite/test_cursor13.py

Enabling this exposed a bug which is also fixed: cursors with owners should not be eligible for caching.
Modified cursor cache test to expect caching by default, and removed
some scenarios that use complex datasets, they won't work.

WT-3935 WT-3919 Enable cursor caching by default, add additional tests

---

dist/s_export

Hi @keithbostic, since @michaelcahill mentioned adding support to macOS, so I just enhanced the lib file checking by incorporate all 3 file extensions - .a / .so / .dylib (macOS). If none of the files is found then print the message.

WT-3940 Enhance libwiredtiger file checking in s_export

---

dist/s_export

Hi @keithbostic, it looks libwiredtiger.so has more symbols compared to libwiredtiger.a, and the old check() picked up below 5 symbols from libwiredtiger.so on Linux env, which I believe to be noise (instead of error).
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
unexpected external symbols in the WiredTiger library
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
__bss_start
_edata
_end
_fini
_init
I know the solution is a bit overdosed by excluding "^_", thought it could auto-cover symbols we could potentially add in the future. But do let me know if you have concern so that I will change it by specifying the 5 symbols in the excluding list.

WT-3945 Support libwiredtiger.so checking in s_export

---

src/include/error.h
src/meta/meta_apply.c

Here's a possible way to make this clearer, to invite discussion.  Open question as to whether an EBUSY is even possible. And if it is, is it safe to ignore?

WT-3948 Clarify metadata apply loop, don't exit early on busy errors.

---

test/csuite/timestamp_abort/main.c
test/format/format.h
test/format/ops.c

Here are the changes to test prepare in both `test/format` and `timestamp_abort`. It required some slight gymnastics in `timestamp_abort` because of the assertion in the code that there are no logged records that are part of the transaction when we prepare. It also means we cannot test prepared transactions in `format` unless logging is turned off.
Please review.

WT-3936 Add prepare testing to timestamp_abort and format.

---

test/format/ops.c
test/format/wts.c

@sueloverso, I plan to merge this one once it passes PR testing to get our stress testing back on track.

WT-3953 test/format can attempt to set an illegal prepare timestamp

---

src/btree/bt_delete.c
src/txn/txn.c
test/format/ops.c

@bvpvamsikrishna, @michaelcahill, for your review.
Commit e4d9ad8 changes format so the oldest timestamp doesn't move past the prepared timestamp. That fix seems right to me, and seems to help, but I may not have it right, since it doesn't avoid the problem entirely (or maybe there's just another failure path I haven't found yet).
Commit 694eeed changes `__wt_txn_rollback()` to allow aborted transactions, `__wt_txn_prepare` sets `WT_UPDATE_RESERVE` updates to aborted. With that change, commit fc4b42d changes format to prepare transactions that are then rolled back.
Commit 6eb70e4 changes the prepare and rollback code to assert no updates are being prepared/rolled back from the lookaside file, and ignores all prepare/rollback updates from the metadata file.  I may have been a little too …

WT-3954 prepared operations evicted before commit

---

test/suite/test_compact02.py

@agorrod, I'm pushing a fix for this one so we don't have to keep triaging the failure.
I don't see any evidence there's an underlying bug, it's just taking a very long time for eviction to finish in the small cache case, so I'm increasing the maximum timer from 1 minute to 5.

WT-3942 Update test_compact02 to handle being halted by eviction pressure

---

src/meta/meta_track.c
test/suite/test_metadata_cursor03.py

It causes an issue with recovery after a hard crash.

WT-3964 Stop wrapping schema operations in a transaction

---

src/cursor/cur_file.c
src/cursor/cur_std.c
src/include/cursor.h
src/include/extern.h
src/include/session.h
src/include/wiredtiger.in
src/session/session_api.c

Performance changes include:
- don't sweep for dead cursors too often
- handle a "" config string in open_cursor efficiently.
- cursors with checkpoint specified are not cached.

WT-3815 Performance changes and code simplification

---

src/cursor/cur_std.c
src/session/session_api.c
test/suite/test_cursor13.py

Also updated the long sweep test to correspond to the current sweep algorithm,
which doesn't run as often.

WT-3967 Fix a coding error that was causing cursor sweep not to run.

---

test/csuite/timestamp_abort/main.c

@keithbostic Please review. Now that WT-3958 is merged the test can print out the actual timestamp used in a checkpoint instead of an approximation. Knowing that exact value will help debug the failure.

WT-3977 Print out actual checkpoint stable timestamp in timestamp_abort.

---

src/btree/bt_page.c

@agorrod, this should make future failures of this type more obvious.

WT-3980 failure returning a modified update without a backing "real" update

---

src/btree/bt_delete.c
src/evict/evict_page.c
src/include/btree.i
src/txn/txn.c

@michaelcahill, this is [Zseries failure 41508](http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-zseries/41508/console).
I believe the fix to only read `WT_REF.addr` once is needed, but I've never seen it fail, I noticed it while looking at the core dump.

WT-3987 Avoid reading lookaside pages in truncate fast path.

---

src/btree/bt_cursor.c
src/cache/cache_las.c
test/csuite/timestamp_abort/main.c

At low isolation levels, new records can appear in between positioning a cursor and calling next/prev.  For this reason, search_near cannot assume that after calling next (or prev), it will have a key larger (or smaller) than the search key.  Loop and check in this (rare) case instead.
This applies particularly to internal code that searches in the lookaside table, because that access is always done at read-uncommitted isolation.

WT-3982 Fix transaction visibility bugs related to lookaside usage.

---

src/btree/bt_delete.c
src/btree/bt_read.c
src/evict/evict_page.c
src/include/btmem.h
src/include/btree.i
src/include/txn.i
src/reconcile/rec_write.c

@michaelcahill, @agorrod, for your review.
I split the commits into two parts so we can separately revert them, if I've gone in the wrong direction on page instantiation.
Also, can you think of a reason we didn't see this fail in format stress testing? It seems to me cursors reading from instantiated deleted pages in snapshot isolation should have read the wrong records (because we weren't applying lookaside records in the deleted-page instantiation path). I found the problem by inspection, and I'm worried we're not testing lookaside as well as we should be.

WT-3987 Avoid reading lookaside pages in truncate fast path

---

test/csuite/timestamp_abort/main.c

Timestamp abort needs to increase the allowed number of session handles, if a high thread count were chosen.

WT-3982 Revert a test change that broke in some configurations

---

src/include/txn.i
test/suite/test_las01.py
test/suite/test_las02.py

Makes sure we read the expected data when lookaside eviction is active and data is truncated with a timestamp.  Fixes a bug checking whether truncate operation need the commit timestamp to be applied.  Even with that fix, this test failed before a8fde4b was merged.

WT-3996 Add a test of truncate with timestamps and lookaside.

---

src/txn/txn_timestamp.c

Without this change, reads could miss committed updates with commit_timestamp lower than the read_timestamp if the commit raced with starting the read transaction.

WT-3981 Update transaction snapshot when a read_timestamp is set.

---

src/cursor/cur_std.c
src/include/extern.h
src/session/session_api.c
test/suite/test_cursor13.py

This fixes a cursor cache leak of sorts when dups of the same URI are repeatedly made.

WT-3971 Cursor duplicates use the cursor cache.

---

test/mciproject.yml

In particular, force the use of Python from mongodbtoolchain/v2 and fix up the libwiredtiger.so path in binaries.

WT-3910 Fix evergreen build on macOS.

---

src/btree/bt_delete.c

Revert part of 32793d9: it's not safe to call page-is-modified without first locking the WT_REF, the page can be evicted out from underneath.

WT-4028 page-is-modified check requires the page be locked

---

src/conn/conn_dhandle.c
src/cursor/cur_backup.c
src/include/meta.h
src/meta/meta_ckpt.c
src/txn/txn_ckpt.c
src/txn/txn_recover.c
src/utilities/util_list.c

We added a "system:checkpoint" entry to the metadata to store the most recent timestamp at which a checkpoint completed.  Current versions of WiredTiger treat a missing entry as equivalent to a zero timestamp.
However, this metadata entry can confuse older versions of WiredTiger (specifically, opening a backup cursor fails when the new entry exists). Since MongoDB will always checkpoint without a timestamp as part of the downgrade process, remove the metadata entry in that case so that older versions of WiredTiger never see it.
Also, check for the "system:" previous generally rather than this specific entry.  Then if future versions of WiredTiger introduce new entries, they will be silently skipped when not expected.

WT-3959 Remove metadata entry for checkpoint timestamp if zero.

---

src/reconcile/rec_write.c

Michael, what happened was AddressSanitizer failed in `__wt_delete_page_rollback()`, with a `WT_REF` in the `WT_REF_DELETED` state but `ref.page_del == NULL`, which is a core dump.
The only path I could find where I thought that might happen is `__rec_child_deleted()`, and I was able to make the free of `ref.page_del` assert with a not-yet-globally visible transaction there, with this stack:
```
#3  0x0000000000496ba1 in __wt_assert (session=0x7f62cf8ed498, error=0, 
file_name=0x5b6210 <__func__.16654> "__rec_child_deleted", 
line_number=1691, fmt=0x5b54fa "%s") at src/support/err.c:512
#4  0x000000000046995f in __rec_child_deleted (session=0x7f62cf8ed498, 
r=0x7f6224009b20, ref=0x7f627c0a3ec0, statep=0x7f62617f98bc)
at src/reconcile/rec_write.c:1691
#5  0x0000000000469aaf in …
```

WT-4035 page-delete information discarded before it was globally visible

---

src/config/config.c

Alex, I've been talking with the Coverity folks about getting rid of this false positive -- it's pretty common because we have so many code paths that go through this function. Hopefully this will do the trick!

WT-4036 Coverity tickets: #1129045, #1129046, #1382093 out-of-bounds access

---

src/btree/bt_read.c
src/cache/cache_las.c
src/include/btree.i
src/include/extern.h
src/reconcile/rec_write.c
src/txn/txn_rollback_to_stable.c

We now "pre-allocate" the lookaside entry count by incrementing it by
100 as records are inserted.  At the end, we need to fix up the final
count to match the number that were actually inserted.  That is always a
decrement.
I merged this once and it trigger a stress [test failure](http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress/65747/), so I reverted and re-created the PR based on the original branch.

WT-4012 Fix lookaside entry count.

---

src/btree/bt_debug.c
src/btree/bt_ret.c
src/btree/bt_slvg.c
src/btree/bt_stat.c
src/include/btree.i
src/include/cell.i
src/include/cursor.i
src/reconcile/rec_write.c

@michaelcahill, I like your idea a lot, but the actual mechanics of it make me nervous.
I split this work into a different ticket from WT-4031 (#4049) because we don't need to backport this work to fix the bug, and second, I think we want to pound on this change hard before we let it out into the wild.

WT-4039 Move row-store missing-value support into the cell unpack code.

---

src/docs/transactions.dox

Attaching a screenshot showing the generated documentation.
@sueloverso Would you please review? I could definitely be convinced to move some/all the content into either the timestamps documentation on the same page, or the API doc in wiredtiger.in.

WT-3914 Add general documentation for prepare transaction.

---

src/docs/backup.dox
src/docs/cursor-log.dox

@agorrod Please review these minor changes to the docs to be clearer when log archiving is disabled. This arose from confusion and a slack chat today.

WT-4063 Explicitly state log archiving is disabled. Fix a typo.

---

src/include/lsm.h
src/lsm/lsm_tree.c
test/format/config.c
test/format/format.h
test/format/wts.c

@sueloverso, I'm going to merge this once it passes PR testing to get general testing back on track, but if you'd take a look when you're back next week, I'd really appreciate it.
Thanks!

WT-4051 format configures too-small LSM caches.

---

src/cache/cache_las.c
src/conn/conn_sweep.c
src/include/cache.h
src/include/extern.h
src/txn/txn_rollback_to_stable.c

If there is a race between inserting and removing lookaside records (or some bug where the entry count is not updated correctly), treat underflow the same as a zero entry count (i.e., treat the lookaside table as empty).
At worst, this will leave some data in the lookaside table that could potentially be swept.  It should avoid assertion failures during tests while we search for the source of the underflow.

WT-4064 Relax checking of lookaside entry count.

---

src/btree/bt_split.c

Parent pages are often not marked dirty until after their page-index structures have been replaced, opening up a window for eviction during the split. There's no reason to wait, once the parent is locked, the page split should succeed, mark the page dirty immediately.
(cherry picked from commit 02e7fd4e22395507f799353d74e5bb94057469ff)

WT-4032 parent pages can be evicted while being split. (v3.4 backport)

---

src/btree/bt_split.c

This PR includes backport changes for both WT-3710 and WT-4037.

WT-4037 Fix a bug where WT_REF structures are freed while still in use (v3.4 backport)

---

dist/s_string.ok
src/os_posix/os_fs.c

(cherry picked from commit ae8bccce3d8a8248afa0e4e0cf67674a43dede96)

WT-4045 Don't retry fsync calls after EIO failure. (v3.4 backport)

---

src/reconcile/rec_write.c

This heuristic attempts to ensure that most pages evicted with lookaside history get the versions on-disk that will be chosen by the next checkpoint.  Even if a stable_timestamp is set, under normal circumstances it will be moving forward regularly, so the next checkpoint is likely to choose the most recent committed versions to write to the backing file.
Only skew towards choosing the oldest versions of records if a page is evicted twice without the pinned timestamp moving forward.

WT-4016 Change lookaside skew heuristic.

---

src/log/log.c

@agorrod This is a small change to always verify the logging subsystem, not just when we specify a compatibility required version.

WT-4086 Always verify the logging subsystem.

---

src/session/session_api.c
src/txn/txn.c
src/txn/txn_timestamp.c
test/format/ops.c
test/suite/test_prepare02.py

I made these modifications. @keithbostic please review the reversion (discussed in the ticket) to `test/format` for this. I ran this with the CONFIG from WT-3698 and it has run some iterations.
@michaelcahill or @bvpvamsikrishna please review the code and unit test changes.

WT-4075 Allow timestamp_transaction after prepare.

---

src/log/log_slot.c

…(#4074)" (#4110)
This reverts commit 38f494b08419017e3c7c06fc3b41be9ea7e95a6f which resolved JIRA ticket WT-4058 and adds a comment explaining why the change wasn't correct.
(cherry picked from commit 8bacd49f4c2a2a6a20766471c768aa4c1e8fdeb1)

WT-4077 Revert a change to release logging slot outside of the lock. (v3.6 backport)

---

dist/s_string.ok
src/btree/bt_cursor.c
src/btree/bt_delete.c
src/btree/bt_read.c
src/btree/bt_walk.c
src/include/misc.i

If we backoff too aggressively it makes page splits less effective in some workloads.

WT-4049 Adjust restarted search backoff algorithm.

---

src/evict/evict_page.c
src/include/btree.i
src/reconcile/rec_write.c

Reverts wiredtiger/wiredtiger#4111
The change caused some automated test failures.

Revert "WT-4076 Discard obsolete lookaside history from cache."

---

src/txn/txn_ckpt.c

Checkpoints were first starting a snapshot transaction without a read timestamp, than checking if a stable timestamp was set by the application.  If the stable timestamp was updated after checkpoint
established its snapshot, the checkpoint's transaction was invalid and could skip over records that were committed after the snapshot with timestamps less than the stable timestamp.

WT-4110 Fix a checkpoint timestamp race that skipped recent commits.

---

src/include/btmem.h
test/csuite/wt4105_large_doc_small_upd/main.c

Restored the max modify update value back to 10.
Tune the test to run as short test instead of long test.
print test statements are masked with verbose flag.

WT-4105 restore max modify update value and tune to run as short test.

---

src/conn/conn_ckpt.c
src/txn/txn_ckpt.c

If the stable timestamp doesn't move between checkpoints, their content would be identical.
Also move the similar existing check for clean databases from the checkpoint server into the checkpoint code itself.

WT-4128 Skip creating checkpoints if the stable timestamp allows.

---

dist/s_string.ok
src/os_posix/os_fs.c

Cherry-pick ae8bccc from WT-4045.

BACKPORT-2218 Don't retry fsync calls after EIO failure

---

src/txn/txn_ckpt.c

The variables fullp and use_timestampp are dereferenced before being checked for NULL.

WT-4133 Coverity 1393445, 1393446 Dereference before null check.

---

src/btree/bt_sync.c

We were skipping such updates for clean pages - even though they may contain history that includes the largest transaction ID.

WT-4101 Ensure tracked maximum transaction ID is always updated

---

src/btree/bt_walk.c

Alex, what I think happened here is that in commit [68138e2](https://github.com/wiredtiger/wiredtiger/commit/68138e21d0fe1529d7f65cebd2556699e3fa854b), this code was changed from:
```
/*
* If we got all the way through an internal page and
* all of the child pages were deleted, evict it.
*/
if (empty_internal) {
__wt_page_evict_soon(ref->page);
empty_internal = false;
}
```
to:
```
/*
* If we got all the way through an internal page and
* all of the child pages were deleted, mark it for
* eviction.  If we see enough deleted refs at either
* end, try a reverse split immediately.
*/
if (empty_internal && pindex->entries > 1) {
__wt_page_evict_soon(ref->page);
empty_internal = false;
} else if (delete_count > 0)
WT_ERR(__wt_split_reverse(session, ref));
```
then at some point, the call to …

WT-4140 Cursor walk limits quick eviction page selection unnecessarily.

---

dist/api_data.py
dist/stat_data.py
src/bloom/bloom.c
src/config/config_def.c
src/conn/conn_cache.c
src/evict/evict_lru.c
src/include/api.h
src/include/cache.h
src/include/session.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/format/lrt.c
test/format/ops.c

The option is to wiredtiger_open called cache_max_wait, and applies per operation on a session.
Also:
Fixup error reporting in bloom filter code.
Enhance test/format to work with new timeout code.

WT-4138 Add option to timeout operations waiting for cache.

---

src/include/extern.h
src/include/lsm.h
src/lsm/lsm_cursor.c
src/lsm/lsm_manager.c
src/lsm/lsm_work_unit.c
src/lsm/lsm_worker.c

If the transaction ID or timestamp lags in LSM, it currently causes chunks to be pinned in memory, which can lead to the cache becoming full of un-evictable pages.
The change here looks for such situations and "unpins" chunks in that case - allowing eviction and hopefully progress. This is only useful if applications aren't holding a cursor open on the active chunks (i.e: if there isn't a cursor doing a range scan).

WT-4067 Enhance LSM to allow eviction in chunks pinned by history

---

src/include/txn.i

Otherwise the visibility check will compare to zero - and lead to bad decisions.

WT-4145 Only include the checkpoint timestamp during checkpoints.

---

src/txn/txn_rollback_to_stable.c

@keithbostic Please review. I'll open a new ticket to add in-mem to timestamp testing where I originally reproduced this, but am pushing the code fix now because Dianna is blocked on this failure.

WT-4174 Only rollback lookaside if we're not an in-memory database.

---

src/include/btree.i
src/reconcile/rec_write.c

@michaelcahill Please review this change that modifies some of the changes made in WT-4141 that resulted in a perf drop for the overflow test. These are things I saw eyeballing that diff in #4147 that can affect a timestamp build that is not actually using timestamps. Here are the things to know:
1. The change to `rec_write.c` does NOT impact performance, but it feels like a correct change and avoids calling the function when timestamps are built but not being used.
2. The real change is in `btree.i`. In particular, the pre-WT-4141 code would return `true` in the case that timestamps were not in use. Restoring that via the `else` restores performance in all my local tests.
3. The other change in `btree.i` is a bug in the original code, IMO. The code gets the `pinned_ts` in the line …

WT-4160 Restore performance when timestamps are built but not in use.

---

test/suite/wttest.py

When there is an unexpected content in stderr, python test treats it
as a test failure and displays the content of stderr on console.
This content on console used to be truncated. This change elongates
the stderr content displayed on console to ease failure triage.

WT-3943 Display full error message on python test failure

---

build_win/wiredtiger.def
dist/s_export.list
dist/s_funcs.list
examples/c/ex_all.c
src/checksum/arm64/crc32-arm64.c
src/checksum/power8/crc32_wrapper.c
src/checksum/software/checksum.c
src/checksum/x86/crc32-x86.c
src/checksum/zseries/crc32-s390x.c
src/conn/conn_api.c
src/include/extern.h
src/include/wiredtiger.in
src/support/global.c
test/csuite/wt4117_checksum/main.c

@agorrod, this approach is intended to make it possible to build the checksum functions in a separate library from the WiredTiger library: in short, we don't use any WiredTiger include files or structures.
Returning a pointer to a function is intended to minimize the wrapping required for C++.

WT-4179 Expose WiredTiger crc32c functions

---

src/btree/bt_handle.c

This PR is to allow the btree durability test to work with an in-memory database.

WT-4178 Check for in-memory in btree durability test.

---

src/log/log.c
test/suite/test_txn19.py

A checksum error in a log does not necessarily imply corruption. Any log entry that was only partially written will result in a checksum mismatch.  This change reverts a selected portion of the change for WT-3270 that basically marked the end of the log to be recovered unconditionally as soon as a checksum error happened.
Certain test scenarios unfortunately need to be watered down as well.

WT-4182 Use conservative approach for log checksum errors.

---

src/include/log.h
src/log/log.c
test/suite/test_txn19.py

We do a conservative consistency check of log record headers, as well as
consistency checks of 'holes' in log files. This catches corruptions that
occur from appending junk to a valid log file, or inserting corruption
in the unused portion of the final log file.
Corruption errors are reported in a standard way that suggests using
salvage to fix.
Tests have been updated, along with extra commentary.

WT-4147 For log recovery/salvage, report/fix corruption outside of log records

---

src/log/log.c
test/suite/test_txn19.py

A small code change, with a big comment!  The test case has been updated accordingly.

WT-4186 Log recovery/salvage now detects/reports corruption within log records

---

src/btree/bt_slvg.c
src/cursor/cur_join.c
src/log/log.c
src/optrack/optrack.c
src/support/scratch.c
src/txn/txn_recover.c

Review WiredTiger error returns for `WT_ERROR`, `WT_PANIC` and `WT_RUN_RECOVERY`, ensure the appropriate places include verbose error messages.

WT-4183 Add verbose option to log more messages on error returns

---

test/suite/test_schema08.py

I created a new Python test that does some schema operations, walks the log, gathering LSNs and then truncates the log to each of those offsets and then runs recovery in each of those.
I'm slightly unsatisfied with it. @keithbostic was correct in the ticket that detailed verification is difficult as we don't know what the system should look like at any given LSN. I copy the database and then truncate the log, but I don't know whether, at that LSN, the actual file should or should not exist during that point in the processing. So the only thing I do is run recovery and get `list -v`. So that makes sure the metadata can be read.
Another path I started on was a `test/csuite` program that would try to make sure we created and then ran recovery on every type of log record and log operation …

WT-3856 Add schema test to truncate and recover from every LSN.

---

bench/workgen/workgen.cxx

Previously, there was code approximating realloc in C++, but it assumed the wrong size of TableRuntime objects in an array.

WT-4235 Fix workgen tracking of table runtime across workloads.

---

dist/api_data.py
src/conn/conn_api.c
src/conn/conn_log.c
src/include/config.h
src/include/log.h
src/include/wiredtiger.in
src/log/log.c
src/os_win/os_fs.c
test/suite/test_config07.py

File extend API on Windows(setEndOfFile) could be slow at times based on MSDN API
documentation hence disable it.

WT-4026 Add implementation for existing file extension configuration API

---

src/conn/conn_api.c
src/include/extern.h
src/meta/meta_turtle.c
test/suite/test_bug020.py

This allows wiredtiger_open to succeed on Windows if a crash happened during a rename at the conclusion of checkpoint.
(cherry picked from commit 0846890fd6f4673d6e7f673262147b0eef8112f9)

WT-4143 Use WiredTiger.turtle.set if it exists but WiredTiger.turtle does not (v3.6 backport)

---

src/btree/bt_delete.c
src/btree/bt_handle.c
src/include/btree.h

As per my understanding, checkpoint is marking the btree as clean, which is resulting in not constructing the update chain when fast truncate page is read back from disk.

WT-4104 keys reappear after fast truncate.

---

src/btree/bt_handle.c

This is fall out from WT-4104 fix, where handles opened by verify are
missed to mark as read-only.

WT-4249 Attempt to discard dirty page during verify operation.

---

test/suite/test_prepare_las01.py
test/suite/test_prepare_lookaside01.py

Currently I kept updates to be low, so that test case will not hang.
Will change the values after lookaside is enabled for prepared transactions.

WT-4211 test for long running prepared transactions.

---

src/cache/cache_las.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btmem.h
src/include/btree.i
src/include/extern.h
src/include/txn.i
src/reconcile/rec_write.c
src/txn/txn_rollback_to_stable.c
test/suite/test_timestamp04.py
test/suite/test_timestamp06.py

There were several bugs, resulting in incorrect data after a rollback_to_stable call in the presence of lookaside history.
The main issue was with pages images containing updates newer than the stable timestamp (which is a common case because WiredTiger evicts optimistically, assuming the stable timestamp will move forward by the time the next checkpoint starts).  Since rollback_to_stable doesn't modify page images, it instead was marking such pages "invalid" so the history would always be loaded before the pages could be read correctly.  However, the required history to make sense of such pages could be removed by a lookaside sweep, which makes decisions solely on the contents of the lookaside table without access to the "invalid" flag.
The solution here is to read the history into cache …

WT-4144 Fix rollback_to_stable with lookaside history.

---

dist/s_void
src/log/log.c
test/suite/test_txn19.py

Most reports of log corruption will now be reported as messages,
and they will not stop recovery from succeeding.

WT-4233 Change log corruption errors to warnings and truncate log

---

src/btree/bt_split.c

(cherry picked from commit d5061d5a500cacce3e637faef4f6d88be477b65c)

WT-3710 Fix a race condition between concurrent page splits

---

src/btree/bt_split.c
src/evict/evict_page.c

@agorrod, @michaelcahill and I figured this out today, the problem is checkpoint can do insert-splits and that can corrupt the tree.
I'm running overnight to confirm, but I think this is ready for review.
This should probably be backported to any release where checkpoint attempts to evict pages.

WT-4239 Checkpoint doing insert-splits can corrupt the tree.

---

src/cache/cache_las.c

Previously this code juggled two session handles, one of which referenced the original tree and the other was specific to the lookaside table.  Now that the code has been simplified to just use one session, we need to take care when we need to operate on the original tree.

WT-4263 When copying a key for a lookaside write, use the right tree.

---

src/txn/txn_rollback_to_stable.c

In particular, cope with updates that are already rolled back, and don't fire for updates that were never assigned a timestamp unless "assert=(commit_timestamp=X)" is configured for the table.

WT-4256 Loosen check during rollback_to_stable.

---

src/btree/bt_walk.c

@keithbostic Please review this. It slightly modifies the change you made in WT-4208. Basically I separate out the two different callers to `wt_spin_backoff` so they do not interfere with each other. This change recovers a bit more than half the performance loss.

WT-4216 Use separate counters for page_swap yield and sleep.

---

test/csuite/schema_abort/main.c

@agorrod This is a branch to add debugging for schema_abort when threads hang. This will give us some more information if it fails on a sanitizer build. We still need a core dump to know exactly where they're all hanging. But this is a step forward.

WT-4270 Add an operation field to know where threads hang.

---

dist/api_data.py
src/config/config_def.c
src/include/wiredtiger.in
src/txn/txn_timestamp.c
test/suite/test_timestamp09.py

Added a new option `oldest_reader` to the `query_timestamp` API. When `query_timestamp` is used with this option, WT will return the minimum of the read timestamps of all the active transactions which includes the checkpoint transaction. If there are no active readers at the time of issuing this API, WT will return WT_NOTFOUND.
@bvpvamsikrishna please review.

WT-4154 Surface the oldest read timestamp.

---

src/btree/bt_cursor.c
src/btree/col_modify.c

In summary, the change in #4262 to clear `WT_CURSOR_BTREE.ins` in the case of finding a record past the end of the page breaks if there are already records past the end of the page and we found an exact match to one of those records.
I don't see any point in doing the work to check past the end of the page if we've already found an exact match, and I want to clear `WT_CURSOR_BTREE.ins` in the append case.
Two bits worth thinking about:
* I'm only checking `WT_CURSOR_BTREE.compare` to determine if an exact match exists, which means any search ending up past the tree is required to pass in a non-zero compare value. I reviewed the usage and I think it's correct (with one fix for `WT_RECNO_OOB`), regardless, I don't think we should be passing in a non-NULL `WT_CURSOR_BTREE.ins` if we didn't …

WT-4286 Column store should skip end-of-table checks if there's an exact match.

---

dist/s_tags

Running `dist/s_tags` will now correctly index the functions with `WT_GCC_FUNC_ATTRIBUTE` tag.

WT-4231 Fix ctags index of functions with attributes.

---

src/btree/bt_read.c

Sometimes it may be possible to avoid the transition.
It's likely the check in __wt_page_in avoids this transition - but it's not clear to me that the code always goes through that path - so I think we might as well be explicit in __page_read as well.

WT-4282 Restructure __page_read and avoid moving from limbo to lookaside

---

test/csuite/schema_abort/main.c

@agorrod Here's the change to increase the timeout to 30 seconds, as discussed in the ticket.

WT-4272 Increase startup timeout to 30 seconds for slow I/O systems.

---

src/btree/bt_delete.c
src/btree/bt_slvg.c
src/evict/evict_file.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/extern.h

During eviction we could move a page from WT_REF_LIMBO to WT_REF_LOCKED. But if the page eviction fails due to some reason we would call __evict_exclusive_clear which used to transition the ref->state from WT_REF_LOCKED to WT_REF_MEM which is undesired. This change set restores the page ref state to the previous state rather than WT_REF_MEM when eviction fails.

WT-4259 Restore ref to previous state rather than MEM when eviction fails

---

src/txn/txn_recover.c

@ddanderson  Here's a minor change to the verbose error message in recovery. I needed this when debugging WT-4284 since the call to `recovery_cursor` was failing.

WT-4284 Print a verbose message in recovery on error too.

---

src/include/txn.h
src/txn/txn.c
src/txn/txn_log.c

@michaelcahill, @bvpvamsikrishna, this changes the meaning of `WT_TXN_OP_NONE`, so it's potentially interesting for that reason.

WT-4301 WT_CURSOR.reserve operations can leak memory when committed.

---

src/block/block_ext.c
src/btree/bt_handle.c
src/btree/bt_split.c
src/btree/bt_sync.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btree.h
src/include/btree.i
src/include/session.h
src/meta/meta_track.c
src/txn/txn_ckpt.c

The existing WT_SESSION_IS_CHECKPOINT macro is too broad: it allows a session-wide checkpoint to bypass the usual rules that make eviction of dirty pages safe.  Since we allow operations like WT_SESSION::create to run concurrent with a checkpoint and flush the metadata, we can't have the checkpoint being tapped for forced eviction in the metadata while it is being flushed.
Track the tree a checkpoint is currently flushing, and only allow checkpoint to bypass eviction rules in that tree.

WT-3879 Fix a race if checkpoint evicts a metadata page.

---

src/include/txn.i
src/txn/txn.c

@bvpvamsikrishna, @agorrod, I'm not sure this fix is correct, but hopefully 2551e61 points out where the problem is.

WT-4300 setting the update timestamp can overwrite the WT_REF.addr field

---

test/csuite/wt4156_metadata_salvage/main.c

Test branch against the clang sanitizer Jenkins job.

WT-4292 Add call to testutil_cleanup to avoid memory leak.

---

src/evict/evict_page.c

Specifically, as a checkpoint is running, it writes updates to the metadata table, which can cause pages to exceed maximum sizes.  It's fine to attempt eviction in that situation, but it should be ordinary eviction that respects the usual visibility rules.

WT-4306 Fix mode if metadata pages need eviction.

---

src/include/misc.h
src/include/txn.i
src/reconcile/rec_write.c

If txn operations have timestamp, then that transaction cannot be prepared, so we avoid making a copy of the key.

WT-4305 Avoid key copy for txn operations with timestamps as they cannot be prepared.

---

src/btree/bt_split.c

It is not currently safe to allocate or free blocks in a tree where checkpoint is running. That's because the checkpoint needs to calculate a map of free space that corresponds to the pages referenced by the checkpoint (otherwise either verify reports holes in the file).
What we saw was an in-memory split is causing an on-disk block to be freed. That was because the split freed any deleted references it found in the parent, which includes freeing their blocks.

WT-4308 Insert split during sync should not free blocks.

---

src/btree/bt_read.c

The lookaside sweep code removes entries in the background so stop removing lookaside entries when reading pages from lookaside tree.

WT-4185 Don't remove all lookaside entries when reading a page.

---

test/csuite/random_directio/util.c

Don't call stat(), save the file size and then open the file, there's a potential race. Instead, open the file and use fstat().

WT-4337 Coverity #1395811 Time of check time of use

---

src/cursor/cur_file.c
src/session/session_dhandle.c

@ddanderson, I introduced a bug in #4292, __wt_session_lock_dhandle() returns 0 with is_dead set, and we're not holding a lock in those cases.

WT-4340 the cursor caching layer can incorrectly release too many handle locks.

---

src/txn/txn.c
src/txn/txn_rollback_to_stable.c

Since the later phase of rollback_to_stable holds a lock to prevent sweep running concurrently, this check should use the same approach to avoid spurious failures.

WT-4335 Don't fail rollback_to_stable due to sweep activity

---

src/txn/txn_rollback_to_stable.c

Unless a table is configured with assert=(commit_timestamp=XX)
skip validating the timestamp ordering during rollback to stable.

WT-4315 Skip timestamp order check in rollback to stable

---

src/btree/bt_debug.c
src/include/extern.h
test/format/config.c
test/format/config.h
test/format/format.h
test/format/wts.c

@michaelcahill, this change takes the in-memory page maximum size into account when sizing the cache, guaranteeing every worker thread can pin two maximum-sized pages into memory without blowing out the cache. This change significantly increases the memory that format will allocate to a cache in the presence of larger numbers of threads and so has an outsized impact on our small-cache testing.
On the other hand, this should resolve the category of small-cache problems where we're simply filling the cache.
I don't like it, but I like playing whack-a-mole even less, and I think that's where we've ended up.

WT-4164 Evict clean internal pages where possible when there is cache pressure

---

src/include/txn.i

As part of indirect reference resolution in prepared transactions, the transaction operation structure currently always refer the first update in the update chain. This assumption is wrong, first update might be from a different transaction in case of lower isolation levels.

WT-4351 Ensure resolving prepared transactions use updates from itself

---

src/btree/bt_cursor.c
src/cursor/cur_file.c
src/include/extern.h

@michaelcahill, the simplest solution I could find was to maintain the "positioned" status of the cursor in the upper-level cursor code. That's arguably a layering violation, let me know if you see something better.
I also reworked error handling in the Btree cursor remove code, there were paths were we could lose errors.

WT-4293 WT_CURSOR.remove can lose a cursor position

---

src/include/txn.i

multi_update_count is tracked only for commit, but not for rollback. Hence moved the assertion to check only in case of commit.

WT-4355 transaction rollback crash for prepared updates.

---

src/btree/bt_compact.c
src/btree/bt_delete.c
src/btree/bt_handle.c
src/btree/bt_page.c
src/btree/bt_read.c
src/btree/bt_slvg.c
src/btree/bt_split.c
src/cache/cache_las.c
src/evict/evict_page.c
src/include/btmem.h
src/include/btree.i
src/include/txn.i
src/reconcile/rec_write.c

We need to consider a lookaside block with prepared updates "active" until they are read back into cache (as part of commit or rollback).  Otherwise we can decide that the history is no longer relevant and transition a page to the WT_REF_MEM state, ignoring its history.

WT-3898 Keep prepared updates in lookaside until they are read.

---

src/log/log.c
src/log/log_slot.c
test/csuite/timestamp_abort/main.c

@agorrod here's a lighter version of the same fix from the other branch. I found that simply releasing and re-acquiring the locks allows threads to make progress and I am unable to reproduce the many-thread failure with these smaller changes (well over 500 iterations). On develop I can reproduce usually in under 30 iterations.
I also moved the Jenkins log perf test to this branch and it avoids the issues the original branch showed. The min/max throughput is back where it was and the performance of the logging variants is within normal variations.
I believe this branch will have less impact on MongoDB. If you agree, this should be reviewed and merged and the other one closed.

WT-4343 Unlock when sleeping to allow other log threads to make progress.

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_random.c
src/include/cursor.i

@bvpvamsikrishna, the core bug fix is 96a3059.
I think 7ae8a03 probably needs close review. If I'm wrong in my assertion, we'll still need some kind of change there because it must be wrong to fall into the iteration code.

WT-4385 Prepare-conflict during a cursor scan can return the wrong key

---

test/format/ops.c

There was fallout from the initial merge of #4325 regarding cursor out-of-order:
http://build.wiredtiger.com:8080/job/wiredtiger-test-race-condition-stress-sanitizer/27811/
http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress/68652/
@keithbostic @agorrod I recreated the PR based on the old `wt-4366-format-prepare-conflict2`  branch for further work.

WT-4366 Fix how test/format handles prepare conflict errors

---

src/log/log.c

@ddanderson Please review this small change. The code path changed slightly with the log corruption/salvage work a couple months ago and in the specific case of a log cursor getting an error, that error return would get overwritten and lost.

WT-4395 Use WT_TRET so error return is not overwritten.

---

src/log/log.c

* WT-4395 Use WT_TRET so error return is not overwritten.
* Update comment and use T_RET in one more place.
(cherry picked from commit 311601ee79024301cda62e6fd07c59473595e9f4)

WT-4395 Use WT_TRET so error return is not overwritten. (#4339) [v3.6 backport]

---

bench/wtperf/wtperf.c

@ddanderson please review this. While debugging throttling in workgen, I'm running the configuration on wtperf. I'm seeing stalls during checkpoints and wanted the monitoring JSON that is in workgen, and it needed rollback support for the log like table.

WT-4402 Add rollback support and monitor JSON output.

---

src/cursor/cur_std.c

This change was suggested by @michaelcahill .

WT-4418 Don't keep key/value memory buffers allocated for cached cursors

---

src/evict/evict_lru.c

Acquire a read lock on the dhandle just before dumping cache information. This would prevent concurrent updates to dhandle state. Also prevent dumping the handle if it is already marked discarded.

WT-4043 Fix assertion failure while dumping the cache

---

src/conn/conn_log.c

@ddanderson Please review this small change to make the timer in the log server thread more accurate. It is needed for PR #4356.

WT-4159 Start timer in log_server inside loop.

---

src/conn/conn_log.c
test/suite/test_bug019.py

@agorrod, here's one possible algorithm to adjust the number of pre-allocated log files downward. It may be just right or too aggressive.
I have also modified a test that generates a lot of log files in a burst so that I can detect it being adjusted once it is idle.

WT-3756 Adjust pre-allocated file amount downward if we're not using them quickly enough.

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/include/cursor.h
src/include/cursor.i
test/suite/test_prepare_cursor01.py

I have added a python test to test the cursor next / prev behaviour with respect to prepared transactions.
I have made some code changes as well.

WT-4405 Fix cursor next & prev for prepared transactions.

---

bench/workgen/workgen.cxx
bench/workgen/workgen_int.h
bench/workgen/wtperf.py

Fix wtperf.py to not modify the throttling number of a thread to account for log-like operations, it was doing the wrong calculation before.
Fix workgen so that small throttle numbers, or generally numbers that aren't divisible by 20 (internal THROTTLE_PER_SEC constant) are still handled.

WT-4409 Fix workgen throttling

---

build_posix/aclocal/options.m4
build_win/wiredtiger_config.h
src/checksum/arm64/crc32-arm64.c
src/checksum/power8/crc32.sx
src/checksum/power8/crc32_wrapper.c
src/checksum/software/checksum.c
src/checksum/x86/crc32-x86.c
src/checksum/zseries/crc32-s390x.c
src/checksum/zseries/crc32le-vx.sx

WT-4419 big-endian machines incorrectly configure little-endian crc32c support

---

test/evergreen.yml
test/suite/README

Split 'unit-test' Evergreen task (Python test/suite) into 8 buckets/tasks to reduce Makespan for the WiredTiger Ubuntu build variant. The split was based on test name (alphabetic order for the 1st letter after 'test_' prefix) and test runtime, a few alphabetics were grouped together to get them 'relatively' evenly-distributed runtime for each bucket/task. 
There's a plan to implement a mechanism to auto-group and auto-generate buckets/tasks based on historic runtime for each tests, which would be covered later in WT-4441. Added a REAME under test/suite to describe the situation and plan. 
A patch build of the change is [here](https://evergreen.mongodb.com/version/5bf745092a60ed72f37df437).

WT-4410 Split 'unit-test' task to reduce Evergreen Ubuntu build variant runtime

---

test/suite/test_bug019.py

Our PPC machine has very slow I/O allow the test to wait up to 90 seconds for log file pre-allocation to work.

WT-4331 Further extend max wait time for test case.

---

src/docs/cursors.dox

WT_CURSOR::next and WT_CURSOR::prev behaviour for read committed isolation.

WT-4393 Explain cursor behaviour for read committed isolation.

---

src/btree/bt_handle.c

To check the perf regression reported for ycsb small docs, reverting the change made to enable dynamic compression for snappy WT-4433.

WT-4433 Revert Enable dynamic compression for snappy

---

dist/s_stat
src/btree/bt_io.c
src/btree/bt_read.c
src/conn/conn_handle.c
src/cursor/cur_stat.c
src/evict/evict_lru.c
src/include/mutex.h
src/include/mutex.i
src/include/stat.h
src/support/mtx_rw.c
test/suite/test_schema06.py
test/suite/test_stat08.py

This change set increments the new session statistics at the desired locations. It does not add any decrement macro yet because s_define complains about the unused macros.

WT-4383 Update session statistics to reflect the operation statistics.

---

test/checkpoint/smoke.sh
test/csuite/rwlock/main.c
test/csuite/time_shift_test.sh
test/csuite/wt2246_col_append/main.c
test/csuite/wt2323_join_visibility/main.c
test/csuite/wt2535_insert_race/main.c
test/csuite/wt2834_join_bloom_fix/main.c
test/csuite/wt2853_perf/main.c
test/csuite/wt2909_checkpoint_integrity/main.c
test/csuite/wt4333_handle_locks/main.c
test/evergreen.yml

@lukech, @agorrod, with these changes, I think we're close to getting rid of `TESTUTIL_ENABLE_LONG_TESTS`.
The only remaining uses of `TESTUTIL_ENABLE_LONG_TESTS` are:
```
test/evergreen.yml
test/csuite/time_shift_test.sh
```
@bvpvamsikrishna, I'm not sure what's going on with `time_shift_test.sh`. I can't find any place in the system that runs that shell script, and when I tried to run it, it hung on me.
Most of the commits simply remove checks for `TESTUTIL_ENABLE_LONG_TESTS`, because the tests involved were almost always reasonably fast, there wasn't any point in limiting the tests to "long" runs.
There were two tests I changed in other ways:
* 675b0c8: I increased the run-time of `wt2535_insert_race`, and changed it so the threads were queued behind a gate and didn't start until all …

WT-4470 Minimize testing that requires TESTUTIL_ENABLE_LONG_TESTS

---

src/cursor/cur_std.c

(cherry picked from commit ed2bf5948e433eaf9efe62093a9de77026d711be)
This is a clean cherry-pick. @ddanderson, can you help to take a look? Cheers.

WT-4418 Don't keep key/value memory buffers allocated for cached cursor (v3.6 backport)

---

src/reconcile/rec_write.c

Revert a commit in the #4407 branch, it's incorrect and can potentially lead to a column-store core dump.

WT-4482 lint

---

src/include/cursor.i

This PR has two changes.
1.A prepared delete operation after resolution will be visible, but should not use the key and value.
2.cbt->compare to be set to non-zero to indicate that key is not pre-built.

WT-4499 Fix prepare transactions key order check failure.

---

dist/stat_data.py
src/cursor/cur_std.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_cursor16.py

Renamed data source statistic for current total.  Tweeked descriptions
of other cache cursor statistics.  Added test to verify new statistic.
(cherry picked from commit 660c2d688c6c04fb85fbf390f3bc7034cf13cb13)
@ddanderson Can you help to take a look of this v3.6 backport? Thanks.
Once this is merged, I'm going to backport WT-4438.

WT-4411 Added connection statistic for current total of cached cursors (v3.6 backport)

---

src/cursor/cur_file.c
src/session/session_dhandle.c
test/csuite/Makefile.am
test/csuite/wt4333_handle_locks/main.c

@keithbostic Could you help to take a quick look? 
This is a clean cherry-pick (to backport the change to v3.6).

WT-4333 WiredTiger cursor cache doesn't handle all possible locked handle states (v3.6 backport)

---

dist/stat_data.py
src/conn/conn_stat.c
src/cursor/cur_std.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_cursor16.py

(cherry picked from commit dfd4f021aca05e62200454c564ecdfce1924478c)
@ddanderson Please help to take a look. There were merge conflicts while cherry-picking the commit from mongodb-4.0. The `SessionOpStat()` function was introduced by WT-4378, which was not backported to mongodb-3.6. So I kept using `SessionStat()` for this v3.6 backporting change.

WT-4438 Use accurate statistics for cursor cache totals in connection (v3.6 backport)

---

test/csuite/wt4333_handle_locks/main.c

@keithbostic For this one I decided to ignore the test in valgrind. Please review.

WT-4525 Don't run test in valgrind. Too many threads.

---

test/suite/test_bug019.py

One is covered already, but there was another place in the test code.

WT-4503 Pre-allocating log file takes long time on PPC machine

---

dist/s_string.ok
lang/python/wiredtiger.i
src/btree/bt_debug.c
src/cache/cache_las.c
src/include/extern.h
src/include/txn.h
src/meta/meta_ckpt.c
src/txn/txn.c
src/txn/txn_recover.c
src/txn/txn_timestamp.c
test/csuite/timestamp_abort/main.c
test/format/util.c
test/suite/test_timestamp09.py

There are two interesting changes here:
* change af46378, switching most of our timestamp displays from hexadecimal to integers, making sure that I switched all of the ones I should have, and none of the ones I shouldn't,
* change 852f06c, shuffling some code in `__wt_txn_parse_read_timestamp()` so we don't format timestamps unless we need to, and we never hold a lock while formatting a timestamp.

WT-4521 Change WiredTiger to format printed timestamps as 4B integer pairs

---

src/conn/conn_log.c
src/os_win/os_fs.c

Please review this diff. I made the windows-specific remove and rename code retry on access issues up to 10 times. One thing is that I retry in a loop with no pause in between. I also removed the similar code from log archiving. This may help other windows access BF failures as well.

WT-4528 Move remove/rename retry into Windows fs code.

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c

When scanning a new page and prepared update is encountered, the cbt->slot is not being updated, it still represents the slot from the earlier page.

WT-4520 prepare transactions fallout during cursor navigation.

---

src/btree/bt_delete.c
src/reconcile/rec_write.c

The durable timestamp of an update structure should be set in congruence with
it's commit timestamp setting. There were couple of functions that were setting
the commit timestamp but not the durable timestamp. This change sets the durable
timestamp in those places.

WT-4539 Set the durable timestamp of the update structure

---

src/btree/bt_read.c
src/cache/cache_las.c
src/include/btmem.h
src/txn/txn_rollback_to_stable.c
test/suite/test_durable_ts03.py

This brings back the changes in the lookaside schema for the durable timestamp.

WT-4529 Update lookaside schema to store durable timestamp

---

src/conn/conn_api.c
src/txn/txn_rollback_to_stable.c

In particular, `WT_CONNECTION::rollback_to_stable` can run for long enough that other periodic tasks (e.g., calls to `WT_CONNECTION::query_timestamp`) are called concurrently.  Disallow any access to data handles via the default session (outside open / close connection), and use a temporary internal session for rollback_to_stable.

WT-4532 Fix shared access to the default session.

---

src/btree/bt_handle.c

@bvpvamsikrishna ,I have executed the ` mongodb-ycsb-perf-develop`, `mongodb-ycsb-perf-windows` and sys-perf tests and do not see any performance degradations due to this change.

WT-4433 Enable dynamic compression for snappy

---

test/evergreen.yml

Update Evergreen configuration of WiredTiger project to use the recently deployed `v3` toolchain. 
Created an Evergreen patch build to verify the changes, all tasks turned green: https://evergreen.mongodb.com/version/5c5a1f4b1e2d171084b571fe

WT-4533 Upgrade to v3 toolchain for Evergreen tests

---

src/btree/bt_cursor.c
src/btree/bt_read.c

Be less aggressive about creating full copies of a value, especially when the values are large.
(cherry picked from commit 42865162b40203367904627e5fc39d3274665cc4)

WT-4483 Improve caching of small updates to large values. (#4403)

---

test/evergreen.yml
test/evergreen/compatibility_test_for_mongodb_releases.sh

Add a new Evergreen test (task) to verify backward and forward compatibility for a set of mongodb release pairs, to make sure the newer release wt binary is able to read objects generated by older release, and vice versa. The recent data format changes (PM-1309, targeting for MongoDB 4.2) will also be covered by this new test.

WT-4492 Add Evergreen compatibility tests for versioned data format

---

src/block/block_write.c
src/include/block.h

@keithbostic Please review this small fix to remove the redundant field in the block structure now that we have the same information in the file handle. I cannot remove the similar `os_cache` field as that has a different purpose.

WT-4547 Remove redundant os_cache_dirty field.

---

src/support/err.c

Change WiredTiger to wait for the underlying application error function to return before setting the connection-level panic flag, ensuring the application has the opportunity to save the interesting thread stack information.
(cherry picked from commit 44868cbc74ea6e4bcd99f0a4a2807d5763c4de4c)

WT-4518 Give applications a chance to handle panic before API panic returns (v4.0 backport)

---

src/btree/bt_cursor.c
src/btree/bt_read.c

Be less aggressive about creating full copies of a value, especially when the values are large.
Cleanly cherry picked from original commit.

WT-4483 Improve caching of small updates to large values (v3.6 backport)

---

dist/stat_data.py
src/conn/conn_capacity.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

@ddanderson Please review. Note the textual change in the stats. I felt that 'throttled bytes' was a bit misleading, as in it was a count of the subset of all bytes read/written that only applied when we actually throttled/slept, not a total number. I simply deleted the `throttled` prefix. If adding some other prefix is clearer, let me know.

WT-4583 Collect read/write stats in throttling even if not using capacity.

---

src/cursor/cur_index.c
src/cursor/cur_join.c
src/cursor/cur_table.c
src/include/extern.h
src/schema/schema_create.c
src/schema/schema_drop.c
src/schema/schema_list.c
src/schema/schema_open.c
src/schema/schema_rename.c
src/schema/schema_stat.c
src/schema/schema_truncate.c
src/schema/schema_worker.c

@agorrod, I don't see any problems in the Coverity "null pointer dereference" complaints themselves ([https://coverity.corp.mongodb.com/reports.htm#v10632/p10001](https://coverity.corp.mongodb.com/reports.htm#v10632/p10001)), but whoever reviews this branch should double check me.
This branch cleans up some minor problems in the table get/release code paths that I noticed while reviewing the Coverity complaints.
EDIT: We triaged the Coverity reports, so they're a bit harder to find. Here's a link to one of them: [https://coverity.corp.mongodb.com/reports.htm#v11943/p10001/fileInstanceId=24060345&defectInstanceId=17273195&mergedDefectId=104925&fileStart=251&fileEnd=318](https://coverity.corp.mongodb.com/reports.htm#v11943/p10001/fileInstanceId=24060345&defectInstanceId=17273195&mergedDefect …

WT-4595 Coverity "null pointer dereference" complaints

---

src/include/session.h
src/session/session_api.c

__wt_epoch is called everytime in __wt_session_cursor_cache_sweep
when session reset is called. This change is to set countdown to
call less often cursor cache sweep during session reset.

WT-4573 Reducing calls to __wt_epoch from session reset.

---

src/meta/meta_turtle.c
test/csuite/wt4156_metadata_salvage/main.c

Check if the turtle file is corrupted before salvaging the metadata. If it's corrupted, delete it and create a new turtle.
@sueloverso Please let me know your feedback for this change.

WT-4554 Enhance WT salvage to handle the case of corrupted WiredTiger turtle

---

src/include/extern.h
src/txn/txn.c
src/txn/txn_timestamp.c

Function name changes for less ambiguity.
Mask the check of commit timestamp < oldest timestamp.

WT-4607 Allow prepare timestamp to commit behind oldest timestamp.

---

src/include/wiredtiger.in

Looks like MongoDB builds WiredTiger with different compiler flags. So the extra parentheses around this macro that I added to please Clang Tidy is now creating an "unnecessary parentheses" warning in the MongoDB build.

WT-4602 Remove macro parentheses and suppress linter instead

---

src/conn/conn_sweep.c
src/include/dhandle.h
src/include/extern.h
src/include/meta.h
src/include/os_windows.h
src/include/session.h
src/include/verify_build.h
src/meta/meta_ckpt.c
src/session/session_api.c
src/session/session_dhandle.c
src/support/time.c

@sueloverso, would you please do the detailed review?
@michaelcahill, I can't think of any reason not to make this change, but wanted to run it by you for sanity.   Thanks!

WT-4620 Assert a uint64_t can hold a time_t, maintain seconds as uint64_t

---

src/btree/bt_debug.c
src/cache/cache_las.c
src/include/extern.h
src/txn/txn.c
src/txn/txn_recover.c
src/txn/txn_timestamp.c

@nehakhatri5, I removed the `sizeof` argument to  `__wt_timestamp_to_string()`, it's always the same value and it's just something to get wrong.
If you can think of a way to get back error checking on this call, I'm open to suggestions, but absent passing in a `WT_SESSION_IMPL *` argument and asserting it, I don't see anything.

WT-4627 Coverity #111405: out-of-bounds overrun

---

src/reconcile/rec_write.c

Sometimes we attempt eviction of a page by writing the most recent versions of updates.  If such a page remains dirty in cache, it must be visited by the next checkpoint to make sure the data that appears in the checkpoint is a consistent cut of versions.

WT-4324 Checkpoints must rewrite pages with data in the future.

---

test/suite/test_txn20.py

These situations are indirectly tested in a number of existing tests. They typically use the `make_scenarios` helper to create a list of operations and then make some assertions to periodically check how many records are visible at each isolation level.
I thought it'd be nice to have some tests that check the isolation levels in detail and ensure that the expected value is visible (along with some comments to aid understanding).

WT-4645 Add isolation level tests

---

test/evergreen.yml

This change is to split the unit-test (python test suite) into 8 buckets for Windows build variant, the same as what we did for the Ubuntu build variant before. With this change, the longest running task in the Windows variant finished within 10 mins (used to be over 40 mins). Patch build is [here](https://evergreen.mongodb.com/build/wiredtiger_windows_64_patch_07a346d2d683cc8a42c0a29753619476cd09314c_5c92e2fc3627e071fa07bd1f_19_03_21_01_03_57).

WT-4654 Split task for Evergreen Windows build variant to reduce makespan

---

src/cache/cache_las.c

This expression would previously always evaluate to `true` meaning that the assertion was not checking anything. I don't have enough context of the surrounding code to understand what is happening here but I deduced what the assertion should be based on the comment above it.

WT-4650 Fix incorrect WT_ASSERT identified by Coverity

---

src/reconcile/rec_write.c

Sometimes we attempt eviction of a page by writing the most recent
versions of updates.  If such a page remains dirty in cache, it must be
visited by the next checkpoint to make sure the data that appears in the
checkpoint is a consistent cut of versions.
(cherry picked from commit d344940895bbf0232ea02e1e56fefac65d1eb2ae)

WT-4324 Ensure checkpoints rewrite pages with data in the future (#4521)

---

SConstruct
lang/python/Makefile.am
lang/python/wiredtiger.i

Builds using whatever the current python is.  On *nix, uses the python found in configuration; on Windows, uses the python used to run SConstruct.

WT-4700 Python3: use the Python version to build from a single source with Python2/Python3.

---

dist/s_docs
dist/s_python
src/docs/tools/fixlinks.py

Fixed error in fixlinks, called by pyfilter.

WT-4711 Dist tools should ignore generated file wiredtiger.py.

---

lang/python/wiredtiger.i
test/suite/test_calc_modify.py
test/suite/test_cursor12.py

- clear Python error code if we guess wrong on what type we are decoding
- fix malloc failure condition
- fixed modify and calc_modify tests to use bytes type for 'u'
- changed calc_modify test to test both 'u' and 'S' types.

WT-4698 Fixes for modify tests to work with Python3.

---

bench/wtperf/runners/wtperf_run.sh

@ddanderson Please review this tiny change to use `bash` for this shell script instead of whatever system's default `sh`. The other scripts in the `runners` directory already did the same.

WT-4724 Use /bin/bash for the script.

---

src/btree/bt_handle.c
src/log/log.c
src/meta/meta_track.c
src/os_common/os_fhandle.c
src/os_win/os_dir.c
src/os_win/os_dlopen.c
src/os_win/os_fs.c
src/os_win/os_getenv.c
src/os_win/os_map.c
src/os_win/os_mtx_cond.c
src/os_win/os_thread.c
src/os_win/os_utf8.c

I did a quick review of places where we use `__wt_errx` and switched them over to `__wt_err` and supplied an error code when applicable.

WT-4575 Review usages of __wt_errx vs __wt_err

---

test/csuite/wt2853_perf/main.c

This is helpful since failures may naturally occur with slow machines.

WT-4721 Add verbose output for failures in the wt2853_perf test.

---

src/txn/txn_timestamp.c
test/suite/test_timestamp16.py

Set the read timestamp to WT_TS_NONE during transaction cleanup - to avoid reuse in the future.
(cherry picked from commit ecbe60ef4f5b4e48898ed54554471bf86a879aa7)

WT-4631 Always clear the read timestamp for transactions (#4528)

---

src/txn/txn.c
src/txn/txn_timestamp.c

Coverity was complaining about the invocation in `txn_timestamp.c` due to not reading the value of `ret`. This configuration was removed as part of #4550, so I believe the correct solution is to just remove all references to this config item.

WT-4717 Remove usages of "round_to_oldest" configuration

---

test/csuite/wt2909_checkpoint_integrity/main.c

If the test fails to find a range to run a valid test,
issue a warning, flag it as a soft (retryable) error, and rerun the
entire test so that a new calibration for the range is done.
Only if that process fails repeated efforts do we abort the test.

WT-4731 Add new retries to the checkpoint integrity test.

---

dist/api_config.py
src/include/wiredtiger.in

To fit lines within 80 chars, we allow line splits after a set of
non-breaking space indicators.

 WT-4647 Avoid splitting words when wrapping lines in wiredtiger.in

---

test/suite/test_las03.py

From my reading of the comment above, the failing assertion is a ballpark figure to ensure that the number of LAS reads is not out of control. The two test failures I've been able to inspect (the remaining ones have had their logs cleared) have failed with LAS reads of `120`, `130` and `166`. So `200` seems safe to me.
@michaelcahill 
- How did we arrive at `100` to begin with?
- Do you think that `200` is still tight enough to be a useful assertion? Or do you feel that this is unreasonably high.

WT-4309 Increase the maximum expected LAS test reads

---

src/txn/txn_timestamp.c

(cherry picked from commit 7e4c7c40759472df628cad74c68f4bb2df1b51f0)
This is a clean cherry-pick.

WT-4687 Querying all_committed shouldn't get timestamp zero. (v4.0 backport)

---

src/docs/upgrading.dox

The changes of below tickets were identified to worth a description in the upgrading doc, which had been covered by the WT tickets. Just need to replace 3.1.1 with 3.2.0 since we decided to use 3.2.0 as the new release version. 
- WT-4192 Remove WiredTiger raw compression support
- WT-4427 Make WiredTiger timestamps always on and 8 bytes
- WT-4193 Make WT_CURSOR.modify require explicit transactions
Please note WT-4283 (together with WT-4156) introduced a new top level API (salvage), which did not exist in the previous WT release 3.1.0. Won't mention it in the upgrading doc, instead will cover it in the release note.

WT-4745 Update upgrading doc for 3.2.0 WiredTiger release

---

src/txn/txn_timestamp.c

- fixed reference to uninitialized variable.
- removed stray spaces from messages.

WT-4749 Fix error case for prepare_transaction

---

test/evergreen.yml

Set up evergreen.yml to run unit tests (Python test suite) with Python3. A new build variant `Ubuntu 14.04 (Python3)` is created, reusing most of existing evergreen variant/task configuration for unit/python tests, by abstracting the difference out into variant expansions. Unit tests are split into 8 buckets so that they can run in parallel to minimise the makespan of the build variant. 
The evergreen patch build turned green:
https://evergreen.mongodb.com/version/5cca63242fbabe450dbbaeeb
In order to turn on the new Python3 tests (build variant) as pull request tester, an evergreen project configuration update is needed. We can turn it on once this evergreen configuration change is merged.

WT-4726 Set up pull request tester to run with Python3 in evergreen

---

src/reconcile/rec_visibility.c

Previously, we would resolve birthmarks for lookaside eviction, and in some other cases (e.g., when overwriting an overflow value).  In particular, we didn't resolve birthmarks during "scrub" eviction, where a new disk image is calculated but kept in cache along with active updates.
Since birthmarks assign version information to on-page data, they should be resolved as part of any eviction that saves updates and overwrites the previous on-page value.

WT-4352 Resolve birthmarks during eviction in more cases.

---

src/reconcile/rec_visibility.c

Reverts part of ace6f599762486eaf980d45c2337fce4660d5180 from WT-4352.

WT-4759 Save a copy when an old overflow value is discarded.

---

tools/wt_ckpt_decode.py

The change is needed because the WT unpack routine now takes a bytes object.  It was working previously for Python3 because a bytearray object behaves like a bytes object in Python3.  In Python2, they are not the same at all, but an explicit conversion will solve the problem.

WT-4766 Make wt_ckpt_decode script work with both python2 and python3

---

test/suite/test_compat02.py
test/suite/test_compat03.py

Cutting a 3.2.0 WiredTiger release broke the Python compatibility
tests, this change fixes the build failures, but means we no
longer test against the 3.1 release. I suspect it's not the
correct final fix.

WT-4767 Temporary fix for compatibility tests

---

lang/python/Makefile.am
lang/python/setup_pip.py
lang/python/wiredtiger/intpacking.py
lang/python/wiredtiger/packing.py
lang/python/wiredtiger/packutil.py
lang/python/wiredtiger/pip_init.py

- avoid the use of relative imports, it doesn't work well with
installed packages.
- introduce packutil.py, to remove a circular dependency that causes
trouble with installed packages.
- minor changes to setup_pip.py for Python3.
- add a new library directory to check for standard compression libs.

WT-3929 Fix "pip install" to work with Python3.

---

src/txn/txn_timestamp.c

We added an assertion that non-prepared transactions commit
timestamp is newer than the oldest, which triggered a test failure.

WT-4779 Disable an assert that commit timestamp is valid

---

src/btree/bt_ret.c

If modifies are created with out-of-order timestamps, WiredTiger should use apply all previous modifications until it finds a complete copy of the document. Once a modify is identified as the most recent visible version for a value WT should not apply normal visibility rules to the prior versions - they were visible when the modify was performed, so should be included in the read.

WT-4776 Modify operations should be equivalent to updates.

---

src/btree/bt_handle.c
src/evict/evict_file.c

With this fix, I do not get any data mismatch failures with the test case. Prior to this fix, I was getting 100% failure with 20 parallel processes.
@michaelcahill I'm a bit concerned this undoes some of the fixes from WT-3715 and dropping the LAS entries for a dropped file with `force=true` by moving it. I also considered some path that would remove or avoid saving the id with the sweep dead versus discard phases if we reopened, but that felt messy pretty quickly.

WT-4768 Save the id for sweep dropping in btree_close instead of eviction.

---

src/btree/bt_delete.c
src/btree/bt_read.c
src/btree/bt_split.c
src/include/btmem.h
src/include/btree.i
src/txn/txn_rollback_to_stable.c

It is only okay to discard a reference once its history is no longer required, even if reconciliation created an empty page image.

WT-4769 Keep empty page references with active history.

---

src/btree/bt_read.c

When the `resolved` flag was first added to `ref->page_las`, it was only being set in the common case where lookaside history was re-instantiated in memory.  This change sets it consistently in all (currently both) paths.

WT-4794 Mark lookaside history resolved in all read paths.

---

src/log/log.c

@ddanderson can you do a quick review of this? All sanitizer builds will fail until this is merged. With this change it passes, prior to this sanitizer catches the bug all the time.

WT-4817 Fix off-by-one error.

---

test/evergreen/verify_wt_datafiles.sh

I've basically just moved the dump section into the verbose block and added the call to unset as it prevents the fork out of memory failure we have been seeing.

WT-4710 Modify datafile verification test

---

src/cache/cache_las.c
test/suite/test_las04.py

For in-memory configurations, the lookaside session isn't allocated so we need to add a `NULL` check here.
I've amended the `test_las04` tests to include in-memory configuration. When I remove the check, this test causes a segmentation fault in the same spot as the reported issue so I believe that this is the correct fix.
After discussing with @agorrod, we elected to simply ignore lookaside configuration for in-memory setups.

WT-4823 Add check for uninitialised lookaside resources

---

dist/s_string.ok
test/checkpoint/checkpointer.c
test/checkpoint/smoke.sh
test/checkpoint/test_checkpoint.c
test/checkpoint/test_checkpoint.h
test/checkpoint/workers.c

Add options to encourage seeing conditions related to lookaside usage,
handle sweep, checkpoints and different types of data access patterns.
This is the first step, subsequently will make the new functionality
configurable.

WT-4793 Extend test/checkpoint to use timestamps and more

---

tools/optrack/find-latency-spikes.py

Explicitly cast the value to int to avoid a type exception. This started showing up after we converted to Python3.

WT-4828 Fix the type exception in operation tracking.

---

src/conn/conn_api.c

This PR is artificially bringing the dirty target down to encourage the eviction threads to help reconcile prior to shutdown.
I reproduced similar results to those recorded by @agorrod in the ticket. Bringing the target value down even further doesn't seem to yield any real improvement. And again, this doesn't help much for when we have a single table.

WT-4190 Decrease shutdown time by doing multi-threaded cache flush

---

src/btree/bt_delete.c
src/btree/bt_read.c
src/btree/bt_slvg.c
src/btree/bt_sync.c
src/evict/evict_file.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btree.i
src/include/cache.h
src/include/extern.h

Clean cherrypick of commit 34c1ffa.

WT-4690 During checkpoints, make sure eviction does not split. (v4.0 backport)

---

test/suite/suite_subprocess.py
test/suite/test_bug018.py
test/suite/wttest.py

As part of this change, a function is made available that allows a specialized test method to run in a subprocess.

WT-4775 Make the "bad file descriptor" test resilient against crashing.

---

src/include/misc.i
src/include/wt_internal.h

With this change the LSM + timing stress stuck cache failure does not happen. @keithbostic let me know what you think of these tweaks to the timing stress function.

WT-4837 Don't sleep in timing_stress if the cache is totally full.

---

src/include/wiredtiger.in
src/txn/txn_timestamp.c
test/suite/test_timestamp09.py

Alex, this is a change already queued up in WT-4733 (#4610), to not log an error message if the application specifies a timestamp older than the current oldest timestamp.
The argument is an application will hit this unless it explicitly synchronizes the read and oldest timestamps, and it's not an error so much as an alert the application's read timestamp likely needs to move forward.
The `test/format` PR #4610 requires this change, and MongoDB is running into it as well (SERVER-40591), which is why I'll pulled it out into its own PR.
@bvpvamsikrishna, @michaelcahill: is this OK with you?

WT-4844 Only log an informational message when a set read-timestamp is older than the oldest timestamp.

---

dist/api_data.py
dist/s_string.ok
src/btree/bt_split.c
src/cache/cache_las.c
src/config/config_def.c
src/conn/conn_api.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btree.i
src/include/cache.h
src/include/wiredtiger.in
src/reconcile/rec_write.c
src/txn/txn_log.c
test/checkpoint/smoke.sh
test/checkpoint/test_checkpoint.c
test/checkpoint/test_checkpoint.h
test/suite/test_debug_mode04.py

This branch pulls in the assertions from the original WT-4750 branch for the data inconsistency reproducer. This branch does not include the assertions in sweep that were commented out on that branch because they were triggering a lot.

WT-4477 Add in asserts from data inconsistency checking.

---

dist/api_data.py
dist/log.py
dist/log_data.py
src/config/config_def.c
src/conn/conn_api.c
src/conn/conn_handle.c
src/conn/conn_log.c
src/conn/conn_reconfig.c
src/include/connection.h
src/include/extern.h
src/include/log.h
src/include/txn.h
src/include/txn.i
src/include/wiredtiger.in
src/log/log.c
src/log/log_auto.c
src/txn/txn.c
src/txn/txn_log.c
src/txn/txn_recover.c
src/txn/txn_timestamp.c
test/csuite/timestamp_abort/main.c
test/suite/test_debug_mode01.py
test/suite/test_debug_mode02.py
test/suite/test_debug_mode03.py
test/suite/test_timestamp17.py
test/suite/wttest.py

* WT-4712 Add diagnostic logging.
* We may not have a btree here, don't check it.
* Add bit field on fileid to ignore operation and remove ignore flag
from the record.
* Allocate a txn id in diagnostic mode if needed.
* Only call logging of timestamp setting if one is set.
* Skip timestamp operation in recovery. Add diagnostic to timestamp_abort.
* Need to unpack timestamp operation to move pointers to next operation.
* Correctly set bit to ignore the fileid. Remove verbose from test.
* Remove debug line.
* Conditionalize assertion that is no longer always true.
* Add support for durable and prepare timestamps.
* Whitespace and spelling.
* Add clock time to txn_timestamp log record.
* Add in support for checkpoint retention (i.e. archiving changes).
* Remove verbose setting from test.
* …

WT-4712 Add diagnostic logging. (#4572)

---

src/support/huffman.c

This PR is just changing the loop counter to be the same integer type as the maximum that we're comparing in the terminating condition. Otherwise, it may be impossible to terminate the loop.

WT-4787 Coverity: Potential infinite loops

---

tools/optrack/find-latency-spikes.py

After conversion to python 3, file names were encoded as byte arrays and not decoded. As a result the filenames used at HTML links were not properly formed and we could not click on these links. Add proper decoding to fix that.

WT-4829 Fix broken filenames in operation tracking.

---

src/btree/bt_slvg.c

Memory allocated into `config` was never freed.
I also explicitly initialized `ckptbase`, just for clarity.

WT-4850 __slvg_checkpoint() metadata memory leak

---

src/block/block_ckpt.c
src/block/block_ckpt_scan.c
src/block/block_mgr.c
src/btree/bt_import.c
src/include/block.h
src/include/extern.h
src/include/meta.h
src/meta/meta_ckpt.c
src/utilities/util_list.c
test/csuite/import/smoke.sh

@agorrod, @michaelcahill, this is a significant change to the standalone recovery code Michael merged. In summary, the previous code tried to repair the most recent checkpoint found in the metadata, and that doesn't work in all cases. The reason I didn't see it was I had a bug in my test harness, and was only testing the import process, instead of doing a full verification after the import.
In this branch, instead of just storing the base file metadata and the corrected checkpoint information in the file, the block manager now constructs the complete, almost-correct, file checkpoint metadata entry, and copies it into the file's avail list along with the base metadata and the corrected checkpoint information.
Additionally, I've pushed changes into the test program to do a full verify after …

WT-4853 standalone recovery code cannot handle deleted checkpoints

---

src/reconcile/rec_write.c

This PR is just to free the `WT_RECONCILE` struct that we allocate earlier in the function.
I think it makes sense to free here if we're returning non-zero.

WT-4790 Coverity: Memory leak within __wt_curbulk_init

---

src/txn/txn_recover.c

@sueloverso, I hit this when debugging a different problem (the symptom was leaking the allocated memory), so I figured I'd add in a check. I don't think it can happen absent corruption, but it might save us some debugging if we ever start importing objects in a significant way.

WT-4855 WiredTiger recovery should detect files without unique IDs.

---

src/btree/bt_ret.c

If modifies are created with out-of-order timestamps, WiredTiger should use apply all previous modifications until it finds a complete copy of the document. Once a modify is identified as the most recent visible version for a value WT should not apply normal visibility rules to the prior versions - they were visible when the modify was performed, so should be included in the read.
(cherry picked from commit 8eb2d9c36c5c23da09f75e16dff982f0be52d34f)

WT-4776 Modify operations should be equivalent to updates (v4.0 backport)

---

dist/stat_data.py
src/cache/cache_las.c
src/include/meta.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

Unclean cherry-pick of the backport commit (b89fdd5) from the `mongodb-4.0` branch.

WT-4706 Add a statistic to track the lookaside table size (v3.6 backport)

---

bench/wtperf/runners/500m-btree-rdonly.wtperf

In our Jenkins testing, IO performance seems to vary a lot. This change is simply throttling the read workload so that variation in IO performance is less likely to affect the `500m-btree-rdonly` workload.

WT-4694 Throttle reads in wtperf to make readonly workload perform more consistently

---

src/reconcile/rec_visibility.c

(cherry picked from commit 6b408028f0267ca26d8821a0be6925e5cb48eca2)

WT-4760 Checkpoint should not read past a stable update (#4651) (Backport-4.0)

---

src/include/txn.i

(cherry picked from commit 39d5985b0db70d601a5adeedbbed964c13d61a24)

WT-4827 Apply commit timestamps when a truncated page is read (#4668) (backport-4.0)

---

src/btree/bt_delete.c
src/btree/bt_handle.c
src/btree/bt_read.c
src/btree/bt_split.c
src/cache/cache_las.c
src/evict/evict_file.c
src/include/btmem.h
src/include/btree.i
src/include/cache.h
src/include/extern.h
src/reconcile/rec_write.c
src/txn/txn_rollback_to_stable.c

This is the 2nd attempt of backporting the set of data corruption fixes to 3.6, hoping to make a clean commit history easy for non-squash merge.
Please note the only diff with the 1st attempt (#4693) is the removal of `has_prepares` field in the `__wt_page_lookaside` structure, as the field is not meant to be used in 3.6.

WT-4352 Backport data corruption fixes to 3.6 (2nd attempt)

---

src/cache/cache_las.c
test/suite/test_las04.py

Clean cherrypick of 57bd75f off `develop`.

WT-4823 Add check for uninitialised lookaside resources (v4.0 backport)

---

src/evict/evict_lru.c
test/csuite/wt4333_handle_locks/main.c

Disable random selection till we get more testing and confidence with
that change.
Fix handle lock test to reset cursors before caching them. Otherwise,
for configurations with many threads it can end up in a state
where there is a cursor on every page, preventing the pages from
splitting, and ultimately blocking eviction.  This was exposed by
changes to eviction, but is a structural problem with the test case.

WT-4878 Disable random dhandle selection for eviction

---

bench/wtperf/config.c
bench/wtperf/runners/evict-btree-scan.wtperf
bench/wtperf/track.c
bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
bench/wtperf/wtperf_opt.i
src/docs/wtperf.dox

To wtperf, add scan_table_count, scan_interval, scan_pct, scan_icount to
support threads that do scanning, using their own separate tables or the
regular set of tables.
Records are not scanned in order, but using a pattern that eventually visits
all records, and using tables in round robin.
Added printing for more fail conditions, so we can tell better why threads fail.
When an operation fails with rollback error when running with log_like tables
enabled and ops per txn at 0, do retries, instead of exiting.
Added a new wtperf workload using the new scan features, tuned to show
failures similar to ones seen in the field.

WT-4758 Create a workload that stresses eviction by running periodic scans

---

src/cache/cache_las.c
test/suite/test_las04.py

Clean cherrypick of eb6ba5c off `mongodb-4.0`.

WT-4823 Add check for uninitialised lookaside resources (v3.6 backport)

---

lang/python/setup_pip.py
test/py_install/testbase.py
test/py_install/testpack.py

SWIG generated Python files are now installed in build_posix, so the script needed to be adjusted.

WT-4812 Fix the Python distribution script for Python3 changes.

---

src/btree/bt_cursor.c
src/cursor/cur_std.c
src/docs/upgrading.dox
src/include/wiredtiger.in
test/csuite/scope/main.c
test/csuite/wt4105_large_doc_small_upd/main.c
test/format/config.c
test/format/ops.c
test/suite/test_cursor12.py

WT-4840 WT_CURSOR.modify must require explicit, snapshot-isolation transaction

---

src/reconcile/rec_write.c

Remove the override of the randomization that is choosen Under
WT_CACHE_EVICT_DEBUG_MODE flag.

WT-4895 Avoid overriding the randomization of lookaside eviction

---

src/btree/bt_ret.c

If modifies are created with out-of-order timestamps, WiredTiger should use apply all previous modifications until it finds a complete copy of the document. Once a modify is identified as the most recent visible version for a value WT should not apply normal visibility rules to the prior versions - they were visible when the modify was performed, so should be included in the read.
(cherry picked from commit 8eb2d9c36c5c23da09f75e16dff982f0be52d34f)
(cherry picked from commit 4738e7c66f59517d9d9c4a0daa291f53f11bf209)

WT-4776 Modify operations should be equivalent to updates. (v3.6 backport)

---

src/include/btree.i

Don't allow reconcile a page refernce when flags indicate
no eviction, session can't perfom slow operation in addition
to the existing.

WT-4898 Don't allow the eviction server to reconcile if it's busy

---

test/evergreen.yml

Lower the scheduling frequency for endianness compatibility tests from **once per day** to **once per week**, to avoid overwhelming little-endian (zseries/s390x) Evergreen distro queue.

WT-4836 Lower scheduling frequency for endianness compatibility tests

---

dist/stat_data.py
src/evict/evict_lru.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

At the moment, we have a stat called `cache_eviction_pages_queued` which tracks the amount of pages initially queued. Afterwards, we do an LRU sort of the pages and trim some entries off the end of the queue. This PR is adding a statistic to track the size of the queue after this processing.

WT-4792 Add stat to track pages queued for eviction after LRU sorting

---

src/include/column.i

This is the simple change that has (so far) fixed the column store mismatch issue. Please review.

WT-4857 Use a local variable to access the insert structure.

---

examples/c/ex_stat.c
src/cursor/cur_stat.c
src/include/wiredtiger.in

WiredTiger example codes are corrected to follow proper
format types of the cursors. Also updated the documentation
of these two API's are they can't check the passed argument
types.

WT-4530 get_key and get_value example format corrections

---

src/btree/bt_curprev.c

CID 112861 (#1 of 1): Deference null return
The reported coverity problem is not possible, but in the same
flow with a different branch flow the issue can happen, so added
a NULL check.

WT-4791 Guard against deference null return (coverity)

---

test/suite/test_prepare07.py

Added a scenario to improve coverage when the oldest timestamp advances past a prepared update.

WT-4612 Improve test coverage for prepare updates older than the oldest.

---

src/evict/evict_lru.c
test/csuite/wt4333_handle_locks/main.c

This mostly goes back to the state before data handles were chosen
randomly to search for eviction candidates.  It also changes some of the
calculations for how many pages to enqueue per tree.
Also fix handle lock test to reset cursors before caching them.
Otherwise, for configurations with many threads it can end up in a state
where there is a cursor on every page, preventing the pages from
splitting, and ultimately blocking eviction.  This was exposed by
changes to eviction, but is a structural problem with the test case.
(cherry picked from commit 859c527b01143c0f3d1a064b4ae14592c65628d1)

WT-4878 Disable random dhandle selection for eviction (#4716)

---

src/include/reconcile.h
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c

Don't skip selecting an update after seeing an uncommitted / prepared entry in an update list, but remember whether one has been seen when determining whether the page can be evicted.

WT-4943 Track uncommitted/prepared status through reconciliation.

---

src/include/reconcile.h
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c

We've tried a few times to get this right, so I've renamed the variables to clarify.  Reconciliation as a whole needs to know whether there are any uncommitted updates on a page (to prevent lookaside eviction): that's tracked in `r->updates_uncommitted`.  Selecting a single update needs to know whether any updates *in the list* are prepared or uncommitted.  That's now tracked in `list_prepared` and `list_uncommitted`.

WT-4943 Separate tracking per update list vs per page.

---

bench/wtperf/wtperf.c

CID 113115, CID 113116, CID 113117 and CID 113119 (integer overflow)
Typecasted one of the variable to uint64_t to evaluate the arithmetic
using 64 bits instead of 32 bits.
CID 113118 (dead code)
Removed dead code

WT-4906 wtperf.c integer overflow and dead code fixes (Coverity)

---

src/txn/txn_ckpt.c

It causes failures in MongoDB.

WT-4958 Temporarily never skip checkpoints with a timestamp

---

src/btree/bt_sync.c

Testing has uncovered a situation where a checkpoint can discard history required for snapshot readers.  Disable this eviction for now when history can be lost, to make sure snapshot transactions get correct results.

WT-4965 Avoid eviction during checkpoints that causes amnesia.

---

src/btree/bt_read.c
src/cache/cache_las.c
src/include/btmem.h
src/include/btree.i
src/include/extern.h
src/include/reconcile.h
src/include/txn.i
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c
src/txn/txn_rollback_to_stable.c
test/suite/test_las01.py
test/suite/test_timestamp04.py

This branch attempts to fix some problems in the base branch, improve efficiency of lookaside evictions and subsequent reads, and simplify the information being tracked for pages with history in lookaside.

WT-4961 part 2: rewrite of reconciliation visibility checks.

---

test/suite/test_compat02.py

Since this hang is not reproducible on any Mac after 500 iterations, I have added debugging so that we can gather some additional information in evergreen. It only sometimes fails there too.

WT-4963 Add debugging for rare test hang.

---

build_posix/aclocal/strict.m4
examples/c/ex_async.c
src/async/async_api.c
src/conn/conn_capacity.c
src/include/gcc.h
src/include/lint.h
src/include/msvc.h
src/include/mutex.i

This PR is to get WiredTiger to compile with the newest Clang and GCC releases.
I had a look at the new flags introduced in both releases but all of the interesting ones are either on by default or are part of `-Wextra`.
The main change here is to move away from the legacy `__sync` compiler intrinsics and towards the `__atomic` ones. These new functions allow us to specify memory order so we could potentially use one of the weaker orderings for performance reasons. I think for our purposes, we want the strongest ordering (sequentially consistent ordering which is what you get by default with a C++ `std::atomic`).

WT-4858 Clang 8 and GCC 9 compatibility

---

src/include/btree.i

If we can't evict immediately (e.g., in the eviction server thread), at least put pages requiring urgent eviction on the urgent queue.

WT-4957 Fix a perf regression in urgent eviction.

---

src/btree/bt_cursor.c
src/btree/bt_ret.c
src/cursor/cur_std.c
src/include/extern.h
src/include/txn.i
src/support/modify.c
src/txn/txn_recover.c
test/csuite/wt3338_partial_update/main.c

This reverts commit 2a43429ebff0b8c4f8d27130cfcf009b98d9b7e6.

Revert "WT-4460 Optimize for in-order, non-overlapping modifications"

---

dist/s_string.ok
src/btree/bt_debug.c
src/include/btmem.h
src/include/btree.i
src/include/reconcile.h
src/include/serial.i
src/reconcile/rec_write.c

This PR is to handle the issue where we consistently have at least one update that doesn't get written to the data file by a checkpoint causing the `write_gen` to never get reset to 0. This type of workload causes the `write_gen` to continually increase until we hit the check in `__page_write_gen_wrapped_check` and begin stalling.
This new scheme involves capping the `write_gen` to 2 since we only need this value to determine whether the page is clean or dirty (or has been dirtied during reconciliation).

WT-4956 Handle the case where 4 billion updates are made to a page without eviction

---

src/btree/bt_cursor.c
src/cursor/cur_std.c
src/include/wiredtiger.in
test/csuite/scope/main.c
test/csuite/wt4105_large_doc_small_upd/main.c
test/format/config.c
test/format/ops.c
test/suite/test_cursor12.py
test/suite/test_las01.py

Disallow WT_CURSOR.modify in anything other than an explicit transaction
at snapshot isolation.
Add tests that other transaction configurations fail.
(cherry picked from commit 7c486eb1d4aecb67a635e06cdd74d179d69638f1)

WT-4840 WT_CURSOR.modify must require explicit, snapshot-isolation transaction (v4.0 backport)

---

src/btree/bt_sync.c

Checkpoint gives up it's snapshot prior to checkpointing the metadata.
Once the snapshot is given up, it's not OK for checkpoint to try eviction prior to doing reconciliation.

WT-5050 Don't allow checkpoints to evict without a snapshot

---

src/btree/bt_cursor.c
src/cursor/cur_std.c
src/include/wiredtiger.in
test/csuite/scope/main.c
test/csuite/wt4105_large_doc_small_upd/main.c
test/format/config.c
test/format/ops.c
test/suite/test_cursor12.py
test/suite/test_las01.py

Reverts wiredtiger/wiredtiger#4767

Revert "WT-4840 WT_CURSOR.modify must require explicit, snapshot-isolation transaction (v4.0 backport)"

---

test/suite/test_las06.py

This PR is adding a test that exercises the new lookaside behaviour and makes some assertions on how the implementation should behave from a memory usage + perf perspective.

WT-4678 Write the test workload for relevant history in cache

---

src/btree/bt_cursor.c
src/cursor/cur_std.c
src/include/wiredtiger.in
test/csuite/scope/main.c
test/csuite/wt4105_large_doc_small_upd/main.c
test/format/config.c
test/format/ops.c
test/suite/test_cursor12.py
test/suite/test_las01.py

Disallow WT_CURSOR.modify in anything other than an explicit transaction
at snapshot isolation.
Add tests that other transaction configurations fail.
(cherry picked from commit 7c486eb1d4aecb67a635e06cdd74d179d69638f1)

WT-4840 WT_CURSOR.modify must require explicit, snapshot-isolation transaction (v4.0 backport)(2nd attempt after revert)

---

bench/wtperf/runners/metadata-split-test.wtperf
src/evict/evict_page.c

Also add a wtperf workload that demonstrates the problem.
(cherry picked from commit 8313783f309cdfc61818607b8714ab0fe3bdec41)

WT-4882 Allow metadata pages to split under load. (#4722) (v4.0 backport)

---

src/include/txn.i
src/txn/txn.c

This PR is to address the use after free issue exposed by WT-4957. Since `__txn_commit_timestamps_assert` actually populates the update list with pointers to data from a given cursor, that cursor needs to stay open until we're finished with the update list.

WT-5038 format heap use after free in __txn_commit_timestamps_assert

---

src/reconcile/rec_write.c

Remove the override of the randomization that is choosen Under
WT_CACHE_EVICT_DEBUG_MODE flag.
(cherry picked from commit dccdc93ba1ca5efcdc2239617d9532f66fa4944e)

WT-4895 Avoid overriding the randomization of lookaside eviction (#4736) (v4.0 backport)

---

src/include/txn.i
src/session/session_api.c
src/txn/txn.c
src/txn/txn_log.c
src/txn/txn_rollback_to_stable.c
test/suite/test_debug_mode03.py
test/suite/test_debug_mode04.py
test/suite/test_debug_mode05.py

This PR is adding some additional logic to clear txn IDs from the global table when we have table logging on. To give a bit of background on what this is solving:
The lifecycle for a normal prepared txn is:
1. Begin txn.
2. Do operations. The first one will alloc a txn ID and a write to the log.
3. Prepare the txn. Here we clear the txn ID from the global table.
4. Commit the txn. We purposely don't clear the txn ID since we did it at the prepare stage.
When a txn has no operations, it gets neither a txn ID nor a log record allocated for it. When we have table logging turned on, an empty prepared txn will have its log record initialised (and a txn ID allocated) at commit time in order to write it to the log. With our existing logic, this causes the txn ID to not get cleared from the …

WT-5046 Prepared transactions aren't properly cleared from global table with WT_CONN_LOG_DEBUG_MODE enabled

---

src/cache/cache_las.c
src/include/extern.h
src/include/txn.i
src/support/modify.c
test/suite/test_las06.py

This PR is adding support for modify records with the new lookaside logic. When we search lookaside and find a modify update, we keep walking backwards until we find a regular update and squash all the modifies in between on top of that base update.

WT-5052 Enhance lookaside search functionality to handle WT_MODIFY records

---

bench/wtperf/config.c
bench/wtperf/runners/modify-force-update-large-record-btree.wtperf
bench/wtperf/runners/modify-large-record-btree.wtperf
bench/wtperf/runners/wtperf_run.sh
bench/wtperf/track.c
bench/wtperf/wtperf.c
bench/wtperf/wtperf.h

The wiredtiger_calc_modify function is used to find out the modify vector
based on the old and new record values. This function may fail when the
changed modifications of the new record reaches the allowed limit of
modification for the MODIFY operation, instead of UPDATE.
This perf test is to find out the extra overhead because of
wiredtiger_calc_modify function where it fails to find out the modify
vectors because of reach of the limits configured for the MODIFY operation
and at the end the operations is carried out as normal update.

WT-4935 Add a perf test to find out the wiredtiger_calc_modify overhead

---

bench/wtperf/runners/modify-force-update-large-record-btree.wtperf
bench/wtperf/runners/modify-large-record-btree.wtperf

The record size is reduced to consume less disk space for the test
as part of the performance tests. Earlier it used to take around
60GB, now it is reduced to 12GB.

WT-5062 Adjust the record size to consume less size in Jenkins perf machine

---

build_posix/Make.base
build_posix/reconf
dist/s_clang-format

This PR is removing code generation from `make check`. Since we began using `clang-format` as part of our code generation process, this has become a problem on architectures such as ZSeries and PowerPC since we don't have the appropriate binaries for them (and maintaining them all would be untenable).
I think it's reasonable to remove this from the build process since I don't believe it belongs here anyway. To my way of thinking, this is unnecessarily making a development dependency also a build dependency. Just as an example, if you have a project that uses code generated by Protobuf, I wouldn't expect to need `protoc` to build it (although developers would need it).
Please let me know your thoughts on this.

WT-5074 Fix "make check" on exotic architectures

---

test/csuite/random_abort/main.c

The row store operations like row_put(insert, update), row_modify(modify)
and row_remove(remove) cursor operations are covered in the test.
The test creates 3 set of files per worker (insert, modify and delete).
Insert file contains all the records that are inserted, followed by
either the record is modified or deleted those will be in their corresponding
files.
After a successful recovery, the main thread verifies the records based
on the file the key is present.
- insert, the record must present
- delete, the record must not present
- modify, the record must present with modified data

WT-4884 Test for recovery correctness with all WAL operation types

---

bench/wtperf/config.c
bench/wtperf/runners/modify-force-update-large-record-btree.wtperf
bench/wtperf/runners/modify-large-record-btree.wtperf
bench/wtperf/runners/update-large-record-btree.wtperf
bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
bench/wtperf/wtperf_opt.i
src/docs/wtperf.dox

The newly added workload configuration parameter can be used for
both modify/update operations where the new value record is formed
with a set of modifications distributed evenly across the whole
old record.

WT-5080 New wtperf workload modify_distribute option

---

src/btree/bt_read.c
src/btree/row_modify.c

structure when allocating a birthmark update.

WT-5098 Simplify the __wt_update_alloc() code, stop passing an empty WT_ITEM

---

src/cache/cache_las.c
src/include/btmem.h
src/include/cache.h
src/include/extern.h
src/reconcile/rec_write.c
src/txn/txn_rollback_to_stable.c

This PR is to replace the `las_counter` part of the key in the lookaside schema and replace it with `las_timestamp` and `las_txnid` for more efficient searches.
Since those values are now embedded in the key, I've removed them from the value.

WT-5092 Modify lookaside schema to add timestamp and transaction id to the key

---

test/format/rebalance.c

The statistics_log configuration used by wiredtiger is not readonly, as such when we close the connection and then open it with any readonly wiredtiger util. e.g. dump it reads the config from the WiredTiger.basecfg file which tells it to begin statistic logging, which triggers this assertion:
`[1567488766:358842][30124:0x7f1ed3d3d700], wt, statlog-server: __wt_open, 248: lock_file || !LF_ISSET(WT_FS_OPEN_CREATE)`

WT-5100 Update test format to pass -R to disable readonly in wt util

---

dist/s_string.ok
src/btree/bt_debug.c
src/include/btmem.h
src/include/btree.i
src/include/reconcile.h
src/include/serial.i
src/reconcile/rec_write.c

Clang formatted cherry-pick of 5697d8b.

WT-4956 Handle the case where 4 billion updates are made to a page without eviction (v4.0 backport)

---

dist/s_string.ok
src/btree/bt_debug.c
src/include/btmem.h
src/include/btree.i
src/include/serial.i
src/reconcile/rec_write.c

Relatively clean cherry-pick of 5697d8b2b2eeba02f4d7d5cb4514427f82207358.
The only alteration was that `WT_RECONCILE` was defined in a different file so I removed the `orig_write_gen` struct member in `rec_write.c` instead of  the non-existent `reconcile.h`.

WT-4956 Handle the case where 4 billion updates are made to a page without eviction (v3.6 backport)

---

test/format/smoke.sh

smoke.sh is run during PR testing when we call `make check` this change simply adds a specific config that forces rebalance to run while also turning statistics logging on, which had we had would've caught the bug introduced by WT-4535.

WT-5113 Add new test format run to smoke config

---

test/csuite/random_abort/main.c

-remove redundant assignment to data.
-bound the maximum number of characters read by fscanf

WT-5097 Fix two coverity issues in random_abort/main.c

---

src/btree/bt_random.c
src/include/cursor.h
src/include/extern.h
test/suite/test_cursor_random.py

@agorrod, this branch reworks the "pick a random page and return a random key/value item from it" version of `WT_CURSOR.next` configured for random key/value returns.
It appears to fix the [SERVER-42840](https://jira.mongodb.org/browse/SERVER-42840) failure.
I ended up with something that I think works better, but the change is chock-full of magic constants I can't defend, there's an awful lot of guesses about what is most likely to return a better random selection.

WT-5068 WT_CURSOR.random unnecessarily returns duplicate records

---

test/evergreen.yml

This PR is to duplicate #4874. 
Evergreen patch build: https://evergreen.mongodb.com/version/5d8a17792a60ed61ee142414

WT-5131 Fix Evergreen configuration file to use working directory

---

dist/api_data.py
examples/c/ex_all.c
src/btree/bt_read.c
src/btree/bt_sync.c
src/cache/cache_las.c
src/evict/evict_page.c
src/include/btmem.h
src/include/btree.i
src/include/extern.h
src/include/reconcile.h
src/include/txn.i
src/include/wiredtiger.in
src/reconcile/rec_child.c
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c
src/txn/txn_ckpt.c
src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c
test/suite/test_debug_mode05.py
test/suite/test_las01.py
test/suite/test_timestamp04.py
test/suite/test_timestamp06.py
test/suite/test_timestamp11.py
test/suite/test_timestamp16.py

WT-4961 Checkpoints with cache overflow must keep history for reads. (Clang Format migration)

---

src/conn/conn_api.c
src/conn/conn_open.c
src/include/extern.h
src/txn/txn.c

@agorrod, the interesting work is in 1231279 (fbb894c just moves the final checkpoint code out of the connection-close source and into the transaction subsystem source).
I moved the shutdown of the capacity, checkpoint and sweep servers to earlier in the shutdown process (it didn't seem useful to let them continue to run during shutdown), but that means we shut them down in two places rather than one, which is obviously more complicated. An alternative would be to not set the `WT_CONN_CLOSING_NO_MORE_OPENS` flag before doing the final checkpoint. That means the sweep server can race with the final checkpoint, but that's been true for a long time without any adverse effects.

WT-5122 the sweep server can close handles the final checkpoint is in the process of using

---

bench/wtperf/runners/wtperf_xray.sh

This is a script to run `wtperf` with XRay profiling enabled and generate some interesting information using the logs. I'm invoking like so:
```
XRAY_BINARY=llvm-xray-8 FLAME_GRAPH_PATH=~/work/FlameGraph/flamegraph.pl bash ../../../bench/wtperf/runners/wtperf_xray.sh ../../../bench/wtperf/runners/small-btree.wtperf
```
`wtperf_account.txt`: A breakdown of the top 10 functions where the workload is spending most of its time.
```
Functions with latencies: 308
funcid      count [      min,       med,       90p,       99p,       max]       sum  function
258        504 [ 0.001050,  0.731710,  7.316153,  7.316191,  7.316230] 939.480654  os_mtx_cond.c:58:0: __wt_cond_wait_signal
471         16 [ 5.624216, 88.403520, 88.404453, 88.404574, 88.404574] 752.231184  thread_group.c:17:0: __thread_run …
```

WT-5128 Add script to run wtperf with XRay profiling

---

src/btree/bt_ret.c
src/cache/cache_las.c
src/include/btmem.h
test/suite/test_las06.py

As it stands, if we open a transaction and apply multiple modifies at the same timestamp, lookaside eviction will cause all but one of these modifies to be lost. This is because they occupy the same key in lookaside (`btree_id, key, timestamp, txnid`).
This PR adds some logic to detect this situation and squash the modifies into a single standard update upon lookaside eviction.

WT-5141 Handle multiple modifies for the same key on lookaside eviction

---

src/txn/txn_rollback_to_stable.c

We recently introduced this constraint, but it's not acceptable.

WT-5160 Stop requiring a checkpoint before calling rollback_to_stable

---

test/evergreen.yml

git.apply_patch is redundant as it is already done in git.get_project

WT-5161 Remove redundant git apply patch command

---

src/cache/cache_las.c

Sweep server should periodically clean the LAS obsolete
entries when there as any tables are dropped or if the LAS
not empty. Fix the check that leads to not to remove the
obsolete entries when there are no tables dropped.

WT-5150 Fix the check to find out whethere LAS is empty

---

src/btree/bt_read.c
src/btree/row_modify.c
src/cache/cache_las.c
src/include/btree.i
test/suite/test_las03.py

Update various memory allocations that are done during the page
instantiation for the tracking stats variables.
Set the page modify restore_state with proper value once the page
is successfully instantiated.
If LAS updates are newer than the disk image, set the flag to include
these updates in the next checkpoint.
Otherwise, if the page image contains newest versions of data than
LAS updates, check whether the page that is marked as dirtly can
be cleared under some conditions.

WT-5167 Fix the missing pieces of page instantiation from las

---

test/evergreen.yml
test/evergreen/csuite_test_evg_task.template
test/evergreen/make_check_test_evg_task.template

Changes include:
- tagging all applicable tasks as `pull_request`
- tagging Windows only tasks as `windows`
- simplifying listing tasks in `ubuntu1804` build variant
- updating task templates to fit recent retro code
@quchenhao Can you help to take a look? Thanks.

WT-5176 Group pull request tasks using Evergreen task tags

---

dist/s_void
src/btree/bt_read.c
src/btree/bt_split.c
src/btree/row_modify.c
src/cache/cache_las.c
src/include/extern.h
src/include/reconcile.h
src/include/serial.i
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c

Backport WT-4899 WT-4940 WT-4943 to mongodb-4.0
There are no test cases associated with the change, not really giving me any confidence that I'm doing the right thing. :(

WT-4899 WT-4940 WT-4943 backport v4.0

---

src/cache/cache_las.c

Sometimes it is possible that the obsolete records in
lookaside are still not may be written to disk image. To avoid
removal of those records, consider the last_ckpt_timestamp also
into consideration before removing those records.
Checkpoint will ensure read all the pages in the tree that has
lookaside content for checkpoint, this ensures that proper version
of the lookaside records are written to disk image, so considering
the last checkpoint time also in obsolete record removal will avoid
of removing any records that don't have disk image.

WT-5191 LAS sweep to consider last checkpoint time

---

src/include/mutex.h
src/include/mutex.i

This bug was introduced in #4740. I didn't notice the deadlock at the time since I didn't run the Python test suite with `--with-spinlock=gcc`.
> The byte is set to some implementation defined nonzero “set” value and the return value is true if and only if the previous contents were “set”
The `__atomic_test_and_set` compiler intrinsic is similar to its `__sync_*` counterpart in that it returns a `bool` for the previous value before the call took place (not for success like I thought). So actually a successful acquisition should return `false` since no other thread should have set it to its "on" value.

WT-5157 Fix atomics usage in spinlock impl

---

test/evergreen.yml

Reduce the runtime for Evergreen Windows build variant, unit test bucket 01 and 06 (the bottlenecks), by dedicating the 2 buckets for `compat` and `timestamp` tests, moving the other tests of `c` and `t` families into other buckets. 
After this change, bucket 01 and 06 both had less than 9m runtime for the Windows build variant. The ubuntu1804 build variant had a similar evenly distribution. 
Patch build: https://evergreen.mongodb.com/version/5db12ad15623437f20d25a7f

WT-5195 Reduce Python unit test build time for Evergreen Windows build variant

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/btree/bt_random.c
src/btree/bt_read.c
src/btree/bt_ret.c
src/btree/bt_split.c
src/btree/col_modify.c
src/btree/col_srch.c
src/btree/row_modify.c
src/btree/row_srch.c
src/cache/cache_las.c
src/include/cursor.i
src/include/extern.h
src/include/wiredtiger.in
src/reconcile/rec_col.c
src/reconcile/rec_row.c

@bvpvamsikrishna, please feel free to change the reviewers on this ticket, I picked @sueloverso because she looked at a possibly related failure in WT-5043, and Alex because he's been in some of this code before.
Reviewers: I'm going to post some discussion in WT-5120.
The changes in 3c2a6a3 are semantic sugar, just getting ready for the change in 62391cc which is the real fix.

WT-5120 checkpoint hangs when reconciliation doesn't release the eviction generation

---

dist/s_clang-format

The temporary files used to store the `clang-format` output haven't been cleaned up properly. So everyone's `/tmp/` is probably full of these. 😞

WT-5106 Remove temporary files generated by s_clang_format

---

src/btree/bt_read.c
src/reconcile/rec_write.c

The reason we were not getting a `WT_PREPARE_CONFLICT` is because the `min_skipped_ts` doesn't get written to for prepared updates on eviction. Therefore in the case where we have a single prepared update in lookaside, we don't bother doing a full instantiation because we (incorrectly) think that the on-disk value is the newest.
@sulabhM In `cache_las.c`, I see the condition `ref->page_las->has_prepares && ref->page_las->min_skipped_ts == WT_TS_MAX` a few times which makes me think that this is the correct spot for the fix (as opposed to writing to `min_skipped_ts` even in the prepare case which I was considering).

WT-5233 Perform a full lookaside instantiation for a page if it has prepared updates

---

src/include/extern.h
src/include/reconcile.h
src/include/reconcile.i
src/reconcile/rec_col.c
src/reconcile/rec_row.c
src/reconcile/rec_write.c
src/session/session_dhandle.c

@agorrod, I ended up drilling the hole that allows callers of the reconciliation split code to force a split regardless of the current disk image size. I found a path I don't think is too ugly, and so avoid the retry logic we discussed (and which neither of us particularly liked). I like this approach better because I think it's reasonable for future work to want to force a split in a similar way, and this moves reconciliation in a more generally useful direction than the retry implementation would.
@sulabhM, these changes are primarily in the split code you & I wrote awhile back. The idea is that a caller can force the underlying code to split regardless of the current size of the disk image.
One relatively subtle change is [at line 1255 in …

WT-5142 Don't create huge root pages when rebalancing or bulk-loading objects with overflow keys

---

src/cache/cache_las.c

Let the LAS sweep work under "read committed" isolation
Earlier, LAS sweep working under "read uncommitted" isolation can find the
LAS records that are even not committed. The LAS sweep does the
cleanup based on the first record that is present for the key.
As the LAS sweep operates in "read uncommitted" mode, sometimes
even when the entire record chain for the key is not finished
insertion, the LAS sweep may clean the part of the update chain
as it finds them as obsolete. This leads to missing update chain
records and that leads to record miss.
To solve this problem, let the LAS sweep to work under "read committed"
isolation level, that leads to non-visibility of records from a running transaction.

WT-5196 data mismatch with las sweep

---

src/btree/row_modify.c

Obsolete birthmark cannot be freed if it follows a set of uncommitted
updates as the uncommitted updates can be aborted and freed causing the
entire update chain being removed in this case.
Birthmark can be discarded only if there is an update that is globally visible before it.

WT-5136 Fix reading freed memory due to birthmark after uncommitted updates freed 

---

src/cache/cache_las.c

This reverts commit fb527a54117f3865aae8a25557849f1228d48205.
WT-5193 has reverted the change in WT-5150 as it leads to data mismatch
problems with checkpoint. WT-5196 addresses the data mismatch problem
even when the las sweep is enabled. Reenable the LAS sweep.

WT-5220 Re-enable LAS dropped table change from WT-5150

---

test/syscall/wt2336_base/base.run

This fixes the syscall test failure caused by WT-5042.

WT-5239 Fix syscall test failure

---

dist/s_funcs.list
src/btree/bt_cursor.c
src/btree/bt_debug.c
src/include/extern.h

@agorrod, @sulabhM, I'm uncertain on some of the possible `WT_REF_LIMBO` transitions, please consider if there's a better test we could use than turning off all fast searches of `WT_REF_LIMBO` pages.
I considered calling `__wt_las_page_skip()` from inside `__cursor_page_pinned()`, but that requires locking the page which might be too heavy-weight (and, as I said, I'm not completely sure that calling that function would be sufficient).

WT-5169 WT_REF_LIMBO pages cannot support fast (leaf-page only) searches

---

test/evergreen.yml

This is the change to increase test frequency for the Linux syscall test. It used to be triggered to run every week, and with this change it will run for each commit merge.

WT-5251 Increase frequency for Linux syscall test

---

dist/s_string.ok
test/format/format.h
test/format/snap.c
test/format/util.c

WT-5211 Print mismatch information before dumping page and LAS, which

---

build_posix/Make.subdirs
build_posix/aclocal/options.m4
build_posix/configure.ac.in
tools/xray_to_optrack/Makefile.am
tools/xray_to_optrack/xray_to_optrack.cxx

Added an `xray_to_optrack` utility program to convert from XRay logs to the OpTrack format. I'm currently building with `../configure --enable-llvm --with-llvm-config=llvm-config-8`.
One issue that I'm seeing is that `xray_to_optrack` generates very big OpTrack logs. The `find-latency-spikes.py` seemed to handle it ok despite taking a while but `optrack_to_t2.py` never finished for me and I waited quite a while. This makes sense to me since I think OpTrack logs have historically been used to instrument a few functions of interest whereas by default, XRay will instrument anything that compiles down to more than 200 instructions. To make this more manageable, we might have to manually choose a set of functions to instrument when building with XRay. We can do it either with function …

WT-5217 Write utility to generate operation tracking log from X-Ray trace

---

dist/stat_data.py
src/btree/bt_walk.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

With the changes that you proposed @keithbostic, we will no longer be spinning on the __wt_page_swap() call in __tree_walk_internal() when it encounters a locked ref.

WT-4565 Remove loop to wait in __tree_walk_internal() for an internal page

---

src/btree/bt_read.c
src/cache/cache_las.c
src/include/btmem.h
src/reconcile/rec_visibility.c

Stop time pair is required for every record in the history
store to represent the end of visibility of each record in
the history store. Store it in the key of the every history
record.

WT-5267 Store stop time pair in history store

---

test/csuite/Makefile.am
test/evergreen.yml
test/suite/test_las06.py

This PR is disabling `schema_abort` since we have a regression in the durable history feature branch.

WT-5295 Disable remaining failing tests in durable history branch

---

test/format/format.sh
test/format/t.c

@sueloverso, I liked your idea of using `SIGKILL`, it's a nice simplification.
While I was there, I realized we weren't treating timeouts as failures, and we weren't kill the process group.

WT-5288 format.sh must distinguish format timeouts and kill child processes

---

src/config/config_collapse.c
src/conn/conn_dhandle.c
src/include/dhandle.h
src/meta/meta_ckpt.c
test/syscall/wt2336_base/base.run

This is to backport WT-5042 and WT-5239.
When doing this, I found the syscall test on mongodb is broken and created a separate ticket WT-5297.
Since I cannot verify the change using syscall test, I manually verified that the change generates the expected change in stderr.txt outputted by syscall test. So I think the backport is good to go.

WT-5042 Avoid calling config functions during checkpoint. (#4936)

---

build_posix/aclocal/options.m4

Change the default value of the WT build to store the time pair
data in the WT_CELL structure whenever a record is reconciled
into a disk image.

WT-5286 Enable data format to store time pair

---

src/btree/bt_cursor.c

@sueloverso, @tetsuo-cpp, I misread the code when I made the changes for WT-5120.
The row-search code doesn't abandon the leaf-page search in cases where it can't be sure the search is safe, it continues with the search and relies on its caller to use the `WT_CURSOR_BTREE.compare` value to decide if a match was found. That's fine for searches, but inserts quite likely don't have an exact match, and so we have to ignore any leaf page results where we don't get an exact match and we're at the edge of the page, as the item might belong on a different page entirely.
I have not re-run the WT-5120 tests to confirm this fix still works, but it seems like it would have minimal impact.

WT-5277 Cursor key out-of-order detected in the lookaside file

---

src/txn/txn.c

Remove the assert that checks that no lookaside operations
can rollback. It is possible that las transaction can rollback.
it is a rare scenario, but better to avoid it.

WT-5037 Remove wrong assert of las transaction rollback

---

test/format/format.sh

Added a new argument(-b) to the format wrapper script to pass the fomat prefix with the binary 
For example : 
a. In some cases the format binary is run with nice command
nice ./format.sh <other_arguments>
b. In some cases the format binary is run with nice & checksegv command
nice checksegv ./format.sh <other_arguments>
So, with the new argument (-b) user can pass prefix with the binary.
For ex : 
format.sh -b "nice ./t"
format.sh -b "checksegv ./t"
format.sh -b "nice checksegv ./t"
format.sh 
NOTE - By default the format binary it is set to "./t" if -b is not specified

WT-5309 update format script add prefix command

---

src/docs/spell.ok

Add words to spell.ok to satisfy earlier versions of aspell on jenkins boxes.

WT-5037 Add words to spell.ok 

---

test/evergreen.yml

I added `TESTUTIL_SLOW_MACHINE=1` to the environment variable list for `make-check-msan-test` to bypass the `test_wt2853_perf` test. The existing code already checks for this environment variable, so the only change required was to the Evergreen configuration.

WT-5221 Bypass test_wt2853_perf in Evergreen make-check-msan-test

---

test/evergreen.yml

The default behaviour of the `compile wiredtiger` function is to set the `CC` environment variable to `gcc`. However, the `bench/workgen` compilation requires `CC` to be set to `cc`, otherwise the directory is bypassed by the recursive make. I overrode the value of `configure_env_vars` so that the `CC` environment variable was not set prior to calling `configure` (thus using the system `/usr/bin/cc`).
The Jenkins test is here: `http://build.wiredtiger.com:8080/job/wiredtiger-test-split-stress/`

WT-5006 Migrate wiredtiger-test-split-stress test to Evergreen

---

src/include/btree.i

Reconciliation has some fast-path code to work on prefix-compressed
to avoid figuring out each key from scratch which would require
going back some number of K/V pairs to key that's not
prefix-compressed and then rolling forward), we use the complete
key we just built for the last K/V pair's reconciliation, and
apply the current key's prefix-compression change to it, saving
us quite a bit of work. The change in WT-4642 clears that saved,
last-key information, and it leads to a performance drop compared
to 4.0 version. More details are available in SERVER-44991.

WT-5319 Avoid clearing the saved last-key when no instantiated key

---

src/reconcile/rec_visibility.c

@bvpvamsikrishna, this change fixes the failure, but I'm not familiar enough with the lookaside visibility rules to be confident it's the correct fix.
Additionally, I would suggest reviewing the update walk loop in the `__wt_rec_upd_select()` function for any other information not being collected because prepared updates are detected and ignored too early in the loop. I reviewed it and don't see anything, but I think it's worth further review.

WT-5263 prepared updates written to the lookaside file are not always read as needed

---

test/suite/wttest.py

Extensions that have a name of None, or "" or "none" are treated the same, they are not loaded.

WT-5314 For python tests, if the name of an extension is blank, don't try to load it

---

dist/s_funcs.list
src/btree/bt_cursor.c
src/btree/bt_debug.c
src/include/extern.h

* Add a function to dump the LAS table based on a random cursor.
* If a thread does a timestamp-based read which doesn't require page history (that is, the page
is left in WT_REF_LIMBO state), and then does a subsequent read based on a different timestamp
which does require page history, we can't treat the page as "pinned", we have to take the full
read path in order to load the page history.
* Assert a pinned page is either in a WT_REF_LIMBO or WT_REF_MEM state.
(cherry picked from commit 9dde82b6f01edc02562535291b02b52a01e6f05d)

WT-5169 WT_REF_LIMBO pages cannot support fast (leaf-page only) searches [Backport to 4.0]

---

src/reconcile/rec_write.c

I've added an assert to check that the previous reconciliation buffer (r->prev_ptr) is not null. This is because this value should always be initialized when a write is triggered either because it was 'forced' or part of a 'bulk-load'. 
The hope is that this silences Coverity, otherwise I will manually mark the report as a false positive. The assertion remains valid in order to find any actual exceptions.

WT-5257 Coverity dereference after null check

---

src/cache/cache_las.c

* WT-5196 Let the LAS sweep works under read committed isolation
LAS sweep working under read uncommitted isolation can find the
LAS records that are even not committed. The LAS sweep does the
cleanup based on the first record that is present for the key.
As the LAS sweep operates in read uncommitted mode, sometimes
even when the entire record chain for the key is not finished
insertion, the LAS sweep may clean the part of the update chain
as it finds them as obsolete. This leads to missing update chain
records and that leads to record miss.
To solve this problem, let the LAS sweep to work under read
committed isolation level, that leads to non visibility of records
from a running transaction.
* The isolation level is set to default in LAS sweep, there is no need
of save and restore …

WT-5196 data mismatch with las sweep (#4967) [Backport to 4.0]

---

src/evict/evict_lru.c

Added log message to the event handler when rollback due to cache full. Tested through randomly factors which forcibly initiates the workflow of producing the message.  
JIRA: https://jira.mongodb.org/browse/WT-5090

WT-5090 Log message to event handler when rollback due to cache full

---

bench/wtperf/wtperf.c
dist/s_goto.py
src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/btree/bt_read.c
src/btree/bt_slvg.c
src/btree/bt_vrfy.c
src/btree/bt_vrfy_dsk.c
src/btree/row_key.c
src/btree/row_srch.c
src/cursor/cur_stat.c
src/reconcile/rec_col.c
src/reconcile/rec_row.c
test/csuite/schema_abort/main.c
test/format/ops.c

(cherry picked from commit f1e0c0a784f0f86fa5fb6c1e914a9d0b7fac7448)

WT-5112 Update regex to handle labels with underscores (#5062) BACKPORT-4.2

---

bench/wtperf/wtperf.c
dist/s_goto.py
ext/datasources/helium/helium.c
src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/btree/bt_read.c
src/btree/bt_slvg.c
src/btree/bt_vrfy.c
src/btree/bt_vrfy_dsk.c
src/btree/row_key.c
src/btree/row_srch.c
src/cursor/cur_stat.c
src/reconcile/rec_col.c
src/reconcile/rec_row.c
test/csuite/schema_abort/main.c
test/format/ops.c

(cherry picked from commit f1e0c0a784f0f86fa5fb6c1e914a9d0b7fac7448)

WT-5112 Update regex to handle labels with underscores (#5062) BACKPORT-4.0

---

src/include/txn.i

Now the algorithm can be simplified to first walk the update chain,
then the history store, and return the first visibile update.

WT-5333 Simplify txn read and remove invisible birthmark optimisation

---

src/btree/bt_ret.c
src/reconcile/rec_visibility.c
test/suite/test_las06.py

This change read the time pairs we write to the cell back to memory when we append the on page value to the update chain. If the cell has a stop time pair, we need to append an extra tombstone before the on page value.

WT-5335 Read the start and stop time pairs back from cell

---

bench/workgen/runner/evict-btree-lookaside.py

This is an example Workgen benchmark to stress lookaside/LAS. This is achieved through: 
- Long running transactions consisting of read and update operations.
- Low cache size (~20%) for a reasonably sized WT table with large documents.
- Pareto distribution for operations in long running transactions. This will cause skewed access for a selective set of keys in WT table.
- Relatively large number of read operation threads to stress cache.

WT-5235 Benchmark for lookaside stress testing

---

src/include/extern.h
src/support/modify.c
src/txn/txn_log.c

* WT-5247 Resizing modify operation log full values.
When modify operations resize part of a value, subsequent bytes are shuffled around and the operation is no longer idempotent.  Since WiredTiger's recovery can reapply operations that overlap with a checkpoint, it is not safe to log resizing modify operations.  Instead, log full update operations for that case.
(cherry picked from commit 9badd6c26c9b5f9e008913a271355cf99ba17952)

WT-5247 Resizing modify operation log full values. (#4977) [BACKPORT-v3.6]

---

src/conn/conn_dhandle.c
src/include/dhandle.h
src/meta/meta_ckpt.c
test/syscall/wt2336_base/base.run

Backports both WT-5042 and WT-5239.
The syscall test mentioned in #5009 still fails in 3.6 version.
JIRA: https://jira.mongodb.org/browse/BACKPORT-5645

WT-5042 Reduce configuration parsing overhead from checkpoints (#4936) #5009 [BACKPORT-v3.6]

---

src/include/hardware.h
src/reconcile/rec_visibility.c

Sue, Alex, Vamsi:
The problem in the original code is here:
```
105     if (upd->type == WT_UPDATE_BIRTHMARK) {
106         upd->type = WT_UPDATE_STANDARD;
107         upd->txnid = WT_TXN_ABORTED;
108     }
```
If the updates are written to memory in the above order, and a reader gets in between lines 106 and 107, a birthmark record can be read as a normal update because its type is `WT_UPDATE_STANDARD` and `upd.txnid` has yet to be set to `WT_TXN_ABORTED`.
I think it might be safe to merge the two `WT_PUBLISH` commands into something like this:
```
if (upd->type == WT_UPDATE_BIRTHMARK) {
append->txnid = upd->txnid;
append->start_ts = upd->start_ts;
append->durable_ts = upd->durable_ts;
append->next = upd->next;
upd->txnid = WT_TXN_ABORTED;
}
/* Append the new entry into the update list. …
```

WT-5119 Birthmark records can be read as normal updates if reads race with checkpoints.

---

src/btree/bt_cursor.c

* If the WT_SESSION.update leaf-page search returns either the first or last slot of the page,
discard the search results and search the entire tree, an inserted item might belong on an
entirely different page.
* If a search-near or update based leaf-page search returns an exact match, then we
should be able to use it, no matter what page slots are involved.
* Fix two cases where successful pinned page searches can result in attempting to modify
an object before starting the necessary implicit transaction: WT_SESSION.truncate and
WT_SESSION.update (with the WT_CURSTD_UPDATE_LOCAL flag set).
We haven't seen the failure in truncate before because a "read" of any page normally
results in starting the transaction, it's only pinned pages that avoid that operation,
and it's relatively unlikely …

WT-5277 Cursor key out-of-order detected in the lookaside file (#5018) [BACKPORT-v4.0]

---

test/evergreen.yml
test/format/format.sh

I updated the `format.sh` script to add a command line argument to run the timing stress split testing.
* The Jenkins test is [here](http://build.wiredtiger.com:8080/job/wiredtiger-test-race-condition-stress-sanitizer/)
* A successful patch build run over one hour is [here](https://evergreen.mongodb.com/version/5e12cb15a4cf47798eb0f30a)
* The 24-hour patch build is [here](https://evergreen.mongodb.com/build/wiredtiger_ubuntu1804_patch_d6ab08870356f990972e588c7be39fd9f396df8c_5e12ca6d0305b91a4325fe41_20_01_06_05_53_17)

WT-5003 Migrate wiredtiger-test-race-condition-stress-sanitizer from Jenkins to Evergreen

---

src/btree/bt_sync.c

(cherry picked from commit 5bd9fdfc0bb7f8fcf791e234b6e436c79dfe1fee)

WT-5192 Dont allow checkpoints to evict without a snapshot (#5104) [BACKPORT-v4.0]

---

test/suite/test_bug018.py

The error message occurs when a recovery fails due to the root page not being written.  This is a somewhat rare occurrence, so it's hard to verify the test is correct.  It's best to keep the test very simple for this case.

WT-4886 For bug018 test, don't depend on any particular error message text from WT

---

src/cache/cache_las.c

As it stands, we're clearly not writing any tombstones to the history store as the `type` parameter to this function can only ever be `WT_UPDATE_STANDARD` and `WT_UPDATE_MODIFY`.
I've just added an assertion to prevent regressions and will consider this ticket done.

WT-5281 Assert that we're no longer writing tombstones to the history store

---

test/suite/test_shared_cache01.py

@agorrod Vamsi assigned me this ticket to fix the test in durable history. However, I found it is disabled by you 7 years ago in develop. So I chose to fix it in develop instead.

WT-5442 Fix and reenable test_shared_cache_verbose

---

src/txn/txn_timestamp.c

Alex, I think this is a trivial cleanup, I can't see a reason the first `WT_PUBLISH` line in `__wt_txn_clear_read_timestamp()` is necessary, and having it there could be confusing.
However, I couldn't spot the reason the second `WT_PUBLISH` is necessary either: do you remember why it's necessary for `WT_TXN.clear_read_q` to be set before the `WT_TXN_PUBLIC_TS_READ` flag is cleared?

WT-5440 __wt_txn_clear_read_timestamp() has an unnecessary serialization point

---

src/support/mtx_rw.c

This change ensures that the value of `readers_queued` never overflows and reader has to wait for the next ticket in case there are already 255 readers in the system.

WT-5395 Fix a bug in the read lock implementation when there is a lot of contention

---

src/evict/evict_lru.c
src/txn/txn.c

This change works, but I'm unsure if it's correct. Specific questions:
* Should the check be wrapped in `!F_ISSET(txn, WT_TXN_HAS_SNAPSHOT)` or `txn->isolation == WT_ISO_READ_UNCOMMITTED || txn->isolation == WT_ISO_READ_COMMITTED` or something else?
* I don't understand why `txn_state->metadata_pinned` needs to be checked; my reading of the code indicates it shouldn't be blocking the oldest ID from moving forward permanently, but it does (and it does not move in lockstep with `txn_state->pinned_id`, they can have different values).
EDIT:
In commit a7e0242, I made the checks of `WT_TXN_STATE.pinned_id` and `WT_TXN_STATE.metadata_pinned` independent. As far as I can tell, they have no consistent relationship and either one can independently stall the system. Again, I need some guidance here …

WT-5366 read-committed and read-uncommitted transactions can stall eviction

---

src/reconcile/rec_visibility.c

this backports wt-5263
(cherry picked from commit 33204938da7bb1c0722536f9f74854ab59237e89)

WT-5263 Prepared updates written to the lookaside file are not always read as needed (#5039) [BACKPORT-v4.0]

---

test/evergreen.yml

Patch builds for Ubuntu 18.04 and RHEL 8.0:
- [Patch](https://evergreen.mongodb.com/version/5e27976ce3c33179485a1af4)
- [Another patch](https://evergreen.mongodb.com/version/5e27977532f41731210c0488)
- [And a third patch](https://evergreen.mongodb.com/version/5e27977f0ae6061d48939468)

WT-5460 Buffer alignment failure captured by linux-directio test

---

dist/s_clang-scan.diff
src/reconcile/rec_col.c
src/reconcile/rec_row.c
test/suite/test_hs09.py
test/suite/test_inmem01.py

The code is complex and I don't understand all of it. So please have a careful look.

WT-5448 Fix column reconciliation overwrites cells with default time pairs

---

test/evergreen.yml
test/format/config.c

Disable `data_source=lsm` setting in test/format configuration generation, and explicitly set & test LSM in a separate format stress sanitizer Evergreen task (run for 1 hour).

WT-5405 Make format LSM test a separate Evergreen task

---

bench/workgen/runner/runner/__init__.py
dist/s_python
lang/python/Makefile.am
lang/python/setup_pip.py
lang/python/wiredtiger.i
lang/python/wiredtiger/init.py

Tested with SWIG4 running with Python3 'in the tree'.  That is `cd build_posix; python3 ../test/suite/run.py ...` . Also tested it running with python2 'in the tree'.  Also did pip_setup.py (using python3, in case it matters), and was able to pip install/test the result in a python3 virtual env, as well as a python2 virtual env.
I made some of these tests with SWIG3.  That is, I can run python3 or python2 'in the tree'.  (These will be confirmed by the PR testing).  I did not check running pip_setup.py and pip install with SWIG3 .  The test matrix is getting too big.
If this works and passes review, I think we should merge, then upgrade all machines to SWIG4, and then deprecate SWIG3 and finally deprecate Python2.  We can deprecate in either order, but I think the SWIG3 deprecate will be …

WT-5159 Fixes to allow SWIG4 to generate code compatible with Python3 or Python2.

---

src/btree/bt_slvg.c

All the interesting work is in 2d560cd, the other two commits are just cleaning up comment formatting.
@agorrod, you're not going to like this much, but absent a real project to fix the problem, it's the only idea I have.
Can you please approve or disapprove the approach, before we do a real review?

WT-5437 salvage can  consume excessive amounts of cache memory, causing eviction to stall

---

src/reconcile/rec_visibility.c

When we select a tombstone in reconciliation, we append an update to the update list representing the on-disk value. Since it is in the in-memory update list, it needs to be taken into account as part of our cache usage calculation.
We're not suffering any ill effects from this. I just noticed it when scanning through the reconciliation code.

WT-5482 Increment cache usage when appending on-disk value to update list

---

test/evergreen.yml

Here we update the `linux-directio` Evergreen test to use the `format.sh` script rather than calling `t` in a loop. This allows us to run tests in parallel, virtually ensuring that we will accumulate completed test results even if we generate long-running configs. We set the `format.sh` timeout to just under the two hour default Evergreen timeout. We also set the build distros to higher spec machines for this task. Successful patch builds below.
- [Patch One](https://evergreen.mongodb.com/version/5e28e34be3c3314abdf82885)
- [Patch Two](https://evergreen.mongodb.com/version/5e28e35857e85a429c58768e)
- [Patch Three](https://evergreen.mongodb.com/version/5e28e3631e2d176633e47276)

WT-5458 Fix Evergreen timeout failures in linux-directio test

---

src/reconcile/rec_visibility.c

…ave a page dirty
This check originally did exist in the code but was removed as part of another change, I think it should be added as if all updates on a page are globally visible then we don't need to leave the page dirty.

WT-5484 Check visibility before saving updates for in memory reconciliation

---

src/history/hs.c
test/suite/test_hs06.py

As part of WT-5441, I noticed that we're unable to find keys in the history store due to a visibility issue.
To aid garbage collection, we're inserting tombstones after each lookaside insert to represent the stop timestamp of the value. When reading with a history store cursor, we use "read uncommitted" isolation which means that we will only see tombstones. In general, we're unable to even position the cursor since not even a single key in the history store table is visible to us.
The proposed solution is to open history store cursors from the user session (and therefore inherit their transaction id, timestamp and isolation level). When it comes to modifies, we'll have to do something interesting and repeatedly reset the read timestamp to be able to see subsequent keys.

WT-5464 Open reading history cursors on the user session

---

test/suite/test_hs06.py

This test was passing in WT-5464 so I reenabled it, but an interaction with something that got merged in that day must have caused it to begin failing.
I will be working on a fix but it's best to keep other branches green in the interim.

WT-5495 Disable hs06:test_hs_modify_reads

---

test/evergreen.yml
test/format/format.sh

Please see the output for the failed tests in the following patch builds:
- [Patch 1](https://evergreen.mongodb.com/version/5e3113043627e064c2aa21b6)
- [Patch 2](https://evergreen.mongodb.com/version/5e31131132f417502f3ebad3)

WT-5488 Evergreen test/format jobs need to report the failing CONFIG

---

src/include/txn.i

@agorrod, @bvpvamsikrishna, should we reconsider having `__ rec_append_orig_value()` change the underlying type of the `WT_UPDATE`?
I'm not familiar enough with the birthmark code to argue the point, but one of the rules we try to follow is that `WT_UPDATE` structures aren't modified once they're inserted into an update chain, and this chunk of code has been remarkably difficult to debug.

WT-5376 WT_UPDATE.type field can race with visibility checks when returning key/value pairs

---

src/reconcile/rec_visibility.c

If the selected update is a TOMBSTONE and it is not globally visible, use that timestamp as the durable timestamp.

WT-5420 use the stop timestamp as durable timestamp if exist

---

src/btree/bt_cursor.c

I'm still debugging one more issue that is affecting `test_hs06:test_hs_modify_reads` for row store which I'll commit in a separate PR.

WT-5495 For column store, check the on-page value and history store even if the key is in the insert list

---

dist/s_clang-scan.diff
src/reconcile/rec_visibility.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable01.py

TOMBSTONE with WT_TS_NONE and WT_TXN_NONE to remove an on-disk key
and to remove an on-disk key remove operation, the TOMBSTONE update
with WT_TS_MAX and WT_TXN_MAX is added.

WT-5419 Add a TOMBSTONE to update on-disk KV pairs

---

src/cursor/cur_backup.c
src/cursor/cur_backup_incr.c
src/meta/meta_ckpt.c

@keithbostic the incremental code was not handling older metadata configs. This change allows us to handle configurations that don't contain `checkpoint_backup_info` at all. I have checked out and confirmed `wt` can now run successfully on a database created in 3.2.1. (And fails with WT_NOTFOUND without this change.)

WT-5534 Handle the absence of checkpoint_backup_info in metadata.

---

test/csuite/Makefile.am
test/evergreen.yml
test/fops/Makefile.am
test/suite/test_compact01.py
test/suite/test_gc02.py
test/suite/test_hs01.py
test/suite/test_stat04.py
test/suite/test_txn02.py
test/suite/test_txn05.py
test/suite/test_txn09.py
test/thread/Makefile.am

I was going to enable `test_hs01` as per @luke-pearson's ticket but I realized that quite a few tests are now passing.

WT-5510 Enable more tests in durable history branch

---

examples/c/ex_backup_block.c
src/block/block_ckpt.c
src/meta/meta_ckpt.c

Also, in the example, if we have a short read, then only write what we
read.

WT-5537 Use correct WT_ITEM fields per memory sanitizer.

---

src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c
test/suite/test_backup08.py
test/suite/test_durable_ts01.py
test/suite/test_timestamp03.py

As writing always newest version to disk, after a successful
recovery, make sure that we rollback all the newer versions
more than the stable timestamp and perform a force checkpoint
to ensure that both in-memory and on-disk representation is
same.

WT-5426 Perform rollback to stable after recovery

---

src/cursor/cur_backup.c
test/suite/test_backup11.py

@ddanderson This is the identical code change, but adds the error test code to an existing Python test instead of creating a new file. Please review.

WT-5553 Return error if primary cursor is not an incremental source.

---

src/include/btree.i

Use proper enum macro to find out page type

WT-5557 The wrong page type is returned when checking the on-page cell.

---

test/suite/test_cursor13.py

Skipped a few tests that do not work with history store, we'll need to fix these separately.
Removed a stray call to breakpoint.

Fixed cursor caching test to work with durable history, which now uses cached cursors for the history store.

---

src/conn/conn_api.c
src/include/extern.h
src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable01.py
test/suite/test_rollback_to_stable02.py
test/suite/test_rollback_to_stable03.py

When a page gets reconciled, its updates in the update list may have
been inserted into the history store, whenever we are aborting those
updates, the updates in the history store also needs to be removed.

WT-5422 remove history store updates

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable01.py
test/suite/test_rollback_to_stable03.py
test/suite/test_rollback_to_stable04.py

I added code to the `__txn_abort_row_replace_with_hs_value` function in `txn/txn_rollback_to_stable.c` so that if the stable timestamp corresponds to a modify value in the history store, the value is converted to a full update. This functionality is tested in `test_rollback_to_stable04.py`.

WT-5423: Convert a history store modified value into a full update

---

lang/python/wiredtiger.i
test/suite/test_stat08.py

@ddanderson Please review this small test change. In particular, do you know if my supposition that some Windows systems lack usec granularity? I recall that from a while ago but, well, it was a while ago and I'm far from expert on anything Windows.

WT-5371 Skip usec time check on Windows.

---

test/suite/test_durable_ts01.py

In first version of durable history, this test was modified
to expect latest value after restart and which was wrong
according to the stable timestamp.

WT-5575 Revert the test modification that was wrong

---

dist/s_string.ok
src/btree/bt_ret.c
src/btree/bt_vrfy.c
src/history/hs.c
src/include/cell.i
src/include/txn.i
src/support/modify.c

@keithbostic This should be quick. I fixed the various complaints from s_string.
Notably however, I added `LAS` back to s_string.ok because it is used in `NEWS` in the check-in message for a release.

WT-5590 Fix s_string failures.

---

src/cache/cache_las.c

Sweep server should periodically clean the LAS obsolete
entries when there as any tables are dropped or if the LAS
not empty. Fix the check that leads to not to remove the
obsolete entries when there are no tables dropped.
(cherry picked from commit a74b4299f9cd5701c580cae502a3f81585a4d89f)

WT-5150 Fix the check to find out whethere LAS is empty (#4908)

---

src/btree/bt_vrfy.c
src/include/txn.i

This PR aims to fix the current verify bug that happens upon startup of database. Talked with @tetsuo-cpp and @sulabhM, and reached a consensus that we will stop verifying the start transaction ID from the data store for now.

WT-5563 Transactions ID are getting wiped which causes errors in WT Verify

---

src/evict/evict_lru.c
test/csuite/Makefile.am
test/evergreen.yml

In case there is only one eviction thread, eviction server will also evicit
pages. Clear the WT_SESSION_LOCKED_PASS flag before it starts to do that.

WT-5565 Clear WT_SESSION_LOCKED_PASS before eviction server starts to evict pages

---

src/schema/schema_create.c
src/txn/txn_ckpt.c
test/suite/test_prepare07.py
test/suite/test_schema08.py
test/suite/test_txn04.py

Fix the scenarios where the history store file doesn't
exist in metadata during recovery.

WT-5597 Fix the history store file access during recovery

---

src/btree/bt_vrfy.c

When the while loop finishes, ret is going to be WT_ERR_NOTFOUND, which is expected behaviour and totally cool!
I removed this code after a comment from @tetsuo-cpp  and managed to overlook this. Sorry about that!

WT-5607 Verify history store fix

---

src/reconcile/rec_write.c

For the fixed-length column store, we unset `WT_REC_HS`. Therefore, this condition needs to be part of the assertion.

WT-5610 Fix assertion for reconciling fixed length column store

---

src/reconcile/rec_write.c

The problem is I misunderstood WT_TRET macro in WT-5320. We should not continue reconciliation if ret is not zero.

WT-5603 Should not continue in-memory reconciliation if there are failures

---

src/reconcile/rec_visibility.c
src/reconcile/rec_write.c

I kept hitting this when running `test/format` for a fixed-length column store configuration. The change is along the same lines as #5278.

WT-5633 Fix another assertion for reconciling fixed length column store

---

src/session/session_dhandle.c

When choosing which dhandles should be swept, we should also sweep the dhandle's that are already evicted. This PR aims to add that functionality when sweeping dhandles.

WT-4458 Only sweep btree handles that have been evicted from cache

---

src/btree/bt_discard.c
src/btree/bt_split.c
src/include/btree.i
src/include/extern.h
src/reconcile/rec_write.c

@agorrod, here's the change to protect callers of `__wt_ref_addr_free()` (including those calling it through `__wt_ref_block_free()`).
The 706444e commit is the change for `__split_parent()`, the 2dec2f9 commit is a change for checkpoint reconciliation.
It feels to me like the reconciliation commit shouldn't be necessary, and I've not been able to make it actually happen in a test, but I can't think of any reason it's safe.
The other uses of these functions are safe as far as I can tell.
Can you please choose someone to do the review?
This is only lightly tested, the develop branch can't handle the level of stress required to test this change. Maybe we should let this change sit until testing is possible?

WT-5552 Checkpoint reconciliation and page splits free the WT_REF.addr field without locking

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable01.py
test/suite/test_rollback_to_stable02.py
test/suite/test_rollback_to_stable03.py
test/suite/test_rollback_to_stable04.py
test/suite/test_rollback_to_stable05.py

As part of rollback to stable ignore performing rollback to stable operation on files that don't exist and also avoid performing the checkpoint and history store search when in in_memory configuration mode

WT-5628 Don't perform rollback to stable on files that don't exist

---

src/btree/bt_sync.c

@agorrod, see a more detailed discussion in the JIRA ticket.
I have no opinion on whether or not it's actually a problem if the page is dirtied after taking a reference to the (presumably NULL) page modify structure during a checkpoint, but the commit in WT-2204 makes me think it was believed to be a problem at that time (November, 2015).

WT-5650 A race is possible between reading the WT_PAGE.modify field and the page being dirtied.

---

src/reconcile/rec_write.c

Thanks @hbokhari for the tip of running `evict-btree-hs.py`. That makes debug much easier.
The problem in this case is we did some unnecessary work when checkpoint has nothing to write but still have some updates saved because they are not visible. We never write that empty page to disk but the extra work makes its parent page to think it has a child which actually does not exist.

WT-5593 Reconcilation is done for checkpoint if it has no more entries left to write

---

src/reconcile/rec_visibility.c

By design any update going to history store is committed. This means that the history store pages can be assumed to be clean after reconciliation.

WT-5638 Ignore checking visibility of history store updates as they are implicitly committed.

---

src/cursor/cur_backup.c

Removed the condition to check if `blk != NULL` as `blk` has already been dereferenced before NULL-checking.

WT-5236 Coverity issues in cur_backup

---

src/btree/bt_handle.c
src/btree/bt_read.c
src/evict/evict_page.c
src/include/extern.h

If we delete a chunk of the name space and evict the page, we can migrate that change up the tree, eventually deleting and evicting internal nodes, setting and internal node's `WT_REF.state` to `WT_REF_DELETED`.
If we're ever forced to re-instantiate that chunk of the name space, it's re-instantiated as a leaf page, not a subtree with both internal and leaf pages.
I see two places to flip the `WT_REF` type from an internal page to a leaf page: when we delete the internal node, or when we re-instantiate the page. I did it in the first one in commit 9020de7, when we delete the internal node because it was a simpler change, but I changed my mind and did it in the second one in commit cafee99, because that matches current practice and so I think it's less likely to cause more breakage.

WT-5666 Deleting a chunk of the namespace changes the WT_REF type

---

src/history/hs.c
test/suite/test_inmem01.py

As part of #5295, I noticed infrequent infinite looping behavior in the positioning of the history store cursor. This is because we're comparing the embedded data store key and using this to infer something about our position in the history store which we know is not allowed.
Consider a case where we have string keys 9, 10 and 11 in the history store. Since strings are encoded with a length prefix, the history store order will be 9, 10, 11. Whereas the data store order will be 10, 11, 9 as it will be sorted alphabetically. So you can imagine a case where we search for the key 10 (which doesn't exist) and position ourselves at the beginning of the entries for 11. When we realize that we have overshot and try to go back to the previous entry, we'll land on 9 (which is lexicographically …

WT-5678 Fix infinite looping behaviour in history store cursor positioning

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable01.py
test/suite/test_rollback_to_stable02.py
test/suite/test_rollback_to_stable03.py
test/suite/test_rollback_to_stable04.py
test/suite/test_rollback_to_stable05.py
test/suite/test_rollback_to_stable06.py
test/suite/test_rollback_to_stable07.py
test/suite/test_rollback_to_stable08.py
test/suite/test_rollback_to_stable09.py

Along with test, a fix to perform history store cleanup from a reconciled page only when the reconciled page has updates greater than the stable timestamp.

WT-5427 Rollback to stable tests

---

src/btree/bt_compact.c
src/btree/bt_debug.c
src/btree/bt_delete.c
src/btree/bt_discard.c
src/btree/bt_handle.c
src/btree/bt_misc.c
src/btree/bt_page.c
src/btree/bt_random.c
src/btree/bt_read.c
src/btree/bt_rebalance.c
src/btree/bt_slvg.c
src/btree/bt_split.c
src/btree/bt_sync.c
src/btree/bt_vrfy.c
src/btree/bt_walk.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/evict/evict_stat.c
src/include/btmem.h
src/include/btree.i
src/include/extern.h
src/include/txn.i
src/reconcile/rec_child.c
src/txn/txn_rollback_to_stable.c

@agorrod, this is the change that removes the `WT_REF.WT_REF_READiNG` state.
As you know, I like this change because it simplifies the `WT_REF` locking protocol a bit, because we only ever care about the `WT_REF_LOCKED` state for the purposes of thread serialization.
I know you see this work a bit differently than I do, so wanted to give you a chance to see the actual change and kill it if you want to go a different direction.
If you're OK with this change, let me know and I'll find a reviewer.

WT-5647 replace the WT_REF structure's WT_REF_READING state with a flag

---

src/btree/bt_cursor.c

@sulabhM, this change went in as part of WT-5256, [here's the commit ](https://github.com/wiredtiger/wiredtiger/commit/1ccc9203409a7032250a4547495a0c098723b8ee).
Assuming your change was correct, I think we can just simplify the whole thing?

WT-5689 reduce work required for the cursor-pinned test.

---

NEWS
dist/s_string
dist/s_string.ok
src/include/txn.i
src/log/log.c

Switch the dictionary `aspell` uses to check and replace spelling from `en` (English) to `en_US` (American English), and address spelling issues detected by the dictionary switch.
I put `signalled` into the ok list as it's already been widely used in the source code (both comments and variable names).

WT-5685 Set aspell dictionary to en_US

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable02.py

As part of rollback to stable process, it aborts the updates in the
order of update list, on page and reconciled page. As part of one page
value correction once the history updates are removed, don't remove
the visible updates again as part of processing reconciled page if the
newer version of the key is stable.

WT-5690 Skip removing update from hs when its newer version is stable

---

src/btree/bt_compact.c
src/btree/bt_misc.c
src/btree/bt_split.c
src/btree/bt_vrfy.c
src/btree/bt_walk.c
src/include/btree.i
src/include/extern.h

Below tickets (which had been vendor-ed into mongo v4.2) will be reverted on `mongodb-4.2` branch, and later vendor-ed into mongo v4.2. 
- WT-5219
- WT-5481
- WT-5489
- WT-5557

WT-5219 Reverting WT-5219 and friends on mongodb-4.2

---

src/include/btmem.h

Given the access pattern for the history-store file, I think we might want to turn off prefix compression.

WT-5636 prefix compression is slow in the history-store access pattern

---

test/csuite/Makefile.am

I have temporarily disabled the test(test_wt4105_large_doc_small_upd) because the modify operation in this test takes around 15 seconds. 
I have created a ticket [WT-5693](https://jira.mongodb.org/browse/WT-5693) to enable the test later.

WT-5579 Evergreen memory sanitizer test failure

---

src/txn/txn_recover.c
test/suite/test_durable_rollback_to_stable.py

Since we were clearing the stable timestamp after recovery, `wt` would complain when using the `-s` option since there would be no stable timestamp to compare against. There doesn't seem to be a compelling reason to clear it so the easiest fix is just to remove this logic.

WT-5713 Don't clear the stable timestamp after recovery

---

src/include/meta.h
src/utilities/util_list.c
test/suite/test_util11.py

Both metadata and history store files are created as part of Wiredtiger
connection open and they are not an application/user objects in the
database. Currently metadata is not listed as part of the WT utility
list, apply the same for the history store file also.

WT-5712 Treat history store file as internal file like metadata

---

test/suite/test_txn07.py

A test case was checking statistics after runWt, which closes
the connection, which led to using the wrong stats. That check
was re-ordered (along with other changes), after which some automate
testing started hanging. Revert that bit of the change to see if is
the cause.

WT-5692 Revert a test change hoping to fix a Python hang

---

src/cursor/cur_backup.c
src/docs/backup.dox
src/include/extern.h
src/schema/schema_util.c
src/txn/txn_ckpt.c
test/suite/test_backup11.py
test/suite/test_backup12.py

@ddanderson and @keitharnoldsmith given yesterday's discussion about namespaces I have implemented changes to apply the same naming restrictions and checks to backup identifiers as we do to other names.

WT-5722 Add standard name checks to incremental backup identifiers.

---

src/include/txn.i

These changes would fix memory leak during the overflow page read (pasted the call stack below). 
Evergreen link [[here](https://evergreen.mongodb.com/task/wiredtiger_ubuntu1804_format_stress_sanitizer_smoke_test_patch_fa51dc8d84fb621ef6a3f92c0117a55fa16cbb34_5e5d96d661837d088fad3f45_20_03_02_23_29_48)]
`#1 0x7f3ebab6881d in __realloc_func /data/mci/eec7f4b32cfd8eff50bd6eb953fb8a61/wiredtiger/build_posix/../src/os_common/os_alloc.c:141:14
#2 0x7f3ebab689a0 in __wt_realloc_noclear /data/mci/eec7f4b32cfd8eff50bd6eb953fb8a61/wiredtiger/build_posix/../src/os_common/os_alloc.c:180:13
#3 0x7f3ebad0bc5e in __wt_buf_grow_worker /data/mci/eec7f4b32cfd8eff50bd6eb953fb8a61/wiredtiger/build_posix/../src/support/scratch.c:54:19
#4 0x7f3eba73b51f in __wt_buf_grow …

WT-5688 Memory leak during page overflow read

---

test/suite/test_timestamp10.py

Based on connection level logging enabled/disabled, the immediate durability
of the table is getting changed. Currently WT, doesn't save the configuration
in most of the scenarios, so make sure to use the same configuratio in the
entire test to let the behaviour of the tables same across the test.

WT-5631 Make sure to follow same connection config in the entire test

---

src/btree/bt_ret.c
src/history/hs.c
test/suite/test_bug022.py

I wasn't able to hit the condition where we apply modifies on top of an on-page value with a set time pair (I get `WT_NOTFOUND` when trying to modify). After chatting with @michaelcahill, we think that this case shouldn't be possible and may have existed from when the rules around modifies were laxer.

WT-5682 Ensure that we can't apply modifies on top of tombstones

---

src/history/hs.c
src/reconcile/rec_visibility.c

We don't expect operations to use timestamps out-of-order, but at least some MongoDB tests do.  Until we figure out whether those tests can be changed to avoid the out-of-order operations (e.g., by inserting rollback_to_stable in between timestamp reuse), deal with out-of-order timestamps rather than asserting.

WT-5747 Cope with out-of-order timestamps.

---

src/evict/evict_page.c
src/include/reconcile.h
src/reconcile/rec_row.c
src/reconcile/rec_visibility.c

When a remove becomes stable, stop writing keys even if some history is saved.  Then when a page becomes empty, it won't have any content and will have a NULL address.  These pages should be evicted into the DELETED state.  There was left over code for LIMBO pages (where a page could be empty in a checkpoint but have relevant history): this commit removes that code.

WT-5680 On evicting an empty page, mark it DELETED not DISK

---

test/suite/test_hs10.py

Don't wrap the updates that are supposed to flush the cache into a
single transaction.

WT-5762 Make test_hs10 more robust

---

src/btree/row_modify.c

We copy some garbage data from cursor when we allocate update for reserve. Similar problem to WT-5745. I don't know why this is not failing before durable history. @michaelcahill

WT-5756 Don't copy data from cursor for reserve update

---

src/btree/bt_compact.c
src/btree/bt_debug.c
src/btree/bt_delete.c
src/btree/bt_handle.c
src/btree/bt_misc.c
src/btree/bt_read.c
src/btree/bt_sync.c
src/btree/bt_vrfy.c
src/include/btmem.h
src/include/btree.i
src/include/extern.h
src/include/misc.h
src/include/txn.i
src/include/wt_internal.h
src/reconcile/rec_write.c
src/support/hazard.c

@kommiharibabu, @tetsuo-cpp: here are some changes to fix problems with looking at the `WT_REF.addr` fields.
In summary, it's not safe look at `WT_REF.addr` (including the associated timestamps), unless we know they won't change underfoot, and that means we either lock them somehow or ensure that checkpoint & eviction are both ignoring the `WT_REF` when we're looking at them.
I tried to come up with some kind of locking scheme, but failed -- we just touch those fields all over the place, and most of the time it's fine, I believe it's just compaction and checkpoint-sync we have to worry about. I'm a little worried about fast-truncate, too, but I didn't spot any problems.
Let me know if you see an approach that leads to a locking solution, I'm happy to back off from this change if there's a …

WT-5649 Refactor WT_REF locking, review all WT_REF.addr reads for locking issues

---

src/btree/bt_debug.c
src/history/hs.c
src/include/btmem.h
src/txn/txn_rollback_to_stable.c

This PR is reserving some extra space in the history store schema to future proof our decision and allow us to add more things if need be. We've decided on extending the `update_type` to 8 bytes. We can then tack on extra data to the `value` buffer and set bit flags on the `update_type` to determine how to interpret it.

WT-5654 Reserve extra space in history store format for future schema changes

---

test/evergreen.yml

Hopefully, this change could make finding stress tasks and triaging test failures easier.

WT-5774 Move stress test tasks into a separate build variant

---

src/reconcile/rec_row.c
src/txn/txn_rollback_to_stable.c

Currently, the value cell doesn't store the durable timestamp and when a page
is getting reconciled again with no newer updates on the page to be considered,
the aggregated durable timestamp is calculated as zero. This gets fixed when
the value cell has durable timestamp, till then consider the commit timestamp
instead of zero.

WT-5696 Reconciliation use commit timestamp of cell as durable timestamp

---

src/reconcile/rec_visibility.c

This is another case where operations out of timestamp order can current cause an assertion.  Handle the situation instead (here by ignoring an on-page value that can never be read, rather than copying it into the update list).

WT-5701 If an out-of-order update masks an on-disk value, don't append it.

---

src/btree/bt_misc.c

Memset the `tmp` variable to 0 with `WT_CLEAR`.

WT-5615 Coverity-Read of uninitialised value

---

src/history/hs.c

@michaelcahill you were right - the assertion fired. Let's revert for now - I expect we can encounter the situation after an aborted reconciliation in the least.

WT-5795 Disable assertion that inserts to the history store are unique

---

src/session/session_api.c
src/utilities/util_dump.c

Dump and verify have been broken since we made it such that only rollback to stable can ignore history store tombstones. I've updated dump and verify to use these flags.
I've mostly tested manually by adding assertions around our `search_near` to ensure that we get `WT_NOTFOUND` before my fix and `0` after.

WT-5792 Dump and verify can't see the history store

---

src/include/hardware.h
src/reconcile/rec_visibility.c

* We need to make sure the WT_UPDATE txnid is set to WT_TXN_ABORTED before the type is switched to
WT_UPDATE_STANDARD, otherwise a read can race with the update and read the birthmark record as a
normal update.
* The most conservative version of this fix, committed for discussion.
Add/Use a WT_ORDERED_WRITE macro, currently synonymous with WT_PUBLISH.
(cherry picked from commit e3cbe6dc8dfb3e39fc014ac32e6192d7fe469677)

WT-5119 Birthmark records can be read as normal updates if reads race with checkpoints. (#5082) [Backport to 4.0]

---

src/block/block_open.c

I've been thinking of a way to generalize this solution to detect changes to file size but I'm not sure how. When we checkpoint, we record the file size. However, if we evict dirty pages after a checkpoint, the data file should grow larger. And if we compact, I believe it may shrink. So I don't think I have any way of using the checkpoint size to check the file size.

WT-5786 Detect if a file is too small to read a descriptor block

---

src/txn/txn_recover.c

If there is no history store file, we should skip performing rollback to stable and the recovery checkpoint. This situation gets triggered when we're upgrading from 4.2 so we can't do anything sensible in recovery.

WT-5789 Check that the history store file exists before performing rollback to stable

---

test/csuite/incr_backup/main.c

Remove an assertion from an unreachable case branch.  Coverity flagged this as dead code.
Made identical change in second, similar switch statement, which Coverity didn't (couldn't) flag as dead code, just to keep things symmetrical.

WT-5733 Remove asserts from unreachable case statements to please covert

---

src/block/block_open.c

We recently made a change in WT-5786 to return `ENOENT` if we found files that are too small to contain a descriptor block in order for WiredTiger to get past rollback to stable and start properly so that MongoDB can run verify/salvage on a database.
There's been some fallout in `wt_corrupt_file_errors.js` since MongoDB is quite specific about what error codes it gets back from WiredTiger and reacts differently on each one. We should maybe negotiate with server to agree on what each value means, but for the time being we should mimic what we were returning before to get the patch closer to green.

WT-5844 Adjust error codes for when we detect files that are too small to contain a descriptor block

---

src/os_posix/os_fallocate.c

The MacOS build has been complaining about an unused macro since #5155 went in. I've just added a preprocessor conditional to define the macro only when we end up actually using it.
I came across this in my triage baroning but figured I'd make a fix since I already know what it is. I've run a patch build on Ubuntu, RHEL, Windows and MacOS to confirm that this compiles everywhere.

WT-5862 Add conditional around macro definition

---

src/reconcile/rec_write.c

A previous attempt to fix this mixed up WT_TXN_GLOBAL.checkpoint_id (an increasing integer that represents the checkpoint generation) with WT_TXN_GLOBAL.checkpoint_state.id (the checkpoint transaction ID).

WT-5879 Fix a bug reconciling metadata.

---

src/txn/txn.c
src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c

Additional verbose messages are added in the code flow of
rollback to stable that are useful for debugging.

WT-5885 Additional rollback to stable verbose messages

---

src/btree/bt_page.c
src/include/cell.h
src/include/cell.i
src/include/extern.h
src/include/reconcile.i
src/meta/meta_ckpt.c
src/reconcile/rec_col.c
src/reconcile/rec_write.c

@ddanderson, I was looking at WT-5669 with @agorrod today, and was wondering if it might make sense to only port the `cell.h` and `cell.i` code from 4.4, that is, don't try and backport the timestamp work, just make 4.2 use the current 4.4 cell code.
I've pushed a branch to show what I'm thinking. Can you take a look and then we can talk about which you prefer? Or if I'm totally missing something?

WT-5669 Prepare support with durable history: backport data format changes to 4.2

---

src/txn/txn_recover.c

This PR is fixing an issue seen in `logkeeper` where there is a code path where we still attempt rollback to stable even without a history store file (i.e. when upgrading from `v4.2`).
This was caused by a bit of a boneheaded error on my part. There's a `goto` above my initial fix that jumps straight to the rollback to stable code if there were no log files found and `hs_exists` is left as `true`. I've moved this check right after the opening of the cursor so we should be safe.
I've verified that `unionWith_fcv.js` still passes with this iteration of the fix.

WT-5896 Recovery sometimes attempts rollback to stable with an absent history store file

---

src/include/cell.i

As we are storing the differences in the value cell from durable
timestamp to commit timestamp, there is no need to save when there
is no difference. When unpacking the cell, assign commit timestamp
to durable timestamp when there is no durable timestamp in the cell.

WT-5894 Don't persist durable timestamp if it is same as commit

---

test/evergreen/compatibility_test_for_mongodb_releases.sh

@lukech, a new version of the release compatibility test script for your consideration.
Note: that this script needs to be updated once there's a 4.2 tagged release that can handle the current 4.4 disk format.
Also note: because the test runs `format` to create variable- and fixed-length column store tables, running this version of the test in Evergreen is going to make the test go red. (cc: @agorrod)

WT-5901 Evergreen release compatibility testing isn't working as intended.

---

test/csuite/wt4333_handle_locks/main.c

Checkpoint cursors are known to be broken as of durable history. This particular visibility issue seems to only happen with checkpoint cursors so let's disable this part of the test temporarily.
If we see visibility issues crop up even with regular cursors, then we can investigate further.

WT-5891 Disable testing of checkpoint cursors in wt4333_handle_locks

---

src/reconcile/rec_col.c
src/reconcile/rec_row.c

@tetsuo-cpp, @luke-pearson, the interesting change is add2f98, 25881fb is just code shuffling.
@bvpvamsikrishna, this change clears the timestamps from salvaged rows, rather than discarding them from the salvaged page because salvage doesn't currently support per-row salvage, we'd have to discard the whole page to discard a single row with a non-max time pair. (Or, rework salvage, I guess, but I'm not too excited about doing that right now.)

WT-5828 reconciliation discards salvaged overflow blocks with stop time pairs

---

src/txn/txn_rollback_to_stable.c

Scenarios when the trees are not checkpointed at once, it is possible
that durable timestamp of that tree can be zero, because of this reason
the trees are treated as non-timestamped tables and lead them to clean
their history store. To avoid this problem, ignore history store cleanup
when the trees are modified.
The side affect of this change is that it doesn't perform the history store
cleanup for the non-timestamped tables also that are modified, but anyway
these tables gets cleaned during recovery rollback to stable phase.

WT-5923 Avoid performing history store cleanup for modified trees

---

bench/wtperf/runners/wtperf_xray.sh

Check the return code instead of call to `objdump`. I'm fairly sure I tested this so I think this may have happened because I was testing on MacOS where `llvm-objdump` is used by default.

WT-5921 Fix wtperf_xray to detect builds that haven't been instrumented with XRay

---

src/docs/devdoc-xray.dox

This PR separates out the instructions for instrumenting with XRay and building `xray_to_optrack` since these require different and very specific configuration flags.
I also did a bit of cleanup and added some detail where appropriate.

WT-5922 Separate out XRay and xray_to_optrack build instructions

---

src/txn/txn_rollback_to_stable.c

Don't check the on-disk key/value when there is a valid update in update list
When the page was processed once for the rollback to stable and valid value is
restored from the history store and added to update list. Once again the page
is getting processed for rollback to stable, it must not process the on-disk
key/value again as it can lead to remove of the key.

WT-5931 Recovery rollback to stable is leading to remove a record that is not expected

---

test/evergreen.yml

Setting the env flag `TESTUTIL_SLOW_MACHINE=1` keeps certain time sensitive tests from running.

WT-5811 For evergreen runs, mark ASAN tests as running on a slow machine.

---

test/csuite/wt2853_perf/main.c

Show any slow performance "gaps", but only fail if there is a much
bigger gap. We intend to set the MAX_GAP parameter back down eventually.

WT-5944 Relax test csuite parameters for wt2853_perf.

---

src/txn/txn_rollback_to_stable.c

While aborting the updates that are more than the stable timestamp,
if it found any update that is not aborted even with the timestamp
of WT_TS_NONE, consider it as a vaid update.

WT-5943 Consider all non aborted updates as valid

---

src/btree/bt_split.c

In __split_multi_inmem_final, I suspect we no longer have exclusive access to the page. In that case, we
cannot free the updates moved to data store and history store as we may race
with the application threads. @keithbostic Can you confirm that we don't have exclusive access to the page in __split_multi_inmem_final?

WT-5952 Fix freeing updates racing with application threads

---

examples/c/ex_backup.c
src/docs/durability.dox
src/include/wiredtiger.in

Add documentation of WT_SESSION::truncate behavior when called on a backup_cursor.
In addition to WT_SESSION::truncate, updated description in the "Log file archival" section
of the "Commit-level durability" page. 
Possible issue:  Is the description of the `start` parameter confusing? It's generally optional, but mandatory for the backup cursor use case.

WT 5357 WT_SESSION.truncate of a log cursor isn't documented

---

src/btree/bt_debug.c
src/btree/bt_vrfy.c
src/history/hs.c
src/include/extern.h

@luke-pearson, @sulabhM, Jeremy Tay did the original work and you were the reviewers; of course, please turf the review elsewhere if that's appropriate.
I haven't tested if this change fixes the timeouts in Evergreen tests, but the speedup is more than 100x, and is roughly the speed of verify in previous releases.
The 903469b commit is the interesting one, and 1c4b3cc adds some minor additional changes (the other commits are code shuffling).

WT-5796 Speed up verification of file's associated history store information.

---

src/btree/bt_vrfy.c

In `__wt_verify`, if the write generation on the checkpoint is less than or equal to the `base_write_gen` on the connection, we should set the parent cell `addr_unpack.oldest_start_txn` to 0.

WT-5961 Respect write generations when constructing the root addr

---

src/include/txn.i

As part of rollback to stable operations, any updates that are needs
to be removed, rollback to stable adds globally visible updates to
both data and history store. Search is not ignoring these updates
for the data store, but whereas these are getting ignored for history
store when session is requested to ignore the tombstones of the
history store, but globally visible tombstone updates shouldn't be
ignored for hs irrespective of the session flags.

WT-5948 Search shouldn't ignore globally visible tombstones

---

dist/s_string.ok
test/evergreen/compatibility_test_for_mongodb_releases.sh
test/format/config.c
test/format/format.h
test/format/t.c
test/format/wts.c

@tetsuo-cpp, @agorrod, here are a set of changes that allow you to run format to create a database and then you can run the 4.2 wt command to verify it, so it's easier to do local testing.
I've updated the evergreen test, but if you want to run this locally, use "./t -B" to create the database in the develop branch, so it's backward compatible with 4.2, and of course you need a 4.2 branch with at  least WT-5894 applied to verify that 4.2 can read the develop database cell format.

WT-5979 Add Evergreen release compatibility test for forward compatibility

---

src/btree/bt_vrfy.c
src/btree/bt_vrfy_dsk.c
src/include/cell.i
src/meta/meta_ckpt.c

@agorrod, @tetsuo-cpp, this is the set of changes that I needed to get current develop branch row-store databases to read in a mongodb-4.2 branch. Basically,  it's a cherry-pick of WT-5894's changes to the cell code, and then removing validation of address and checkpoint durable timestamps. (I was able to get those tests to pass, but it required sufficient changes that I thought it was more destructive than helpful.)
I haven't run this against the failing Evergreen tests.
Anyway, it's an alternative approach to #5478.

WT-5934 Stop validating timestamps read from disk in 4.2

---

src/block/block_ext.c
src/btree/bt_vrfy_dsk.c
src/include/btmem.h
src/include/connection.h
src/reconcile/rec_write.c

@agorrod, as you know, we updated the on-disk page header to include a version number in the 4.2 release. The version number was removed in the 4.4 release, and I'm not sure if that change was deliberate or not?
We don't strictly need this change because (as far as I know), we never wrote non-zero versions into customer databases, and we do not yet use the page header version in the 4.4 release (the cell code uses the fact that the "interesting" timestamps are never set to detect 4.4 created tombstones).
However, this change was never backported into 4.2, so it's writing a "version" that happens to be 0 and so matches the zero'd out bytes on the disk the 4.4 release expects.
If the change to remove the page-header version was deliberate, this PR can be almost entirely discarded (we should …

WT-5993 restore disk page header version

---

src/log/log_slot.c
src/txn/txn_rollback_to_stable.c

As the log server didn't get started until end of recovery, any log
records that are written during recovery can block. To avoid it, ensure
that all log records written during recovery are unbuffered to let them
write directly.

WT-5988 Do not write log records as part of recovery rollback to stable operation

---

test/evergreen.yml

This test fails with TEST TIMED OUT error because of the performance degradation after 'pm-1521-durable-history' branch merge to develop. 
So, closing this ticket by reducing the number of test runs and wait for the resolution of performance degradation ticket [WT-5929](https://jira.mongodb.org/browse/WT-5929).
Successful evergreen patch builds with 8 binaries. 
https://evergreen.mongodb.com/task/wiredtiger_ubuntu1804_stress_tests_checkpoint_stress_test_patch_ddc71be625083937af2e6858f25e6bcc16f9885d_5e927384850e615c287a474c_20_04_12_01_49_17

WT-5825 Timeout failure in checkpoint-stress-test

---

bench/workgen/runner/compress_ratio.py
bench/workgen/runner/evict-btree-lookaside.py
bench/workgen/runner/example_simple.py
bench/workgen/runner/example_txn.py
bench/workgen/runner/insert_stress.py
bench/workgen/runner/insert_test.py
bench/workgen/runner/maintain_low_dirty_cache.py
bench/workgen/runner/multi_btree_heavy_stress.py
bench/workgen/runner/read_write_storms.py
bench/workgen/runner/read_write_sync_long.py
bench/workgen/runner/read_write_sync_short.py
bench/workgen/runner/runner/__init__.py
bench/workgen/runner/small_btree.py
bench/workgen/runner/small_btree_reopen.py
bench/workgen/runner/split_stress.py
bench/workgen/workgen.swig
bench/workgen/wtperf.py

Relatively clean cherry-pick of c8116016de0f93931f5275ec65de3c9418d3c0a8. One of the workgen runners didn't exist in `mongodb-4.2` so I discarded those changes.

WT-5989 Support arguments in workgen (v4.2 backport)

---

src/btree/bt_cursor.c
src/btree/bt_read.c
src/btree/bt_sync.c
src/conn/conn_api.c
src/cursor/cur_join.c
src/cursor/cur_std.c
src/evict/evict_lru.c
src/history/hs.c
src/include/api.h
src/include/btree.i
src/include/session.h
src/include/time.i
src/include/txn.h
src/include/txn.i
src/lsm/lsm_cursor.c
src/lsm/lsm_work_unit.c
src/meta/meta_track.c
src/reconcile/rec_write.c
src/schema/schema_util.c
src/session/session_api.c
src/txn/txn.c
src/txn/txn_ckpt.c
src/txn/txn_ext.c
src/txn/txn_log.c
src/txn/txn_timestamp.c

@tetsuo-cpp, as anticipated, your changes in WT-5766 make this a much simpler change. (It was easier to re-create the branch than to bring the old branch forward, so it's a new PR.)

WT-5968 Allocate the WT_TXN structure when activating the WT_SESSION 

---

test/format/backup.c
test/format/bulk.c
test/format/checkpoint.c
test/format/config.h
test/format/format.h
test/format/format.i
test/format/ops.c
test/format/t.c
test/format/util.c

This change replaces calls to pthread reader-write locks with an abstract lock that can be
implemented with either the pthread locks or with WT's faster locks.  The lock type can be
specified (or selected at random) via a new config parameter (`wiredtiger.fast_mutex`).
WT's locks require a `WT_SESSION`.  There are a few changes that were required to ensure that we (mostly) have a one when we use a lock:
- Locks are initialized and torn down each time we call `operations()` instead of just once in `main()`. 
- The timestamp thread opens its own session just to have a one when it uses the timestamp lock.
- There are two cases where we might access a lock outside of `operations()` --- during failure handling and during bulk load. In those cases we now check whether the locks are initialized …

WT-4701 Switch test/format to use WiredTiger locking primitives

---

src/txn/txn_rollback_to_stable.c

Hari, staring at the rollback-to-stable code, it seems to me like we could lose data if rollback-to-stable fails and then we checkpoint. In other words, it seems like:
```
rollback-to-stable -- fails
rollback-to-stable -- fails
rollback-to-stable -- succeeds
checkpoint
```
should be safe and work correctly, but I don't think that:
```
rollback-to-stable -- fails
checkpoint
rollback-to-stable -- fails
checkpoint
rollback-to-stable -- succeeds
checkpoint
```
will work, I think we can lose stuff from the pages because of the checkpoint that would mean a subsequent rollback-to-stable wouldn't work correctly.
I don't understand this stuff very well, so please just discard this PR if I'm misunderstanding how rollback-to-stable is supposed to behave.

WT-6018 WiredTiger shouldn't checkpoint if rollback-to-stable fails.

---

src/block/block_open.c
src/include/session.h
src/txn/txn_rollback_to_stable.c

Alex, I removed the next-to-last use of the WT_SESSION_ROLLBACK_TO_STABLE macro in WT-5946, so I thought I'd try and clean up the final use.
My concern is that the macro is fragile because any operation that's changed to set the WT_SESSION_IGNORE_HS_TOMBSTONE flag would lead to the block manager treating the operation
as if it were rollback-to-stable.

WT-6017 WT_SESSION_IGNORE_HS_TOMBSTONE flag has multiple meanings

---

test/format/format.h

We got unlucky with the timing of WT-4701 and WT-6016. A comment beginning with a parenthesis was added in WT-4701 and was missed in the mass formatting introduced by WT-6016.
Need to fix this now as it's going to break everyone's builds.

WT-6026 Fix s_all breakage on format.h

---

src/btree/bt_discard.c
src/btree/bt_ovfl.c
src/include/btmem.h
src/include/extern.h
src/reconcile/rec_col.c
src/reconcile/rec_row.c
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c

I think this is close, but I'm concerned there is something about HS caching of overflow items I still don't understand, specifically, other paths in `__wt_rec_upd_select()` where we won't cache a deleted overflow item, or if there is any additional work that's needed for overflow keys.
@bvpvamsikrishna, @agorrod, I need a reviewer for overflow changes, can you please assign someone?

WT-5833 overflow key/value item caching is not working

---

INSTALL
dist/s_all
dist/s_install
src/docs/build-posix.dox

Added INSTALL file (and script to update/generate it) describing pre-requisites, as well as
configure, build, and installation instructions.  These instructions are simply pointers to the
appropriate pages in the existing WT reference guide.
The reference guide had almost all of the required information already.  The only change there is an update to the "Building... on POSIX" page to include SWIG requirement for building python and/or Java support.  The corresponding "Building... on Windows" page already had this information.

WT-3726 Add documentation specifying build pre-requisites

---

bench/workgen/runner/example_prepare.py
bench/workgen/workgen.cxx
bench/workgen/workgen.h

Looks like some Operation flow in workgen.cxx calls cursor operations without calling begin_transaction().
Updated workgen.cxx to call any cursor operation only after begin_transaction() (_in_transaction = true).

WT-6010 Workgen changes - Add session config at Thread level.

---

examples/c/ex_all.c
examples/c/ex_backup_block.c
examples/java/com/wiredtiger/examples/ex_all.java
src/docs/backup.dox
src/docs/spell.ok

* WT-5246 First pass at incremental backup documentation
* Clean up block incremental backup documentation and examples.
* Minor spelling notes.
* Minor wordsmithing from review.
(cherry picked from commit b0d099eabfc1a351490a86059d7ee23893c45031)

WT-5246 First pass at incremental backup documentation (#5299)

---

test/suite/test_backup12.py

* WT-5624 Fix test_backup12.py to use range incremental backup.
* Set granularity small and k/v larger to get more range.
* Set writing open flag for bytes.
(cherry picked from commit bc866d0263da51e8bcb64d1004e1d7bc47c451f1)

WT-5624 Fix test_backup12.py to use range incremental backup. (#5280) (v4.2 backport)

---

src/btree/bt_slvg.c

@agorrod, our solution in WT-5437 isn't sufficient, the eviction of the constructed root page can itself be slow enough to trigger the cache stuck configuration.
You and I talked about decrementing the constructed root page's memory footprint and never restoring it when working on WT-5437, and we agreed we preferred restoring the memory footprint information. However, I don't see any alternative at this point, given we can't possibly wait and restore the memory footprint value after eviction completes.

WT-5544 Cache stuck during salvage

---

examples/c/ex_all.c
examples/java/com/wiredtiger/examples/ex_all.java
src/docs/backup.dox

* WT-4954 Document the duplicate log backup cursor.
* Clarify cursor name.
* Add more information about log files returned.
(cherry picked from commit f3db4f868600a9a46a183f4b4362ef53d767012b)

WT-4954 Document the duplicate log backup cursor. (#5322) (v4.2 backport)

---

examples/c/ex_backup_block.c

… range case. (#5330)
(cherry picked from commit 9849337bf9e206cc6e50fa84c6805f13f91bc59b)

WT-5695 Fixed incremental backup example to use O_CREAT in the backup range case. (#5330) (v4.2 backport)

---

examples/c/ex_backup_block.c
src/meta/meta_ckpt.c
test/suite/test_backup12.py

* WT-5719 Add quotes to the metadata string. Modify example to use special
characters.
* Use quotes in example. Use special characters in python test.
* Fix typo.
(cherry picked from commit 9bf859e311aa75bc2cba4bad041c6e3f6df27ce5)

WT-5719 Add quotes to the metadata string. Modify example to use special characters. (#5347) (v4.2 backport) 

---

test/checkpoint/Makefile.am
test/csuite/Makefile.am
test/evergreen.yml
test/fops/Makefile.am
test/format/Makefile.am

Re-enable Evergreen tasks that were previously disabled during DH development, and verified passing in a recent patch build. 
For those failed tasks in the same patch build, we have separate tickets created (under PM-1852) to address the effort of fixing and re-enabling them.

WT-6068 Re-enable tests temporarily disabled during durable history development

---

src/cursor/cur_backup.c
src/docs/backup.dox
src/include/extern.h
src/schema/schema_util.c
src/txn/txn_ckpt.c
src/txn/txn_nsnap.c
test/suite/test_backup11.py
test/suite/test_backup12.py

Cherry-picked from c61fcdc6656d048339b797290514a604f6007f55

WT-5722 Add standard name checks to incremental backup identifiers. (#5351) (v4.2 backport)

---

test/evergreen.yml
test/format/Makefile.am

The previous change of enabling make check format test caused some fallout - the failure pattern is different this time (not WT-5839). Will re-disable this test to address the fallout, and create another ticket to re-enable it later (as part of PM-1852).

WT-6068 Disable format test in make check

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/btree/bt_debug.c
src/btree/bt_random.c
src/btree/bt_ret.c
src/btree/col_modify.c
src/btree/col_srch.c
src/btree/row_modify.c
src/btree/row_srch.c
src/cursor/cur_bulk.c
src/cursor/cur_file.c
src/cursor/cur_index.c
src/cursor/cur_join.c
src/cursor/cur_json.c
src/cursor/cur_stat.c
src/cursor/cur_std.c
src/cursor/cur_table.c
src/history/hs.c
src/include/cursor.h
src/include/cursor.i
src/lsm/lsm_cursor.c
src/lsm/lsm_cursor_bulk.c
src/reconcile/rec_col.c
src/support/modify.c
src/txn/txn_log.c

Alex, Michael: I almost added this once before, so this time I made the change for your consideration.
It steps on name-space we don't control, but we pass cursors around more now than we used to, and I think this might simplify that process.
If you disagree, feel free to discard this change without further discussion.

WT-6087 Add a C2S(cursor) macro to simplify translation from a cursor to a session.

---

test/evergreen/compatibility_test_for_releases.sh

@lukech, based on your recent merge of `develop` into `mongodb-4.4`, we should be able to do local upgrade/downgrade testing against the `mongodb-4.4` branch.

WT-6032 turn on mongodb-4.4 branch upgrade/downgrade testing.

---

test/format/bulk.c

@keithbostic 
This is the diff that was pasted in the ticket description. I don't understand the intention behind that original snippet or the fix associated with it. If you could explain, that'd be helpful.

WT-6070 Coverity: Copy paste error

---

test/format/bulk.c

`keyno` is an `uint32_t` so we should use `PRIu32` in the format string.

WT-6071 Coverity : Change format specifier

---

src/history/hs.c

This will allow wiredtiger_open to return WT_TRY_SALVAGE.

WT-5841 Set the data corruption flag if we find history store issues.

---

src/cursor/cur_backup_incr.c
test/csuite/incr_backup/main.c

* WT-5697 Fix incremental backup with schema operations.
* Whitespace
* Only need to clear cursor caching around open call.
* Remove old comment. Alphabetize.
(cherry picked from commit 4a3bbfa97835c6dba98ae03aa1566a708a552bde)

WT-5697 Fix incremental backup with schema operations. (#5565) (v4.2 backport)

---

src/reconcile/rec_visibility.c
test/csuite/random_abort/smoke.sh
test/evergreen.yml

The problem is the globally txn structure is updated concurrently and the tombstone becomes globally visible so the onpage value is not appended to the update chain.

WT-6093 __wt_rec_upd_select may not append the onpage value if the global txn structure is updated

---

src/include/wiredtiger.in
test/format/CONFIG.stress
test/format/backup.c
test/format/bulk.c
test/format/checkpoint.c
test/format/config.c
test/format/config.h
test/format/format.h
test/format/format.i
test/format/ops.c
test/format/t.c
test/format/util.c
test/format/wts.c

Copying the entire format/config.c file from 4.4 to 4.2 instead of backporting parts of the format code.

WT-5914 Only configure log-incremental backup if archiving is off in test/format (V4.2 backport)

---

src/txn/txn.c

It is possible that there can be multiple aborted updates in the update
chain when the prepared update is rolling back. So fix the assert to
not to expect an update that is aborted.

WT-6142 Fix the assert with no more than one aborted update in chain

---

src/block/block_ckpt.c
src/include/meta.h

Please review this change carefully since I got it wrong the first time. It fixes a problem I saw in the metadata where we were over allocating the bitmap. I wanted to fix this first before the other tickets since I understood it well and maybe it affected the block-not-changed (it doesn't).
I renamed the variables to be clear about what units we're dealing with and moved everything to be in bits until we get to the allocation part.

WT-6137 Fix calculation of bits versus bytes for incremental bitmap.

---

test/evergreen.yml

This test appears to now be passing in Evergreen. Patch build is [here](https://evergreen.mongodb.com/version/5eb8c63c2a60ed36b28a3696).

WT-6063 Enable checkpoint-filetypes-test in Evergreen

---

src/btree/bt_ovfl.c
src/btree/bt_page.c
src/btree/bt_sync.c
src/history/hs.c
src/include/btmem.h
src/include/reconcile.h
src/include/txn.i
src/reconcile/rec_row.c
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c
src/support/modify.c

The durable timestamp represents whether the update is stable or not.
Use the durable timestamp only to decide whether the update is globally visible
instead of commit timestamp. This change reverts part of the changes
done by ticket 5414.

WT-6092 Use durable timestamp to find out global visibility

---

test/evergreen.yml

The test is now passing:
https://evergreen.mongodb.com/build/wiredtiger_ubuntu1804_patch_5b7d6ff3503cfa2e7c6ca858bb9955dc6f28936d_5eb8df407742ae0e1643829a_20_05_11_05_15_38

WT-6065 Enable spin lock gcc test

---

test/format/backup.c

@sueloverso, the failure here was passing a `u_int` to the incremental backup cursor, it expects a `uint64_t`.
The path construction code had minor problems as well, so I reworked it for simplicity.

WT-6160 format failure caused by stack overwrite

---

src/include/error.h
src/include/misc.h

@agorrod, @sueloverso, I add this in every so often so I can figure out what verbose messages came from where. Maybe it's generally useful?
Verbose messages get the flag added, so they look like this:
```
file:wt.wt, WT_CURSOR.insert: [WT_VERB_BLOCK] file extend 512B @ 145408
file:wt.wt, WT_CURSOR.insert: [WT_VERB_BLOCK] file extend 512B @ 145920
file:wt.wt, WT_CURSOR.insert: [WT_VERB_BLOCK] file extend 9216B @ 146432
```

WT-6159 tag verbose messages to make them easier to distinguish

---

src/block/block_ckpt.c
src/conn/conn_open.c
src/include/connection.h
src/meta/meta_ckpt.c
src/txn/txn_ckpt.c
test/suite/test_backup01.py
test/suite/test_checkpoint05.py

This fixes a problem from WT-5242 where there was a path where we could create a checkpoint but not update the global "last checkpoint" time, resulting in backups that didn't include the correct checkpoint(s).  This PR fixes that by updating the last checkpoint time at the same point where we assign time values to each new checkpoint.  
I've changed the name of that global field from `conn->ckpt_finish_secs` to `conn->ckpt_most_recent` to more accurately reflect the current usage.  We are no longer updating the time when checkpoints finish.
Also re-enable python tests for dropping checkpoints during backup.

WT-6118 Missing checkpoint in backup

---

test/evergreen.yml
test/format/format.sh

Introduce a new "-e" argument to the `format.sh` wrapper for environment variable setting, so that the setting could be put in front of the `setsid` command to avoid execution failures. 
Also add the checking of the RUNDIR log file for the execution failure right after the `setsid` command, mark failure counter and force quit.

WT-6172 Fix silent failures of Evergreen test/format tasks

---

src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/btree/bt_debug.c
src/btree/bt_random.c
src/btree/bt_ret.c
src/btree/col_modify.c
src/cursor/cur_backup_incr.c
src/cursor/cur_bulk.c
src/cursor/cur_file.c
src/cursor/cur_metadata.c
src/history/hs.c
src/include/api.h
src/include/cursor.h
src/include/dhandle.h
src/include/extern.h
src/include/txn.i
src/lsm/lsm_cursor.c
src/meta/meta_table.c
src/schema/schema_truncate.c
src/txn/txn.c
src/txn/txn_ckpt.c
src/txn/txn_log.c

@agorrod, would you please approve the overall change, and @ddanderson, would you please do the detailed review?
The potentially interesting changes:
- `btree/bt_debug.c`, use `WT_WITH_BTREE`  in two more places
- `cursor/cur_bulk.c`, create a per-bulk cursor close routine
- `cursor/cur_file.c`, setting/clearing `WT_CURSOR_BTREE.dhandle` in different places`
- `include/api.h`, don't pass a `WT_BTREE` handle to `CURSOR_UPDATE_API_CALL_BTREE`, which makes that macro different but clarifies the `WT_BTREE` handle isn't optional as it is in other places
- `include/cursor.h`, remove `WT_CURSOR_BTREE.btree`, add the `CUR2BT` macro
I also fixed up a few places in LSM and `dhandle.h` where we were using the `WT_CURSOR_BTREE.WT_BTREE.dhandle`, and it was simpler to just use …

WT-5725 Remove the WT_CURSOR_BTREE.btree field.

---

src/session/session_dhandle.c
test/suite/test_checkpoint04.py

This change removes the use of timestamps as they were not being updated
properly for checkpoints. It prints out via self.pr more information, in
particular, the value of all interesting statistics prior to checking
them so that if we fail we can see all of them in results.txt.

WT-6042 Changes to checkpoint04 to remove or debug failures on Windows.

---

src/txn/txn_recover.c

This change is to avoid performing rollback to stable when we have no history store file. Previously, if we skip log recovery we `goto done` which will skip the logic where we determine whether or not a history store exists and `hs_exists` won't be assigned to properly.

WT-6195 Ensure that we don't perform rollback to stable without a history store

---

test/format/format.sh

@lukech, in #5634 we removed the `nohup` call in `format.sh`, and that means we can't exit `format.sh` and let the underlying commands keep running. Can we talk about why that was needed for your fix?
Rather than calling `eval`, can we just export the environment variables?

WT-6214 format.sh must disassociate from the child process

---

src/txn/txn.c
test/suite/test_rollback_to_stable07.py

When a uncommitted prepaed update is written to the data store, the
history store update must have a value with stop timestamp as WT_TS_MAX.
Need to update that value with proper stop timestamp by inserting a
new update to the history store folllowed by a tombstone with valid
stop timestamp.

WT-6148 Add new update to the history store with valid stop timestamp

---

src/btree/bt_page.c
test/suite/test_prepare08.py

When the prepared update is a tomnbstone that is written to the datastore,
while instantiating the data store, make sure that instantiate both
update and tombstone to avoid replacing the on-disk value.

WT-6245 Instantiate both update and tombstone for prepared tombstone

---

dist/log_data.py
src/history/hs.c
src/include/extern.h
src/include/txn.h
src/include/txn.i
src/log/log_auto.c
src/txn/txn.c
src/txn/txn_ckpt.c
src/txn/txn_log.c
src/txn/txn_recover.c
src/txn/txn_timestamp.c

As part of #5677, @quchenhao  noted that we can simplify our transaction structures since we're no longer moving our read timestamp back and forth for resolving modifies since the introduction of the `WT_SESSION_RESOLVING_MODIFY` flag.

WT-6252 Remove mutable read timestamp from transaction structure

---

test/csuite/incr_backup/main.c

@ddanderson I'm turning off rename in general testing while WT-6215 is open. That ticket will turn it back on, but the fix is non-trivial so in order to allow testing to proceed in the meantime, I'm turning off rename.

WT-6261 Turn off incremental backup rename testing until open ticket is fixed.

---

dist/api_data.py
src/block/block_write.c
src/conn/conn_log.c
src/conn/conn_open.c
src/cursor/cur_backup.c
src/docs/backup.dox
src/include/connection.h
src/include/schema.h
src/include/wiredtiger.in
src/log/log.c
src/meta/meta_ckpt.c
src/schema/schema_util.c
src/txn/txn_ckpt.c
src/txn/txn_log.c
test/suite/test_backup01.py
test/suite/test_checkpoint05.py

WT-5242 Minimize checkpoints pinned during backup (#5590)
- Checkpoints have time values generated from a per-session monotonic clock.  Use these values to preserve only the checkpoints that may be needed by backup.  At the end of each checkpoint, we save a time value from the same clock.  When we open a backup cursor we use this save value as a limit on checkpoint preservation.  All checkpoints with times values less than or equal to that are kept until the backup cursor is closed.
- Add python tests for new behavior and update docs to reflect new way checkpoints and backup cursors interact.
- Eliminate unnecessary iteration searching for highest value in sorted array.
Co-authored-by: Keith A. Smith <keith.smith@mongodb>
(cherry picked from commit …

WT-5242 Minimize checkpoints pinned during backup (v4.2 backport)

---

src/block/block_ckpt.c
src/cursor/cur_backup.c
src/include/meta.h
test/suite/test_backup15.py

WT-6137 Fix calculation of bits versus bytes for incremental bitmap. (#5618)
- Add comment. Fix end bit to `len - 1`.
(cherry picked from commit 5f744db3b90e453a98ed018f7f950de2f7306850)
WT-6136 Record incremental extent lists before merging them with earlier (#5619)
- Add reproducer test that reads all blocks returned to make sure they have changes.
- Fix a comment.
- The function names were swapped vs. the functionality.
- Push the extent lists written as intermediate checkpoints are rolled forward to the hot backup. Enhance some comments to explain what's going on.
- Record incremental backup blocks before possibly skipping processing so we record them every time.
- Move the loop down into the block mod functions for checkpoint.
Co-authored-by: Keith Bostic <keith.bostic@mongodb.com> …

WT-6136 Record incremental extent lists before merging them with earlier checkpoints (v4.2 backport)

---

test/format/ops.c

This expression (`pause_ms *  WT_THOUSAND`) can overflow since it is using 32-bit integer arithmetic. We can avoid this by casting one of the operands to `uint64_t`.

WT-6265 Coverity: Integer overflow in test/format/ops.c

---

src/meta/meta_turtle.c
test/csuite/wt4156_metadata_salvage/main.c

Also set test_abort to false in child process instead of inheriting.

WT-6056 Set DATA_CORRUPTION flag so we return TRY_SALVAGE on open.

---

dist/api_data.py
src/btree/bt_debug.c
src/btree/bt_vrfy.c
src/config/config_def.c
src/history/hs.c
src/include/extern.h
src/include/wiredtiger.in

@agorrod, @quchenhao, @tetsuo-cpp, @kommiharibabu, @luke-pearson, @bvpvamsikrishna: these are the changes that I mentioned over the weekend. If you find this approach useful in your debugging, I'm happy to fix the output in any way you like, just let me know what information you'd like to see in the page dumps. (If this isn't helpful, I'm happy to kill this branch entirely.)
One change I should flag is that I'm no longer printing time windows if they're empty, only if they have values that are different from the defaults.
@sulabhM, @luke-pearson, I've asked you to review because this PR changes the work done in WT-5347 by @jeremytay90, that you reviewed. In that ticket, we added `-d dump_history` to the `wt` command, which I think changed verify to dump HS records at the same time as …

WT-6248 add HS records to page dumps

---

src/include/cursor.h
src/include/txn.i
src/utilities/util_dump.c

When we moved `WT_CURSTD_IGNORE_TOMBSTONE` from being a session flag to a cursor flag, we broke wt dump. `wt dump` uses a dump cursor which delegates calls to the cursor API to a "child" cursor. We need to set the flag on the child cursor for this to work.
We also modified the check in `__wt_txn_read` such that we will read the on-disk value's stop time pair even with `WT_CURSTD_IGNORE_TOMBSTONE` enabled if it is globally visible. This makes `wt dump` less useful so let's make an exception here.

WT-6284 History store isn't visible to wt dump

---

src/evict/evict_lru.c

Don't fast track the eviction of HS pages, as this can lead
to thrashing when there are a lot of deletes to apply to the
HS file during checkpoint reconciliation.

WT-6229 Fix memory growth bug during MDB shutdown

---

src/btree/bt_delete.c
src/btree/bt_page.c

Some memory allocations are missed to considered as page cache
allocations.

WT-6307 Increase the page cache size for all the page allocations

---

src/cursor/cur_backup.c
src/cursor/cur_backup_incr.c
src/include/extern.h

This was picked up by Coverity so I figured we may as well propagate the return value upwards to callers.

WT-6334 Coverity: Use return value when closing incremental backup cursor

---

src/btree/bt_slvg.c
test/format/format.h
test/format/salvage.c
test/format/t.c
test/format/wts.c

@quchenhao, this branch does timestamp aggregation during salvage, would you please do the review?
I have a few concerns:
* First, in WT-6260, you commented "The cause of the failure is we are not aggregating time window information to the internal pages when doing salvage. If we need to aggregate that information, we have to rebuild every page we try to salvage, which will make salvage take much longer." I'm not following that, my approach is to read the timestamps out of the leaf pages and then use that information to initialize the internal pages we create. It seems to me you're talking about rewriting leaf pages, which would be expensive -- can you please explain further what you were thinking, and if I'm missing something?
* Second, the failure in the initial WT-6260 ticket was that …

WT-6295 Aggregate time windows in salvage

---

src/txn/txn.c

Sorry, I forgot to merge in `develop`. Same deal here, I think it's fine to remove this usage because we're always ignoring visibility for history store now.

WT-5769 Remove remaining usage of ignore visibility flag

---

test/suite/test_prepare08.py
test/suite/test_prepare10.py

@kommiharibabu - I have increased the cache size to 2MB and so far I haven't seen the test failing again with WT_ROLLBACK error.

WT-6323 Increase cache size in test_prepare10 to avoid rollback errors

---

test/format/smoke.sh

This is the suggested change in the existing `smoke.sh` to run test/format binary for 10 times, which takes ~ 11 minutes. 
Evergreen patch build with the changes
https://evergreen.mongodb.com/build/wiredtiger_ubuntu1804_patch_b9e8146ae5bc2f131cd7d9c19a2870746573cb38_5ed31853d6d80a49850ef5ba_20_05_31_02_37_56
Another approach would be to call `format.sh` with `-t` option and specify the time in minutes to run the test/format binary.

WT-6301 Add short running stress jobs

---

test/suite/test_compact02.py

Looks like this error was reported earlier as well and the maximum timer was increased to 5 minutes since it is not failing because of any bug, it is just that eviction taking a very long time to finish in the small cache case. The maximum wait time was increased to 5 minutes with the ticket [WT-3942](https://jira.mongodb.org/browse/WT-3942). 
I have increased the maximum timer to 8 minutes and give enough time for eviction with a small cache.

WT-6328 Update test_compact02 to handle being halted by eviction pressure.

---

src/history/hs.c
src/reconcile/rec_visibility.c
test/suite/test_hs11.py

Reverts wiredtiger/wiredtiger#5742

Revert "WT-6347 Don't reset transaction ids when evicting mixed mode tombstones and clear history store contents for mixed mode updates"

---

src/btree/bt_import.c
src/conn/conn_api.c
src/conn/conn_log.c
src/conn/conn_open.c
src/conn/conn_reconfig.c
src/include/connection.h
src/include/extern.h
src/meta/meta_turtle.c

@agorrod and @luke-pearson here is a redo of the compatibility changes and adding in the turtle validation. I found in `conn_single` we were already doing some turtle work and added it there. That felt better than adding another case where we interact with the turtle. It happens to come before the log checking so it should fix the skip version test.
@luke-pearson can you check or test with this branch and that failure? I am still not thrilled with the fragility of certain things being in order in the server code, but this works around that for the moment.
Also @luke-pearson do we still need/want the second call to `wt_turtle_validate_version` in `wt_turtle_init`? Or, is the one I added in `conn_single` going to break or crash in the case of corruption and/or salvage?

WT-6015 Check log and turtle versions early before modifying database.

---

test/checkpoint/workers.c

Coverity link
https://coverity.corp.mongodb.com/reports.htm#v15509/p10049/fileInstanceId=30123292&defectInstanceId=19812275&mergedDefectId=114181&fileStart=1&fileEnd=125

WT-6359 Coverity Explicit NULL dereference

---

test/evergreen.yml

Updating ASAN_SYMBOLIZER_PATH to correct location and version of llvm-symbolizer for PPC sanitizer tests.

WT-6342 Invalid path to external symbolizer on PPC machines

---

test/suite/test_compat02.py

Add the `prune` & `prunelong` argument settings in test_compat02.py as suggested by @ddanderson. Created a patch build with some quick analysis (in jira).

WT-5801 Reduce runtime of Python unit tests by pruning test_compat02.py

---

src/txn/txn_rollback_to_stable.c

During aborting of on-disk update on a data store while replacing it
with the history store update that have both equal start and stop
timestamps led to not removing the history store record can led to
the update present in both data store and history store. To hanlde
this problem, RTS must remove the history store update that is getting
appended to the data store.

WT-6381 RTS to remove hs record that is appended to the update chain

---

dist/api_data.py
src/block/block_ckpt.c
src/config/config_def.c
src/include/wiredtiger.in
test/csuite/incr_backup/main.c
test/format/backup.c
test/format/config.c
test/format/config.h
test/format/format.h

* WT-6366 Off-by-one overflow in block-modification bitmaps for incremental backup
Fix off-by-one error that caused overflow of allocated memory buffer
when setting the last bit in the bitmap used to track block changes
for incremental backup.
Allow block sizes as small as 4KB to make it easier to test and trigger
this type of bug.
Modify test/format and test/csuite/incr_backup to use the smaller
block sizes.
Co-authored-by: Keith A. Smith <keith.smith@mongodb>
(cherry picked from commit ee2d775e537151d683baa6954097de560856f715)

WT-6366 Off-by-one overflow in bitmaps for incremental backup (#5771)

---

src/btree/bt_cursor.c
src/btree/col_srch.c
src/btree/row_srch.c
src/history/hs.c

I noticed while debugging WT-6257 that we should be using the `WT_WITH_BTREE` macro when invoking search. I see some code in search that updates `btree->maximum_depth` based on information in that function so we need to be doing this.
Unfortunately, it doesn't solve WT-6257 however.

WT-6382 Use history store btree when searching

---

test/suite/test_bug019.py

@keitharnoldsmith I want to merge this into the tree so that there are breadcrumbs of what the values are in any artifacts. I've run several hundred iterations on two machines without a failure so this will capture information for whenever it next hits on evergreen or for anyone.

WT-6353 Print out failing values and value history of prealloc.

---

test/evergreen.yml

- Moved the long running stress test jobs into variables so that we could run multiple parallel instances in the same build variant without creating duplicate code in the `evergreen.yml` file.
- Added task tags to identify and group the stress tests and simply the build variant configurations.
- Removed a few lines of code in an unrelated test that caused `evergreen validate` to error.
- Removed redundant comments in the task definitions.
- Further discussion/work is needed to split the `checkpoint-stress-test` into shorter running instances. With the column-store and lsm testing disabled, it currently takes approximately six hours to complete.

WT-6379 Split Evergreen stress test job into multiple shorter running jobs

---

src/history/hs.c

This is handling a corner case where we end up with an update chain with `WT_UPDATE_MODIFY` type update as the oldest update when handling mixed mode operation (timestamped and non-timestamped updates).

WT-6344 Trim the update vector until there is a full update

---

test/format/util.c

Set stable ts to the "all_durable" value, and let oldest ts lag that.

WT-6427 Always set stable timestamp when setting oldest timestamp.

---

test/csuite/timestamp_abort/main.c
test/suite/test_txn13.py

Ideally tests would be written to retry on rollback errors rather than treat them as fatal, but for now configure to make rollbacks unlikely.

WT-6434 Configure tests to avoid rollback due to cache pressure.

---

src/evict/evict_lru.c
src/support/cond_auto.c

Here we are trying to read the `prev_wait` of condition variables's value using atomic operations because there can be multiple threads accessing this block of code simultaneously. 
The `cond->prev_wait` value was going above WT_MILLION due to race between threads and causing it to assert.

WT-6351 Fix race between threads to update condition variable's previous wait value.

---

src/include/txn.i
src/txn/txn.c

When we read values from history store's update list as part of prepared transaction rollback, the tombstones on the update list are not visible and we end up in restoring deleted values. This change will skip tombstone visibility checks and brings it line with how we deal with tombstones when reading on-disk values.

WT-6397 Reduce restrictions on reading tombstone info from history store update list

---

test/format/bulk.c
test/format/config.c
test/format/format.h
test/format/ops.c
test/format/util.c
test/format/wts.c

@ddanderson #5814 was reverted due to the testing fallout described [here](https://jira.mongodb.org/browse/WT-6427?focusedCommentId=3211591&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3211591). Please use this PR for further change.

WT-6427 Always set stable timestamp when setting oldest timestamp (2nd attempt)

---

test/format/format.sh

@lukech, this should turn off the core dumps we're seeing from `format-stress-sanitizer-smoke-test-2`.
I didn't chase why the test itself isn't reporting failure.
cc: @agorrod

WT-6476 Block running rebalance with timestamp set in test format

---

dist/stat_data.py
src/btree/bt_read.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable12.py

RTS used to read internal pages as part of tree walk and read
the leaf pages internally and evict them is causing the tree walk
to be restarted. Instead of inventing the tree walk restart logic
again in RTS, better to load all the RTS required pages as part
of tree walk.

WT-6448 RTS to read all the required pages as part of tree walk

---

src/include/txn.i

Checkpoint timestamp is not included while calculating the pinned timestamp
for history store, this can lead to the removal of history store updates that
are may be required later as per the checkpoint timestamp.

WT-6460 Consider checkpoint timestamp also as part of pinned timestamp for HS

---

src/reconcile/rec_row.c
test/suite/test_hs11.py

When a timestamped delete is globally visible led to removal
of data store key doesn't need to truncate all the previous
history store updates until the tombstone from a mixed mode
delete operation.

WT-6349 Don't truncate hs updates for timestamped deletes

---

test/suite/test_bug019.py

This is a test that has rarely failed when trying to reproduce. I'm adding more debugging to catch all the different assertions so that whenever it happens we get information.

WT-6483 Add debugging for log file lists.

---

src/include/reconcile.i

In the case of a row-store leaf page, we want to encourage a split if we see lots of in-memory content. This allows pages to be split for update/restore and history store eviction even when the disk image itself isn't growing.

WT-6487 Force pages to split in the case of lots of small updates on a page

---

src/include/txn.i

* Cache the WT_UPDATE.type field so that it can't change underneath us after the visibility checks.
(cherry picked from commit 168c7f1b3859516115721868f312544abb0caf5b)

WT-5376 WT_UPDATE.type field can race with visibility checks when returning key/value pairs (v3.6 backport)

---

test/csuite/wt4333_handle_locks/main.c

The test test_wt2853_perf fails because of memory contention by other csuite binaries, ex: `test_wt4333_handle_locks`
uses 5 GB of cache and runs a maximum of 600 threads.
I updated the binary `test_wt4333_handle_locks` to use a maximum of 64 threads, cache_size of 1 GB, ran the test overnight and none of the csuite binaries failed.

WT-5970 test_wt2853_perf failure

---

src/txn/txn_ckpt.c

(cherry picked from commit a19d2bff3d30fdd83086172b29161527aefc28e3)
(cherry picked from commit 58baf804dd6e5a72c4e122cfb696e2d06a9fc888)
(cherry picked from commit e58bd570c06955c5b85b75af4a58b6d1da7c5d90)

WT-5587 Limit how many checkpoints are dropped by a subsequent checkpoint (v3.6 backport)

---

src/cursor/cur_join.c
test/suite/test_join10.py

Not doing so will leave the iteration incomplete and (at a minimum) unnecessary work will be done.
The change includes a new test that checks statistics to see how much work is being done.

WT-6511 cursor join: explicitly advance the iterator when finished with a clause.

---

src/btree/bt_sync.c

Avoiding the checkpoint cleanup during recovery let the trees to be
in clean state to change the logging of the table during startup.

WT-6521 Don't perform checkpoint cleanup during recovery

---

test/suite/test_txn13.py

So essentially if we avoid doing > 10 modifications we can prevent the rollback logic from triggering while also ensuring we keep the intention behind the test and write large log records. All I've done is taken the mod count to 8 and multiplied the value size by the same factor.

WT-6517 Update test_txn13 to avoid getting a rollback error

---

test/suite/test_rollback_to_stable11.py

@ddanderson I put an explanation in the ticket if you want/need more context.

WT-6425 Turn off log archiving to avoid file copy race.

---

src/evict/evict_file.c

The problem is that a single file checkpoint tries to close a clean tree. The tree has some pages that are truncated and loaded into memory again. These truncated pages are cleaned by a previous full checkpoint, thus triggering the assert as non-globally visible truncation are not evictable. The solution is to relax the assert as we should be able to discard these pages.
We don't see this before durable history because checkpoint cannot clean the page in this case as we can't write tombstones to disk.

WT-6468 Discard a deleted page that is cleaned by a checkpoint

---

test/suite/test_txn19.py

Not sure what the intention of the test change in #5541 was but I believe that we were already testing that the history store can be salvaged. The removal of the history store from the `non_salvageable` list just means that we expect that it can be salvaged (not that it isn't tested anymore). I added back the extra checks of the history store error pattern but I believe this does the job.

WT-5717 Reenable history store salvage test

---

src/meta/meta_ckpt.c

(cherry picked from commit 0de11da4bff9ecd783340836e12cceb033c43bd8)

WT-6319 Reserve a byte for the terminating nul. (#5792)

---

dist/api_data.py
src/include/wiredtiger.in

The formatting issue is seen externally [here](http://source.wiredtiger.com/develop/struct_w_t___c_o_n_n_e_c_t_i_o_n.html#a579141678af06217b22869cbc604c6d4), where an unintended ordered list item appears in the config parameter table for the value `eviction_updates_trigger`. The `struct_w_t___c_o_n_n_e_c_t_i_o_n.html` file is generated internally via our top-level `s_all` script. At a lower level, doxygen is used to (among other things) transform our auto-generated `wiredtiger.in` file to the html documentation. It appears that when generating `wiredtiger.in`, we created a text pattern that [doxygen interprets as an ordered list item](https://www.doxygen.nl/manual/lists.html).
```
* size if the value is within the range of 1 to 100 or an absolute size when greater than
--->  * 100. …
```

WT-6514 Fix description of eviction_updates_trigger in the documentation

---

test/evergreen/compatibility_test_for_releases.sh

Adding the new `mongodb-4.6` branch into both the 'short' and 'long' compatibility tasks, and removing `mongodb-4.0` from the 'short' task in favor of `mongodb-4.6`.

WT-6519 Add testing coverage for mongodb-4.6 branch in compatibility test

---

test/evergreen.yml

The change is to avoid Artifacts overwriting across task restarts in the WiredTiger Evergreen projects.

WT-6543 Adding task execution number to name of Artifacts uploaded to S3

---

src/include/meta.h
src/include/txn.h
src/meta/meta_ckpt.c
src/txn/txn_ckpt.c
src/txn/txn_recover.c
test/format/format.h
test/format/t.c
test/format/util.c
test/suite/test_timestamp19.py

Fixed the issue that test format had when it reopened a previously existing database.
New changes are in:
t.c, util.c and format.h

 WT-6331 Set oldest timestamp on startup of WiredTiger

---

test/evergreen.yml

#5914 was reverted due to fallout on the Evergreen waterfall page. Will use this PR for further changes/fixes.
The fallout was because some testing tasks restarted, and in those newer executions the tests tried to retrieve artifacts of the dependant compile task, using their own execution number 1, however, the compile task was never restarted and only had the artifacts with execution number 0 uploaded. That caused artifacts retrieval (and task) failures.
To resolve this issue, the new design is to avoid distinguishing artifacts using task execution number for compile tasks, and let all testing tasks to retrieve compile artifacts without the execution number. For testing tasks, the artifacts will still be distinguished across task restarts, to provide users the flexibility to check into …

WT-6543 Adding task execution number to name of Artifacts uploaded to S3 (2nd attempt)

---

dist/api_data.py
src/block/block_write.c
src/btree/bt_vrfy.c
src/conn/conn_log.c
src/conn/conn_open.c
src/cursor/cur_backup.c
src/docs/backup.dox
src/include/connection.h
src/include/extern.h
src/include/wiredtiger.in
src/log/log.c
src/lsm/lsm_work_unit.c
src/meta/meta_ckpt.c
src/meta/meta_ext.c
src/schema/schema_util.c
src/txn/txn_ckpt.c
src/txn/txn_log.c
test/suite/test_backup01.py
test/suite/test_checkpoint05.py

This PR is a series of cherry-picks from #5684. These cherry-picks were very unclean mainly because 4.0 doesn't have #4520. I was briefly considering backporting that change too but it happened BEFORE Clang Format so it's a bit complicated.
Before merging this PR, I'll squash any changes I make into @tammybailey's "PR changes" commit.

WT-5242 Minimize checkpoints pinned during backup (v4.0 backport)

---

examples/c/ex_backup_block.c
src/include/txn.i
test/format/backup.c

int.
(Also fix a contraction that is flagged on multiple machines in
s_string.)

WT-6571 Lseek cannot use error_sys_check because it does not return an

---

test/csuite/timestamp_abort/main.c

Set eviction_{dirty,update}_{trigger,target} appropriately, and update comments.
Add handling for rollback, it's likely to happen now.

WT-6472 In timestamp abort, size cache to be proportional to number of threads.

---

src/evict/evict_lru.c

This ended up looking a bit different to how I anticipated as while we do clear `operation_timeout_ms` on our transaction we actually check against the sessions timeout parameter.

WT-6507 Exit cache eviction worker after our operation has timed out

---

test/suite/test_backup02.py
test/suite/test_checkpoint02.py
test/suite/test_rollback_to_stable10.py

While trying to repro a separate issue, I noticed that tests that use `checkpoint_thread` occasionally hit a C assertion if they're failing in Python.
The issue is that we spin up a separate checkpoint thread but if we fail in Python before reaching the `ckpt.join()`, we'll close the connection mid-checkpoint which is not allowed. Our API doesn't allow users to be doing things with the engine from other threads if they're closing the connection.

WT-6591 Stop checkpoint thread before closing connection in Python tests

---

dist/s_docs
src/docs/Doxyfile
src/docs/command-line.dox
src/docs/devdoc-optrack.dox
src/docs/devdoc-xray.dox
src/docs/eviction.dox
src/docs/spell.ok
src/docs/tune-capacity.dox
src/docs/tune-durability.dox

The issue in this ticket was initially reported as below spelling error about a digit character being included in a word. It turned out this error stopped the spell checking from running, and shadowed a list of warnings in the rest of unchecked `.dox` files.
> [2020/04/19 23:26:31.395] Error: ./spell.ok: The word "t2" is invalid. The character '2' (U+32) may not appear at the end of a word.
The 1st commit removes `t2` from `src/docs/spell.ok`, and fixes all [warnings](https://jira.mongodb.org/browse/WT-6027?focusedCommentId=3335816&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3335816) detected later on (as spell checking got unblocked for the rest of .dox files).
The 2nd commit updates aspell language setting to `--lang=en_US` in `dist/s_docs` script, to …

WT-6027 Fix docs spelling errors and warnings

---

dist/s_clang-format

Below log message was dumped out when the `clang-format` binary does not exist in the git tree when running `s_all` or `s_clang_format` (which is the case in Evergreen testing). The message may confuse users and make them think the `s_clang-format` script did not get to run, though in reality the script will try to download the clang-format tarball, unzip it and continue running. 
> [2020/06/23 07:17:55.123] ./s_clang-format: line 29: clang-format: command not found
This PR is to avoid the "command not found" error message, ~~and add another log line by indicating the tarball downloading is happening~~.

WT-6471 Avoid the error message for non-existent clang-format binary

---

src/utilities/util_main.c

The global `-S` salvage option currently doesn't work with the `wt` utility. We moved this functionality from being an argument to `recover` to being its own option to `wiredtiger_open`.
This PR is changing the `wt` utility to use the new API correctly.

WT-6560 Fix usage of global salvage in WT utility

---

test/csuite/random_abort/main.c
test/csuite/schema_abort/main.c
test/csuite/timestamp_abort/main.c

Ensure threads' key spaces are truly separate.
Show the wiredtiger_open configuration on output.

WT-6596 Increase cache for timestamp abort test.

---

src/cursor/cur_backup_incr.c
src/include/cursor.h
src/include/extern.h
src/include/meta.h
src/meta/meta_ckpt.c
src/schema/schema_rename.c
test/csuite/incr_backup/main.c

* WT-6215 Clear backup block information on rename.
* Set all bits in backup info of new metadata on rename.
* We need to retain all the incremental metadata information on rename.
* Add a rename field to incremental backup info in metadata for rename
management.
Co-authored-by: Alex Cameron <alex.cameron@10gen.com>
(cherry picked from commit 7365ea188aaf1aa094824def8822d816752dcab2)

WT-6215 Clear backup block information on rename. (#5662) (v4.2 backport)

---

test/suite/test_compact02.py

I haven't had a great deal of luck reproducing this on either my MacBook or even on one of the MacStadium hosts (1000+ runs). I'm not surprised as it's very rare given how frequently we run this test in Evergreen.
It seems to be reproducing much less often than when @raviprakashgiri29 extended the timeout so I think we're on the right track. I'm hoping that after bumping this to 10 min, the last x% of failures will disappear.

WT-6390 Extend compact02 timeout from 8 => 10 minutes

---

test/suite/test_cursor13.py
test/suite/test_cursor16.py

@ddanderson & @sueloverso.  I think the [JIRA Ticket](https://jira.mongodb.org/browse/WT-6589) sufficiently explains what's going on here.  But feel free to ping me with questions—here or on Slack.
This basically goes back to the version of these tests before WT-6274, and then fixes the tests to work with the changes from WT-6274 and WT-6478.

WT-6589 Fix disabled cursor cache python tests

---

test/suite/test_cursor13.py

Fail if we can't get stable hs statistics after 100 tries, rather than trying forever.

WT-6619 Eliminate possibility of infinite loop in test_cursor13.py

---

test/suite/test_hs06.py

This `TODO` comment refers to a ticket that has been closed which was flagged by some PM script.
We still don't know what to do about checkpoint cursors yet but we do have WT-5927 to track this issue so I've replaced it with a `FIXME` and marked it appropriately.

WT-6625 Remove outdated TODO

---

src/async/async_api.c
src/conn/conn_api.c
src/conn/conn_cache.c
src/conn/conn_cache_pool.c
src/conn/conn_capacity.c
src/conn/conn_ckpt.c
src/conn/conn_log.c
src/conn/conn_open.c
src/conn/conn_stat.c
src/conn/conn_sweep.c
src/history/hs.c
src/include/api.h
src/include/extern.h
src/lsm/lsm_manager.c
src/meta/meta_track.c
src/schema/schema_util.c
src/session/session_api.c
src/txn/txn.c
src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c
test/suite/test_txn22.py

Due to PANIC error set by the recovery failure stops processing
any session operations led to memory leak. Avoid stopping of processing
session operations for the internal sessions can fix the memory leak
and also avoid performing the final checkpoint when the connection
is PANIC state

WT-6556 Fix internal sessions to use internal session close function than public API to avoid memory leak 

---

dist/s_stat
dist/stat_data.py
src/include/btree.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/txn/txn_ckpt.c
test/suite/test_checkpoint05.py
test/suite/test_checkpoint07.py

* WT-6421 Avoid parsing metadata checkpoint for clean files.
* Set timer to forever if we know we'll never have to delete older
checkpoints.
* Fix WT_RET to WT_ERR.
* Remove unneeded WT_UNUSED. And formatting.
* Add per-btree stat for clean checkpoint timer
* Add new stat to list we cannot detect.
* Add test and fixes for it.
* Alphabetize.
* Clean up and simplify test
* Fix test to check values are within 1 second of each other.
* Style fixes. Remove unneeded code/comment.
(cherry picked from commit 8d8e71d683e08794cfd6946e56bdd81042fb2fd8)

WT-6421 Avoid parsing metadata checkpoint for clean files. (#5924)

---

bench/workgen/workgen.cxx
bench/workgen/workgen_func.c
bench/workgen/workgen_func.h
bench/workgen/workgen_int.h
bench/wtperf/idle_table_cycle.c
bench/wtperf/wtperf.c

@ddanderson please carefully check the changes to `workgen`. I left some of the `workgen_epoch` calls in there where it was not an obvious `stop-start` timing situation.

WT-5144 Improve runtime in perf programs.

---

src/utilities/util_main.c

This PR is making a usability fix to the `wt` utility. A common use case is to use the utility on MongoDB data files which require a specific set of options in the `-C` argument.
I've added a line in the help output to provide the correct configuration to use for MongoDB data files.

WT-6561 Provide MongoDB configuration in the wt utility usage output

---

src/session/session_api.c

Once the session->close API enters the code to close the session,
don't raise intermmediate errors until the session is closed properly.

WT-6650 Don't raise error until session is closed properly

---

test/suite/test_rollback_to_stable10.py

Group entire iteration of updates in a function that can be repeated after rollback.

WT-6653 In the rollback to stable test, rollback/restart txn before retry.

---

test/suite/wttest.py

Introducing a new `skipped` instance variable in `WiredTigerTestCase` Python class. Setting the variable while detecting not-built extension and calling skipTest(), and at the tearDown phase avoid treating the skipped test as an error.
Please note normally when a test is marked as skipped in unittest framework, no setUp() or tearDown() would be called. The case we are trying to address here is a bit special, that the test is not skipped at the beginning (as a whole), instead, the skip decision is made at a later stage of the test when detecting missing extension.

WT-6592 Avoid marking errors for skipped Python tests due to not-built extension

---

src/include/reconcile.i

The expression `r->supd_next * WT_UPDATE_SIZE` uses 32-bit arithmetic and can overflow. We just need to cast one of the operands to a `size_t` and we should be fine.

WT-6649 Coverity: Unintentional integer overflow in __wt_rec_need_split

---

src/txn/txn.c
test/suite/test_txn23.py

This change decouple clearing the read timestamp from releasing snapshot. We now only clear the read timestamp when we release the transaction's resources after commit or rollback.
The tests including stress tests and mongodb tests look OK with the change.
The downside of the change is that in some cases, the read timestamps are cleared later than before, thus pinned timestamp may not be updated as aggressively as before causing more data to be pinned for slightly longer. But I think it shouldn't be a big deal.

WT-6583 Only clear the read timestamp when releasing the transaction

---

test/suite/test_bug019.py

@ddanderson I changed this test to use statistics instead of file names to ensure consumption since files can be returned in any order and the sets may not be disjoint. I also fixed a strange indentation I found in there.

WT-6762 Use stats instead of files to check consumption.

---

src/btree/row_modify.c

@lukech This does not fix the problem completely. The test is running out of memory. We need to move the unit test long to a larger machine.

WT-6763 Fix freeing update on the chain when insert fail after inserting to the update chain

---

test/csuite/random_directio/main.c
test/csuite/random_directio/util.c
test/csuite/random_directio/util.h

This change backs off the aggressive abort from WT-6765 and will let the test fail with the missing file on the recovery side to be sure we catch the correct situation.

WT-6806 Back off aggressive abort in random_directio.

---

test/evergreen.yml

Move below 2 existing code statistics related Evergreen tasks into a separate build variant for ease of tracking by test failure triaging barons. Also lower the scheduling frequency to once per day. 
- coverage-report
- cyclomatic-complexity

WT-6793 Organize code statistics Evergreen tasks

---

test/suite/test_prepare08.py

This test used to fail with rollback error due to cache pressure, looks like same test coverage can be achieved by increasing the cache size.

WT-6612 Increase cache size in test_prepare08 to fix rollback error due to cache pressure.

---

test/csuite/timestamp_abort/main.c

There is a possible race condition in test timestamp_abort where checkpoint thread is able to perform a checkpoint before writer threads get a chance to start and write something into the database. With this change checkpoint thread waits for the checkpoint timestamp to move beyond 0 before signalling to parent process via a file.

WT-6764 Wait for stable timestamp to move before publishing checkpoint information

---

dist/stat_data.py
src/evict/evict_page.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

These newly added stats are useful to track the number of evictions
that occurs during checkpoint is inprogress.

WT-6736 Statistics to track evictions in parallel with checkpoint

---

build_posix/configure.ac.in
dist/s_string.ok
src/include/gcc.h

Armv8 originally had load-exclusive/store-exclusive atomics. In Arm v8.1 these were extended with the Large Scale Extensions (LSE) which provided native atomic primitives such as compare-and-swap, load-and-add, etc which have been shown to scale much better on larger core-count systems. These are the default for -march=armv8.1-a, but to retain compatibility with older Arm systems the -moutline-atomics option is available which includes both new and old-style atomics and chooses dynamically. moutline-atomics is the default in gcc10 and has been backported to some distro gcc7 compilers as well as the official gcc 8 and 9 branches. Detect if the flag is available and if it is use it. 
bench/wtperf/runners/medium-btree.wtperf ops/s increases by 5x with  the flag applied.
Additionally, the …

WT-6798 Utilize Arm LSE atomics and the correct strength barriers

---

src/history/hs_rec.c
test/suite/test_timestamp20.py

As part of WT-6811, Luke noticed that the "out-of-order fixup" code appeared to be using the wrong value. I'm not 100% sure why `timestamp20` manages to pass but I suspect it's to do with the fact that the leading garbage in the value does not translate to valid ASCII characters and may be dropped as part of the conversion to a Python string.
I wrote another test that uses modifies since I suspect that these would be more sensitive to corruption and was able to make the API return garbage and sometimes crash. I also ran into the issue that modifies aren't moved correctly since we don't pass the correct `upd_type` in (we just read a byte pattern corresponding to a modify and return it as if it were a real value).

WT-6812 Fix "out-of-order fixup" potentially corrupting historical values

---

README

As part of #6088, the doc link got changed (I assume they did this because it's a dead link). I couldn't fix this in the PR because it was from a fork that I didn't have write permissions for.
I believe we still want this to point at 10.0.0 because the docs will be at this address when our 10.0.0 release is distributed.

WT-6828 Fix doc link in README

---

src/btree/bt_walk.c

This is to aid the debugging of WT-6770

WT-6869 Assert never return the page that started the walk in tree walk

---

examples/c/ex_all.c

This code was just here to generate documentation so I didn't notice it breaking compilation. We can just remove this since the import portion of the documentation doesn't exist anymore.

WT-6875 Remove legacy import invocation

---

dist/s_string.ok
src/include/gcc.h

Use an isb instruction here to be closer to the original x86 pause instruction.
The yield instruction that was previously here is a nop that is intended to
provide a hint that a thread is a SMT systems could yield. This is different
from the x86 pause instruction which delays exeuction by O(100) cycles. The isb
will typically delay exeuction by about 50 cycles so it's a reasonable
alternative.
I've marked this with RFC beacuse while we've seen similar changes improve
performance on other projects, I don't know what the best way is to test a
high-contention senario that would result in the pausing being impactful here.
I'm looking for suggestions of tests that would illustrate the benefit.

WT-6872 Replace the yield instructions with an ISB

---

test/format/backup.c
test/format/format.h

@keitharnoldsmith this is the same change from WT-6873 that showed hangs in test/format. The reason was that we needed to break out on getting EOF. I could easily reproduce the hangs. The file size can change during backup or by breaking up the large value from the cursor into smaller chunks we may read exactly on the EOF boundary. It no longer hangs with the addition of the fix.

WT-6883 Redo change for breaking up backup ranges and fix for EOF.

---

src/evict/evict_file.c
src/evict/evict_page.c
src/reconcile/rec_row.c
src/reconcile/rec_write.c

Do not cache HS cursor when operating on the metadata. Also do not set history store reconciliation flag, WT_REC_HS, when reconciling metadata or the history store itself. Some new asserts have been added and others modified to validate these assumptions.

WT-6868 Don't cache history store cursor for operations on metadata

---

test/format/format.sh

I've finally got around to doing this and am planning to do a session with the team next week introducing UndoDB to them.
One thing I wanted to do was to add basic integration for running `live-record` via our `format.sh` script since we use it all the time. This is pretty primitive and doesn't support forwarding arguments to `live-record` but I think that's ok since `resmoke` doesn't do that either. The `resmoke` script does set some arguments to change the way that the recording is named but I don't think that's necessary for us.

WT-6986 Add UndoDB support to format.sh

---

dist/api_config.py

It was recently found the text wrapping for `src/include/wiredtiger.in` when running `s_all` or `python api_config.py` under the `dist` directory became different for various versions of Python (2.7, 3.6, 3.7). It's suspected some updates to `re` or `textwrap` Python standard libraries may have triggered the text wrapping difference.
The solution is to make the line break regex to account for "one or more" word or certain punctuation, to make all `&nbsp;` stay on the same line (not wrapped in between).

WT-6983 Make wiredtiger.in text wrapping consistent across Python versions

---

src/include/txn_inline.h

Irrespective of whether the prepared update is visible or not, retry
the search again when the prepared update is either committed/rollbacked
in-parallel to search.

WT-6831 Retry search if we race with prepare update commit/rollback

---

src/include/txn_inline.h

There seems to be some issue with `upd->durable_ts` being written to when it is already in the chain and visible to other threads. If I copy the `upd->durable_ts` and check it, I see that it was previously 0 and then soon after, gets written with the same value as `upd->start_ts`. I'm thinking that there may be a missing write barrier somewhere.
I'm temporarily removing this assertion to stop the testing fallout and we can take our time to figure out what's going wrong here. I think the actual culprit is not related to WT-6861 so the rest of the code can remain.

WT-6861 Disable assertion when fetching prev_durable_ts

---

src/cursor/cur_backup.c
test/suite/test_backup13.py
test/suite/test_backup20.py

Metadata checkpoints assume they're running at read-committed isolation. MongoDB opens sessions explicitly at snapshot isolation. I wrapped the backup force_stop checkpoint call to enforce read-committed. I also updated our incremental backup test to use snapshot isolation and added the small reproducer for this.

WT-7027 Run the metadata checkpoint for force_stop at read-committed isolation.

---

dist/api_data.py
examples/c/ex_backup_block.c
src/config/config_def.c
src/cursor/cur_backup.c
src/cursor/cur_backup_incr.c
src/include/cursor.h
src/include/wiredtiger.in
test/format/backup.c
test/suite/test_backup11.py
test/suite/test_backup17.py

* WT-6835 Add consolidate API for incremental backup.
* Add python test for new backup API setting.
* Fix compiler warning.
* Remove extraneous increment.
* Review comments. Some fixes, a new test condition.
* clang-format whitespace
* Remove erroneous open_cursor line.
* Fix typo
(cherry picked from commit 56bac0f71605e24767a1002e4271ee2ff2271893)

WT-6835 Add API to consolidate incremental backup information (#6100)

---

test/suite/suite_random.py

Currently the suite_random.rand32() only returns values that are < 2^16, this PR fixes the precedence of operations to return 2^32 values. This PR needed to double check if it exposes any other tests through having a bigger value being returned

WT-6996 Fix suite_random.rand32() in python test suite

---

README

The existing doc link is not accessible because the 10.0.0 release has not been cut. Point the doc link to `develop/index.html` for now.

WT-7066 Point README doc link to develop/index.html

---

src/btree/bt_discard.c

@michaelcahill this is a change to the assertion added with the split generation code change from a few weeks ago. It is failing when a file is being swept. I added a clause for a dead dhandle. Please review that it fits your understanding of that new assertion.

WT-7065 Add check for WT_DHANDLE_DEAD to assertion.

---

test/suite/test_hs01.py

Added column store configurations to make scenarios, however, found that scenario 3 fails, so, added a conditional statement on scenario 3, as durable check when timestamp is true is not supported in columnar store yet. 
There is already a ticket to make durable check (timestamp = true) work. (WT-5545 Fix rollback to stable for fixed length columnar storage type objects)

WT-7067 Add column store to test_hs01

---

test/evergreen.yml
test/suite/run.py
test/suite/suite_random.py
test/suite/test_cursor13.py
test/suite/wttest.py

The purpose of this ticket is to investigate the possibility of adding more randomness to the python test suite. This can be done through giving the option to randomise the seed for random numbers. This achieves more test coverage through generating unpredictable random numbers through the option of **-R**,  and the option of running two specific random integer seeds is now available through **-S**
The reason for the generating the random seed from 1-2^32, is to make sure that the seed doesn't get 0, which isn't allowed in the formula for generating random numbers
The random seed will only be used in a test case when the "@wttest.randomseed()" is applied to the test case, therefore using the random seed for specific tests.

WT-6981 Add randomness to Python test suite runs

---

src/cursor/cur_backup.c
test/suite/test_backup13.py
test/suite/test_backup20.py

Backporting WT-7027 (and dependent change in WT-6844) to v4.2
Cherry-picked commits: 
- WT-7027: `1bc96db` 
- WT-6844: `be01a2f`

WT-7027 Run the metadata checkpoint for force_stop at read-committed isolation for incremental backup (v4.2 backport)

---

test/suite/test_hs09.py

This change allows the test to skip prepared updates in the datastore if eviction runs.

WT-6772 Add support for prepared updates in datastore for test_hs09

---

src/docs/spell.ok

A doc spelling check warning was captured by the "aws-perf" machine which was running a relatively old version of aspell. Adding the related word into the spell.ok list to make spelling check happy. 
```
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Documentation spelling notes
Update src/docs/spell.ok to remove warnings.
decrement
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

WT-6901 Fix warning for doc spelling check

---

test/evergreen/compatibility_test_for_releases.sh

This test is to ensure the newer version can able to dump an older
version database table and load it back.

WT-7116 Add a wt dump/load to the compatibility test

---

src/history/hs_rec.c

We added a new assert WT-6751 to verify we are not inserting duplicate key-value pairs to history store. This check doesn't consider the globally visible stop time on the existing values.

WT-7137 Update an assert to consider globally visible stop time for HS values

---

build_posix/Make.subdirs
build_posix/aclocal/options.m4
build_posix/configure.ac.in
src/docs/tool-libfuzzer.dox

There's been some fallout on the PPC machines due to some difference in the toolchain.
It's not worth getting into a discussion with the build team about what packages need to be installed on that variant. So I'm just going to disable it on PPC and make WT-7158 in case we see value in the future.

WT-6840 Only build with LibFuzzer when configured with --enable-libfuzzer

---

test/suite/test_util18.py
test/suite/test_util19.py
test/suite/test_util20.py

Extended the python util test set (test_utilX.py) with a series of small tests for the `upgrade`, `downgrade`, `printlog` functionality. This is intended to extend the wt utility test coverage where it was missing specific test coverage for the above functions.

WT-6354 Increase wt utility coverage with printlog, downgrade, upgrade tests

---

src/history/hs_rec.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable14.py

The updates written to the data store are always full updates, but
when these updates are moved into the history store by eviction due
to further updates on the key, make sure that on-disk update is always
written as full update even in the update list it is a modify, because
the on-disk update will be the base update for all the history store
updates that are previous to the on-disk update.
Due to concurrent operation of checkpoint and eviction, it is possible
that history store may have more recent versions of a key than the
on-disk version. Without a proper base value in the history store,
it can lead to wrong value being restored by the RTS.

WT-7159 Always write on-disk update as a full update to history store

---

test/evergreen/compatibility_test_for_releases.sh

WT doesn't support dump and load from a newer version database by
older version of WT due to incompatibility with newer configuration
options that are added in newer releases. Don't test dump/load for
forward compatibility.

WT-7167 Do not perform forward compatibility test with wt dump/load

---

test/evergreen.yml

My testing patch build ran into the failure of WT-7045 3 times in a row, which may indicate the failure would become more frequently hit after switching to macos-1014. WT-7045 failed frequent enough on waterfall builds, and I labelled it as a CI-blocker so that it could be planned for the next sprint.

WT-5137 Switch to macos-1014 Evergreen distro

---

dist/s_docs
src/docs/backup.dox
src/docs/tool-xray.dox

The github diff doesn't show the bad characters very well, here's what they look like with `git diff`:
```
$ git diff develop src/docs/
diff --git a/src/docs/backup.dox b/src/docs/backup.dox
index 265253d89..5f333eca1 100644
--- a/src/docs/backup.dox
+++ b/src/docs/backup.dox
@@ -121,7 +121,7 @@ The following is the procedure for incrementally backing up a database
using block modifications:
1. Perform a full backup of the database (as described above), with the
-additional configuration \c incremental=(enabled=true,this_id=<E2><80><9D>ID1<E2><80><9D>).
+additional configuration \c incremental=(enabled=true,this_id="ID1").
The identifier specified in \c this_id starts block tracking and that
identifier can be used in the future as the source of an incremental
backup.
diff --git …
```

WT-7184 add check for non-ASCII chars in documentation input files

---

src/cursor/cur_file.c
src/include/dhandle.h
src/session/session_api.c

Simplify the WT_DHANDLE_CAN_REOPEN macro, it will no longer return true for some
weird flag combinations.  Use this macro when reopening as a final check.
When doing the sweep check, even if the cursor is otherwise
"reopenable", don't allow sweeping of a cursor that is using the current
dhandle. Remove the assertion that used to protect that case, as it
can no longer happen.

WT-7192 Fixes for cached cursor sweep.

---

dist/s_string.ok
src/cursor/cur_log.c
src/include/extern.h
src/include/log.h
src/log/log.c
src/txn/txn_log.c
src/txn/txn_recover.c
src/utilities/util.h
src/utilities/util_misc.c
src/utilities/util_printlog.c
test/suite/suite_subprocess.py
test/suite/test_txn08.py
test/suite/test_txn19.py

* Added optional arguments [-l start-file,start-offset]|[-l start-file,start-offset,end-file,end-offset] to start and stop the printlog at given LSN's. Details included in the printlog usage string.
* Added python tests to test_txn08 to test the start, stop functionality.
(cherry picked from commit e39ffb554160de902060cd063c4b1547ff6d5e1e)

WT-6309 Add support for start/stop arguments to wt printlog command (v4.2 backport)

---

dist/s_string.ok
src/include/wiredtiger.in

This is incompatible with older versions of doxygen that we want
to make the wiredtiger docs compatible with. This simply reverts
a change introduced in e99db726.

WT-6714 Remove usages of parblock in docs

---

test/evergreen.yml

Switch the compile task back to using the older but more stable `macos-1012` Evergreen disto, to avoid being hit by the long queue issue on the newer `macos-1014` distro. Will add macOS compile task back into the PR testing scope once this change is merged.

WT-7214 Run macOS compile task on macos-1012 Evergreen distro

---

test/suite/helper.py
test/suite/test_backup05.py
test/suite/test_backup09.py
test/suite/test_backup13.py
test/suite/test_bug014.py
test/suite/test_bug018.py
test/suite/test_checkpoint_snapshot01.py
test/suite/test_cursor12.py
test/suite/test_durability01.py
test/suite/test_hs01.py
test/suite/test_prepare_hs03.py
test/suite/test_prepare_hs04.py
test/suite/test_readonly02.py
test/suite/test_rollback_to_stable07.py
test/suite/test_rollback_to_stable10.py
test/suite/test_rollback_to_stable11.py
test/suite/test_rollback_to_stable12.py
test/suite/test_rollback_to_stable13.py
test/suite/test_rollback_to_stable14.py
test/suite/test_timestamp03.py
test/suite/test_timestamp06.py
test/suite/test_timestamp07.py
test/suite/test_txn10.py
test/suite/test_txn14.py

This PR updates usages of the `simulate_crash_restart` and `copy_wiredtiger_home` helpers to be able to tolerate a potential race condition in the python tests. The error more specifically being a `FileNotFoundError` as a testing thread starts copying wiredtiger log files whilst they are being archived/removed by a background log server thread. In particular this PR adds the following key changes:
* Try/Except block in`copy_wiredtiger_home` : To catch the case when a wiredtiger log file gets removed as its being copied
* Updated the implementation of `simulate_crash_restart` to be a small wrapper around `copy_wiredtiger_home` due to near identical functionality + centralized the helper to remove code duplication.

WT-7045 Fix FileNotFoundError in simulate_crash_restart

---

src/btree/bt_debug.c
src/btree/bt_vrfy.c
test/suite/test_util21.py

This ticket refactors **__verify_key_hs** to use the new history store interface. Also included in this ticket is how we grab the hs cursor when printing out the page values from the btree, and adding a read committed flag, to allow history see the values visibly when running wt verify.

WT-7225 Restructure verify key function for the history store

---

src/os_posix/os_fs.c

Remove redundant code which was pushed as part of WT-6673

WT-7252 Remove redundant code

---

src/btree/bt_debug.c
src/btree/bt_vrfy.c
src/cursor/cur_hs.c
src/evict/evict_page.c
src/history/hs_conn.c
src/history/hs_verify.c
src/include/extern.h
src/include/session.h

Remove the deprecated HS cursor as part of the history store project. This also involves the code that affects running the **hs_cursor** from the session. Also added in some close to cursors that would be left open. Ran a patch build to make sure that deleted changes are fine.

WT-7246 Remove old HS cursor from session

---

dist/s_void
src/btree/bt_debug.c
src/btree/bt_delete.c
src/btree/bt_vrfy.c
src/cursor/cur_hs.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/history/hs_cursor.c
src/history/hs_rec.c
src/history/hs_verify.c
src/include/extern.h
src/txn/txn.c
src/txn/txn_rollback_to_stable.c

This ticket involves renaming some of the functions inside cur_hs.c, some of the functions need **__wt** removed as it is only used inside the file. This ticket also involves changing the **hs_cursor** name back to old convention of **curhs**

WT-7254 clean function names inside cur_hs

---

test/suite/test_import10.py

This ticket involves adding a python test that tests doing a live import while a backup cursor is open.

WT-7210 Add testing for import/export while a backup cursor is open

---

dist/s_typedef
examples/c/ex_storage_source.c
src/conn/conn_api.c
src/include/wiredtiger.in

Add a way to get a storage source by name.
Give WT_LOCATION_HANDLE a close method.
Add API doc comments to tighten up the API behavior.
Adjust the example according to the new API.
Made some small style fixes in the example as well.

WT-7249 Improve the storage source extension API.

---

build_posix/aclocal/options.m4
build_win/wiredtiger_config.h
src/docs/upgrade.dox
src/include/btree.h
src/meta/meta_ckpt.c

The overall changes are 
- Enable WT_STANDALONE_BUILD by default in WiredTiger build.
- Check for a version mismatch if WT_STANDALONE_BUILD is defined and if compatibility has not been configured.
- Add a configuration option --disable-standalone-build to build WiredTiger similar to MongoDB.
- Update documentation page.

WT-5886 Compatibility with older versions of WT

---

src/schema/schema_project.c

When performing a schema project on a set of input columns we grow our input cursors buffer with more memory than is required to write out a given applications columns. Whilst this doesn't impact the overall functionality we do create trailing uninitialised memory that will be flagged by Clang's 'msan' as it gets reconciled.
The following changes adjust the buffer allocation calculations to account for when the schema projection is re-using/overwriting the memory of a previously allocated column.

WT-7150 Trailing uninitialized mem in schema_project_in

---

src/os_posix/os_fallocate.c

This ticket involves removing the printing of an error message when calling WT_CALL_FUNCTION. WT_CALL_FUNCTION is used for checking suitable `fallocate` functions. The reason is that customers are worried with the error messages that are produced, is that wiredtiger tests multiple `fallocate` solutions, and when they don't exist an ENOTSUP error message is printed towards the logs. 
Therefore it has been requested that the error messages to be removed, to remove confusion. This functionality has been tested with the `mongod` binary inside a testing machine, and successfully removed the messages.
Assumption: System configurations are all setup for ENOTSUPP messages to occur.(For more information refer to ticket).
Steps taken to confirm fix:
1. Tested mongod 4.2 and found no ENOTSUP …

WT-7223 WT_CALL_FUNCTION should not print out a message

---

test/evergreen.yml
test/evergreen/verify_wt_datafiles.sh
test/format/CONFIG.endian
test/format/config.c

The aim is to enable the tests for Evergreen testing. There are two major changes:
- `format` doesn't support column store configs at the moment and therefore I have disabled them by explicitly adding row-store config.
- Although we have logging selected in config, `format` can override that config if it's incompatible with other randomly selected config options. I have modified the script to look for log files only if they were created.

WT-6066 Enable datafile test

---

test/evergreen.yml

With this change `unit-test` does not depend on the compile task, it gets the project and compiles it in the current machine.

WT-7239 Fix unit-test of OS X 10.14 machine.

---

src/include/tiered.h
src/tiered/tiered_cursor.c
test/suite/test_tiered01.py

This is a strictly mechanical change that changes "LSM" in comments and variable names to "tiered" and "chunk" to "tier.
I've also removed the chunk_size parameter from test_tiered01.py since tiered tables don't use that value.

WT-7298 Remove LSM references from tiered cursor code

---

test/evergreen.yml

The documentation build task is currently performed by a Jenkins job `wiredtiger-doc-build` with a special setup that can only run on a given machine. A cron job was run hourly to pick up the build result and "git push" to the `wiredtiger.github.com` repo using people's Github credential. We need to migrate the job out of Jenkins, and taking the chance to implement it in a proper way. 
- A new Github bot user `svc-bot-doc-build` (together with credential) is created, which we'll use to run git push.  
- A new Evergreen task `doc-update` is created calling 2 sub functions to build & update documentation into wiredtiger website, for all supported branches - similar as what we currently adopt in the Jenkins job and cron script. 
- `doc-update-github-token` is provisioned as a private …

WT-7160 Migrate wiredtiger-doc-build job to Evergreen

---

bench/workgen/runner/many-dhandle-stress.py
bench/workgen/wtperf.py
bench/wtperf/runners/many-dhandle-stress.wtperf

Imported `many-dhandle-stress.wtperf` to `many-dhandle-stress.py` from `wtperf.py` script. 
Increased `random_range` and `icount` because `wtperf.py` does some divisibility checking with these numbers and expect it to be divisible with `table_count`. (random_range+icount)/table_count.

WT-7290 Import many-dhandle-stress.wtperf to workload

---

src/btree/bt_handle.c
src/txn/txn_recover.c
test/suite/test_checkpoint_snapshot04.py

Use connection base write generation as btree base write generation
when the checkpoint run write generation is less than the last checkpointed
connection base write generation number. This scenario is possible only
when rollback to stable doesn't get performed during the recovery.

WT-7302 Use last connection base write generation as a minimum base write generation for a btree

---

test/evergreen.yml

The comment and `batchtime` setting conflict with each others. Fix the batchtime setting to line up with the comment (intended testing frequency) for the 2 builders.

WT-7360 Fix batchtime setting for some Evergreen builders

---

src/history/hs_conn.c
src/txn/txn_recover.c
test/suite/test_rollback_to_stable10.py

- The history store file size stat is now set in __wt_txn_recover.
- The test test_rollback_to_stable10.py has been edited to check the history store file size stat before and after a simulated crash.

WT-7060 Set the history store file size stat on startup

---

test/evergreen.yml

According to [Evergreen wiki](https://github.com/evergreen-ci/evergreen/wiki/Project-Configuration-Files#commit-only-patch-only-and-git-tag-only-tasks), the `patchable: false` attribute setting can be used to make a task run only in commit builds (not patch builds). 
The `doc-update` task is such a task that we expect to run only in commit builds.

WT-7361 Remove doc-update task from patch build

---

dist/s_string.ok
src/include/serial_inline.h

This ticket involves removing running **__wt_update_obsolete_check** when dealing with the history store. This is because it is possible that we access freed memory when there are two internal readers reading the history store. The ticket describes the scenario in detail on how this can be possible.

WT-7349 Free memory access when walking through HS during eviction

---

test/evergreen.yml

There is a build failure reported against doc-update [task](https://evergreen.mongodb.com/task/wiredtiger_mongo_v4.4_doc_update_doc_update_8f90c3c2923040725fb424b3a5c510bacc4ce380_21_03_26_04_39_34) on the `mongodb-4.4` branch waterfall page, regarding the non-existent `wiredtiger.github.com` directory. The directory is supposed to be created when checking out the corresponding git repo, only if the task is running on the Evergreen project that's configured for the wiredtiger 'develop' branch. 
The shell that is to run git push command did not have the branch checking logic in place to bypass the remaining code, and ran into this directory-not-found issue. 
The fix is simply adding the branch checking logic in for the affected Evergreen shell.

WT-7374 Add missing branch checking logic for doc-update task

---

src/reconcile/rec_visibility.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable01.py
test/suite/test_rollback_to_stable18.py

Remove the updates from the page only when both the start and stop time windows
are globally visible if the update has both time windows. Otherwise, the start time window.
Change the default value of rollback to stable to check for any unstable updates of a page
when the page doesn't have any aggregated time window information to avoid
rollback to stable skipping any pages with unstable updates.

WT-7367 Do not remove unstable updates of an in-memory database btree page

---

dist/api_data.py
src/config/config_def.c
src/include/wiredtiger.in

I modified (but did not commit) `test_tiered04.py` to reconfigure `auth_token`. It passed in the current tree and failed with the expected invalid configuration on this branch.

WT-7385 Remove 'auth_token' from being reconfigurable.

---

src/cursor/cur_std.c
src/include/tiered.h
src/tiered/tiered_cursor.c

Eliminate the name field of WT_TIERED in favor of the table name/uri which is already stored in the dhandle within WT_TIERED.
Also, since there are multiple places in the cursor code that assume `cursor->uri_internal` hold a valid string, add assert that it is set in `wt_cursor_init()`.

WT-7376 Initialize tiered cursor name

---

test/suite/test_hs21.py

Added a new test to validate we don't lose any data when idle files with an active history are closed/sweeped. With WT-6819
files with active history, ie content newer than the oldest timestamp, can be closed when idle. This test ensures that when an
active history file is idle closed we can continue reading the correct version of data and their base write generation hasn't changed (since we haven't restarted the system)

WT-7266  Test to validate re-reading files that were closed with active history

---

src/tiered/tiered_cursor.c

Rather than always using `cursor->insert()` to store the tombstone, we should use `insert()` or `update()` according to whether we need to leave the cursor positioned (i.e., whether it was positioned at the time of the `remove()`). This happens in `curtiered_put()` which is the common code for inserting something into the tables under the tiered cursor.
This change basically copies the relevant code from {{clam_put()}}.  After puzzling over what to do for a reserve operation that wants an unpositioned cursor, I realized that's impossible give the current implementation and API. So I've added an ASSERT that this doesn't happen.

WT-7389 Remove on positioned tiered cursor should leave cursor positioned

---

test/suite/hook_tiered.py

Python hook file (see WT-7329) to repurpose existing cursor tests to use cursors on tiered tables.  Currently this will not be included in automated PR or Evergreen tests.  I'm just merging it so we have the tools for future Tiered Storage work.
Feedback on my Python usage welcome.

WT-7355 Create python hooks to valudate tiered cursor implementation

---

src/btree/bt_random.c

If the tree is entirely populated with large items (MongoDB configures the maximum leaf page item to avoid overflow objects), we can still end up reading huge amounts of data on every random cursor sample. If the page is clean (that is, just read from disk), it can't be fully populated with deleted items, use it as our sample.

WT-7373 Investigate slow random cursor operations on oplog

---

ext/storage_sources/local_store/local_store.c
src/conn/conn_api.c
src/include/wiredtiger_ext.h
test/suite/test_tiered06.py

For the local file system open, use the WT file system to get a file handle, rather than using POSIX file descriptors directly.
This makes for a cleaner implementation.  Get rid of marker files and temp files. We don't need temp files because our model is to behave exactly like a "regular" file system until flush occurs. We also don't need a flush marker, when a flush occurs, we chmod the file to readonly.  That matches the semantics - flushed files are by definition immutable.

WT-7419 Tiered local storage changes to use WT file system.

---

src/btree/bt_random.c

If the tree is entirely populated with large items (MongoDB configures the maximum leaf page item to avoid overflow objects), we can still end up reading huge amounts of data on every random cursor sample. If the page is clean (that is, just read from disk), it can't be fully populated with deleted items, use it as our sample.
(cherry picked from commit a809a25052cf614f2d8fbcb4ff93a136b6d9a84f)

WT-7373 Improve slow random cursor operations on oplog (#6466) (v4.4 backport)

---

test/suite/test_backup21.py
test/suite/test_import10.py
test/suite/wtthread.py

This ticket involves creating a python test to testing create/drop operations while a backup is ongoing. The behaviour is that no changes should occur while analysing the backup cursor files.

WT-7414 Create a python test to ensure that all tables that are dropped during backup are exists in the backup

---

src/btree/bt_random.c

If the tree is entirely populated with large items (MongoDB configures the maximum leaf page item to avoid overflow objects), we can still end up reading huge amounts of data on every random cursor sample. If the page is clean (that is, just read from disk), it can't be fully populated with deleted items, use it as our sample.
(cherry picked from commit a809a25052cf614f2d8fbcb4ff93a136b6d9a84f)
Co-authored-by: Keith Bostic <keith.bostic@mongodb.com>
(cherry picked from commit 885403077cfdbabc8107b9522af57513952e6f85)

WT-7373 Improve slow random cursor operations on oplog (#6466) (#6476) (v4.2 backport)

---

ext/storage_sources/local_store/local_store.c
src/include/wiredtiger.in
test/suite/test_tiered06.py

A new "cache_directory" config parameter is now available when
customizing a file system. New files are placed there, and copied
to the bucket directory only when flushed.  Currently no files
are "aged out" of cache nor are "paged in" to cache.

WT-7420 Tiered local storage changed to flush files to bucket directory.

---

src/cursor/cur_std.c
src/include/extern.h
src/session/session_api.c

This change is to set the computed hash value in `cursor->uri_hash`while opening a cursor and with this approach, we will reduce one hash computation during cursor close.

WT-7092 Reduce hash calls during cursor open/close

---

src/btree/bt_io.c
src/include/cell_inline.h
src/reconcile/rec_write.c

Set write generation number whenever the page image is created instead of
waiting for it to be written to disk. In scenarios, when the page image is instantiated
it can lead to misuse of the stale transaction ids present on the page.
(cherry picked from commit b3e3b2580ce14e7609e7ba269d3c7432f81339b7)

WT-7426 Set write generation number when the page image gets created (#6474) (v4.4 backport)

---

src/txn/txn_ckpt.c

This ticket involves researching if there could be a potential race condition between backup and checkpoint at file close. This race condition can only happen if:
- It is not the last checkpoint for the system
- We don't have the schema lock
- We don't have the checkpoint lock 
Thus, upon researching, the assert was never hit. It would be useful to still include this assert to prevent future possible race conditions.

WT-6204 Possible race between backup and checkpoint at file close

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable19.py

It is only possible for the prepared transactions to have an on-disk
data with both start and stop time windows are the same and the
prepared timestamp is less than the stable timestamp. RTS must
abort all the updates from the prepared transaction either by
replacing it with stable data or remove the key.
(cherry picked from commit cf79d062ecdaa7509ca80c4a643268ee5303e915)

WT-7460 RTS to abort all the updates from a prepared transaction (#6496) (v4.4 backport)

---

src/evict/evict_page.c

The modified variable will always be true if this part of the code is reached.

WT-7458 Coverity redundant condition check in evict page

---

src/reconcile/rec_dictionary.c

Replacement of FNV hash function to City hash function as the latter hashes 8 bytes at a time, while the former hashes 1 byte at a time.

WT-7191 Use of hash_city64 over hash_fnv64

---

dist/stat_data.py
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable20.py
test/suite/test_txn16.py

The main changes are for rollback to stable to open dhandles only when the dhandle has unstable updates.
(cherry picked from commit e3efbee8a31d9802b20f96f67a2f0f6191aeedb0)

WT-7442 RTS to open dhandle only when the dhandle has unstable updates (#6506) (v4.4 backport)

---

src/schema/schema_create.c

This involves clearing the checkpoint LSN and the backup information when importing a table. These values are only relevant from old database.

WT-7423 Clear checkpoint LSN and backup metadata on import

---

src/btree/bt_cursor.c

Turn off cursor-order checks in all cases on search. The search/search-near functions turn them back on after a successful search.

WT-7474 Reset cursor-order checks whenever a search is performed

---

test/suite/test_rollback_to_stable10.py
test/suite/test_rollback_to_stable14.py

Prepared updates are restored on to the page when the page gets loaded
into memory, so it is possible that there can be in-memory abort updates.

WT-7186 Correct expected in-memory abort updates in prepare scenario

---

src/tiered/tiered_handle.c

Removed some debugging code I left in because Coverity doesn't like it. We don't need to have it.

WT-7488 Remove verbose output for Coverity.

---

src/conn/conn_api.c
src/txn/txn_rollback_to_stable.c

RTS cannot run concurrently with checkpoints, lock them out.

WT-7489 rollback to stable can fail if running concurrently with a checkpoint

---

src/history/hs_rec.c

Updated the history store reconciliation code to increase the frequency of reverse modifies by allowing standard updates to be stored as deltas. Additionally, ensure the most recent update in the chain gets reconciled as a full update through checking if it has already been written on the data store.
In addition, when reconciling history store standard updates, limit the number of consecutive reverse modifies as to avoid impacting reading performance.

WT-7106 Reverse deltas are performed on standard updates

---

CMakeLists.txt
build_cmake/configs/base.cmake
build_cmake/configs/modes.cmake
dist/s_string.ok
test/csuite/CMakeLists.txt
test/csuite/timestamp_abort/smoke.sh
test/csuite/wt2909_checkpoint_integrity/main.c
test/csuite/wt3120_filesys/main.c
test/csuite/wt4333_handle_locks/main.c
test/ctest_helpers.cmake
test/syscall/syscall.py
test/utility/CMakeLists.txt
test/utility/misc.c
test/utility/parse_opts.c
test/utility/test_util.h

This PR appends some additional fixes to the final CMake POSIX support, to be merged with all the other changes under WT-7348.
More specifically, this PR adds:
* Fixes to `define_csuite_test` helper so we can run csuite tests in parallel without them running over each other
* Adjustments to the following C tests:
*  Prevent `wt2909_checkpoint_integrity` & `wt3120_filesys` from assuming the build location of the fail fs extension
library/module
* Avoid `syscall` test assuming the layout of `build_posix`
* Avoid compiling with `fPIC` for static builds
*  Respect CMake Build Modes: Making it IDE friendly
*  ASAN and UBSan build mode

WT-7348 CMake Complete POSIX support fixes

---

test/suite/run.py

When running the python test suite with a CMake generated build we can no longer depend on falling back to a build directory of `build_posix`. Users can dynamically define the name of their CMake build directory and create multiple working builds of varying names. To avoid incorrectly assuming the build exists in `build_posix`, provide an opportunity to read an env variable 'WT_BUILDDIR' indicating the location of the build we want to use for the test.
Note: We can mostly depend on invoking the python test in the working build directory e.g. `python3 ../test/suite/run.py`, however this approach doesn't work when the test starts spawning sub processes from different working directories e.g. invoking `run_subprocess_function`(or the user generally wants to invoke the test in a different …

WT-7348 WT_BUILDDIR option in python test runner

---

src/btree/bt_split.c

When the cache is configured for scrub dirty pages, consider the
update restore eviction as a progress when the page doesn't have
any skipped updates.

WT-7531 Consider update restore eviction as a progress

---

CMakeLists.txt
build_cmake/configs/modes.cmake
build_cmake/install/install.cmake
ext/compressors/lz4/CMakeLists.txt
ext/compressors/snappy/CMakeLists.txt
ext/compressors/zlib/CMakeLists.txt
ext/compressors/zstd/CMakeLists.txt

Adds two small fixes to the Darwin POSIX support merged as a result of WT-7348. This changes include:
* Check whether compiling with GCC or Clang for ASAN and UBSAN since they have slightly different linker definition. We also need to move the inclusion of the modes config file to after the project definition to ensure 'CMAKE_C_COMPILER_ID' has been defined.
* Older versions of CMake 3.10 & 3.11 are unable to have install definitions referring to subdirectory projects. We need to have these definitions at the same project scope when defining extension install targets.

WT-7348 Fix Darwin POSIX issues

---

test/evergreen.yml

I updated `evergreen.yml` to use the `ubuntu1804-large` and `rhel80-large` distros for `unit-test-long`. These distros have 64GB of memory which should be more than enough to resolve the memory issues in the tests.

WT-6555 Fix memory error in test_txn13

---

test/suite/test_hs21.py

After investigating, it seems like a lot of the failures are happening on PPC machines where checkpoint is hanging after the test completes but before shutdown. The idea is to make the Python test less intensive.

WT-7504 test_hs21 cache stuck dirty

---

build_cmake/configs/auto.cmake
lang/python/CMakeLists.txt

This PR adds some small fixes encountered with newer toolchains on MacOS. This PR adds the following:
* The CMake 'test_big_endian' can return an unset variable, capture this case as to avoid having an empty default value. This will fail to configure otherwise.
* The SWIG generated code for the Python API triggers additional on-by-default Clang diagnostic errors on newer versions of Clang on MacOS. Turn these off to avoid compilation failures.

WT-7602 Fix MacOS CMake Compilation Issues

---

src/cursor/cur_hs.c
src/history/hs_rec.c
src/include/cursor.h
src/include/extern.h

Our history store cursor insert implementation performs a few calls after the actual insertion into the history store stable. If these fail, the insert will return non-zero.
This means that we may bail out of reconciliation without marking the inserted update with the `WT_UPDATE_HS` flag, leading us to try inserting it again in a subsequent reconciliation.
Unfortunately, this punches a hole through our cursor abstraction... but I think it's necessary for now. The priority is to fix this but we should come up with a cleaner way to deal with this in the future.

WT-7595 Add flag to history store cursor to track whether underlying table insertion was successful

---

dist/s_all
dist/s_docs
dist/s_docs_plantuml
dist/s_export
dist/s_string
dist/s_tags
src/docs/Doxyfile
src/docs/build-posix.dox
src/docs/introduction.dox
src/docs/spell.ok
src/docs/tools/doxfilter.py
test/evergreen.yml

@lukech, @jiechenbo: e1adc17 and 06b1413 upgrade the docs to doxygen 1.8.17 and skips building the documentation if the installed doxygen isn't that version or newer. (That means the documentation won't build until we build on a system with 1.8.17 installed, of course.)
@ddanderson, 65d64c8 and 298b964 are yours. I ended up leaving the architecture files in the `src/docs` directory, as that seemed simplest. I labeled them with a "warning: maybe not correct" message, and de-emphasized them in the introductory documentation page.

WT-7437 Upgrade documentation to doxygen 1.8.17

---

test/evergreen.yml

Switch distro to Ubuntu 20.04 for the `doc-update` Evergreen task.
Swap mongodb-3.6 with mongodb-5.0 branch in `update wiredtiger docs` function.
Switch distro back to Ubuntu 18.04 for the little-endian builder (undesired to switch).

WT-7633 Switch doc-update Evergreen task to newer Ubuntu 20.04 distro

---

src/btree/bt_split.c

When the cache is configured for scrub dirty pages, consider the
update restore eviction as a progress when the page doesn't have
any skipped updates.

WT-7531 Consider scrub update restore eviction as a progress

---

test/format/wts.c

Updated test/format to configure the table with 'write_timestamp_usage=key_consistent' when doing timestamp runs.
Using 'write_timestamp_usage=always' end up being incompatible when trying to use the test/format produced database with other wt utilities and applications that are not timestamp aware. Resulting in assertion failures.

WT-7594 Use key_consistent mode on format TS runs

---

src/reconcile/rec_visibility.c

In order to reduce complexity of __wt_rec_upd_select two methods were extracted: ___timestamp_sanity_check_ and ___rec_need_save_upd_ Ideally, there should be more refactoring done. The method is still quite long.

WT-7585 Cyclomatic-complexity test failing

---

build_cmake/toolchains/cl.cmake
build_cmake/toolchains/mongodbtoolchain_v3_clang.cmake
build_cmake/toolchains/mongodbtoolchain_v3_gcc.cmake
examples/CMakeLists.txt
test/evergreen.yml
test/evergreen/build_windows.ps1
test/evergreen/find_cmake.sh
test/fops/CMakeLists.txt
test/format/CMakeLists.txt
test/format/format.h
test/manydbs/CMakeLists.txt

This PR adds evergreen support for building WiredTiger with CMake. It also adds build variants that run the compilation & unit testing tasks with our CMake builds.
Whilst we continue to support autoconf and SCons, I've left most of the evergreen build tasks as they currently are. The tests under the CMake variants are only a small subset of what is currently being tested. This is done to avoid unnecessary duplicate test runs. The main objective of these new tests are to ensure the CMake builds are always working as expected and correctly configures+compiles the WiredTiger library and its associated binaries.
---
More specifically this PR adds the following features:
- Updated the evergreen configure and build functions to optionally support a CMake build.
- Extended 'make check' and 'unit …

WT-7231 Evergreen jobs for compiling WiredTiger using CMAKE

---

dist/s_define.list
dist/s_string.ok
src/block/block_addr.c
src/block/block_ext.c
src/block/block_read.c
src/include/btmem.h
src/include/error.h
src/include/misc.h
src/include/msvc.h
src/include/optrack.h
test/cppsuite/test_harness/test.h
test/cppsuite/tests/run.cxx
test/utility/test_util.h

Hitting an assert in the test framework now looks like this:
```
$ ./run 
example_test: FAILED: void test_harness::connection_manager::create(const string&, const string&)/72: false
example_test: process aborting
Aborted (core dumped)
```
In C code, it remains unchanged. Here's an example in `format`:
```
t: FAILED: row_update/1601: false
t: process aborting
```

WT-7648 Improve error messaging in the test framework

---

test/evergreen.yml

We did not turn "make check" tests on Windows previously, and it's not very surprising certain tests fail. Let's disable the make-check-test task from Windows CMake builder for now to address the test (manydbs) fallout.

WT-7672 Remove make-check-test from Windows CMake Evergreen build variant

---

src/history/hs_rec.c

We're currently having issues with duplicate insertions into the history store. This is not harmful in the case of full updates but could cause invalid values to be read for modifies.
While we're trying to solve this, I want to gain an understanding of whether this can only happen with full updates so I'm adding an assertion to distinguish between these two cases.

WT-7666 Add assertion to check whether duplicate history store inserts are modifies

---

src/txn/txn.c

We don't expect recovery to be using timestamps when applying commits. If a table is configured with write timestamp asserts, being `assert=(write_timestamp=on),write_timestamp_usage=always)`, the recovery process will trigger asserts and fail. To avoid failing/blocking recovery, updated the timestamp assert to be skipped on a recovery connection.

WT-7649 Skip timestamp assert during recovery

---

src/txn/txn_rollback_to_stable.c

Rollback-to-stable rolls back instantiated fast-truncate pages twice, once when processing the parent internal page and a second time when processing the child leaf page.
I don't see a problem in the current code, but it's dangerous because rollback-to-stable uses the WT_PAGE_DELETED.durable_timestamp value to determine if rollback is needed. When a page is instantiated, the WT_PAGE_DELETED.durable_timestamp moves from the WT_PAGE_DELETED structure to the individual WT_UPDATE structures, so after instantiation rollback-to-stable is taking the value from the wrong source.
Change rollback-to-stable to only check WT_PAGE_DELETED.durable_timestamp for pages that have not yet been instantiated.

WT-7674 reduce rollback-to-stable work for fast-truncate pages

---

src/txn/txn_rollback_to_stable.c

Refactor __rollback_to_stable_btree_apply() into two separate functions, __rollback_to_stable_btree_apply_all() which performs RTS on all files, and __rollback_to_stable_btree_apply() which performs RTS on a single file.
Wrap __rollback_to_stable_btree_apply() in a set/clear of WT_SESSION_QUIET_CORRUPT_FILE.

WT-7680 refactor rollback-to-stable to support operating on individual files

---

test/suite/hook_tiered.py
test/suite/wttest.py

Updated test to add tiered storage options to config for
wiredtiger_open().  The test then ignores tiered storage
for tests that aren't on simple row-store tables.  It also
calls flush_tier() after every checkpoint call.

WT-7644 Implement python hooks for tiered storage

---

examples/c/ex_file_system.c
src/history/hs_rec.c
src/txn/txn_ckpt.c

Fix the assertion failure by changing where we update the statistic that measures the history store file size.

WT-7556 Fix test_rollback_to_stable10 failure cache_hs_ondisk is 0

---

src/cursor/cur_hs.c

If the insertion code path fails in the history store cursor, we can free the same update twice. We can easily reproduce this by injecting an error with a patch like this:
```
modified   src/cursor/cur_hs.c                                                                                                                                                        
@@ -914,6 +914,11 @@ __curhs_insert(WT_CURSOR *cursor)                                                                                                                                
hs_upd = hs_tombstone;                                                                                                                                                       
} …
```

WT-7689 Fix double free in `__curhs_insert`

---

bench/workgen/workgen.cxx
bench/workgen/workgen_int.h

The following changes have been done to the output JSON format:
1. "workgen" entries are now packed into array
2. "localTime" element belongs to entry and should be placed inside
3. "version" does not belong to any entry and should be placed into the root element
Also, in order to reduce complexity and improve readability of Monitor::run, several methods were extracted from the function.

WT-7667 Fix workgen json output

---

src/txn/txn_timestamp.c

Using barrier call before querying last_checkpoint timestamp to make sure we are not reading a stale or cached value.

WT-7675 Query last ckpt timestamp changes without taking checkpoint

---

dist/stat_data.py
src/conn/conn_tiered.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_tiered02.py

Eliminated a pair of places where we don't need exclusive dhandles (i.e., we now get shared dhandles instead).  Also updated the `tiered02` test to hold an open cursor across a bunch of flush_tier and other operations.

Wt 7591 Fixes to allow cursors to be open during flush_tier

---

src/btree/bt_split.c

Simplify the first child page's key when doing an insert split, there's no reason not to use the original WT_REF's key, rather than taking if from the split page.
Minor cleanup of fast-truncate page checks and comments, re-order structure initialization to match structure declarations.

WT-7707 Simplify insert splits to use the splitting WT_REFs key
