test/format/util.c

Reverts wiredtiger/wiredtiger#5814

Revert "WT-6427 Always set stable timestamp when setting oldest timestamp."

---

src/reconcile/rec_row.c

Reverts wiredtiger/wiredtiger#5744

Revert "WT-6349 Don't perform on disk key removal as part of checkpoint"

---

src/btree/bt_read.c
src/conn/conn_api.c
src/history/hs.c
src/include/extern.h
src/include/txn.i
src/txn/txn.c
src/txn/txn_rollback_to_stable.c

Reverts wiredtiger/wiredtiger#5853

Revert "WT-6462 Use read uncommitted isolation level for history store operations"

---

src/history/hs.c
src/include/btmem.h
src/include/extern.h
src/support/modify.c

Reverts wiredtiger/wiredtiger#5863

Revert "WT-6479 Don't insert updates after the first globally visible update to the history store"

---

test/suite/test_backup16.py

Please review. I added one more case and did some refactoring and a lot of commenting.

WT-6495 Clean up and minor changes to test_backup16.py.

---

test/suite/test_backup16.py

* WT-6495 Clean up and minor changes to test_backup16.py.
* Fix comment.
(cherry picked from commit d60d58943076ac3980c8c9976fb4bb47c8be0bda)

WT-6495 Clean up and minor changes to test_backup16.py. (#5878)

---

test/csuite/incr_backup/main.c

(cherry picked from commit 620b107bf8e5383c46ad416379edc9feeb1d4a62)

WT-6261 Turn off rename until open ticket is fixed. (#5688) (v4.2 backport)

---

src/schema/schema_rename.c

I was able to repro this running clang and this fix passes.

WT-6539 Free checkpoint when done.

---

test/evergreen.yml

Reverts wiredtiger/wiredtiger#5914

Revert "WT-6543 Adding task execution number to name of Artifacts uploaded to S3"

---

test/csuite/timestamp_abort/main.c

Reverts wiredtiger/wiredtiger#5934

Revert "WT-6472 In timestamp abort, size cache to be proportional to number of threads"

---

src/cursor/cur_std.c

I moved where we increment the `cursor_cache` statistic to before we try to cache the cursor.  This is necessary since caching the cursor releases the session's dhandle, so afterwards we no longer have one to increment statistics on.  To avoid counting errors, I also decrement the statistics after we re-open the cursor on error.  Since different cursor types can have different implementations of reopen, it's possible this won't always work. But I figure occasionally miscounting an event is better than never counting the event.

WT-6478 Cursor cache statistics not getting incremented

---

src/cursor/cur_backup_incr.c
src/include/cursor.h
src/include/extern.h
src/include/meta.h
src/meta/meta_ckpt.c
src/schema/schema_rename.c
test/csuite/incr_backup/main.c

Thre is a bug, and reverting will give us time to fix it properly.
The changes being reverted are WT-6215 and WT-6539.

WT-6611 Revert support for doing rename and incremental backups.

---

test/suite/test_rollback_to_stable10.py

Add output to help diagnose any hangs in the same test.

WT-6593 Retry conflicting operations in test_rollback_to_stable10.

---

test/suite/test_backup15.py

@ddanderson I was able to reproduce after about 800 iterations. After making a few minor test improvements I have not been able to reproduce after 4000 iterations. There was a path in the test that would have compared the main table against itself (and expect them to be different). I fixed that, but added an assertion at the top to make sure we weren't taking that path. So I haven't "fixed" anything. There was also a line that was repeated. We may still see this again but I cannot reproduce at the moment and these changes improve the test.

WT-6654 Clean up test_backup15.py

---

test/format/backup.c

*** Please note this is a clean cherry-pick ***
Don't pass a (u_int) to a backup cursor WT_CURSOR.next method, the method expects a (uint64_t) and (u_int) is only 4B, not 8B.
Rework the path construction code: it was passing the wrong buffer length to __wt_snprintf()
in some cases, and was doing unnecessary work on the second and subsequent passes through the block copying loop.
(cherry picked from commit 2c72bba817b9427ba0f53540de2e4e34dc572a0d)

WT-6160 format failure caused by stack overwrite #5627 (v4.2 backport)

---

test/csuite/timestamp_abort/main.c

Reverts wiredtiger/wiredtiger#6043

Revert "WT-6748 Support testing different durable timestamp and commit timestamp in timestamp abort"

---

dist/api_data.py
src/config/config_def.c
src/conn/conn_api.c
src/include/connection.h
src/include/wiredtiger.in
src/support/err.c
test/csuite/wt4156_metadata_salvage/main.c
test/suite/test_txn19.py

Reverts wiredtiger/wiredtiger#6014

Revert "WT-4310 Add option to not abort in diagnostic builds on data corruption"

---

test/suite/test_bug019.py

@ddanderson one more time with `test_bug019.py`! But the earlier debugging allowed me to fully understand the periodic failure now. Good news is that it is a test issue not a WT issue.

WT-6797 Ensure minimum entries before short-circuiting.

---

test/format/backup.c
test/format/format.h

WT-6873 Break up consolidated backup information into reasonably sized

---

dist/api_data.py
src/config/config_def.c
src/cursor/cur_std.c
src/include/wiredtiger.in
test/suite/test_hs19.py

Also extend the cursor API to allow dynamic configuration of forced eviction as a debug option.

WT-6563 Add test confirming modify correctness.

---

src/block/block_open.c
src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c
test/suite/test_prepare_hs04.py
test/suite/test_rollback_to_stable05.py
test/suite/test_schema08.py
test/suite/test_txn16.py
test/suite/test_txn22.py
test/suite/test_verify.py
test/suite/wttest.py

Reverts wiredtiger/wiredtiger#6039

Revert "WT-6712 RTS no stable timestamp"

---

src/conn/conn_api.c
src/conn/conn_dhandle.c
src/include/extern.h
src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c

Reverts wiredtiger/wiredtiger#6115

Revert "WT-6672 Don't increase the writegen number until RTS cleans up checkp…"

---

src/block/block_open.c
src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c
test/suite/test_prepare_hs04.py
test/suite/test_rollback_to_stable05.py
test/suite/test_schema08.py
test/suite/test_txn16.py
test/suite/test_txn22.py
test/suite/test_verify.py
test/suite/wttest.py

Reverts wiredtiger/wiredtiger#6153

Revert "WT-6938 RTS no stable timestamp"

---

src/include/txn_inline.h

Reverts wiredtiger/wiredtiger#6159

Revert "WT-6962 Check against NULL before dereferencing cursor btree"

---

test/csuite/incr_backup/main.c

(cherry picked from commit 5b91477f3437adba4d50b538de580698695fbb64)

WT-6922 Add random consolidate testing to incr_backup. (#6137)

---

src/conn/conn_api.c
test/format/format.sh
test/format/recover.sh

Added verify_metadata configuration to the exclusion list when writing to basecfg.

WT-6313 Metadata-base-config

---

src/block/block_ckpt.c
src/block/block_open.c
src/include/block.h
test/csuite/incr_backup/main.c

(cherry picked from commit b73b201bd449fd34da516d7b5f29d16eb4de2f01)

WT-6882 Files created during incremental backup should be copied in full (v4.2 Backport)

---

test/evergreen.yml
test/format/config.c
test/format/format.sh
test/format/smoke.sh

I ran the patch build with these changes and I found 3 different failures but all these failures have already been reported and tracked with the tickets WT-6504, WT-7065, and WT-7010

WT-6717 Restrict usage of LSM with compatible functionality

---

src/include/txn_inline.h

Validate the previous update timestamps of an item that was already
updated by another transaction while updating it by current transaction.

WT-7020 Assert the previous update timestamp of an item

---

src/log/log.c
test/suite/test_base01.py

Hi. It's a minor test bug. Please have a check.

WT-7084 Fix assert calls in test_base01

---

src/tiered/tiered_cursor.c
src/tiered/tiered_schema.c
test/suite/test_tiered01.py

Add a couple of asserts where to verify the number of tiers is greater than zero.
Includes new test case to cover error handling.

WT-7131 Tiered cursor should return error if configured with zero tiers

---

src/cursor/cur_backup.c
src/docs/backup.dox
test/format/config.c

Reverts wiredtiger/wiredtiger#6232

Revert "WT-7091 Restrict LSM tests with compatible backup configuration"

---

build_posix/configure.ac.in
test/cppsuite/tests/poc.cxx
test/evergreen.yml

Added a check so C++ compilation is also enabled when gcc and g++ have the same version

WT-4649 Updating build system to allow for different C++ compilers

---

test/suite/test_backup04.py
test/suite/test_backup07.py
test/suite/test_backup10.py
test/suite/test_backup11.py
test/suite/test_backup12.py
test/suite/test_backup13.py
test/suite/test_backup14.py
test/suite/test_backup15.py
test/suite/test_backup16.py
test/suite/test_backup17.py
test/suite/test_backup19.py
test/suite/wtbackup.py

Reverts wiredtiger/wiredtiger#6252

i Revert "WT-7102 Migrate full and incremental backup functionalities into wtbackup class"

---

test/evergreen.yml
test/format/config.c
test/format/format.sh
test/format/smoke.sh

This PR will revert the WT-6717 [changes](https://github.com/wiredtiger/wiredtiger/pull/6224/files).

WT-7181 Turn off LSM test

---

dist/api_data.py
dist/s_string.ok
src/docs/data-sources.dox
src/include/wiredtiger.in

This PR adds a small series of miscellaneous API doc updates to ensure descriptions are consistent with the implementation (+ minor formatting fixes). 
This mostly touches the doc descriptions in `wiredtiger.in`and `api_data.py`. If there's anything I obviously missed, please let me know and I will add it to the PR!
_When modifying the doc description I tried my best to refer to the ticket that made the change in the commit description (if preferred, will make sure to scrub the ticket number to avoid unnecessary githooks when squashing)_

WT-6714 Update API documentation for WT exposed APIs

---

dist/test_data.py
src/config/test_config.c
test/cppsuite/test_harness/api_const.h
test/cppsuite/test_harness/test.h
test/cppsuite/test_harness/workload_generator.h
test/cppsuite/test_harness/workload_tracking.h
test/cppsuite/test_harness/workload_validation.h
test/cppsuite/tests/poc.cxx

Main changes are:
- Tracking is enabled from the configuration
- workload_validation class now inherits from the component class
- workload_validation class contains all the methods to:
- Represent in memory the state of the collections using the tracking tables
- Compare the memory representation of the collections to what is actually on disk and vice-versa

WT-6854 Implementation of the test harness validation component

---

test/evergreen/compatibility_test_for_releases.sh
test/evergreen/import_compatibility_test.sh

Reverts wiredtiger/wiredtiger#6374

Revert "WT-7278 Compatibility tests failure"

---

build_posix/aclocal/options.m4
build_win/wiredtiger_config.h
src/docs/upgrade.dox
src/include/btree.h
src/meta/meta_ckpt.c

Reverts wiredtiger/wiredtiger#6366

Revert "WT-5886 Compatibility with older versions of WT"

---

dist/test_data.py
src/config/test_config.c
test/cppsuite/test_harness/api_const.h
test/cppsuite/test_harness/configuration.h
test/cppsuite/test_harness/connection_manager.h
test/cppsuite/test_harness/random_generator.h
test/cppsuite/test_harness/runtime_monitor.h
test/cppsuite/test_harness/test.h
test/cppsuite/test_harness/thread_context.h
test/cppsuite/test_harness/timestamp_manager.h
test/cppsuite/test_harness/workload_generator.h
test/cppsuite/test_harness/workload_tracking.h
test/cppsuite/tests/poc.cxx

Main changes:
- New configuration parameters for timestamp and transaction operations.
- Timestamps are based on the date and are using a counter for uniqueness in multi thread env.
- Thread will execute a random number of operations per transaction.

WT-7275 Implementation of the timestamp manager and transaction management

---

bench/wtperf/runners/many-dhandle-stress.wtperf

Initial many dhandle wtperf workload

WT-7288 Construct many-dhandle-wtperf workload

---

test/evergreen.yml

So theres a few extra fixes in here, mostly around working directories being wrong.

WT-7176 Adding Ubuntu 18.04 ASAN variant to wiredtiger build

---

bench/workgen/runner/many-dhandle-stress.py
bench/workgen/workgen.cxx
bench/workgen/workgen.h
bench/workgen/workgen_int.h
bench/workgen/wtperf.py

Added `max_idle_table_cycle ` and `max_idle_table_cycle_fatal` options in workgen similar to [wtperf](https://source.wiredtiger.com/develop/wtperf.html) .

WT-7332 Add ability to create and drop tables in workgen

---

bench/workgen/workgen.cxx

@ddanderson Please review this one-line change. I grabbed this ticket so that I can get clean builds locally.

WT-7388 Add parens to assignment in conditional.

---

src/txn/txn_recover.c

I must've forgotten to hit the "create pull request" button. Here is the PR I mentioned.

WT-7105 Add recovery error messages to include the URI.

---

src/txn/txn_ckpt.c

Reverts wiredtiger/wiredtiger#6495

Revert "WT-6204 Possible race between backup and checkpoint at file close"

---

test/format/hs.c

Update format to use the new history-store cursor type.

WT-7475 update format to use the new history-store cursor type

---

dist/test_data.py
src/config/test_config.c
test/cppsuite/configs/config_example_test_default.txt
test/cppsuite/configs/config_poc_test_default.txt
test/cppsuite/configs/config_poc_test_stress.txt
test/cppsuite/test_harness/core/configuration.h

Reverts wiredtiger/wiredtiger#6550

Revert "WT-7296 Implementing configuration merging"

---

test/format/format.sh

This ticket is created as part of the Skunkworks project and is aimed to assist the test/format failure analysis/triaging with a “classifier” to generate a human-readable output for critical configuration properties.

WT-7407 test/format failure classifier

---

test/cppsuite/test_harness/core/configuration.h
test/cppsuite/test_harness/workload/database_operation.h

I figured I may as well just make the changes since I'm already triaging them.

WT-7546 Coverity: Minor issues in CppSuite test harness

---

dist/s_function
dist/s_function_with.py
src/conn/conn_log.c

This ticket is fixing a potential resource lock by removing the early exit.

WT-7469 Potential hot backup read lock never unlocked

---

src/include/btmem.h

Reverts wiredtiger/wiredtiger#6540

Revert "WT-7503 Change the history store compressor from snappy to ZStandard."

---

dist/test_data.py
src/config/test_config.c
test/cppsuite/configs/config_poc_test_default.txt
test/cppsuite/test_harness/checkpoint_manager.h
test/cppsuite/test_harness/test.h
test/cppsuite/test_harness/util/api_const.h

This PR adds a new component to call a checkpoint repeatedly. We can use the existing throttle capabilities to configure the interval.

WT-7319 Implement a checkpoint_manager class that creates checkpoints at configurable intervals

---

test/evergreen.yml

Reverts wiredtiger/wiredtiger#6661

Revert "WT-7552 Add UBSAN to automated WT testing"

---

src/block/block_ckpt_scan.c
src/block/block_ext.c
src/block/block_slvg.c
src/conn/conn_dhandle.c
src/conn/conn_tiered.c
src/include/tiered.h
src/tiered/tiered_handle.c

The ticket has an itemization of the items I found and how they are covered (i.e., new ticket, Appendix E, etc.)
This PR is for the removal of the relevant comments, ifdefs, etc.

WT-7473 Resolve "TODO: tiered" comments in code

---

src/txn/txn_ckpt.c

Fixed uninitalized variable in txn_ckpt.c

WT-7715 Fix uninitialized bool in txn_ckpt.c

---

test/evergreen.yml

This change comes after the creation of the script run_many_coll.sh: https://github.com/wiredtiger/mongo-tests/pull/16
We are waiting for a solution to be able to set `ulimit -n` on ubuntu.
EDIT: We will reduce the number of collections in this test to avoid the issues related to `ulimit`.

WT-7343 Created evergreen task for many-collection test.

---

src/block/block_tiered.c

This patch ensures that the block manager file handle is always valid when we switch files during `flush_tier`. The issue was that both `wt_open()` and `wt_close` set their file handle arg to NULL. The change uses temp variables so we avoid passing the block manager's file handle pointer to those functions.

WT-7754 Fix race when updating block manager file handle

---

test/suite/hook_tiered.py

Also remove some dead code that set up a hook for session.close().

WT-7683 Add python hook to call flush_tier during connection.close()

---

test/evergreen.yml

Added the new argument due to this change: https://github.com/wiredtiger/mongo-tests/pull/22

WT-7609 Add log file to the many collection test.

---

test/evergreen/compatibility_test_for_releases.sh

Reverts wiredtiger/wiredtiger#6695

Revert "WT-7599 Compatibility test - create multiple config files for each release"

---

test/cppsuite/test_harness/util/scoped_types.cxx
test/cppsuite/test_harness/workload/database_operation.cxx
test/cppsuite/test_harness/workload/thread_context.cxx
test/cppsuite/test_harness/workload/thread_context.h
test/cppsuite/test_harness/workload/workload_tracking.cxx
test/cppsuite/test_harness/workload/workload_validation.cxx
test/cppsuite/test_harness/workload_generator.cxx
test/cppsuite/tests/example_test.cxx
test/cppsuite/tests/hs_cleanup.cxx

Reverts wiredtiger/wiredtiger#6787

Revert "WT-7836 Fixing a number of small cppsuite issues"

---

lang/python/wiredtiger/packing.py
src/docs/schema.dox
src/include/packing_inline.h

- Remove the Java column as no longer supported.
- Update the packing s per the [schema doc](https://source.wiredtiger.com/develop/schema.html)

WT-7752 Update packing code according to documentation

---

src/evict/evict_lru.c
src/include/cache.h

WT-7852 Don't release eviction server lock when evicting pages

---

src/btree/bt_split.c

@keithbostic in this PR I removed the comments that are stale. If you want different text instead, let me know.

WT-7874 Remove two other stale comments.

---

test/evergreen.yml

Reverts wiredtiger/wiredtiger#6820

Revert "WT-8970 Fix measurement of cyclomatic code complexity"

---

test/format/ops.c

Clear the list of inserted records between individual runs of operations (inside a larger, single run): the numbers left in the list can conceivably overlap leading to races, or more likely, the list is entirely filled between runs and an insert in a subsequent run would fail because the count says there are empty slots in the table, and there aren't.
Increment the pointer into the table of inserted records, otherwise we'll never resolve any inserted record that isn't in the first slot of the table. This means we haven't been testing inserts of more than 256 records per thread (and only testing that lightly, this is a significant change).

WT-7900 format test program column-store mode doesn't correctly insert new records

---

src/btree/bt_cursor.c
src/btree/bt_ret.c
src/include/btmem.h
src/include/wiredtiger.in

(cherry picked from commit 1235ec5a646243d5fe9fcdfd21ece082cd16f646)
Please note this is not a clean cherry-pick.

WT-7776 Add a hard limit on the number of modify updates before we instantiate a complete update (v4.2 backport)

---

src/txn/txn_ckpt.c

There are a few places in the code where we unnecessarily invalidate the cached checkpoint list - remove these invalidations.

WT-7521 Remove excess cached checkpoint list invalidations

---

src/btree/bt_cursor.c
src/btree/col_modify.c
src/btree/row_modify.c
src/include/extern.h
src/include/serial_inline.h
src/include/txn_inline.h
src/reconcile/rec_col.c
test/checkpoint/CMakeLists.txt
test/checkpoint/checkpointer.c
test/checkpoint/smoke.sh
test/checkpoint/test_checkpoint.c
test/checkpoint/workers.c
test/csuite/random_abort/main.c
test/cursor_order/CMakeLists.txt
test/cursor_order/Makefile.am
test/cursor_order/smoke.sh
test/suite/test_bug022.py
test/suite/test_durable_ts03.py
test/suite/test_timestamp10.py
test/suite/test_timestamp11.py
test/suite/test_timestamp12.py
test/suite/test_timestamp14.py
test/suite/test_timestamp16.py
test/suite/test_timestamp17.py
test/suite/test_timestamp18.py
test/suite/test_timestamp19.py
test/suite/test_timestamp20.py
test/suite/test_timestamp22.py
test/suite/test_timestamp23.py

Second go, with a fix for the ubsan issue that cropped up (WT-7951)

WT-7928 VLCS checkpoint and additional test suite improvements (redux)

---

test/csuite/timestamp_abort/main.c

Here's a small change to sometimes lag the oldest timestamp. @bvpvamsikrishna and @kommiharibabu please review and decide if this change is worthwhile.

WT-7961 Sometimes lag oldest timestamp in timestamp_abort.

---

dist/s_all
dist/s_docs
dist/s_docs_plantuml
dist/s_export
dist/s_string
dist/s_tags
src/docs/Doxyfile

(cherry picked from commit f34c50a7b1ed4a3e021a63fd44478a03f29c2552)

WT-7437 Upgrade documentation to doxygen 1.8.17 (3.6 backport) (#6614)

---

test/evergreen.yml
test/format/config.c

- Added evergreen test
- Added configuration check to avoid in_memory field to be set to 1 when abort/recovery is enabled

WT-7941 Add abort/recovery test in test/format

---

src/include/extern.h
src/txn/txn.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable22.py

Reverts wiredtiger/wiredtiger#6896

Revert "WT-7909 Use a new method to check concurrent user transactions before starting rollback to stable"

---

dist/s_all
dist/s_docs
dist/s_docs_plantuml
dist/s_export
dist/s_string
dist/s_tags
src/docs/Doxyfile

Reverts wiredtiger/wiredtiger#6919

Revert "WT-7437 Upgrade documentation to doxygen 1.8.17 (3.6 backport) (#6614)"

---

src/include/txn_inline.h

Always use the checkpoint visibility to decide the global visibility
when the checkpoint is running. This is to avoid inconsistent data visiblity
when the checkpoint has finished checkpointing the data store and before it
checkpoints the history store.

WT-7995 Use checkpoint visibility as global visibility when running

---

src/txn/txn_rollback_to_stable.c

The rollback to stable code unpacks values up to three times (for column store) or twice (for row store), and also under some circumstances sometimes unpacks row store keys twice. This is a bit wasteful and fairly readily tidied.

WT-8041 Rollback to stable unpacks values repeatedly

---

src/reconcile/rec_visibility.c

… timestamps while a checkpoint is running

WT-8045 Fail eviction with EBUSY if we detect OOO timestamps and a checkpoint is running.

---

test/cppsuite/create_test.sh
test/cppsuite/test_harness/workload/database_operation.cxx
test/cppsuite/test_harness/workload/random_generator.cxx
test/cppsuite/test_harness/workload/random_generator.h
test/cppsuite/test_harness/workload/thread_context.cxx
test/cppsuite/test_harness/workload/thread_context.h
test/cppsuite/tests/example_test.cxx

All changes and their motivation are described in WT-8093. The commits tried to reflect each change.

WT-8093 Improve the CPP testing framework for better flexibility

---

test/cppsuite/create_test.sh
test/cppsuite/test_harness/workload/database_operation.cxx
test/cppsuite/test_harness/workload/random_generator.cxx
test/cppsuite/test_harness/workload/random_generator.h
test/cppsuite/test_harness/workload/thread_context.cxx
test/cppsuite/test_harness/workload/thread_context.h
test/cppsuite/tests/example_test.cxx

Reverts wiredtiger/wiredtiger#6997

Revert "WT-8093 Improve the CPP testing framework for better flexibility"

---

src/txn/txn_rollback_to_stable.c

`__rollback_row_modify` now calls `__wt_row_modify`

WT-8068 Improve __rollback_row_modify control flow

---

test/csuite/random_abort/main.c
test/evergreen.yml

I am adding targeted compact testing as follows:
1 - Add a new format test config that will exercise compact operation more often
2 - Add compact operation to the existing random_abort csuite test.

WT-8119 Add targeted compact testing to the existing testing framework

---

src/reconcile/rec_write.c

* WT-7984 Fix a bug that could cause a checkpoint to omit a page of data.
Here are the steps involved:
1. page P exists on disk with address A and is clean
2. checkpoint starts running
3. page P is modified, setting first_dirty_txn ahead of the checkpoint
4. eviction chooses P to evict (in some tree ahead of the checkpoint)
5. eviction reconciles P
6. the main part of reconciliation succeeds but _rec_hs_wrapup fails
with EBUSY
7. at this point, ref->addr == NULL && mod->rec_result == 0 and the
block for A has been freed, the page is dirty but first_dirty_txn is
ahead of the checkpoint
8. checkpoint skips writing P, and when it writes P’s parent, it
considers P, sees the missing address and takes the WT_CHILD_IGNORE
path — i.e., nothing is written and the original content of P (from
step …

WT-7984 Fix a bug that could cause a checkpoint to omit a page of data (v4.2 backport) (#6926)

---

test/evergreen.yml

Migration of the wiredtiger-perf-evict Jenkins job into Evergreen

WT-5012 - Migrate wiredtiger-perf-evict to Evergreen

---

test/suite/test_hs18.py

test_hs18.py test depends on the page eviction to validate the
timestamp weirdness due to out of order or mixed mode timestamps.
Use the debug evict cursor to evict the page to let the test to
have consistent behaviour.

WT-8232 Fix test_hs18.py test to use release evict cursor to evict the page

---

test/evergreen.yml

Added ${distro_id} to the Evergreen info included in the test output.

WT-8357 Add more Evergreen expansions into the performance test output

---

dist/api_data.py
dist/stat_data.py
src/btree/bt_debug.c
src/btree/bt_handle.c
src/btree/bt_page.c
src/btree/bt_split.c
src/btree/bt_stat.c
src/docs/arch-data-file.dox
src/docs/tune-page-size-and-comp.dox
src/include/btmem.h
src/include/btree.h
src/include/btree_inline.h
src/include/extern.h
src/include/stat.h
src/include/wiredtiger.in
src/reconcile/rec_col.c
src/reconcile/rec_row.c
src/reconcile/rec_write.c
src/support/stat.c
test/format/wts.c

Never store overflow keys on row-store internal pages.

WT-8317 Cache stuck with updates when thread performing checkpoint

---

test/suite/test_inmem01.py

Update test_inmem01.test_insert_over_delete_replace to avoid a degenerate case in FLCS.
See the comment in the test (or the ticket) for the full explanation.

WT-8401 test_inmem01.test_insert_over_delete_replace fails under load on FLCS

---

src/reconcile/rec_row.c

Simplify overflow key block frees: now that we no longer store overflow cookies on internal pages, we can free backing overflow key blocks in all cases without further consideration.

WT-8371 row-store internal page overflow key blocks are not being freed

---

bench/wtperf/wtperf_run_py/wtperf_run.py

* Added a check for duplicate operations and exit with an error if duplicates are found.
* Tidied the code.

Added a check for duplicate operations and exit with an error if duplicates are found.

---

src/reconcile/rec_row.c

Now that we no longer store overflow cookies on internal pages, we can free backing overflow key blocks in all cases without further consideration.
(cherry picked from commit af898a825c610f57c54e7475426b150f4372e3ab)

WT-8371 Simplify overflow key block frees (#7179) (v5.0 backport)

---

dist/s_string.ok
test/checkpoint/CMakeLists.txt
test/checkpoint/checkpointer.c
test/checkpoint/smoke.sh
test/checkpoint/test_checkpoint.c
test/checkpoint/test_checkpoint.h
test/checkpoint/workers.c

I've added FLCS support to test_checkpoint.
See the first changeset's change message for the gory details.
The second changeset does a cosmetic reorganization of the options in the test lists; if people don't like it I'm fine with dropping it, but I think it improves the legibility a good deal.

WT-8420 FLCS support for test_checkpoint

---

test/format/CONFIG.endian

Re-enable FLCS evergreen endianness tests.

WT-8015 Re-enable FLCS evergreen endianness tests.

---

test/evergreen.yml

Re-enable FLCS tests in coverage report.

WT-8016 Re-enable FLCS tests in coverage report.

---

test/evergreen.yml

- New function `fetch artifacts from endian` to fetch little and big endian artifacts
- New function `verify wt datafiles` that executes the `verify_wt_datafiles.sh` script

WT-8501 Create functions to refactor endianness tasks in evergreen.yml

---

test/csuite/wt4156_metadata_salvage/main.c

WT-8149 Updating metadata salvage csuite test to handle salvaging table metadata without salvaging file metadata

---

test/csuite/wt4156_metadata_salvage/main.c

Reverts wiredtiger/wiredtiger#7263

Revert "WT-8149 Updating metadata salvage csuite test to handle salvaging table metadata without salvaging file metadata"

---

examples/c/ex_col_store.c

Lint: Fix V4 toolchain complaints.

WT-8530 MongoDB V4 toolchain can't build ex_col_store example program

---

test/format/wts.c

Turn off block-cache configurations.

WT-8533 format-stress-test-1 failed with assert in __wt_blkcache_remove

---

test/evergreen.yml

This ticket is part of [WT-8498](https://jira.mongodb.org/browse/WT-8498), the initial PR is [here](https://github.com/wiredtiger/wiredtiger/pull/7280), this PR aims at merging the same changes to the develop branch.

WT-8500 Update stale comments in evergreen.yml

---

src/txn/txn_log.c

UBSAN undefined error in logging, there may not be any snapshot entries, in which case the allocated buffer can be NULL.
@sueloverso, can you please look at this one?
I just made the obvious change, but I have no clue if this is an indication of a real problem, that is, (1) `txn.snapshot_count` should never be 0, or (2) we shouldn't be doing this processing if `txn.snapshot_count` is equal to 0, or (3) it would be OK to check `txn.snapshot_count`  equal to 0 and skip allocating a buffer at all and it will be allocated the next time the function is called.

WT-8575 UBSAN undefined error in logging

---

test/checkpoint/test_checkpoint.c

(cherry picked from commit 1ac6c119846cfdf77c1496541af50f9c3caef22f)

WT-8576 Enabled logging in test checkpoint. (v4.4 backport)

---

test/checkpoint/test_checkpoint.c

(cherry picked from commit 1ac6c119846cfdf77c1496541af50f9c3caef22f)

WT-8576 Enabled logging in test checkpoint. (v5.0 backport)

---

test/checkpoint/test_checkpoint.c
test/evergreen.yml

Reverts wiredtiger/wiredtiger#7341.
It seems there's something strange going on with the order tests run in - revert this while investigating.

Revert "WT-8370 Add non timestamped configurations to data validation stress tests"

---

src/docs/Doxyfile

(cherry picked from commit c1e1fed1c467b7b0788128a0b46a1d641acf119b)

WT-8004 Add search box to the docs (#7082)

---

test/evergreen.yml

This ticket is part of WT-8498, the initial PR is https://github.com/wiredtiger/wiredtiger/pull/7275, this PR aims at merging the same changes to the develop branch + one change related to a new test `compatibility-test-upgrade-to-latest`, see c6da5dbfdd22d8e83e05d617e976e8378788d696.

WT-8505 Create a compatibility test function in Evergreen

---

test/evergreen.yml

This ticket is part of WT-8498, the initial PR is https://github.com/wiredtiger/wiredtiger/pull/7276/files, this PR aims at merging the same changes to the develop branch.
Additional changes were made as the cpp tests were split recently.

WT-8499 Create a function to execute tests from the cpp suite in evergreen.yml

---

src/reconcile/rec_visibility.c

(cherry picked from commit 2447fe9fbf67422324d15733824363804abc9a6b)

WT-8320 Select updates restored from history store irrespective of visibility (v4.4 backport) (#7253)

---

test/evergreen.yml

This ticket is part of WT-8498, the initial PR is https://github.com/wiredtiger/wiredtiger/pull/7286, this PR aims at merging the same changes to the develop branch.

WT-8517 Create a function to execute smoke scripts in evergreen.yml

---

src/reconcile/rec_visibility.c

(cherry picked from commit 2447fe9fbf67422324d15733824363804abc9a6b)

WT-8320 Select updates restored from history store irrespective of visibility (v5.0 backport) (#7253)

---

test/evergreen.yml

This ticket is part of WT-8498, the initial PR is https://github.com/wiredtiger/wiredtiger/pull/7288, this PR aims at merging the same changes to the develop branch.

WT-8508 Define test env vars expansion for unit test function

---

src/cursor/cur_table.c
src/schema/schema_project.c

WT-8645 v4 toolchain sanitizer errors

---

src/session/session_api.c

Don't release transactional information or scratch buffers if there are open cursors, they might still be in use.
@luke-pearson, I found this one when I pushed the fix for WT-8198 (#7404). In that ticket I changed the bulk load cursor to use a scratch buffer, and `test_bulk02` does a checkpoint while the bulk cursor is open. If checkpoint discards the session's scratch buffers, subsequent bulk cursor actions error out trying to use or close the scratch buffer.
I changed the session resource-discard function to leave the session's transactional information alone if there are cursors open, as well as the scratch buffers. I can't think of a way that would go wrong (given the session can't currently be in a transaction when we get into the session resource-discard function), but that could …

WT-8649 WT_SESSION methods cannot release scratch buffers unless reset or closing

---

dist/stat_data.py
src/btree/row_modify.c
src/conn/conn_cache.c
src/include/cache.h
src/include/cache_inline.h
src/include/extern.h
src/include/stat.h
src/include/wiredtiger.in
src/reconcile/rec_write.c
src/support/stat.c
test/suite/test_hs05.py

Reverts wiredtiger/wiredtiger#7390

Revert "WT-8021 remove unused cache lookaside score and cache hs score"

---

test/format/format.sh

Make format.sh more verbose for failure diagnosis.

WT-8614 Make format.sh more verbose for failure diagnosis.

---

test/evergreen.yml

This ticket is part of WT-8498, the initial PR is #7300, this PR aims at merging the same changes to the develop branch.

WT-8511 Remove unnecessary steps in evergreen

---

dist/api_config.py
dist/api_data.py
src/config/config_def.c
src/include/wiredtiger.in

Document WT_SESSION.assert=(read_timestamp,write_timestamp).

WT-7652 write_timestamp_usage documentation refers to missing assert section

---

test/format/config.c
test/format/wts.c

Fix illegal log removal configuration in compatibility-test-for-newer-releases.

WT-8699 Fix illegal log removal configuration in compatibility-test-for-newer-releases

---

CMakeLists.txt
cmake/configs/aarch64/darwin/config.cmake
cmake/configs/arm64/darwin/config.cmake

I've tested this on my local machine, both compiling and running the csuite tests. I tried to run the python tests but couldn't figure out how to get SWIG working locally. If that's a problem, I'd appreciate a hand with that.

WT-8594 Add ARM64+Darwin CMake config for M1 Macs

---

test/suite/test_hs30.py

New test hs30 that checks history with nontimestamped tables.

WT-8746 Add test for history store usage of non-timestamped tables

---

src/history/hs_rec.c

Update the statistics cache_hs_insert with a value instead of increments.

WT-8778 Update the statistics cache_hs_insert with a value instead of increments

---

test/suite/test_schema07.py

Reverts wiredtiger/wiredtiger#7530

Revert "WT-8805 Fix test_schema07"

---

src/conn/conn_api.c
test/suite/test_config10.py
test/suite/test_txn19.py

Cherry-picked from c6ae92c.
Initial PR [#7388](https://github.com/wiredtiger/wiredtiger/pull/7388).
This cherry-pick applied cleanly. No modifications required.

WT-7922 Handle missing or empty WiredTiger version file (v5.0 Backport)

---

src/include/wiredtiger.in

Clarify expected behavior for configuring and resetting sessions.

WT-8832 Clarify expected behavior for configuring and resetting sessions.

---

src/txn/txn.c
test/suite/test_prepare19.py

Cherry-picked from 966d116.
Initial PR #7537.

WT-8753 Add tombstone when rolling back in-memory, prepared, reconciled updates (v5.0 backport)

---

src/btree/bt_walk.c
src/txn/txn.c
test/checkpoint/CMakeLists.txt
test/checkpoint/test_checkpoint.c
test/checkpoint/workers.c

This PR includes the following:
- We now use 1G of cache size of each test_checkpoint scenario.
- Some minor format updates.

WT-8706 Increase the cache size in all test_checkpoint scenarios

---

dist/api_data.py
dist/api_err.py
src/docs/error-handling.dox
src/docs/programming.dox
src/docs/timestamp-misc.dox
src/docs/timestamp-prepare-roundup.dox
src/docs/timestamp-prepare.dox
src/docs/timestamp-txn.dox
src/include/wiredtiger.in

WT-8878 Documentation cleanups

---

src/txn/txn_ckpt.c

@kommiharibabu, I think this change will revert WT-8695 for MDB server until SERVER-64026 can be scheduled. I don't fully understand what's going on with `(S2C(session)->txn_global.has_stable_timestamp || !metadata))`, but it looks like a mechanical change. Would you please do the review? -- Thanks!
@lukech, my patch runs indicated this fixes at least some of the fallout, so hopefully we'll get clean runs after this is merged.

WT-8883 Change to disallow single file checkpoint has MDB server fallout

---

test/evergreen.yml

(cherry picked from commit 40e535fbbdf92ce0367f230d6994031d9b8d053a)

WT-8894 Find the path to the mongod executable for many-collection-test(v4.4 backport) (#7610)

---

test/evergreen.yml

(cherry picked from commit 40e535fbbdf92ce0367f230d6994031d9b8d053a)

WT-8894 Find the path to the mongod executable for many-collection-test(v5.0 backport) (#7610)

---

src/txn/txn_rollback_to_stable.c

@tammybailey, @kommiharibabu, this is a trivial change and it clears SERVER-63989 for scheduling.

WT-8884 Change return code of rollback_to_stable_check from EINVAL to EBUSY

---

src/btree/bt_cursor.c
src/cursor/cur_hs.c
src/include/btree_inline.h
src/include/cursor_inline.h
src/include/extern.h
src/schema/schema_create.c

Imported files should not remain configured for potential bulk load.

WT-8910 imported files should not remain configured for bulk load

---

src/txn/txn.c
test/suite/test_prepare19.py

Cherry-picked from 966d116.
Initial PR #7537.

WT-8753 Add tombstone when rolling back in-memory, prepared, reconciled updates (v4.4 backport)

---

test/cppsuite/configs/hs_cleanup_default.txt
test/cppsuite/configs/hs_cleanup_stress.txt

Cherry-picked from 4375642.
Initial PR #7526.

WT-8743 Configure hs_cleanup configuration to stress the cache less (v5.0 backport)

---

test/cppsuite/configs/hs_cleanup_default.txt
test/cppsuite/configs/hs_cleanup_stress.txt

Cherry-picked from 4375642.
Initial PR #7526.

WT-8743 Configure hs_cleanup configuration to stress the cache less (v4.4 backport)

---

test/suite/test_rollback_to_stable26.py

Works during local testing, unfortunately I don't yet have access to a zSeries machine so I'll have to wait for a patch build (comment on ticket). That's probably going to take a couple of hours, may as well do a code review in the meantime.

WT-8823 Wait for checkpoint to start using statistics instead of fixed sleep

---

dist/api_data.py
dist/s_docs
src/docs/arch-backup.dox
src/docs/arch-log-file.dox
src/docs/backup.dox
src/docs/checkpoint.dox
src/docs/durability-checkpoint.dox
src/docs/durability-log.dox
src/docs/durability-overview.dox
src/docs/durability.dox
src/docs/explain-acid.dox
src/docs/programming.dox
src/docs/timestamp-global.dox
src/docs/timestamp-misc.dox
src/docs/timestamp-model.dox
src/docs/timestamp-prepare-roundup.dox
src/docs/timestamp-prepare.dox
src/docs/timestamp-txn.dox
src/docs/transactions.dox
src/docs/transactions_api.dox
src/docs/tune-cache.dox
src/docs/tune-durability.dox
src/docs/verbose-messaging.dox
src/include/wiredtiger.in

WiredTiger standalone documentation review

WT-8934 WiredTiger standalone documentation review

---

src/reconcile/rec_visibility.c

Co-authored-by: Etienne Petrel <etienne.petrel@mongodb.com>
(cherry picked from commit 23e5746ea948e3b1ac903f2cce3ea209e19329a1)

WT-8879 Set the OOO flag when the selected tombstone is globally visible (5.3 backport) (#7632)

---

src/session/session_api.c
src/txn/txn.c

Reverts wiredtiger/wiredtiger#7657

Revert "WT-8935 Failed transaction commit doesn't reset cursors."

---

src/reconcile/rec_visibility.c

(cherry picked from commit 23e5746ea948e3b1ac903f2cce3ea209e19329a1)

WT-8879 Set the OOO flag when the selected tombstone is globally visible (5.0 backport) (#7632)

---

src/txn/txn.c

Allow rollback of read only txns in WT_STANDALONE_BUILD mode.

WT-8869 Allow rollback of read only txns in WT_STANDALONE_BUILD mode.

---

test/evergreen.yml

- Made evergreen.yml file changes to add tiered06 extension testing to PR.

WT-8914 Add python testing for tiered storage (including S3) to pull request tests

---

test/csuite/random_abort/main.c

Handle rollback from all applicable cursor operations.

WT-8966 Failed test_random_abort: WT_ROLLBACK conflict between concurrent operations

---

test/checkpoint/test_checkpoint.c

Reverts wiredtiger/wiredtiger#7688

Revert "WT-8223 Enhance test/checkpoint to randomly operate with high eviction rate"

---

src/txn/txn_rollback_to_stable.c
test/suite/test_log04.py

Reverts wiredtiger/wiredtiger#7685

Revert "WT-8970 Turn on exclusive access to dhandles during RTS"

---

src/include/txn_inline.h

(cherry picked from commit 403df77b0a6452e1b3a21ce32eec5a21aefdbe08)
Initial PR #7648

WT-8924 Adding insert list check back to if statement, adding a comment explaining why (v5.0 backport)

---

src/include/txn_inline.h

(cherry picked from commit 403df77b0a6452e1b3a21ce32eec5a21aefdbe08)
Initial PR #7648

WT-8924 Adding insert list check back to if statement, adding a comment explaining why (v4.4 backport)

---

test/checkpoint/test_checkpoint.c

- Random initialisation of boolean to decide when to operate with fast eviction

WT-8223 Enhance test/checkpoint to randomly operate with high eviction rate

---

src/txn/txn.c

Run the update loop in __txn_resolve_prepared_op backwards. Avoids the race described in WT-6778.

WT-6778 Checkpoint may write partial resolved prepared update to disk

---

test/suite/test_tiered02.py

Added ComplexDataset scenario into "test_tiered02.py". The dataset utilizes column groups and indexes. The new scenario causes a crash on line #166 because of the opened cursor, which we create at line #156. The new scenario is commented out with FIXME comment.

WT-8989 Extend "test_tiered02.py" with column group scenario

---

test/cppsuite/configs/hs_cleanup_stress.txt

(cherry picked from commit 11338fc0ed96da84ebefd66d3cccdf04dcaa0357)

WT-8450 Report stats in hs_cleanup_stress, don't validate them in 5.0 (#7472)

---

test/cppsuite/configs/hs_cleanup_stress.txt

(cherry picked from commit 11338fc0ed96da84ebefd66d3cccdf04dcaa0357)

WT-8450 Report stats in hs_cleanup_stress, don't validate them on 4.4 (#7472)

---

src/reconcile/rec_write.c

The other concerns in WT-7657 are covered by other tickets. See the discussion in the ticket.

WT-7657 Update comment about OOO/mixed mode evictions and the history store.

---

src/reconcile/rec_visibility.c

(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/23e5746ea948e3b1ac903f2cce3ea209e19329a1)

WT-8879 Set the OOO flag when the selected tombstone is globally visible (4.4 backport) (#7632)

---

bench/wtperf/config.c
bench/wtperf/runners/tiered-btree.wtperf
bench/wtperf/runners/tiered-read-only.wtperf
bench/wtperf/track.c
bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
bench/wtperf/wtperf_opt.i

…er for a tiered storage workload.

WT-9047 Add tiered storage support to wtperf

---

LICENSE
src/utilities/util_alter.c
src/utilities/util_backup.c
src/utilities/util_compact.c
src/utilities/util_cpyright.c
src/utilities/util_create.c
src/utilities/util_downgrade.c
src/utilities/util_drop.c
src/utilities/util_dump.c
src/utilities/util_list.c
src/utilities/util_load.c
src/utilities/util_loadtext.c
src/utilities/util_main.c
src/utilities/util_misc.c
src/utilities/util_printlog.c
src/utilities/util_read.c
src/utilities/util_rename.c
src/utilities/util_salvage.c
src/utilities/util_stat.c
src/utilities/util_truncate.c
src/utilities/util_upgrade.c
src/utilities/util_verify.c
src/utilities/util_write.c

@agorrod, can you please check me on d6c6c68? -- Thanks!

WT-9076 The LICENSE file and wt utility copyrights need to be updated.

---

src/docs/wtperf.dox

Rebuild the wtperf documentation.

WT-9101 Rebuild the wtperf documentation.

---

src/support/generation.c

Reverts wiredtiger/wiredtiger#7786

Revert "WT-9045 Change integer type to avoid potential overflow in generation drain "

---

test/suite/test_truncate03.py

Eviction can re-dirty the cache and cause verify to fail, loop, checkpointing, until verify succeeds.

WT-9160 test_truncate03: verify fails with EBUSY

---

bench/wtperf/wtperf.c

WT-9086 Run flush_tier and checkpoint threads during populate for tiered

---

src/reconcile/rec_visibility.c

Reverts wiredtiger/wiredtiger#7811

Revert "WT-9147 Fix metadata reconciliation sees uncommitted updates followed by committed updates"

---

test/evergreen.yml

…st (#7757)
(cherry picked from commit 2a20e7cd4b75aaccc40eb7d0009548b92dc1aa81)

WT-8860 Save the mongod logs as a test artifact in many-collection-test (Backport v5.0)

---

src/reconcile/rec_visibility.c

Reverts wiredtiger/wiredtiger#7820

Revert "WT-9147 No need to walk the whole update chain in __wt_rec_upd_select except for metadata"

---

bench/wtperf/wtperf.c
bench/wtperf/wtperf.h

@fedorova give this a try and look at these changes. Let me know what you think.

WT-9204 Change wtperf checkpoint stopping for flush thread.

---

src/btree/bt_delete.c
src/btree/bt_read.c
src/cursor/cur_file.c
src/include/btmem.h
src/include/btree_inline.h
test/suite/test_checkpoint25.py

Reverts wiredtiger/wiredtiger#7865

Revert "WT-9252 instantiated fast-truncate pages in read-only trees fail eviction tests"

---

src/include/serial_inline.h

It doesn't make sense to call this with a null update, and in any case it was broken if we did (since it dereferences the update in a couple of spots).
I also had a look at the call sites, there are only two: one in `col_modify`, and one in `row_modify`. If either of these manage to pass in a null update, something is very wrong.

WT-9168 Assert non-null update passed to update_serial

---

src/reconcile/rec_row.c

@kommiharibabu, @sauclovian-wt: this loop in RS reconciliation is ugly -- we replace the `previously built key` that we'll use to create the next key we're writing into the disk image with a fully instantiated copy of the current key, and that appears to work, but I think there are some nasty edge cases and invitations to future problems. Particularly, when we encounter a `WT_UPDATE_STANDARD`, we rewrite the previous-key buffer and keep running, and I have a hard time convincing myself that's OK. I can't find a problem (and I looked really hard today), but I just don't trust it.
I split the usage apart into two buffers: they're scratch buffers so I don't think it will impact the performance and I think it makes the code significantly easier to work with.

WT-9316 row-store leaf page reconciliation code confuses temporary keys with previous keys

---

dist/s_whitespace

* Expanded s_whitespace to check for newlines in .cpp files as well as these were previously being skipped.

WT-9351 Expand s_whitespace to check for newlines in .cpp files

---

test/evergreen.yml

Reverts wiredtiger/wiredtiger#7999

Revert "WT-9412 Add missing flags for evergreen testing"

---

src/evict/evict_page.c
src/include/cache_inline.h
src/include/txn_inline.h

Reverts wiredtiger/wiredtiger#8011

Revert "WT-9439 Don't attempt to evict using a checkpoint-cursor snapshot"

---

test/cppsuite/tests/cursor_bound_01.cpp

Reverts wiredtiger/wiredtiger#8015

Revert "WT-9441 Fix bound setting in cursor_bound_01 cppsuite stress test"

---

ext/storage_sources/dir_store/dir_store.c
src/conn/conn_tiered.c
test/csuite/schema_abort/main.c

Mostly handle ENOENT in a few places.

WT-9447 Fix errors around drop and tiered storage from schema_abort.

---

src/meta/meta_ckpt.c
src/session/session_dhandle.c

Rearrange the checkpoint-cursor open synchronization again.
Now we retrieve the snapshot's wall time twice (before and after everything else) and reject if they don't match. This and still
checking if any of the items are newer than the snapshot *should* fix the problem for good. I think. I hope...

WT-9463 Fix a race opening checkpoint cursors

---

src/btree/bt_debug.c

Adjust history store visibility for checkpoint cursor debug dumps.
Use WT_CURSTD_HS_READ_ALL instead of WT_CURSTD_HS_READ_COMMITTED to avoid a visible_all test that doesn't do the right thing (and now asserts because of it).
(See the Jira ticket for the full rationale)

WT-9476 Fix debug dumps of checkpoint cursor history store pages

---

dist/s_string.ok
test/CMakeLists.txt
test/simulator/CMakeLists.txt
test/simulator/third_party/nlohmann/json.hpp
test/simulator/timestamp/CMakeLists.txt
test/simulator/timestamp/timestamp_simulator.cpp

The directory structure looks like this:
```
Simulator
|– third_party
|---- nlohmann
|------ json.hpp
|– timestamp
|---- CMakeLists.txt
|---- timestamp_simulator.cpp
CMakeLists.txt
```
I have linked the patch build in the ticket itself.

WT-9210 Create directory structure for simulator including CMake files

---

cmake/configs/base.cmake
cmake/configs/modes.cmake
test/evergreen.yml

Do this by setting the optimization level to 0

WT-9432 Ensure Evergreen builds have debug information

---

test/cppsuite/src/main/database_operation.cpp

Two issues are being covered here:
- We now reset the random cursor so we don't pin content
- We handle `WT_ROLLBACK` that can be returned from the `next` cursor call
I have added the cpp stress tests to the PR.

WT-9480 Handle WT_ROLLBACK in the default remove_operation of the cpp suite

---

dist/api_data.py
src/config/config_def.c
src/include/wiredtiger.in
test/suite/test_tiered05.py

Reverts wiredtiger/wiredtiger#8053

Revert "WT-9302 Deprecated object_target_size as a config in api_data.py (v5.0 backport) "

---

dist/s_all
dist/stat.py
dist/stat_data.py

* Wrote a check in `stat.py` that checks the imported statistics from `stat_data.py`. 
* The `check_unique_description` function will check if the stat descriptions within each category is unique
* Otherwise it will print an error message. 
* `s_all` does an error check on its call to `stat.py` and `s_all` will fail if there is an output.

WT-9416 Check if statistic descriptions are unique in s_all

---

src/call_log/call_log.c
src/conn/conn_api.c
src/include/extern.h
src/session/session_api.c

Added a function for generating call log entry for open session.

WT-9221 Generate call log for open_session()

---

test/cppsuite/how_to_use_cppsuite.md

Documentation for how to create and run a cppsuite test, including a worked example.

WT-9111 - Document how to create and run cppsuite tests

---

cmake/configs/base.cmake

Fixing the order of enabling/disabling python to make sure that it behaves correctly.

WT-9626 Fixing the order of enabling/disabling python to make sure that it behaves correctly

---

src/btree/bt_vrfy.c

Cross-check btree->type and page->type.

WT-9645 Crosscheck tree type and page type in verify

---

test/simulator/timestamp/call_log_manager/call_log_manager.cpp
test/simulator/timestamp/call_log_manager/call_log_manager.h
test/simulator/timestamp/src/include/session_simulator.h
test/simulator/timestamp/src/session_simulator.cpp

I've added a boolean to the session class to indicate whether a transaction is running. Let me know if there's anything else we need to do for begin_transaction.

WT-9226 Process the call log for begin_transaction()

---

test/simulator/timestamp/call_log_manager/call_log_manager.cpp
test/simulator/timestamp/call_log_manager/call_log_manager.h
test/simulator/timestamp/src/connection_simulator.cpp
test/simulator/timestamp/src/include/connection_simulator.h
test/simulator/timestamp/src/include/error_simulator.h
test/simulator/timestamp/src/include/session_simulator.h
test/simulator/timestamp/src/include/timestamp_manager.h
test/simulator/timestamp/src/session_simulator.cpp
test/simulator/timestamp/src/timestamp_manager.cpp

As part of this PR, the following will be done:
- Create functions for the call_log operations in the switch/case statement. This leads to better readability of the code.
- Error handling
- Assertion for all non-timestamps-related errors.
- Exception handling for timestamp-related issues.
- Improving the JSON output from wiredtiger.

WT-9219 Fix error handling in the simulator

---

test/suite/test_prepare21.py

FLCS doesn't work properly in this branch, so remove that part of the test.

WT-9595 Disable FLCS in test_prepare21 for v5.0

---

test/format/format.sh

format.sh resolve function could produce cores that were not correct adding to confusion on the results.

WT-9721 Fix format.sh resolve function

---

test/suite/test_cursor_bound_fuzz.py
test/suite/wtbound.py

- Implemented truncate and prepare functionalities in the Python fuzz test.

WT-9554 Implement truncate and prepare in the cursor bounds fuzz tester python test

---

src/btree/bt_cursor.c
test/suite/test_cursor_bound08.py
test/suite/test_cursor_bound15.py

- Fix edge case bug where search near was returning the wrong exact with bounded cursors.
- Added python test.

WT-9781 Fix search near exact edge case with bounded cursor

---

src/block_cache/block_mgr.c

@ddanderson I have not seen this assert fail with this change.

WT-9838 Allow checkpoint when creating first object.

---

test/format/util.c

Fix row-store key handling in mirror page dumps.

WT-9845 Fix key handling in test/format mirror page dumps

---

test/suite/test_jsondump01.py
test/suite/wtdataset.py

This adds a little bit of "shuffling" for complex data set indices, so slightly better test coverage.

Changed the values of columns in a ComplexDataSet so they are not ordered.

---

test/evergreen.yml

Updating python test runs to preload TCMALLOC to avoid conflicts in allocators.

WT-9835 Run python tests with TCMALLOC if enabled

---

src/btree/bt_handle.c

When opening a column-store btree, always use WT_READ_VISIBLE_ALL.

WT-9817 Column store tree open should always fetch the last page with global visibility

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/cursor/cur_std.c
test/suite/test_cursor_bound02.py
test/suite/test_cursor_bound03.py
test/suite/test_cursor_bound04.py
test/suite/wtbound.py

Reverts wiredtiger/wiredtiger#8273

Revert "WT-9851 Support bounded cursor next and prev traversal in FLCS"

---

test/utility/misc.c
test/utility/parse_opts.c
test/utility/test_util.h

Add -Po option for specifying storage source, and the -PT option that adds tiered configuration to wiredtiger_open and starts a flush_tier thread.

WT-9739 test tiered: test_util command line parsing

---

ext/storage_sources/dir_store/dir_store.c

Fix 2 instances of memory leak that were captured by Coverity.

WT-9676 Coverity analysis defect 126347/123712: Resource leak

---

ext/storage_sources/dir_store/dir_store.c

Fix a double-free issue that was captured by Coverity.

WT-9682 Coverity analysis defect 125363: Double free

---

src/history/hs_rec.c

Can I trouble you @sueloverso for a trivial review?

WT-9938 Change WT_NOT_FOUND to WT_NOTFOUND in comment in rec_hs.c

---

src/cursor/cur_json.c
src/cursor/cur_stat.c
src/os_common/os_alloc.c
test/suite/test_jsondump01.py
test/suite/test_jsondump02.py

Reverts wiredtiger/wiredtiger#8343

Revert "WT-9950 __wt_realloc with clear memory flag requires knowledge of old size"

---

test/suite/hook_tiered.py
test/suite/wtdataset.py
test/suite/wthooks.py
test/suite/wttest.py

This change is mainly to add and parse tier_populate_cache option to hook_tiered.py and flush the passing percentage of data to local disk after populating.

WT-9744 test tiered: add tier_populate_cache configuration option to hook_tiered

---

test/evergreen.yml
test/format/config.c
test/format/ops.c
test/suite/hook_nonstandalone.py
test/suite/hook_rollback.py
test/suite/hook_tiered.py
test/suite/hook_timestamp.py

Add tests for non standalone build for:
python
c tests
stress testing

WT-10071 Add nonstandalone evergreen tests

---

cmake/configs/base.cmake
test/CMakeLists.txt
test/cppsuite/src/main/thread_worker.cpp
test/cppsuite/src/main/thread_worker.h
test/evergreen.yml

I tested this on a basic scenario locally but don't plan on pushing any tests as part of this change. I'm also going to defer the implementation of the validation mechanisms to another ticket as I think it requires some more consideration.

WT-10032 Implement support for truncate operation cpp test framework

---

src/btree/bt_cursor.c

WT-10084 Minor refactor of cursor search near.

---

src/btree/bt_page.c
test/suite/test_truncate19.py

(cherry picked from commit 8e8d4be3138eba73b4d530b832dcf2cc545e2a64)

WT-10030 Mark internal page with deleted pages as dirty when reading it into memory (#8414)

---

test/evergreen.yml

See WT-9102 for the patch build.

WT-9102 Update macOS variant to version 11.00

---

src/log/log.c

WT-10206 Refactoring __wt_log_release and __wt_log_force_sync to use common methods for fsyncing the dir and log file.

WT-10206 Refactoring log fsync calls

---

test/evergreen.yml

- Enable perf tests on MacOS-1100 and Ubuntu2004-ARM64 platforms

WT-10039 Enable perf tests on non ubuntu platforms

---

test/evergreen.yml

Patch build in the JIRA ticket.

WT-10214 Enable format-smoke-test

---

src/rollback_to_stable/rts_api.c
src/rollback_to_stable/rts_btree.c

I considered converting a bunch of `WT_ASSERT`s into `WT_ASSERT_ALWAYS`, but to be honest I don't know enough to be confident about pushing those assertions into the real world.

WT-10231 Extra RTS assertions

---

dist/s_string.ok
test/format/config.c
test/format/format.h
test/format/wts.c

Reverts wiredtiger/wiredtiger#8535

Revert "WT-10072 Limit format rows to one million if realloc_exact and realloc_malloc are set"

---

test/evergreen.yml

Reverts wiredtiger/wiredtiger#8562

Revert "WT-10282 Fix MSan optimisation level"

---

src/conn/conn_log.c
src/include/log.h
src/log/log.c
src/log/log_slot.c

WT-10207 Change log slot flags to flags_atomic and remove debugging added for WT-9796 as the root cause was identified.

WT-10207 Change log slot flags to flags_atomic and remove debugging

---

dist/s_all
dist/s_clang_format
dist/s_evergreen_validate
dist/s_function
src/include/cache_inline.h

I've made a number of changes here:
- I created a new s_evergreen_validate script, I discussed merging this with s_evergreen but it doesn't come out nicely. If people would like me to still try I can.
- I only run s_evergreen_validate if git says the files are modified in fast mode
- I added a fast argument to s_function which reduced its runtime from 30 seconds to about .5 seconds (modulo git changes)
- I fixed a typo in that script that meant it wasn't running on a number of files
- Fixed the subsequent issue it found
- Removed a spurious echo

WT-10300 Additional speedups for s_fast.

---

test/evergreen/run_format_configs.sh

(cherry picked from commit eccc369904708f4f076ce279fe65b62dbfad1ad5)
Co-authored-by: Luke Pearson <luke.pearson@mongodb.com>
(cherry picked from commit 6f2040328bf9d20a0c01544394bc9d42d09c09b6)

WT-10291 Only run test format failure configs once (#8609) (#8614)

---

src/conn/conn_cache_pool.c
src/include/cache.h
src/include/hardware.h

WT-10284 Updating connection cache pool pool_flags to atomic due to race condition.

WT-10284 Updating connection cache pool pool_flags to atomic

---

src/support/err.c
test/unittest/tests/test_assertions.cpp
test/unittest/tests/wrappers/connection_wrapper.cpp
test/unittest/tests/wrappers/connection_wrapper.h

Adding a unit test to test the new run time diagnostic assertion config behaviour with different assertion categories.

WT-10042 Unit testing runtime __wt_assert function

---

bench/workgen/runner/example_dynamic_tables.py
bench/workgen/workgen.cxx
bench/workgen/workgen.h
bench/workgen/workgen_int.h

Reverts wiredtiger/wiredtiger#8656

Revert "WT-10456 Reimplement create and drop of the tables as a service in workgen"

---

bench/workgen/runner/example_dynamic_tables.py

Reverts wiredtiger/wiredtiger#8678

WT-10423 Stoney's Merge Test Take Two

---

bench/workgen/runner/example_dynamic_tables.py

Reverts wiredtiger/wiredtiger#8679

Revert "WT-10423 Stoney's Merge Test Take Two"

---

bench/workgen/runner/example_dynamic_tables.py

Reverts wiredtiger/wiredtiger#8680

WT-10423 Stoney's Merge Test Take FOUR

---

bench/workgen/runner/example_dynamic_tables.py

Reverts wiredtiger/wiredtiger#8681

WT-10423 Stoney's Merge Test Take five alive

---

bench/workgen/runner/example_dynamic_tables.py

Reverts wiredtiger/wiredtiger#8682

WT-10423 Stoney's Merge Test Take Six

---

dist/stat_data.py
src/conn/conn_sweep.c
src/include/session.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_sweep05.py

It also adds a warning for sessions that did not sweep for more than an hour.

WT-10340 Add stats for sessions that did not run a sweep for a while.

---

bench/workgen/workgen.cpp
bench/workgen/workgen.h

Reverts wiredtiger/wiredtiger#8697

Revert "WT-10202 Provide option to disable the generation of stats in Workgen"

---

ext/storage_sources/azure_store/azure_connection.cpp
ext/storage_sources/azure_store/azure_connection.h
ext/storage_sources/azure_store/test/test_azure_connection.cpp

Implemented the list_objects functionality for azure connection using list_blobs azure sdk function.

WT-10349 Implement list_objects() in connection class for Azure

---

bench/workgen/workgen.cpp

Reverts wiredtiger/wiredtiger#8740

Revert "WT-10532 Add signal handler to Workgen"

---

ext/storage_sources/azure_store/azure_connection.cpp
ext/storage_sources/azure_store/azure_connection.h
ext/storage_sources/azure_store/test/test_azure_connection.cpp

Implemented the following:
- object_exists functionality
- bucket_exists functionality
- constructor for Azure inside connection class
- error check if we can't create a bucket/can't access in constructor
- unit testing for object_exists

WT-10518 Implement bucket_exists, object_exists and constructor for Azure

---

ext/storage_sources/azure_store/azure_connection.cpp
ext/storage_sources/azure_store/azure_connection.h

- Implement exception handling for Azure Connection -> maps the HTTP error code if one is thrown to an OS error. If not the exception is caught and the reason is just printed out.
- Created free function to deal with exceptions thrown by Azure

WT-10541 Implement exception handling for Azure Connection class

---

ext/storage_sources/azure_store/test/test_azure_connection.cpp

- Added unit tests for the whole connection class testing each function in isolation and not dependent on another connection class function 
- Added prefix generator for multi threading testing 
- Added function to create a file
- Added code to create 2 files before each tests run and deletes them after

WT-10510 Implement unit testing for connection class for Azure

---

dist/s_string.ok
ext/storage_sources/gcp_store/gcp_connection.cpp
ext/storage_sources/gcp_store/gcp_connection.h
ext/storage_sources/gcp_store/test/test_gcp_connection.cpp

Mapping between Google status codes and errno values has been added. 
All GCP connection class functions have been updated to return these codes instead of just -1.

WT-10546 Implement error handling for GCP Connection class

---

lang/python/wiredtiger.i
test/suite/test_count01.py

Reverts wiredtiger/wiredtiger#8508

Revert "WT-10184 Update SWIG mapping for int64_t*"

---

cmake/third_party/azure_sdk.cmake
test/evergreen.yml
test/suite/test_tiered19.py

These crept in during the last few days while we weren't doing the drop.

WT-10574 Fix whitespace issues in three files

---

src/btree/row_srch.c
src/include/serial_inline.h

(cherry picked from commit 3687d84457c5468542645aff23930a2a248a16ed)

WT-10461 Fix key out of order in skip list on weakly ordered architecture (#8757) (v6.2 backport)

---

src/btree/row_srch.c
src/include/serial_inline.h

(cherry picked from commit 3687d84457c5468542645aff23930a2a248a16ed)

WT-10461 Fix key out of order in skip list on weakly ordered architecture (#8757) (v6.0 backport)

---

src/btree/row_srch.c
src/include/serial_inline.h

(cherry picked from commit 3687d84457c5468542645aff23930a2a248a16ed)

WT-10461 Fix key out of order in skip list on weakly ordered architecture (#8757) (v4.4 backport)

---

ext/storage_sources/azure_store/azure_connection.cpp
ext/storage_sources/azure_store/azure_connection.h
ext/storage_sources/azure_store/test/test_azure_connection.cpp

- Updated obj_prefix to bucket_prefix 
- Amended unit tests to account for this change

WT-10580 Rename object_prefix and prefix in Azure Connection Class

---

ext/storage_sources/azure_store/azure_connection.cpp
ext/storage_sources/azure_store/azure_storage_source.cpp
ext/storage_sources/azure_store/test/test_azure_connection.cpp
test/suite/test_tiered19.py

- Implemented object size() with python testing 
- Fix merge issues from last PR that existed

WT-10596 Implement object size() for Azure Storage Source

---

src/btree/bt_split.c

WT-9477 Don't allow checkpoint triggering internal page split which leads to corrupted internal page in the checkpoint

---

src/btree/bt_curprev.c

WT-10584 Add missing read barriers in __cursor_skip_prev (#8806) (v6.3 backport)

---

src/btree/bt_curprev.c

WT-10584 Add missing read barriers in __cursor_skip_prev (#8806) (v6.2 backport)

---

src/btree/bt_curprev.c

WT-10584 Add missing read barriers in __cursor_skip_prev (#8806) (v6.0 backport)

---

src/btree/bt_curprev.c

WT-10584 Add missing read barriers in __cursor_skip_prev (#8806) (v5.0 backport)

---

src/btree/bt_curprev.c

WT-10584 Add missing read barriers in __cursor_skip_prev (#8806) (v4.4 backport)

---

src/btree/bt_curprev.c

WT-10584 Add missing read barriers in __cursor_skip_prev (#8806) (v4.2 backport)

---

src/reconcile/rec_col.c
src/reconcile/rec_row.c
test/suite/test_hs11.py

(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/ede3bedaa1e5bfd03b51857608843c00dabc03d5)

WT-10469 Fix no timestamp tombstones not removing history store entries (#8727)

---

bench/workgen/workgen.cpp
bench/workgen/workgen.h
bench/workgen/workgen_int.h

Reverts wiredtiger/wiredtiger#8798: Identified an issue when running workloads using dynamic tables with transactions and without mirrors.

Revert "WT-10240 Implement mirrored dynamic tables in workgen"

---

ext/storage_sources/gcp_store/README.md

- Wrote GCP documentation on how to build extension

WT-10588 Create documentation for WiredTiger GCP extension

---

ext/storage_sources/azure_store/README.md

- Fix typos in Azure Documentation that were overlooked

WT-10656 Fix Typos in Azure documentation

---

test/csuite/wt10461_skip_list_stress/main.c

Add some missing frees for memory allocated in the wt10461 test.

WT-10654 Fix leaks in wt10461 csuite test

---

src/utilities/util_dump.c
tools/keyblob.py

Add window functionality to util dump.
That is the ability to dump records "around" a searched for record.

WT-10708 dump window

---

test/format/format.sh

WT-10738 Adding RR support to format.sh

WT-10738 Adding RR support to format.sh

---

test/evergreen.yml
test/evergreen/print_stack_trace.py

The code was imported from the `develop` branch.

WT-10288 Dump stack traces in Evergreen upon failures (v6.0)

---

dist/s_string.ok
src/docs/command-line.dox
src/docs/spell.ok
src/utilities/util_dump.c
test/suite/test_dump01.py
test/suite/test_dump02.py
test/test_coverage.md

The initial PR is #8888. This PR merges the code to the `develop` branch.

WT-10709 Update the WT util dump to perform a search on a key

---

src/rollback_to_stable/rts_btree.c
src/rollback_to_stable/rts_btree_walk.c
src/rollback_to_stable/rts_visibility.c
test/suite/test_rollback_to_stable42.py
tools/rts_verifier/operation.py

- Analyse existing RTS logs for possible improvements
- Improve the readability and understandability of identified RTS logs

WT-10274 Improve RTS logs readability

---

test/evergreen.yml
test/suite/helper_tiered.py
test/suite/wttest.py

Reverts wiredtiger/wiredtiger#8953

Revert "WT-10373 Download objects from the bucket on test failure or preserve"

---

src/history/hs_rec.c
src/rollback_to_stable/rts.c
src/rollback_to_stable/rts_btree.c
src/rollback_to_stable/rts_btree_walk.c
test/suite/test_rollback_to_stable04.py
test/suite/test_rollback_to_stable06.py

Reverts wiredtiger/wiredtiger#8969

Revert "WT-10017 Remove the unstable historical versions at the end of rollback to stable"

---

src/meta/meta_ckpt.c
test/csuite/timestamp_abort/main.c
test/csuite/timestamp_abort/smoke.sh
test/suite/test_backup29.py
test/utility/misc.c

You can review now, but I won't merge until my testing successfully runs overnight.

WT-10551 Load backup block mod information into base checkpoints.

---

test/suite/test_cursor_random.py

(cherry picked from commit a4d5ea58c472488199347d145a0360fab058c5fe)

WT-10380 Fix expected warning output in test_cursor_random (v6.3 backport) (#8850)

---

test/suite/test_backup29.py

WT-10909 Simplify test_backup29.py. We don't need to actually take a

---

cmake/third_party/aws_sdk.cmake
test/evergreen/find_cmake.sh

(cherry picked from commit ed8b5562dd2cf78b1d18b19892e8b5bd362bfb92)

WT-10597 Fix tiered storage extensions test (v6.3 backport)(#8823)

---

test/evergreen.yml

* Changed zseries test from ubuntu-1804-zseries-test to rhel80-zseries-test
(cherry picked from commit 324fdee42e1e5a99c274fc2e552c007aa786c523)

WT-8689 Switch Evergreen zSeries builder to RHEL distro (v5.0 backport) (#7649)

---

bench/workgen/workgen.cpp

This changes the logic to better match the original intent, and adds a comment describing that intent.

WT-10945 Fix workgen compilation

---

test/cppsuite/src/util/barrier.cpp
test/cppsuite/src/util/barrier.h

Address coverity warning with additional refactoring.

WT-10326 Address copy without assignment

---

test/evergreen.yml

(cherry picked from commit 7b89b15c8968b9064a6892530acceacc8089e0d7)

WT-10900 Fix mac crash for python tests. (v6.3 backport) (#9032)

---

test/evergreen.yml

Co-authored-by: Siddhartha Mahajan <siddhartha.mahajan8899@mongodb.com>
(cherry picked from commit 6cc26d69b131f14f870bcf8ecc5bf2f6fbc23ac5)

WT-10932 Remove many collection test (v6.0) (#9089)

---

test/evergreen.yml

Co-authored-by: Siddhartha Mahajan <siddhartha.mahajan8899@mongodb.com>
(cherry picked from commit 6cc26d69b131f14f870bcf8ecc5bf2f6fbc23ac5)

WT-10932 Remove many collection test (v5.0) (#9089)

---

test/evergreen.yml

(cherry picked from commit 7b89b15c8968b9064a6892530acceacc8089e0d7)

WT-10900 Fix mac crash for python tests. (v6.0 backport) (#9032)

---

dist/api_data.py
src/include/wiredtiger.in
src/txn/txn_ckpt.c

WT-9957 Add phrase to document flush tier only applies if tiered storage

---

test/csuite/wt8246_compact_rts_data_correctness/main.c

Retry to insert the data till we get WT_ROLLBACK.

WT-10528 test_wt8246_compact_rts_data_correctness retry to insert the data during WT_ROLLBACK

---

src/btree/bt_sync.c

This reverts commit d31db8f8be34e8ec6b584a1602eee7710243d085.

WT-10979 Revert WT-10062 to make startup faster on 6.0

---

src/btree/bt_sync.c

This reverts commit b09743bdf8073e3bc9bbf5a67bc0d5c855188afa.

WT-10979 Revert WT-10062 to make startup faster on 5.0

---

src/include/error.h
test/evergreen.yml
tools/antithesis/CONFIG.antithesis
tools/antithesis/build_and_push_containers.sh
tools/antithesis/docker-compose.yaml
tools/antithesis/test_format.dockerfile

WT-11003 Updated container for antithesis. Added wt and tracing for format. Added task to compile with release with debug. Changing versioning to identify the container by task. Disabled diagnostic yields. Increased the rows for the format config.

WT-11003 Updated container for antithesis.

---

test/suite/test_checkpoint04.py

(cherry picked from commit 2f59c728dd8413902697761bda85cb39d856dbbe)

WT-10671 Reset statistics when retrying test in test_checkpoint04.py (#9078) (v7.0 backport)

---

test/evergreen.yml

WT-10900 Fix mac crash for python tests (cherry picked from commit 3718ee4f836ac53db26cba378b58e5c2ec14c31e).

WT-10900 Segmentation fault on unit-test-macos on macos-1100

---

test/evergreen.yml

(cherry picked from commit 3718ee4f836ac53db26cba378b58e5c2ec14c31e).
Co-authored-by: Siddhartha Mahajan <55784503+Siddhartha8899@users.noreply.github.com>
(cherry picked from commit e68d2ab250ac91dbe0c9141ae4b754b49f8c6a1c)

WT-10900 Fix mac crash for python tests

---

test/suite/test_backup29.py

Refactor the test for WT-10551 so we can test for the failure both across a restart and when dhandle sweep
leads to closing a file that we then reopen to cause the error.
The sweep code is blatantly stolen from `test_sweep01.py1`
I ran this on `develop` from before the WT-10551 fix to ensure that both scenarios fail as expected.

WT-11036 Add test of incremental backup after files are closed

---

src/schema/schema_truncate.c
test/suite/hook_tiered.py
test/suite/test_truncate01.py
test/suite/test_truncate10.py
test/suite/test_truncate11.py
test/suite/test_truncate12.py
test/suite/test_truncate13.py
test/suite/test_truncate14.py
test/suite/test_truncate15.py
test/suite/test_truncate16.py
test/suite/test_truncate17.py
test/suite/test_truncate18.py
test/suite/test_truncate19.py
test/suite/wttest.py

Reverts wiredtiger/wiredtiger#9133

Revert "WT-10971 Fix truncate for tiered storage."

---

src/reconcile/rec_visibility.c
test/suite/test_bug030.py

(cherry picked from commit afb39a5d7df201dc8ecbff7b24407db1439c12a7)

WT-10522 Don't use aborted tombstone as original value of key (#9083)

---

test/suite/test_checkpoint04.py

(cherry picked from commit 2f59c728dd8413902697761bda85cb39d856dbbe)
(cherry picked from commit 28741784a2a6608c9792d3facac6c862a9f402b1)

WT-10671 Reset statistics when retrying test in test_checkpoint04.py (#9078) (#9123)

---

test/suite/test_checkpoint04.py

(cherry picked from commit 2f59c728dd8413902697761bda85cb39d856dbbe)

WT-10671 Reset statistics when retrying test in test_checkpoint04.py (v5.0) (#9078)

---

test/suite/test_checkpoint04.py

(cherry picked from commit 2f59c728dd8413902697761bda85cb39d856dbbe)

WT-10671 Reset statistics when retrying test in test_checkpoint04.py (v4.4) (#9078)

---

test/evergreen.yml

When executing a script task. Standardize on bash as shell.

WT-7401 Fix silent failures in evergreen

---

dist/stat_data.py
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/txn/txn_ckpt.c
test/suite/test_checkpoint_snapshot02.py
test/suite/test_checkpoint_snapshot05.py

Also, fixed test_checkpoint_snapshot02.py where the same issue was present.
(cherry picked from commit b69729ea9fe2b3124c8c9e6b88378ac124dbb279)

WT-8825 Fix test_checkpoint_snapshot05 expected value validation failure (v7.0) (#9063)

---

tools/antithesis/test.sh

Updating container to print thread dump on core.

WT-11124 Dump threads on container core

---

cmake/helpers.cmake
src/include/ctype_inline.h
test/evergreen.yml
test/suite/wttest.py

(cherry picked from commit 60db8c885489c4847b35d5eb04a63f37e991226e)

WT-11140 Update Python path for Windows and add Python 3.11 (v6.0 backport)

---

dist/stat_data.py
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/txn/txn_ckpt.c
test/suite/test_checkpoint_snapshot02.py
test/suite/test_checkpoint_snapshot05.py

Also, fixed test_checkpoint_snapshot02.py where the same issue was present.
(cherry picked from commit b69729ea9fe2b3124c8c9e6b88378ac124dbb279)
Co-authored-by: Monica Ng <30430618+mm-ng@users.noreply.github.com>
(cherry picked from commit 721d4d71fbedf9364bd85f0d339659b7c8c0149b)

WT-8825 Fix test_checkpoint_snapshot05 expected value validation failure (6.0 backport)

---

test/suite/test_backup29.py

I had to backport WT-10909 and WT-10920 to have a clean backport of WT-11036.

WT-11036 Add test of incremental backup after files are closed (6.0)

---

src/block/block_open.c
src/block_cache/block_mgr.c
src/include/block.h

Reverts wiredtiger/wiredtiger#9286

Revert "WT-11181 Make block unreachable when closing"

---

test/evergreen.yml

cherry picked from commit f7d86b2af9d3aaee6e6d65c8e1df12eadaa546e6)
Co-authored-by: Mick Graham <99703363+mickgraham-mongodb@users.noreply.github.com>
(cherry picked from commit b6ef8abb9edcddffbaeecba9df346b37d47951a9)

WT-10285 Increase instance size for stress sanitizer tasks (#9219) (#9289) 

---

test/csuite/CMakeLists.txt
test/csuite/Makefile.am
test/csuite/wt8246_compact_rts_data_correctness/main.c
test/evergreen.yml

* WT-10528 test_wt8246_compact_rts_data_correctness fails with unexpected mismatch
* Retry 5 times and then abort the test
(cherry picked from commit 1daa7d05a761f3968fbcefa46f2d71803c3cc17d)

WT-10528 test_wt8246_compact_rts_data_correctness retry to insert the data during WT_ROLLBACK (#9099)

---

test/evergreen.yml

(cherry picked from commit 3ffe37211688408d645156e7423d1b52f0f1716c)

WT-11226 Correctly set environment variables in tiered and predictable tests (#9346)

---

test/evergreen.yml
test/evergreen_develop.yml

(cherry picked from commit 3aa2d3f1ccd04e41d1b8d553ed09713a65c61da0)

WT-11233 Ensure all evergreen variants are using the v4 toolchain (#9352) (v7.0 backport)

---

test/evergreen.yml

(cherry picked from commit 3aa2d3f1ccd04e41d1b8d553ed09713a65c61da0) (cherry picked from commit b95a1af76599098cfa9564a12697bf866ec6f04d)

WT-11233 Ensure all evergreen variants are using the v4 toolchain (#9352) (#9355) (v6.0 backport)

---

test/evergreen.yml
test/evergreen/code_coverage_analysis.py
test/evergreen_develop.yml

Added a couple of evergreen tasks to generate the atlas-compatible code coverage reports and to upload the report to the atlas cluster.

WT-11082 Collect and ingest code coverage Evergreen metrics

---

test/csuite/schema_abort/main.c

WT-11268 Check flush_tier just before we do a checkpoint to avoid

---

src/txn/txn_rollback_to_stable.c

This change is a reimplementation for older branches from the commit af1fb31f4ecfa4d8e267c1856d159e84e70c70b4
(cherry picked from commit ccde00ad5b5b48a827cd0101bcf1714d27fe38cd)

WT-11031 Fix RTS to skip tables with no time window information in the checkpoint (5.0 backport)

---

tools/rts_verifier/checker.py
tools/rts_verifier/operation.py

(cherry picked from commit 8751e4ea31ee70487e0a37a8cecef96a9bbd1f43)

WT-11043 Stop RTS verifier raising exceptions until it's more complete (#9175)

---

test/evergreen/run_format_configs.sh

Tightening the process id match and log the process id once the process is finished.

WT-11299 Fix run_format_configs.sh script to grep exact process id

---

cmake/configs/modes.cmake
cmake/configs/msan-ignorelist.txt

Prevent false positives from MSan:
https://reviews.llvm.org/D121652

WT-11218 Suppress MSan false positives

---

cmake/configs/modes.cmake
cmake/configs/msan-ignorelist.txt

Reverts wiredtiger/wiredtiger#9400

Revert "WT-11218 Suppress MSan false positives"

---

ext/compressors/zstd/zstd_compress.c

fix the Memory leak: context_pool

WT-11313 Fix memory leak in zstd compressor

---

src/btree/bt_vrfy_dsk.c

Reverts wiredtiger/wiredtiger#9404

Revert "WT-8003 Print keys in __verify_row_key_order_check in human readable format"

---

test/format/wts.c

This is for when tracing is enabled and the messages where going to the ops tracing log instead stdout which is what Antithesis requires.

WT-11355 Update test format to always out ANTITHESIS messages to stdout

---

src/docs/command-line.dox
src/utilities/util_compact.c

The file [util_create.c](https://github.com/wiredtiger/wiredtiger/blob/develop/src/utilities/util_create.c) was used as a model for the changes.

WT-11369 Update the wt util compact command with a configuration string

---

src/btree/bt_sync.c

I have attached a test on the corresponding Jira ticket to demonstrate the issue. I don't plan on merging in the test.

WT-11321 Free fast-truncated pages in checkpoint cleanup (v6.0)

---

test/suite/hook_tiered.py

Patch build available on JIRA.

WT-11426 Allow background compaction calls with tiered testing

---

src/conn/conn_compact.c

Previously, we would set the `uri` to the `prefix` (file:) after a full iteration or when the server is not supposed to run.
Now, even if the server is requested to stop, we are not erasing the last compacted `uri`. This way, if it is requested to run again, it will resume using `uri` used by the last `compact` call. This gives a chance for all the tables present in the metadata file to be compacted despite multiple calls requesting the turn on/off the background compaction server.

WT-11409 Keep the latest URI compacted even if the background compaction server is stopped

---

src/rollback_to_stable/rts_btree_walk.c
src/rollback_to_stable/rts_history.c

See the ticket for the motivation behind this approach.

WT-8528 Log btree_id in a couple of extra places

---

dist/s_style
src/txn/txn.c

Reverts wiredtiger/wiredtiger#9540

Revert "WT-11424 Revert back to using c stdlib qsort for modification sorting"

---

test/unittest/tests/test_prepare_mod_sort.cpp

Replace the random variables causing occasional segfaults.

WT-11539 Fix segfault in test_prepare_mod_sort.cpp

---

src/block/block_compact.c
src/block/block_open.c
src/include/block.h
test/format/format_config.c
test/suite/test_compact07.py
test/suite/wttest.py

Reverts wiredtiger/wiredtiger#9547

Revert "WT-11432 Prevent parallel compaction on the same URI"

---

test/evergreen.yml

- Change stress tests back to using non perf distros.

WT-11531 Change stress tests back to original distros

---

test/evergreen.yml
test/evergreen_develop.yml

The changes align with the new compilation steps for MDB implemented in SERVER-76751.

WT-11599 Update MonogDB compilation steps in many-collection-test

---

src/txn/txn.c

WT-11638 Fix assertion in prepared update resolution path

---

src/evict/evict_lru.c

The change addresses to issues:
1. __wt_cache_eviction_worker() loops for several times to evict page(s) and make space in cache. When exiting the loop, it reset the return code from the eviction as the caller/application doesn't need to handle the expected eviction failures. When we exit the loop early, as there is a timeout set, we are not hiding the eviction return codes from the caller. This could leak the expected eviction failures like EBUSY/WT_NOTFOUND to the application. This change moves the timeout check before eviction errors could occur.
2. When a timeout is set, we check if the application needs rollback to create more space in cache. If we do, a WT_ROLLBACK error is returned with a reason for the rollback set. The agreement is that a rollback reason will only be set when the …

WT-11602 Hide expected eviction failures from the application and don't rollback in case of errors

---

test/format/format.sh

Add more verbosity around forcibly quitting the run.
(cherry picked from commit 3ff05eff65bee4ff27d45c039fd51593f727c717)

WT-8614 Make format.sh more verbose for failure diagnosis (v4.4)

---

test/format/format.sh

Add more verbosity around forcibly quitting the run.
(cherry picked from commit 3ff05eff65bee4ff27d45c039fd51593f727c717)

WT-8614 Make format.sh more verbose for failure diagnosis (v5.0)

---

src/txn/txn.c

(cherry picked from commit 7436a8fe2ca61e9eb4e92b11525c3ca46c698ac5)

WT-11223 Prepare resolution diagnostic check reads freed update (v7.0 backport)

---

bench/workgen/runner/workgen_stat.sh
bench/wtperf/runners/wtperf_run.sh
dist/s_whitespace
test/checkpoint/recovery-test.sh
test/csuite/schema_abort/smoke.sh
test/csuite/schema_abort/smoke_lazyfs.sh
test/csuite/time_shift_test.sh
test/csuite/wt2447_join_main_table/smoke.sh
test/csuite/wt6185_modify_ts/smoke.sh
test/csuite/wt6616_checkpoint_oldest_ts/smoke.sh
test/evergreen/compatibility_test_for_releases.sh
test/evergreen/install_gcp_dependencies.sh
test/evergreen/setup_spawn_host.sh
test/evergreen/verify_wt_datafiles.sh
test/format/failure_configs/CONFIG.WT-11121
test/format/failure_configs/CONFIG.WT-9792
test/format/format.sh

`dist/s_whitespace` was not checking failure config files and all sh scripts for whitespace formatting.

WT-10883 Add to s_all to check for new lines in test/format and .sh files 

---

test/suite/test_compact03.py

Skip the `test_compact03.py` test with tiered is enabled.

WT-11586 Skip test_compact03.py when tiered is enabled

---

dist/stat_data.py
src/include/btmem.h
src/include/reconcile.h
src/include/stat.h
src/include/wiredtiger.in
src/reconcile/rec_write.c
src/support/stat.c

(cherry picked from commit 3fec160f846361d72c7f65dabb214e5182f05be9)
(cherry picked from commit 7e5a7375fc1635f1d0f1acc02ca63862d885beee)

WT-11168 Remove the page image reuse logic (v6.0 backport)

---

test/compatibility/suite/test_fast_truncate_disk_space.py

Made timestamp usage consistent across transactions and added a comment explaining why we only run with 6.0 as the older branch.

WT-11716 Clarify test scenario in test_fast_truncate_disk_space

---

dist/stat_data.py
src/include/btmem.h
src/include/reconcile.h
src/include/stat.h
src/include/wiredtiger.in
src/reconcile/rec_write.c
src/support/stat.c

(cherry picked from commit 3fec160f846361d72c7f65dabb214e5182f05be9)

WT-11168 Remove page image reuse logic (v4.4 backport)

---

test/evergreen/evg_cfg.py

This pull request aims to provide better error messages and fix better if statement checks.

WT-11745 Improve robustness evergreen script

---

src/schema/schema_open.c
src/schema/schema_stat.c

@agorrod @etienneptl Let me know if this approach is along the lines of what you've been thinking to simplify the statistics retrieval flow.

WT-7929 Investigate a solution to avoid FTDC stalls during checkpoint

---

dist/s_string.ok
src/block/block_open.c
src/block_cache/block_chunkcache.c
src/conn/conn_api.c
src/conn/conn_open.c
src/include/block_chunkcache.h
src/include/extern.h
src/include/meta.h

This reverts commit 99698d7a8bd6ea4e15a6c4da5cfecb6f169daba9.

Revert "WT-11721 Chunk cache metadata file management (#9704)"

---

src/btree/bt_prefetch.c
src/btree/bt_read.c
src/conn/conn_prefetch.c
src/include/btmem.h
src/include/connection.h
src/include/extern.h
src/include/session.h
src/include/wt_internal.h
src/session/session_prefetch.c

Create a new data structure for the pre-fetching variables added in the MVP.

WT-11687 Create a new data structure for prefetching-related information

---

dist/stat_data.py
src/block_cache/block_chunkcache.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

WT-11475 Statistics for inserting new or modified content

---

test/suite/test_checkpoint04.py

Reverts wiredtiger/wiredtiger#9732

Revert "WT-11584 Fix test_checkpoint_stats test"

---

src/btree/bt_sync.c
src/evict/evict_page.c
src/include/extern.h
src/include/txn.h
src/include/txn_inline.h
src/include/wt_internal.h
src/meta/meta_ckpt.c
src/txn/txn.c
src/txn/txn_ckpt.c
src/txn/txn_log.c
test/format/format_inline.h

Reverts wiredtiger/wiredtiger#9742

Revert "WT-11398 Application thread stuck doing eviction because snapshot is old"

---

src/evict/evict_lru.c

(cherry picked from commit 931ba8bab0b80eb471df9b8a741cd4076304a1d3)
Co-authored-by: Sulabh Mahajan <sulabh.mahajan@mongodb.com>
(cherry picked from commit e6617ae602e3818bf01c56a5ea55e85b4cf28e0b)

WT-11602 Hide expected eviction failures from the application and don't rollback in case of errors (v6.0 backport)

---

test/suite/test_checkpoint04.py

(cherry picked from commit ee9b335babbfa7212c20691376d10772c43d5c34)

WT-11584 Fix test_checkpoint_stats test (v5.0 backport)

---

test/suite/test_checkpoint04.py

(cherry picked from commit ee9b335babbfa7212c20691376d10772c43d5c34)

WT-11584 Fix test_checkpoint_stats test (v4.4 backport)

---

test/evergreen/code_change_report/code_change_report.py

Improved the display of information in the Code Change Report.

WT-11738 Code Change Report improvements

---

dist/s_docs
dist/s_string
src/docs/spell.ok

Please see the JIRA ticket for the description of the annoyance faced without those changes.

WT-11844 Sort string.ok and spell.ok

---

test/suite/test_app_thread_evict01.py

WT-11857 Skip the new test test_app_thread_evict01 from the hooks timestamp

---

CONTRIBUTING.rst

Copy minimal but complete style guide for C from internal sources.

WT-11853 Make coding style guidelines publicly available

---

bench/wtperf/wtperf.c

bool Judgment comparison perfect，It is not appropriate to compare the bool type with 0

WT-11886 Cleanup expressions using boolean options

---

src/schema/schema_open.c
src/schema/schema_stat.c

(cherry picked from commit f6b53220bf1ba63e95ff5fd12ab9dc56ec2b6e7a)
Co-authored-by: Monica Ng <30430618+mm-ng@users.noreply.github.com>
(cherry picked from commit bbbf868a3a28fac540aaf5dea02b9fae41910fd3)

BACKPORT-17596 WT-7929 Investigate a solution to avoid FTDC stalls during checkpoint (#9631) (#9780)

---

src/schema/schema_open.c
src/schema/schema_stat.c

(cherry picked from commit f6b53220bf1ba63e95ff5fd12ab9dc56ec2b6e7a)
Co-authored-by: Monica Ng <30430618+mm-ng@users.noreply.github.com>
(cherry picked from commit bbbf868a3a28fac540aaf5dea02b9fae41910fd3)

BACKPORT-17597 WT-7929 Investigate a solution to avoid FTDC stalls during checkpoint (#9631) (#9780)

---

CONTRIBUTING.rst

Also grouped and reordered the items describing variable declaration and initialization.

WT-11955 Fix list formating bug in CONTRIBUTING.rst

---

test/evergreen.yml
test/evergreen/doc_update.py

There are 2 changes made in this PR:
1. Fix the "with" statement in `test/evergreen/doc_update.py` by passing it a context manager object. 
2. Move the "wiredtiger.github.com" folder/tree into the "wiredtiger" folder/tree so that it can be included in the artifacts by default (for ease of debugging).

WT-11971 Fix doc-update task and artifacts archiving

---

dist/stat_data.py
src/block/block_read.c
src/block_cache/block_chunkcache.c
src/conn/conn_chunkcache.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

Reverts wiredtiger/wiredtiger#9862

Revert "WT-11726 Add chunk cache persistence statistics"

---

bench/workgen/workgen.cpp

With the changes, the Testy error mentioned in the JIRA ticket would look like:
```
RuntimeError: Too many open files: Table drop failed for 'table:table_vWH9j_mirror' in create_all.
```
This is enough to say `ret` had the value `EMFILE` at the time of the error.
Please note that I have removed the references to `WT_DECL_RET` to follow what was done in WT-11793.

WT-12009 Add error code in Workgen exceptions

---

bench/workgen/workgen.cpp

Reverts wiredtiger/wiredtiger#9876

Revert "WT-12009 Add error code in Workgen exceptions"

---

src/docs/arch-fast-truncate.dox

This ticket aims to update any unclear sections in the architecture. There are a few places in the architecture guide that I have attempted to make more clear. I have also updated the information to follow the fix of WT-11845

WT-12017 Update truncate section of the architecture guide

---

src/conn/conn_api.c
src/include/extern.h
src/include/misc.h
src/include/time_inline.h
src/rollback_to_stable/rts.c
src/rollback_to_stable/rts_api.c
src/txn/txn.c
src/txn/txn_recover.c

(cherry picked from commit a9f8d18ee3e65fb53546e63744d9c10d0b919783)

WT-11777 Fix units of __wt_timer_evaluate() calls: logging and progress period (#9824)

---

src/block/block_ext.c
src/btree/bt_handle.c

some log perfect, this can help us to understand the code.

WT-12047 improve block_ext logs

---

dist/api_data.py
dist/stat_data.py
src/block/block_read.c
src/block_cache/block_chunkcache.c
src/config/config_def.c
src/conn/conn_capacity.c
src/include/block_chunkcache.h
src/include/capacity.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_chunkcache02.py

Reverts wiredtiger/wiredtiger#9909

Revert "WT-11542 Chunk cache I/O throttling"

---

test/evergreen.yml

Reverts wiredtiger/wiredtiger#9903

Revert "WT-11843 Create nonstandalone variants in evergreen"

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
test/suite/test_cursor_bound21.py

WT-11957 Handle prepare conflicts when traversing next or prev with a bounded cursor

---

src/conn/conn_compact.c

Some cleanup to improve readability.

WT-11990 Create a dedicated function to process excluded tables from background compaction

---

test/csuite/wt12015_backup_corruption/main.c

WT-12103 Fix the assertion about return values from waitpid to account

---

src/docs/introduction.dox
src/docs/portability.dox

Most of the discussion around this has lived on the Jira ticket. Steve Kuhn has OK'ed the general framing of this as "what we test against vs. what we support", so I'm adding some other people who have expressed interest in this.

WT-11550 General portability documentation

---

test/model/src/core/kv_table.cpp
test/model/src/driver/debug_log_parser.cpp
test/model/src/include/model/driver/debug_log_parser.h
test/model/src/include/model/kv_table.h
test/model/test/common/include/model/test/wiredtiger_util.h
test/model/test/common/wiredtiger_util.cpp
test/model/test/model_basic/main.cpp

This PR adds support for truncate to the model.
As usual, feel free to pay less attention to tests. Thank you!

WT-12140 Add support for truncate to the model

---

src/block_cache/block_mgr.c

WT-12151 Fix incorrect read-only initialization of bm->switch_object_end

---

src/evict/evict_lru.c
src/include/cache.h
src/include/cache_inline.h

I have also added assertions to make sure we are not trying to go below 0.

WT-12156 Ensure evict_aggressive_score stays within bounds

---

src/os_posix/os_fs.c

@fedorova I'm requesting a review from you for this as it is a fix from the original mmap work in WT-5170 a few years ago. There is a race condition that allows the reader/writer and a thread extending/resizing the mmap to collide and result in a segfault. @keitharnoldsmith and @korteland because you've been involved in the ticket.

WT-12099 Check racing threads in mmap.

---

src/block_cache/block_tier.c

@ddanderson & @sueloverso: I left a longish comment on WT-7590 explaining in more length why I think this code is safe.

WT-7590 Prevent races in tiered data structures when opening files

---

dist/s_all
test/evergreen.yml

This option seems no longer used.

WT-12198 Remove the reconf option from s_all

---

test/utility/tiered.c

Assert error if pointer is ever null

WT-10106 dereference null pointer

---

test/suite/test_backup12.py
test/suite/test_backup13.py
test/suite/test_backup17.py
test/suite/test_backup22.py
test/suite/test_compact10.py
test/suite/test_compact11.py
test/suite/wtbackup.py

This ticket creates a python test to test the interaction between incremental backup and background compaction.

WT-12049 Create test between incremental backup and background compaction

---

dist/s_string.ok
src/include/gcc.h

Hi @ajmorton,
This PR matches the work described in the acquire/release proposal doc.

WT-12166 Upgrade the write barrier to a full barrier on ARM

---

src/txn/txn_rollback_to_stable.c

WT-10972 Eliminate long periods of silence when recovering with recovery_progress verbose messages enabled (v5.0 backport)

---

test/evergreen.yml

Disable amazon2-arm64-nonstandalone builder

WT-99999 Disable amazon2-arm64-nonstandalone builder

---

test/evergreen.yml

Reverts wiredtiger/wiredtiger#10055

Revert "WT-99999 Disable amazon2-arm64-nonstandalone builder"

---

src/schema/schema_open.c
src/schema/schema_stat.c

(cherry picked from commit f6b53220bf1ba63e95ff5fd12ab9dc56ec2b6e7a)

WT-7929 Investigate a solution to avoid FTDC stalls during checkpoint (v4.4 backport) (#9631)

---

src/btree/bt_split.c
src/include/btmem.h

internal splite marcros perfect

WT-12202 Use macros to replace split magic numbers

---

src/conn/conn_dhandle.c
src/include/dhandle.h
src/meta/meta_ckpt.c

WT-11987 and WT-12043 v7.2 group backport

---

dist/s_string.ok
src/checksum/zseries/crc32-s390x.c
test/csuite/wt2695_checksum/main.c

(cherry picked from commit f04c438863a93ebf8e8b42d053f62bec7b3459f0)

WT-12077 Fix zSeries checksum code (#10021)

---

src/btree/bt_discard.c
src/btree/bt_prefetch.c
src/btree/bt_vrfy.c
src/include/btree_inline.h

(cherry picked from commit 248864f3ecbe26aaa00ce6696f46d9cff8f481be)

WT-11062 Safe free the ref addr to allow concurrent access (#9959)

---

test/evergreen.yml

(cherry picked from commit 070151a733c5659cd920bec491f314a5fb7cb571)

WT-12272 Remove unnecessary module in evergreen.yml (#10118) BACKPORT-18456

---

bench/workgen/runner/many-dhandle-stress.py
bench/workgen/runner/skiplist_stress.py
bench/workgen/runner/split_stress.py
test/evergreen.yml
test/suite/test_gc03.py

Reverts wiredtiger/wiredtiger#10130

Revert "WT-12308 Generate stats in JSON formats in several tests"

---

bench/workgen/runner/many-dhandle-stress.py
bench/workgen/runner/skiplist_stress.py
bench/workgen/runner/split_stress.py
test/evergreen.yml
test/suite/test_gc03.py

Same as https://github.com/wiredtiger/wiredtiger/pull/10130 with the Evergreen changes reverted as the test relies on that specific non-JSON output.

WT-12308 Generate stats in JSON formats in several tests

---

test/evergreen.yml
test/evergreen_develop.yml

Added coverage-report, coverage-report-catch2, code-change-report and cyclomatic-complexity to PR testing.

WT-12290 add code stats to PR testing

---

test/format/wts.c

(cherry picked from commit 8068826997686f2595760d4fa154381c0c0d946f)

WT-12316 Fix test/format timing stress options (#10140)

---

test/format/wts.c

Reverts wiredtiger/wiredtiger#10143

Revert "WT-12316 Fix test/format timing stress options (#10140)"

---

src/include/extern.h
src/rollback_to_stable/rts.c
src/rollback_to_stable/rts_btree_walk.c

@pmacko86 here is the alternative. It is definitely smaller and clearer. @keitharnoldsmith and @kommiharibabu FYI also.

WT-12304 Alternative messaging for RTS progress.

---

dist/api_data.py
dist/s_string.ok
src/btree/bt_debug.c
src/btree/bt_vrfy.c
src/config/config_def.c
src/docs/command-line.dox
src/include/extern.h
src/include/wiredtiger.in
src/utilities/util_verify.c

Update WT verify to have a unredact key option.

WT-10683 Add key unredact and value unredact flags

---

src/block/block_compact.c

Reverts wiredtiger/wiredtiger#10155

Revert "WT-12319 Estimate compaction work again when expected work is done"

---

dist/s_string.ok
src/checksum/zseries/crc32-s390x.c
test/csuite/wt2695_checksum/main.c

Co-authored-by: Will Korteland <korteland@users.noreply.github.com>
(cherry picked from commit e43e88f8f8b41ceb1c5b354c2998f610a303efb8)
(cherry picked from commit f04c438863a93ebf8e8b42d053f62bec7b3459f0)

WT-12077 Fix zSeries checksum code (#10021) (#10114)

---

test/suite/test_compact06.py

(cherry picked from commit af5f9d7789ce9c7250b488a0c287ae1100eb5934)

WT-12061 Skip compact06 with tiered storage (v7.2 backport) (#10000)

---

src/docs/arch-compact.dox
src/session/session_compact.c

- Tidied up the existing section about compaction
- Added a new section dedicated to background compaction

WT-11352 Update the architecture guide with background compaction

---

src/evict/evict_lru.c

Develop evict page log perfect, Added update and dirty information.

WT-12219 Improve log messages for eviction

---

bench/workgen/workgen.cpp

Reverts wiredtiger/wiredtiger#10212

Revert "WT-12428 Use the right locks in Workgen"

---

src/evict/evict_lru.c
src/include/cache.h

Reverts wiredtiger/wiredtiger#10207

Revert "WT-12418 Assert if we don't queue enough pages in aggressive mode for 1 minute"

---

dist/api_config.py
dist/api_err.py
dist/comment_style.py
dist/common_functions.py
dist/common_functions.sh
dist/flags.py
dist/function.py
dist/prototypes.py
dist/pygrep.py
dist/s_all
dist/s_clang_format
dist/s_define
dist/s_docs
dist/s_evergreen_validate
dist/s_fast
dist/s_funcs
dist/s_function
dist/s_getopt
dist/s_longlines
dist/s_stat
dist/s_string
dist/s_style
dist/s_test_suite_no_executable
dist/s_typedef
dist/s_void
dist/s_whitespace
dist/stat.py

Summary of changes:
* Add common functions for filtering out unchanged files from the list in bash and python.
* Use these functions in all scripts where appropriate.
As a result:
* The output it constrained to changed files only (where possible).
* The scripts are simplified and are easier to maintain.

WT-12425 Uniform fast mode for dist scripts.

---

dist/api_config.py
dist/api_err.py
dist/comment_style.py
dist/common_functions.sh
dist/flags.py
dist/function.py
dist/s_function_loop.py
dist/s_function_verbose.py
dist/s_function_with.py
dist/s_outdated_fixmes.py
dist/stat.py
dist/style.py
src/docs/tools/doxypy.py
test/evergreen/evg_cfg.py
tools/wt_to_mdb_bson.py

https://stackoverflow.com/questions/77531208/python3-12-syntaxwarning-on-triplequoted-string-d-must-be-d

WT-12523 Fix Python 3.12 triple-quote string backslash warning.

---

src/txn/txn.c

* Add limit to the amount of timing stress calls.
(cherry picked from commit b8a85f4c8a53a14d9b899c098b6a90968a1f3bd1)

WT-10178 Fix timing stress causing format to time out with prepare-conflict (7.0 backport) (#9187)

---

test/csuite/timestamp_abort/main.c

@pmacko86 please review ASAP. Not sure how it got around both review and PR testing with no failure.

WT-12544 Move initialization of backup_home.

---

src/conn/conn_log.c
src/cursor/cur_log.c
src/log/log.c

The bool type should not use 0 or 1, It is better to use true or false

WT-12517 Use true or false for the bool type instead of 1 or 0

---

src/conn/conn_dhandle.c
src/include/dhandle.h
src/meta/meta_ckpt.c

Cherry picked from the 7.0 changes: https://github.com/wiredtiger/wiredtiger/pull/10181
This applied cleanly. No merge conflicts or changes to resolve

WT-11987 WT-12043 v6.0 group backport

---

src/include/extern.h
src/rollback_to_stable/rts.c
src/rollback_to_stable/rts_btree_walk.c

(cherry picked from commit b0172c96455e13f4cea5bbb2199de3ca539d7a5a)

WT-12304 Alternative messaging for RTS progress (7.0 backport). (#10151)

---

test/format/verify.c

Reverts wiredtiger/wiredtiger#10272

Revert "WT-12431 Pin the snapshot for mirror verification by an active cursor"

---

test/csuite/incr_backup/main.c

Coverity - plus I saw that I typoed a variable name and then copy-pasted the typo.

WT-12579 Initialize local variables. Coverity.

---

test/evergreen/code_change_report/code_change_info.py

Only capture function info for changed or added lines.

WT-12588 Fix function table in the code change report 

---

tools/backup_analysis.py

WT-12600 Fix backup too output to count/output total blocks.

---

src/support/hazard.c

Reverts wiredtiger/wiredtiger#10330

Revert "WT-11894 Convert hazard pointer NULL write to a release write"

---

dist/s_string.ok
src/checksum/zseries/crc32-s390x.c
test/csuite/wt2695_checksum/main.c

This had a couple of merge conflicts, so should be treated with some care.
(cherry picked from commit f04c438863a93ebf8e8b42d053f62bec7b3459f0)

WT-12077 Fix zSeries checksum code (v5.0 backport)

---

src/include/hardware.h
test/evergreen.yml

…o added testing coverage for ARM

WT-12618 Add messages to the static assertions in the new macros

---

dist/s_string.ok
src/checksum/zseries/crc32-s390x.c
test/csuite/wt2695_checksum/main.c

Reverts wiredtiger/wiredtiger#10335

Revert "WT-12077 Fix zSeries checksum code (v5.0 backport)"

---

test/model/src/include/model/driver/kv_workload.h
test/model/src/include/model/driver/kv_workload_runner.h
test/model/src/include/model/driver/kv_workload_runner_wt.h
test/model/src/include/model/util.h

Combining fixes for WT-12220, WT-12317, and WT-12578 into a single PR, plus a few new issues without their own tickets.

WT-12436 Fix Coverity bugs in the model

---

test/evergreen.yml
test/evergreen_develop.yml

Also update TCMALLOC_ENABLE entries in evergreen_develop.yml

WT-12673 Ensure TCMALLOC_ENABLE evaluates as zero if not defined

---

tools/backup_analysis.py

@ddanderson I used some indexes in a wtperf run so added them to the script. But they may be going away with the removal project.

WT-12599 Use parseargs for backup tool. Add verbose mode.

---

cmake/configs/wiredtiger_config.h.in

Remnant accidentally left behind in WT-12586

WT-12711 Remove obsolete references to tcmalloc

---

test/suite/test_compact07.py

Reverts wiredtiger/wiredtiger#10403

Revert "WT-12702 Handle error message related to parallel compaction in compact07"

---

src/btree/bt_debug.c
src/btree/bt_sync.c
src/conn/conn_log.c
src/evict/evict_lru.c
src/include/btree.h
src/include/btree_inline.h
src/include/stat.h
src/reconcile/rec_write.c
src/session/session_api.c
src/support/hazard.c
test/evergreen.yml
test/evergreen/tsan_warnings.supp

Adding four more tests to examples-c-tsan. Since most tests are now enabled I've switched from a test inclusion list to a test exclusion list.

WT-12720 Add ex_call_center, ex_data_source, ex_log, ex_stat to examples-c-tsan

---

dist/s_docs

I used Don's suggestion from the ticket verbatim, since it works perfectly for me. Tested on macOS against both the BSD and GNU coreutils. Adding a second reviewer so Don's not reviewing his own code :-)

WT-12400 Fix s_docs failure on macOS

---

test/format/verify.c

(cherry picked from commit 2a6ac02c415ff5ab8f3c031e616a4a5867dd6007)

WT-12431 Pin the snapshot for mirror verification by an active cursor (v7.3 backport)

---

dist/api_data.py
src/docs/timestamp-global.dox
src/include/wiredtiger.in
src/txn/txn_timestamp.c
test/checkpoint/checkpointer.c
test/format/format_timestamp.c
test/model/src/include/model/kv_database.h
test/model/test/model_checkpoint/main.cpp
test/simulator/timestamp/simulator_interface/simulator_interface.cpp
test/simulator/timestamp/src/timestamp_manager.cpp
test/suite/test_timestamp02.py
test/suite/test_timestamp09.py
test/suite/test_timestamp19.py
test/suite/test_timestamp22.py

Reverts wiredtiger/wiredtiger#10195

Revert "WT-12345 Return an error when setting a timestamp to an older value"

---

test/evergreen.yml
test/evergreen/tcmalloc_install_or_build.sh

Add new evergreen script to make tcmalloc available.
See also WT-12586.

WT-12383 Integrate new tcmalloc

---

src/txn/txn_rollback_to_stable.c

Co-authored-by: sueloverso <sue@mongodb.com>
(cherry picked from commit 93800466f950e2b73be872df1ece864dba90caba)

WT-12304 Alternative messaging for RTS progress (5.0 backport) (#10393)

---

src/include/extern_posix.h
src/os_posix/os_fallocate.c
src/os_posix/os_fs.c

@keitharnoldsmith after all the comments on the other PR, I reviewed my change and came up with this one that I believe is cleaner and simpler. It passes early testing. I am going to let it run much, much longer.

WT-11555 Send remap as a boolean to detect a race

---

src/utilities/util_main.c

Reverts wiredtiger/wiredtiger#10493

Revert "WT-12836 Enable prefetch by default in wt verify"

---

dist/stat_data.py
src/evict/evict_lru.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

add application_cache_ops statistics and Adjust application_evict_time's order

WT-12208 add application_cache_ops statistics and adjust application_evict_time's order

---

src/conn/conn_dhandle.c
src/conn/conn_sweep.c
src/history/hs_conn.c
src/include/btree.h
src/include/extern.h
src/include/txn_inline.h
src/lsm/lsm_merge.c
src/lsm/lsm_tree.c
src/lsm/lsm_work_unit.c
src/meta/meta_turtle.c
src/schema/schema_alter.c
src/schema/schema_drop.c
src/schema/schema_list.c
src/schema/schema_worker.c
src/session/session_api.c
src/session/session_dhandle.c
test/suite/helper.py
test/suite/test_cursor06.py
test/suite/test_drop.py
test/suite/test_drop03.py
test/suite/test_sweep03.py
test/suite/test_tiered20.py
test/suite/wtdataset.py
test/unittest/tests/cursors/test_bulk_cursor.cpp

The original code from Sulabh is commit 1 in branch wt-10576-drop-forced. More was needed to finish the fix. This merged commit is all the changes.

WT-10576 Return EBUSY on forced drop if there is an active transaction.

---

test/suite/test_chunkcache03.py

Occasionally the float division in `self.assertEqual(total_chunks/pinned_chunks, 2)` would evaluate to 2.0625 instead of 2 and fail the test. This assertion works on the assumption that all tables in the test have been populated to be exactly the same size and use the exact same number of chunks, but there is no guarantee that this is true. Instead round the divided result to handle small variation is number of chunks used by each table.
This PR also updates the check to test a few more combinations of pinned tables for certainty.

WT-12872 Make the pinned_ratio check in test_chunkcache03 more lenient

---

src/include/txn_inline.h

optimize txn upd_value's tw assignment method

WT-12842 Tidy up txn upd_value's tw assignment method

---

test/model/src/core/data_value.cpp
test/model/src/core/kv_database.cpp
test/model/src/core/kv_table.cpp
test/model/src/core/kv_table_item.cpp
test/model/src/core/util.cpp
test/model/src/core/verify.cpp
test/model/src/driver/debug_log_parser.cpp
test/model/src/driver/kv_workload_generator.cpp
test/model/src/include/model/data_value.h
test/model/src/include/model/driver/debug_log_parser.h
test/model/src/include/model/driver/kv_workload_generator.h
test/model/src/include/model/driver/kv_workload_runner.h
test/model/src/include/model/kv_checkpoint.h
test/model/src/include/model/kv_database.h
test/model/src/include/model/kv_table.h
test/model/src/include/model/kv_update.h
test/model/src/include/model/util.h
test/model/test/common/include/model/test/util.h
test/model/test/common/include/model/test/wiredtiger_util.h
test/model/test/common/util.cpp
test/model/test/common/wiredtiger_util.cpp
test/model/test/model_basic/main.cpp
test/model/test/model_transaction/main.cpp
test/model/tools/model_test/main.cpp

Add a basic models for our column stores, both FLCS and VLCS, to improve code coverage.
As usual, feel free to pay less attentions to the model's unit tests. Let me know if you'd like a code walk-through.

WT-12882 Add column store support to the model

---

test/evergreen/code_change_report/code_change_report.py

- don't assume prev_complexity exists

WT-12915 Fix code quality PR comment for new functions

---

tools/hexfiend/Templates/WT/WT-Log.tcl
tools/hexfiend/Templates/WT/_intpack.tcl-inc
tools/hexfiend/Templates/WT/_wtpage.tcl-inc

* WT-12926 Fix cell size unpacking
* Numeric keys decode and better decoding of incomplete entries

WT-12926 Fix cell size unpacking

---

test/model/src/core/kv_database.cpp
test/model/src/driver/kv_workload_generator.cpp
test/model/src/include/model/driver/kv_workload_generator.h
test/model/src/include/model/kv_checkpoint.h
test/model/test/common/include/model/test/wiredtiger_util.h

The PR addresses several Coverity errors and adds a missing include to make VS Code happy.

WT-12930 Fix Coverity bugs in the model

---

test/format/checkpoint.c

(cherry picked from commit c07700749d0de9afd38330c63ad15ccc6fbdcfe9)

WT-10802 Handle EBUSY error when checkpointing in test/format (7.0) (#9079)

---

test/evergreen.yml

(cherry picked from commit f91ceec86ebb104b170a8106577d7246c6049c54)

WT-12900 Upload test/format failing CONFIG to Evergreen (7.0) (#10528)

---

dist/stat_data.py
src/btree/bt_sync.c
src/evict/evict_page.c
src/include/extern.h
src/include/stat.h
src/include/txn.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/include/wt_internal.h
src/meta/meta_ckpt.c
src/reconcile/rec_write.c
src/support/stat.c
src/txn/txn.c
src/txn/txn_ckpt.c
src/txn/txn_log.c
test/format/format_inline.h
test/suite/test_app_thread_evict01.py

(cherry picked from commit b7a57e4b457774c8e9d9417a2e69565b50fa0950)

WT-11972 Refresh application thread snapshot if eviction didn't make progress (#10076) (7.0)

---

dist/stat_data.py
src/btree/bt_sync.c
src/evict/evict_page.c
src/include/extern.h
src/include/stat.h
src/include/txn.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/include/wt_internal.h
src/meta/meta_ckpt.c
src/reconcile/rec_write.c
src/support/stat.c
src/txn/txn.c
src/txn/txn_ckpt.c
src/txn/txn_log.c
test/suite/test_app_thread_evict01.py

(cherry picked from commit b7a57e4b457774c8e9d9417a2e69565b50fa0950)

WT-11972 Refresh application thread snapshot if eviction didn't make progress (6.0 backport)

---

cmake/strict/strict_flags_helpers.cmake
test/evergreen/configure_combinations.sh

Tested on my personal machine running Clang 17.0.6.

WT-12630 Fix compilation Clang 17

---

test/format/alter.c
test/format/backup.c
test/format/bulk.c
test/format/checkpoint.c
test/format/compact.c
test/format/format.h
test/format/format_salvage.c
test/format/format_timestamp.c
test/format/format_util.c
test/format/hs.c
test/format/ops.c
test/format/random.c
test/format/verify.c
test/format/wts.c

- `wt_wrap_open_session` can now take a custom session configuration
- Preliminary work to unblock WT-12978

WT-12979 Update test/format to take a config when opening a session

---

src/conn/conn_prefetch.c
src/include/session.h

(cherry picked from commit 4019d090721affe36e97072b120ca16137a23fdb)

WT-12976 Set WT_SESSION_PREFETCH_THREAD for prefetch sessions (#10582)

---

test/suite/compact_util.py
test/suite/rollback_to_stable_util.py
test/suite/test_compact01.py
test/suite/test_compact02.py
test/suite/test_compact03.py
test/suite/test_compact04.py
test/suite/test_compact05.py
test/suite/test_compact06.py
test/suite/test_compact07.py
test/suite/test_compact08.py
test/suite/test_compact09.py
test/suite/test_compact10.py
test/suite/test_compact11.py
test/suite/test_compact12.py
test/suite/test_compact13.py

- Creation of [compact_util.py](https://github.com/wiredtiger/wiredtiger/commit/d0e29ed763312f2562a2d664f514aef8121538c3) which contains methods used across all the compact tests
- Each test has been updated to use the base class

WT-13007 Refactor compact tests

---

src/btree/bt_compact.c
src/btree/bt_delete.c
src/btree/bt_random.c
src/btree/bt_read.c
src/btree/bt_sync_obsolete.c
src/btree/bt_walk.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/include/btmem.h
src/include/btree_inline.h
src/include/extern.h
src/include/reconcile.h
src/include/ref_inline.h
src/include/txn_inline.h
src/reconcile/rec_write.c
src/support/hazard.c
src/txn/txn.c

Implements the type alias WT_REF_STATE for WT_REF::state field.

WT-13048 Use a typedef for WT_REF::state

---

src/conn/conn_prefetch.c

(cherry picked from commit ee3260563585b57be69070c2badb135044b1e385)

WT-12981 Investigate the right way to wait for prefetch readers to drain (#10626)

---

src/evict/evict_lru.c
src/include/btree.h
src/include/log.h
src/include/mutex.h
src/include/mutex_inline.h
src/log/log.c
src/log/log_slot.c
src/txn/txn_ckpt.c
test/evergreen.yml
test/evergreen/tsan_warnings.supp

Add ex_file_system to examples-c-tsan and resolve any new TSan warnings

WT-12731 Add ex_file_system to examples-c-tsan

---

src/block/block_compact.c

(cherry picked from commit 2c8dd3af892cba530036c4520d227430225f8426)

WT-12993 Partially revert WT-12314 (quit compaction early if there is no expected work) (#10609)

---

src/include/hardware.h
test/cppsuite/tests/cache_resize.cpp

Remove or update FIXME comments for Jira tickets that have been closed

WT-13078 Fix outdated FIXME comments

---

dist/stat_data.py
src/evict/evict_lru.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

Successes = attempts - failures.
If anyone wants to add statistics or logs related to eviction, add them to this branch, [wt-8969-eviction-stats](https://github.com/wiredtiger/wiredtiger/tree/wt-8969-eviction-stats). I will handle the code review, and commit.
If you want to add statistics or logs, you can use this PR to see what has already be added without becoming a reviewer and with no need to make comments. You can also add yourself as a reviewer if that is what you want.

WT-8969 Split four eviction statistics into attempts, and failures.

---

test/suite/test_compact09.py

Co-authored-by: Sean <41533874+Sean04@users.noreply.github.com>
(cherry picked from commit 3496b3862cf8294ff4d9746205b64c8e0fb146f4)

WT-13039 Use run_once in test_compact09.py to track stats (#10641)

---

src/cursor/cur_std.c
src/include/api.h
src/include/extern.h

(cherry picked from commit 7facd2810f02f65be3a5530974aa3fc7b645daae)

WT-13025 Do additional fast paths for NULL or blank configurations (#10636) (v8.0)

---

src/cursor/cur_file.c
src/include/txn_inline.h
src/meta/meta_table.c
src/session/session_dhandle.c

Reverts wiredtiger/wiredtiger#10672

Revert "WT-13049 Forbid reading the metadata using the checkpoint cursor transaction"

---

dist/stat_data.py
src/evict/evict_lru.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

(cherry picked from commit 1cc237d6e4e86b0a40765ca688393ee3f7ddbda4)

WT-12863 Update the eviction target page check for selection of tree in eviction walk (v7.0 backport) (#10511)

---

dist/api_data.py
src/btree/bt_vrfy.c
src/include/wiredtiger.in

(cherry picked from commit 8a774da4ecf4a89a31487f1e21edbebbe8b025f6)

WT-13001 Disable history verification when -t option is set (#10687)

---

src/btree/bt_sync.c

(cherry picked from commit 7465e7e9fa01fa69c92dffc0e1d303f20adedf17)

WT-9502 Checkpoint cleanup not to mark the dirty page as obsolete (#8074) (v6.0)

---

src/include/mutex.h
src/support/mtx_rw.c

Reverts wiredtiger/wiredtiger#10751

Revert "WT-13166 Instrument __wt_rwlock_* calls to be TSan compatible"

---

src/btree/bt_delete.c
src/btree/bt_vrfy_dsk.c
src/include/btmem.h
src/include/btree_inline.h
src/include/cell_inline.h

It always == WT_REF_DISK so it is not needed.

WT-10226 Remove WT_PAGE_DEL::previous_ref_state

---

dist/s_clang_format
src/block_cache/block_cache.c
src/btree/row_srch.c
src/checksum/arm64/crc32-arm64.c
src/include/column_inline.h
src/include/os.h
src/log/log_sys.c
src/meta/meta_ckpt.c
src/txn/txn.c
src/txn/txn_recover.c
src/utilities/util_dump.c
test/cppsuite/src/common/thread_manager.h
test/packing/intpack-test3.c

(cherry picked from commit bf70e500b12d2fd175fc966c2787b1182d2648a2)

WT-10619 Clang format upgrade to 12.0.1 (#9436) (7.0)

---

test/evergreen.yml

- Sorted tasks for ubuntu2004-arm64 and amazon2-arm64
- Added format-stress-pull-request-test to both variants

WT-12877 Extend PR testing for ARM variants

---

test/evergreen.yml
test/evergreen/python_version_check.py

[WT-9575](https://jira.mongodb.org/browse/WT-9575) incorrectly removed Mac Python version consistency checks, This PR restores those checks.

WT-13115 Restore Mac Python version consistency check

---

src/include/reconcile.h
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c
test/suite/test_eviction01.py

(cherry picked from commit 739fd1491a41dead5017f134a803d35ae8f0a024)

WT-12560 Fix eviction not making progress with visible but aborted updates (v8.0 backport) (#10640)

---

src/include/cell_inline.h
src/include/connection.h
src/reconcile/rec_child.c
src/reconcile/rec_write.c
src/support/global.c
test/suite/test_truncate20.py

Reverts wiredtiger/wiredtiger#10433

WT-13191 Revert enable point in time truncate functionality for MongoDB

---

src/include/cell_inline.h
src/include/connection.h
src/reconcile/rec_child.c
src/reconcile/rec_write.c
src/support/global.c
test/suite/test_truncate20.py

Reverts wiredtiger/wiredtiger#10788

Revert "WT-13191 Revert enable point in time truncate functionality for MongoDB"

---

src/conf/conf_bind.c
src/conf/conf_compile.c
src/include/conf.h
test/csuite/config/main.c

Reverts wiredtiger/wiredtiger#10458

Revert "WT-12778 Allow a richer set of integral types to fix variable args in bindings."

---

src/include/os.h

WT-13114 Use THOUSAND to replace 1000

---

dist/stat_data.py
src/include/stat.h
src/include/wiredtiger.in
src/reconcile/rec_write.c
src/support/stat.c

(cherry picked from commit b0903c26bcf5f572fce56d2bd927066714442948)

WT-11391 Create 2 new stats for eviction (7.0) (#10046)

---

src/rollback_to_stable/rts_btree.c

Reverts wiredtiger/wiredtiger#10827

Revert "WT-13198 Remove the updates from hs if we rollback any update on the update chain with hs flags in RTS"

---

dist/s_clang-format

fbcc739e7
(cherry picked from commit e672b90a0c5e0ed327caae1667ab1b569125769a)

WT-11092 Update s_clang_format to automatically download aarch64 binaries (6.0) (#10759)

---

dist/s_clang-format
src/block_cache/block_cache.c
src/btree/row_srch.c
src/checksum/arm64/crc32-arm64.c
src/include/column_inline.h
src/include/os.h
src/log/log_sys.c
src/meta/meta_ckpt.c
src/txn/txn.c
src/txn/txn_recover.c
src/utilities/util_dump.c
test/cppsuite/test_harness/thread_manager.h
test/packing/intpack-test3.c

(cherry picked from commit bf70e500b12d2fd175fc966c2787b1182d2648a2)
Co-authored-by: clarissecheah <65272339+clarissecheah@users.noreply.github.com>
(cherry picked from commit 0d882da7e5e93c655236656bbfd774d9355b2528)

WT-10619 Clang format upgrade to 12.0.1 (6.0) (#9436) (#10761)

---

dist/s_string.ok
src/include/connection.h
src/rollback_to_stable/rts_btree.c
src/session/session_helper.c
test/evergreen.yml

Going to run a full patch and see if there are other failures on the feature branch to fix.

WT-13286 Remove string in string.ok and test join02 and 07 from evergreen

---

dist/stat_data.py
src/btree/bt_handle.c
src/include/os_fhandle_inline.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

Reverts wiredtiger/wiredtiger#10365

Revert "WT-12653 enable compression adjustment for small page sizes and add io stats"

---

src/include/txn_inline.h

In `__wt_txn_id_alloc` retrieve the pre-incremented value of `txn_global->current` instead of using the post-incremented value and undoing the change.

WT-13200 Simplify txn id allocation path atomic usage

---

test/evergreen.yml

Reverts wiredtiger/wiredtiger#10950

Revert "WT-13365 fix code change report failure"

---

src/conn/conn_log.c
src/include/log.h

Here's one style of debug that can be added for any future failure like this ticket sees.

WT-13307 Add diagnostic log message when removing log files.

---

dist/stat_data.py
src/evict/evict_lru.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

Fix eviction cache stats name to match the description

WT-13466 Fix eviction cache stats name to match the description.

---

tools/jupyter/InternalTreeStructure.ipynb
tools/jupyter/README.md

Implement a tool that can be extended to answer questions about internal tree-changing algorithms in WiredTiger

WT-13596 Create a Jupyter notebook that can simulate tree shapes and transitions

---

src/btree/bt_import.c
src/btree/bt_sync.c
src/btree/bt_sync_obsolete.c
src/meta/meta_ckpt.c
src/txn/txn_ckpt.c

Reverts wiredtiger/wiredtiger#11052

Revert "WT-13493 Review Checkpoint logging debug levels"

---

test/csuite/wt6185_modify_ts/main.c

Increase the trace buffer size in the modify test so that overflow is exceedingly unlikely. Add an assert and big comment too.

WT-8532 Increase trace buffer size in test. Add comment about overflow.

---

.github/workflows/pr_checklist.yml

Made some wording updates to the PR template based on the feedback collected from the template users, to encourage adoption and make the template more consumable.

WT-13598 Wording updates for the PR template

---

test/suite/test_cc01.py
test/suite/test_cc02.py
test/suite/test_cc03.py
test/suite/test_cc04.py
test/suite/test_cc05.py
test/suite/test_cc07.py
test/suite/test_compact12.py
test/suite/test_truncate20.py

(cherry picked from commit 43f34771d41faa204e3e93c0aff62cfd4826bcd8)

WT-13287 Incorporate checkpoint as part of test_cc_base.wait_for_cc_to_run() (v8.0) (#10885)

---

test/suite/test_bug034.py

Add in WT-12602 reproducer that was accidentally left out in the pull request.

WT-13625 Add python reproducer for WT-12602

---

dist/s_string.ok
src/os_posix/os_dir.c

Reverts wiredtiger/wiredtiger#11097

Revert "WT-13609 Add debugging for rare error case on directories."

---

src/docs/build-posix.dox
test/evergreen.yml
test/multiversion/wt_multiversion.sh

f3cb304093
(cherry picked from commit 6f85c25fa681d67e7ca54c0a76c8ced5b7d2f49b)

WT-13560 Deprecate SSH Cloning of Git repositories (v7.0 backport) (#11144)

---

examples/c/ex_backup_block.c
test/csuite/incr_backup/main.c

Add a summary line to backup test.

WT-13688 Add total ranges summary to backup test.

---

src/docs/build-posix.dox
test/compatibility/common/compatibility_common.py
test/evergreen.yml
test/multiversion/wt_multiversion.sh

f3cb304093
(cherry picked from commit 6f85c25fa681d67e7ca54c0a76c8ced5b7d2f49b)

WT-13560 Deprecate SSH Cloning of Git repositories (port to disagg storage branch)

---

.github/workflows/pr_checklist.yml

This is a non-functional change to the PR template base off feedback received from the team. It makes it a little more succinct.

WT-13689 Minor improvements to the PR template based on engineering feedback

---

dist/access_check/check_sources.py
dist/access_check/init.sh
dist/access_check/requirements.txt
dist/access_check/scan_sources.py
dist/access_check/wt_defs.py
dist/modstat

This PR adds a source modularity analysis tool based on the engine used in the existing s_access script. It can report connections between modules via function calls, structure member uses and macros. The report can have 3 levels of detail: per module, per file, per entity.
Details are in the first comment.

WT-13691 Modularity analysis tool

---

src/docs/build-posix.dox
src/docs/build-windows.dox
test/evergreen.yml
test/multiversion/wt_multiversion.sh

f3cb304093
(cherry picked from commit 6f85c25fa681d67e7ca54c0a76c8ced5b7d2f49b)
(cherry picked from commit f8d5471512fe421a5f6858915f4aba1469a226bf)
There are  a few merge conflicts fixed in `test/evergreen.yml`.

WT-13560 Deprecate SSH Cloning of Git repositories (v6.0 backport) (#11144) (#11151)

---

src/docs/build-autoconf.dox
src/docs/build-posix.dox
src/docs/build-windows.dox
test/evergreen.yml
test/multiversion/wt_multiversion.sh

f3cb304093
(cherry picked from commit 6f85c25fa681d67e7ca54c0a76c8ced5b7d2f49b) (cherry picked from commit f8d5471512fe421a5f6858915f4aba1469a226bf) (cherry picked from commit eca8f4468d658f23b9440f5bcb47f46b777f6bfc)
A few minor conflicts were resolved.

WT-13560 Deprecate SSH Cloning of Git repositories (v5.0 backport) (#11144) (#11151) (#11163)

---

src/cursor/cur_oligarch.c
src/oligarch_log/oligarch_log.c
src/reconcile/rec_write.c
test/suite/test_oligarch09.py

LABS-1268 Fix crash on non block meta and oligarch delete bugs

---

ext/page_log/palm/CMakeLists.txt
src/block_disagg/block_disagg_read.c
src/btree/bt_debug.c
src/include/block.h
src/rollback_to_stable/rts_btree.c

SLS-479 Fix macos build

---

ext/page_log/palm/CMakeLists.txt
ext/page_log/palm/palm_kv.c
test/suite/test_oligarch05.py
test/suite/test_oligarch06.py

SLS-485 Fix byte swapping of keys in PALM, enable some tests

---

dist/access_check/MODSTAT.md
dist/access_check/requirements.txt
dist/access_check/scan_sources.py
dist/access_check/wt_defs.py

WT-13711 Add documentation for modstat tool

---

dist/access_check/requirements.txt

modstat -l displays static functions

WT-13739 modstat -l displays static functions

---

src/reconcile/rec_write.c

SLS-517 Fix verbose null pointer

---

INSTALL
README
cmake/configs/version.cmake
src/docs/spell.ok
src/docs/top/main.dox
src/docs/upgrading.dox

Changes in this PR are made to support cutting a new WiredTiger open-source release, by following the procedure documented in https://github.com/wiredtiger/wiredtiger/wiki/HOWTO%3ABuildARelease.

WT-13634 Cut WiredTiger 11.3.0 release

---

src/block_disagg/block_disagg_write.c
src/btree/bt_page.c
src/include/btree_inline.h
src/reconcile/rec_write.c

Reverts wiredtiger/wiredtiger#11201

Revert "SLS-486 Don't evict pages that belongs to the next checkpoint"

---

src/conn/conn_oligarch.c
src/include/connection.h

Pretty much exactly as described on the ticket. Thanks Peter!

SLS-63 Extend dhandle refresh mechanism to support multiple tables

---

dist/api_data.py
src/config/config_def.c
src/conn/conn_cache.c
src/evict/evict_lru.c
src/include/connection.h
src/include/wiredtiger.in

Add a feature flag `legacy_page_visit_strategy`. Enabling this flag reverts the bug fix here: WT-12643.

WT-13758 Add a feature flag legacy_page_visit_strategy

---

tools/wt_palm_decode.py

SLS-551 Add a basic dumper for the PALM database.

---

test/evergreen.yml

e7149e203a
Co-authored-by: jchen <29520270+jiechenbo@users.noreply.github.com>
(cherry picked from commit aeba39cf47c4596ac31ddf9886417c989a51d85c)

WT-13527 Migrating to new IBM-hosted zSeries hosts (v6.0 backport) (#11213)

---

test/evergreen.yml

e7149e203a
(cherry picked from commit 0feb3ec3274586f25b8b5ca18933787c53f6ca82)

WT-13527 Migrating to new IBM-hosted zSeries hosts (v5.0 backport) 

---

src/btree/bt_handle.c
src/btree/bt_sync.c
src/checkpoint/checkpoint.h
src/checkpoint/checkpoint_conn.c
src/checkpoint/checkpoint_txn.c
src/conn/conn_dhandle.c
src/conn/conn_handle.c
src/include/connection.h
src/include/wt_internal.h
src/meta/meta_ckpt.c
src/rollback_to_stable/rts_btree_walk.c
src/txn/txn.c
src/txn/txn_recover.c

Move checkpoint-related members from connection_impl to dedicated struct.

WT-13782 Move checkpoint-related members from connection_impl to dedicated struct

---

src/block/block_compact.c
src/block_cache/block_mgr.c
src/btree/bt_compact.c
src/include/block.h
src/include/compact.h
src/include/extern.h
src/session/session_compact.c

(cherry picked from commit 6d94648b8d3812cad02e4e7599c64de661bb49e9)

 WT-9607 WT-12302 Fix timing of compact progress messages (v6.0 group backport) (#10858)

---

test/suite/test_layered15.py

Enhance WiredTiger's node step-up test to check the metadata cursor and the data at various points during the step-up.

SLS-725 Enhance the node step-up test

---

test/evergreen.yml

This was left around by mistake. This PR removes it.

WT-13882 Removing evergreen task left over from direct_io

---

test/cppsuite/tests/test_live_restore.cpp

Reverts wiredtiger/wiredtiger#11321

Revert "WT-13880 Fix truncate calls in test_live_restore.cpp"

---

src/support/global.c

This PR optimizes the `__global_calibrate_ticks` function to reduce execution time while maintaining the same level of precision. Test results can be found in the associated Jira ticket.

WT-13781 Update __global_calibrate_ticks to take less time

---

dist/api_data.py
dist/stat_data.py
src/btree/bt_sync.c
src/config/config_def.c
src/conn/conn_api.c
src/conn/conn_reconfig.c
src/evict/evict_page.c
src/include/btmem.h
src/include/btree.h
src/include/connection.h
src/include/extern.h
src/include/stat.h
src/include/wiredtiger.in
src/include/wt_internal.h
src/support/stat.c
src/txn/txn_ckpt.c
src/txn/txn_rollback_to_stable.c
test/suite/eviction_util.py
test/suite/test_eviction02.py

These tickets need to be backported together, and each change can be viewed separately by looking at each commit.

WT-13092 WT-13262 WT-9939 (v5.0 backport)

---

src/include/txn.h
src/reconcile/reconcile.h

WT-13938 Move WT_OP_CONTEXT from reconcile.h to txn.h

---

src/btree/bt_handle.c

This is just in until we can understand whether the server should be using overflow items at all, and if so, what level of support we should provide for that.
It reuses the same path as in-memory trees, where we force set the `maxleafkey` and `maxleafvalue` to (effectively) `UINT32_MAX`.

SLS-841 Workaround for unexpected overflow item usage

---

src/live_restore/live_restore_fs.c
test/catch2/live_restore/unit/test_live_restore_extent_list.cpp

WT-13970 Get WiredTiger building on Macs again

---

src/meta/meta_turtle.c

In the case where we have a fatal error trying to read the turtle file, give more information about what failed to aid in debugging.

WT-13980 Add error value and location information to error message.

---

src/checkpoint/README.md

This PR adds a README file in the checkpoint folder. This README provides a high-level overview of the checkpoint module.

WT-13966 Create a README file for the checkpoint module

---

dist/modularity/wt_defs.py

Based on the recent module assessment, I believe the wt_defs list in dist/modularity should be updated.

WT-13978 Update dist/modularity/wt_defs.py

---

bench/workgen/validate_mirror_tables.py
tools/py_common/binary_data.py
tools/py_common/btree_format.py
tools/py_common/wiredtiger_util.py
tools/wt_binary_decode.py
tools/wt_ckpt_decode.py
tools/wt_cmp_uri.py
tools/wt_timestamps
tools/wt_tools_common.py

Do not require a binary build of WT to run this, use the pure Python version of the integer unpacker.
This changes includes a cherry-pick of fc2ab4b491aee18f1a1c76add12251f101018897 from develop, which refactors needed functions into tools/py_common/binary_data.py (among other nice changes).

SLS-910 Add support to wt_ckpt_decode tool for disagg checkpoint cookies

---

src/checkpoint/checkpoint.h
src/checkpoint/checkpoint_txn.c
src/conn/conn_open.c
src/cursor/cur_backup.c
src/include/extern.h
src/meta/meta_ckpt.c
src/meta/meta_track.c
src/schema/schema_worker.c
src/session/session_api.c
src/session/session_compact.c
src/session/session_dhandle.c
src/txn/txn.c
src/txn/txn_log.c

Rename checkpoint functions for consistency.

WT-13989 Rename checkpoint functions for consistency

---

src/live_restore/live_restore_fs.c

Reverts wiredtiger/wiredtiger#11380

Revert "WT-13890 Add check to ensure live restore read not enclose a hole"

---

test/evergreen.yml
test/evergreen_develop.yml

WT-13995 Upload module metrics to Atlas

---

dist/api_err.py
src/checkpoint/checkpoint_txn.c
src/conn/api_strerror.c
src/conn/conn_compact.c
src/conn/conn_dhandle.c
src/docs/error-handling.dox
src/include/error.h
src/include/wiredtiger.in
test/catch2/misc_tests/test_msg_macros.cpp
test/catch2/misc_tests/test_strerror.cpp
test/suite/test_compact06.py
test/suite/test_error_info.py
test/suite/test_strerror01.py

Reverts wiredtiger/wiredtiger#11388

Revert "WT-13865 New macro WT_RET_SUB and WT_ERR_SUB"

---

dist/api_err.py
src/checkpoint/checkpoint_txn.c
src/conn/api_strerror.c
src/conn/conn_compact.c
src/conn/conn_dhandle.c
src/docs/error-handling.dox
src/include/error.h
src/include/wiredtiger.in
test/catch2/CMakeLists.txt
test/catch2/misc_tests/test_msg_macros.cpp
test/catch2/misc_tests/test_strerror.cpp
test/suite/test_compact06.py
test/suite/test_error_info.py
test/suite/test_strerror01.py
test/suite/test_sweep04.py

Reopening this [PR](https://github.com/wiredtiger/wiredtiger/pull/11388)

WT-13865 New macro WT_RET_SUB and WT_ERR_SUB

---

dist/api_data.py
test/suite/hook_disagg.py

Remove remaining layered_table_log references to make the tests pass.

SLS-1010 Remove remaining layered_table_log references

---

lang/python/wiredtiger.i

1ac6f25bff
Co-authored-by: Etienne Petrel
<77254506+etienneptl@users.noreply.github.com>
(cherry picked from commit fb4019c82e9410791dadf8eb3ca4b86463b47050)
(cherry picked from commit a9760b9912080d68091613a07f8d47eb163c26a2)

WT-13667 Support compiling WiredTiger with SWIG 4.3.0 version (v5.0 backport) (#11456) (#11457)

---

bench/workgen/workgen.cxx
dist/s_string.ok
dist/s_style
ext/storage_sources/dir_store/dir_store.c
test/csuite/wt7989_compact_checkpoint/main.c
test/fuzz/fuzz_util.c

(cherry picked from commit c522dcecaee4091682cdbba66353df47a9f14e27)

WT-10022 Replace sprintf with snprintf in bench and test code (#8399)

---

test/evergreen.yml

(cherry picked from commit f91ceec86ebb104b170a8106577d7246c6049c54) (cherry picked from commit fe2544197555eb3cd6c54275a7c0813708211443)

WT-12900 Upload test/format failing CONFIG to Evergreen (6.0) (#10528) (#10559)

---

src/cursor/cur_stat.c
test/suite/test_layered04.py
test/suite/test_layered06.py

This is a tidied-up version of the change I had to make for the `insert1` jstest to work. I've also added a little bit of testing for it.

SLS-1022 Layered table stats

---

src/include/btmem.h
src/reconcile/rec_write.c

SLS-1072 Fix memory leak

---

dist/s_void
src/cursor/cur_layered.c
test/suite/hook_disagg.py
test/suite/test_layered21.py
test/suite/wtdataset.py
test/suite/wthooks.py
test/suite/wttest.py

- Add parameter to disagg hook to specify a starting role (leader/follower).
- Consolidated disagg parameters internally.
- Add test case for starting as follower, and inserting to follower.

SLS-1040 Allow layered writes to follower

---

test/format/backup.c
test/utility/backup.c
test/utility/test_util.h

Reverts wiredtiger/wiredtiger#11503

Revert "WT-12505 Have format use a separate backup check directory."

---

lang/python/wiredtiger.i

Fix a few random int issues in our SWIG code. This fixes the configure-combinations test.

SLS-1122 Fix signed/unsigned int issues in SWIG

---

ext/page_log/palm/CMakeLists.txt

Fix MSAN compile by removing an unmet dependency.

SLS-1138 Fix MSAN compile

---

dist/stat_data.py
src/block_disagg/block_disagg_open.c
src/block_disagg/block_disagg_read.c
src/block_disagg/block_disagg_write.c
src/include/block.h
src/include/meta.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

Add PUT/GET and bytes read/written statistics for the shared history store in SLS.

SLS-1201 Add statistics for shared HS

---

dist/s_void
lang/python/wiredtiger.i
src/cursor/cur_version.c
src/evict/evict_lru.c
src/include/extern.h
src/include/txn.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/session/session_api.c
src/txn/txn.c
test/format/snap.c
test/suite/test_error_info02.py
test/suite/test_error_info04.py
test/suite/test_txn27.py

Reverts wiredtiger/wiredtiger#11519

Revert "WT-13948 Deprecate rollback_reason API"

---

src/schema/schema_list.c
test/suite/test_layered28.py

SLS-1295 Fix crash when closing a dropped layered table

---

test/catch2/CMakeLists.txt
test/catch2/sub_level_error/api/test_sub_level_error_strerror.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_live_restore_conflict.cpp
test/suite/test_strerror01.py

This PR finds the issues causing build failure and fix those codes.(errors that are fixed is to do)

WT-14154 Investigate the build failure for live restore feature branch

---

dist/stat_data.py
src/include/stat.h
src/include/wiredtiger.in
src/session/session_compact.c
src/support/stat.c

(cherry picked from commit 5aa312f4320bdec3ccead6b3baa42ad16ab32ab4)

WT-12528 Add a stat to track compaction conflicting with a checkpoint(#10255)

---

src/btree/bt_cursor.c

This PR removes adding a tombstone to empty, implicitly created FLCS records, because doing so causes problems during reconciliation (please refer to the ticket and/or the new comment in the code for details).
(cherry picked from commit 284029860b72ce9be2a314497a36ff68de91af04)

WT-12971 Fix assertion failure: 'onpage_upd != ((void*)0) || supd_restore' on FLCS eviction (#10787)

---

src/include/cursor_inline.h

Ignore return code of __wt_evict_app_assist_worker_check in __cursor_enter except WT_ROLLBACK

WT-14025 Ignore return code of __wt_evict_app_assist_worker_check in __cursor_enter

---

src/docs/cursor-log.dox
src/docs/durability-checkpoint.dox
src/docs/durability-log.dox

Documentation review and updates for logging.

WT-14135 Review and update logging documentation

---

test/suite/test_compact07.py

The changes modify compact07.py so background compaction does not interfere with foreground compaction. The test was failing as background compaction was resetting a stat unexpectedly

WT-13432 Don't let background compaction interfere with foreground compaction in compact07

---

src/session/session_compact.c
test/suite/hook_tiered.py
test/suite/test_compact15.py

(cherry picked from commit f49c810f58d706c592a7aa54ae44c3dd0c3f3bb9)

WT-13050 Don't allow NULL URI for foreground compaction (v6.0) (#11486)

---

src/docs/arch-backup.dox

Review/update backup documentation.

WT-14136 Minor edits/updates of backup documentation.

---

test/csuite/timestamp_abort/main.c
test/csuite/timestamp_abort/smoke.sh
test/csuite/timestamp_abort/smoke_lazyfs.sh

Add support for live restore to timestamp_abort.

WT-13792 Add live restore to timestamp_abort

---

src/conn/conn_dhandle.c
test/suite/test_live_restore05.py

Thanks Sean for finding this issue. I've pushed a very minimal reproducer and catcher to ensure we don't regress.

WT-14108 Strip live restore items from the dhandle config

---

test/csuite/timestamp_abort/main.c

WT-14198 Initialize variable.

---

src/live_restore/live_restore_fs.c

Fix computation of read end bit when the file has been extended on the destination.

WT-14200 Fix calculation of read end bit.

---

src/conn/conn_layered.c

Note that this doesn't include testing, since that comes for free with the SLS-1446 PR.

SLS-1421 Remove ingest content after drain

---

src/include/extern.h
src/include/generation_inline.h
src/include/wt_internal.h
src/support/generation.c

This PR moves some functions from .c file to _inline.h

WT-14241 Hot-fix syscall.py issue

---

dist/stat_data.py
src/include/stat.h
src/include/wiredtiger.in
src/reconcile/rec_row.c
src/reconcile/rec_write.c
src/support/stat.c
test/suite/test_layered32.py

SLS-1133 Write internal page delta to PALI

---

test/format/format.h
test/format/format_config.c
test/format/ops.c

(cherry picked from commit dd95565f4feef4cb98df7f630e7e90ee431d63c2)

WT-11448 Fix truncation mismatch verification test problem (#9523) (v7.0 backport)

---

test/csuite/schema_abort/main.c

The changes handle the `WT_ROLLBACK` error code in the schema_abort test.

WT-11556 Handle WT_ROLLBACK in schema_abort

---

src/docs/style/header-web.html

This change removes unused code in the WiredTiger documentation source code because it triggers an XSS warning.

WT-14217 Removed unused doc code that triggers an xss warning.

---

test/csuite/wt13867_interrupt_eviction_handler/main.c

Fix test flakiness due to low timer granularity.
The purpose of this test is to verify the eviction interruption mechanism. It relies on certain metrics, and as a side effect, it also ensures the correctness of those metrics.
However, on systems with low clock granularity, this part of the test is unreliable. One way to mitigate this would be to run the test longer, but that would increase runtime on all platforms.
Instead, I reduced the metrics coverage in this test. Metrics can be tested separately in a dedicated test.

WT-14212 Fix test flakiness due to low timer granularity

---

test/cppsuite/tests/test_live_restore.cpp

Reverts wiredtiger/wiredtiger#11750

Revert "WT-14216 Add test to run crud operations after live restore completion"

---

test/evergreen/code_coverage/code_coverage_config.json
test/evergreen/code_coverage/code_coverage_config_catch2.json
test/evergreen/code_coverage/per_test_code_coverage.py
test/evergreen/code_coverage_analysis.sh

Reverts wiredtiger/wiredtiger#11756

Revert "WT-14410 Fix code coverage report for v5 toolchain"

---

test/suite/helper_disagg.py
test/suite/test_layered23.py

Allow palm_cache_size_mb to be set to increase the PALM cache.\

SLS-1721 For the oplog class, cache cursors during a set of operations.

---

tools/wt_binary_decode.py

The decode tool currently requires the argument --verbose to dump the extent list. This also has the affect of dumping all the keys and values in the blocks. This PR is to add an argument to allow the tool to only decode the extent lists without dumping the other block data.

WT-14348 Add arg to decode tool to optionally print extent lists

---

test/evergreen/build_windows.ps1

Auto detect location of `vcvars.bat`.

WT-14445 Auto detect location of vcvars.bat

---

test/evergreen/build_windows.ps1

Auto detect location of `vcvars.bat`.
(Cherry-picked from 60537f84: WT-14445 Auto detect location of vcvars.bat (#11875))

SLS-2824 Auto detect location of vcvars.bat (Cherry-picked from 60537f84)

---

src/block_cache/block_cache.c
src/block_cache/block_io.c
src/include/block_cache.h
src/include/extern.h
src/include/wt_internal.h
test/suite/test_layered43.py

Add support for deltas to the block cache.

SLS-2868 Support deltas in the block cache on the read path

---

tools/py_common/binary_data.py
tools/py_common/btree_format.py
tools/wt_binary_decode.py
tools/wt_ckpt_decode.py
tools/wt_palm_decode.py

- made wt_binary_decode functions callable externally
- made wt_binary_decode and py_common/* aware of disaggregated storage changes
- Various enhancements for palm debugging to get a similar decoding experience to classic WT.

WT-14569 Enhance wt_palm_decode to call wt_binary_decode.

---

tools/hexfiend/Templates/WT/WT-Log.tcl
tools/hexfiend/Templates/WT/_Utils.tcl-inc
tools/hexfiend/Templates/WT/_intpack.tcl-inc

Fix handling of WT Log files by HexFiend and hexdump.

WT-14573 Fix handling of WT Log files by HexFiend and hexdump

---

src/utilities/util_main.c

Prior to this change, the `wt` utility tool overwrote the provided config string when also provided with the `-m` flag to verify metadata.
As per @kommiharibabu's suggestion - the metadata option `-m` now utilises `metadata_config` instead of `cmd_config`. The code has also been adjusted to account for this change.
Created [WT-14574](https://jira.mongodb.org/browse/WT-14574) to refactor the `wt` tool code.

WT-14392 wt util no longer overwrites config when verifying metadata

---

src/live_restore/live_restore_fs.c

This ticket is to add missing of freeing tmp_buf in __live_restore_fh_read.

WT-14575 Free tmp_buf in __live_restore_fh_read

---

src/live_restore/live_restore_server.c
test/suite/test_live_restore02.py

Adding a completion message for when live restore finishes.

WT-14570 Log a completion message for live restore

---

src/live_restore/live_restore_server.c
test/suite/test_live_restore02.py

Reverts wiredtiger/wiredtiger#11917

Revert "WT-14570 Log a completion message for live restore"

---

dist/stat_data.py
src/cache/cache.c
src/evict/evict_lru.c
src/include/cache.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

Reverts wiredtiger/wiredtiger#11958

Revert "WT-14336 Track the dirty and update bytes of the history store"
