bench/workgen/runner/many-dhandle-stress.py

This PR is to set the threshold max_latency that is used for Jenkins plots: http://build.wiredtiger.com:8080/job/wiredtiger-many-dhandles/plot/

WT-7698 Reduce max_latency value in many-dhandle-stress.py.

---

src/txn/txn.c

Reverts wiredtiger/wiredtiger#6689

Revert "WT-7708 Add an assert to ensure stable timestamp is not moved during prepared commit"

---

test/suite/test_prepare_hs02.py

Even though it's not enforced at the moment but documentation clearly states that during commit in unprepared transaction **commit_timestamp** must be greater than **stable_timestamp**. To avoid ambiguity and possible crashes in the future changing commit timestamp from 301 to 302.

WT-6782 test_prepare_hs02 WT_ROLLBACK failure: conflict between concurrent operations

---

src/txn/txn_rollback_to_stable.c

A visual inspection of the code shows that the Coverity analysis is correct, and the variable rollback_txnid is not used after it is set. 
The issue is not detected by the compiler because of the chained assignment used to initialise the three variables. The compiler thinks that rollback_txnid is being used to assign to rollback_msg_count. If rollback_txnid were the left-most variable in the chained assignment (ie assigned last) then the compiler would display an error because it would consider rollback_txnid unused. 
So, whether the error is triggered in the case of one of the variables being unused after being set is entirely dependent on the order of variables in the chained assignment. This means that the correct fix is to both remove rollback_txnid and, to avoid potential issues …

WT-7696 Fix coverity error - Unused variable in _rollback_to_stable_btree_apply_all

---

src/txn/txn_rollback_to_stable.c

In the definition of macro `WT_CHECK_RECOVERY_FLAG_TS_TXNID`, the `durablets` parameter is not surrounded by parentheses in the implementation. This could cause unexpected behaviour should an expression be passed in as a parameter. 
The macro is used three times in the .c file that it is declared in. Each of the three uses passes a single variable (ie not an unbracketed expression) as the `duablets` parameter, so the missing parentheses in the macro definition do not currently result in incorrect behaviour in the code that uses the macro.
However, subsequent code changes could change the parameters to the macro and expose the missing parentheses.
Hence the code has been changed to add the parentheses, but there is no immediate concern that the un-corrected code is causing bugs right now.

WT-7725 Add missing brackets around parameter in macro definition

---

test/format/t.c

The test-format binary can now reopen an already existing database with different CONFIG files because some configurations are not supported by the older release. In compatibility testing, we want the test format binary to operate on the CONFIG that it understands.

WT-7721 Update test-format to reopen an existing database with different config

---

test/evergreen.yml

Since we've disabled MacOS PR testing, let's switch back to 10.14. MacOS 10.12 is giving us issues because the system compilers are quite old (don't support the `thread_local` keyword) and the MongoDB toolchain seems busted.

WT-7739 Switch back to using MacOS 10.14 for Evergreen compile task

---

test/cppsuite/test_harness/workload/random_generator.h

Neither `std::uniform_int_distribution` or `std::mt19937` are thread-safe so it's not ok to be calling `random_generator::generate_string` concurrently. To fix this, I've marked the singleton instance as `thread_local` so each thread has its own copy.

WT-7738 Fix thread-safety issue in `random_generator`

---

test/cppsuite/tests/run.cxx

We were previously overwriting the `cfg` and `config_filename` variables between each loop iteration which was giving weird behaviour when running the full suite of tests.

WT-7543 Always use default configurations when no config is provided

---

src/reconcile/rec_visibility.c
test/suite/test_prepare_hs05.py

* Use same transaction update when on-disk value is an aborted prepared update
* add a test to verify correct restoration of update from HS after prepared transaction abort
(cherry picked from commit 7074f12888e3e7e93c7ca2fc6f541ebd40b58749)
(cherry picked from commit f63a096cf08f8b5e72b3b36bbaba9bf54c7ba5a9)

WT-7706 Prepared transaction abort should restore correct update from the history store. (#6687) (v4.4 backport)

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable21.py

When an out of order update is performed by a prepared transaction
the earlier updates are not adjusted to the out of order prepared
timestamp. While aborting these updates properly frame the update
that needs to be restored.
(cherry picked from commit c5620904105f2e2f092f0d08d13e610d1fc39c97)
(cherry picked from commit 086b09040dbd291ebf82eba7ccd2012ac2523718)

WT-7699 Fix RTS handling to abort an out of order prepared transaction (#6684) (v4.4 backport)

---

src/cursor/cur_hs.c

(cherry picked from commit 88250b7a3ad29d4338b9d529c277c852889e9bdf)
(cherry picked from commit a41345737223a2432b548566b516ea5f3bd06131)

WT-7710 Fix to use history store btree while initialising HS cursor (#6694) (v4.4 backport)

---

src/conn/conn_tiered.c
test/suite/test_tiered02.py
test/suite/test_tiered03.py
test/suite/test_tiered08.py
test/suite/wtthread.py
test/test_coverage.md

@ddanderson and @sueloverso. This is a heavy handed way of solving a race between checkpoint and flush_tier. But I think it's better as we wrap up the project to support this functionality.  I will create a follow-on ticket to understand and fix the underlying issue with flush-tier and the cached checkpoint metadata and tag it for POC2.

WT-7724 Fix race when running concurrent checkpoint and flush_tier

---

test/csuite/wt3338_partial_update/main.c

The C standard states that the behaviour of memset (and other mem* functions) is undefined when NULL pointers are passed to them. This is the case even if the 'n' count parameter is 0.
The UBSAN tests were picking up a case where a NULL pointer was being passed into this memset call. This was occurring when the 'n' count parameter was 0.
To address this, a conditional guard has been added around the call to memset that was generating an UBSAN error to ensure that the 'n' count parameter is greater than 0.

WT-7744 Fix null pointer within wt3338_partial_update csuite

---

test/csuite/wt3184_dup_index_collator/main.c

Replaced type cast with memcpy to avoid UBSAN error.

WT-7742 Fix misaligned address in wt3184_dup_index_collator/main.c

---

test/format/snap.c

The C standard states that the behaviour of memcpy and memcmp (and other mem* functions) is undefined when NULL pointers are passed to them. This is the case even if the 'n' count parameter is 0.
The UBSAN tests were picking up some cases where NULL pointers were being passed into memcpy and memcmp calls. This was occurring sometimes when the 'n' count parameter was 0.
To address this, conditional guards have been added around the calls to memcpy and memcmp that were generating UBSAN errors to ensure that the 'n' count parameter is greater than 0.

WT-7727 Fix null pointer passed to memcpy() during 'format' test.

---

test/cppsuite/test_harness/core/configuration.h

This seems to do the trick. I don't think we want to merge array contents so we just need to ignore the commas within the array.

WT-7760 Support array parsing in CppSuite config handling

---

src/checksum/x86/crc32-x86.c

UBSAN complains about loading of misaligned address during  the second step of the algorithm where we process 8B chunks. It stops complaining if during the first step we go to the first 8 bytes boundary instead of 4.

WT-7741 Fix misaligned address in crc32-x86.c

---

build_cmake/configs/auto.cmake
build_cmake/helpers.cmake
build_cmake/strict/clang_strict.cmake
ext/compressors/lz4/CMakeLists.txt
ext/compressors/snappy/CMakeLists.txt
ext/compressors/zlib/CMakeLists.txt
ext/compressors/zstd/CMakeLists.txt

On a lot of systems external libraries are in places like /usr/local
or /usr/pkg or /opt that aren't in the default linker path. Use
find_library() instead of check_library_exists() so they can be found
according to user-supplied cmake paths.
When linking with the library, use the path found instead of just the
library name. This is what the cmake manual recommends, rather than
adding to the library path and generating -L linker options.
Also add a HEADER option to config_lib(), use it to look for the
library's header files, and add the resulting dir to the include
path. Pass a header name to uses of config_lib() where this makes
sense.
And, print what's happening in config_lib() since otherwise it's
completely silent.

WT-7748 cmake: fix library probes for libs not on the default linker path

---

bench/wtperf/runners/ycsb-a.wtperf
bench/wtperf/runners/ycsb-b.wtperf
bench/wtperf/runners/ycsb-c.wtperf
bench/wtperf/runners/ycsb-d.wtperf
bench/wtperf/runners/ycsb-e.wtperf
bench/wtperf/wtperf.c
bench/wtperf/wtperf_opt.i
dist/s_string.ok
src/docs/wtperf.dox

Created a native implementation of YCSB in WTPERF. This includes small changes to WTPERF, such as enhanced support for range reads and a new "select-latest" random distribution, as well as new runners for workloads YCSB-A through YCSB-E. There is no runner for YCSB-F, because in WTPERF it is the same as YCSB-A: YCSB-A is 50% reads / 50% updates, and YCSB-F is 50% reads / 50% read-modify-write.

WT-7755 YSCB: Add a native implementation of YCSB to WTPERF.

---

test/csuite/wt3338_partial_update/main.c

The cause and fix are similar to WT-7744.
The C standard states that the behaviour of memset (and other mem* functions) is undefined when NULL pointers are passed to them. This is the case even if the 'n' count parameter is 0.
The UBSAN tests were picking up a case where a NULL pointer was being passed into this memset call. This was occurring when the 'n' count parameter was 0.
To address this, a conditional guard has been added around the call to memset that was generating an UBSAN error to ensure that the 'n' count parameter is greater than 0.

WT-7766 Fix null pointer passed to memset in test_wt3338_partial_update

---

test/packing/intpack-test3.c

The C standard specifies that overflow in signed integers has undefined behaviour.
This test code tests a range of values around a signed start value. If the test value is (or close to) the maximum value for that int type (in this case INT64_MAX) then the range will overflow, and this is what was being detected by the UBSAN test.
The fix is to change the test ranges where required so that overflows are no longer possible.

WT-7765 Fix signed integer overflow in intpack-test3

---

test/csuite/random_directio/main.c
test/format/config.c
test/salvage/salvage.c

Patches for two bugs: (1) use of <ctype.h> functions without casting to unsigned char (possibly undefined behavior) and (2) wrong assertion about the return value of puts().

WT-7447 minor bugs (ctype, puts) in WT tests

---

test/csuite/incr_backup/main.c

Extracted logic of generation of operation type into a separate method. The method does boundary test. All asserts outside of the method are removed as they are redundant now.

WT-7690 Fix coverity error when enum is compared against 0 (incr_backup:table_changes)

---

build_cmake/configs/base.cmake
test/evergreen.yml
test/evergreen/build_windows.ps1

We want to avoid assuming the default build environment requires a development/debug configuration for WiredTiger standalone builds. Change the default value of ENABLE_STRICT to 'OFF' to avoid bringing random warnings and diagnostics into default standalone builds.

WT-7719 Change default value of "ENABLE_STRICT" to "OFF" in CMake

---

src/docs/build-posix.dox
src/docs/spell.ok

* Fixes CC_OPTIMIZE_LEVEL typo in doxygen: The flag value should be 'O1' instead of '01'
* Doxygen description on running CTest: Expanded the CMake doxygen docs to also describe on how to run the CTest smoke tests.

WT-7720 Fix POSIX CMAKE doxygen documentation 

---

CMakeLists.txt
build_cmake/configs/auto.cmake
build_cmake/configs/wiredtiger_config.h.in
build_cmake/helpers.cmake
src/utilities/CMakeLists.txt
test/ctest_helpers.cmake

This PR fixes the following issues:
* CMake didn't link TCMalloc when the `ENABLE_TCMALLOC` option. Updated CMake to link the tcmalloc library when tcmalloc builds are enabled.
* If CMake detects tcmalloc on the user system it will set the `HAVE_LIBTCMALLOC` CPP variable. This is an issue since our C sources will include the tcmalloc headers when `HAVE_LIBTCMALLOC` is defined (Autoconf and SCons will define `HAVE_LIBTCMALLOC` to indicate enabling tcmalloc build). In CMake, we want to reserve the CPP definition `HAVE_LIBTCMALLOC` to just check if the library exists, not to necessarily enable a tcmalloc build. We  want to use the `ENABLE_TCMALLOC` option to actually create a tcmalloc build.
* Removes some dead code in `config_lib` helper

WT-7770 Fix issue linking TCMalloc in CMake

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable21.py

When a prepared update is an out of order update, as part of reconciliation
the earlier updates doesn't modified until it gets committed. while aborting these
uncommitted prepared updates by RTS, it missed to restore the tombstone
from the history store as it is greater than the on-disk update.

WT-7783 Fix RTS to restore tombstone when an on-disk update is out of order prepared

---

test/cppsuite/test_harness/util/debug_utils.h
test/cppsuite/tests/run.cxx

This change is wrapping the use of `std::cout` and `std::cerr` behind a mutex. Since the utility header is used everywhere, we need to make the mutex global (which I've put in the `run` translation unit).

WT-7780 Guarantee log message sequencing in the test framework.

---

test/suite/wttest.py

The CMake build exports the extension libraries to a different build path than libtool/autoconf. This results in the tests that
depend on extension libraries/modules being skipped when used with CMake builds. When searching for extension libraries in the python unit test framework, we want to also search for the location CMake will store the library/module binaries.

WT-7781 Check for CMake ext path in findExtension

---

test/suite/test_backup02.py
test/suite/wtthread.py

I removed the use of "checkpoint=WiredTigerCheckpoint" in compare tables as checkpoint cursor is not supported. This may need to be revisited once PM-1982 project is completed.

WT-7640 Fix test_backup02 where checkpoint tables differ due to checkpoint cursor not supported

---

test/cppsuite/configs/hs_cleanup_default.txt

Temporarily disable postrun statistics since it's causing fallout.

WT-7797 Disable postrun stats in CppSuite testing

---

src/cursor/cur_backup.c
src/docs/backup.dox

Minor fix I saw while reading through backup code. (Plus a small grammar fix in the backup docs.)

WT-7807 Remove unused arg in backup_config.

---

src/reconcile/rec_visibility.c
test/suite/test_prepare08.py
test/suite/test_rollback_to_stable13.py

The logic of stable update in RTS and reconciliation select is
diverged due to the data store squash logic. The history store
properly handles the squash logic, there is no point in having
it multiple places. Removing it from the reconciliation select makes
the code in sync with RTS.

WT-7802 Remove data store same transaction update squash logic

---

test/suite/test_tiered08.py

Reverts wiredtiger/wiredtiger#6773
Found the reason the tiered08 test was failing.  It is an old (and fixed) bug. So we don't need this change to disable the test.

Revert "WT-7816 Disable test_tiered08 on macOS."

---

test/evergreen/compatibility_test_for_releases.sh

Updated the compatibility script to create multiple config files each per release, so that each branch is provided a CONFIG file that it understands.

WT-7599 Compatibility test - create multiple config files for each release

---

test/evergreen/find_cmake.sh

Re-ordered the steps to match the paths for cmake and ctest. This does two things:
1. The order of steps is more consistent with the code from https://github.com/mongodb/mongo-c-driver/blob/master/.evergreen/find-cmake.sh 
2. The code doesn't assume that as a first step that if cmake is found on the path, that ctest is also available on the path.
In addition, the code now logs the CMake and CTest environment variables, paths and versions.
This makes it easier to check that CMake and CTest are configured correctly and being used consistently. It will assist should problems such as WT-7692 occur again in the future.

WT-7692 fix make check test failure on osx10 14 cmake

---

test/cppsuite/test_harness/util/scoped_types.cxx
test/cppsuite/test_harness/workload/database_operation.cxx
test/cppsuite/test_harness/workload/thread_context.cxx
test/cppsuite/test_harness/workload/thread_context.h
test/cppsuite/test_harness/workload/workload_tracking.cxx
test/cppsuite/test_harness/workload/workload_validation.cxx
test/cppsuite/test_harness/workload_generator.cxx
test/cppsuite/tests/example_test.cxx
test/cppsuite/tests/hs_cleanup.cxx

Each issue is a in a separate commit, so please look commit by commit. The thread context change came about as the {{hs_cleanup}} test was using the wrong session. 
The idea is that the only session available now is the one in the thread context, which is also shared with the transaction context.

WT-7836 Fixing a number of small cppsuite issues

---

src/btree/bt_cursor.c
src/include/btmem.h
src/include/wiredtiger.in

Add a hard limit on the number of modify updates before we instantiate a complete update

WT-7776 Add a hard limit on the number of modify updates before we instantiate a complete update

---

lang/python/CMakeLists.txt
test/ctest_dir_sync.cmake
test/ctest_helpers.cmake

The CMake helper `create_test_executable` supports an option to sync a directory over to the build directory:  `ADDITIONAL_DIRECTORIES`. When creating a test executable we may want to sync the contents of a directory (such as a set of configs). Additionally we want this directory to be re-synced on subsequent builds. CMake didn't detect and sync over new files and changes added to the source directory. The commit overhauls the `ADDITIONAL_DIRECTORIES` feature to ensure new files & changes get synced over if present. 
The slight downside of this change is this process needs to be added to the `all` target since CMake can't automatically detect if new files have been added (which is reasonable). 
This PR additionally fixes up issues in the `define_test_variants` helper and SWIG compilation …

WT-7746 Improve directory syncing with CMake helper 'create_test_executable'

---

test/evergreen/compatibility_test_for_releases.sh

Force checksums "on" in the run, there are choices that aren't backward compatible.

WT-7851 Fix illegal checksum configuration in compatibility-test-for-newer-releases

---

test/suite/test_tiered04.py

I should have removed this code when I fixed WT-7591.  I'm addressing that now.
I ran the test a few thousand times without incident.  (I.e., left it running while I made a some tea)

WT-7856 Enable flush test with open cursor in test_tiered04

---

dist/api_data.py
src/config/config_def.c
src/conn/conn_tiered.c
src/include/wiredtiger.in
test/suite/test_tiered04.py

@keitharnoldsmith I asked a question in the ticket about whether to leave in `lock_wait` while adding `timeout`. This first version keeps both.

WT-7732 Add a timeout configuration for flush_tier.

---

test/suite/test_checkpoint_snapshot04.py

If the page gets evicted by an eviction thread all the written updates can be written to disk, because eviction threads operate with a transaction snapshot. It seems that all the pages are trying to evict with the application thread after the transaction is finished can write only the globally visible updates. As this issue is happening only on Z-series machines, this could be the reason behind the cache stuck issue.
The better solution to fix this problem is to increase the cache size of the test to not let the eviction be triggered. The test intention is to verify the backup database, so there is no point in triggering the eviction.

WT-7703 Fix timeout in test_checkpoint_snapshot04

---

test/evergreen.yml

Modified the setup for the code complexity measurements (by moving the install of Metrix++ to outside the 'src' directory. This ensures that our complexity measurements don't accidentally include the Metrix++ source code too.

WT-7870 Fix measurement of cyclomatic code complexity

---

test/evergreen.yml

Modified the setup for the code complexity measurements (by moving the install of Metrix++ to outside the 'src' directory. This ensures that our complexity measurements don't accidentally include the Metrix++ source code too.

WT-7870 Fix measurement of cyclomatic code complexity (take 2, with the correct JIRA ticket number)

---

src/btree/bt_sync.c

When a checkpoint is tasked with garbage collection, it has to
clean up the older content from a file that is now obsolete. To
do so, the checkpoint-cleanup process can effectively visit and
load all of the internal pages in a file. Doing so when the cache
has already reached an aggressive state can be counterproductive.
Not only reading of the pages into the cache for the cleanup can
be slower, but the checkpoint itself could hold eviction in the
aggressive state longer.
When the eviction is set to aggressive, this change allows
checkpointing to skip loading the internal pages that are not
already in cache. This will help a faster checkpoint, and a higher
chance for the cache to get back to normal.
Co-authored-by: Haribabu Kommi <haribabu.kommi@mongodb.com>
Co-authored-by: Sulabh Mahajan …

WT-7787 Don't read pages for checkpoint cleanup when the cache is in aggressive mode

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable22.py

Enable this assert and the test once the reason behind the active transactions
that are still clearing the cache for more than two minutes in an idle system of 
no more operations.

WT-7865 Disable timeout assert while waiting for eviction to quiesce prior to RTS and test

---

src/btree/bt_split.c

This is a bulk backport of the following related changes:
- WT-7871 Remove barrier comment that is no longer true
- WT-7874 Remove two other stale barrier comments

WT-7871 Remove barrier comment that is no longer true (v4.2 backport)

---

test/suite/run.py

Add support to run.py for running lists/ranges of scenarios with -s.
The syntax supported matches e.g. 1-3,5,7-9. A single number is handled
as a trivial list.

WT-7864 Add support to run.py for running lists/ranges of scenarios in a test

---

src/docs/arch-metadata.dox
src/docs/spell.ok

This PR reworks the metadata subpage entry for the Architecture Guide. This subpage being expanded to discuss the format of the WiredTiger.wt table, the role of metadata when checkpointing and how to read WiredTiger metadata.
Please let me know if I should add any additional sections on WT metadata or expand on any points! I was a bit uncertain with what areas should be covered under this topic. Happy to iterate on anything :)

WT-6902 Metadata subpage for Architecture Guide

---

src/include/wiredtiger.in

Some discrepancy was detected by `s_all` check for the `wiredtiger.in` file, after the recent branch syncing between `mongodb-4.4` and `mongodb-5.0` branches. Fix the discrepancy to make `mongodb-4.4` branch truly in sync with `mongodb-5.0`.

WT-7882 Fix discrepancy for wiredtiger.in on mongodb-4.4 branch

---

test/evergreen.yml

`ulimit -n 1000000` is no longer needed as it is by default now.

WT-7842 Remove explicit ulimit call for many-coll-test

---

test/suite/test_encrypt08.py

Catch up to run.py no longer printing wiredtiger_open failures on stdout.

WT-7893 test_encrypt08 fails after merge of wiredtiger_open fixes

---

test/suite/test_rollback_to_stable19.py

WT-7876 Update rollback to stable test to use correct boolean values and update statistic checking logic.

---

test/suite/test_hs01.py

Rollback error at small cache (often at 5MB cache). Hence, increased the cache from 50MB to 200MB, as an extremely constrained cache is not necessary for the test. (As with the large_modify(), where the error occurs, we are not testing eviction but checking for the modified content in the history store after recovery. )

WT-7352 Fix test_hs01 conflict between concurrent operations in cursor modify.

---

dist/s_string.ok
src/include/time_inline.h
src/support/global.c

The instruction isn't exactly the same as instead of cpu cycles its a system
clock. However, this is the same clocksource used for clock_gettime() and
similar calls so it has the same true resolution as those.

WT-7935 add arm64 implementation of rdtsc equivalent instruction

---

dist/s_docs
src/docs/Doxyfile
src/docs/arch-glossary.dox
src/docs/js/sorttable.js
src/docs/spell.ok
src/docs/style/header-web.html
src/docs/style/header.html

Included a way to have sortable tables.
Included \sic, a new way to indicate that the chosen spelling is correct,
without entering it into the dictionary.

WT-6755 Add a glossary to the architecture guide.

---

src/txn/txn_rollback_to_stable.c

On error, __rollback_abort_ondisk_kv() can fail to release allocated memory returned in the value buffer. Don't crack the underlying value unless we actually need it and restructure error handling to avoid leaking the memory. Use a scratch buffer instead of allocating new memory on each iteration.

WT-7938 Fix rollback-to-stable memory leak on error

---

src/txn/txn.c
test/suite/test_assert06.py

I'm struggling to get the python tests running locally (a constant struggle to import `_wiredtiger`, but for the first time I couldn't figure out how to move forward). Meaning I haven't run the test I wrote -- nor have I verified that test fails as expected without the patch.
Hoping to get partial confirmation from the automated testing. In the meantime I'll dive into the problem on my machine.

WT-7943: Do not assert timestamps when rolling back a prepared transactions.

---

test/cppsuite/configs/hs_cleanup_stress.txt
test/cppsuite/test_harness/test.cxx
test/cppsuite/test_harness/timestamp_manager.cxx

- Updated limits for cache_hs_insert
- Updated logs for timestamps
- Added the units to the duration of the test in the logs

WT-7866 Update cache_hs_insert limits in cppsuite-hs-cleanup-stress

---

dist/s_docs
src/docs/arch-hs.dox

Minor docs build fixes:
(1) sort --ignore-case is a gnuism; -f is portable.
(2) handle another case of needing a space at the end of @plantuml_start{file.png }  (seems to be required in doxygen 1.8.20, dunno why)

WT-7952 Minor docs build fixes.

---

dist/stat_data.py
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/txn/txn_rollback_to_stable.c

Rollback to stable doesn't fix any of the deleted or stable
RLE cells as part aborting any unstable updates present on the
page. Skipping them improves the rollback to stable performance.

WT-7956 RTS to skip deleted or stable RLE cells

---

src/include/buf.i
src/support/scratch.c

This pull request aims to fix the memory out of bounds failure occurring within WT-7858. This problem comes from not being able to allocate enough memory from the buffer grow function. Recent changes from WT-7234 needs to be back ported, to account for the fact of overflow items, and to allocate enough memory.

WT-7858 Fix malloc writing out of bounds in compatibility-test-for-newer-releases

---

cmake/configs/base.cmake
cmake/helpers.cmake
lang/python/CMakeLists.txt

If a users system has multiple python installations, when building the Python API, CMake will preference using the highest python version found in the system path. This may be un-ideal if the user wants to preference a specific python version to build the API with e.g. ignore another installation.
This change adds the ability to pass a preferred Python version through a CMake config option. If unset, behaviour will default to the previous functionality, taking the newest Python version it can find.

WT-7947 Allow CMake to take in a specific Python version

---

dist/s_string
dist/s_string.ok

Teach s_string to not look at option lists in __wt_getopt calls.
Purge a bunch of unwanted spelling words that are no longer needed. (This doesn't get rid of all of them, because a few also appear in usage messages and those are not so easily filtered. But it helps.)

WT-7953 Teach s_string to not look inside getopt option lists.

---

lang/python/CMakeLists.txt

The [CMake documentation](https://cmake.org/cmake/help/latest/module/UseSWIG.html) describes the possibility of adding extra dependencies through `SWIG_MODULE_<name>_EXTRA_DEPS` when defining the swig module.
The change made in this PR will ensure the last version of `wiredtiger.in` is used to generate `wiredtigerPYTHON_wrap.c`.

WT-7907 Add dependencies to swig module definition in CMake build

---

test/format/CMakeLists.txt

- When `format.sh` is executed, it looks for the binary `t` within the same directory or under `build_posix/test/format`. 
- `CONFIG.stress` is the default configuration used by `format.sh`, both are under `test/format`.
-  When building with CMake, a different build directory could be used, hence `t` is not found. By copying `format.sh` to `<build_dir>/test/format`, where `t` is, we can tackle this issue. We copy the default test configuration for the same reason.

WT-7955 Copy format.sh and CONFIG.stress to the build directory with CMake

---

CMakeLists.txt
ext/compressors/lz4/CMakeLists.txt
ext/compressors/snappy/CMakeLists.txt
ext/compressors/zlib/CMakeLists.txt
ext/compressors/zstd/CMakeLists.txt
ext/encryptors/sodium/CMakeLists.txt
test/cppsuite/CMakeLists.txt
test/evergreen.yml
test/format/CMakeLists.txt

Currently the CMake build doesn't have correct builtin behaviour, the extension libraries that have been configured for builtins, show no symbols within the wiredtiger library. This ticket aims to fix that via compiling extension libraries for builtins as OBJECTS.

WT-7905 Fix incorrect builtin behaviour for builds in CMake

---

test/checkpoint/checkpointer.c
test/checkpoint/test_checkpoint.c

Set the stable timestamp before starting the checkpointer and clock threads.
Avoids a race where the checkpointer starts up before the clock thread
and then chokes because there's no stable timestamp yet. Seen in WT-7970.

WT-7970 startup race in test_checkpoint produces WT_NOTFOUND

---

src/txn/txn_rollback_to_stable.c
test/csuite/CMakeLists.txt
test/csuite/Makefile.am
test/csuite/schema_abort/main.c
test/csuite/schema_abort/smoke.sh
test/csuite/timestamp_abort/main.c
test/csuite/timestamp_abort/smoke.sh
test/csuite/truncated_log/main.c
test/csuite/truncated_log/smoke.sh
test/csuite/wt2246_col_append/main.c
test/csuite/wt6185_modify_ts/main.c
test/csuite/wt6185_modify_ts/smoke.sh
test/csuite/wt6616_checkpoint_oldest_ts/main.c
test/csuite/wt6616_checkpoint_oldest_ts/smoke.sh
test/suite/test_rollback_to_stable24.py
test/suite/test_rollback_to_stable25.py

Fix RLE counting bug in column rollback to stable, and an error-path
free twice in __rollback_ondisk_fixup_key.
Add column support to C tests: schema_abort, timestamp_abort,
truncated_log, wt6185_modify_ts, wt6616_checkpoint_oldest_ts.
Re-enable wt2246_col_append.
Add two new Python tests, one for the RLE-counting bug and the other
that exercises various cases of rollback-to-stable vs. column-store
RLE cells.
Condense the commit message; so far this is the same as the previous
version of this changeset.

WT-7974 More column fixes and tests.

---

src/docs/arch-cache.dox

Fix a typo, add description of modify structures for column-store
leaf pages, and clean up a couple formatting details.

WT-7998 Minor fixes on Cache subpage of Architecture Guide

---

src/btree/bt_ret.c
src/include/extern.h
src/include/txn_inline.h
test/suite/test_timestamp24.py

Fix accidentally row-specific code in __wt_txn_modify_check.
__wt_txn_modify_check wants to check if an on-disk value exists before
looking at its timestamps. It was checking that cbt->ins is NULL,
which is sufficient for row-store but too enthusiastic for
column-store, leading to acceptance of out-of-order writes and
consequent data corruption.
To fix this, change __wt_read_cell_time_window to report whether it
found anything, and only check the results if it did. Determine this
by checking whether the slot is UINT32_MAX and also whether the slots
array exists at all. For FLCS, return failure instead of the default
timestamp. (Note that __wt_txn_modify_check is the only caller of this
code.)
While here, tidy the interface a bit, and in __wt_txn_modify_check
don't bother checking that the …

WT-8019  VLCS snapshot-isolation search mismatch

---

test/evergreen.yml

- The task `compile wiredtiger docs` does not process all branches anymore, it takes an input arg which defines the branches where the doc needs to be compiled. When it is triggered as part of the PR testing, it should only try to compile the current branch with the current changes. When it is triggered through `update wiredtiger docs`, it should compile all branches.
- The task `update wiredtiger docs` is now triggered once a week.

WT-7914 Update the documentation correctly and only when required

---

test/format/smoke.sh

Enable VLCS format testing in "make check'.
While I'm in the area, pick a minimum cache size so we don't time out during the run and increase
the number of rows/operations to a larger number so there's at least a little work being done.

WT-6193 Re-enable VLCS testing in format-test

---

test/format/util.c

- Added a missed unlock from WT-7708

WT-7942 Release timestamp lock in test/format when all_durable timestamp is not found

---

test/evergreen.yml
test/format/CONFIG.endian

Enable variable-length column-store access method in `test/format/CONFIG.endian`, and increase the running frequency for endian-related Evergreen tasks.

WT-7294 Re-enable VLCS evergreen endianness tests

---

src/cursor/cur_file.c
src/cursor/cur_std.c
src/include/meta.h
src/meta/meta_apply.c
src/meta/meta_ckpt.c
src/session/session_api.c
src/txn/txn_rollback_to_stable.c

I've added a new macro, `WT_BTREE_PREFIX` for checking if a uri starts with `file:` or `tiered:`.  I wasn't sure of the best place to put the macro.  It's in `meta.h`, but I could imagine it going in `btree.h`, as well, or maybe elsewhere.

WT-7745 Add macro to identify uris for btree objects

---

src/btree/bt_vrfy_dsk.c
src/include/api.h

Add a call to WT_SESSION.breakpoint in the verify disk image verification code so it's easy to
set a breakpoint in gdb when debugging page format changes.
Clean up the API process macros:
- Change the thread-check publish macro to a full barrier; there isn't any reason to flush
writes BEFORE assigning to WT_SESSION.api_tid, what you want is that assignment to be flushed
before another thread uses the session.
- Don't hard-code "session" use. It's probably safe, but the session is a macro argument, use
the argument instead.
- Use the standard cursor-to-session macros instead of hard-coding the call.

WT-8079 add breakpoint to verify error macros, clean up API processing

---

test/suite/hook_tiered.py

Also disable the `modify_smoke_recover` test from `test_cursor12.py` as it doesn't work with the tiered hook due to WT-8096.

WT-8081 Fix tiered hook functions to provide default for config string

---

test/csuite/CMakeLists.txt
test/csuite/Makefile.am
test/csuite/wt8057_compact_stress/main.c
test/evergreen.yml

This test verifies that there are no data inconsistencies if compact operation is interrupted by an unclean shutdown. To achieve this, the main process spawns a child process. The child process perform certain operations on two identical tables. The parent process randomly kills child process and verifies that the data across two tables match after restart.

WT-8057 New test to verify the data after aborted compaction

---

test/csuite/CMakeLists.txt
test/csuite/Makefile.am
test/csuite/wt8057_compact_stress/main.c
test/evergreen.yml

This test verifies that there are no data inconsistencies if compact operation is interrupted by an unclean shutdown. To achieve this, the main process spawns a child process. The child process perform certain operations on two identical tables. The parent process randomly kills child process and verifies that the data across two tables match after restart.

WT-8057 Add a test to verify that changing compact is not resulting in data loss

---

test/cppsuite/create_test.sh
test/cppsuite/test_harness/workload/database_operation.cxx
test/cppsuite/test_harness/workload/random_generator.cxx
test/cppsuite/test_harness/workload/random_generator.h
test/cppsuite/test_harness/workload/thread_context.cxx
test/cppsuite/test_harness/workload/thread_context.h
test/cppsuite/tests/example_test.cxx

On top of https://github.com/wiredtiger/wiredtiger/pull/6997:
- Added required macros for old gcc versions, see a4d5132e0f81962b8d36c730d5c913ee2b9d33d8

WT-8093 Improve the CPP testing framework for better flexibility

---

ext/storage_sources/local_store/local_store.c

Includes checking error returns from all snprintf calls.

WT-8108 Use temporary files and rename in local store

---

src/btree/bt_delete.c
test/suite/test_verify2.py

- The `WT_BTREE_READONLY` flag is already checked within `__wt_page_modify_set`
- Only set the `btree` as modified if `original` is not true

WT-8126 Mark btree as dirty only if not newly created when instantiating a deleted row-store leaf page

---

test/suite/test_timestamp22.py

I have gone ahead and modified the test_timestamp22, i.e., the commit timestamp generated randomly cannot be lesser than the recent durable timestamp. 
OOD does not work well with prepared updates as WiredTiger crashes if the commit timestamp is lesser than the durable timestamp.

WT-7169 Fix test_timestamp22.test_timestamp_randomizer failure in time window validation.

---

test/checkpoint/workers.c

In the current implementation, there's no way `ret` can be non-zero. It's safe to just remove the redundant check.

WT-8069 Coverity analysis defect 120706: Redundant test

---

dist/api_data.py
src/btree/bt_walk.c
src/config/config_def.c
src/conn/conn_api.c
src/include/connection.h
test/format/config.h
test/format/config_compat.c
test/format/config_compat.sed
test/format/failure_configs/CONFIG.WT-5637
test/format/failure_configs/CONFIG.WT-6568
test/format/failure_configs/CONFIG.WT-6725
test/format/failure_configs/CONFIG.WT-6727
test/format/format.h
test/format/wts.c

Removing the split_8 timing configuration given this particular stress timing option hasn't really be useful in finding/detecting
any race conditions (since being added). Additionally using the split_8 timing stress during stress tests runs adds a significant
run time i.e multiple hours, slowing the system down to a crawl.

WT-8048 Remove split_8 timing stress configuration

---

src/include/extern.h
src/session/session_api.c
src/session/session_compact.c
test/csuite/wt7989_compact_checkpoint/main.c

This pull request implements the following changes:
1. Change all checkpoints in compact to "wait" checkpoints. This eliminates all conflicts between external (system/application) and internal compact checkpoints. If wait happens, additional checkpoint call shouldn't add too much overhead. Compact operation is expected to take a fairly long time. Adding a little extra delay shouldn't affect general performance too much.
2. "wt7989_compact_checkpoint" test now runs multiple checkpoints in parallel with compact. The first one starts immediately and the following checkpoints start after a random delay.

WT-8055 Fix issue when compact quits when running at the same time as a checkpoint

---

test/evergreen.yml

Currently when ctest executes the smoke target, it does so with the verbosity option '-VV'. When parsing the logs for potential failures, this gets extremely noisy and hard to parse, since multiple parallel test outputs are interleaved with each other. 
To simplify this, remove the 'VV' option and replace it with 'output-on-failure'. This ensures all the output for a failing test will be logged, whilst successful test output will not be logged.

WT-8161 Reduce verbosity of CMake Evergreen smoke

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
test/suite/test_search_near01.py
test/suite/test_search_near02.py

This ticket covers performing a prefix search near early exit when we are traversing in the insert list. This benefits two causes:
1. This ticket will increase performance when we are doing a prefix search near, if there are a lot of inserts in the list.
2. The cursor can potentially returns an entry outside of the prefix key range when we are performing a prefix search near. This change will fix that behaviour as we double check if the prefix matches between the tree entry and the search key.
Furthermore this ticket also addresses fixes from WT-8044. When we are performing prefix search near on an insert list, cbt->tmp is NULL. Therefore we change this behaviour to check if the valid key matches the prefix of search near after we gather the key `__cursor_kv_return `

WT-8092 prefix enabled search_near does not return the correct key when in memory

---

src/evict/evict_lru.c
src/support/thread_group.c

I believe that since the eviction threads are also stopped (or __wt_evict_thread_stop is called) if an error has occurred in __thread_run, we should also expect the same. Hence, added the WT_CONN_PANIC flag in two assert statements in wt_evict_thread_run and _wt_evict_thread_stop.

WT-8036 Added connection panic flag in two assert statements in wt_evict_thread_run and _wt_evict_thread_stop.

---

examples/c/CMakeLists.txt
test/csuite/CMakeLists.txt
test/ctest_helpers.cmake

We currently use a CMake helper, `define_c_test`, for defining our csuite tests. An argument you can give is `SMOKE`, which is shorthand for "execute the test with a script named smoke.sh, where the script is located in the tests source sub-directory". Using `SMOKE` can be quite confusing as it assumes multiple things about the test and abstracts important details e.g. test arguments, script location (mistakes have been made in the past using `SMOKE`). 
Defining test definitions should be clear and easy to read, i.e. should be easy to determine how the test is run from its definition,  where uses of `SMOKE` achieves the opposite of this (for background, `define_c_test` used to be a macro where uses of `SMOKE` in context of the csuite tests was useful. However`define_c_test` has since been …

WT-8162 Remove SMOKE arg in 'define_c_test' helper

---

test/csuite/wt3338_partial_update/main.c
test/format/format.h
test/format/ops.c
test/utility/CMakeLists.txt
test/utility/Makefile.am
test/utility/modify.c
test/utility/test_util.h

@quchenhao, based on our discussions on WT-8019, I added code to format to validate the returned data from `WT_CURSOR.modify()`. I think it's generally useful, so this is a branch for that work.

WT-8022 Verify WT_CURSOR.modify return values in format test program.

---

src/btree/bt_slvg.c

- Added a check on `ss->ovfl` to avoid passing a NULL pointer to `bsearch` when there are no overflow items.

WT-8059 Add a check in salvage when no overflow items are found

---

bench/workgen/workgen.cxx
test/cppsuite/test_harness/connection_manager.h
test/cppsuite/test_harness/util/logger.h
test/cppsuite/test_harness/util/scoped_types.h
test/cppsuite/test_harness/workload/random_generator.h

The macros are `__STDC_LIMIT_MACROS` and `__STDC_FORMAT_MACROS`, we now check if they are already defined before defining them.

WT-8115 Define macros only when necessary in cpp files

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable27.py

Fix a corner case of VLCS rollback-to-stable.
It turns out that just the presence of a stable update for one key in the cell isn't sufficient to skip the whole cell. While it's true that in a fully timestamped world, if there's a stable update it must be newer than the cell's on-disk value and therefore the cell's on-disk value must be stable, this breaks down if the stable update isn't timestamped. We can skip iterating the cell if _every_ key in it has a stable update; otherwise we need to check each key.
It's also incorrect to call downstream to __rollback_abort_ondisk_kv for keys that have a stable update; the downstream code assumes that no stable update exists and will in some cases (e.g. in-memory databases) do the wrong thing if one does.
Therefore:
- have …

WT-8193 Wrong corner case in VLCS rollback-to-stable

---

test/cppsuite/CMakeLists.txt
test/cppsuite/Makefile.am
test/cppsuite/test_harness/connection_manager.cxx
test/cppsuite/test_harness/connection_manager.h
test/cppsuite/test_harness/workload/random_generator.cxx
test/cppsuite/tests/basic_test.cxx
test/cppsuite/tests/csuite_style_example_test.cxx
test/cppsuite/tests/example_test.cxx
test/cppsuite/tests/run.cxx
test/utility/CMakeLists.txt

- Added the `run` function to `example_test.cxx` file. This way, when one creates a test with the script `create_test.sh`, they will be given the possibility to override the `run` function and have more control over their test. This was already possible before this change since `run` is a virtual function but now it is more explicit.
- Added a new test `csuite_style_example .cxx` that barely uses the framework.
- Modified the CMake build for the cpp suite.
- API change for the `connection_manager` where `create` now returns a `WT_CONNECTION*`
- Corrected a bug when a specified test with the command `./run -t` would not exist
- Improved some code in the random generator helper class

WT-8171 Implement a C style test in the CPP testing framework

---

test/evergreen.yml

- Added `--enable-diagnostic` to `cppsuite-stress-tests` in evergreen
- Alphabetized the flags

WT-8101 Enable diagnostic mode for the CPP tests in evergreen

---

bench/wtperf/wtperf_run_py/perf_stat_collection.py
bench/wtperf/wtperf_run_py/wtperf_run.py
dist/s_whitespace

* Removed Python checking from s_whitespace as it was rejecting PEP8 compliant line-break usage.
* Modified the wtperf_run_py Python code to be PEP8 compatible, as checked by the pycodestyle tool. This includes introducing double line-breaks where required to comply with the PEP8 requirement to "Surround top-level function and class definitions with two blank lines.".

WT-8199 Make s_all accept Python PEP8 compliant line breaks

---

test/suite/test_debug_mode10.py
test/suite/test_rollback_to_stable28.py

Introduces a python suite test that enables the debug mode setting for update restore evict during recovery. The debug mode forces update restore eviction whenever we evict a page. We want to perform this in recovery to ensure that all the in-memory images have the proper write generation number and we don't end up reading stale transaction ID's stored on the page.
Let me know if I should expand the test in any way, wasn't super sure if I covered all the important behaviors/scenarios/edge cases :)

WT-7494 Add Python test to trigger update restore eviction during recovery

---

test/format/config.c

Change format to allow single and double quote characters, evergreen scripts use them.

WT-8331 change format to allow quote characters

---

test/evergreen.yml
tools/run_parallel.sh

- Reduced the number of test iterations for those stress tests that have been running out of disk space.
- Log disk usage info at the start of each iteration to help diagnose future disk space issues.

WT-8253 Fix disk space issue in stress tests

---

dist/api_data.py
src/docs/transactions.dox
src/include/wiredtiger.in
src/txn/txn_timestamp.c
test/suite/test_prepare06.py

This reverts commit c371a9cd2ac4ced5790fe256bfa4408d1973d77b.

WT-8114 Revert allow setting the prepare timestamp smaller than or equal to the latest active read timestamp with roundup prepare config

---

test/checkpoint/workers.c

Fix slipup in test_checkpoint that made it immediately overwrite all its modifies.

WT-8347 Slipup in test_checkpoint modify changes

---

test/evergreen.yml

Increase evergreen timeout to 1 hr to allow time for test to do recovery.

WT-8157 Fix format-abort-recovery-stress-test timeout condition

---

test/format/config.c
test/format/config.sh
test/format/config_def.c
test/format/format.h
test/format/smoke.sh
test/format/t.c
test/format/wts.c

Fix problems where the wrong type of value was used to turn a configuration value off.
Add new functionality to configure a value "off" so we don't have to do it manually.
Switch from a mixture of "none" and "off" for "not configured" or "configured off" strings, always use "off".

WT-8350 format uses the wrong syntax to turn off common prefix configuration

---

test/format/config.c

Switching from a mixture of "none" and "off" for "not configured" or "configured off" strings to always using "off" leads to problems in the historic format builds used in compatibility runs. For the 3 configurations that used "none" previously (logging.compression, btree.compression and disk.encryption), output "none" instead of "off".

WT-8354 Historic format builds used in compatibility runs need their previous syntax

---

test/format/format.i
test/format/wts.c

Coverity reports the statistics cursors can be used uninitialized because it's not seeing that the WiredTiger library will return an error in any path where a cursor isn't initialized. Change the statistics functions to use format's underlying cursor-open function and change that function to initialize the returned cursor for clarity and to hopefully avoid these complaints in the future.
While I'm in the area:
Abstract out the code to dump a cursor's worth of statistics, it's identical between tables and the connection, no need to have two copies.
Assert the printf's into the output file succeed.

WT-8355 Coverity analysis defect 121096: Uninitialized pointer read

---

CMakeLists.txt
cmake/configs/base.cmake
cmake/configs/x86/windows/config.cmake
cmake/define_libwiredtiger.cmake
cmake/install/install.cmake
lang/python/CMakeLists.txt
lang/python/setup_pip.py
src/utilities/CMakeLists.txt
test/ctest_helpers.cmake
test/fuzz/CMakeLists.txt
test/utility/CMakeLists.txt

Currently we only support compiling either a static or shared build of the WiredTiger library in CMake (being a binary option). For some uses case, it can be ideal to compile both the static and shared artifacts in a single build e.g. for a system installation. This change overhauls the CMake build of the wiredtiger target such that we can compile both a static and shared wiredtiger in the same build run i.e. no longer limited to either a static or shared build. This change brings a bit more feature parity with autoconf (before we officially deprecate it).
More specifically, the key changes this PR introduces:
- CMake configuration option `ENABLE_SHARED` : Introduces a seperate configuration option, `ENABLE_SHARED`, in conjunction to `ENABLE_STATIC`. The intention is to support the …

WT-8335 Support compiling both a static and shared WiredTiger library in CMake

---

bench/wtperf/wtperf.c

Addition of missing comma to csv header for wtperf monitor file

WT-8339 wtperf monitor missing comma

---

bench/wtperf/runners/log.json
bench/wtperf/runners/log_many_threads.json
bench/wtperf/runners/log_no_checkpoints.json
bench/wtperf/runners/log_no_prealloc.json
bench/wtperf/runners/log_small_files.json
bench/wtperf/runners/log_zero_fill.json
bench/wtperf/runners/update-btree.json
bench/wtperf/runners/update-checkpoint.json
bench/wtperf/runners/update-stress.json
bench/wtperf/wtperf_run_py/perf_stat.py
bench/wtperf/wtperf_run_py/perf_stat_collection.py
bench/wtperf/wtperf_run_py/wtperf_run.py
test/evergreen.yml

Migration of the log-consolidation performance tests from Jenkins to Evergreen.
Also in the commit:
- In Arg files (e.g. update-btree.json) multiple arguments can now be passed into wtperf
- Introduction of the min/max_throughput stats
- When wtperf fails print the stderr output for debugging purposes

WT-5011 - Migrate log consolidation tests to Evergreen

---

test/csuite/schema_abort/smoke.sh

Turn non-timestamp testing back on.

WT-6116 test_schema_abort failed with data loss

---

test/csuite/random_abort/main.c
test/csuite/random_directio/main.c
test/csuite/schema_abort/main.c
test/csuite/tiered_abort/main.c
test/csuite/timestamp_abort/main.c
test/csuite/truncated_log/main.c
test/csuite/wt2909_checkpoint_integrity/main.c
test/csuite/wt4803_history_store_abort/main.c
test/csuite/wt6616_checkpoint_oldest_ts/main.c
test/csuite/wt8057_compact_stress/main.c

Don't call exit() without an exec, call _exit() instead.
While I'm in the area...
Close the WiredTiger connection when we're done, that cleans up everything else.
Remove/re-create the WiredTiger directory near where we open it.
Simplify a couple of failure checks.

WT-8291 AddressSanitizer reported attempting double-free during test_wt4803_history_store_abort

---

test/evergreen.yml

Only do one format smoke test run in each Evergreen test run.

WT-8321 Fix format-stress-smoke-test timeout condition

---

test/suite/test_verbose01.py
test/suite/test_verbose02.py

Implementation of new tests to verify the new verbose API is working as expected when specific categories along with verbosity levels are set. The main changes are:
- Creation of a class that defines common helpers that are used across the different verbose test classes.
- Creation of a new file that contains the tests related to the new verbose API

WT-8256 Create new tests capturing different verbose configuration scenarios

---

test/cppsuite/CMakeLists.txt

On CMake builds of WiredTiger with TCMalloc enabled, the cppsuite crashes due to an invalid pointer error when free()'ing memory. 
When the tcmalloc config is enabled, CMake builds the cppsuite without linking tcmalloc (defaulting to the standard libc allocator), whilst the WiredTiger library is linked against tcmalloc. This meaning two different allocators are being used at runtime. 
This becomes problematic as it appears the cppsuite is allocating/freeing/sharing memory between itself and WiredTiger, thus leading to an invalid pointer free() error. 
To fix this, update the cppsuite to also link against TCMalloc (if WiredTiger is using TCMalloc). This keeping the allocator runtime uniform between the two artifacts.

WT-8364 Fix CMake bug for TCMalloc cppsuite builds

---

src/include/verbose.h

Letting 'wt_verbose_multi' wrap over another macro results in the category field completely expanding, rather than its intermediate string representation. For various uses of the macro this ends up being a string representation of the entire
WT_VERBOSE_MULTI_CATEGORY struct definition, resulting in an overly verbose message. To fix this, avoid calling an underlying macro, performing the multi-check inline.

WT-8368 Avoid using wrapper in __wt_verbose_multi

---

test/csuite/CMakeLists.txt
test/csuite/tiered_abort/main.c
test/csuite/tiered_abort/smoke.sh

This PR involves fixing the tiered abort test to work with the cmake builds. Currently the required libraries and build directory only adheres to the build_posix system. This ticket aims to make it work for both, meaning we will need to return the correct library location and build directory based on the system.

WT-8076 Modify tiered_abort csuite test to work with cmake

---

test/evergreen.yml

WT-8321 made changes to let smoke test tasks run the test once (instead of multiple times). Those tasks are no longer suitable to be included in the stress test builders. 
Changes in this PR include:
- Move the smoke test tasks from the stress test builders into the base Ubuntu and Ubuntu ASAN builders. 
- Remove the task tags from smoke test tasks and add the tasks into PPC & zSeries builders explicitly.
- Reduce the times of run to 1 for the smoke test PPC task.

WT-8359 Separate smoke tests from stress tests in Evergreen

---

bench/wtperf/runners/evict-btree-stress-multi.json
bench/wtperf/runners/evict-fairness.json
bench/wtperf/runners/log.json
bench/wtperf/runners/log_many_threads.json
bench/wtperf/runners/log_no_checkpoints.json
bench/wtperf/runners/log_no_prealloc.json
bench/wtperf/runners/log_small_files.json
bench/wtperf/runners/log_zero_fill.json
bench/wtperf/runners/update-stress.json
bench/wtperf/wtperf_run_py/perf_stat.py
bench/wtperf/wtperf_run_py/wtperf_config.py
bench/wtperf/wtperf_run_py/wtperf_run.py
test/evergreen.yml

Pass the `operations` and `arguments` parameters to wtperf_run.py via command line instead of through an `arg_file`. Now these parameters can be passed via `-ops` and `-args` instead of via `-a path/to/arg_file.json`
Additionally `arg_file` (-a) has been renamed to `batch_file` (-bf) to indicate it is intended for running multiple jobs with slightly different wtperf arguments, and shouldn't be used for a single test

WT-8358 Pass args via command line

---

test/evergreen.yml

In the wtperf-test Evergreen task, display the path of the wtperf config file in the logs for each test executed.

WT-5580 Dump the wtperf command into logs in Evergreen wtperf test

---

bench/wtperf/wtperf_run_py/validate_expected_stats.py
test/evergreen.yml

Add an evergreen function to validate that performance tests return an expected values for each stat.
`perf-test-evict-fairness` will now fail if "Pages seen by eviction" is not exactly 200.

WT-8363 - Validate stats output by perf tests

---

bench/wtperf/wtperf_run_py/validate_expected_stats.py
test/evergreen.yml

Redelivery of https://github.com/wiredtiger/wiredtiger/pull/7173 (Reverted here https://github.com/wiredtiger/wiredtiger/pull/7183).
This change is identical to the original review, but moves the `perf.send` and `s3.put` commands back into `upload-perf-test-stats` with new commit 11f6785.

WT-8363 Redeliver Validate stats output by perf tests

---

test/suite/test_hs24.py

Fix test_hs24.zero_ts_deletes for FLCS deleted rows reading back as 0.
Also add a sleep before starting the checkpoint so the removes running asynchronously in the background have a chance to get started. This makes it much more likely that any of them will actually be seen afterwards. (That they aren't is how this got missed.)

WT-8399 test_hs24.test_zero_ts fails on FLCS on lagged test machines

---

test/suite/test_rollback_to_stable28.py

Disable rts28 on VLCS as well as FLCS.
It seems the test is timing-dependent and fails sometimes on the test machines because it doesn't always trigger the update restore eviction it's supposed to exercise.

WT-8400 Disable test_rollback_to_stable28 for VLCS

---

test/suite/test_rollback_to_stable10.py

Adjust HS assertions in the "prepare" test of rts10.
Currently, adding time.sleep(50) before stopping the background checkpointer makes the hs_sweep > 0 assertion fail. This is because under these circmstances all the outdated HS entries are removed by the data-store RTS and counted in hs_removed instead of hs_sweep. Since tests shouldn't be timing-dependent, assert about the sum of hs_removed and hs_sweep instead of each individually.

WT-8398 test_rollback_to_stable10 is timing-dependent

---

src/block/block_cache.c

The rewriting of the formula caused it to report no overhead when the number of lookups was smaller than the number of insertions and removals, but this is precisely the situation when the overhead is high. As a result, performance dropped by 30-70%. The proposed changed reverses the performance regression.

WT-8410 Conversion from floats to integers changed overhead computation formula in block cache.

---

test/suite/test_inmem01.py

Always skip the inmem01.insert_over_delete_replace test on FLCS.
While I'm pretty sure the previous change was sound in principle, it seems that the threshold that works for me is not portable to the test environment, and since I don't myself have direct access tracking down a suitable threshold value is not currently worthwhile.

WT-8419 Disable test_inmem01.test_insert_over_delete_replace for FLCS

---

test/cppsuite/configs/search_near_01_stress.txt
test/cppsuite/tests/search_near_01.cxx

The fix involved in the PR, regards to increasing the assert limit for search near 01 cppsuite test. The reason for this change is because we previously didn't account if a thread would perform multiple search nears before another thread completing one. To account for this fact, I have doubled the expected entries to account for this anomaly. Now this change presumes that it is not possible to have all threads performing two search nears which on theory is impossible.

WT-8361 Increase assert limit in search near 01 cppsuite test

---

bench/wtperf/wtperf_run_py/perf_stat.py
bench/wtperf/wtperf_run_py/perf_stat_collection.py
bench/wtperf/wtperf_run_py/wtperf_run.py

Instead of reading all PerfStats and then filtering them out at the reporting stage, define the list of required PerfStats when we build PerfStatCollection and only read these values.
Additionally wtperf_run.py::main() has been split into subfunctions to make things cleaner

WT-8369 - Filter perf stats on PerfStatCollection construction

---

test/suite/test_verbose01.py
test/suite/test_verbose03.py
test/suite/wttest.py

Added a python suite test to assert valid JSON messages are produced when enabling them via the event handler interface.
Valid messages are those that can be successfully parsed as JSON (meeting the JSON standard) and subscribe to an expected schema (i.e. contain expected fields and types).

WT-8260 Python test to validate new EVENT_HANDLER JSON schema

---

test/evergreen.yml

When compiling WiredTiger in the Evergreen little-endian variant,
the build is configured with the v3 mongodbtoolchain. We
subsequently need to ensure the PATH is set to point to the mongodb
toolchain when running make. Otherwise build scripts invoked
during the compilation process i.e. workgen's 'setup.py', will
be called with a mis-matched toolchain.

WT-8424 Use consistent toolchain in little-endian

---

test/csuite/wt7989_compact_checkpoint/main.c
test/csuite/wt8057_compact_stress/main.c

Compaction is a best-effort algorithm. It moves blocks from the end to the beginning of the file but there is no guarantee that all empty space at the beginning will be filled. The logic in the algorithm checks if at least 20% of the file is available in the first 80% of the file, we'll try compaction on the last 20% of the file. Else if at least 10% of the total file is available in the first 90% of the file, we'll try compaction on the last 10% of the file. It may well happen that 9.9% of the space is available for reuse in the first 90% of the file. And 9.9% available in the last 10% of the file. In this case, the algorithm would give up. But total available space in the file would be 19.8%. So we need to check that there is a maximum of 20% space available for reuse after compaction.

WT-8250 size_check_res failure in test_wt7989_compact_checkpoint

---

test/evergreen.yml

WT-8292 - switched the WiredTiger performance tests from running on ubuntu2004-large to ubuntu2004-medium instances.

WT-8292 - switched the WiredTiger performance tests from running on ubuntu2004-large to ubuntu2004-medium instances.

---

test/suite/test_tiered04.py

WT-8430 Add sleep back in to allow thread to run for testing on slower

---

test/format/backup.c

This ticket involves fixing a previously unused return value. This error was happening on line 66, and was never used afterwards. Coverity found that the variable was being unused afterwards.
I have employed a solution where we don't need to reset ret, and instead change the if condition to check if unlink failed with errno being set other than ENOENT.

WT-8385 Fix unused value in test format backup

---

test/format/config.c

Increase variable type size to avoid Coverity complaint that the value could overflow.

WT-8388 Increase variable type size to avoid Coverity complaint that the value could overflow in test/format

---

test/format/bulk.c
test/format/config.c
test/format/kv.c
test/format/ops.c
test/format/salvage.c
test/format/wts.c

Coverity doesn't understand the relationship between ntables and the tables array, clarify it.

WT-8387 Assert table cannot be NULL when tables_apply is used in test/format

---

test/format/config.c

Coverity doesn't understand the relationship between ntables and the tables array, clarify it.

WT-8390 Assert table cannot be NULL within config_table in test/format

---

test/format/format.i

Setting a side-effect variable to NULL makes Coverity think it can be NULL when the function returns, remove the set to NULL.

WT-8384 Coverity analysis defect 121118: Explicit null dereferenced

---

test/format/snap.c

Fix a bug in format (which is  one of the principle reasons RTS can't acquire exclusive handlelocks), found by Coverity, where a test was swapped and we weren't closing WT_SESSION handles.

WT-8386 Coverity analysis defect 121104: Dereference after null check

---

test/format/config.c

Simplify an input loop to avoid any tainted-scalar reports from Coverity.

WT-8389 Coverity analysis defect 121099: Untrusted loop bound

---

test/format/format.sh
test/format/smoke.sh

Re-enable FLCS smoke testing in format.

WT-8013 Re-enable FLCS smoke testing in format.

---

examples/c/CMakeLists.txt
examples/c/ex_verbose.c
src/docs/programming.dox
src/docs/verbose-messaging.dox

This PR updates the doxygen documentation with a new page on WiredTiger's verbose messaging system. This reflecting the recent changes to the configuration interface, including a discussion about the verbosity levels and categories. 
This PR specifically adds:
* A new doc page under `Writing WiredTiger applications` describing the verbose messaging system
* A new `C` example: To demonstrate basic usage of the verbose messaging API and provide code snippets that can be used in the accompanying doxygen page.

WT-8257 Verbose Messaging Doc Page

---

examples/c/ex_verbose.c

Explicitly cast the session pointer in ex_verbose to meet the
print format argument. This fixing a warning triggered by the
'format-pedantic' compiler diagnostic.

WT-8463 Fix 'format-pedantic' error in ex_verbose

---

test/csuite/random_abort/main.c
test/csuite/random_directio/main.c
test/csuite/schema_abort/main.c
test/csuite/tiered_abort/main.c
test/csuite/timestamp_abort/main.c
test/csuite/truncated_log/main.c
test/csuite/wt2909_checkpoint_integrity/main.c
test/csuite/wt4803_history_store_abort/main.c
test/csuite/wt6616_checkpoint_oldest_ts/main.c
test/csuite/wt8057_compact_stress/main.c
test/csuite/wt8246_compact_rts_data_correctness/main.c
test/salvage/salvage.c
test/utility/misc.c
test/utility/test_util.h

Rename test_checksys() to test_assert_errno(), flipping the sense of the test.

WT-8459 rename test_checksys() to test_assert_errno()

---

dist/s_all
dist/s_mentions

Generated build scripts in `build_posix` and `cmake_build` will contain wiredtiger's filepath, and when the filepath contains the ticket that `s_mentions` is checking for (e.g. `~/src/wt-8448/wiredtiger`) then `s_mentions` will return false positive matches.
Update `s_mentions` to handle this case.
Additionally ensure that any reported matches by `s_mentions` are treated as warnings only and `s_all` does not fail when they are detected.

WT-8448 - s_mentions finds content that should not be matching

---

dist/test_data.py
src/config/test_config.c
test/cppsuite/configs/search_near_01_default.txt
test/cppsuite/configs/search_near_01_stress.txt
test/cppsuite/tests/search_near_01.cxx

Historically search near 01 has suffered through quite alot of concurrency issues when testing the number of expected traversals of a prefix search near. The problem is that testing expects only at max `thread_count` number of search nears to be happening at once. This is a large mistake, because one thread can actually not be scheduled for a long while. 
I have implemented an idea, where we have one read thread that manages the spawning and joining of all threads then checking the statistics. This allows us to be confident that there are no search nears being performed while we are testing the expected number of traversals.

WT-8417 Restructure assert testing in search near 01 cpp for concurrency

---

test/format/config.c

Fix calls to isblank(); they're supposed to be passed 0..255 (or EOF) but not -2..-128. NetBSD's libc has been arranged to generate a warning (and thus fail statically) if char is passed; it should be cast to unsigned char.

WT-8475 isblank() build failure on NetBSD

---

src/support/err.c

We previously directed all 'wt_verbose' messages through the
'WT_EVENT_HANDLE::handle_message' interface, regardless of
verbosity level. The 'WT_EVENT_HANDLE::handle_message' interface
is the appropriate interface for the bulk of the verbosity levels,
except for 'WT_VERBOSE_ERROR'. This change ensures messages
associated with the 'WT_VERBOSE_ERROR' will be directed through
the 'WT_EVENT_HANDLE::handle_error' interface.

WT-8446 Direct verbose error messages to handle_error

---

build_posix/aclocal/strict.m4
cmake/strict/strict_flags_helpers.cmake
dist/s_clang-scan.diff
src/block/block_ckpt_scan.c
src/btree/bt_sync.c
src/conn/conn_dhandle.c
src/conn/conn_stat.c
src/cursor/cur_index.c
src/cursor/cur_stat.c
src/evict/evict_lru.c
src/evict/evict_page.c
src/evict/evict_stat.c
src/history/hs_verify.c
src/log/log_slot.c
src/lsm/lsm_merge.c
src/schema/schema_alter.c
src/schema/schema_create.c
src/schema/schema_rename.c
src/support/hazard.c
src/support/mtx_rw.c
src/tiered/tiered_handle.c
src/txn/txn_ckpt.c

This branch fixes all but a few of the clang-scan warnings (there's another branch for WT-8466 that moves some files around and fixes two that remain, the ones in `bt_read.c`  and `bt_io.c`).
I did a commit per file, hopefully that makes it more obvious what got changed.

WT-8474 review clang analyzer warnings

---

CMakeLists.txt

If strict is enabled, the intermediate wt_objs target in CMake
needs to compile with the diagnostic flag. This change corrects a
bug where our CMake build didn't apply the diagnostic flags to
the intermediate object library.

WT-8483 Use diagnostics on CMake wt_objs target

---

test/checkpoint/recovery-test.sh
tools/run_parallel.sh

Currently our evergreen task, uses the parallel script to run the recovery-test.sh script through multiple iterations of parrallel jobs. We need to clear the WT_TEST.out file after we finish executing the test, because another iteration of the script will grep for WT_TEST.out on a completed test run. This is dangerous behaviour.

WT-8360 Remove WT_TEST output file when test finishes in recovery-test script

---

src/btree/bt_debug.c
src/btree/bt_page.c
src/btree/bt_vrfy_dsk.c
src/include/bitstring_inline.h
src/include/btmem.h
src/include/cell_inline.h
src/reconcile/rec_col.c
src/reconcile/rec_write.c

Don't zero the whole FLCS disk buffer up front.
- Explicitly zero the leftover bits in the last byte of the bitmap data, if any.
- Explicitly zero the empty/wasted space on odd-sized pages.
- Check both these points in __verify_dsk_col_fix.
This requires adjusting the auxiliary header read code slightly to expose the empty space, which previously had been abstracted away.
While here, remove accidental doubled check in __verify_dsk_col_fix.

WT-8487 FLCS reconciliation zeroes the entire disk buffer in advance

---

test/evergreen.yml

the `unit-test-with-compile` task is only called in the` macos-1014` build variant.

WT-8515 Remove unit-test-with-compile function as it is redundant.

---

test/evergreen.yml

In Evergreen, variables live within the scope of a task. If a function
defines a variable once, it will persist and be visible to the
subsequent function calls within that task. If a test should not use
extra variables, it should be executed before the extra variables are
defined.

WT-8520 Reorder csuite tests in the long-test task

---

dist/api_data.py
src/btree/bt_handle.c
src/docs/tune-page-size-and-comp.dox
src/include/wiredtiger.in

Because the configured page size is used to size the bitmap data and the time windows come along for the ride, and the time windows (if present) are much larger than the data itself, the default page size limit of 512M allows generating pages far larger than 4G.
The hard limit on the page size is around 8M; an 8M bitmap in a 1t table has 64 million entries, each of which can in theory have a time window as large as 63 bytes attached, for a total space of just under 4G.
However, because FLCS pages that size perform poorly even when they aren't bloated out with timestamps, set the limit much lower, to a somewhat arbitrarily selected 128K, which is still considerably larger than you'd actually want to use in practice.

WT-8514 Apply an explicit page size limit to FLCS pages

---

test/evergreen.yml

The `ftruncate-test` was updated with the following changes:
- Use the `csuite test` function for `test_truncated_log`
- Enable and use the `csuite smoke test` for `random_abort`

WT-8519 Use csuite functions in evergreen.yml

---

test/evergreen.yml

Don't report an error in the `save wt hang analyzer core/debugger files` task when there are no Hang Analyzer artifacts to upload.
Evergreen now prints the trace
`file '/data/mci/a4f3beb3412bf6dd9816880952165975/wt-hang-analyzer.tgz' not found but skip missing true`
instead of the (red font) error 
`Command failed: missing file '/data/mci/a4f3beb3412bf6dd9816880952165975/wt-hang-analyzer.tgz': problem opening file /data/mci/a4f3beb3412bf6dd9816880952165975/wt-hang-analyzer.tgz: open /data/mci/a4f3beb3412bf6dd9816880952165975/wt-hang-analyzer.tgz: no such file or directory`
in the `s3.put` step.

WT-8522 Don't report error in Evergreen when there are no Hang Analyzer artifacts to upload

---

test/evergreen.yml

The short-term solution is to avoid recompiling WiredTiger for the tasks mentioned in the WT-8511 description by calling the compile wiredtiger function once within each task (only the tasks in the description).
That said, a long-term solution would be to follow the evergreen best practice to only compile once and let the other tasks fetch the binaries. Since, this approach seems more involved, created WT-8525

WT-8511 Remove unnecessary fetching of the cached binaries in evergreen.yml

---

lang/python/wiredtiger.i
src/txn/txn_timestamp.c
test/suite/test_timestamp09.py
test/suite/test_timestamp21.py

Turn off MongoDB timestamp informational messages in standalone builds, they're too verbose if the application isn't tracking the oldest available read timestamp.

WT-8547 MongoDB timestamp information messages are application-specific

---

src/btree/bt_debug.c
src/conn/conn_api.c
src/conn/conn_reconfig.c
src/include/extern.h

Don't reconfigure JSON or verbose settings just because some other setting is being reconfigured.
Split JSON configuration out into its own function for simplicity.

WT-8546 verbose/JSON output configurations shouldn't reset without reason

---

src/btree/bt_delete.c
test/suite/test_truncate06.py
test/suite/test_truncate07.py

Fix behavior of fast-truncate when conflicting with a prior remove.
(check both start times and stop times, not just start times)
Add new test truncate06 that checks this and a variety of related scenarios.

WT-8493 Fast-truncate fails to detect conflicts with prior removes

---

bench/wtperf/runners/large-lsm-large.wtperf
bench/wtperf/runners/large-lsm.wtperf
bench/wtperf/runners/overflow-10k.wtperf

The history-store/timestamp rework of FLCS limits the maximum leaf page size to 128KB.
@jeremythorp, I wasn't able to reproduce this failure, maybe my build is off or something, but the fix seems obvious.

WT-8535 Wiredtiger-perf-stress-jobs failed for fixed-length column store due to page size larger than 128Kb

---

dist/log.py
src/cursor/cur_json.c
src/include/extern.h
src/include/misc.h
src/log/log_auto.c
src/support/err.c
src/utilities/util_dump.c

@alisonfel, @etienneptl, here are the changes so we don't truncate error/verbose messages.
BTW, the motivation for this change is that `format` test program (and other test or application programs, I guess), want to trace operations on key/value pairs that are potentially quite large. Currently we truncate big verbose and error messages, and it's especially problematic since the actual error information follows the message, so big messages likely discard error information. Additionally, because format will run 100s of verbose messages a second through message processing, we want to avoid copying and memory allocation if possible.
The heart of the change is using allocated scratch buffers when the stack buffer isn't sufficient. In the JSON path, I immediately allocate a scratch buffer and …

WT-8545 WiredTiger error messages are truncated unnecessarily

---

test/cppsuite/test_harness/test.cxx
test/cppsuite/test_harness/test.h

Add a couple of missing includes to some files in the cppsuite tests.
I tested this by changing every v3 reference in evergreen.yml to v4, as well as in the cmake/toolchains directory and running the same set of tests we run on pull requests. See the ticket for details/output.

WT-8529 MongoDB V4 toolchain can't build cppsuite

---

src/schema/schema_project.c

Assume key/value can be empty, resulting in allocating a buffer without any memory and triggering a UBSAN undefined error.

WT-8577 UBSAN undefined error in schema layer

---

test/checkpoint/test_checkpoint.c

This change is required for WT-8554 (Automated testing for upgrade from 4.4 releases). It has to go in a separate commit because we need to backport it to 4.4 and 5.0.

WT-8576 Enabled logging in test checkpoint.

---

src/conn/conn_api.c
src/txn/txn_recover.c
test/suite/test_checkpoint_snapshot02.py

WiredTiger versions 10.0.1 onward have a valid checkpoint snapshot on-disk. There was a bug
in some versions of WiredTiger that are tagged with the 10.0.0 release, which saved the wrong
checkpoint snapshot, so we ignore the snapshot when it was created with one of those versions.
Versions of WiredTiger prior to 10.0.0 never saved a checkpoint snapshot. Additionally, the turtle
file doesn't always exist (for example, backup doesn't include the turtle file), so there isn't always
a WiredTiger version is available. If there is no version available, assume that the snapshot is valid,
otherwise restoring from a backup won't work.
Co-authored-by: Alexander Gorrod <alexander.gorrod@mongodb.com>
(cherry picked from commit 172d0033bd8608828bcb79cf935e458493c9aba1)

WT-8534 Allow retrieving the checkpoint snapshot for backup restore recovery (5.0 backport)

---

src/conn/conn_api.c
src/txn/txn_recover.c
test/suite/test_checkpoint_snapshot02.py

WiredTiger versions 10.0.1 onward have a valid checkpoint snapshot on-disk. There was a bug
in some versions of WiredTiger that are tagged with the 10.0.0 release, which saved the wrong
checkpoint snapshot, so we ignore the snapshot when it was created with one of those versions.
Versions of WiredTiger prior to 10.0.0 never saved a checkpoint snapshot. Additionally, the turtle
file doesn't always exist (for example, backup doesn't include the turtle file), so there isn't always
a WiredTiger version is available. If there is no version available, assume that the snapshot is valid,
otherwise restoring from a backup won't work.
Co-authored-by: Alexander Gorrod <alexander.gorrod@mongodb.com>
(cherry picked from commit 172d0033bd8608828bcb79cf935e458493c9aba1)
(cherry picked from commit …

WT-8534 Allow retrieving the checkpoint snapshot for backup restore recovery (4.4 backport)

---

test/cppsuite/test_harness/timestamp_manager.cxx
test/cppsuite/tests/search_near_01.cxx
test/cppsuite/tests/search_near_03.cxx
test/evergreen.yml

Split cppsuite search near tests into 3 separate tasks on evergreen and
update their logging levels.

WT-8481 Split cppsuite search near tests

---

src/block_cache/block_cache.c
test/format/wts.c

Incrementing the block-item reference count is a read-modify-write, so can race with another thread decrementing the reference count without holding the hash bucket lock.

WT-8568 fix reference count race in block cache

---

test/evergreen.yml

(cherry picked from commit e57066854acb98f999ed78c7a69c2e999b8268b5)

WT-8477 Enforce the use of Pymongo 3.12.2 in our Evergreen tests (v5.0 backport). (#7254)

---

test/csuite/incr_backup/main.c
test/csuite/random_abort/main.c
test/csuite/random_directio/main.c
test/csuite/schema_abort/main.c
test/csuite/tiered_abort/main.c
test/csuite/timestamp_abort/main.c
test/csuite/truncated_log/main.c
test/csuite/wt4333_handle_locks/main.c
test/csuite/wt6185_modify_ts/main.c
test/csuite/wt6616_checkpoint_oldest_ts/main.c
test/csuite/wt8246_compact_rts_data_correctness/main.c
test/utility/misc.c
test/utility/test_util.h

`spinlock-pthread-adaptive-test` is failing in Evergreen due to a lack of available space on the host machines (ubuntu2004-small is capped at 50GB space) due to a large amount of artifacts left over from executing all csuite tests as part of the `make check` step.
To resolve this the artifacts and workspaces are now cleaned up on test success. If we want to retain these artifacts is can be done by passing the `-p` preserve flag.

WT-8426 Clean up csuite test artifacts on test success

---

test/evergreen.yml

This is intended to help with debugging WT-8198, which is tricky to repro locally but happens reasonably often in Evergreen. Unfortunately it isn't leaving cores behind right now, making debugging hard.

WT-8593 Let UBSAN hosts abort and dump core instead of simply exiting

---

test/evergreen.yml

(cherry picked from commit e57066854acb98f999ed78c7a69c2e999b8268b5)

WT-8477 Enforce the use of Pymongo 3.12.2 in our Evergreen tests. (#7254)

---

dist/s_version

Moved the generation of the package.spec to the autoconf generation
function in s_version. This logic is not needed for the CMake
build system.

WT-8602 Moved s_version package.spec to autoconf

---

test/evergreen.yml

Set project-level `exec_timeout_secs` in evergreen.yml to address the below warning captured by the "evergreen validate" command. 
```
WARNING: project '' does not have an exec_timeout_secs defined on one or more tasks; these tasks will default to a timeout of 6 hours
test/evergreen.yml is valid with warnings
```

WT-8606 Set project-level exec_timeout_secs in evergreen.yml

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable31.py

If no stable timestamp is set, don't RTS the history store.
(This matches the behavior with the data store.)
Add a test that runs RTS with no stable timestamp set.

WT-8600 Make recovery with no stable timestamp not drop history

---

src/txn/txn.c
test/suite/test_prepare18.py

Return an error if there's an attempt to prepare a logged object rather than asserting.

WT-8609 prepared operations on logged tables assert

---

src/session/session_compact.c

@raviprakashgiri29 I noticed this when I was doing other timing stress related work. Is there any reason why the compact timing stress needs its own function instead of using the system function? At a minimum I think we want this change.
However, I also could not find any test code, anywhere, that uses this. Is there any use of this? If not, can it be removed instead? I do not see any follow-on tickets for tests to use it. I can see why it was thought at the beginning of the compact project that it might be useful, but if it turned out not to be, can we just remove it?

WT-8611 Use system timing stress function for compact.

---

src/include/extern.h
src/session/session_api.c
src/txn/txn.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable19.py
test/suite/test_rollback_to_stable30.py

@kommiharibabu, for your consideration.
* I rewrote the active test in `__wt_txn_user_active()` to check `F_ISSET(session_in_list->txn, WT_TXN_RUNNING)`, and I'm suspicious that's wrong because otherwise it would have been written that way from the start. I can't find any reason that won't work, but I wanted to call it out. If that's wrong, would it be OK to add `F_ISSET(session_in_list->txn, WT_TXN_PREPARE)` to the existing test? I couldn't find anything in the shared structure that indicates a transaction is in the prepared state, but maybe I just missed it.
* I also couldn't find any RTS tests that checked that RTS fails if there are active transactions, so I re-purposed David's test to do that, plus confirm that after RTS fails the transaction can be resolved.

WT-8543 Rollback-to-stable doesn't fail if there are active prepared transactions

---

src/include/txn_inline.h

If a caller without a snapshot is checking visibility, and further tests require a snapshot, assume the test is for global visibility.

WT-8617 Temporary fix for transaction snapshot assert.

---

test/evergreen.yml

When compiling WiredTiger in the Evergreen little-endian variant,
the build is configured with the v3 mongodbtoolchain. We
subsequently need to ensure the PATH is set to point to the mongodb
toolchain when running make. Otherwise build scripts invoked
during the compiliation process i.e. workgen's 'setup.py', will
be called with a mis-matched toolchain.
(cherry picked from commit 8b101406dae486678313d3189f971dc4beaa68d4)

WT-8424 Use consistent toolchain in little-endian (#7216)

---

test/evergreen.yml

When compiling WiredTiger in the Evergreen little-endian variant,
the build is configured with the v3 mongodbtoolchain. We
subsequently need to ensure the PATH is set to point to the mongodb
toolchain when running make. Otherwise build scripts invoked
during the compiliation process i.e. workgen's 'setup.py', will
be called with a mis-matched toolchain.
(cherry picked from commit 8b101406dae486678313d3189f971dc4beaa68d4)
Co-authored-by: Alison Felizzi <76922497+alisonfel@users.noreply.github.com>
(cherry picked from commit 7f5f23a3b3f51f58e4cd68dfa2b8faea03fd229b)

WT-8424 Use consistent toolchain in little-endian (#7216) (#7376)

---

bench/workgen/workgen.cxx
dist/s_string
dist/s_string.ok
test/cppsuite/test_harness/workload/workload_tracking.cxx
test/cppsuite/tests/example_test.cxx
test/cppsuite/tests/search_near_01.cxx
test/cppsuite/tests/search_near_02.cxx

Extend s_string utility to check .cxx files. The utility has then been run and the appropriate spelling mistakes were fixed.

WT-7147 Extend s_string utility to .cxx files

---

test/utility/misc.c

When using ASAN, we generate LeakSanitizer errors if passing a build directory option (-b) to the csuite test framework library.
This particular option allocates memory to hold the build directory path string but doesn't free the memory on exit/cleanup. To avoid a memory leak, we want to free the memory backing the build directory argument on `testutil_cleanup`.

WT-8637 Fix Mem Leak error for csuite build directory option

---

src/history/hs_rec.c
src/include/api.h
test/suite/test_hs29.py

In some scenarios, it is possible to open up to three hs cursors, see WT-8550 for more details and the new [Python script](https://github.com/wiredtiger/wiredtiger/pull/7362/files#diff-90038e6aefdcbf60dc857d7eb67c1cc0052e66ff763211868e4b4dfa8acfe87f) included in this PR.

WT-8550 Bump the maximum number of opened hs cursors to 3

---

test/csuite/wt8246_compact_rts_data_correctness/main.c
test/utility/misc.c

Do not make a copy of the working database in wt8246_compact_rts_data_correctness because it's not used anywhere and not deleted after the test is finished.

WT-8437 Fix "No space left on device" issue

---

src/btree/bt_walk.c

Check if the caller wants to skip the page regardless of the outcome of previous "skip this page tests". If the caller wants to skip a class of pages (for example, compaction wants to skip all leaf pages), we have to check in the caller's skip function regardless of other tests.
@kommiharibabu, @sulabhM, I'm asking you for review because I think the danger in this one is that some other user of the custom tree-walk skip functionality isn't prepared for the skip function to be called after an earlier test in the tree-walk code has already tested some page information. I don't see a problem, but I think there's danger there. The interesting cases are cursor.next/prev, sync and RTS, and I believe you two are likely to be the best reviewers of changes in those areas. -- Thank you!

WT-8616 Btree walk functions can ignore the caller's "skip function"

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
test/suite/test_hs26.py
test/suite/test_hs27.py

Extend hs26 to the case when its initial values are globally stable.
Add comments in cursor next/prev to note a critical point about why this works.
While here, tidy up a couple leftovers in the test code.

WT-8635 Extend VLCS RLE caching test to another set of cases

---

src/checksum/arm64/crc32-arm64.c
src/checksum/x86/crc32-x86.c
src/checksum/zseries/crc32-s390x.c
src/include/wiredtiger.in

Cache the result of the wiredtiger_crc32c_func() return value, the server is calling it on every CRC32 operation.

WT-7236 wiredtiger_crc32c_func() should cache result

---

src/conn/conn_api.c
test/suite/test_config10.py
test/suite/test_txn19.py

- If the `WiredTiger` file is missing during a normal startup, WiredTiger will write an error message and fail.
- If the `WiredTiger` file is empty during a normal startup, WiredTiger will write an error message.
- If the `WiredTiger` file is missing or empty, but "salvage" is on, it will create and populate the file with the current version string.

WT-7922 Handle missing or empty WiredTiger version file

---

src/os_common/os_fstream.c

This is to fix the immediate issue identified by Coverity. None of the other uses of this function were identified as problematic. It would be possible to add this check to all of them, but not all callers have a `session` available for `WT_ASSERT`, and it would be a lot of noise to fix this in lots of places that my have other guarantees the arguments are valid.
It would also be possible to add this check to `__wt_vsnprintf_len_set`, but again it doesn't have a `session` pointer, and there really shouldn't be a need to change the signature to provide one.

WT-8636: add check for zero snprintf buffer size when buffer is NULL

---

test/csuite/incr_backup/main.c
test/format/backup.c
test/format/import.c
test/utility/test_util.h

Don't use documentation macros in test code, specifically update test code with failed system calls to report errno.

WT-8642 Update test code with failed system calls to report errno

---

src/txn/txn_ckpt.c

Eviction is allowed during the shutdown checkpoint, so performing
checkpoint scrubbing can improve the shutdown checkpoint performance.

WT-8651 Allow checkpoint scrubbing during shutdown

---

src/include/reconcile.h
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c

Remove __rec_update_stable(), it's no longer used.

WT-5316 Investigate the feasibility to remove __rec_update_stable check in __wt_rec_upd_select

---

test/evergreen.yml

Minor patch forward fixing some small settings missed after the WT-8020 refactor.
- Renamed 'OS X 10.14 CMake' to 'OS X 10.14'
- Restore exotic variants batch time
- Restore PPC variant 'format_test_setting' setting

WT-8672 Restore missing evergreen.yml settings

---

test/format/format.i
test/format/ops.c

Periodically we're flagging a failure in a prepared transaction, and as far as we can tell, it's not real, it's just that prepared transactions are staying around without resolution for too long (the last one was a measured 70 seconds). Stop sleeping after prepared transactions and increase the amount of time we'll wait for prepare-conflict resolution from 1 to 2 minutes.
@ddanderson, would you please do the review? You put this code in originally, and I want to make sure there's no history here where it's a bad idea for correctness testing to let prepared transactions proceed at a faster rate. If you feel strongly that is the case, I can revisit this change: the alternative I was considering was to sleep in tiny increments instead of for seconds at a time, that way we could ensure that …

WT-7662 Format timed out with prepare-conflict

---

dist/test_data.py
src/config/test_config.c
test/cppsuite/configs/base_test_default.txt
test/cppsuite/configs/base_test_insert_heavy.txt
test/cppsuite/configs/base_test_stress.txt
test/cppsuite/configs/burst_inserts_stress.txt
test/cppsuite/configs/hs_cleanup_default.txt
test/cppsuite/configs/hs_cleanup_stress.txt
test/cppsuite/test_harness/core/configuration.cxx
test/cppsuite/test_harness/core/configuration.h
test/cppsuite/test_harness/runtime_monitor.cxx
test/cppsuite/test_harness/runtime_monitor.h
test/cppsuite/test_harness/util/api_const.cxx
test/cppsuite/test_harness/util/api_const.h
test/evergreen.yml

This commits reworks the way the statistics are defined in a configuration file from the cpp suite. It also reworks how statistics are defined and handled within the runtime component.
Sorry, this PR is quite big, to review it, I suggest the following:
- Review the runtime_monitor.h file and get familiar with the different classes:
- The base class is `statistics` and there are two derived classes, `cache_limit_statistic` and `db_size_statistic`. The previous class `postrun_statistic_check` has been removed as it is no longer used.
- A statistic is now made of a field, min/max values, a name, and two fields that indicate whether it should be checked at runtime or post-run.
- Then move on to the runtime_monitor.cxx file to check the definitions of the different methods:
- The base class …

WT-8664 Rework the monitoring component and statistics in the cpp suite

---

src/include/reconcile.h
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c

Remove WT_RECONCILE.min_skipped_ts, it's no longer used anywhere.

WT-6052 Investigate remove min_skipped_ts from WT_RECONCILE

---

test/suite/test_timestamp09.py

Fix a typo in the test.
Thanks for spotting this one, @jeremythorp.

WT-8249 Correct the order of operations in test_timestamp09.py

---

test/format/hs.c

Don't use WT_CURSOR.search-near on the history store, the semantics aren't defined for random cursors. Instead, do next/prev periodically, from the start/end of the file.

WT-7551 Format's history store thread violates history store cursor assumptions

---

dist/api_err.py
src/docs/error-handling.dox
src/include/wiredtiger.in
test/format/ops.c
test/suite/test_truncate08.py

@kommiharibabu, I made the change you suggested, but I also updated `format`, it anticipated `WT_PREPARE_CONFLICT` being returned from write operations. It will now assert in that case, which should give us better test coverage of error handling in the library.

WT-4907 WT_PREPARE_CONFLICT error description is wrong

---

test/checkpoint/smoke.sh
test/csuite/wt2246_col_append/main.c
test/csuite/wt2323_join_visibility/main.c
test/csuite/wt2535_insert_race/main.c
test/csuite/wt2853_perf/main.c
test/csuite/wt4333_handle_locks/main.c
test/evergreen.yml

Remove TESTUTIL_BYPASS_VALGRIND and TESTUTIL_SLOW_MACHINE flags, they're no longer useful.

WT-7722 Clean up TESTUTIL_BYPASS_VALGRIND and TESTUTIL_SLOW_MACHINE flags

---

test/evergreen.yml

This ticket is part of [WT-8498](https://jira.mongodb.org/browse/WT-8498) and initially reviewed in #7297. 
This new PR merges the same change into `develop`.

WT-8522 Don't report error in Evergreen when there are no Hang Analyer artifacts to upload

---

test/evergreen.yml

This ticket is part of WT-8498, the initial PR is #7285, this PR aims at merging the same changes to the develop branch. The task is no longer used at all since #7317, see the diff [here](https://github.com/wiredtiger/wiredtiger/pull/7317/files#diff-42f20e21217bd7d4b14489056e1ea24ea2b87599c85413d49182a3b0b721c132L4327).
The second commit is from #7296.

WT-8515 Remove unused code in evergreen.yml

---

dist/api_data.py
src/docs/tune-system-buffer-cache.dox
src/include/wiredtiger.in
src/schema/schema_create.c
test/suite/test_bug028.py

Silently increase allocation and page sizes to be at least as large as any configured buffer alignment.
Add a smoke test for direct I/O and buffer alignment.
Refresh  the documentation for direct I/O.

WT-4416 buffer_alignment setting does not work

---

src/evict/evict_page.c

Earlier eviction was not allowed to operate with transaction
snapshot when the checkpoint is running in parallel as the eviction
operating with transaction snapshot can lead to inconsistent
on-disk checkpoint information. RTS has the support of fixing
the inconsistent checkpoint with the recovered checkpoint snapshot.
Allowing eviction to operate with snapshot improves the cache usage.

WT-6707 Allow eviction to operate with snapshot when checkpoint is running

---

test/evergreen.yml

PPC & zSeries test hosts are not performant as their x86 equivalents, which could cause OOM-kill failures for some format tests if setting the number of concurrent jobs to the number of vCPU. The solution is to halve the number of concurrent jobs for PPC & zSeries builders in Evergreen.

WT-8382 Halve the number of concurrent jobs when running PPC & zSeries tests

---

src/include/txn_inline.h
src/txn/txn.c

In rare scenarios where the oldest ID can be greater than the recovered
checkpoint snapshot. Do not let the oldest ID to go beyond the recovered
checkpoint snapshot to avoid wrong global visibilty until recovery is
finished.

WT-8702 Limit oldest id to recovered checkpoint snapshot in recovery

---

src/session/session_api.c
src/session/session_compact.c
test/format/bulk.c
test/format/compact.c
test/format/hs.c
test/format/ops.c
test/format/snap.c
test/suite/test_prepare13.py
test/suite/test_truncate07.py

WT_SESSION.truncate and WT_SESSION.compact should map WT_PREPARE_CONFLICT to WT_ROLLBACK.

WT-8686 WT_SESSION.truncate doesn't map WT_PREPARE_CONFLICT to WT_ROLLBACK

---

cmake/configs/modes.cmake
cmake/configs/x86/windows/config.cmake
cmake/strict/strict_flags_helpers.cmake

When using newer versions of CMake & VS MSBuild, we get a significant number of warnings at both the CMake configuration stages and during an `MSBuild` compilation. The PR intends to tidy these warnings up, the key changes being:
- Added `CMAKE_MODULE_LINKER_FLAGS` to build modes: This being a missing flag variable that is appended to a given CMake build mode. Newer versions of CMake will flag a warning about the missing variable, this change addresses the warning.
- Defined `None` build mode: The `None` build mode is the default CMake build mode, where no additional compiler flags are appended. We want to explicitly define it as newer versions of CMake will display warning messages about the None build mode not existing in the CMake cache. This change shouldn't have an effect on the …

WT-8704 Tidy up CMake warnings on Windows builds

---

test/cppsuite/tests/search_near_03.cxx

Verified this locally and with a patch build.

WT-8619 Replace nullptr with empty string when key lacks prefix

---

test/evergreen.yml
test/wt_hang_analyzer/wt_hang_analyzer.py

Fixes a syntax error when opening the `coredump_filter` in the `wt_hang_analyzer.py` script on Windows platforms. This was occurring since Windows was defaulting to Python2.7 when running the hang analyzer, whilst Python f-String's are only available in Python 3.6+. This PR adds the following small changes to address the issue:
* Explicitly configure the Windows Evergreen variant to use the Python3.9 executable
* Updated the `coredump_filter` access to use the old-school Python string formatting method. 
Though the Windows Evergreen change should strictly fix this issue, the later change in the `wt_hang_analyzer.py` was intended to make the script compatible across all Python3 versions (it also seems to work in Python2, not that its a requirement).

WT-8666 Fix syntax error opening 'coredump_filter' in wt_hang_analyzer.py

---

test/evergreen.yml

Reduce the running frequency of perf Evergreen tasks to once per day (They used to run for every commit) to save build resources.

Run performance tests once per day in Evergreen

---

test/checkpoint/workers.c

I have not been able to reproduce this failure since WT-8570 was committed, but it's always been difficult to reproduce. Turn testing back on and wait for fallout.

WT-8586 Data validation stress tests fail when logging is enabled

---

test/cppsuite/configs/hs_cleanup_stress.txt

`hs_cleanup_stress` is consistently failing in Evergreen due to performance stats not being within the expected ranges provided by `hs_cleanup_stress.txt`. We'll need a second ticket to investigate the performance regression where WiredTiger has dropped below `min`, but this ticket stops the test failing on every commit which is a ci-blocker.
Instead of failing when stats drop below `min` (or exceed `max` which we shouldn't do) just report these stats to the Atlas performance cluster. We can check for regressions using Atlas charts instead.

WT-8450 Report stats in hs_cleanup_stress, don't validate them

---

src/cursor/cur_version.c
src/include/packing_inline.h

WT_UNPACK_PUT has a return out of the middle of the macro, __curversion_get_value() can't handle that. The return isn't necessary and should never be exercised, log an error and continue;
Call va_start before any possible jump to the err: label.

WT-8726 Coverity analysis defect 121385: Missing varargs init or cleanup

---

src/include/extern.h
src/include/reconcile_inline.h
src/reconcile/rec_col.c
src/reconcile/rec_row.c
src/reconcile/rec_visibility.c
test/suite/test_checkpoint09.py

Whenever we are rewriting an existing page image with the latest update of keys
on reconciliation, clear out any of the existing time windows from other keys
on the page, if they are obsolete.
Clearing the time window will decrease the size required to store the
same cell and also improves the performance.
(cherry picked from commit b757e1c61d3b2d54300d7b3be5b68f7316140fed)

WT-8422 Clear the on-disk cell time window if it is obsolete (v5.0 Backport)

---

bench/workgen/workgen/__init__.py
dist/s_docs
dist/s_style
lang/python/wiredtiger/init.py
test/suite/suite_subprocess.py
test/suite/test_cursor13.py
test/suite/test_prepare08.py
test/suite/test_search_near04.py
test/suite/test_stat01.py
test/suite/test_timestamp14.py
test/syscall/syscall.py

* Add non-ascii character removal on `.dox`, `.cxx`, `.py`, `.cmake`,  `.i` source files in `s_style`.
* Remove similar check in `s_docs` which prints error at non-ascii characters in `.dox` files.
* Add check for paired typos to `.cxx`, `.py`, `.cmake`,  `.i` source files.
* Fix paired typos in source files.

WT-7195 Remove non-ascii input and paired typos in any source files

---

src/txn/txn.c

Limit the key consistency checks run on MongoDB server builds.
@kommiharibabu, the changes in WT-8691 to add in all of the `key_consistent` checks when the `ordered` keyword was set breaks the MDB server build.
This change only runs those tests in standalone mode.

WT-8748 turn off key-consistent checking for MongoDB builds

---

test/cppsuite/configs/hs_cleanup_default.txt
test/cppsuite/configs/hs_cleanup_stress.txt

Since WT-6707 has fixed the problem in WT-7848, but has a new error in WT-8743. I am using this ticket to re-enable WT-7848 and disabling the cache usage check in hs_cleanup_default for now.

WT-7848 Re-enable cache usage check in hs_cleanup_stress and disable hs_cleanup_default

---

src/cursor/cur_std.c
src/include/api.h
test/suite/test_cursor06.py

Do validation checking on WT_CURSOR.reconfigure arguments.

WT-8248 Check for valid configuration key when using the WT_CURSOR.reconfigure API

---

src/block/block_open.c
src/include/block.h

Fix an error return path that could return without releasing the connection's block-manager lock.  Add an explicit boolean value if the WT_BLOCK structure has been linked into the block list, so we do the right thing during close after an allocation error.

WT-8752 Coverity analysis defect 121408: Missing unlock

---

test/evergreen.yml

Updating the build command used to compile WT with the S3 extension on evergreen to use the new CMake flag and specify the AWS SDK to be downloaded as an external project.

WT-8762 Fix S3 extension not compiling on evergreen.

---

test/suite/test_backup07.py
test/suite/test_backup10.py

From #6291, The ticket involved refactoring all the backup tests to use a class in the means to simplify all the backup tests. This however caused backup07 to lose the flavour for the original of its testing. I have fixed this and still used the refactored portions.

WT-8701 Fix test_backup07.py to test the creation of new tables when backup cursor is open

---

cmake/README.md

The CMake `README` (under `cmake/README`), currently defines `ninja`, `python` and `swig` as hard dependencies. This isn't necessarily true. Python is only required when building the Python API and `ninja` is an optional generator. Updated the `README` to better distinguish between 'hard' and 'soft' dependencies.
The intention here is to make the cmake build more approachable to external users & contributors. Keeping the build to a minimal number of steps to make sure random community building remains easy (without requiring the end user to install multiple packages). 
_**Note** this README is mostly intended for external users_, and won't necessarily match the requirements of a WT developer, where we generally advocate using `ninja`, `python` etc. in the team (our internal wiki/docs …

WT-8768 Distinguish between hard & soft CMake dependencies

---

src/txn/txn_rollback_to_stable.c

Knowing the information of what keys are rolled back as part of
RTS will help in debugging to find out any data mismatch problems.

WT-8772 Print the rolling back key in the verbose logs

---

test/evergreen.yml

Our current standalone evergreen CI setup doesn't include testing on arm64. The MongoDB server supports arm64 hosts and testing for arm64 builds of WT are done indirectly via MongoDB. There may be parts of WT that are not currently exercised by the server regression testing, and it would be better to catch any arm specific issues in WT itself. Since arm64 is becoming increasingly important in the cloud, we should perform testing on arm64 at a scope that is equivalent to our other target architectures.
Patch Build: https://spruce.mongodb.com/version/61fb57660ae60650cae29538/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Let me know if there's any test I should add or remove. Again I mostly tried to define a suite of tests equivalent to our x86_64 testing. Just some notes on the build …

WT-8679 Add support for arm64 Evergreen testing

---

ext/storage_sources/s3_store/s3_connection.cpp
ext/storage_sources/s3_store/s3_storage_source.cpp
test/suite/test_s3_store01.py

- Implemented `WT_STORAGE_SOURCE.ss_flush` for tiered storage as `S3Flush`  using AWS SDK C++ PutObject to flush file to the S3. 
- Implemented `WT_STORAGE_SOURCE.ss_flush` as `S3FlushFinish` to flush the local file to cache.
- Added python testing in to validate the file exists in S3 and the cache, as well as expiring the cached file.  
- Additionally also tested if the file remains in S3 after deleting it from the cache.

WT-8717 Flush files to S3 store and cache them locally to a local directory

---

test/cppsuite/test_harness/workload/workload_tracking.cxx
test/cppsuite/test_harness/workload/workload_tracking.h

The tracking table is in charge of saving all the operations that occur in a test. The same session is used to track schema operations and when we try to sweep obsolete data from the tracking table periodically. If a thread creates a collection and another thread tries to sweep data from the tracking table, the same session ends up being used by two different threads which is not allowed in WT.
In this PR, we define a dedicated session for the sweeping process.

WT-8700 Define a dedicated session for sweeping data in the cpp suite

---

dist/api_data.py
src/docs/checkpoint.dox
src/include/wiredtiger.in
src/session/session_api.c

Add a warning about checkpointing a target set of objects.
Reorder the WT_SESSION transaction methods, right now the list is completely unordered.
@quchenhao, @kommiharibabu, let me know if you disagree with this decision.
There's a prebuilt version of the docs for your review. The important changes are:
[WT_SESSION transaction method restructuring](https://keithbostic.github.io/docs.build/struct_w_t___s_e_s_s_i_o_n.html)
[The Ref Guide warning for the 'target' configuration](https://keithbostic.github.io/docs.build/struct_w_t___s_e_s_s_i_o_n.html#a6550c9079198955c5071583941c85bbf)
[The User Guide warning](https://keithbostic.github.io/docs.build/checkpoint.html#checkpoint_target)
I had to restructure session initialization in `session_api.c`, but that was a mechanical change.

WT-7509 Document dangers around checkpointing a targeted list of objects

---

src/btree/bt_sync.c

The hazard variable is no longer being used for anything.

WT-8816 Coverity analysis defect 121526: Redundant test

---

test/cppsuite/configs/hs_cleanup_default.txt
test/cppsuite/configs/hs_cleanup_stress.txt

This pull request aims to increase the stress test for hs_cleanup because it is generating lots of uncommitted updates for the cache, ideally we want to just test the history store. I have chosen 2 GB instead of 200MB because there are 10 updates threads with 100K value updates, and we have possibly 20 uncommited transactions. This means there is possibly 20 MB circling around inside the cache. That would constantly generate around 10% of uncommitted updates. 1% sounds like a more realistic expectation as it is not the goal of stressing the cache but the history store. 
I have also lowered the operations per transactions for the default test.

WT-8743 Configure hs_cleanup configuration to stress the cache less

---

src/txn/txn_timestamp.c
test/suite/test_prepare01.py

@bvpvamsikrishna, @kommiharibabu: I'm torn about this one. Trying to set the read timestamp after a transaction is prepared is technically an error on the transaction after it's prepared -- but the error also seems like an easy one for an application to make and not discover until after deployment.
There is a typo in `__wt_txn_set_timestamp()` that this PR also fixes, so if you decide to not allow a read timestamp after prepare, that's fine, with me and I'll remove that part of the change and keep the rest.

WT-8776 Setting a read timestamp after prepare panics

---

test/format/config.c

Direct I/O can be so slow the additional I/O for overflow items can
cause eviction to stall.

WT-8759 Keep the number of rows and keys/values small for direct I/O runs in test/format

---

ext/storage_sources/s3_store/s3_connection.cpp
ext/storage_sources/s3_store/s3_connection.h
ext/storage_sources/s3_store/s3_storage_source.cpp
ext/storage_sources/s3_store/test/test_s3_connection.cpp
test/suite/test_s3_store01.py

- Created a function `ObjectSize` that gets the `ContentLength` of the object in bucket in `S3Connection.cpp`.
- Implemented `fh_size` that gets the file size from WiredTiger's native file handle.
- Implemented `fs_size` that uses the `ObjectSize` function `S3Connection.cpp` to get the object size. 
- Added testing for the functions that can be merged into `test_tiered06.py` and others.

WT-8821 Add a get object size method in S3Connection and implement file handle and file system size

---

src/docs/tune-page-size-and-comp.dox

Update the documentation for tuning page size parameters to reflect the changes to `split_pct` from
WT-2439. That parameter currently has a range of 50-100% with a default of 90%.

WT-8831 Correct tuning documentation for split_pct parameter

---

ext/storage_sources/s3_store/CMakeLists.txt
ext/storage_sources/s3_store/s3_storage_source.cpp
test/evergreen.yml

Add a new task to do the following:
* Compiling the WiredTiger and the S3 extension on the platform
* Running the unit tests for the S3 extension's C++ class(es)
* Running the python tests for S3

WT-8837 Add S3 testing to Linux builders in WiredTiger

---

cmake/toolchains/mongodbtoolchain_v4_clang.cmake
cmake/toolchains/mongodbtoolchain_v4_gcc.cmake
test/evergreen.yml

Update the following PPC ASAN tests to use the base tests and adopt the V4 toolchain in the base tests:
* Replace `format-stress-sanitizer-ppc-test` with `format-stress-sanitizer-test`.
* Replace `format-asan-smoke-ppc-test` with `format-asan-smoke-test`.
Evergreen patch build: https://spruce.mongodb.com/version/620a203632f4171a210cf4a1/tasks

WT-8482 Use toolchain clang binary for PPC ASAN tests

---

src/reconcile/rec_write.c

Cherry-picked from c457fb3, which is the 4.2 backport of 405b72f. 
v4.2 backport PR: #7051 
Initial PR: #6926
This cherry-pick applied cleanly after the modifications made in the 4.2 backport.
Co-authored-by: Michael Cahill <michael.cahill@mongodb.com>
Co-authored-by: Monica Ng <mailto:monica.ng@mongodb.com>
(cherry picked from commit c457fb3eee12986e206a09bbc04e8daf4fa892b3)

 WT-7984 Fix a bug that could cause a checkpoint to omit a page of data (v4.0 backport) (#7051)

---

ext/storage_sources/s3_store/s3_connection.cpp
test/suite/test_s3_store01.py

Directory listing was changed in `S3Connection.cpp` so when returning the output files, the filenames do not include the prefix. 
* Testing was adjusted for this change.

WT-8846 Fix S3 directory listing - strip prefix from the output files

---

test/evergreen.yml

Use the Evergreen build variant field `activate` (refer to [this](https://github.com/evergreen-ci/evergreen/wiki/Project-Configuration-Files#build-variants) wiki page) to disable perf tests for the `mongodb-5.0` branch, as we only expect perf tests to be executed on the Evergreen project "WiredTiger (develop)".

WT-8605 Disable the perf tests for mongodb-5.0 branch in Evergreen

---

test/evergreen.yml

Use the Evergreen build variant field activate (refer to [this](https://github.com/evergreen-ci/evergreen/wiki/Project-Configuration-Files#build-variants)[](https://github.com/lukech) wiki page) to disable perf tests for the mongodb-4.4 branch, as we only expect perf tests to be executed on the Evergreen project "WiredTiger (develop)".

WT-8605 Disable the perf tests for mongodb-4.4 branch in Evergreen

---

test/evergreen.yml

As discussed in [WT-8865](https://jira.mongodb.org/browse/WT-8865), there's limited value of keeping performance tests running for LSM configurations, before the support for LSM is restored in WiredTiger code base. 
This PR is to disable the LSM performance tests in Evergreen. 
WT-8867 will be used to re-enable the same set of sets later once LSM support is restored.

WT-8866 Disable LSM performance tests in Evergreen

---

test/checkpoint/checkpointer.c
test/checkpoint/test_checkpoint.h
test/checkpoint/workers.c

There's a race in test/checkpoint, we update `g.ts_stable` and then set the stable timestamp, while holding `g.clock_lock`, but read `g.ts_stable` without holding a lock, and if we read it between the update and the set, we can try and set the oldest timestamp after the stable timestamp.
The obvious change is to acquire the lock before reading `g.ts_stable`, and that's what I did. I don't think this will adversely affect how `test/checkpoint` works, but I'm not really familiar with it. The change was part of "WT-5605 Updating test checkpoint to no longer use checkpoint cursors and improve usage of timestamps": @luke-pearson authored that test, but he's not around at the moment, @sueloverso, it looks like you were involved at the time.

WT-8708 Fix timestamp usage error in test/checkpoint

---

dist/test_data.py
src/config/test_config.c
test/cppsuite/configs/search_near_01_default.txt
test/cppsuite/configs/search_near_01_stress.txt
test/cppsuite/tests/search_near_01.cxx

This ticket involves restructing the method we do assert testing in search_near_01 cppsuite test. The restructuring of the test includes creating group inserts, and waiting on all the threads before we check the WT statistics in our testing phase.
(cherry picked from commit b28c35937fbaa1efb6f6a89646883e2d575c1d6e)

WT-8417 Restructure assert testing in search near 01 cpp for concurrency (v5.0 backport) #7219

---

dist/api_data.py
src/config/config_def.c
src/include/wiredtiger.in

Put key_consistent back into the write_timestamp_usage choice table for backward compatibility.

WT-8777 Fix compatibility test issue about invalid key_consistent argument

---

src/include/reconcile_inline.h
src/include/timestamp_inline.h

Earlier logic clears the on-disk cell start time window even if
it is empty if that cell contains a stop time window which is
unnecessary extra work for no benefit. Clear the on-disk cell
start time window only if it exists.

WT-8560 Clear the obsolete on-disk cell start time window if it exists

---

test/evergreen.yml

(cherry picked from commit 72c1b33f3b54d4c07091f8ede1513f0d66b49f08)

WT-8874 Disable compatibility tests on mongodb-5.0 (v4.4 backport) (#7593)

---

src/docs/arch-timestamp.dox
src/docs/timestamp-prepare.dox
test/suite/test_durable_rollback_to_stable.py
test/suite/test_durable_ts01.py
test/suite/test_durable_ts03.py
test/suite/test_flcs02.py
test/suite/test_hs06.py
test/suite/test_rollback_to_stable01.py
test/suite/test_rollback_to_stable02.py
test/suite/test_rollback_to_stable03.py
test/suite/test_rollback_to_stable04.py
test/suite/test_rollback_to_stable06.py
test/suite/test_rollback_to_stable07.py
test/suite/test_rollback_to_stable08.py
test/suite/test_rollback_to_stable10.py
test/suite/test_rollback_to_stable11.py
test/suite/test_rollback_to_stable12.py
test/suite/test_rollback_to_stable13.py
test/suite/test_rollback_to_stable14.py
test/suite/test_rollback_to_stable18.py
test/suite/test_rollback_to_stable23.py

Document the problem and, for now at least, don't attempt to enforce a solution.
Also adjust a bunch of tests to not read in that window unless they really meant to.

WT-8747 Reading between commit_timestamp and durable_timestamp can produce inconsistency

---

src/btree/bt_sync.c

Replaced a NULL check with a WT_ASSERT and direct assignment to avoid the possibility of ref->page dereferencing a null pointer.

WT-8814 Coverity analysis defect 121527: Dereference after null check

---

test/evergreen.yml

* Disabling documentation-update for mongodb-5.0
* Fixed typo
(cherry picked from commit f297c94aec8141221ee7d11379f5941fc76662c2)

WT-8799 Disable Documentation Update on mongodb-5.0 (v4.4 backport) (#7599)

---

src/meta/meta_ckpt.c

When called from the wt utility, there's no checkpoint list cached, and further, there's no tree handle.

WT-8893 wt list -c command drops core

---

test/suite/test_tiered04.py

When testing the "timeout=" config option for flush_tier() us a large enough timeout that a slow system doesn't take so long that it hits the timeout generating an unexpected EBUSY error.
(cherry picked from commit 8f6a0a2e0de9e89041479af9e899df4dd93da5d7)

WT-7954 Use longer flush_tier timeout in test_tiered04 (#7607)

---

dist/api_data.py
src/docs/timestamp-txn.dox
src/include/wiredtiger.in
src/txn/txn_timestamp.c
test/suite/test_hs02.py
test/suite/test_hs06.py
test/suite/test_hs07.py
test/suite/test_hs19.py
test/suite/test_hs22.py
test/suite/test_hs24.py
test/suite/test_hs27.py
test/suite/test_hs_evict_race01.py
test/suite/test_prepare_hs01.py
test/suite/test_prepare_hs04.py
test/suite/test_rollback_to_stable24.py
test/suite/test_rollback_to_stable25.py
test/suite/test_tiered11.py
test/suite/test_timestamp09.py
test/suite/test_timestamp22.py

@kommiharibabu, @sauclovian-wt, would you please do the review? I tried to be careful in the test suite to be sure my changes didn't alter the intent of the test, but obviously that's the most interesting question for the test suite.

WT-7712 commit and durable timestamps should be disallowed at stable timestamp

---

test/evergreen.yml

The problem was caused by the test creating and then attempting to copy a large (26Gb) database file on a machine with only 50Gb of disk. Renaming the file (using mv) solves the issue, while also keeping the database available.
I have deliberately left the disk space diagnostics I added in place to make it easier/faster to debug issues in the future.

WT-8882 Fix bug showing as no space left on device for wtperf test

---

src/btree/bt_handle.c

Reverting WT-8601 breaks some configurations; restore a small part of that change to set the btree handle logging flags.

WT-8906 Restore the change to set the btree handle logging flags

---

test/evergreen.yml

A second -j 4 argument was added to the linux-directio evergreen task as part of [WT-5458](https://jira.mongodb.org/browse/WT-5458) to increase the number of resources for the test however a patch build shows the default -j (number of processors) to be sufficient.
Evergreen patch build: https://spruce.mongodb.com/version/622028719ccd4e75c3b4b5ee/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

WT-8802 Removed duplicate -j argument in linux-directio evergreen task

---

src/evict/evict_lru.c

- Changed the cache debug messages to facilitate outputs for smaller page sizes.

WT-8870 Making cache debug info output with smaller page sizes

---

src/btree/bt_walk.c

Revert the change in WT-8591 that checks WT_REF.state == WT_REF_DELETED before checking for truncation skips.

WT-8770 32% performance regression misc_workloads/insert_vector_*/thread_level 16/ops_per_sec

---

test/checkpoint/checkpointer.c
test/checkpoint/test_checkpoint.c
test/checkpoint/test_checkpoint.h

Remove two unused failpoint definitions in test checkpoint.
Fix an obvious typo.

WT-8889 Remove unused failpoint definition in test checkpoint

---

src/docs/timestamp-global.dox

@kommiharibabu, @sauclovian-wt, please let me know if I've misunderstood what we need to do here or if I've missed anything.
There's an already built page with this change at https://keithbostic.github.io/docs.build/timestamp_global_api.html.

WT-6667 Document checkpoint's oldest timestamp behavior

---

dist/s_string

There's a few things going on with GNU vs. BSD sed. The order of the arguments matters a bit more (need to have the filename last), the `+` operator is only supported with extended regexes (`-E`) but that breaks other stuff so just use a `{0,}` range operator. I also added the `global` flag to catch cases where there are multiple constants on the one line.

WT-8930 Make s_string hex number search compatible with MacOS

---

src/evict/evict_lru.c

The cache is dumped by the eviction server which doesn't have a snapshot, set the WT_READ_VISIBLE_ALL flag, the tree walk routines require one or the other.

WT-8923 Cache stuck leads to failed assert in __tree_walk_internal

---

src/session/session_api.c
src/txn/txn.c

Restructure txn commit so that if it fails, we reset the cursors and discard their positions.

WT-8935 Failed transaction commit doesn't reset cursors.

---

test/suite/test_compact01.py
test/suite/test_compact02.py

Since overflow reads are synchronous, it might be slow to process all of them and eviction can take too long. To avoid this situation, we decided to increase the page size so we have fewer chances to deal with overflow items. The intent of the test has never been to work with overflow items.
With the new changes, I checked and no overflow items are created.
**Note: I have enabled the tests on macOS in the PR testing.**

WT-7187 Re-enable compact tests for macOS

---

src/reconcile/rec_col.c
test/suite/test_stat10.py

During reconciliation, drop values whose stop times are globally visible. Also fix a related but not quite the same bug in FLCS that popped up in WT-8569: if the visibility code hands back a tombstone, that tombstone is meant to be globally visible; don't also record the stop time from upd_select->tw, and fix test_stat10 accordingly.

WT-8780 In VLCS and FLCS, on-disk values with globally visible stop times are never cleared out

---

src/reconcile/rec_col.c
test/suite/test_stat10.py

Reverts wiredtiger/wiredtiger#7678

Revert "WT-8780 In VLCS and FLCS, on-disk values with globally visible stop times are never cleared out"

---

test/csuite/wt7989_compact_checkpoint/main.c

The wt7989-compact-checkpoint-test failed as a result of synchronizing the checkpoint and compaction threads using the conditional variable to signal when the threads are ready. The log showed the compaction thread sending a ready signal before the checkpoint thread waits for it, resulting in the checkpoint thread waiting forever. This PR replaces the signal with a global thread-ready counter as an alternative approach to force the threads to wait until all threads are ready before starting their operations.

WT-8584 Replace wait signal with global thread counter in wt7989-compact-checkpoint-test

---

test/csuite/tiered_abort/main.c
test/utility/misc.c

I have changed the test, such that it doesn't do a chdir() within `run_workload`. This is brcause the extensions for WT_LIB needs to have the proper build directory. WT-7598 also now enforces test to run with a -b option as well. To run the test currently requires the absolute directory e.g.
```./test/csuite/tiered_abort/test_tiered_abort -b /data/wiredtiger/build```
This ticket aims to be able to give support to also add in relative directory as well e.g. 
```./test/csuite/tiered_abort/test_tiered_abort -b .```

WT-8835 Allow relative directory to be passed into -b option in tiered_abort test

---

bench/workgen/CMakeLists.txt
test/cppsuite/CMakeLists.txt
test/cppsuite/test_harness/core/configuration.cxx
test/evergreen.yml

This PR fixes a bug in the `cppsuite` code that was picked up by the C++17 address sanitizer build. I also updated the `evergreen.yml` to add `CXX_FLAGS=-ggdb` to the `cmake` flags for all build variants running the `cppsuite` tests, so that we can have line number information in the evergreen logs on test failure.

WT-8787 Update C++ compiler standard in builds from C++11 to C++17

---

src/txn/txn_rollback_to_stable.c
test/suite/test_log04.py

Turn on exclusive access to dhandles during RTS.
This should wait on [SERVER-63989](https://jira.mongodb.org/browse/SERVER-63989) to merge, assuming it passes local testing.

WT-8970 Turn on exclusive access to dhandles during RTS

---

test/csuite/CMakeLists.txt
test/csuite/wt8963_insert_stress/main.c
test/evergreen.yml

The motivation for this test is to try and reproduce BF-24385 by stressing insert functionality. The test creates a lot of threads that concurrently insert a lot of records with random keys. Having a large memory page ensures that we have big insert lists. Big cache size allows having more dirty content in the memory before eviction kicks in.

WT-8963 Implement a stress test for insert operation

---

test/suite/test_verbose01.py

Note: This cherry-pick only adds the changes required to fix a bug when
parsing the logs. We need to truncate them when too many are received.
(cherry picked from commit 4f9feab8ca9ead857ef7e0493a92617e889ae0b9)

WT-8260 Truncate the logs in verbose tests (v5.0 backport)

---

src/txn/txn_ckpt.c

Now that SERVER-64026 has committed, make the standalone build behavior of disallowing single object checkpoints the behavior for all builds.

WT-8892 Disallow single file checkpoint from MDB server

---

src/cursor/cur_hs.c
src/txn/txn_rollback_to_stable.c
test/suite/test_backup27.py
test/suite/test_rollback_to_stable05.py

This ticket involves fixing up the history cursor usage when we only set the btree ID as the key. Currently the truncate function doesn't work and I have fixed that as well. Furthermore the history store cursor interface also doesn't appriopately handle the case when there is only btree id set.

WT-8944 Fix history store truncate function on partial restore or non-timestamp tables

---

test/suite/test_durable_rollback_to_stable.py

test_durable_rollback_to_stable.py violates timestamp ordering rules by setting a prepare timestamp in advance of a previous durable timestamp.
@kommiharibabu, I'm fuzzy on the whole prepare/durable timestamp rules, so apologies if this is wrong-headed. -- Thanks!

WT-8980 test_durable_rollback_to_stable.py violates timestamp ordering rules

---

src/docs/timestamp-txn.dox
test/suite/test_alter05.py

An implicit transactions after a timestamped transaction violates timestamp ordering rules.

WT-8979 test_alter05 violates timestamp ordering rules

---

dist/test_data.py
src/config/test_config.c
test/cppsuite/tests/run.cxx
test/cppsuite/tests/search_near_01.cxx
test/evergreen.yml

This test focuses on the prefix_search feature that is not available on
4.4. It has been decided to disable the test.

WT-8909 Disable cpp test search_near_01 on 4.4

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable30.py

Removed the have diagnostic check to always dump active transaction information when rollback to stable fails due to active transactions. Also changed test_rollback_to_stable30 to reflect this change and to always check for the transaction state dump on failure.

WT-8877 Always dump transaction state of active sessions on RTS failure

---

test/csuite/wt2853_perf/main.c

The root cause of `wt2853_perf` failures is still under investigation in WT-8373. This change is to suppress noisy evergreen failures while investigation is underway.

WT-8994 Increase gap error in wt2853_perf

---

src/txn/txn_ckpt.c
test/csuite/incr_backup/main.c
test/csuite/wt2323_join_visibility/main.c
test/csuite/wt3135_search_near_collator/main.c
test/utility/test_util.h

Wrap rename in a checkpoint loop if it returns EBUSY.
Add a message when checkpoint-close is blocked by modified data.
Generalize test suite support for checkpoint/op loops.

WT-8900 incr_backup fails due to EBUSY from rename

---

src/btree/bt_split.c

Once the update restore eviction is finished with restoring
the updates, free all the update written to the data store
and history store including the on-page tombstone.

WT-9004 Free the onpage tombstone after update restore eviction

---

src/meta/meta_turtle.c

This ticket frees up the metadata configuration after we have done a metadata search to fix a resource leak.

WT-8943 Fix metadata configuration string resource leak in meta_turtle.c

---

src/docs/durability-checkpoint.dox
src/txn/txn_ckpt.c

Don't allow "all" to be a checkpoint name. It means something special when dropping checkpoints.

WT-9024 Don't allow "all" as a checkpoint name

---

ext/storage_sources/s3_store/README.md

Created `README.md` file to document building, running and testing S3. 
Stored in `/ext/storage_sources/s3_store`.

WT-8995 Create S3 extension documentation

---

test/format/format.sh

Fix split  stress argument specification ("stress.", not "stress_"), there are currently only 7 stress.split tests.
@lukech, I messed up a change in WT-7936, merged in August 2021, so this has been broken for awhile, and could potentially affect our testing when it's turned back on.

WT-9054 format.sh incorrectly configures split stress options

---

test/suite/helper_tiered.py

Set the primary bucket location to the US to improve the performance of the tests on evergreen.

WT-9002 Move the primary S3 test buckets to us-east region

---

src/txn/txn_timestamp.c

MDB Server no longer sets the commit/durable timestamps equal to the stable timestamp, remove the code that allows that.

WT-8902 MDB server sets the commit/durable timestamps equal to the stable timestamp

---

src/history/hs_rec.c
src/include/api.h
src/include/extern.h
src/include/reconcile.h
src/include/session.h
src/reconcile/rec_col.c
src/reconcile/rec_row.c
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c
src/session/session_api.c
test/suite/test_hs29.py
test/suite/test_hs31.py

These changes include [WT-8362](https://jira.mongodb.org/browse/WT-8362) and additional changes in order to have the function __wt_rec_hs_clear_on_tombstone available as well as [WT-8550](https://jira.mongodb.org/browse/WT-8550) since more hs cursors can be opened at once now.
Note: the FLCS scenario has been disabled as it is not supported in 4.4

WT-8362 Truncate HS when ooo or mm tombstone is written to datastore (v4.4 backport)

---

test/csuite/timestamp_abort/main.c

The check for all_durable moving backwards in txn_commit can fail when multiple transactions commit at the same time since it's possible for the durable timestamp to move backward. timestamp_abort is the only test to use the all_durable timestamp so I've added back the check from WT-7968 to prevent the stable timestamp from moving backward as a result of all_durable.

WT-8072 Check if all_durable is moving backwards with internal testing

---

test/evergreen.yml

We are not saving the whole resulting directory instead of the FTDC only. The logs are generated in this directory.

WT-8860 Save the mongod logs as a test artifact in many-collection-test

---

ext/encryptors/sodium/sodium_encrypt.c

Close libsodium's internal reference to the random device.
Avoids an fd leak that manifests when the extension is loaded and unloaded repeatedly (as happens during testing).

WT-9082 fd leak in libsodium extension

---

src/txn/txn_recover.c
test/evergreen.yml

Summary: In special cases during recovery WiredTiger will use the wrong Write Generation Number for some btrees and retains the `start_txn` and `stop_txn` of updates made before a restart. These outdated txn ids then cause visible updates to be incorrectly treated as invisible by WiredTiger.
In current WT behaviour `last_ckpt_base_write_gen` is not set at the start of recovery, but [this check](https://github.com/wiredtiger/wiredtiger/blob/f74c4db3a8018c7d6af9b55bb90f4b4050746a8d/src/btree/bt_handle.c#L558) uses it to determine the WGN for btrees when opening them. As `last_ckpt_base_write_gen` has a default value of zero the check evaluates to false and the btree will use the largest WGN from the start of recovery instead of the largest WGN at the end of recovery. As a result any changes …

WT-8622 Read in last_ckpt_base_write_gen at start of recovery

---

cmake/third_party/aws_sdk.cmake

There are two solutions to stop the AWS SDK integration tests from running when building the SDK.
- Turn off the services integration tests by setting the CMake flag `ENABLE_TESTING` to off. 
- This means it will not build the SDK with the testing. 
- Build with the integration testing enabled, but skip running them by setting the `AUTORUN_UNIT_TESTS` flag. 
- This flag will get ignored when `ENABLE_TESTING` is turned off. 
I have implemented the first option; with a comment on the CMake file outlining the alternative option should we need it in the future.

WT-8926 Turn off SDK's integration tests when building the SDK

---

dist/api_data.py
src/conn/conn_dhandle.c
src/docs/timestamp-misc.dox
src/docs/timestamp-txn.dox
src/include/dhandle.h
src/include/wiredtiger.in
src/txn/txn.c
test/suite/test_timestamp26.py

Change the MDB timestamp default behavior to "ordered", leaving the WiredTiger standalone build default at "none".
Remove the "always" configuration, it's no longer useful.
The documentation has been updated to match the MDB timestamp behavior, and it is expected the WiredTiger standalone code will follow shortly.

WT-6356 Change WiredTiger MDB timestamp default to "ordered", remove "always".

---

src/include/serial_inline.h

Add a null check to keep Coverity happy.

WT-9018 Coverity: dereference before null check in __wt_update_serial

---

cmake/third_party/memkind.cmake
src/block_cache/block_cache.c
src/include/block_cache.h

See the ticket for a full description. This also fixes `memkind.cmake` to respect either flag.

WT-9112: Fix build on systems not using libmemkind, but with it installed

---

test/evergreen.yml
test/evergreen/print_stack_trace.py

This ticket delves into adding support to dump all the threads when a test/format failure occurs. Furthermore I have added functionality to also upload all the stacktraces into the evergreen UI as well. **Note: For printing our the test format, we only print the aborting thread, and dump all the threads in the backtrace txt file instead.**

WT-8328 Dump and upload backtraces when python and test format fails in evergreen testing

---

ext/storage_sources/s3_store/s3_storage_source.cpp
test/suite/helper_tiered.py
test/suite/test_tiered04.py

- Prefixes that can simulate a directory structure using "/" are now reflected in the cache directory structure itself and directories are made from the prefixes. 
- The linking to the cache directory now succeeds because intermediate directory structures are created. 
- Changes were made to testing structures to include prefixes with "/".

WT-8890 Add bucket prefix to S3 extension cache directory creation

---

ext/storage_sources/s3_store/README.md
test/evergreen.yml

- GDB debugging flag for C++ `CMAKE_CXX_FLAGS="-ggdb"` was added to `evergreen.yml` tiered test builds.
- Documentation was updated to include the flags in build instructions and examples.

WT-9087 Add cmake debugging flag to S3 extension documentation and evergreen testing

---

dist/api_data.py
src/btree/bt_cursor.c
src/conn/conn_dhandle.c
src/docs/timestamp-misc.dox
src/docs/timestamp-txn.dox
src/include/dhandle.h
src/include/extern.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/txn/txn.c
test/suite/test_assert06.py
test/suite/test_timestamp26.py

Change WiredTiger to do commit timestamp checking by default, that is, timestamp usage will always be called at commit.
If timestamp usage is violated, an error message will always be logged.
In DIAGNOSTIC builds, timestamp usage violations will result in an immediate core dump after the error message
In STANDALONE builds, timestamp usage violations will result in transaction rollback (the commit will fail after the error message)
In MDB builds the transaction commit will succeed after the error message
Remove the assert=(write_timestamp) configuration from the documentation and update the User Guide.

WT-8876 Make timestamp usage checking at commit the default

---

test/checkpoint/checkpointer.c
test/checkpoint/test_checkpoint.c
test/checkpoint/workers.c

Flush all prints in test_checkpoint instead of just some.
(actually doesn't flush everything during startup; flushes the last of those before things get going)
This prevents messages to stdout and stderr from getting reordered, which can be quite misleading if one isn't expecting it.

WT-9154 Have test_checkpoint flush all its prints

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c

Explain why we must specify the update chain in VLCS when checking for history store values.

WT-9119 Fixed length and variable length column store check update chain visibility twice

---

test/salvage/salvage.c

Build the salvage data where WT can't see it; this prevents it from getting corrupted if WT looks at it prematurely.

WT-9159 Make test_salvage more robust

---

src/evict/evict_lru.c
src/txn/txn.c
test/suite/test_rollback_to_stable10.py
test/suite/test_rollback_to_stable14.py
test/suite/test_txn27.py

Don't output verbose messages when rolling back transactions.

WT-9007 test_compact02 has unexpected stdout: oldest pinned transaction

---

src/tiered/tiered_handle.c
test/suite/test_tiered04.py

@keitharnoldsmith this ticket is pretty small as the earlier ticket put in all the infrastructure needed. And testing is far easier because it will generally hit anytime we have a restart.

WT-9100 Restart work units to drop locally retained tiered objects.

---

test/cppsuite/test_harness/workload/workload_tracking.h

The tracking table is our source of truth, we need to make sure it is persistent at all times by enabling logging.
No perf impacts have been found after this change.

WT-9062 Enable logging for the tracking table in cpp testing

---

test/cppsuite/test_harness/timestamp_manager.cxx
test/cppsuite/tests/search_near_01.cxx
test/evergreen.yml

* Split cppsuite search near tests into 4 separate tasks on evergreen.
* Update some log message levels from LOG_INFO to LOG_TRACE.
(cherry picked from commit efd9d9adf2af4d68383868c4bd5e156b19bca99b)

WT-8481 Split cppsuite search near tests and update their logging levels (backport 5.0)

---

dist/s_string.ok
ext/storage_sources/s3_store/s3_aws_manager.h
ext/storage_sources/s3_store/s3_storage_source.cpp
test/suite/test_tiered03.py
test/suite/test_tiered10.py

This PR adds a singleton class to s3_storage_source to ensure the AWS SDK is initialized and terminated in the correct order when multiple connections are active. The class is globally visible across connections and uses a reference counter to know when to initialize the SDK and when to terminate without causing other connections to hang. The first call to the extension will initiate the SDK while subsequent calls will increment the reference counter. Then each call to terminate will decrement the reference counter until it reaches 0 at which point SDK shutdown will be called. The fix also includes changes to S3Flush to properly handle multiple WT home directories.

WT-8896 Add class to s3_storage_source to handle AWS SDK initialization and termination

---

dist/api_data.py
src/config/config_def.c
src/tiered/tiered_handle.c
test/suite/test_tiered04.py

We have a place in `tiered->obj_config` to store the base object configuration. I fixed that to contain the consistent information and removed the places where it was hard coded on particular paths.

WT-8299 All object metadata should consistently indicate it is a tiered object.

---

test/checkpoint/CMakeLists.txt

Add some test_checkpoint cases with a lot of runs per go.
There was a problem last week with the WT-5927 code that is easily repeatable this way and wasn't otherwise detected by the standard test runs. All the existing cases of test_checkpoint we run do only two runs at a time, except for the ones that only do one.
I've only added two new cases because there are already a lot; the mixed-table ones seem to offer the most traction, and there's probably no need to add any more than this.

WT-9180 Add test_checkpoint cases with more runs

---

src/btree/bt_cursor.c
test/suite/test_flcs05.py

Fix a problem with FLCS non-overwrite insert.
The value returned on a duplicate key error for tombstones and implicit rows was uninitialized rubbish rather than 0.
Add a test.

WT-9181 FLCS non-overwrite insert returns uninitialized values

---

src/btree/bt_vrfy_dsk.c
src/support/timestamp.c
test/suite/test_truncate10.py

Check the fast-delete timestamps against both the time aggregate they're packed with and the parent aggregate.

WT-9179 Timestamp verification for fast-delete information

---

dist/stat_data.py
src/include/extern.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/txn/txn_ckpt.c
src/txn/txn_timestamp.c
test/suite/test_checkpoint_snapshot02.py

Revert "WT-9041 checkpoint can miss transactions with commit times before stable (#7774)"
This reverts commit 07cee370d83fd1c90f4ecf6781331db020960323.

WT-9177 Checkpoint waiting for transactions to complete can deadlock

---

src/docs/transactions_api.dox

@sueloverso and @keithbostic: This is a very small doc change to capture the point Keith B. made in slack last week that applications should not pause during a transaction.   
I'm open to suggestions if you think this point should be stated more forcefully, or if there is other information from that conversation (copied onto the WT-9134 ticket) should be added to the doc.

WT-9134 Document WiredTiger expectations for transaction progress

---

src/docs/transactions_api.dox

Sorry to hit you with another PR, @sueloverso.  I somehow missed your comment on the last one.  This change addresses that.

WT-9205 Correct transaction warning text in documentation

---

test/cppsuite/test_harness/test.cpp
test/cppsuite/test_harness/workload/database_operation.cpp
test/cppsuite/test_harness/workload/database_operation.h
test/cppsuite/tests/test_template.cpp

Those changes let the user be able to override the validation algorithm that is triggered at the end of a test when the tracking component is enabled.
**Note: The testing of this new feature will be done as part of WT-9094.**

WT-9093 Allow the user to override the validation algorithm in the cpp suite

---

src/cursor/cur_backup.c
src/cursor/cur_config.c
src/cursor/cur_ds.c
src/cursor/cur_dump.c
src/cursor/cur_file.c
src/cursor/cur_hs.c
src/cursor/cur_index.c
src/cursor/cur_join.c
src/cursor/cur_log.c
src/cursor/cur_metadata.c
src/cursor/cur_stat.c
src/cursor/cur_table.c
src/cursor/cur_version.c
src/include/cursor.h
src/include/extern.h
src/include/meta.h
src/include/wiredtiger.in
src/lsm/lsm_cursor.c
src/session/session_dhandle.c

Add undocumented cursor method to allow applications to detect checkpoint cursor mismatch.

WT-9208 add cursor method to allow applications to detect checkpoint cursor mismatch

---

src/btree/bt_delete.c
src/include/btree_inline.h
test/suite/test_checkpoint24.py
test/suite/test_checkpoint25.py

Add tests for fast-truncate and checkpoint cursors.

WT-9183 Fast-truncate in readonly trees can result in truncated items reappearing

---

test/suite/test_hs14.py

Increase the cache size to reduce eviction activity. Eviction hinders the latency and gets inaccurate results.

WT-8431 Increase test_hs14 cache size to reduce eviction activity

---

src/include/extern.h
src/include/reconcile.h
src/reconcile/rec_child.c
src/reconcile/rec_col.c
src/reconcile/rec_row.c

Proxy cells must copy fast-truncate information before releasing the WT_REF lock, it's possible for a checkpoint to need that information, and once the WT_REF lock is released, the page can be instantiated, discarding the fast-truncate information.
There are now three pieces of information returned from the underlying __wt_rec_child_modify() function (fast-truncate information, child state and hazard pointer), encapsulate it all into a return structure for simplicity.

WT-9165 proxy cells must copy fast-truncate information before releasing the WT_REF lock

---

cmake/configs/base.cmake
cmake/configs/modes.cmake

We can now build CMake using the build type RelWithDebInfo:
```
-DCMAKE_BUILD_TYPE=RelWithDebInfo
```
Additional changes were made to remove the default optimization level set by the RelWithDebInfo build type to use our own `CC_OPTIMIZE_LEVEL` instead. By default, `CMAKE_C_FLAGS_RELWITHDEBINFO` is evaluated to `-O2 -g -DNDEBUG`.
Note: This is incompatible with the `ENABLE_STRICT` flag, see WT-9209.

WT-9189 Compile CMake with RelWithDebInfo build type

---

ext/storage_sources/s3_store/s3_log_system.h
test/suite/test_tiered06.py
test/suite/test_tiered14.py

This change fixes the python test failures due to aws calls intermittently timing out by changing the aws SDK log levels, such that only fatal errors are output to stderr by default. The aws log levels are now mapped to the WiredTiger verbosity levels as follows:
AWS::Fatal -> WT_VERBOSE_ERROR
AWS::Error -> WT_VERBOSE_WARNING
AWS::Warn -> WT_VERBOSE_WARNING
AWS::Info -> WT_VERBOSE_INFO
AWS::Debug -> WT_VERBOSE_DEBUG

WT-8915 Change log verbosity level mapping between AWS SDK and WiredTiger

---

dist/api_data.py
dist/stat_data.py
src/config/config_def.c
src/include/connection.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/tiered/tiered_config.c
test/suite/test_tiered04.py
test/suite/test_tiered07.py
test/suite/test_tiered13.py

* WT-9029 Remove tiered storage object_target_size. It is unused.
* s-all and stats auto-generation.
(cherry picked from commit 98951dc36714908c733b6a853c080a84b4cdb079)

WT-9029 Remove tiered storage object_target_size. It is unused. (v6.0 backport)

---

dist/s_typedef

Quote [] characters used in tr(1) invocation.
(The use of [] characters here is incorrect, but harmless, and might cause the script to work on some very old legacy systems, so is best left alone.)

WT-9259 Unquoted shell metacharacters in s_typedef

---

examples/c/ex_all.c
src/docs/backup.dox

Remove paragraph and example about backing up from a prior (named) checkpoint.
In addition to being possibly incorrect on its own terms, it doesn't work; backup works from the latest checkpoint, and dropping
checkpoints always creates a new one. The example is particularly hazardous as it replaces the old checkpoint with a new one of the same name.

WT-7205 Fix backup documentation to be more accurate with respect to named checkpoints

---

src/btree/bt_debug.c

Make __wt_debug_cursor_page print history for checkpoint cursors.
We can temporarily substitute the right history checkpoint name into the session when called on a checkpoint cursor and there's none already set.

WT-9250 Make __wt_debug_cursor_page print the history store for checkpoints

---

test/suite/test_checkpoint10.py
test/suite/test_checkpoint11.py
test/suite/test_checkpoint14.py

Disable crosschecks in tests.
These tests use timing_stress_for_test=[checkpoint_slow] and a
background checkpoint Python-thread to create a torn transaction in a
checkpoint. This is important for testing that the torn transaction
isn't visible. Actually getting one relies on racing with the
background thread, and (especially under load) sometimes one loses the
race and the checkpoint isn't inconsistent. When I wrote the tests I
added code to crosscheck that this doesn't happen, because when it
does the test succeeds but doesn't actually test anything interesting.
However, it seems that we do get occasional failures on the test
machines, which are at best a nuisance and at worst can get mistaken
for real problems.
Consequently, I'm going to disable the crosschecks until we have a
reliable …

WT-9195 disable torn transaction tests

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/btree/bt_ret.c
src/btree/row_srch.c
src/include/txn_inline.h
test/checkpoint/workers.c

Avoid using the cursor temporary key as the history store key when the
cursor search compare is not found an exact match. When cursor search
didn't find an exact match, the cursor tmp key and the cursor slot can diverge.
Generate the key from the cursor slot in those scenarios to avoid checking
the wrong key in the history store for visibility.
(cherry picked from commit 1e26b59bc55bc111d7b623685731e0784a52d281)
(cherry picked from commit 5003f657b04bde3df73de6f655cbfbbc081cd252)

WT-9096 Fix search near returning wrong key/value sometimes when key doesn't exist (v5.0 backport)

---

dist/api_data.py
dist/stat_data.py
src/config/config_def.c
src/include/connection.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/tiered/tiered_config.c
test/suite/test_tiered04.py
test/suite/test_tiered07.py

* WT-9029 Remove tiered storage object_target_size. It is unused.
Co-authored-by: sueloverso <sue@mongodb.com>

WT-9029 Remove tiered storage object_target_size. It is unused. (v4.4 backport)

---

src/cursor/cur_hs.c
src/history/hs_rec.c
test/suite/test_rollback_to_stable26.py

Performing a prepared insert rollback can lead to a situation where
the datastore and history store may have the same update and inserting it
back again to the history store triggers the OOO timestamp handling.
Compare and fix the existing history store entry start durable timestamp
also to avoid generating the condition where the start durable timestamp
is greater than the stop timestamp.
(cherry picked from commit 462db2dbb2ed77b516dd35addf5dce4f4978f3c1)

WT-9249 Compare and fix the start durable timestamp if it is greater than OOO timestamp (v6.0 backport)

---

src/btree/bt_vrfy_dsk.c
src/include/cell_inline.h
src/support/timestamp.c
test/suite/test_truncate10.py

Add code to vrfy_dsk to crosscheck the timestamps in on-disk fast-delete information.
This caused failures the first time around; digging around revealed that the unpack-time obsolete timestamp cleanup wasn't being done correctly, so I've fixed that. I am not absolutely sure this is what caused the observed failures, but it's at least consistent with the report in WT-9197.

WT-9179 Timestamp verification for fast-delete information (try 2)

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/btree/bt_ret.c
src/btree/row_srch.c
src/include/txn_inline.h
test/checkpoint/workers.c

Avoid using the cursor temporary key as the history store key when the
cursor search compare is not found an exact match. When cursor search
didn't find an exact match, the cursor tmp key and the cursor slot can diverge.
Generate the key from the cursor slot in those scenarios to avoid checking
the wrong key in the history store for visibility.
(cherry picked from commit 1e26b59bc55bc111d7b623685731e0784a52d281)
(cherry picked from commit 5003f657b04bde3df73de6f655cbfbbc081cd252)

WT-9096 Fix search near returning wrong key/value sometimes when key doesn't exist (v4.4 backport)

---

test/cppsuite/test_harness/workload/database_operation.cpp
test/cppsuite/tests/search_near_03.cpp

- Check all usage of `random_generator` where generating a `uint64` value and make sure that invalid inputs (inputs of less than 0) will not be allowed.
- Added checks in `search_near_03.cpp` and `database_operation.cpp`

WT-9185 Add checks for random generator for uint64 in cppsuite

---

lang/python/wiredtiger.i
test/suite/hook_rollback.py
test/suite/test_checkpoint_snapshot03.py
test/suite/test_hs11.py
test/suite/test_hs14.py
test/suite/test_hs20.py
test/suite/wttest.py

* When a rollback error occurs, retry the entire test case.  If too
may retries on a particular test case, or in the entire suite happens,
raise an error.
* Add a test hook to inject rollback errors to verify the retry logic.
* Removed WiredTigerTestCase.retry() function, it is no longer needed.
Adjust callers accordingly.
A similar change was tried before, and was reverted due to errors when
running tests in parallel.  This change overrides Python test case
execution in a cleaner way that avoids pitfalls of the previous approach.

WT-9063 Handle occasional WT_ROLLBACK errors in Python test suite

---

dist/s_style

Portability fix for the new paired-typo checker.
\s isn't portable; use [[:space:]].

WT-9296 Portability fix for the new paired typo checker in s_style

---

test/cppsuite/configs/operations_test_stress.txt

…est (#7828)
(cherry picked from commit 484656b0971c16e5fb45c46589c6bd94ebeb9eb4)

WT-9176 Set operation rate to 10ms for update threads (v6.0 backport) 

---

src/btree/bt_sync.c
test/suite/test_truncate11.py

Deleted pages are no longer needed to be present in the cache
for the checkpoint to work, but these deleted pages are read
into the cache if the fast truncate operation is not visible
to the checkpoint.

WT-9304 Fix checkpoint not to read the deleted pages into cache

---

dist/api_data.py
dist/stat_data.py
src/config/config_def.c
src/conn/conn_api.c
src/conn/conn_log.c
src/include/connection.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/txn/txn_ckpt.c
test/suite/test_rollback_to_stable35.py

The checkpoint may include the updates from a recent transactions
due to some parallel eviction activity. Ensure that all the log
writes that are performed in parallel are flushed to disk before the
metadata gets checkpointed to ensure that all the log records are
written to the disk before the checkpoint becomes stable.
(cherry picked from commit e41ecd207030991a3c79a27ba39e35025f2e8379)

WT-9251 Perform log flush before the metadata checkpoint (#7910) (6.0 backport)

---

test/cppsuite/test_harness/workload/database_operation.cpp
test/cppsuite/test_harness/workload/thread_context.cpp
test/cppsuite/test_harness/workload/thread_context.h
test/cppsuite/tests/burst_inserts.cpp
test/cppsuite/tests/hs_cleanup.cpp
test/cppsuite/tests/search_near_01.cpp
test/cppsuite/tests/search_near_02.cpp
test/cppsuite/tests/search_near_03.cpp

This ticket includes changes to improve the framework flexibility:
- The `insert` function from the `thread_class` was overloaded but it was not necessary
- The `timestamp` argument from the `remove` function appears to be unused, it has been removed
- Users can now provide the `value` they want to insert/update when calling the `insert` and `update` functions from the `thread_class`
Those changes will benefit WT-9094 and won't appear in https://github.com/wiredtiger/wiredtiger/pull/7916 as they deal with internal stuff.

WT-9314 Let users provide values for the inserts/updates operations in the cpp suite

---

dist/test_data.py
src/config/test_config.c
test/cppsuite/test_harness/test.cpp
test/cppsuite/test_harness/timestamp_manager.cpp
test/cppsuite/test_harness/timestamp_manager.h
test/cppsuite/test_harness/util/api_const.cpp
test/cppsuite/test_harness/util/api_const.h
test/cppsuite/test_harness/workload/database_model.cpp
test/cppsuite/test_harness/workload/database_model.h
test/cppsuite/tests/search_near_02.cpp

This ticket involves creating a reverse collator configuration in the CPPSuite framework. Furthermore the random timestamp functionality has been moved to the timestamp manager.

WT-9322 Clean up random timestamp and create reverse configuration option CPPSuite framework

---

dist/s_string.ok
src/session/session_api.c
src/support/rand.c

WiredTiger's RNG seed function uses the system's clock time nanoseconds component, which isn't a great source as a seed value, it's limited to 10^9 assuming it's uniform. Instead, sample the time twice (once for the top 4B, once for the bottom 4B), and use algorithm "xor" from Marsaglia, "Xorshift RNGs" to generate an initial random value to use as a seed.

WT-9336 WiredTiger's RNG seed function is limited to 10^9 initial states.

---

src/os_common/os_fstream_stdio.c

Returning EIO from __stdio_printf if `vfprintf` fails (instead of `WT_ERR_MSG`), prevents the stack from overflowing with printf errors with printf is unable to print.

WT-9046 Don't call error handler when logging an error with __stdio_printf

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_delete.c
src/btree/bt_page.c
src/cursor/cur_hs.c
src/include/btree_inline.h
src/include/txn.h
src/include/txn_inline.h
src/txn/txn.c

It turns out that reading from a history store checkpoint correctly requires doing accurate visible_all checks relative to the checkpoint context; bypassing them doesn't work. This is because it's possible for outdated history store entries with globally visible stop times and nonzero start times to hang around; they are necessarily sorted (and thus seen during reads) before more recently added entries with zero start times and later stop times. They're supposed to be skipped over via a global visibility check; that check can't be shortcut. (Assuming all stop times are globally visible causes items to disappear; assuming none are causes obsolete stop times to be honored and thus also causes items to disappear.) Therefore, visible_all needs to be able to test against the checkpoint's …

WT-9341 Implement proper visible_all for reading checkpoints

---

test/suite/wttest.py

This change fixes the bug where `wttest` would try and download objects from the S3 bucket even when the S3 test is skipped.

WT-9338 Fix wttest to not download S3 objects when test is skipped

---

dist/s_style
src/conn/api_calc_modify.c
src/conn/conn_log.c
src/include/txn_inline.h
src/include/version.h
src/schema/schema_alter.c
src/schema/schema_create.c

* Added a check to `s_all` in `s_style` to check that return values are in brackets.
* Modified the regex to ensure that comments and strings with 'return' will not be picked up. 
* Output with filename, line number and expression. 
* Tested with edge cases. 
* Modified code in files that have missed parentheses.

WT-8908 Expand s_all to check return values are in parentheses

---

src/include/txn_inline.h
src/txn/txn_timestamp.c
test/cppsuite/test_harness/workload/thread_context.cpp
test/cppsuite/test_harness/workload/thread_context.h
test/csuite/tiered_abort/main.c
test/csuite/timestamp_abort/main.c
test/suite/test_timestamp28.py
test/utility/test_util.h

Reverts wiredtiger/wiredtiger#7962
There was some fallout in cppsuite that we didn't expect, so reverting this while we investigate.

Revert "WT-9186 Check earlier first commit timestamp against stable timestamp"

---

src/meta/meta_ckpt.c
src/session/session_dhandle.c

Fix metadata race in checkpoint cursor open.
Read the timestamps after the snapshot; the timestamps are written
before the snapshot, so we know that if we get a timestamp it must be
either from the same checkpoint or newer than the snapshot. It isn't
valid to have or use a timestamp from an earlier checkpoint (unlike a
btree) -- if the timestamp isn't present it's cleared. However,
because the system can't go from having a stable (or oldest) timestamp
to not having one, if we get none we're ok even if it's actually from
the next checkpoint.
(The trouble is that if the timestamp isn't written, we don't get a
wall clock time for it, so we have to allow for this.)

WT-9367 Fix remaining race in checkpoint cursor open

---

dist/api_data.py
dist/stat_data.py
src/config/config_def.c
src/conn/conn_api.c
src/conn/conn_log.c
src/include/connection.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/txn/txn_ckpt.c
test/suite/test_rollback_to_stable35.py

The checkpoint may include the updates from a recent transactions
due to some parallel eviction activity. Ensure that all the log
writes that are performed in parallel are flushed to disk before the
metadata gets checkpointed to ensure that all the log records are
written to the disk before the checkpoint becomes stable.
(cherry picked from commit e41ecd207030991a3c79a27ba39e35025f2e8379)

WT-9251 Perform log flush before the metadata checkpoint (v5.0 backport) (#7910)

---

cmake/configs/wiredtiger_config.h.in

Sorry about leaving this out, I've verified it's working now with the following four combinations:
* Machine without libmemkind, and `HAVE_MEMKIND=0` (builds fine, but without memkind of course)
* Machine without libmemkind, and `HAVE_MEMKIND=1` (fails to build, as expected)
* Machine with libmemkind, and `HAVE_MEMKIND=0` (verified it takes the non-memkind preprocessor option)
* Machien with libmemkind, and `HAVE_MEMKIND=1` (verified it's now seeing the right include directive).
Note that the default memkind version on an Ubuntu 18.04 workstation is too old, the version in 20.04 works fine though.

WT-9295 Add missing ENABLE_MEMKIND to wiredtiger_config generator file

---

test/suite/test_export01.py

I tried to reproduce the issue on the target hardware. After running 1500 iterations I didn't get even one crash. This PR adds a debug functionality to copy WiredTiger.export file right after it's generated. Hopefully, if we get the crash next time we will be able to understand the reason.

WT-9203 In test_export01, backup WiredTiger.export file right after it's created

---

test/evergreen.yml

* Check for missing strict flags in `evergreen.yml` file. 
* Wiredtiger should always be compiled with strict enabled unless there is a good reason to not. 
* Enabled strict compilation for `compile wiredtiger address sanitizer` and `compile wiredtiger address sanitizer ppc ubuntu`  functions
* Adding it into the functions default compile flags since it is always needed. This avoids having to pass it in as a variable every time the function is called.

WT-9412 Add missing flags for evergreen testing

---

test/evergreen.yml

* Moved the following tests to use "compile wiredtiger address sanitizer" so that it compiles with ASan enabled, in this function ASan is part of the default compiler flags used. 
* race-condition-stress-sanitizer-test
* race-condition-stress-sanitizer-test-no-barrier

WT-9149 Missing sanitizer flags in Evergreen

---

dist/s_string

Make `s_script` skip all the files in the `test/cppsuite` folder. This will unblock WT-9385 and is a temporary change that will be fixed by WT-9433.

WT-9438 Skip cppsuite files for spell check

---

src/evict/evict_page.c
src/include/cache_inline.h
src/include/txn_inline.h

Don't use checkpoint-cursor transactions for eviction.
Also assert that we don't try to do visibility checks using a checkpoint-cursor transaction when not reading from a checkpoint, or vice versa.

WT-9439 Don't attempt to evict using a checkpoint-cursor snapshot

---

dist/api_data.py
src/config/config_def.c
src/include/wiredtiger.in

* Deprecated `object_target_size` as a config in `api_data.py`
* Removed the config option by setting `object_targed_size` in `tiered_config` as `undoc=True`
* Removed `object_target_size` from `tiered_storage_configuration_common` 
* tested compatibility with `test/evergreen/compatibility_test_for_releases.sh`

WT-9302 Deprecated object_target_size as a config in api_data.py

---

test/cppsuite/configs/cache_resize_default.txt

The time has been reduced between each insert so it is less likely that we will change the cache size while we try to insert data.

WT-9377 Reduce the time between each insert in the cache_resize cpp test

---

dist/s_all
test/cppsuite/configs/cache_resize_default.txt
test/cppsuite/src/component/operation_tracker.cpp
test/cppsuite/src/component/operation_tracker.h
test/cppsuite/src/main/thread_worker.cpp
test/cppsuite/tests/cache_resize.cpp
test/cppsuite/tests/test_template.cpp

`set_tracking_cursor` now takes session as an argument to allow greater flexibility in what can be saved to the tracking cursor without users needing to update the function interface.
Initially I also looked at reducing the number of arguments passed in, but these changes lead to issues in other areas of the code and so the arguments have been left as is.

WT-9388 Pass thread worker session into set_tracking_cursor

---

test/evergreen.yml

The new cppsuite test task didn't upload libraries so core dumps aren't helpful. This change gets libraries and removes most other content which it doesn't need.

WT-9479 Fixing cppsuite archiving stage in evergreen

---

dist/api_data.py
src/config/config_def.c
src/include/wiredtiger.in
test/suite/test_tiered05.py

WT-9302 Deprecated object_target_size as a config in api_data.py (#8029)
* WT-9302 deprecating object_target_size in api_data.py, adding changes from config_def.c and wiredtiger.in
* Removed the config option by setting `object_targed_size` in `tiered_config` as `undoc=True`
* Removed `object_target_size` from `tiered_storage_configuration_common`
* tested compatibility with `test/evergreen/compatibility_test_for_releases.sh`
(cherry picked from commit d9f9b08dfc14190698c9d79d5dd5516990095856)

WT-9302 Deprecated object_target_size as a config in api_data.py (v5.0 backport) 

---

dist/s_docs
dist/s_release
dist/s_string
src/docs/introduction.dox

In [WT-9310](https://jira.mongodb.org/browse/WT-9310) we decided to deprecate/remove the NEWS file. However, the references to the NEWS file in those dist scripts were not fully removed, including the changelog in the WiredTiger documentation. This PR is to get them cleaned up.

WT-9494 Remove references of NEWS file from dist scripts and changelog from documentation

---

ext/compressors/zlib/zlib_compress.c

Use the right ifdef to build in the zlib compressor.

WT-9497 Wrong ifdef in the zlib compressor extension

---

src/docs/license.dox

Update locations of separately-licensed code in license.dox.

WT-9493 Update 3rd party license paths to match source code

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable37.py

RTS reads the timestamps present as part of the key/value of a history store
record to decide it's visibility. These timestamp values can be wrong when
there exists a globally visible tombstone in the update list and leads to
removal of the entire key by restoring a wrong update/tombstone combination.
To avoid RTS generating wrong update/tombstones, always read the cell time
window information to decide the HS update visibility.

WT-9500 Fix RTS to use cell time window instead of key/value timestamps

---

src/btree/bt_sync.c

Checkpoint cleanup marks the in-memory obsolete pages for urgent
eviction when they are obsolete based on the reconciliation results.
For a modified page, the reconcilation result is invalid and deciding
the page obsoleteness can lead to marking a page for urgent eviction
that is not obsolete.
The provided fix doesn't fix the race condition of marking the page
dirty with checkpoint cleanup marking it for urgent eviction. Adding
more complexity to protect a page being marked for urgent eviction
in parallel to page dirty is not worth.

WT-9502 Checkpoint cleanup not to mark the dirty page as obsolete

---

dist/stat_data.py
src/include/extern.h
src/include/stat.h
src/include/wiredtiger.in
src/schema/schema_drop.c
src/support/stat.c
src/tiered/tiered_handle.c
src/tiered/tiered_work.c
test/csuite/schema_abort/main.c
test/suite/test_tiered07.py

This change fixes the stale tiered pointers and dereferencing null pointer failures. I also found a couple places in schema_abort that were incorrect and needed to send in the `remove_shared` configuration.
The test does not yet pass as it hits other issues, such as WT-9486. Those other failure signatures should be worked out in different tickets.

WT-9446 Remove tiered work units when dropping a tiered table.

---

test/cppsuite/configs/test_template_default.txt
test/cppsuite/src/main/database_operation.cpp
test/cppsuite/src/main/database_operation.h
test/cppsuite/src/main/test.cpp
test/cppsuite/src/main/transaction.cpp
test/cppsuite/src/main/transaction.h
test/cppsuite/src/main/validator.cpp
test/cppsuite/src/main/validator.h
test/cppsuite/tests/cache_resize.cpp
test/cppsuite/tests/test_template.cpp

A couple of fixes Identified when writing the example test in the cppsuite docs:
- Pass the database into `validate` so we can check against its contents
- Make the comment in test_template_default.txt a single line. Otherwise the sed command in `create_test` only deletes the first line
- Allow the user to access the number of operations per transaction when writing tests

WT-9556 Clean up code used by the cppsuite example test

---

dist/api_data.py
src/config/config_def.c
src/include/wiredtiger.in
test/suite/test_tiered05.py

* WT-9302 deprecating object_target_size in api_data.py, adding changes from config_def.c and wiredtiger.in
* Removed the config option by setting `object_targed_size` in `tiered_config` as `undoc=True`
* Removed `object_target_size` from `tiered_storage_configuration_common`
* tested compatibility with `test/evergreen/compatibility_test_for_releases.sh`
(cherry picked from commit d9f9b08dfc14190698c9d79d5dd5516990095856)

WT-9302 Deprecated object_target_size as a config in api_data.py (#8029)

---

dist/s_mentions

After compiling WiredTiger the build folder will contain full paths to the WiredTiger directory, and if that path contains the ticket number `s_mentions` is looking for then `s_mentions` will raise a warning incorrectly. There was existing code to check for this, but it didn't handle symlinks correctly. 
Now that build_posix is deprecated we can also simplify the code and just ignore the build folder.

WT-9473 Update s_mentions to exclude build directories.

---

test/evergreen.yml

Change the `/opt/mongodbtoolchain/` path in evergreen to `/opt/mongodbtoolchain/v3` as the former is a symlink to v3 will be deprecated in future.

WT-8903 Convert all GDB references to explicitly use the v3 toolchain

---

test/simulator/timestamp/call_log_manager/call_log_manager.cpp
test/simulator/timestamp/call_log_manager/call_log_manager.h

The call log for open session is processed by creating a new session object in connection and adding it to the session map along with the session id.

WT-9222 Process the call log for open_session()

---

test/evergreen/build_windows.ps1

This also fixes a couple of whitespace oddities I found.
I was tossing up between this and a version that let you write `Die-On-Failure(cmake ...)` but it got a little weird. The function calls don't actually return an exit code - they return some opaque type that we'd have to extract the exit code from somehow, and I'm not confident that every binary returns the same type of object.
Hopefully this doesn't result in a cascade of Evergreen failures...

WT-9587 Fix Windows status reporting in evergreen

---

test/format/verify.c

Logic in the assert doesn't match the comment above it in `table_verify_mirror`. This PR fixes the assert to match the comment.

WT-9584 Fixed verification logic in table_verify_mirror

---

dist/s_style

s_style checks for explicit declarations of ret using the regex `int.*[, ]ret[,;]`, but this is too broad and will also match against functions that contain "int" in their name and take `ret` as an argument. For example __wt_call_log_pr**int**_return(conn, session, **ret**, "")
Add a filter to the regex above to ignore lines that contain brackets as this indicates the line is a function call and not a variable declaration.

WT-9573 Ignore "explicit declaration of ret" false positive in s_style

---

cmake/configs/base.cmake
test/evergreen.yml
test/evergreen/compatibility_test_for_releases.sh

Fixing fallout of WT-9455. Fixing optimization for perf tests (typo). Fixing Ubuntu PPC tests with removing ZSTD as its not supported. Fixing compatibility tests by disabling extensions

WT-9610 Unable to set HAVE_BUILTIN_EXTENSION_ZSTD: Failed to find zstd library

---

test/suite/test_salvage01.py

Make FLCS test_salvage01 more robust.
When looking for the intended place for intentional data corruption, search for a sequence of bytes in adjacent rows instead of just one byte.
This can still fail if the sequence ends up sitting across a page boundary, but it's much less likely to get false matches in bad places that result in test failure than looking for just one byte.

WT-9605 Make test_salvage01 more robust for FLCS

---

cmake/README.md
cmake/configs/base.cmake
cmake/define_libwiredtiger.cmake
src/docs/build-posix.dox
src/docs/build-windows.dox
test/evergreen.yml

Updating cmake to default python enable/disable based on presence. Requiring C11 standard for compiler. Improving doc around tool requirements and cmake features.

WT-9614 Improve required compiler and python support in cmake/doc

---

test/evergreen.yml

Disabling ZSTD on little endian as big endian doesn't support it.

WT-9596 verify-datafile-little-endian test couldn't open lz4 compressor extension

---

cmake/README.md
cmake/configs/base.cmake
test/evergreen.yml

Disabling Catch2 C++ tests by default as it exposes additional symbols and downloads a 3rd party package

WT-9634 s_export on a clean WT checkout complains about unit-test function

---

test/evergreen.yml

Adding back enabling python and strict for doc compile for 6.0

WT-9639 doc-update fails due to missing python folder

---

src/btree/bt_cursor.c
test/suite/test_flcs06.py

Detect conflicts when (re-)truncating zero values in FLCS.
Add a Python test for this case.

WT-9522 Add missing conflict check in fixed-length-column-store

---

test/format/config.c

This was the only thing in the ticket that turned out to be a real issue. I played around with a couple of different formats for that weird comment, and `s_all` is happy as-is so let's leave it.

WT-9653 test/format mirroring: cosmetic changes

---

test/suite/test_cursor_bound_fuzz.py

With this change, the unit-test-long takes 1hr now. Previously the unit-test-long would take 3 hrs.

WT-9635 Fix Cursor bound fuzz taking too long to run

---

src/evict/evict_page.c
src/include/btree_inline.h
src/include/extern.h
test/suite/test_truncate15.py

Evict any committed truncate, not just globally-visible ones.
This turns out to be more than a one-line change because for eviction threads the check happens before we get the snapshot that we'll be using to check for visibility. So in that case we want to check explicitly if the truncate's committed. Otherwise, if we have a snapshot, use it; otherwise fall back to a global visibility check.
Include the test Hari posted in the ticket as test_truncate15, with a few adjustments. Most notably, the cache overflow condition now results in reads failing with WT_ROLLBACK, so catch that and fail if we see it.
(Otherwise the test harness retries the whole test, and that isn't what we want.)
Also, I had to make it larger to get it to fail reliably.
Note 1: the transition from page_del_active to …

WT-9393 Reading fast truncated pages in a readonly database can lead to cache stuck

---

src/block_cache/block_map.c
src/include/extern.h
src/include/extern_posix.h
src/include/extern_win.h
src/include/wiredtiger.in
src/os_posix/os_map.c
src/os_win/os_map.c

Correct the pointer-return argument types in the mmap call chain.
Note: the use of `void *` instead of `void **` to accept a pointer to an arbitrary pointer occurs because because if `x` is a `foo *` rather than a `void *`, passing `&x` to an argument of type `void **` is rejected by the compiler. Declaring the argument as `void *` prevents this check, and works on all real machines (as opposed to those run only by comp.lang.c contributors). That's why it was the way it was.
However, it's unsafe (in that you can accidentally pass `x` instead of `&x `and it won't be caught) and also hiding formally undefined behavior (at least with strict-aliasing enabled) and that might eventually lead to problems. Furthermore, the call sites we have are already passing the address of a `void *`, so …

WT-9647 Correct the pointer return arguments in the mmap call chain

---

src/block/block_compact.c

We weren't updating compact statistics in __wt_block_compact_page_rewrite()

WT-9629 Fix collection of compact progress statistics

---

test/checkpoint/checkpointer.c

We need to wait to destroy the lock protecting the stable timestamp
until all threads using that lock have exited.

WT-9643 Fix pthread_mutex_destroy() failure during test_checkpoint.

---

src/btree/bt_split.c

(cherry picked from commit 3a5e2b974eae2b5ebe2a7cc007b46aaea79516c0)

WT-9477 Don't allow checkpoint triggering internal page split which leads to corrupted internal page in the checkpoint

---

test/cppsuite/configs/hs_cleanup_stress.txt
test/cppsuite/src/main/database_operation.cpp
test/cppsuite/src/main/transaction.cpp
test/cppsuite/src/main/transaction.h
test/cppsuite/tests/burst_inserts.cpp
test/cppsuite/tests/cache_resize.cpp
test/cppsuite/tests/cursor_bound_01.cpp
test/cppsuite/tests/hs_cleanup.cpp
test/cppsuite/tests/search_near_02.cpp

The changes include:
- A rework of the cppsuite-hs-cleanup code
- The deactivation of the cache size runtime check
- The removal of the `can_rollback()` function

WT-9466 Rework cppsuite-hs-cleanup code

---

test/evergreen.yml

Stop the `coverage-report` task from timing out and not reporting coverage metrics, as well as fixing any subsequently revealed errors.
There's a handful of changes here:
1. `cppsuite`, `cppsuite`, `format`, and the `--long` flag for python tests have been dropped from `coverage-report` as these tests are long running and do not add much test coverage. Total coverage has dropped from [(90%/60%)](https://build_external.s3.amazonaws.com/wiredtiger/code-statistics/7aa26795530b445019003a758a3027a891f1cfc7/coverage_report_wiredtiger_code_statistics_patch_7aa26795530b445019003a758a3027a891f1cfc7_62e31093850e613da63ca00f_22_07_28_22_42_18-2/1_coverage_report_main.html) for line and branch coverage to [(88%/58.6%)](https://build_external.s3.amazonaws.com/wiredtiger/code-statistics/7aa26795530b4450 …

WT-9394 Fix coverage-report timing out

---

src/btree/bt_compact.c

Ensure that we only call __compact_walk_internal() on internal pages.

WT-9057 Address null address read in compact walk.

---

cmake/configs/base.cmake
src/block/block_ext.c
src/btree/bt_page.c
src/btree/col_modify.c
src/btree/row_modify.c
src/reconcile/rec_visibility.c
src/schema/schema_project.c

The warnings were found by doing the following:
```
mkdir build && cd build
cmake -DCC_OPTIMIZE_LEVEL=-Og -DENABLE_STRICT=1 -G Ninja ../.
ninja
```
The compilation would generate errors with the following syntax:
```
error: 'XXX' may be used uninitialized in this function [-Werror=maybe-uninitialized]
```

WT-9481 Initialize variables to compile with -Og 

---

test/evergreen.yml
test/format/CONFIG.mirror

This changes all Evergreen test/format configurations to have some amount of tracing by default. It also adds a dedicated `format-mirror-test` task that's basically the stress config but with all tracing enabled.
There are a couple of linked patch builds on the Jira ticket. These two patch builds run every single test-format configuration I could find, so I believe the new tracing defaults are safe to add.
There's a failure for `format-abort-recovery-stress-test` in `table_verify_mirror`, so there's clearly an issue elsewhere in this branch, but I don't believe it's related to this tracing change. I'll investigate it, but I don't think it should block me from getting some feedback on this PR.

WT-9555 Add dedicated mirror config and trace arguments to test/format

---

bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
ext/test/fail_fs/CMakeLists.txt
ext/test/fail_fs/fail_fs.c
src/utilities/util_dump.c
test/fuzz/config/fuzz_config.c
test/fuzz/fuzz_util.c
test/salvage/salvage.c

Cleaning up usage of assert from assert.h and enabling compile with Release build type. Updated fail fs to use test_util.

WT-9209 Cannot build Release build with ENABLE_STRICT enabled

---

cmake/define_libwiredtiger.cmake
lang/python/CMakeLists.txt
src/utilities/CMakeLists.txt
test/cppsuite/CMakeLists.txt
test/ctest_helpers.cmake
test/evergreen.yml
test/unittest/CMakeLists.txt

Re-enabled tcmalloc usage in evergreen. Updated linking of tcmalloc from at the shared object level to the executable level which should prevent running multiple allocators which is known to introduce issues.

WT-9710 Re-enable tcmalloc usage in evergreen

---

src/history/hs_rec.c
src/include/extern.h
src/reconcile/rec_write.c

A data corruption bug in [WT-9705](https://jira.mongodb.org/browse/WT-9705) is rarely reproducible (more info in the ticket itself). In diagnostic mode, the following assert is hit.
`WT_ASSERT(session, prev_upd->start_ts == WT_TS_NONE); `
However, in release mode, EBUSY is returned. It would be helpful to have a core file when/if this issue happens in MongoDB to extract more information about the bug.
The scope of this ticket is to convert the WT_ASSERT to WT_ASSERT_ALWAYS.

WT-9752 Change WT_ASSERT to WT_ASSERT_ALWAYS in __wt_hs_insert_updates

---

test/format/config.c

I verified this by changing `format.sh` to add the `-S` option to the format command, which runs the syntax-only mode, running that in a loop, and counting how often it was enabled.

WT-9735 Mirroring enabled too often

---

test/evergreen.yml

Explicitly disabling TCMALLOC on mac OS X via the config flag as some evergreen machines have TCMALLOC installed and that can cause the compile to use it when other hosts do not have it installed

WT-9723 Explicitly disabling TCMALLOC on mac OS X 

---

src/btree/bt_split.c
src/include/extern.h
src/include/misc_inline.h
src/include/txn_inline.h
src/session/session_compact.c

The `__wt_timing_stress` function currently does not allow for a specific sleep time, and generates a random sleep time by default when called. 
- We have made changes so the function will take an explicit sleep time if given. 
- Refactored the function so it looks cleaner.

WT-9733 Clean up the __wt_timing_stress interface

---

test/evergreen.yml

When investigating the task timeout failure in WT-9761, it was found we have 2 Evergreen tasks running ASAN testing on the PPC platform:
- format-stress-sanitizer-test-ppc-ubuntu
- format-stress-ppc-zseries-test
The only differences are the former task uses a different ASAN symbolizer (v4 toolchain vs llvm-6.0) and runs format for a longer period of time (6hrs vs 2 hrs). 
The proposed solution is to remove the latter task which hit timeout failure recently (likely due to a slow host issue).

WT-9761 Remove duplicated ASAN test on PPC

---

test/cppsuite/tests/search_near_01.cpp

Increasing the buffer for search near assert due to changes in WT-9474 which increase the stats incremented with prefixed bounds.

WT-9609 cppsuite-search-near-01-stress assert failure due to changes in statistics

---

bench/workgen/workgen.cxx

Fix the below warning observed when compiling wiredtiger using clang 10. 
```
[366/542]` Building CXX object bench/workgen/CMakeFiles/workgen_cxx.dir/workgen.cxx.o
--
../bench/workgen/workgen.cxx:1197:33: warning: implicit conversion from 'unsigned int' to 'float' changes value from 4294967295 to 4294967296 [-Wimplicit-int-float-conversion]
return (((float)r * sign) / UINT32_MAX);
~ ^~~~~~~~~~
/usr/include/stdint.h:129:23: note: expanded from macro 'UINT32_MAX'
^~~~~~~~~~~
1 warning generated.
```

WT-9760 Fix implicit conversion in workgen.cxx

---

ext/storage_sources/s3_store/CMakeLists.txt
test/evergreen.yml

Previously TCMALLOC wasn't enabled for the S3 extension as it cored. Turns out it was a linking issue.

WT-9590 Fixing linking to TCMALLOC for S3 extension

---

src/history/hs_rec.c
src/include/timestamp_inline.h
test/suite/test_rollback_to_stable39.py

There was  BF reported [BF-26002](https://jira.mongodb.org/browse/BF-26002) where the data store and history store had the same content after restore/restart. The approach to fix this issue is to return EBUSY in the `__hs_delete_reinsert_from_pos ` time window of the inserting record does not match with the time window of the history sore record.

WT-9763 Return EBUSY if the time window of inserting record does not match with history store time window

---

src/tiered/tiered_handle.c

Remove the unused variable `*orig_name` from the function.

WT-9683 Coverity analysis defect 124895: Parse warning

---

src/include/btree_inline.h

Co-authored-by: Ruby Chen <ruby.chen@mongodb.com>
(cherry picked from commit 68d75efac2541f9bbba05d03f7510f50cfa2a83d)

WT-9323 Fix a race tracking whether a tree has updates after a checkpoint (#8194)

---

src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable37.py

RTS reads the timestamps present as part of the key/value of a history store
record to decide its visibility. These timestamp values can be wrong when
there exists a globally visible tombstone in the update list and leads to
the removal of the entire key by restoring a wrong update/tombstone combination.
To avoid RTS generating wrong updates/tombstones, always read the cell time
window information to decide the HS update visibility.
(cherry picked from commit 250a4b0dccf298e5099229bb361a3903d712baa0)

WT-9500 Fix RTS to use cell time window instead of key/value timestamps (#8073) (v4.4 Backport)

---

src/btree/bt_handle.c
test/suite/test_truncate18.py

Code was recently added to read the last record in a column store table
during open. That doesn't work with checkpoint cursors, since they
don't yet have visibility rules configured.
Skip the reading - it was necessary for append operations, which can't
happen in checkpoint cursors.

WT-9776 Opening checkpoint cursor on column store table fails

---

src/docs/spell.ok
src/docs/tool-xray.dox
tools/xray_to_optrack/xray_to_optrack.cxx

LLVM introduced a [change](https://github.com/llvm/llvm-project/commit/77fc1f6049a7414ec193c9ff8226eeb5662a5878#diff-baa6f6f39a0b2833424bed5a6abe2e870a3db85d7ac993d0fecb9c4cd38d8d65) in v9.0 updating debuginfo `symbolizeCode` function to expect `object::SectionedAddress` argument type (instead of uint64_t), which broke the compilation for WiredTiger `xray_to_optrack` tool.
The change in this PR is to adapt to the LLVM change for the Symoblizer call in xray_to_optrack. The Xray tool documentation was updated as well to advise that LLVM v10+ (tested) is needed to run the tool properly.

WT-9591 Adapt to LLVM v9.0+ for a Symoblizer call

---

src/history/hs_rec.c
src/include/timestamp_inline.h
test/suite/test_rollback_to_stable39.py

This bug was one of the cases where the data store and the history store may contain the same value. In this case, skip inserting the same value into the history store again. The fix is the time window of the inserting record and the history store record are compared to make sure that the same record is not being inserted again.
(cherry picked from commit f45ebf82dba6e0d88edccb6c3047a717669b4562)

WT-9763 Return EBUSY if the time window of inserting record does not match with history store time window (v6.0 backport)

---

test/suite/test_tiered08.py

Quick change to disable test_tiered08 since is generating a lot of Evergreen failures.

WT-9839 Disable stress testing in test_tiered08.

---

src/block/block_ckpt.c

Without this fix, an assertion occurs in non-diagnostic mode.

WT-9841 Fix tracking of live_open variable, so it works both in diagnostic and non-diagnostic mode.

---

examples/c/ex_data_source.c
src/cursor/cur_ds.c

This change means that any custom data source cursors requires bounds function to be initialised.

WT-9577 Implement bounded cursor API for the Datastore cursor

---

dist/docs_data.py
dist/s_docs
src/docs/arch-btree.dox
src/docs/arch-fast-truncate.dox
src/docs/arch-index.dox
src/docs/spell.ok

Add a fast-truncate page to the architecture guide.
Improve s_docs so we don't need non-words appearing in certain filenames and symbols (e.g. "vrfy") to be spelling words. This is done with ad hoc seddery because there are not many cases and not that many new ones likely to appear.
Add some spelling words.
Drop most of the old brief description in arch-btree and refer to the new page instead.
Also update the discussion of the transactionality of truncate operations. I'm not changing what the user-facing docs say without discussion, but we can afford to document the current understanding here instead of having it buried in various tickets and github comments.
(The known bug referred to is WT-4158. I didn't put the ticket number in the docs because that doesn't seem like the right thing, …

WT-9811 Fast-truncate page for the architecture guide

---

src/history/hs_rec.c

This assertion was triggering in mongo tests and causing a crash and core dump. However, the impact of this assertion not firing would be to add an invisible update to the history store which would be quickly cleaned up, has no impact on data integrity, and is preferable to a crash in release mode.
As such, downgrade this assertion to only fire in diagnostic mode. Investigation into the root cause will continue in WT-9846

WT-9863 - Downgrade assertion in __hs_delete_reinsert_from_pos

---

test/evergreen/run_format_configs.sh

The RUNDIR (renamed WT_TEST in this PR) gets replaced by each new iteration of format config test runs, even when there is a failure. 
To preserve the database files when there is a failure for debugging purposes; we move the WT_TEST directory to a new directory if there is a failure and prevent it from being overwritten or deleted. 
The directory is named after the failure config in the format WT_TEST_{CONFIG}.

WT-9755 Retain database files after a failure in run_format_configs.sh

---

test/suite/test_truncate15.py

The changes include:
- Avoid long running transaction as it does not change the intent of the test but can cause undesired cache pressure
- Remove unused variables

WT-9673 Avoid long running txn in test_truncate15

---

test/suite/test_stat08.py

In order to avoid consistent failures, we are disabling this test until [WT-9774](https://jira.mongodb.org/browse/WT-9774) is resolved.

WT-9873 Temporarily disable test_stat08

---

src/call_log/call_log.c
test/simulator/timestamp/call_log_manager/call_log_manager.cpp
test/simulator/timestamp/call_log_manager/call_log_manager.h
test/simulator/timestamp/src/include/session_simulator.h
test/simulator/timestamp/src/session_simulator.cpp

I've added the processing logic in the call log manager to invoke the timestamp_transaction_uint() API in the session. At the moment the set methods for the timestamps are placeholders and the validation logic for the timestamps will be handled in future tickets. 
I've also removed the quotes in the generate call log for timestamp_transaction_uint() for the timestamp input argument so that it can be interpreted as a uint64_t instead of a string.

WT-9241 Process the call log for timestamp_transaction_uint()

---

src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable40.py

Rollback to stable operations decides the stability/obsoleteness of an update before it restores it to replace an unstable update. Having a proper global time window state can help rollback to stable to restore the proper updates to bring back the database into a consistent state.

WT-9870 Fix the global time window state before performing rollback to stable

---

test/evergreen/verify_wt_datafiles.sh
test/format/config.c

The changes include:
- Make sure `logging` is enabled before using `printlog`. If `logging` is not enabled, `printlog` won't be able to find any log files to work on.
- Also disabled the `transaction.timestamp` parameter if `logging` is enabled as they are incompatible.

WT-9829 Verify logging is enabled before using printlog

---

src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable40.py

* WT-9870 Fix the global time window state before performing rollback to stable
* WT-9870 Fix the global time window state before performing rollback to stable
Rollback to stable operations decides the stability/obsoleteness of an update before it restores it to replace an unstable update. Having a proper global time window state can help rollback to stable to restore the proper updates to bring back the database into a consistent state.
* Update the pinned timestamp in recovery as part of txn setup
* A new line
* Move setting stable timestamp also into a setup function
* change the condition to stable timestamp instead of recovery
* better comment
* Add comments about checkpoint and oldest timestamp
(cherry picked from commit 1237b92598f4056b456dd937afeb64481b427f3d)
* Change assert …

WT-9870 Fix the global time window state before performing rollback to stable (5.0 backport)

---

src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable40.py

* WT-9870 Fix the global time window state before performing rollback to stable
Rollback to stable operations decides the stability/obsoleteness of an update before it restores it to replace an unstable update. Having a proper global time window state can help rollback to stable to restore the proper updates to bring back the database into a consistent state.
* Update the pinned timestamp in recovery as part of txn setup
* A new line
* Move setting stable timestamp also into a setup function
* change the condition to stable timestamp instead of recovery
* better comment
* Add comments about checkpoint and oldest timestamp
(cherry picked from commit 1237b92598f4056b456dd937afeb64481b427f3d)
* Change assert always to assert and function return check
(cherry picked from commit …

WT-9870 Fix the global time window state before performing rollback to stable (4.4 backport)

---

src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable40.py

* WT-9870 Fix the global time window state before performing rollback to stable
Rollback to stable operations decides the stability/obsoleteness of an update before it restores it to replace an unstable update. Having a proper global time window state can help rollback to stable to restore the proper updates to bring back the database into a consistent state.
* Update the pinned timestamp in recovery as part of txn setup
* A new line
* Move setting stable timestamp also into a setup function
* change the condition to stable timestamp instead of recovery
* better comment
* Add comments about checkpoint and oldest timestamp
(cherry picked from commit 1237b92598f4056b456dd937afeb64481b427f3d)

WT-9870 Fix the global time window state before performing rollback to stable (6.1 backport)

---

test/suite/test_cursor_bound16.py

Added testing to test_cursor_bound16 to test the bounded cursor API works with JSON cursors.

WT-9579 Test implementation of bounded cursor API for the JSON cursor

---

src/call_log/call_log.c
test/simulator/timestamp/call_log_manager/call_log_manager.cpp
test/simulator/timestamp/call_log_manager/call_log_manager.h
test/simulator/timestamp/src/include/session_simulator.h
test/simulator/timestamp/src/session_simulator.cpp

I've added a method to the session class for querying the commit, first_commit, read and prepare timestamps. Since the call log entry for the `connection.query_timestamp()` and `session.query_timestamp()` are similar, the function `call_log_query_timestamp` in the call log manager handles the calls to both.

WT-9231 Process the call log for session.query_timestamp()

---

src/call_log/call_log.c
src/include/extern.h
src/session/session_api.c

This PR adds a method to print the call log entry for session.timestamp_transaction().

WT-9237 Generate call log for timestamp_transaction()

---

test/simulator/timestamp/call_log_manager/call_log_manager.cpp
test/simulator/timestamp/call_log_manager/call_log_manager.h
test/simulator/timestamp/src/include/session_simulator.h
test/simulator/timestamp/src/session_simulator.cpp

This PR adds the timestamp_transaction method to the simulator session class and the corresponding processing for the call log manager. Note that multiple timestamps can be set in a single call of timestamp_transaciton.

WT-9238 Process the call log for timestamp_transaction()

---

ext/storage_sources/dir_store/dir_store.c

Remove 2 redundant tests (in if check) that were captured by Coverity.

WT-9684 Coverity analysis defect 124205/124090: Redundant test

---

test/simulator/timestamp/call_log_manager/call_log_manager.cpp
test/simulator/timestamp/src/include/session_simulator.h
test/simulator/timestamp/src/include/timestamp_manager.h
test/simulator/timestamp/src/session_simulator.cpp
test/simulator/timestamp/src/timestamp_manager.cpp

The focus of this PR is to add the validate_read_timestamp to the timestamp manager which is used to check whether or not a read timestamp is valid before setting it in the transaction. 
Read timestamps can also now be set in begin transaction along with the round_read configuration option.
I've also added getters for the session transaction timestamps so they can be compared against.

WT-9227 Support read_timestamp processing

---

src/block/block_compact.c

We want to replace the word "skipped" in verbose messages for compact, to be more clear that these skipped pages were intentional and not skipped due to error.  Some variations for "skipped" that I have considered includes: "omitted", "bypassed", "disregarded", "skipped over",  and "intentionally skipped". However, these variations may still be a bit ambiguous to the user surrounding what we are trying to achieve with the skipped pages. 
Therefore, in this PR I have decided to remove the "skipped" portion of the verbose messaging. As @keitharnoldsmith has noted, the skipped statistic in this usage is not particularly informative to the user and can be removed.

WT-9864 Improve compact messages about "skipped" pages

---

src/meta/meta_turtle.c
src/txn/txn_ckpt.c
src/txn/txn_recover.c

I have run existing backup tests and will kick off a test format stress test forcing backup and abort both on.

WT-9926 Remove backup file after recovery checkpoint.

---

test/evergreen/compatibility_test_for_releases.sh

Added a bash associative array containing the required git tags to compatability_test_for_release.sh.
This facilitates compatibility testing with arbitrary versions by specifying the required branches and/or git hashes. For example, this approach was used to test the fix for WT-9795.

WT-9885 Make compatibility_test_for_release.sh more flexible

---

src/include/btree_inline.h

`WT_STAT_SESSION_TXN_BYTES_DIRTY` statistic seems to be overcounting. To mitigate this problem the statistic counter has been moved inside a conditional if statement that checks the page type so that it is not counting internal pages.

WT-9879 Fix overcounting of session txn dirty bytes statistic

---

test/evergreen/compatibility_test_for_releases.sh

The script now handles the case where the branch is not in gittags. In this case, the branch name itself will be used for the git checkout. This is needed for patch testing.

WT-9940 compatibility_test_for_releases.sh handles empty gittags, enabling patches to work

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/include/extern.h
test/cppsuite/tests/search_near_01.cxx
test/suite/test_search_near01.py
test/suite/test_search_near04.py

(cherry picked from commit bc1c3dc0d46ea79127697aae7b50e8b6c5afb14d)

WT-7912 Fix prefix search near optimisation to handle scenarios where the key range is split across pages (#7097) (v4.4 backport)

---

src/cursor/cur_std.c
test/suite/test_cursor_bound01.py

Disable setting bounds with random cursors and add scenario in test_cursor_bound01 to validate this behaviour.

WT-9899 Validate that bounded cursor logic doesn't apply to random cursors

---

test/format/bulk.c
test/format/ops.c

Switched from __wt_atomic_fetch_addv64() to __wt_atomic_addv64 to return the incremented value, rather than the pre-incremented value.
This means that the returned, new timestamp that is used for the commit is after the stable timestamp, not the same as the stable timestamp

WT-9795 - In test/format, use commit timestamps which are after the stable timestamp

---

test/unittest/CMakeLists.txt
test/unittest/tests/test_bounds_restore.cpp

Created a unit test to check the logic behind flag saving and restoration for bounds.

WT-9900 Create unit test to validate cursor bounds save/restore flag logic

---

test/evergreen.yml

Before these changes, the `doc-compile` task is executed by the two variants `! Ubuntu 20.04` and `! Ubuntu 20.04 ASAN`. It is fine to execute that task only on `! Ubuntu 20.04`.

WT-9945 Remove doc-compile task from ASAN build variant

---

test/cppsuite/tests/run.cpp

Use the executable `run` with the `--list` option to list all the cpp tests:
```
./run --list
The tests are:
bounded_cursor_perf
bounded_cursor_prefix_indices
bounded_cursor_prefix_search_near
bounded_cursor_prefix_stat
bounded_cursor_stress
burst_inserts
cache_resize
hs_cleanup
operations_test
search_near_01
search_near_02
search_near_03
test_template
```

WT-9963 Create a new option to list all the cpp tests

---

src/include/btree_inline.h

WT-9323 Fix a race tracking whether a tree has updates after a checkpoint (#8194) (#8228)
Co-authored-by: Ruby Chen <ruby.chen@mongodb.com>
(cherry picked from commit 68d75efac2541f9bbba05d03f7510f50cfa2a83d)
Co-authored-by: Alex Gorrod <alexander.gorrod@mongodb.com>
(cherry picked from commit 3ecab025d4c0a337fe80b6fe55538896c43c159e)

WT-9323 Fix a race tracking whether a tree has updates after a checkpoint

---

dist/s_clang-format

After checking out the Mongo Git repo and trying to run `s_clang-format` from `mongo/src/third_party/wiredtiger/dist`, the script fails due to an invalid path as the script expects to be executed from a WiredTiger Git repo.
These changes fix this issue.
@agorrod, I reused your suggestion from WT-9946 (thanks!) and tweaked it a bit.

WT-9946 Make s_clang-format more robust

---

src/conn/conn_tiered.c
src/include/extern.h
src/tiered/tiered_work.c

This came from Sid who was seeing this when running a wtperf job by hand. I'm not sure why we haven't seen it running other tests but it gets printed out on most/all wtperf configurations.

WT-9983 Remove tiered timed out message.

---

src/cursor/cur_json.c
src/cursor/cur_stat.c
src/include/cursor.h
src/os_common/os_alloc.c
test/suite/test_cursor_bound16.py
test/suite/test_jsondump01.py
test/suite/test_jsondump02.py

@ddanderson We had to revert the original PR as there was fallout on additional Python tests that were only occurring on macOS. Re-creating this PR with `test_jsondump01.py` and `test_jsondump02.py` fully disabled, and `test_cursor_bound16.py` partially disabled.

WT-9950 __wt_realloc with clear memory flag requires knowledge of old size

---

src/history/hs_rec.c
src/include/timestamp_inline.h
test/suite/test_rollback_to_stable39.py

…match with history store time window (#8218) (#8246)
This bug was one of the cases where the data store and the history store may contain the same value. In this case, skip inserting the same value into the history store again. The fix is the time window of the inserting record and the history store record are compared to make sure that the same record is not being inserted again.
(cherry picked from commit f45ebf82dba6e0d88edccb6c3047a717669b4562) (cherry picked from commit bfc6fc15de632da2000143bcce3a23141cfc6a2c)

WT-9763 Return EBUSY if the time window of inserting record does not match with history store time window (v5.0 backport)

---

src/cursor/cur_std.c
test/suite/test_cursor_bound01.py

- Make bounded API error messages consistent.
- Update bounded testing to account for new configuration changes.
- Expand cursor_bound01 to include edge cases.

WT-9947 Tidy up cursor->bound API error messages

---

test/3rdparty/concurrencytest-0.1.2-locally-modified/concurrencytest.py

Restrict usage of os.waitstatus_to_exitcode to only when its supported (which is in all evergreen tests).

WT-10012 Restrict usage of os.waitstatus_to_exitcode

---

test/csuite/wt9937_parse_opts/main.c
test/utility/parse_opts.c

Two changes here:
1. When initialising `TEST_DRIVER`s pass in the enum value `TABLE_NOT_SET` instead of `0`
2. `case '?':` in `testutil_parse_single_opt` is dead code as we'll early exit when `ch == '?'`. Remove this line.

WT-9994 - Fix parse_opts coverity warnings

---

bench/workgen/workgen.cxx
dist/s_string.ok
dist/s_style
ext/storage_sources/dir_store/dir_store.c
test/csuite/wt7989_compact_checkpoint/main.c
test/fuzz/fuzz_util.c

Compiling locally with Clang 14.0.0 fails with
```
warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  
Due to security concerns inherent in the design of sprintf(3), it is highly recommended 
that you use snprintf(3) instead. [-Wdeprecated-declarations]
```
This is due to `sprintf` writing past the end of the buffer if the input string is long enough, while `sprintf` will truncate the string instead.
This PR replaces `sprintf` with `snprintf`, or `__wt_snprintf` where possible.

WT-10022 - Replace sprintf with snprintf in bench and test code

---

test/format/t.c

There is already a call to `wts_verify` before we get to the `skip_operations` label.

WT-10023 Remove duplicate call to verify in test/format

---

test/evergreen.yml

This PR create buckets for the `unit-test-long` task. A similar job was done for the `unit-test` task in WT-4410.

WT-9853 Create buckets for the unit-test-long task

---

src/conn/conn_tiered.c
src/include/extern.h
src/include/tiered.h
src/tiered/tiered_handle.c
src/tiered/tiered_work.c

Renamed the `WT_TIERED_WORK_DROP_LOCAL` and `WT_TIERED_WORK_DROP_SHARED` work units for tiered storage to reflect its purpose and replaced `DROP` with `REMOVE`. This will remove the ambiguity of the work units as they are not used in session->drop(). 
Functions and descriptions for:
- `__wt_tiered_put_remove_shared`
- `__wt_tiered_get_remove_shared`
- `__wt_tiered_put_remove_local`
- `__wt_tiered_get_remove_local` 
Have been adjusted to reflect the naming changes.

WT-9527 Rename tiered work units for removing objects

---

test/evergreen.yml

Increase run on variant for little endian tests due to ops tracking in format using more disk space

WT-10001 Increase variant size for little endian tests

---

test/format/trace.c
test/format/wts.c

Changing test/format statistics setting to fast from all to reduce the cache stuck issues that are a CI blocker and tracked in WT-8054. 
The cache stuck issue is currently see in btree_walk (which is on when all is used) and we hit the sources setting in format.

WT-10061 Changing test/format statistics setting to fast

---

src/include/os_fhandle_inline.h
src/os_posix/os_fs.c
src/os_posix/os_mtx_cond.c
src/os_win/os_mtx_cond.c

The only assumption I've made here is that reads and writes are more common than open/close/mmap/etc. The full list of lines I reviewed is:
src/include/os_fhandle_inline.h:109
src/include/os_fhandle_inline.h:135
src/include/os_fhandle_inline.h:154
src/include/os_fhandle_inline.h:188
src/include/os_fhandle_inline.h:27
src/include/os_fhandle_inline.h:61
src/include/os_fhandle_inline.h:92
src/include/os_fs_inline.h:111
src/include/os_fs_inline.h:137
src/include/os_fs_inline.h:172
src/include/os_fs_inline.h:212
src/include/os_fs_inline.h:35
src/include/os_fs_inline.h:64
rc/os_common/os_fhandle.c:164
src/os_common/os_fhandle.c:188
src/os_common/os_fhandle.c:327
src/os_posix/os_fs.c:1029
src/os_posix/os_fs.c:1066
src/os_posix/os_fs.c:1121
src/os_posix/os_fs.c:1148
src/os_posix/os_fs.c:346 …

WT-10058 Check OS-specific and filesystem verbosity

---

src/btree/bt_debug.c

[Patch build](https://spruce.mongodb.com/version/635ef16ad6d80a5ef41434f0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).

WT-9860 Debug dumps include page deletion information for fast truncate

---

dist/s_string.ok
src/call_log/call_log.c
test/simulator/timestamp/src/connection_simulator.cpp
test/simulator/timestamp/src/include/error_simulator.h
test/simulator/timestamp/src/include/session_simulator.h
test/simulator/timestamp/src/session_simulator.cpp
test/simulator/timestamp/src/timestamp_manager.cpp

This PR includes a few fixes to the timestamp simulator after testing it against the call logs generated from the python timestamp tests. 
- test_timestamp13.py failed as a result of outputting a garbage timestamp value into the call log when query_timestamp fails. I've added a check in __wt_call_log_query_timestamp to not print the queried timestamp in the case of an error.
- test_timestamp22.py failed due to commit_transaction not rolling back if an earlier API call failed on that transaction. Adding a txn_error boolean to the session simulator class fixes this. This boolean is set if any part of the transaction fails and the transaction needs to be rollback during commit transaction. 
- There is also a small fix for parsing timestamp configurations.

WT-10026 Verify the timestamp simulator with the timestamp python tests

---

src/include/verbose.h
src/meta/meta_table.c
src/reconcile/rec_track.c
src/reconcile/rec_write.c

Some notes: for the metadata code, some stuff logs with the "checkpoint progress" module, I left this alone since it's different to the "checkpoint" module and can be left at INFO separately.
For the reconciliation code, I'm assuming that overflow records are reasonably frequently modified/used. In rec_write, I'm assuming dumping keys is appropriate at a higher debug level than seeing which pages were reconciled.
Here's the full list of everything that was reviewed in this PR:
src/meta/meta_ckpt.c:1530
src/meta/meta_ckpt.c:1727
src/meta/meta_table.c:186
src/meta/meta_table.c:216
src/meta/meta_table.c:252
src/meta/meta_table.c:296
src/meta/meta_turtle.c:389
src/meta/meta_turtle.c:549
src/reconcile/rec_track.c:134
src/reconcile/rec_track.c:169
src/reconcile/rec_track.c:342 …

WT-10055 Check metadata and reconciliation verbosity

---

src/btree/bt_sync.c
src/cursor/cur_backup.c
src/cursor/cur_backup_incr.c

Some assumptions for the btree code: I'm assuming that stuff used in bt_vrfy and bt_slvg are reasonably uncommon. I'm also assuming that opening a btree isn't anywhere near the hot path, or frequent enough to justify moving to `DEBUG_2`. The split code does log stuff for every split, but it's a single line so I left it. bt_sync's per-page operations moved to debug2, but I think leaving the per-file stuff as debug1 is ok?
For backup cursors, I suspect adding IDs seems like it'd be common enough to move to `DEBUG_2`, but some confirmation would be good here.
Here's the full list of log lines I checked in case you want to check any of them:
src/btree/bt_curnext.c:589
src/btree/bt_curnext.c:625
src/btree/bt_debug.c:72
src/btree/bt_handle.c:321
src/btree/bt_handle.c:326 …

WT-10054 Review btree and backup cursor verbosity

---

dist/s_release
dist/s_release.list
src/docs/top/main.dox

Two changes are made in this PR:
- Remove the contents and logic of skipping given directories for release packages
- Update the WT doc homepage to replace the "release package" link with a "source code" link for the 11.0.0 release

WT-10021 Remove directory exclusions for release packages

---

src/schema/schema_drop.c
src/tiered/tiered_handle.c

Schema layer: I've assumed there would normally be many more objects than tables.
Tiered storage: I suspect object creation/removal is much more common than adding/removing schemas or tiers.
Here's the full list of lines I reviewed, in case you're *really* bored and want to check:
src/schema/schema_drop.c:212
src/schema/schema_drop.c:229
src/schema/schema_drop.c:244
src/schema/schema_drop.c:248
src/schema/schema_drop.c:289
src/tiered/tiered_config.c:170
src/tiered/tiered_config.c:171
src/tiered/tiered_handle.c:161
src/tiered/tiered_handle.c:209
src/tiered/tiered_handle.c:212
src/tiered/tiered_handle.c:239
src/tiered/tiered_handle.c:305
src/tiered/tiered_handle.c:33
src/tiered/tiered_handle.c:345
src/tiered/tiered_handle.c:36
src/tiered/tiered_handle.c:388
src/tiered/tiered_handle.c:458 …

WT-10056 Check schema layer tiered storage verbosity

---

src/log/log.c
src/lsm/lsm_merge.c
src/lsm/lsm_tree.c
src/lsm/lsm_work_unit.c
src/lsm/lsm_worker.c

Notes for the log/ verbose calls: opening/renaming/removing a file isn't super frequent, so I've left them.
For LSM, I'm assuming tree switches are uncommon, while flushes and chunk checkpoints are common. I don't know this code at all, unfortunately.
Here's the full list of verbose calls I checked:
src/log/log.c:1001
src/log/log.c:1009
src/log/log.c:1015
src/log/log.c:1062
src/log/log.c:1411
src/log/log.c:1458
src/log/log.c:1462
src/log/log.c:1509
src/log/log.c:1536
src/log/log.c:1597
src/log/log.c:1620
src/log/log.c:1639
src/log/log.c:1704
src/log/log.c:1710
src/log/log.c:1717
src/log/log.c:1956
src/log/log.c:1972
src/log/log.c:2007
src/log/log.c:2138
src/log/log.c:2170
src/log/log.c:2189
src/log/log.c:2210
src/log/log.c:2377
src/log/log.c:2755
src/log/log.c:2801
src/log/log.c:301 …

WT-10057 Check log and LSM verbosity

---

src/history/hs_rec.c
src/txn/txn_rollback_to_stable.c
test/suite/test_rollback_to_stable06.py

In the case where we had an update chain inside an insert list that:
- contained only unstable updates, and
- was on a page that had been reconciled but not evicted since the new update chain was created
RTS would leave unstable updates in the history store as it didn't find any stable updates on the chain, and the key being rolled back was not present in the pages disk image.
This change tracks the oldest timestamp of an unstable update in the chain that is also in the history store. When no stable updates are found on-chain RTS will instead clean the history store using this unstable timestamp.
There is a preferred change in which `__rollback_to_stable_hs_final_pass` is now called for user triggered RTS and shutdown RTS, but issues were found when implementing this so additional work …

WT-9846 Use oldest unstable timestamp to clean history store when no stable updates are on chain

---

src/txn/txn.c
src/txn/txn_ckpt.c
src/txn/txn_recover.c
src/txn/txn_rollback_to_stable.c

For this, I'm assuming stuff that happens once per checkpoint isn't going to be too much logging. I'm also assuming RTS isn't something where we need to be sensitive about extra logging.
Here's the full list of verbose lines I checked as part of this PR:
src/txn/txn.c:1181
src/txn/txn.c:1188
src/txn/txn.c:1792
src/txn/txn.c:2432
src/txn/txn.c:2499
src/txn/txn.c:2503
src/txn/txn.c:2569
src/txn/txn.c:2573
src/txn/txn.c:2640
src/txn/txn.c:491
src/txn/txn.c:493
src/txn/txn.c:765
src/txn/txn.c:785
src/txn/txn_ckpt.c:109
src/txn/txn_ckpt.c:425
src/txn/txn_ckpt.c:560
src/txn/txn_ckpt.c:618
src/txn/txn_ckpt.c:626
src/txn/txn_ckpt.c:783
src/txn/txn_ckpt.c:80
src/txn/txn_recover.c:109
src/txn/txn_recover.c:403
src/txn/txn_recover.c:432
src/txn/txn_recover.c:590
src/txn/txn_recover.c:76 …

WT-10059 Check RTS and txn verbosity

---

test/evergreen.yml

…hat the complexity task runs per commit and the coverage report task occurs once every 7 days.

WT-10085 Updating code complexity batch time to run every commit.

---

test/format/format.sh

Not a bug that broke anything, but it was a little annoying going back over test results after it's run a couple of hundred times.

WT-10097 Fix test/format's live recording option flag generation

---

src/block/block_compact.c
src/evict/evict_lru.c
src/include/txn_inline.h
src/include/verbose.h

It became inconsistent with the other functions after we got debug2 and debug3.

WT-10090 Rename wt_verbose_debug -> wt_verbose_debug1

---

test/cppsuite/src/common/random_generator.cpp
test/cppsuite/src/common/random_generator.h
test/cppsuite/src/main/operation_configuration.cpp
test/cppsuite/src/main/thread_worker.cpp
test/cppsuite/src/main/thread_worker.h

Update enums to enum classes in cppsuite. This removes the need for default cases on switches as unhandled cases are now caught at compile time.

WT-9442 - Replace enums with enum classes in cppsuite

---

test/format/config.c
test/format/format.h

There's really three values a table can have for mirroring - explicit on, explicit off, and unspecified. If a table has it as explicitly on, `config_mirrors` works fine - we'll set `already_set` to true, hopefully pick a base mirror, and return. If a table leaves it unspecified, the code also works fine - `already_set` will be false, we'll fall out of the loop, see that `set_explicit` is false, and do the probability thing. 
If a table explicitly sets it to zero, however, the code is wrong - we won't ever hit the `if (NTV(tables[i], RUNS_MIRROR))` condition, so we fall out of the loop. But then `set_explicit` is true, and we'll skip the probability thing and turn it on. The core of the issue here seems to be a misunderstanding of `config_explicit`, which simply returns whether a config …

WT-10070 Don't mirror when tables turn off mirroring

---

dist/s_string.ok
src/schema/schema_drop.c

This assertion was firing on every run of `test_base04` but I didn't see a quick fix for it. Disabling this assertion to remove the CI-blocker. 
The full correction will take place in WT-10112

WT-10113 Disable assertion in __drop_tiered

---

test/evergreen.yml

`pygit2` has recently released version `1.11.0` which breaks our performance tests with `ImportError: libssl-9ad06800.so.1.1.1k`. Downgrade `pygit2` to `1.10.1` to resolve the CI-blocker.
There are other pip3 dependencies that don't have their versions locked, but this can be handled in WT-8567

WT-10115 Lock pygit2 to version 1.10.1

---

test/evergreen.yml

Changes made in this PR include:
- apply a new tag to the set of unit-test-long-bucket tasks, and add them to the `ubuntu2004` builder
- apply `patch_only: true` to all unit-test-long-bucket tasks, so that they are not triggered by commit builds
After this PR is merged, it is expected we are able to config commit-queue to pick the set of unit-test-long-bucket tasks.

WT-10063 Enable unit-test-long-bucket tasks in patch builds

---

test/evergreen/compatibility_test_for_releases.sh

`realloc_malloc` is a `debug_mode` configuration which we do not want to backport to older release versions, I am disabling this config in compatibility testing.

WT-10111 Disable realloc_malloc config in compatibility testing.

---

CMakeLists.txt
test/ctest_helpers.cmake

I've added cmake custom commands to the target test executables and wiredtiger shared library in order to generate dSYM bundles using the dsymutil on macOS. This provides a way to load the symbols previously missing in macOS core dumps from evergreen.

WT-9814 Generate dSYM bundles for macOS core dumps

---

bench/perf_run_py/perf_config.py
bench/perf_run_py/perf_run.py
bench/wtperf/wtperf.c
test/evergreen.yml

Add a function in `perf_run.py` that supports more stable results through increased runs and a limit on the duration of the test (useful for longer running tests). Added a build variant to support increased-accuracy perf runs.

WT-10037 Generalise performance test wrapper to work on all performance tests

---

cmake/configs/base.cmake
cmake/configs/wiredtiger_config.h.in
src/include/error.h
src/include/session.h
src/session/session_api.c
test/evergreen.yml
test/unittest/CMakeLists.txt
test/unittest/tests/test_assertions.cpp

This is a simple unit test framework for testing that `WT_ASSERT_ALWAYS` has fired without crashing the program under test. I've only made this change for `WT_ASSERT_ALWAYS` as the other `WT_ASSERT`s are still dependent on `HAVE_DIAGNOSTIC` and we plan to remove them as part of this project.
With this change when `HAVE_UNITTEST_ASSERTS` is true we'll remove the call to `__wt_abort` and instead track that the assert has fired and the message that would be printed. We can then check these fields in the unit test.

WT-10040 - Implement unit test that can call __wt_abort without crashing

---

test/evergreen.yml

In [WT-10148](https://jira.mongodb.org/browse/WT-10148) we ran into a Python test failure (connection lost). As the affected test is part of our pre-merge testing (i.e. commit-queue patch builds), we'd mitigate the test failures for now by moving the "unit-test-long-bucket04" Evergreen task onto a larger instance type (proved to be effective by a patch build).

WT-10155 Move unit-test-long-bucket04 onto a larger Evergreen distro

---

src/reconcile/rec_child.c

(cherry picked from commit 0fc80dd1e769b50f81227391436206d01ddd4aa1)

WT-10064 Don't evict internal pages with non-globally visible deleted pages for non standalone build (6.1 backport)

---

test/format/config.c

In a non-standalone build, we cannot write the fast truncate information to the disk as part of the checkpoint. This information is required to rollback any unstable fast truncate operation. To avoid this problem in the test, turn off the truncate operation when timestamp or prepare is enabled.

WT-10159 Disable truncate operation when prepare is enabled in non-stanadlone build

---

test/suite/test_cursor_random.py

test_cursor_random.py fails as there is the following output in stdout.txt
`[WT_VERB_GENERATION][NOTICE]: evict generation drain waited 1 minutes `
After looking at the core and the FTDC (more explanation on the ticket), it is clear that eviction is struggling with evicting the overflow items. This is because the system is running multiple tests in parallel and is under a lot of stress. Also, as mentioned in [WT-7187](https://jira.mongodb.org/browse/WT-7187) overflow items make eviction very slow, especially on macOS platforms.
That said, the easy solution is to simply ignore the output in the stdout file that matches the following pattern:
`evict generation drain waited `

WT-7492 Ignore the evict drain wait msg in stdout.txt for test_cursor_random

---

bench/perf_run_py/aggregate_perf_stat.py
test/evergreen.yml

- Add Evergreen tasks for each set of performance tests to aggregate all perf stats into a single file.
- Add a Python script that aggregates all perf stat JSON files into a single CSV file and uploads it.

WT-10038 Add aggregate functionality for perf stats

---

test/evergreen.yml

Tag the builder so that we can leverage the tag to disable the builder in periodic builds. 
Please note the "activate: false" setting has already been applied onto the builder, but that setting is not respected by periodic builds.

WT-10172 Tag RHEL PPC Evergreen builder on mongodb-6.1

---

bench/perf_run_py/perf_run.py
test/evergreen.yml

A couple of tweaks to fix the failures we're seeing in our project patch builds:
- Have `configure_for_extra_accuracy` return `arguments` rather than modify it so we're sure that the changes are sticking
- Move `configure_for_extra_accuracy` from `main` into `run_perf_tests`. When we're running tests with a batch file (via the `-bf` flag) this would overwrite the `run_time` value we set with `--improved_accuracy`
- Update the `wtarg` field in evergreen to fix a string parsing issue
- Remove some perf tests from the aggregate task. They were either disabled for the buildvariant (lsm) or unreliable (mongodb-large-oplog)

WT-10171 Fix perf_run's new improved_accuracy flag when used with batch files

---

test/cppsuite/src/main/thread_worker.h

This fixes the build with newer LLVM versions, where the compilation order seems to be different.

WT-10193 Include optional from thread_worker.h

---

lang/python/wiredtiger.i
test/suite/test_count01.py

Tested by hand that
```
count = self.session.count(self.uri)
```
works when the API returns `OK`, but because the skeleton API returns `WT_NOTFOUND` right now, it's not easily testable for now.

WT-10184 Update SWIG mapping for int64_t*

---

test/evergreen/print_stack_trace.py

When the `execfn` is missing, it is most likely that the core has been analyzed already.

WT-10187 Skip core analysis when execfn field is missing

---

src/btree/bt_curprev.c

Fixing a cut-and-paste error in `wt_btcur_prev()` that updated the `cursor_next_skip_*` statistics instead of the `cursor_prev_skip_*` statistics.

WT-10192 Fix bug in cursor_prev_skip statistics

---

dist/s_docs

It's currently buggy: https://github.com/doxygen/doxygen/issues/9552
This version results in the error message
```
s_all run of: "./s_docs" resulted in:
/home/ubuntu/dev/pm-3094/wt-clean/src/include/wiredtiger.in:4018: error: WT_COLLATOR::compare has @param documentation sections but no arguments (warning treated as error, aborting now)
```
I could probably allow anything from v1.9 except 1.9.5, but we have a whitelist mechanism already so it was simpler to use that. Let me know if you disagree with this call. I believe our CI is currently running v1.8.17, so that should be fine.

WT-10195 Disallow doxygen v1.9.5

---

bench/workgen/workgen.cxx

I tested the changes by replacing the key/value format to `u` in some of our existing files.
I also tested against https://github.com/wiredtiger/testy/pull/6 and it worked.

WT-10175 Update Workgen to work with the 'u' format

---

bench/perf_run_py/perf_run.py
test/evergreen.yml

Drop a bunch of the perf tests from our aggregate task due to high variance from run to run. I've also bumped runtime up to 4 as we're more likely to get stable results once the system has warmed up for a bit.
@clarissecheah I'm leaving `mongodb-secondary-apply` in for now, but we can drop it as part of WT-10039 if the mac build keeps playing up.

WT-10204 Reduce number of perf tests in aggregate-perf-tests

---

test/cppsuite/src/common/logger.cpp

Fixing this as part of fixing the apparent cpp stress test timeouts in evergreen.

WT-10076 Flush CppSuite logs so they are shown correctly in evergreen.

---

test/format/format.sh

WT-10144 Updating format.sh to check the timer if set during the resolve loop in case abort recovery take a long time.

WT-10144 Update format.sh to check timer for expiry in resolve loop

---

src/txn/txn_timestamp.c
test/suite/test_timestamp08.py

Querying the all_durable timestamp during the first transaction of a new instance of WT would incorrectly return the commit_timestamp of that transaction. This fixes that scenario and instead returns a 0 timestamp indicating that there is no all_durable timestamp before any transaction has been committed.

WT-10116 Return 0 timestamp for all_durable upon first open transaction

---

test/cppsuite/src/main/validator.cpp

Some of the cppsuite stress tests were timing out as a result of the logs not being properly flushed and validation taking a long time. Adding this extra log message once a collection is validated should help stop evergreen from timing out during the validation stage. If further timeouts persist we may need to consider increasing the timeout in evergreen.

WT-10080 Add a log after validating a collection in the cpp suite

---

test/evergreen.yml
test/evergreen/find_cmake.sh

Added a new variant `amazon2-arm64`
The new variant contains the same tests as `ubuntu2004-arm64`.
There are failing tests, tickets have been created to address them. Until then, they are disabled.

WT-9831 Add tests to new variant Amazon Linux 2

---

test/format/config.c

WT-9117 Restrict in memory rows count to 1 million if in memory was not explicit

WT-9117 Restrict in memory rows count to 1 million if in memory was not explicit

---

test/format/config.c

Revert WT-9117: Restrict in memory rows count to 1 million if in memory was not explicit (#8531)
This reverts commit 6fddc2ea2b9c07b3a0e7dbdb51f46d601ee32ca0.

WT-9117 Revert

---

src/btree/bt_cursor.c
src/btree/bt_delete.c
src/btree/bt_discard.c
src/btree/bt_page.c
src/btree/bt_split.c
src/btree/col_modify.c
src/btree/row_modify.c
src/history/hs_cursor.c
src/include/extern.h
src/reconcile/rec_col.c
src/rollback_to_stable/rts_btree.c
src/session/session_api.c
src/support/mtx_rw.c
src/txn/txn.c

Continuation of WT-10043. Now that WT_ASSERTs can run in release mode there are some variables requires by these asserts that should no longer be hidden behind `#ifdef HAVE_DIAGNOSTIC`. 
The one exception to this is the assertions of `__wt_hazard_check_assert`, these assertions are now hidden behind an `#ifdef` as they are only applicable when `HAVE_DIAGNOSTIC=1`.
This PR is currently targeting the WT-10043 branch so we can see only the WT-10044 diffs. Once WT-10043 is merged into pm-2897 this PR will immediately follow.

WT-10044 Remove HAVE_DIAGNOSTIC ifdefs that break WT_ASSERT

---

test/evergreen.yml

Sorry, the branch name comes from previous work. **It does not reflect the work that is being done here**.

WT-10212 Remove configure-combinations on AL2

---

bench/workgen/runner/compress_ratio.py
bench/workgen/runner/evict-btree-hs.py
bench/workgen/runner/example_prepare.py
bench/workgen/runner/example_simple.py
bench/workgen/runner/example_txn.py
bench/workgen/runner/insert_stress.py
bench/workgen/runner/insert_test.py
bench/workgen/runner/maintain_low_dirty_cache.py
bench/workgen/runner/many-dhandle-stress.py
bench/workgen/runner/multi_btree_heavy_stress.py
bench/workgen/runner/multiversion.py
bench/workgen/runner/prepare_stress.py
bench/workgen/runner/read_write_storms.py
bench/workgen/runner/read_write_sync_long.py
bench/workgen/runner/read_write_sync_short.py
bench/workgen/runner/small_btree.py
bench/workgen/runner/small_btree_reopen.py
bench/workgen/runner/split_stress.py
bench/workgen/wtperf.py

- Added an assertion when the `run` command is expected. We expect it to return `0`.
- Modified a few workloads to align with Python3 and work with the latest version of Workgen.

WT-10245 Check output of Workgen and Wtperf workloads

---

test/format/config.c

WT-9117 Restricting runs.rows to 1,000,000 when runs.in_memory is automatically enabled. Removing restriction on runs.rows when direct IO is enabled (as it most likely never used).

WT-9117 Restricting runs.rows to 1,000,000 when runs.in_memory is auto enabled

---

test/wt_hang_analyzer/wt_hang_analyzer.py

This change was split from SERVER-62995 as it touches a source file in the wiredtiger repository.
The plan is to merge this PR after SERVER-62995 is merged, and then vendor this change to mongo master via the daily WT release task.

WT-9966 Switch toolchain to v4 for WT hang analyzer

---

test/cppsuite/create_test.sh
test/wt_hang_analyzer/wt_hang_analyzer.py

Changed input validation to regex string match C++ Style 
Updated error message to 
`Invalid test name. Test name must match the regex '[a-zA-Z]+(_[0-9a-zA-Z]+)$'`

WT-9872 Perform input validation for create_test.sh

---

test/evergreen.yml

Enabling the tiered-storage-extensions-test after demonstrating that the S3 extension works on AL2 when compiling with the MongoDB v4 toolchain.

WT-10213 Enable tiered-storage-extensions-test on Amazon Linux 2

---

bench/workgen/runner/example_dynamic_tables.py
bench/workgen/workgen.cxx
bench/workgen/workgen.h
bench/workgen/workgen_int.h

This is reusing the work done in WT-10238 (https://github.com/wiredtiger/wiredtiger/pull/8573).
We are now:
- Using a reference counter when a table in Workgen is used
- Able to ask Workgen to prepare a table for deletion using the new Workgen API `remove_table`
- When this is the case, the table cannot be used by any other thread. However, the threads currently using the table can finish their job.
- A new API garbage_collection has been created so Workgen can delete the data associated with those tables when it is safe to do so. **This API only deletes the data in Workgen, the table will still be on disk and the WiredTiger API session:drop should be called on the table**
**Note: reviewing one commit at a time makes the review much easier.**

WT-10239 Implement dynamic table deletion in Workgen

---

src/btree/bt_discard.c
src/btree/bt_split.c
src/btree/col_modify.c
src/btree/row_modify.c
src/include/error.h
src/lsm/lsm_cursor.c
src/reconcile/rec_col.c
src/rollback_to_stable/rts_btree.c
src/session/session_api.c
src/support/generation.c
src/support/hazard.c
src/txn/txn.c

Two changes in this PR:
1. Change `WT_ASSERT` back to its original behaviour where it is enabled via compile flag `HAVE_DIAGNOSTIC` and not by the new runtime flag. Some calls to `WT_ASSERT` have been changed to `WT_ASSERT_ALWAYS` as part of this step to avoid `unused variable` errors. We could wrap these vars in `#ifdef HAVE_DIAGNOSTIC` again, but we'll just end up removing them again in the next ticket.
2. Update some `WT_ASSERT` calls to `WT_ASSERT_OPTIONAL`. These asserts are now runtime enable-able, but we don't want them running all the time (`ALWAYS`) as they call expensive subfunctions. 
The remaining `WT_ASSERT`s will be reviewed in later tickets to see if they should become `WT_ASSERT_ALWAYS`.
I'm also open to any better names for `WT_ASSERT_OPTIONAL`. The current situation is …

WT-10321 Introduce WT_ASSERT_OPTIONAL, keep WT_ASSERT behind compile flag

---

src/btree/bt_debug.c

Changed __wt_debug_page unreadact option to true.

WT-10292 Turn off redact option from test format when using wt verify

---

src/meta/meta_turtle.c
src/txn/txn_ckpt.c
src/txn/txn_recover.c

Cherry-picked from the 6.0 branch (c01e34c7a23abf8b0da9a7ef1ee2a7c5cfc1b7ae)
* WT-9926 Remove backup file after recovery checkpoint.
* Don't delete checkpoints during recovery from backup.
(cherry picked from commit ebdf18ec2ef5e700a56f36822d1afa19dd7f73f7)
Co-authored-by: sueloverso <sue@mongodb.com>
(cherry picked from commit c01e34c7a23abf8b0da9a7ef1ee2a7c5cfc1b7ae)

WT-9926 Remove backup file after recovery checkpoint. (#8316) (#8428) (v5.0 Backport)

---

src/include/btree_inline.h

Cherry-picked from the 5.0 backport (d9340610d5c44fc315912673d15203b25ce5a80b)
Co-authored-by: Ruby Chen <ruby.chen@mongodb.com>
(cherry picked from commit 68d75efac2541f9bbba05d03f7510f50cfa2a83d)
Co-authored-by: Alex Gorrod <alexander.gorrod@mongodb.com>
(cherry picked from commit 3ecab025d4c0a337fe80b6fe55538896c43c159e) (cherry picked from commit d9340610d5c44fc315912673d15203b25ce5a80b)

WT-9323 Fix a race tracking whether a tree has updates after a checkpoint (#8194) (#8228) (#8356) (v4.4 Backport)

---

src/os_common/os_alloc.c

- Added tmpp null check before memcpy as we shouldnt need to perform a memcpy if tmpp is NULL

WT-10142 Fix NULL pointer in realloc function

---

src/include/connection.h
src/include/schema.h
src/support/global.c

This run time flag is enabled in WiredTiger standalone mode and it is used to protect any metadata changes slipping into the MongoDB release before the feature gets stable.

WT-10375 union tables run time process flag configuration

---

test/evergreen.yml

Mongodb revision [d824f5a6e46](https://github.com/mongodb/mongo/commit/d824f5a6e46ac74967e38e015bc46858c235a788) in triggered a toolchain test failure in the wiredtiger `many-collection-test`. The test was not using the mongodb toolchain when compiling mongodb, and in particular using a python version (3.8) with a known issue having the same symptoms as the test failure. This change updates `evergreen.yml` to use the current mongodb toolchain (v4) when compiling mongodb.

WT-10410 Update mongodb compile to use v4 toolchain in evergreen.yml

---

test/evergreen/compatibility_test_for_releases.sh

WT-10444. Disabling debug log retention and stress checkpoints for compatibility tests to ensure they complete in the expected time.

WT-10444. Disabling debug log retention and stress checkpoints for compatibility tests

---

ext/storage_sources/s3_store/test/test_s3_connection.cpp
test/evergreen.yml
test/suite/helper_tiered.py

Use the evergreen feature include_expansions_in_env to include the access/secret key in the env and then update our code to use these env vars.

WT-8839 Hide AWS creds when running tests in evergreen

---

dist/s_string.ok
src/os_posix/os_fs.c
test/evergreen.yml

Updated evergreen yaml to use RHEL8 instead of Ubuntu 18.04 on PPC.  Reducing the concurrency for RHEL8 PPC tests to a quarter of vCPUs. Added retry (WT_SYSCALL_RETRY) for pread which helps on RHEL8 PPC.
(cherry picked from commit b3719943c9d9790b26bbdcf4aabe95801c1de804)

WT-8981 Enable evergreen testing for RHEL8 on PPC (#8308) (BACKPORT)

---

test/evergreen.yml

These tasks were used on the PM-2897 project branch, but should not be merged into develop as they will pollute out existing Atlas chart results and aren't useful to run automatically. Code changes made to support improved accuracy are kept, but the evergreen changes are dropped.

WT-10181 Remove additional accuracy evergreen tasks

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_cursor.c
src/btree/bt_random.c
src/cursor/cur_hs.c
src/include/cursor.h
src/include/cursor_inline.h

Perf tests indicate a ~5% slowdown on some tests which stems from some very frequent calls to `EXTRA_DIAGNOSTICS_ENABLED` in `__wt_btcur_next_prefix` (among others). 
As removing this check touches `__wt_cursor_key_order_check` I've also removed runtime toggling from the full set of coupled functions: `__cursor_key_order_check_col`, `__cursor_key_order_check_row`,  `__wt_cursor_key_order_init`, `__wt_cursor_key_order_reset`, `__wt_btcur_open`,  `__wt_btcur_close`.
The changes were made by checking out the code from prior to WT-10383, so you can treat this a partial revert of the WT-10383 changes. Behaviour is now back to what it was at the start of the project for these specific functions.

WT-10440 Change out of order checks to remove runtime toggle

---

test/checkpoint/checkpointer.c
test/csuite/schema_abort/main.c
test/utility/test_util.h
test/utility/tiered.c

Coverity warning: Change the type of `seconds` in `testutil_tiered_sleep` from `uint32_t` to `uint64_t` to avoid overflow.
This was pretty harmless - we'd only hit this if we decided to write a test where tiered needs to sleep for over an hour and all current calls to `testutil_tiered_sleep` are capped at a 5 second wait.
All the same, the type has been updated.

WT-10107 Fix potential overflow in testutil_tiered_sleep

---

src/tiered/tiered_work.c

Move break statement inside of if branch so we only break from our search when pending flush work is found.
I think this was caused by having the original code 
```c
if (FLD_ISSET(entry->type, WT_TIERED_WORK_FLUSH))
found = true;
break;
```
and `s_all` silently re-indenting without providing giving us a `misleading-indentation` warning. I'll create a separate ticket to have `s_all` detect this in future.

WT-9685 Don't exit loop early in __wt_tiered_flush_work_wait

---

bench/workgen/runner/example_prepare.py
bench/workgen/runner/prepare_stress.py

Wrapped group of operations to create transactions using `op_group_transaction`.
Read the comments updated in the jira ticket [WT-10243](https://jira.mongodb.org/browse/WT-10243) to understand the reason for this change.

WT-10243 Failure in example_prepare.py and prepare_stress.py due to unexpected timestamp usage

---

test/evergreen.yml
test/suite/test_truncate20.py

Changes include:
- add a new bucket to the existing unit-test-bucket tasks to offload some tests.
- add a new bucket to the existing unit-test-long-bucket tasks to match the above change.
- set `test_truncate20.py` to a long test (runs over 10mins), so that it's not triggered in PR builds. 
With the above changes, the longest-running task in a PR patch build (unit-test-bucket02) was below 25 mins.

WT-9759 Bring down longest-running Pull Request task duration to below 25mins

---

dist/comment_style.py
dist/s_export
dist/s_export.list
test/evergreen/evg_cfg.py

This fixes a handful of false positives when running s_all:
- When run in fast mode `comment_style.py` only checks files that have been modified since the branch diverged from develop. When no files have changed this list is empty which the script script didn't handle.
- When compiled with `HAVE_UNITTEST=1` unit test functions (prefixed with `__ut`) are exposed so we can perform testing on internal functions. `s_export` reports this as an error so add the unit test functions to the whitelist.
- Finally `evg_cfg.py` was looking in our build directories and reporting an error that the third party dependency `catch2` didn't have any associated evergreen tests. This isn't required so exclude the build directory from checking

WT-10503 Fix false positives in s_all

---

test/evergreen.yml

Enabled the `format-stress-pull-request-test` in `evergreen.yml` for all testing except on the UBSan build variant, where there is a known failure (see Jira ticket for details). 
Note that this test wasn't disabled "correctly". It was creating an EC2 instance for every PR over multiple build variants (for the past six months!) only to run a compile and exit. **Please disable tests at the build variant level!**

WT-10507 Enable format-stress-pull-request-test in evergreen.yml 

---

dist/s_string.ok
src/docs/command-line.dox
src/docs/spell.ok
src/os_common/os_getopt.c
src/utilities/util.h
src/utilities/util_alter.c
src/utilities/util_backup.c
src/utilities/util_compact.c
src/utilities/util_create.c
src/utilities/util_downgrade.c
src/utilities/util_drop.c
src/utilities/util_dump.c
src/utilities/util_list.c
src/utilities/util_load.c
src/utilities/util_loadtext.c
src/utilities/util_main.c
src/utilities/util_printlog.c
src/utilities/util_read.c
src/utilities/util_rename.c
src/utilities/util_salvage.c
src/utilities/util_stat.c
src/utilities/util_truncate.c
src/utilities/util_upgrade.c
src/utilities/util_verify.c
src/utilities/util_write.c
test/suite/test_util22.py

The PR adds the `-?` option to the `wt` commands. When executed with the `-?` option, the command exits with exit code 0, because this is not an error, but if there is an invalid argument, it still exits with an error code.
To that extent, I had to modify `__wt_getopt` to use a different exit code than `'?'` on error, because it would be otherwise impossible to distinguish between an invalid option and the `-?` command-line argument. As this is a non-standard behavior, the caller has to enable it through a global variable. I was inspired to do it this way, as we already added the ability to reset option parsing using a global variable.
I also used this as an opportunity to correct the documentation. Please check especially that the `-S` option is used correctly in the paragraph below the …

WT-9612 Add the -? option to the wt commands and fix the documentation.

---

src/history/hs_rec.c
src/include/timestamp_inline.h
test/suite/test_rollback_to_stable39.py

This bug was one of the cases where the data store and the history store may contain the same value. In this case, skip inserting the same value into the history store again. The fix is the time window of the inserting record and the history store record are compared to make sure that the same record is not being inserted again.
(cherry picked from commit f45ebf82dba6e0d88edccb6c3047a717669b4562) (cherry picked from commit bfc6fc15de632da2000143bcce3a23141cfc6a2c)
* Updated the test case to support backward compatibility
(cherry picked from commit 2a44acce45238f86124a2ee95e63e45791fb7304)

WT-9763 Return EBUSY if the time window of inserting record does not match with history store time window (v4.4 backport) 

---

dist/s_all
test/evergreen/evg_cfg.py

A small cleanup to `s_all` that fixes an issue where we would ignore the failure of our `s_evergreen` script.
When checking the result of our scripts that run in parallel we get the name of a failing script by grepping the name of the output file it produced (`$LOCAL_NAME`) against the list of parallel scripts in `$COMMANDS`.
The problem occurs when `s_evergreen` reports a problem, but the resulting grep of `LOCAL_NAME` matches against both the `s_evergreen` command as well as the `s_evergreen_validate` command. This results in an incorrect `$FAILED_CMD` value being passed into `errchk` which breaks the `# If the test was skipped, ignore the failure.` and suppresses the error.
To fix this we now match against the full name of the command (`[^\w]` ensures there are no further characters …

WT-10524 Match on full script name in s_all

---

dist/s_string.ok
src/docs/spell.ok
src/include/misc.h
src/os_common/os_getopt.c
src/utilities/util.h
src/utilities/util_backup.c

The PR cleans up a few issues that were raised after #8721 was merged.
The PR does not yet add `-?` to all of the examples in the documentation or in `usage()`, as for example, calling `wt -r -? backup` doesn't make sense. If we'd like, we can still add it to the synopsis of `wt` when it is called by itself, which would be easy to do in the documentation, but it would require a special case `usage()` which I was hoping to avoid. @sueloverso, please let me know if you would like me to do that.

WT-10517 Clean up command-line argument parsing for the wt utility

---

bench/workgen/workgen.cpp

This change adds signal handler functionality to `workgen`. This allows us to gracefully terminate `workgen` and the user to close the connection in the python runner script, thus ensuring a clean shutdown of `wiredtiger`, when performing a `Ctrl-C` from the keyboard or when running `workgen` under a `systemd` service. The registered signals to be handled by the signal handler are `SIGINT` and `SIGTERM`, as specified in the `WorkloadRunner::run_all` function.

WT-10532 Add signal handler to Workgen

---

src/cursor/cur_metadata.c
src/include/extern.h
src/include/schema.h
src/schema/schema_create.c
src/schema/schema_open.c
test/suite/test_tiered18.py

To support tiered storage shared, we need to split the current tiered storage table into two internal tables to track the active and shared data across the cluster.
These two internal URIs that are created are referenced using two column groups with extensions of active and shared from a single tablename.

WT-10378 Allow creating active and shared column groups

---

CMakeLists.txt
src/docs/build-windows.dox

Changes in this PR include:
- Fix to make Windows CMake builds compatible with systems that have unset `PROCESSOR_ARCHITECTURE` env variable
- Fix docs to git clone with https, and use "-A x64" to make builds work on 64-bit Windows systems. 
Changes has been verified on a Windows spawn host (distro `windows-64-vs2017-small`) with a successful CMake compilation and installation.

WT-10526 Fix CMake build errors and docs on Window system

---

src/btree/row_srch.c
src/include/serial.i

(cherry picked from commit 3687d84457c5468542645aff23930a2a248a16ed)

WT-10461 Fix key out of order in skip list on weakly ordered architecture (#8757) (v4.2 backport)

---

test/evergreen.yml

Disable the `compile-clang` task in Evergreen for now, as it kept failing and affected PR testing. 
We'll re-enable the task once the package missing issue on the Evergreen distro is addressed, using WT-10595.

WT-10586 Disable compile-clang task in Evergreen

---

lang/python/wiredtiger.i
src/include/txn.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/session/session_api.c
src/txn/txn.c
test/suite/test_txn27.py

* Adding a Python test for WT_SESSION.get_rollback_reason().
* Shifting to using #defines for rollback messages so they are less likely to be modified freely.
Co-authored-by: Keith Bostic <keith.bostic@mongodb.com>
Co-authored-by: Luke Pearson <luke.pearson@mongodb.com>
(cherry picked from commit 44f59f255cd2894489339ffe9f3c853ba7e5117e)

WT-8290 Adding a new API to the session to return the rollback reason. (v5.0 backport) (#7369)

---

test/evergreen.yml

As the image of the problematic distro has been reverted to a working version, let's re-enable the task in Evergreen.

WT-10595 Re-enable compile-clang task in Evergreen

---

test/evergreen.yml

Temporarily reduce the concurrency level (and cache pressure) for the macOS unit tests to avoid hitting repeated failures addressed in WT-9575. It's expected this fix gets reverted as part of WT-9575.

WT-10589 Halve the number of concurrent jobs for macOS unit tests

---

dist/api_data.py
dist/stat_data.py
src/config/config_def.c
src/conn/conn_api.c
src/conn/conn_log.c
src/include/connection.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
src/txn/txn_ckpt.c
test/suite/test_rollback_to_stable35.py

The checkpoint may include the updates from a recent transactions due to some parallel eviction activity. Ensure that all the log writes that are performed in parallel are flushed to disk before the metadata gets checkpointed to ensure that all the log records are written to the disk before the checkpoint becomes stable.
(cherry picked from commit e41ecd207030991a3c79a27ba39e35025f2e8379)
(cherry picked from commit 40b4e65dcb917d8982ed3435198c243f295df7ec)

WT-9251 Perform log flush before the metadata checkpoint (v4.4 backport)

---

cmake/third_party/aws_sdk.cmake
test/evergreen/find_cmake.sh

This does a few things:
1. Clean up some minor whitespace issues in the AWS CMake file
2. Updates the AWS SDK version to a version that no longer uses curl in a deprecated way (this was the original cause of the build failure - some systems got a newer libcurl and starting throwing warnings while building)
3. Looks for CMake/CTest in the Mongo toolchain v4 directory, since the new AWS SDK version needs CMake >= 3.13, which is newer than some of the system-wide installations that `find_cmake.sh` was getting.

WT-10597 Fix tiered storage extensions test

---

src/evict/evict_page.c
src/include/btmem.h

WT-9939 Added entering split generation on eviction to prevent parent from being freed after split.

WT-9939 Enter split generation on eviction to prevent split parent free to early

---

test/evergreen/compatibility_test_for_releases.sh

See the details described in [WT-10594](https://jira.mongodb.org/browse/WT-10594), `cursor_reposition` is not supported in older releases.

WT-10594 Disable cursor_reposition in test/format for older releases

---

bench/workgen/workgen.cpp
bench/workgen/workgen.h
bench/workgen/workgen_int.h

This PR adds mirror table functionality to workgen for dynamic tables. Tables created by the `Table()` class are not affected. I used the `tools/wt_cmp_uri` script to validate mirrored content (thanks @ddanderson!!)
Changes include:
* Added new members to the `TableRuntime` to indicate if a table is a base table or a mirror.
* Added a boolean to the `app_metadata` indicating if the table is a base or mirror.
* Added the mirror table name to the `app_metadata` if the table is mirrored.
* Updated the dynamic table create and drop to operate on mirror table pairs.
* Moved random table selection out of `op_run` and into a new `op_run_prepare` function so that (non-transaction) mirrored table operations could be wrapped in a transaction.
* Removed the `force` config setting from the …

WT-10240 Implement mirrored dynamic tables in workgen

---

src/reconcile/rec_visibility.c

(cherry picked from commit 00a2f853db0321cd2c283b14a520163452e5b0c0)

WT-10449 Do not save update chain when there are no updates to be written to the history store (6.3 backport)

---

lang/python/setup_pip.py
test/suite/test_prepare21.py
test/suite/test_rollback_to_stable32.py
test/suite/test_rollback_to_stable34.py
test/suite/test_rollback_to_stable35.py
test/suite/test_rollback_to_stable36.py
test/suite/test_rollback_to_stable37.py
test/suite/test_rollback_to_stable40.py
test/suite/test_truncate09.py
test/suite/test_truncate13.py
test/suite/test_truncate16.py
test/suite/test_truncate17.py
test/suite/test_truncate18.py
test/suite/test_txn13.py
test/suite/test_txn16.py
test/suite/test_txn18.py
test/suite/test_txn19.py
test/suite/test_txn22.py

The changes remove the redefinition of a function to simulate a crash since there is one that already exists as a helper function.

WT-10635 Remove duplicate Python crash code

---

dist/s_string.ok

I should have rerun `s_string -r` locally on the other branch after pulling to current develop. One minor change when the new evergreen script ran.

WT-10649 Run s_string -r locally.

---

test/suite/test_cursor_random.py

test_cursor_random started failing again on the macOS host after WT-10197 changed the warning message for eviction taking more than 1 minute. Not all the BFGs are linked to the ticket, there are others that appear in the logs of the other macOS failures. The test was initially failing on macOS due to stress on the host from running many tests concurrently. The original fix in WT-7492 was to ignore the warning as the expected output however that message is now outdated. I've fixed the test to reflect the new warning message.
In the WT-7492 it was discussed whether we should check for the masOS platform when ignoring the output. I've included it here but I'm not sure whether to keep that check.

WT-10380 Fix expected warning output in test_cursor_random

---

src/rollback_to_stable/rts_history.c
test/suite/test_rollback_to_stable42.py
test/suite/wttest.py

Of the four scenarios in the ticket:
1. We don't want a test that runs long enough to trigger this.
2. This was being tested, but not by an RTS test.
3. This was also being tested, but the logging was done under the wrong subsystem, so fix it.
4. This is almost all of the PR. It needed some supporting infra in `wttest.py`, in particular the idea of a custom log validator and `ignoreTeardownLogs`. This latter part seems a little hacky to me, but I'm not sure how to improve it - perhaps a getter/setter? Feedback welcome here.
The other possibly-controversial part is the lack of Windows support - we delete the file while WiredTiger has it open, and this doesn't work nicely with the Windows model of "only one process opens the file".

WT-10276 Improve RTS test coverage

---

src/docs/durability-checkpoint.dox
src/session/session_dhandle.c
test/suite/test_checkpoint01.py

We are disallowing the use of reserved checkpoint names when opening a checkpoint cursor.
A checkpoint cursor can be opened using a named checkpoint or `WiredTigerCheckpoint`. However, any name that has "WiredTigerCheckpoint" as a prefix is not allowed.
The same behaviour already exists when naming a checkpoint through the `session.checkpoint()` API, there is existing testing to check this in `test_checkpoint01.py`. This test was extended to cover invalid scenarios when opening a checkpoint cursor.

WT-10637 Prevent the use of reserved checkpoint names for checkpoint cursors

---

dist/s_all
dist/s_string
dist/s_string.ok

A lot of program names have been added to the aspell dictionary between versions `0.60.7-20110707` and `0.60.8`, resulting in words such as `MongoDB` that are considered typos in older versions and ok in new versions.
If we rebuild the `s_string.ok` whitelist using a newer version of aspell words such as `MongoDB` are removed from the whitelist - no longer being considered typos to ignore - but then older of versions of aspell report these as errors due to absence from the whitelist.
This change ensures that the relevant words are retained in the whitelist even when rebuilding with newer versions of aspell.

WT-10676 Retain program names when rebuilding s_string.ok

---

dist/s_all

When a script called by `s_all` fails it writes output to an appropriately named `__s_all_tmp_*` file in the dist folder. Previously the script was iterating through all created output files, then grepping against the contents of the `COMMANDS` variable to find the which check had produced the output file.
This grep was proving troublesome as it was either overly lenient (matching the file `s_evergreen` against the command populating `s_evergreen_validate`), or too strict and not finding the correct line in `COMMANDS`.
Rather than iterating over created output files and finding the correct check in `COMMANDS` I've flipped the logic to iterate through all checks in `COMMANDS` and finding which ones have produced an output file. This avoids the `evergreen`/`evergreen_validate` issue …

WT-10643 Fix s_all not reporting name of failing checks

---

test/csuite/schema_abort/main.c
test/csuite/timestamp_abort/main.c

The fix ensures that the `bucket` directory gets created in the right place, so that the `dir_store` plugin then finds it in the right place. The original ticket was for `schema_abort`, but as `timestamp_abort` has the same issue, this PR fixes it for it as well.
Here is the output from running the tests manually after the fix (some lines are omitted for brevity):
```
wt-10674-schema-abort-bucket-dir$ build/test/csuite/schema_abort/test_schema_abort -PT -T 5 -t 10 -h WT_TEST0
[4/4] cd /home/peter.macko/Projects/wt-10674-schema...4-schema-abort-bucket-dir/test/ctest_dir_sync.cmake
Running test command: build/test/csuite/schema_abort/test_schema_abort -PT -T 5 -t 10 -h WT_TEST0 
Parent: compatibility: false, in-mem log sync: false, timestamp in use: true, tiered in use: true
Parent: Create …
```

WT-10674 Fix the location of the "bucket" directory in schema_abort and timestamp_abort

---

test/suite/test_hs20.py

Applying the same fix as WT-10380 for test_hs20. This warning only occurs when there are many tests running in parallel putting a large amount of stress on the system. See the WT-10380 PR (#8850) or the tickets for more information.

WT-10432 Fix expected warning output for test_hs20 on macos

---

src/btree/bt_discard.c
src/include/btmem.h
src/include/btree_inline.h
src/include/extern.h
src/reconcile/rec_write.c

WT-10471. Adding flags for page modify to catch paths trying to make unsupported changes while reconciling.

WT-10471 Adding diagnostics for page_state updates when reconciling

---

ext/storage_sources/azure_store/azure_connection.cpp
ext/storage_sources/azure_store/test/test_azure_connection.cpp
ext/storage_sources/gcp_store/gcp_connection.cpp
test/suite/test_tiered19.py

Reverts wiredtiger/wiredtiger#8878

Revert "WT-10692 Strip away prefix when listing objects for both providers"

---

cmake/third_party/lz4.cmake
cmake/third_party/snappy.cmake
cmake/third_party/zlib.cmake
cmake/third_party/zstd.cmake

Add `IMPORTED_IMPLIB` property for imported `SHARED` wt::\<compressor\> libraries.
On Windows, `find_library()` always finds a .lib(or .dll.a) file. The `IMPORTED_IMPLIB` should be set to the .lib part of a DLL.
Since `IMPORTED_LOCATION` is needed on non-Windows and is optional on Windows, and `IMPORTED_IMPLIB` is optional on non-Windows and is needed on Windows, simply setting both of them to `${HAVE_LIB<compressor>}` will work.
Also, I notice that other third-party libraries(like sodium and memkind) are also imported SHARED but only specify `IMPORTED_LOCATION`. I'm not sure if I need to modify them by the way, since I don't use them and this ticket is related to builtin compressors.

WT-10661 Specify IMPORTED_IMPLIB for builtin compressors on Windows 

---

test/csuite/schema_abort/main.c

WT-10488 Added sleep to worker thread loop to give all threads a chance to progress and move the timestamp forward. Increased the max time to set the stable timestamp before first checkpoint.

WT-10488 Updated how schema abort sets the stable ts to make it reliable 

---

test/format/format_timestamp.c
test/format/ops.c

Also, fix timestamp thread so that oldest ts is always less than stable ts.

WT-10672 No special handling for predictable replay needed when read timestamps become invalid in test/format

---

src/docs/command-line.dox

Added the missing `m` and `S` options.

WT-10712 Add missing args to the wt util doc

---

cmake/configs/base.cmake

Have clang and gcc emit debug info for macros when we compile with `HAVE_DIAGNOSTIC=1`. This allows us to use macros inside gdb:
```
(gdb) p S2C(session)
$1 = (WT_CONNECTION_IMPL *) 0x4a9280
```

WT-10710 Emit macro debug information in diagnostic builds

---

src/session/session_dhandle.c
test/suite/test_checkpoint29.py

When closing, the bulk cursor performs a single-file checkpoint (different from a system-wide checkpoint which tries to operate on all the files present in the database). While the single-file checkpoint is required when the bulk operations are done, it creates inconsistencies that block the checkpoint cursor to be opened on that file. This eventually leads to a hang with the current code.
When this scenario is detected, the error code `WT_NOTFOUND` is returned to the application.
_Note: A long-term solution is described in [WT-10715](https://jira.mongodb.org/browse/WT-10715)._

WT-10545 Avoid hanging when opening a checkpoint cursor after bulk operations

---

dist/s_string.ok
src/docs/command-line.dox
src/utilities/util_dump.c
test/suite/test_dump01.py
test/suite/test_dump02.py
test/test_coverage.md

The changes introduce two new options for the `dump` command:
```
./wt dump -k "key0" <wt_file>
./wt dump -k "key0" -n <wt_file>
```

WT-10709 Update the WT util dump to perform a search on a key

---

dist/s_string.ok
src/docs/command-line.dox
src/utilities/util_dump.c
test/suite/test_dump02.py
test/test_coverage.md

The changes introduce two new options for the dump command:
```
./wt dump -l "key0" <wt_file>
./wt dump -u "key0" <wt_file>
```

WT-10682 Update the WT util dump to work on a range of keys

---

test/format/ops.c

Make sure `trace_op`s calls print `tinfo->key` data as well as `tinfo->keyno` in test/format.

WT-10733 Print out full key in test format ops traces

---

src/utilities/util_write.c
test/suite/test_util12.py

Now we explicitly set the `overwrite` cursor option to `false` when `-o` is not given to the `write` command. The same change was done for the `append` cursor option.
The relevant test was updated.

WT-10730 Fix the overwrite/append options for the util write command

---

dist/s_string.ok
src/docs/command-line.dox
src/utilities/util_dump.c

When the -e option is given to the dump command, it is possible to go through the file in an interactive fashion:
```
$ ./wt dump -e file:test_dump.wt
**************************
Explore mode for file:test_dump.wt.
**************************
Enter 'h' for help, 'q' to exit.
```

WT-10727 Make the util dump command interactive

---

src/block/block_ckpt.c

@ddanderson & @sueloverso, the ticket has a explanation of this change. 
The PR also includes some additional comments and ASSERTS.
This should be safe because the added functionality -- reseting the extent lists -- only happens when the block handle and the checkpoint cookie have different objectIDs, which can only happen in a tiered table. So this shouldn't other table types.

WT-10763 Don't load the wrong extent lists in __wt_block_checkpoint_load

---

test/evergreen.yml

Remove the `unit-test` task from 2 x Evergreen builders:
- `! Ubuntu 20.04` - covered by `unit-test-bucketxx` tasks
- `RHEL 8.0` - covered by `unit-test-long` task

WT-10762 Remove redundant unit-test task from a few Evergreen builders

---

src/history/hs_rec.c
test/suite/test_hs32.py

(cherry picked from commit de4e9ae0b5c52c680ba9a86cb62b621f8f92e7c2)

WT-10536 Fix statistic check cache_hs_key_truncate_onpage_removal in test_hs32.py (#8771) (v6.3 backport)

---

test/cppsuite/tests/reverse_split.cpp

WT-10706 Updated reverse_split test to reset cursor used to locate the start key of truncate prior to blocking to prevent pinning content in the cache.

WT-10706 Updated reverse_split test to reset cursor more often

---

src/btree/bt_curnext.c
src/btree/bt_cursor.c
src/include/cursor.h

(cherry picked from commit fa1ea9f917c56947c5ca22185285d29f713e6401)

WT-10585 Record the location of the last key to help debug key out of order (6.3 backport) (#8793)

---

src/history/hs_rec.c
src/rollback_to_stable/rts.c
src/rollback_to_stable/rts_btree.c
src/rollback_to_stable/rts_btree_walk.c
test/suite/test_rollback_to_stable04.py
test/suite/test_rollback_to_stable06.py

The suggested changes are taken from [here](https://jira.mongodb.org/browse/WT-10017?filter=-1) and modified to fit the current codebase. 
Additional testing changes were added.

WT-10017 Remove the unstable historical versions at the end of rollback to stable

---

src/txn/txn_ckpt.c
test/suite/test_checkpoint01.py

When a checkpoint is marked for deletion while still in use, we should add the name of the checkpoint to the error for a better debugging experience.

WT-10847 Add the checkpoint name to the error

---

test/suite/test_checkpoint01.py

- The original symptom of this ticket has since gone away, so the scope of this ticket was reduced to removing the skip hook annotation.
- A new FIXME ticket has been created to fix the skip tiered hook that is still resulting in an error.

WT-9902 Fix python test test_checkpoint01.test_checkpoint_target with timestamps

---

test/evergreen.yml

Discussed in office hours and agreed this is the best approach to reduce disk space usage. 50 ops tracing logs should be enough to cover majority of cases.

WT-10620 Reducing default test format ops tracing in evergreen

---

bench/workgen/workgen.cpp
bench/workgen/workgen.h
bench/workgen/workgen_int.h

This PR adds functionality to workgen so that different tables can be assigned to a single operation that is shared among threads.

WT-10825 Allow shared operations to use different tables in Workgen

---

src/btree/bt_vrfy_dsk.c
src/btree/row_modify.c

The usage of these variables are removed in earlier commits but missed to remove the variables leads to the compilation errors.

WT-10879 Fix compilation errors of unused variables in mac os 13.3

---

dist/s_string.ok
src/os_posix/os_fs.c
test/evergreen.yml

(cherry picked from commit de2888df11ef8cdfa9b4c2e8ec76f1b4a64a346b)
* WT-8981 Enable evergreen testing for RHEL8 on PPC (#8308) (BACKPORT) (#8626)
* WT-8981 Enable evergreen testing for RHEL8 on PPC (#8308)
Updated evergreen yaml to use RHEL8 instead of Ubuntu 18.04 on PPC.  Reducing the concurrency for RHEL8 PPC tests to a quarter of vCPUs. Added retry (WT_SYSCALL_RETRY) for pread which helps on RHEL8 PPC.
(cherry picked from commit b3719943c9d9790b26bbdcf4aabe95801c1de804)
Co-authored-by: Mick Graham <99703363+mickgraham-mongodb@users.noreply.github.com>
(cherry picked from commit 4dff67dd815aeaecb3f2987afa9bb63766b8c888)
---------
(cherry picked from commit ad583b158e9ccb035d29c1efaa7bce4c6907851b)

WT-8981 Enable evergreen testing for RHEL8 on PPC (v4.4 backport) 

---

src/block_cache/block_mgr.c
src/block_cache/block_tier.c
src/include/extern.h

Refactor `__wt_blkcache_get_handle()` so that it doesn't hold the handle array lock while opening a block handle. This makes error handling a bit more complicated, but avoids holding the lock across an operation that is likely to be slow.

WT-10888 Don't hold block handle arrray lock when opening a handle.

---

test/cppsuite/configs/hs_cleanup_stress.txt
test/cppsuite/configs/operations_test_stress.txt
test/evergreen.yml

This upsizes the vm instance for testing, as the small instance runs out of disk space.

WT-10447 Upgrade instance for cppsuite tests

---

test/suite/test_backup29.py

@pmacko86  a few more cleanup items I added to the test. Comparing the bitmap for the original table, better naming.
This originated yesterday when I added up to 4 tables to test opening and modifying at different times. Having that many tables does not add to the test and made it cluttered but the naming and function changes were worth keeping.

WT-10920 Cleanup of test_backup29.py. Compare bitmap in a function.

---

test/evergreen.yml

WT-10487 Fixed V4 toolchain path env for many-collection-test. Updated many-collection-test to use env var for the username/password to allow for better debugging on failures.
(cherry picked from commit 16242574607a2837de1a1f1192871160353479fc)

WT-10487 Fixed V4 toolchain path for many-collection-test (#8703) (v6.0 backport)

---

src/btree/bt_compact.c
test/csuite/wt10897_compact_quick_interrupt/main.c

WT-10928 Compact should print "skipping compaction" only when it is actually skipped

---

test/evergreen.yml

On Ubuntu 2004, post-merge Python unit tests are run on in the single Evergreen task 'unit-test-extra-long', which is executed on ubuntu2004-large instances.
However, PR/patch testing for the Python unit tests are run in a series of bucket tasks (named unit-test-long-bucket00 to unit-test-long-bucket11) on ubuntu2004-test (aka ubuntu2004-small) instances. Some test fail on the small instances. For example test_txn13.test_txn13.test_large_values(integer-row.4gb).
This change will fix this issue by changing the PR/patch Python unit tests to run on ubuntu2004-large instances.

WT-10935 Change patch build Python unit tests to run on ubuntu2004-large

---

test/suite/rollback_to_stable_util.py
test/suite/wttest.py

The main problem here is that the test suite needs `self.fail` to be called for the test to be registered as a failure - setting `passed` is not adequate. However, this still needs to be done after the `os.chdir` call in `tearDown`, otherwise that call doesn't run and future tests get into a messed-up state where they run from another test's directory.
This also fixes the verifier's `stderr` not getting echoed. This is a nice-to-have since it was already getting saved in the log, but now it'll be clearer when looking at Evergreen.

WT-10913 Python teardown failures not reflected in test suite return value

---

test/utility/misc.c

On MacOS 11, the cp command doesn't support the -l option to link rather than copy files. This change stops testutil_copy_data_opt() from trying to link files on Macs.

WT-10914 Fix make-check-test on MacOS 11

---

src/include/txn_inline.h
src/txn/txn.c
src/txn/txn_rollback_to_stable.c
test/suite/test_checkpoint_snapshot05.py

Increasing the oldest ID during the recovery can lead to a scenario where the eviction threads that operation in recovery can check the global visibility according to the current oldest ID and it may go wrong until the recovery rollback to stable is finished.
Also, let all the history store records return to the rollback to stable irrespective of global visibility.
(cherry picked from commit 945c520f026ec0cdfa53703be0d48a274340a610)
Note: This is backported along with WT-8702

WT-8570 Do not increase oldest ID during recovery (#7438) (5.0 backport)

---

test/syscall/wt2336_base/base.run

WT-10777 added code to set thread names on WiredTiger internal threads. The pthreads library implements this by opening `/proc/self/task/<TID>/comm`, where `<TID>` is the threadID. As a result these operations get picked up by our `syscall` test. This change updates the template used to match system calls to it ignores these pthread-based operations.

WT-10940 Ignore system calls to set thread name in test/syscall.

---

cmake/configs/base.cmake
src/block/block_ext.c
src/btree/bt_page.c
src/btree/col_modify.c
src/btree/row_modify.c
src/reconcile/rec_track.c
src/reconcile/rec_visibility.c
src/schema/schema_project.c
test/unittest/tests/test_reconciliation_tracking.cpp

* Initialize variables
* Update CMake to default to -Og
(cherry picked from commit d10d9d24e544c4d0325f68af144543cea60e2c37)

WT-9481 Initialize variables to compile with -Og  (v6.0) (#8181)

---

src/btree/bt_cursor.c

MongoDB restricts the truncate operation to be performed only on a table that does not have historical versions to prevent the problems that can arise with performing the truncate operation without a timestamp.

WT-10949 Allow truncate operation with no timestamp for MongoDB

---

src/rollback_to_stable/rts_btree.c

Coverity was raising a warning about a memory leak when we're running RTS in dryrun mode and don't free an allocated update. Specifically on the line: 
```
/* Avoid freeing the updates while still in use if hs_cursor->remove fails. */
upd = tombstone = NULL;
``` 
In non-dryrun mode this update has been added to an update chain and is now owned by that chain, but in dryrun mode the update is not inserted the assignment to NULL leaves the memory orphaned. With this change we now always free the allocated update.

WT-10189 Always free updates allocated in RTS dry runs

---

src/btree/bt_cursor.c

Reverts wiredtiger/wiredtiger#9064

Revert "WT-10949 Allow truncate operation with no timestamp for MongoDB"

---

tools/antithesis/test_format.dockerfile

WT-10964 Updated test format docker container to include more compression libraries (zstd, lz4, zlib) and gdb.

WT-10964 Updated test format container to include all compressors and gdb

---

src/include/misc.h

Fixes WT_PREFIX_MATCH which was incorrectly returning false for empty prefix strings.

WT-10878 Fix WT_PREFIX_MATCH to correctly handle empty prefix

---

test/suite/test_checkpoint04.py

Reset connection statistics on each retry of the test in checkpoint04, as maintaining the time_min stat across runs can cause the test to loop indefinitely. 
Full details on why this is needed are present in the Jira ticket.

WT-10671 Reset statistics when retrying test in test_checkpoint04.py

---

bench/workgen/validate_mirror_tables.py
bench/workgen/workgen.cpp

We can probably do better but that's the algorithm in two steps::
(0) Once we have parsed the metadata, we know all the tables.
(1) For each table, if it has a mirror (`has_mirror()` returns `true`), retrieve the URI of the mirror. If the map `_dyn_tint` does not contain the URI, then the entry is missing. Add it to `to_delete`.
(2) Delete all entries in `to_delete`.
Note: this is safe as we are single-threaded at this time.

WT-10934 Process missing mirrors when starting from an existing database in workgen

---

dist/s_string.ok

Drop words from s_string.ok that are no longer in the code base and don't need to be whitelisted anymore.
We've run `sh s_string.ok -r` on both an `ubuntu2204` and `ubuntu1804` to confirm that this is correct for both older and more recent versions of aspell.

WT-10975 Remove redundant entries in the s_string.ok whitelist

---

test/evergreen.yml
test/evergreen_develop.yml

Move the `infrequent-checks` buildvariant from `evergreen.yml` to `evergreen_develop.yml` so that they only run on the develop branch.

WT-10977 Only run the infrequent-checks buildvariant on develop

---

src/txn/txn.c

We should not process any obsolete resolved updates as they may be freed concurrently.

WT-10876 Skip obsolete updates when verifying resolved updates

---

test/format/format.h
test/format/format_config.c
test/format/ops.c

The VLCS characteristic of appending to the end of a table means that a truncate at the end of a table and then an append-insert can overwrite the mirror space. It is correctly handled except when both FLCS and VLCS exist as mirrors. In that case I adjust the truncate range to leave the last mirror element in the table.

WT-10849 Work around edge case for mirrors with FLCS, VLCS and truncate.

---

test/format/checkpoint.c

When checkpointing, it is possible to get an `EBUSY` error for various reasons. One of them is when we are trying to drop a checkpoint while a dhandle referring to it is being used by a reader or the sweep server for instance.
The current code of test/format assumes checkpoints always succeed. The suggested changes cover the `EBUSY` scenario.

WT-10802 Handle EBUSY error when checkpointing in test/format

---

dist/s_string
dist/s_string.ok
test/evergreen.yml
test/evergreen_develop.yml

Move s-string from `infrequent-checks` into PR testing so we correct `s_string.ok` in the same PR that makes the `s_string.ok` updates necessary.
As part of this I've also: 
- merged `s-all` and `s-string` into a single task, and 
- set `stepback: false` for the `infrequent-checks` buildvariant. This will prevent any future cases of an infrequent test failing and evergreen generating a large amount of BFGs via the stepback process.

WT-10981 Move s-string task into PR testing

---

src/meta/meta_ckpt.c
test/suite/test_backup29.py

Please note this is not a clean cherry-pick. I ran into quite some conflicts on the below 3 files and realized there are a few recent tickets that touched the `timestamp_abort` test code lately (namely WT-10626, WT-10756, and WT-10755). 
- test/csuite/timestamp_abort/main.c
- test/csuite/timestamp_abort/smoke.sh
- test/utility/misc.c
In order to make the backport easier I dropped the changes for the above 3 files and kept the core fix and Python test changes in this PR. We can use a different backport to add the `timestamp_abort` test change later (with a thorough evaluation of dependencies from other recent changes).

WT-10551 Load backup block mod information into base checkpoints. (#9014) (#9093) (v6.0 backport)

---

dist/s_string.ok
dist/s_style
src/utilities/util.h
src/utilities/util_backup.c
src/utilities/util_compact.c
src/utilities/util_create.c
src/utilities/util_drop.c
src/utilities/util_dump.c
src/utilities/util_list.c
src/utilities/util_load.c
src/utilities/util_load_json.c
src/utilities/util_loadtext.c
src/utilities/util_main.c
src/utilities/util_misc.c
src/utilities/util_read.c
src/utilities/util_rename.c
src/utilities/util_salvage.c
src/utilities/util_stat.c
src/utilities/util_truncate.c
src/utilities/util_upgrade.c
src/utilities/util_verify.c
src/utilities/util_write.c

Convert wt utility allocations/frees to tcmalloc, when we build with it.
There are a few alternative designs here:
1. `#define malloc tc_malloc` (and so forth). This is the approach that the main WiredTiger library uses, and it would work here - but I find it to be in slightly bad taste, and I don't particularly like it being used in the main library. It definitely doesn't feel right to extend that approach here, and it also doesn't fix the `strdup` case.
2. Have the ifdef around the function definitions, and have a tcmalloc section and "normal" section. This was slightly more duplicated code, but I don't dislike it.
There are a couple of higher-level changes discussed on the ticket, but they were undesirable for other reasons (e.g. an API change to describe how WT allocated memory, or …

WT-10767 Have WT utility use the same allocator as the main WiredTiger library

---

src/meta/meta_ckpt.c
test/suite/test_backup29.py

This is a clean cherrypick from the `mongodb-6.0` branch.

WT-10551 Load backup block mod information into base checkpoints. (#9014) (#9093) (#9106) (v5.0 backport)

---

src/meta/meta_ckpt.c
test/suite/test_backup29.py

This is a clean cherrypick from the `mongodb-5.0` branch.

WT-10551 Load backup block mod information into base checkpoints. (#9014) (#9093) (#9106) (#9110) (v4.4 backport)

---

test/csuite/wt8246_compact_rts_data_correctness/main.c
test/evergreen.yml

The test wt8246_compact_rts_data_correctness had a bug that I fixed in [WT-10528](https://jira.mongodb.org/browse/WT-10528) and I think this failure also was because of the bug. I tried to reproduce this issue after [WT-10528](https://jira.mongodb.org/browse/WT-10528) but could not reproduce it after running the wt8246_compact_rts_data_correctness and make-check-test for a couple of days.
This ticket is used to do some changes in the make-check-test task and also in the test that could help us to debug faster if it fails again.

WT-9545 wt8246_compact_rts_data_correctness test read incorrect data on macOS

---

test/evergreen.yml

Though the solution is the same, on the mongodb-6.0 branch we only need to switch distro for the `unit-test-long` task in the `ubuntu2004-arm64` builder.

WT-10935 Move to a larger distro for unit-test-long task

---

test/utility/misc.c

On MacOS 11, the cp command doesn't support the -l option to link rather than copy files. This change stops testutil_copy_data_opt() from trying to link files on Macs.
(cherry picked from commit d1b22a118d77b4a7bac69123094854d4d5a7170e)

WT-10914 Fix make-check-test on MacOS 11 (#9053)

---

test/suite/test_sweep01.py

`test_sweep01.py` includes the following comment about the loop where it waits for sweep to close handles:
```
```
This PR updates the comment to address changes to the code that have accumulated over the past few years:
- The test no longer runs automatic checkpoints
- The sweep server runs every second
- The idle time was reduced to 3 seconds
- The previous two points mean we expect a handle to be closed after 4 seconds
- The code doesn't sleep for double 4 seconds. Instead uses stats to check sweep progress until the expected handles are closed.

WT-11035 Fix out of date comment in test_sweep01.py

---

src/schema/schema_truncate.c
test/suite/hook_tiered.py
test/suite/test_truncate01.py
test/suite/test_truncate10.py
test/suite/test_truncate11.py
test/suite/test_truncate12.py
test/suite/test_truncate13.py
test/suite/test_truncate14.py
test/suite/test_truncate15.py
test/suite/test_truncate16.py
test/suite/test_truncate17.py
test/suite/test_truncate18.py
test/suite/test_truncate19.py
test/suite/wttest.py

Fixed a bug in tiered truncate that tried to truncate the file:....-0000001.wtobj uri
Enable the vast group of truncate tests that were previous disabled in the tiered hook.
Individually skip a few truncate tests that rely on fast truncates.
Skip tests with named checkpoints for tiered storage.

WT-10971 Fix truncate for tiered storage.

---

src/rollback_to_stable/rts_btree_walk.c
tools/rts_verifier/checker.py
tools/rts_verifier/operation.py

The versions before 4.4 only write the checkpoint with no time window information and in those versions, only the stable data is written to the disk. There is no need to verify these tables as part of the rollback to stable as these tables contain only the stable data to avoid unnecessary verification.

WT-11031 Fix RTS to skip tables with no time window information in the checkpoint

---

test/format/ops.c

Although I haven't been able to reproduce it, it is possible for test/format to choose `max_rows` as the starting key number. If we adjust `last` down in the truncate edge case, we also need to possibly adjust the starting key too.

WT-11046 Adjust format keyno if necessary.

---

src/session/session_dhandle.c

@etienneptl @marcbutler I'm going to put you down as reviewers - please let me know if you disagree with the change or you think that there's a better way to do it.

WT-11057 Fix potential out of bounds read in __wt_session_get_btree_ckpt

---

src/conn/conn_api.c
src/conn/conn_open.c
src/include/extern.h
src/meta/meta_ckpt.c
src/txn/txn_recover.c
test/suite/test_bug029.py
test/test_coverage.md

The core change here is to initialize conn->ckpt_most_recent from the time on the last checkpoint in the metadata. This ensures that new checkpoint and flush times after (re-)starting WT will be greater than those used before we shutdown. The change is just a couple lines of code to load this value at the same time we load the base write generation.

WT-9457 Preserve ckpt_most_recent value across restart

---

dist/s_void
src/include/btree_cmp_inline.h

The goal of this is to catch cases in WiredTiger that falsely optimize search operations by skipping prefixes that should logically match, but don't.

WT-11049 Always check prefix skipped search results in diagnostic builds

---

src/btree/bt_sync.c
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c
test/suite/test_alter05.py
test/suite/test_checkpoint_snapshot06.py
test/suite/test_hs21.py

Eviction can run in parallel to the checkpoint and can able to write more data than the checkpoint can see and checkpoint operation includes the changes from the eviction as part of the checkpoint can lead to the scenario where this tree is ignored in the next checkpoint due to the tree being clean leads to a scenario where the log records of a tree are replayed from the prior checkpoint location than the current checkpoint as part of the backup restore.
To avoid ignoring these trees as part of the next checkpoint, mark the tree dirty whenever the checkpoint detects that it has more data than the checkpoint can see.

WT-10820 Checkpoint to mark the tree dirty when the tree has more data

---

src/tiered/tiered_handle.c

@sueloverso: hope you don't mind looking at a very small, house cleaning PR.

WT-11078 __wt_tiered_open_btree() should assert dhandle != NULL before using it

---

test/suite/test_bug031.py

As WT-10522 fixes the edge case scenario, it needs to be reverted in order to fail with the suggested reproducer.

WT-10717 Add a reproducer to show it is possible to miss a record in the update list without WT-10522

---

src/utilities/util_load.c

Fixed leak config_rename() where string array entry was replaced without being freed.

WT-11098 Fix memory leak in wt load

---

test/evergreen.yml

I saw that in our PR testing we only have unit-test and not unit-test-long, so I've added unit-test-nonstandalone to our PR testing to match that. I've done this in buckets as well to reduce the duration of the PR. At the moment it is only on Ubuntu2004, let me know if we want this on other variants.

WT-10968 Add non standalone build test to the PR testing

---

tools/rts_verifier/checker.py
tools/rts_verifier/operation.py

This adds FIXMEs to all of the places where the RTS verifier thinks there's something wrong with what RTS did. This is necessary because until the checking is more complete, it doesn't know enough about the system to correctly make these assertions. Note that problems with the input (missing types, fields etc) are still an exception.
Also fixed some random whitespace issues I noticed while looking for exceptions.

WT-11043 Stop verifier raising exceptions until it's more complete

---

src/btree/bt_curnext.c
src/btree/bt_curprev.c

It's possible for the history store cursor to see out-of-order keys when crossing page boundaries as a result of using read uncommitted isolation. This can occur when the lastkey seen is removed along with the page it was on and new keys are inserted at the page boundary that the cursor has just moved to. To fix this we can reset the cursor check when we are using read uncommitted isolation mode and cross a page boundary. Note that the keys are not actually out-of-order in the tree it just appears this way to the cursor.

WT-11017 Fix out-of-order key diagnostic check for history store cursor

---

cmake/helpers.cmake
test/suite/README
test/suite/helper_tiered.py
test/suite/test_backup10.py
test/suite/test_backup11.py
test/suite/test_checkpoint_snapshot04.py
test/suite/test_compat02.py
test/suite/test_compat03.py
test/suite/test_cursor_bound19.py
test/suite/test_cursor_bound_fuzz.py
test/suite/test_debug_mode02.py
test/suite/test_hs21.py
test/suite/test_import01.py
test/suite/test_import02.py
test/suite/test_import03.py
test/suite/test_import05.py
test/suite/test_import07.py
test/suite/test_import08.py
test/suite/test_stat01.py
test/suite/test_tiered13.py
test/suite/test_timestamp14.py
test/suite/test_timestamp26.py
test/suite/test_txn19.py
test/suite/test_txn22.py
test/suite/wtbackup.py

These typos were detected with `cspell`. There are lots of false positives, I may have missed a few real ones.

WT-11108 Fix typos in the code base

---

src/support/timestamp.c

* WT-11051 Fix newest start durable timestamp comparison in aggregate timestamp validation.
(cherry picked from commit 2a63f4a39c3a74467005c2c7423823f22f5af394)

WT-11051 Fix newest start durable timestamp comparison in aggregate timestamp validation (#9150) (v6.0 backport)

---

dist/s_clang_format

Add auto-downloading of `clang-format 10.0.0 aarch64` binaries in `s_clang_format`.
I've also done a bit of cleanup to `download_clang_format` and added a comment explaining how to add new binaries in future.

WT-11092 Add clang-format 10.0.0 aarch64 binary to s_clang_format

---

test/evergreen.yml

Fixed ignoring format exit, standardizing on bash as shell.
(cherry picked from commit 039cc949e442a69f072984ce625cb6cd2983cfa3)

WT-7401 Fix silent failures in evergreen (v7.0) (#9159)

---

dist/log.py
src/log/log.c
src/log/log_auto.c
src/log/log_slot.c
src/os_common/os_alloc.c
src/os_posix/os_fs.c
test/format/wts.c
test/suite/test_bug028.py

Here are fixes needed to make direct I/O work for logging. Apparently it has never worked, but this did uncover an actual bug that is also fixed.

WT-8684 Fixes for logging direct I/O.

---

test/evergreen.yml

Fixed ignoring format exit.
Co-authored-by: Mick Graham <99703363+mickgraham-mongodb@users.noreply.github.com>
(cherry picked from commit 62f0a8764f9ddd868fc97f491f3317a2bb6993c1)

WT-7401 Fix silent failures in evergreen (v6.0) (#9183)

---

test/evergreen.yml

Fixed ignoring format exit.
(cherry picked from commit 039cc949e442a69f072984ce625cb6cd2983cfa3)

WT-7401 Fix silent failures in evergreen (v5.0) (#9183)

---

test/evergreen.yml

Fixed ignoring format exit.
(cherry picked from commit 039cc949e442a69f072984ce625cb6cd2983cfa3)

WT-7401 Fix silent failures in evergreen (v4.0) (#9183)

---

test/evergreen.yml
test/evergreen_develop.yml

Changed the WiredTiger code coverage tests to (a) execute only the Catch2 based tests, and (b) run in every post-merge test cycle.

WT-11120 Update code coverage task to execute only Catch2 based unit tests

---

src/txn/txn.c

The timing stress added in [WT-10873](https://jira.mongodb.org/browse/WT-10873) caused test format to timeout with a prepare-conflict after two minutes. This was due to a high value for txn->mod_count caused by truncate operations. Limiting the timing stress to be called a maximum of 10 times resolves the timeout issue and prevents the thread to sleep for too long.

WT-10178 Fix timing stress causing format to time out with prepare-conflict

---

src/include/cell_inline.h

These are just the basic ones, I spent some time trying to add some assertions on the packing side but (a) that code is more complex and I was less convinced my assertions were correct, and (b) we strongly suspect the bugs we've seen are on the unpacking side.
Note that we don't think the unpacking code is itself wrong - rather, we think something is using it incorrectly, but these assertions should still help with that.

WT-11134 Add extra assertions around cell unpacking

---

src/txn/txn_rollback_to_stable.c

This change is a reimplementation for older branches from the commit af1fb31f4ecfa4d8e267c1856d159e84e70c70b4

WT-11031 Fix RTS to skip tables with no time window information in the checkpoint (6.0 backport)

---

src/reconcile/rec_visibility.c

(cherry picked from commit 00a2f853db0321cd2c283b14a520163452e5b0c0)

WT-10449 Do not save update chain when there are no updates to be written to the history store (6.0 backport)

---

test/csuite/schema_abort/main.c

WT-10488 Added sleep to worker thread loop to give all threads a chance to progress and move the timestamp forward. Increased the max time to set the stable timestamp before first checkpoint.
(cherry picked from commit d68edf8a25c95f4f9e3d5a13e9023081605a6b0a)

WT-10488 Updated schema abort to set stable ts reliably (#8884) (v6.0 backport)

---

test/format/config.c

The current version does not have the NTV macro ` #define NTV(table, off) ((table)->v[V_TABLE_##off].v)` so I have just substituted the values inline to keep the backport within scope (the `TV `and `GV `macro are not compatible here due to requiring `tables[0]` instead of `table`). 
If it reads better adding the NTV macro to the backport let me know and I can add that.

WT-9117 Restricting runs.rows to 1,000,000 when runs.in_memory is auto enabled (#8541) (v6.0 backport)

---

test/format/config.c

[WT-9117](https://jira.mongodb.org/browse/WT-9117) Restricting runs.rows to 1,000,000 when runs.in_memory is automatically enabled. Removing restriction on runs.rows when direct IO is enabled (as it most likely never used).
(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/78017d23df44a069ef6f224dfc8b27887acf4073)

WT-9117 Restricting runs.rows to 1,000,000 when runs.in_memory is auto enabled (#8541)(v5.0 backport)

---

ext/storage_sources/gcp_store/gcp_storage_source.cpp

The file imports `wt_internal.h` but it is never used.

WT-11145 Clear unused wt_internal import in gcp_storage_source.cpp

---

test/format/format.sh

Updating resolve function to handle format process not being a child of the shell. Adding comment for expected race that can be ignored. Adding failure reporting for ASan issues.
(cherry picked from commit 7e97e06ff3b4c8eb71625478ce3c96a6c9073adc)

WT-9721 Fix format.sh resolve function (#8196) (v5.0 backport)

---

test/csuite/wt8246_compact_rts_data_correctness/main.c

… 
* Retry 5 times and then abort the test
(cherry picked from commit 1daa7d05a761f3968fbcefa46f2d71803c3cc17d)
Co-authored-by: Ravi Giri <56813441+raviprakashgiri29@users.noreply.github.com>
(cherry picked from commit 880c9703e9018c3aea3d7bfb48ce82ee8fa1bd22)

WT-10528 test_wt8246_compact_rts_data_correctness retry to insert thedata during WT_ROLLBACK (#9099) (#9192) (v6.0 backport)

---

src/include/btmem.h

Corrects layout of __wt_page. Thereby reducing unnecessary padding and bringing the modify field back within the first 64 bytes of struct consistent with code comments.

WT-11116 Correct layout of __wt_page

---

test/evergreen.yml
test/evergreen_develop.yml

Refactored the code coverage task to make the steps reusable by turning the analysis and result publishing steps into functions. Cloned the refactored code coverage task to create 'code-coverage-catch2'.

WT-11136 Clone the new code coverage task into two

---

dist/primitive_check.py

Make the regex search in `primitive_check.py` use the `re.MULTILINE` flag. This allows the `^` start-of-line character to match both at the beginning of the string being searched and also after each `\n` character.

WT-11157 Add re.MULTILINE to regex search in primitive_check.py

---

bench/workgen/runner/example_prepare_evict_reconcile.py
dist/stat_data.py
src/btree/bt_read.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

WT-10759 During reconciliation do not retry to forcibly evict the page.
(cherry picked from commit d76b5a3e51d9f4d1a879db5734c147385401d1d0)

WT-10759 Do not retry to force evict history store pages during reconciliation (#9044)

---

src/txn/txn_rollback_to_stable.c

* Updating RTS verifier script to handle the new message.
(cherry picked from commit 83f2b1b94c08e5d7c5b97a0fd77880cbb8989b82)

WT-10764 Adding a message to indicate that rollback to stable has finished (v6.0) (#8934)

---

test/suite/test_backup29.py

I had to backport [WT-10909](https://jira.mongodb.org/browse/WT-10909) and [WT-10920](https://jira.mongodb.org/browse/WT-10920) to have a clean backport of [WT-11036](https://jira.mongodb.org/browse/WT-11036).

WT-11036 Add test of incremental backup after files are closed (5.0)

---

test/suite/test_backup29.py

I had to backport [WT-10909](https://jira.mongodb.org/browse/WT-10909) and [WT-10920](https://jira.mongodb.org/browse/WT-10920) to have a clean backport of [WT-11036](https://jira.mongodb.org/browse/WT-11036).

WT-11036 Add test of incremental backup after files are closed (4.4)

---

src/cursor/cur_backup.c
src/include/misc.h
src/session/session_dhandle.c

The main changes are in the `WT_STRING_MATCH` macro. The changes prevent the macro from attempting to read past memory that is valid to read. I've also changed the `WT_STRING_MATCH` macro to call an inline function instead as that should provide more safety.
The other changes are fixing up some calls to `WT_STRING_MATCH` as strlen() was being called on the wrong argument, and a workaround where we previously used `WT_PREFIX_MATCH` instead of `WT_STRING_MATCH`.

WT-11065 Fix WT_STRING_MATCH macro

---

src/reconcile/rec_visibility.c
test/suite/test_flcs07.py
test/suite/test_reconcile01.py

Reconciliation always expects an update before the tombstone if the tombstone is not globally visible. The empty records are filled with single tombstones for fixed-length column store tables. Handle these single tombstones in reconciliation if there is no on-disk entry exist.

WT-11113 Handle implicit tombstones of fixed length column store in reconciliation

---

test/csuite/wt8246_compact_rts_data_correctness/main.c
test/evergreen.yml

…
* WT-9545 wt8246_compact_rts_data_correctness test read incorrect data on macOS
* Updated the optimize level for the entire macos variant
(cherry picked from commit 46fb8317e1cfbbb72204596065d78d951fc36c82)
Co-authored-by: Ravi Giri <56813441+raviprakashgiri29@users.noreply.github.com>
(cherry picked from commit e9f6e2ef429317344c88a5cd57e0a53662f24132)

WT-9545 wt8246_compact_rts_data_correctness test read incorrect data on macOS (#9116) (#9199) (v6.0 backport)

---

test/evergreen.yml

In `/cygdrive/c/python`, all the binaries are preserved, we should have used that path from the start.

WT-11142 Use the right Windows toolchain path

---

test/evergreen.yml

There are another 2 tasks `format-stress-sanitizer-ppc-test-1` and `format-stress-sanitizer-ppc-test-02` in the same Evergreen builder. Removing this task to avoid testing duplication (and the hacky config).

WT-11167 Remove the duplicated format-stress-sanitizer-ppc-test Evergreen task
