wiredtiger/wiredtiger

src/block/block_open.c
src/block_cache/block_mgr.c
src/include/block.h

Make block unreachable in the connection object
prior to releasing any resources.

WT-11181 Make block unreachable when closing

---

src/conn/conn_sweep.c

Before this fix, we would never re-read the new `conn->sweep_interval` value after reconfiguring it during runtime.

WT-11199 Read the correct sweep server interval value after reconfiguration

---

src/block/block_open.c
src/block_cache/block_mgr.c
src/include/block.h

Fix race condition where blocks with a non-zero ref count could be freed.
Fix race condition where block from a failed open could be acquired and then freed with a non-zero ref count.
Fix potential corruption of block lists in connection: due to modification without holding the associated lock.

WT-11181 Fix errors in block open and close

---

src/txn/txn.c
test/huge/huge.c

**Description of the issue:** (why test_huge fails)
1) Application thread does some cursor operation (like update) which causes a page in the btree to be referenced (active hazard pointer maintained for it after the end of the btree search walk). The page referenced is the one updated during the operation, lets call it page A.
2) At the end of the operation (for example at the end of __curfile_update), a call to CURSOR_UPDATE_API_END_STAT is made. This causes the transaction associated with the operation to be committed.
3) At the end of the transaction commit operation, while a reference to A is still maintained from step 1), a check for cache eviction is made.
4) Assume A is very large, such that it alone exceeds a cache threshold (let it be clean/update/dirty thresholds). This causes …

WT-11184 Use explicit transaction in test/huge to prevent pinning of large page

---

src/history/hs_rec.c
test/suite/test_hs32.py

(cherry picked from commit de4e9ae0b5c52c680ba9a86cb62b621f8f92e7c2)

WT-10536 Fix statistic check cache_hs_key_truncate_onpage_removal in test_hs32.py (v6.0 backport) (#8771) (#8975)

---

src/history/hs_rec.c
src/include/extern.h
src/reconcile/rec_write.c
test/suite/test_hs32.py

This change backports WT-10512 but also includes WT-10536 which fixes some issues that arose from that change. The fixed-length column store scenario will be disabled in the Python test as it is known to not work on v5.0.
[WT-10536](https://jira.mongodb.org/browse/WT-10536) Fix statistic check cache_hs_key_truncate_onpage_removal in test_hs32.py (v6.3 backport) (https://github.com/wiredtiger/wiredtiger/pull/8771) (https://github.com/wiredtiger/wiredtiger/pull/8975)
(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/de4e9ae0b5c52c680ba9a86cb62b621f8f92e7c2)
Co-authored-by: Sean <41533874+Sean04@users.noreply.github.com>
[WT-10512](https://jira.mongodb.org/browse/WT-10512) Fix not inserting an out of order timestamp into the history store (6.0 backport) …

WT-10512 Fix not inserting an out of order timestamp into the history store (v5.0 backport)

---

test/evergreen.yml

(cherry picked from commit f7d86b2af9d3aaee6e6d65c8e1df12eadaa546e6)
Co-authored-by: Mick Graham <99703363+mickgraham-mongodb@users.noreply.github.com>
(cherry picked from commit b6ef8abb9edcddffbaeecba9df346b37d47951a9)
(cherry picked from commit 20f96dc020602f5b5eea80d74cf2b60c2beb5138)

WT-10285 Increase instance size for stress sanitizer tasks (#9219) (#9289) (#9315) (v5.0 backport)

---

src/reconcile/rec_col.c
src/reconcile/rec_row.c
test/suite/test_hs11.py

* WT-10469 Fix no timestamp tombstones not removing history store entries (#8727)
(cherry picked from commit ede3bedaa1e5bfd03b51857608843c00dabc03d5)
* Fix ooo_tombstone check.
* Fix retry transaction in test_hs11
(cherry picked from commit 3c695aff6bb1c62f553f7c2514c3a34d7deb0db8)

WT-10469 Fix no timestamp tombstones not removing history store entries (#8727) (#8832) (v5.0 backport)

---

dist/s_string.ok
dist/stat_data.py
src/conn/conn_cache.c
src/evict/evict_page.c
src/include/cache.h
src/include/connection.h
src/include/session.h
src/include/stat.h
src/include/wiredtiger.in
src/reconcile/rec_write.c
src/support/stat.c
src/txn/txn_ckpt.c

v6.0 does not have split generation or some of the macros so I have kept the `local_gen` variable. 
Please review if the changes are appropriate for 6.0.

WT-10911 Investigate and update eviction timeline metrics that are showing up incorrectly (6.0 backport)

---

dist/s_clang-scan.diff
dist/s_string.ok
dist/stat_data.py
src/conn/conn_cache.c
src/evict/evict_page.c
src/include/cache.h
src/include/connection.h
src/include/session.h
src/include/stat.h
src/include/wiredtiger.in
src/reconcile/rec_write.c
src/support/stat.c
src/txn/txn_ckpt.c

* WT-10911 Fix update eviction timeline metrics that are showing up incorrectly (#9055) (#9317)
w / fixes and adjustments
(cherry picked from commit 4061ee7289304fdd594e2b1377bfa432ee6533e1)
Co-authored-by: Ruby Chen <ruby.chen@mongodb.com>
(cherry picked from commit 0c9b80ec41eb963e3f30c93bcdc3f9af6dce293b)
* setting variable.
---------
(cherry picked from commit 80fc8c2b636863fed77e1cfee720df9d17d40cc8)

WT-10911 Investigate and update eviction timeline metrics (v5.0 backport) 

---

test/evergreen.yml

Disable tests that are failing in WT-11226 until WT-11226 is resolved.
@lukech I'll also open a backport ticket for 7.0, and possibly older branches if we see this occur

WT-11267 Disable failing tests after Python 3.9.5 upgrade

---

test/evergreen.yml

This PR has two commits:
1. Re-enable tests disabled in WT-11227
2. Set the correct env vars in the tasks for tiered storage tests and predictable tests

WT-11226 Correctly set environment variables in tiered and predictable tests

---

test/evergreen.yml
test/evergreen_develop.yml

Make sure that `PATH=/opt/mongodbtoolchain/v4/bin:$PATH` is set inside the `configure_env_vars`, `compile_env_vars`, and `test_env_vars` expansions on a buildvariants.
In some cases I've tweaked existing configs for consistency so that we always have
```
configure_env_vars: PATH=/opt/mongodbtoolchain/v4/bin:$PATH
compile_env_vars: PATH=/opt/mongodbtoolchain/v4/bin:$PATH
test_env_vars: PATH=/opt/mongodbtoolchain/v4/bin:$PATH
```
or if `test_env_vars` has multiple fields PATH is always the first one set.
Further work is planned in WT-11230 to see if we can reduce the redundancy here

WT-11233 Ensure all evergreen variants are using the v4 toolchain

---

src/block_cache/block_map.c

WT-8728 was closed as "Won't Do" but there is a FIXME comment in the code base. Using the ticket to remove it.

WT-8728 Remove FIXME comment regarding tiered storage and memory mapped files

---

test/csuite/random_directio/main.c

Leveraging the testutil custom_die to kill child if the parent aborts.

WT-10990 Killing child of test_random_directio if parent aborts

---

src/include/btree_inline.h
src/include/extern.h
src/include/txn_inline.h
test/suite/test_checkpoint30.py

The aggregated time window of a page is calculated based on the maximum transaction/timestamp values present on each individual key/value pair. It is possible that a page can have a key that removal operation may not be visible to the reader snapshot.

WT-11241 Skip current transaction snap_min visible deleted pages as part of the tree walk

---

src/tiered/tiered_config.c
test/suite/test_tiered21.py

Disallow the use of the "in_memory" configuration to be used together with tiered storage.
The PR also removes the cleanup code from `__wt_tiered_conn_config`, because it resulted in double-free: On error, it would remove the current `bstorage`, but it would be removed later _again_ when `wiredtiger_open` cleans up, when it goes through the linked list of all block storages.

WT-9818 Disallow in_memory when using tiered storage

---

test/cppsuite/src/common/logger.cpp
test/cppsuite/src/common/logger.h
test/cppsuite/src/util/execution_timer.cpp
test/simulator/timestamp/src/include/session_simulator.h

Couple of minor fixes, all in test code. The `std::string_view` thing is a way to accept either a `char *` or a `std::string`, since there are lots of places that used both it seemed better to fix it like this.

WT-11282 Fix build for GCC 13

---

dist/s_string.ok
src/include/btmem.h
src/include/txn_inline.h

This barrier was paired with a write barrier on upd->type when it switched from WT_UPDATE_BIRTHMARK to WT_UPDATE_STANDARD. We no longer support birthmarks and we don't change upd types.

WT-11272 Removing upd->type read barrier in the txn read path.

---

test/format/format_config.c

The combination of logging, backup, and salvage can use a large amount of disk space, especially when logging.remove=0. As such, this PR will limit the length of the run to 10 mins if these are all true.

WT-11281 Limit runs timer to limit disk space usage

---

cmake/configs/modes.cmake
dist/s_export
dist/s_export.list
test/evergreen.yml

Add necessary compiler flags to enable msan origin tracking.
Update msan environment in CI to remove unrecoginzed flag and increase verbosity to aid debugging.

WT-11278 Add msan origin tracking

---

cmake/configs/modes.cmake
dist/s_export
test/evergreen.yml

Reverts wiredtiger/wiredtiger#9383
To allow fixing format.sh and updating evergreen.yml

Revert "WT-11278 Add msan origin tracking"

---

src/txn/txn_rollback_to_stable.c

This change is a reimplementation for older branches from the commit af1fb31f4ecfa4d8e267c1856d159e84e70c70b4
(cherry picked from commit ccde00ad5b5b48a827cd0101bcf1714d27fe38cd)
(cherry picked from commit 5f734cefc93076fad704b244b58cee64b31c9670)

WT-11031 Fix RTS to skip tables with no time window information in the checkpoint (#9216) (#9391) (4.4 backport)

---

dist/api_data.py
src/config/config_def.c
src/include/wiredtiger.in

Hiding the DRAM config. 
I had the assumption that putting `undoc` after choices would hid only the choices however in wiredtiger.in it shows that the whole config is hidden - do we need visibility of the chunk type selecting being 'FILE' if this is the default? Need to investigate further if only choices can be hidden.
An alternative solution if we cannot hide the whole config:
```
Config('file', 'true', r'''
set cache location to the file system.''',
type='boolean'),
Config('dram', 'false', r'''
set cache location to the block device. This will override chunk_cache.file setting.''',
type='boolean', undoc=True),
]),
```
This can separate the options from the config and hide the DRAM option - can nest this in a subconfig under type as well if that is more readable - but otherwise not much …

WT-11258 Hide dram option in config

---

test/utility/file.c

I added a retry mechanism for `pread` in file copy as suggested in the ticket. We don't have a record of the failure described in the ticket since we switched our mechanism for copying files in tests, but I still decided to make this change as it's straightforward and safe (given that now we have the ability to fix our own file copy). I used the same approach as in WT-8981 (#8308).

WT-10117 Retry pread in file copy

---

bench/wtperf/runners/chunk_cache_reads.wtperf
bench/wtperf/runners/chunkcache_reads.wtperf
bench/wtperf/wtperf.c
bench/wtperf/wtperf.h
bench/wtperf/wtperf_config.c
bench/wtperf/wtperf_opt_inline.h
src/docs/wtperf.dox

This adds scenarios to measure throughput, both with and without the chunk cache. This also makes it a lot more difficult to mis-use the chunk cache, by adding a separate `wtperf` config item for the config that implies a restart. This way, we don't run into the issue where changing a file under the chunk cache causes the block manager to see stale data (and, thankfully, invalid checksums).

WT-11255 Tiered storage performance scenario

---

test/evergreen.yml
test/evergreen/run_format_configs.sh

The format-failure-configs-test task was changed to run in parallel and that has triggered an OOM. This occurred on Ubuntu ARM64 which turned out not to have TCMALLOC enabled. Also while testing I ran into an issue with the script which runs the configs with removing via a regex which could have overlapping PIDs.

WT-11302 Enabling TCMALLOC for Ubuntu ARM64 and fixing failure configs scripting issue

---

test/format/format_config.c

The hs_search stress point impacts the performance of test format when pareto distribution is enabled for a table as it creates a lot of hot keys with history. When paired with predictable replay, test format will not stop on time. This is due to how predictable replay needs to stop a run (with a consistent timestamp). This change disables the combination to prevent this error.

WT-11273 Prevent hs_search stress point with pareto and predictable replay

---

dist/filelist
dist/s_funcs.list
dist/s_string.ok
src/include/extern.h
src/include/misc.h
src/support/qsort.c
src/support/qsort_r.c
test/unittest/CMakeLists.txt
test/unittest/tests/test_qsort.cpp

A few things worth noting:
* The tests are largely based on the work @marcbutler did for WT-11060 - thanks!
* The initial cleanup work (over what was in the paper) was Luke's
* I also did some performance testing, it's definitely O(n log n) but the standard library `qsort` is still ~15% faster
* Original license for the qsort from the paper is retained

WT-11232 qsort_r support

---

src/os_posix/os_fs.c
test/utility/file.c

Improved the message to include while EOF would be an error in os_fs.c
Added an assert that in file.c for tests that we copied at least the size of the current file. I believe it has to be at least the size because the file could get larger, I don't think it can get smaller in these cases.

WT-11317 Improving comments and asserts around pread executions

---

test/csuite/wt6616_checkpoint_oldest_ts/main.c

WT-11327 Ensure writing of checkpoint done file by child occurs after the oldest timestamp has been set at least once. On very slow machines, this can be an issue causing a failure in setting the oldest timestamp on verification to 0 as it was not set.

WT-11327 Delay writing of checkpoint done file by child until oldest timestamp is set

---

test/evergreen.yml

When backup, salvage, and no compression are randomly selected these tasks can run out of disk space. This change limits that from occurring.

WT-11247 Reduce long-test format rows to limit disk usage

---

test/evergreen.yml

Limiting the number of rows used by format (when combined with backup, salvage, and no compression can cause out of disk). Also moving the unit test to before format which is more likely to use more disk space and means we don't need to clean up.

WT-11359 Update spinlock tasks to limit disk usage

---

src/include/misc_inline.h

It prevented the timing stress from showing up.

WT-11382 Fixing typo in misc_inline.h for Antithesis

---

test/3rdparty/testtools-0.9.34/testtools/distutilscmd.py
test/suite/test_bug001.py
test/suite/test_bug004.py
test/suite/test_bug010.py
test/suite/test_bug016.py
test/suite/test_bug031.py
test/suite/test_checkpoint01.py
test/suite/test_checkpoint09.py
test/suite/wtthread.py

Dealt with a few DeprecationWarnings:
* Replaced `assertEquals()` with `assertEqual()`
* Replaced `isSet()` with `is_set()`
* Favoured `setuptools` over `distutils` module in compliance with [PEP-632](https://peps.python.org/pep-0632/)
Should be no more now

WT-11196 Clean up deprecated functions in python tests

---

dist/s_docs
src/docs/Doxyfile.9

Our new ARM workstations come with Doxygen 1.9.1 pre-installed and I haven't found any ARM Doxygen release binaries for the versions we currently support (1.8.17 and 1.9.3). We used to support all 1.9.X versions before we found an issue with 1.9.5 and limited support to 1.9.3 in https://github.com/wiredtiger/wiredtiger/pull/8513.
This PR re-enables support for 1.9.1 in s_docs. I've had to remove a handful of config items that were introduced post-1.9.1, however all these fields are either unset or use default values. I've confirmed that Doxygen 1.9.3 still works correctly and the doc-gen evergreen task work correctly.

WT-11386 Support doxygen 1.9.1 in s_docs

---

test/evergreen.yml

This is a build issue as this test intentionally does not use the mongodbtoolchain and recent platform changes have caused issues with the system toolchain. We will be fixing this as part of WT-11239.

WT-11380 Temporarily disable compile-clang task

---

dist/flags.py
dist/stat_data.py
src/btree/bt_compact.c
src/btree/bt_debug.c
src/btree/bt_discard.c
src/btree/bt_page.c
src/btree/bt_split.c
src/evict/evict_lru.c
src/evict/evict_stat.c
src/include/btmem.h
src/include/btree_inline.h
src/include/hardware.h
src/include/stat.h
src/include/wiredtiger.in
src/reconcile/rec_write.c
src/support/stat.c

This backport is for WT-10424 but the changes increase the size of `WT_PAGE::flags_atomic` from `uint8_t` to `uint16_t`. To handle this we're also we're also backporting WT-8340 which updates our `ATOMIC` macros to handle 16 bits. 
------------------
[WT-8340](https://jira.mongodb.org/browse/WT-8340) Fix overflowed value in Btree atomic flags of 8 bit type (https://github.com/wiredtiger/wiredtiger/pull/7178)
* [WT-8340](https://jira.mongodb.org/browse/WT-8340) Fix overflowed value in Btree atomic flags of 8-bit type
* Added a new macro F_SET_ATOMIC_16  to support 16-bit integer.
* Read next line of flags and return an error if the number of flags is greater than the size of the field
(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/180c9bfa728620b9e59399eb49dc9e83 …

WT-10424, WT-8340 v5.0 group backport

---

test/evergreen.yml

(cherry picked from commit cf4f840fa14f739a0618851ca04eeb5e9fbf2933)

WT-11380 Temporarily disable compile-clang task (v4.4 backport)

---

src/conn/conn_api.c
src/conn/conn_handle.c
src/conn/conn_log.c
src/conn/conn_reconfig.c
src/include/connection.h
src/log/log.c

Take the existing uses of `debug_log_cnt` and `debug_ckpt_cnt` (`debug_mode.log_retention` and `debug_mode.checkpoint_retention` in the connection config) and change them from using memory barriers to locks.
Since this is the first PR in PM-3221 which migrates a barrier to using locks these a few questions to discuss. I'll 
flag them with comments.
The git diff for this PR is a bit hard to read. The main changes are as follows:
- Add a new lock (exact name tbd) which protects reads and writes to `debug_ckpt`, `debug_ckpt_alloc`, `debug_ckpt_cnt`, `debug_log_cnt`
- Pull the logic that reads and writes these fields into subfunctions where needed. This makes it easier to correctly set and release the new lock.

WT-11303 Move the debug mode retention flags behind a lock

---

test/suite/wttest.py

This [commit](https://github.com/wiredtiger/wiredtiger/pull/9451/commits/6af46389a6a92e84a00c93dcc8d66c4a88280892) shows how it was used in `test_compact04.py`.

WT-11392 Be able to read more chars from data streams in Python tests

---

dist/s_string.ok
src/include/btmem.h
src/include/txn_inline.h

C does not support for this usage of const, and the predicted cost of hiding this field behind an accessor is too high at this time.

WT-11315 Remove const qualifier from WT_UPDATE::type

---

dist/s_string.ok
src/block_cache/block_chunkcache.c
src/include/block_chunkcache.h
src/include/misc.h
test/unittest/CMakeLists.txt
test/unittest/tests/test_binary_search_string.cpp

The following work has been done in the ticket:
1. A new function was created to handle the pinned configuration due to the increasing size of the setup function and the potential needed to reconfigure this specific config in the future.
2. The pinned objects were extracted from the config and sorted into an array. Additionally, the name of each object was changed (example: from `table:abcd` to` abcd.wt`), as this is the required format for storing object names.
3. With a sorted array of pinned objects in place, a binary search is now performed every time a chunk is requested. This search determines whether the chunk belongs to any of the pinned objects.
4. Added unit testing for binary search.

WT-11336 Check chunk cache pinned list when admitting chunks

---

src/cursor/cur_backup_incr.c
src/cursor/cur_file.c
src/cursor/cur_index.c
src/cursor/cur_std.c
src/cursor/cur_table.c

__curbackup_incr_next API CALL error,  now it CALL "get_value", It is best to keep the style consistent with other interfaces，so It would be better to CALL "next".

WT-11402 Discrepancies when calling the API_CALL macro

---

test/suite/test_txn24.py

In test_txn24.py, set rollbacks_allowed to 0, and wrapped the final data insertion in a try-except block to catch any rollback errors and keep going.

WT-11407 Fix test_txn24 test (not WiredTiger) to stop WT_ROLLBACK errors on MacOS

---

src/conn/conn_compact.c
test/suite/test_compact06.py

The changes:
- Fix the background compaction algorithm so it does not call compact on incompatible files
- Update the tests with the method `assertRaisesWithMessage`
- Add more tests

WT-11421 Prevent background compaction from processing incompatible files

---

src/block_cache/block_chunkcache.c

I'm not sure why I thought this would be harder - oops. (Bear in mind this is the dumb version, it's a known issue that this can let the chunk cache fill up.)

WT-11337 Don't evict pinned chunks from chunk cache

---

src/conn/conn_compact.c

- Use a dedicated buffer for the URI used for compaction. We used to rely on the buffer associated with the cursor but this one can be freed as soon as the cursor is released.
- Handle `ENOENT` instead of `WT_NOTFOUND` as the error `WT_NOTFOUND` is always mapped to `ENOENT` in `__wt_session_compact`.

WT-11430 Make background compaction use a dedicated buffer for the URI and handle ENOENT

---

dist/stat_data.py
src/block_cache/block_chunkcache.c
src/include/block_chunkcache.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

The only stat that seemed relevant to add was `Total number of pinned chunks in the cache`. Many other things about the system in regard to the pinned content can be known by simple math b/w stats.
For instance, this stat added can answer the following questions by looking at the FTDC - 
- How many pinned chunks in the cache?
- How many non-pinned chunks are in the cache? (Total chunks - pinned chunks)
- How many pinned chunks were evicted?
- How many non-pinned chunks were evicted?

WT-11338 Pinned chunk cache content statistics

---

src/btree/bt_compact.c
src/include/extern.h
src/lsm/lsm_tree.c
src/session/session_compact.c

The changes extend the work done in WT-9636:
- Creation of a new function `__wt_session_compact_check_interrupted` that checks if foreground compaction has been interrupted.
- Add a check in `__compact_checkpoint` where we check for the timeout as well.
- The code for LSM trees is performing those checks too.
This function will most likely be reused for the work in WT-11344.

WT-11434 Make foreground compaction check for interruption before a checkpoint

---

dist/stat_data.py
src/btree/bt_compact.c
src/conn/conn_compact.c
src/include/stat.h
src/include/wiredtiger.in
src/session/session_compact.c
src/support/stat.c

I've added stats to track the status of the background compaction server. These stats mostly duplicate the existing session compact operation statistics that are tracked on individual calls to compact. I've created a new category of stats under the connection statistics labelled `BackgroundCompactStat`, let me know if there is a preference for creating a new category vs adding them to an existing one. 
One notable difference to the existing session compact operation statistics is the definition of the `background_compact_success` statistic. This is incremented after a round of compaction that has made some progress. On the other hand, the session operation statistic is incremented on any successful call to `wt_compact` regardless of whether any work was done. I've left this as is for now.

WT-11427 Create stats for the background compaction server

---

src/block_cache/block_chunkcache.c

Readers of `chunk->valid` need to ensure that reading other `chunk` fields happens strictly after checking validity, and writers need to ensure that it is the last field written to.
Unfortunately locking doesn't really solve the problem here - this reordering can still happen while holding the bucket lock, and there can be a large number of chunks so finer-grained locking just for `valid` field would be wasteful. Locking is also likely to have a measurable performance impact - significant work has gone into minimising the critical section, and since the lock is at the bucket level, reading or writing `valid` with the bucket lock will prevent anyone else looking at the entire bucket.
Use `ORDERED_READ`/`PUBLISH` as the longer-term solution of acquire/release isn't ready yet.

WT-10688 Review chunk cache barrier usage

---

dist/stat_data.py
src/conn/conn_compact.c
src/include/stat.h
src/include/wiredtiger.in
src/session/session_compact.c
src/support/stat.c
test/suite/test_compact07.py
test/suite/test_compact08.py

Background compaction follows the same behaviour as foreground compaction when it is interrupted:
- `ETIMEDOUT` if the timer has elapsed
- `WT_ERROR` if the server has been turned off while compaction was happening

WT-11344 Make background compaction interruptible

---

dist/test_data.py
src/config/test_config.c
test/cppsuite/configs/operations_test_default.txt
test/cppsuite/configs/operations_test_stress.txt
test/cppsuite/src/common/constants.cpp
test/cppsuite/src/common/constants.h
test/cppsuite/src/component/workload_manager.cpp
test/cppsuite/src/main/database_operation.cpp
test/cppsuite/src/main/database_operation.h
test/cppsuite/src/main/operation_configuration.cpp
test/cppsuite/src/main/thread_worker.cpp
test/cppsuite/src/main/thread_worker.h
test/cppsuite/tests/test_template.cpp

The changes:
- Add the possibility of adding a thread to a cppsuite workload that would enable background compaction.
- Update the default testing configuration with background compaction.
Note: a new test using that feature may come with WT-11346.

WT-11454 Add background compaction operation config to cppsuite

---

src/evict/evict_page.c

Co-authored-by: Siddhartha Mahajan <siddhartha.mahajan8899@mongodb.com>
(cherry picked from commit 7ef518cd7c8c0f8e4a608a13ebcf6d2484e049ad)

WT-11312 Fix incorrect flag check for accurate force eviction stat (v7.0) (#9403)

---

test/evergreen.yml

WT-11365 Re-enabled testing on RHEL zSeries, after it was disabled temporarily in WT-11364.

WT-11365 Re-enabled testing on RHEL zSeries.

---

src/evict/evict_page.c
test/suite/test_hs07.py
test/suite/test_prepare_hs01.py
test/suite/test_txn13.py

Added a 'us' unit to the eviction time in the "Eviction took more than 1 minute" warning message. Ignore more cases of the "Eviction took more than 1 minute" warnings in the standard output.
(cherry picked from commit 5b7de4cb3e22a351d79b045ad9af1bdac374f309)

WT-11221 Ignore unexpected Eviction took more than 1 minute warning in stdout (v7.0) (#9399)

---

test/evergreen.yml
test/evergreen_develop.yml

- Create dedicated perf testing distros for both the ARM64 and Ubuntu2004 distros
(cherry picked from commit ad8cab39bf70840ed489c34a6915e0c88b7136b0)

WT-10714 Use explicitly labelled perf distro for perf testing (#9500)

---

test/format/format_util.c
test/format/wts.c

Check if test format trace conn is NULL prior to using the trace sessions in the event it has been closed due to an error.

WT-11063 Protect against trace session closure on test format error

---

bench/workgen/workgen.cpp
bench/workgen/workgen.h

With those changes, we can enable/disable background compaction and set a specific threshold for compaction in Workgen.

WT-11455 Add background compaction setting to Workgen

---

src/conn/conn_compact.c

The changes change the code path when the background compaction encounters an error, we always free the allocated memory now.

WT-11466 Free memory allocated by the background compaction server

---

test/format/format_config.c

The changes:
- Improve some existing code
- Disable compaction for in-memory runs

WT-11467 Disable compaction in test/format for in-memory runs

---

test/suite/test_compact07.py

The changes:
- Avoid possible parallel compaction
- Expect an error message because the background compaction may be interrupted when stopped

WT-11479 Avoid parallel compaction in test_compact07 and expect possible interruption

---

test/evergreen.yml

This task has been on the border of failing and this will give it the time to complete.

WT-11449 Increase task timeout for csuite-long-running (MSan)

---

test/evergreen.yml

Also report the smp_command being used so the logs show the number of cores being used simultaneously for testing.

WT-11504 For Mac, use half the logical cores for both 'unit test' and 'make check all'.

---

test/evergreen.yml

Should the build hang at this stage again, hopefully this extra info will assist with diagnosis.

WT-11482 Add extra 'echo' calls to output more information during "configure wiredtiger" in evergreen.yml.

---

bench/workgen/runner/chunkcache.py
test/suite/test_chunkcache02.py

Currently chunkcache tests merged in WT-11261 is failing after the changes in WT-10799, this ticket fixes the bugs introduced.

WT-11514 Fix chunkcache tests to cache only tiered readonly objects

---

src/include/session.h
src/support/hazard.c

Some small changes after reviewing hazard pointer's shared variable semantics. There's only one change in which I've moved a barrier closer to where it's required. Otherwise there's some small cosmetic changes ID'd during the review.

WT-11458 Review shared variable semantics in hazard pointer logic

---

dist/s_style
src/txn/txn.c

Should I change all our qsort calls back to this? There 20 or so other ones in the codebase, once this is merged `__wt_qsort` will be reverted, and then those calls would have to be moved back again. So probably fine to leave them as is for the time being.

WT-11424 Revert back to using c stdlib qsort for modification sorting

---

src/session/session_compact.c

The `WT_CONN_MINIMAL` flag is used to cover the path when `__wt_compact_server_destroy` is called in `__conn_close`.
The `WT_CONN_CLOSING` flag is used to cover the path when `__wt_compact_server_destroy` is called in `__wt_connection_close` which is called in `wiredtiger_open` when things go wrong.

WT-11523 Do not check for background compact interruption when opening/closing the connection

---

src/session/session_compact.c
test/csuite/wt10897_compact_quick_interrupt/main.c
test/csuite/wt8057_compact_stress/main.c
test/suite/test_compact07.py

In WT-11519, we are discussing why an error message can be seen as a false positive. WT-11524 was then created to change from an error to a warning by replacing `WT_RET_MSG` with `__wt_verbose_warning`. However, interruption still returns `WT_ERROR` to be able to exit the compaction loop.

WT-11524 Log a warning instead of an error when compaction is interrupted

---

src/block/block_compact.c
src/block/block_open.c
src/include/block.h
test/format/format_config.c
test/suite/test_compact07.py
test/suite/wttest.py

The changes:
- Add a new field `session_id` to the `__wt_block` struct. When set, it indicates a session is compacting that dhandle.
- Return `EBUSY` if one of the dhandles is already being compacted and another session tries to compact it
- Update our tests now parallel compaction is handled

WT-11432 Prevent parallel compaction on the same URI

---

test/evergreen.yml
test/evergreen_develop.yml

The idea behind this change is that we utilize the concept of pre: tasks and expansions to help us clean up the environment variables. pre: will be run for every task in the evergreen system, and an expansion is a way to persist environment variables across tasks. In our case we have two expansions:
- PREPARE_TEST_ENV: Which allows the task to prepare any environment variables to run tests.
- PREPARE_PATH: Allows any environments that require the mongodbtoolchain path to be set for you.
The idea is that we can run the expansions at the start of each task, which is meant to do the setup for you. I have been able to clean up multiple different variables in the buildvariants through this.

WT-11230 Cleanup the usage of test_env_vars and configure_env_vars in evergreen.yml

---

src/btree/bt_handle.c

maxmempage bug fix, eviction_dirty_trigger,s percentage usage error, It will cause the btree->maxmempage to become invalid
if (!F_ISSET(conn, WT_CONN_CACHE_POOL) && (cache_size = conn->cache_size) > 0)
btree->maxmempage = (uint64_t)WT_MIN(
btree->maxmempage, (conn->cache->eviction_dirty_trigger * cache_size) / WT_THOUSAND);
#define WT_THOUSAND (1000)
The denominator should be 100， not 1000.

WT-11490 Improved Readability: Introduced WT_MIN_PAGES macro for memory_page config

---

src/btree/row_modify.c

WT-10614 Coverity analysis defect 135089: Dereference before null check

---

src/block_cache/block_chunkcache.c
src/conn/conn_capacity.c
src/include/capacity.h
src/include/extern.h
src/log/log.c
src/os_common/os_fhandle.c

This PR was created to deal with a recent failure in a chunkcache test on `Linux noftruncate`  build variant.
To enable the successful operation of the chunkcache on `Linux noftruncate`  build variants, the following has been done:
- A function for truncating the chunkcache file.
- Within this function, an attempt is made to truncate the file, depending on its support.
- In cases where support is absent, a manual process of resetting the file to a zeroed state is executed.
There are some modifications made to the existing function `__wt_file_zero`. @sueloverso it would be great if you could review the same.

WT-11535 Create a dedicated file truncate function for chunkcache

---

src/conn/conn_dhandle.c

I was able to reproduce this immediately. I think that the btree apply function should not operate on individual objects. The btree apply function is called from statistics logging and checkpoint only. Both should just operate on the actual btree. So this change skips objects.

WT-10823 Skip applying functions to tiered objects.

---

dist/log.py
src/log/log_auto.c

The comments have been updated in `dist/log.py` and `s_all` took care of updating `log_auto.c`.

WT11554 Generate comments for log_auto.c

---

test/format/format_config.c

Moved the check into two places as what is enabled changes post the first check so want to make sure reverse still has a chance if mirroring happens to be disabled.

WT-11557 Prevent format from running mirroring with reverse

---

src/rollback_to_stable/rts_btree_walk.c

@agorrod  you were recently in this code. I fixed 2 spaces in output and removed `it` from some messages because that word seemed wrong in that context. Should be a very fast review.

WT-11565 Whitespace and text fixes.

---

test/format/format.sh

Add a condition so that if there are no successes and a timeout is set, it's not a failure.

WT-11401 test/format indicates a failure when all jobs have neither completed or failed

---

src/rollback_to_stable/rts_btree_walk.c

Reading the value when it doesn't exist has a junk value and it lead to open the file unnecesary for rollback to stable operation to validate it for correctness. This can cause problem when the database has large number of files.

WT-11564 Fix RTS to read the newest_txn value only when it exists in the checkpoint

---

test/csuite/timestamp_abort/main.c
test/csuite/timestamp_abort/smoke.sh

This PR adds a `-f` flag to `timestamp_abort`, which then performs `force_stop` before every other backup (is this too frequent?) and forces a new full backup to be created.

WT-11499 Add "force_stop" test to timestamp_abort

---

test/format/format_config.c

The function `config_random` already takes care of generating random values, thanks @Siddhartha8899 for spotting this.

WT-11572 Remove unecessary code related to background compaction in test/format

---

bench/workgen/runner/evict-btree-hs.py
bench/workgen/runner/prepare_stress.py
bench/workgen/runner/runner/core.py
bench/workgen/workgen.cpp
bench/workgen/workgen.h
bench/workgen/workgen_int.h
test/evergreen.yml

Addressed a number of issues found under ASAN. Also updated some of the tests in order for them to pass consistently (e.g. with core.py increasing the key size to 12 for log keys as they are S and not Q).  Fixed overflow memory issue and fixed stopping issue when dropping tables. Enabled for evergreen once per day.

WT-11311 Address workgen issues and enable in evergreen

---

bench/workgen/workgen.cpp
bench/workgen/workgen_int.h

To be merged after WT-11311 as that enables the tests to cover this change.

WT-11309 Updating max size and value to be uint64_t in workgen

---

test/suite/test_compact06.py

We had a failure because the following message was raised:
```
WT_SESSION.compact: [WT_VERB_COMPACT][WARNING]: background compact interrupted by application
```
This happened because we enable/disable the background compaction as part of this test and a table exists. Since we don't need that table for this test, we can simply not create it and avoid that spurious message.

WT-11588 Remove the table in test_compact06.py

---

test/suite/test_checkpoint_snapshot05.py
test/suite/wtthread.py

Test fails due to the presence of more than 1 checkpoint.
Add new interface to allow tests to specify maximum checkpoint count.

WT-11492 Fix false positive failure in test_checkpoint_snapshot05

---

src/block/block_open.c

when parse the config of "block_allocation first", "the bool type" assigned to "the uint32_t type".
This coding style is not very friendly.

WT-11610 When parse the config of "block_allocation first", "the bool type" directly assigned to "the uint32_t type"

---

src/conn/conn_compact.c

Previously, `background_compact_fail` was not incremented when `WT_ERROR` was returned from the `compact` call.

WT-11637 Always increment background compaction failure stat when compaction does not succeed

---

src/conn/conn_log.c
src/include/log.h
src/log/log.c
src/log/log_slot.c

WT-10207 Changing log slot flags to flags_atomic. Removing debugging added for WT-9796 as the root cause was identified.
(cherry picked from commit 1b6329a945230f76011d0aad7a73b31188104f42)

BACKPORT-14420 Fix log slot flags and remove debugging

---

test/evergreen.yml
test/format/failure_configs/CONFIG.WT-11507

In order to have more chances to reproduce WT-11507, we are adding a temporary task to Evergreen which runs test/format with the config from WT-11507.

WT-11607 Add a temporary test/format task using the WT-11507 config in Evergreen

---

dist/stat_data.py
src/include/stat.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/support/stat.c
src/txn/txn.c
src/txn/txn_ckpt.c
src/txn/txn_rollback_to_stable.c
test/suite/test_checkpoint_snapshot02.py
test/suite/test_checkpoint_snapshot05.py
test/suite/test_rollback_to_stable10.py
test/suite/test_rollback_to_stable14.py
test/suite/wtthread.py

The backports are done together due to their dependency:
[WT-8570](https://jira.mongodb.org/browse/WT-8570)
[WT-8702](https://jira.mongodb.org/browse/WT-8702) (caused by [WT-8570](https://jira.mongodb.org/browse/WT-8570))
[WT-8709](https://jira.mongodb.org/browse/WT-8709) (caused by [WT-8702](https://jira.mongodb.org/browse/WT-8702))
WT-8825, WT-9248 and WT-11492 have also been included as they create/modify/fix the new test `test_checkpoint_snapshot05.py`.

WT-8570 WT-8702 WT-8709 WT-8825 WT-11492 WT-9248 (v4.4 backport)

---

test/evergreen.yml

I've gone through the `evergreen.yml` file and labelled tasks with type "`setup`" that are run to setup the environment for our testing, external tasks that are relied upon for specific tests, and also the post-test tasks such as upload. 
I've compiled a list of ambiguous tasks that I am not sure if we want to classify as "setup":
- Compile mongo (this is external to us)
- Compile / make wiredtiger (the failure still shows up - but do we consider this part of the setup process, or compile in itself a test) 
- python config check (checking the python binary matches cmake)
- compile / update wiredtiger docs or similar to adjusting documentation
- build and push antithesis container
Please feel free to review the current tasks, or mention any I have missed. Thanks.

WT-11654 Label setup commands in evergreen to ensure failures are bucketized correctly

---

src/include/serial_inline.h

We want to make updating the last recno in the btree to be thread safe.

WT-11652 Fix data race when updating btree's last record number

---

src/conn/conn_log.c
src/include/log.h
src/log/log.c
src/log/log_slot.c

WT-10207 Changing log slot flags to flags_atomic. Removing debugging added for WT-9796 as the root cause was identified.
(cherry picked from commit 1b6329a945230f76011d0aad7a73b31188104f42)

WT-10207 Change log slot flags to flags_atomic and remove debugging (v6.0) (#8578)

---

test/suite/test_checkpoint_snapshot05.py
test/suite/wttest.py

This test uses synchronous API calls and threads to coordinate concurrent activity, and sensitive to changes in timing.
Add assertion to verify test environment expectations. Both Improving documentation and simplyfing failure identification.
Add free function to wttest to allow cursor instances to be used in `with` statements.

WT-11670 verify test_checkpoint_snapshot05 expectations

---

src/reconcile/rec_write.c

__wt_rec_split buf fix, we shoud use min_split_size, not use split_size / 2, it is more accurate by using min_split_size

WT-11713 Check min_split_size when growing the split buffer in __wt_rec_split

---

src/reconcile/rec_write.c

Reverts wiredtiger/wiredtiger#9658
This ticket is causing reliable test failures in `test-prepare-hs03-hook-timestamp` as described in WT-11741

Revert "WT-11713 Check min_split_size when growing the split buffer in __wt_rec_split"

---

test/cppsuite/how_to_use_cppsuite.md
test/cppsuite/src/main/database_operation.cpp
test/cppsuite/src/main/database_operation.h
test/cppsuite/src/main/test.cpp
test/cppsuite/tests/cache_resize.cpp
test/cppsuite/tests/test_template.cpp

We should be able to validate a workload without the need for the tracking component to be enabled.
The `validate` function has been updated with a new first argument `tracking_enabled`. This one has to be `true` for the default implementation.

WT-11733 Decouple validation from tracking in the cppsuite

---

dist/s_style
dist/s_typedef

Changes:
* `s_style`: Remove the temporary file as long as it's not needed anymore, before the name is changed.
* `s_typedef`: Don't proceed to overwriting a good file if there were any errors or interruptions.

WT-11747 s_all and other s_ scripts in dist/ should clean up when interrupted

---

test/format/checkpoint.c
test/format/format.h
test/format/ops.c
test/format/verify.c

Inspired by WT-11507.
Perform verification of mirror tables after a mirror truncate. Since this can be expensive we always perform verification for small truncate ranges, and only infrequently for larger truncate ranges.
Previously verification always ran on all keys in the tables. This change updates it to allow for iteration over smaller ranges.

WT-11609 Verify mirror tables after a mirrored truncate

---

dist/test_data.py
src/config/test_config.c
test/cppsuite/README.md
test/cppsuite/src/common/constants.cpp
test/cppsuite/src/common/constants.h
test/cppsuite/src/main/test.cpp

When the default configuration is used, validation may not make sense. This will be particularly useful for WT-11346.

WT-11771 Be able to skip the validation stage in the cppsuite

---

test/cppsuite/src/main/database_operation.cpp
test/cppsuite/src/main/transaction.cpp
test/cppsuite/src/main/transaction.h
test/cppsuite/tests/bounded_cursor_prefix_search_near.cpp
test/cppsuite/tests/bounded_cursor_stress.cpp

WT-9466 changed the behaviour of a few cpp tests because the function `try_rollback` was modified. There are two scenarios:
- Rollback if a transaction is active
- Rollback only once the current transaction has reached its target in terms of number of operations
The changes here somehow revert what WT-9466 did to go back to the second scenario wherever expected.
See the JIRA ticket for more details.

WT-11772 Only rollback txn when the target has been reached in the cppsuite

---

bench/workgen/workgen.cpp
bench/workgen/workgen_int.h

The following was happening in testy's [workload](https://github.com/wiredtiger/testy/blob/main/workloads/sample/sample_run.py) when mirroring is enabled:
- A table TA is created but not its mirror TB yet
- A thread T1 selects that table to work on and sees that it should have a mirror associated with it.
- T1 starts updating the in-memory data struct of the table and its mirror. **The information about the mirror is wrong as it has not been allocated yet.**
- The mirror TB is finally created
- T1 keeps working on the table and its mirror but now the information related to TB is different since TB has finally been allocated. The inconsistency leads to different assertions to fire.
See the ticket for more information.
I have also added assertions when an exception is caught in the main …

WT-11045 Create the mirror table before its base in Workgen

---

test/format/random.c

The random cursor would loop calling next and not check that it was requested to stop. Normally that would be fine, but when the stress point for HS search was enabled it became extremely slow and caused task timeouts. I checked the other threads and only the HS thread could have this but it should not have the same stress points.

WT-10691 Reduce delay in stopping the random cursor thread in test format

---

src/txn/txn_rollback_to_stable.c

(cherry picked from commit 5af8d7ffe439462df9c8c67992a1688e90995e40)
(cherry picked from commit d7de14f738f12cd95365e211e3840be046237a48)

WT-11564 Fix RTS to read the newest_txn value only when it exists in the checkpoint (6.0 backport)

---

test/evergreen.yml

With the merge of [EVG-20276](https://jira.mongodb.org/browse/EVG-20276) variables passed into evergreen functions no longer persist across stages. 
The `s3.get` stage of `code-change-report` used to inherit the `dependent_task: coverage-report` field, but now we need to set it explicitly.

Add missing dependent_task arg in code-change-report

---

test/suite/test_checkpoint04.py

The changes made in WT-10671 has a slight bug, where when we perform a retry of the loop we don't account for the extra checkpoint performed by the connection reopen.

WT-11584 Fix test_checkpoint_stats test

---

test/suite/test_verbose04.py

Adding the tiered hook to verbose04 alters the logs produced by WiredTiger, and since verbose04 is checking logs produced by WiredTiger this can break the test.
The logic under test in verbose04 (the "all" configuration item) is not impacted by tiered storage logic so we'll skip this test when using the tiered hook.

WT-11802 Disable verbose04 for tiered hook tests

---

test/suite/test_checkpoint04.py

The previous PR does not work. The reason why is because the specific statistics in the python test has a **no_clear** option, which means that the statistics do not get re-cleared. We need to perform a re-open and fix the number of expected ckpts. However I still see that the test failing. The test is failing due to eatmydata.so which no-ops any fsync which causes the statistic to not be properly updated. As a safety measure increasing the number of tables helps with solving that problem.

WT-11584 fix test checkpoint04 test

---

dist/primitive_check.py
dist/s_define.list
src/include/block.h
src/include/block_cache.h
src/include/block_chunkcache.h
src/include/btmem.h
src/include/btree.h
src/include/cache.h
src/include/capacity.h
src/include/connection.h
src/include/cursor.h
src/include/dhandle.h
src/include/hardware.h
src/include/log.h
src/include/lsm.h
src/include/mutex.h
src/include/os.h
src/include/session.h
src/include/txn.h

This PR adds a `wt_shared` tag to all variables identified in PM-3221 to use concurrency primitives for inter-thread operations. The macro pre-processes away to nothing, and is just used to highlight these variables for future tickets.
I've added a developer link on the Jira ticket to the variable catalog we've built in PM-3221 for reference

WT-10861 Annotate shared variables

---

test/suite/hook_tiered.py
test/suite/test_salvage02.py

Fix two that the python hooks are causing for test_salvage02.
- The tiered hook should skip all salvage logic as salvage is not supported. Update the filter string to catch all salvage tests and not just `test_salvage01`
- The timestamp hook auto-increments timestamps which causes issues with the manually configured `stable_ts`. Use a dedicated `large_updates` function to control this logic.
Co-authored-by: Will Korteland will.korteland@mongodb.com

WT-11823 Fix test_salvage02 for the tiered and timestamp hooks

---

src/session/session_compact.c

Currently, we are not checking if background compaction should be interrupted when the connection closes. This has the consequence of increasing the shutdown time when background compaction is still working since we are not trying to interrupt it.

WT-11826 Always check if background compaction is being interrupted

---

test/suite/test_chunkcache01.py
test/suite/test_chunkcache03.py
test/suite/test_chunkcache04.py

Reduce the capacity of chunkcache tests, when they are run in parallel with the original configs they use up all of the RAM available on our ARM macos test hosts and leave the system unresponsive.

WT-11830 Reduce capacity of chunkcache tests

---

src/block/block_open.c

Defer inserting the new block into the globally visible list in connection in  __wt_block_open until no more errors are possible.

WT-11818 Fix memory leak in __wt_block_open

---

dist/s_docs

Explicitly set locale in `dist/s_docs` so that we get consistent output when running the script across different testing/development environments.

WT-11827 Explicitly set locale for s_docs

---

dist/s_string.ok
src/docs/command-line.dox
src/docs/spell.ok
src/utilities/util_verify.c

The `strict` command can be enabled with the `-S` option when using the `verify` command:
```
./wt -h <db_path> -r verify -S
```

WT-11832 Add the strict option to the wt tool verify command

---

lang/python/setup_pip.py

WT-8633 introduced a Python source directory name change, and missed changing the corresponding place in the setup script. The mismatch was captured during a Python open-source release while testing "pip install <wiredtiger tarball>". 
The fix in this PR is to make the same directory name change in the setup script so that it's lined up with the CMake file.

WT-10466 Line up Python source directory in setup script

---

src/include/serial_inline.h

As described in the Jira ticket changes to `btree-last_recno` are protected by a lock on the rightmost page in the b-tree due to a combination of two conditions:
1. `__col_append_serial_func` must hold a lock on the page being modified, and
2. A column-store append that increases `btree->last_recno` must take place on the rightmost page in the b-tree.
This allows us to drop the compare_and_swap and set `btree->last_recno` normally.

WT-11757 Remove compare_and_swap in __col_append_serial_func

---

test/suite/test_app_thread_evict01.py

This new test test_app_thread_evict01 forces the application threads to perform eviction and at the end, it checks for the stats that at least one application thread is triggered to perform eviction. The eviction behavior is not deterministic so the plan is to turn off the test now and create another ticket to modify the test.

WT-11861 Turn off the new test_app_thread_evict01 test

---

src/conn/conn_cache.c
src/conn/conn_open.c
src/evict/evict_lru.c
src/include/cache_inline.h
src/include/session.h
src/include/wt_internal.h
src/session/session_api.c
src/support/hazard.c

Code style improvements identified during the hazard pointer algo review. I've named this based on the major change, but there are three modifications in total:
1. Take the four hazard pointer fields in session (`hazard_size`, `hazard_inuse`, `nhazard`, `hazard`) and move them into a new `WT_HAZARD_ARRAY` struct. They've also been renamed as follows:
```
hazard_size  -> hazards.size
hazard_inuse -> hazards.inuse
nhazard      -> hazards.active
hazard       -> hazards.arr
```
2. Add an assert in diagnostic mode if a session is closed while still holding hazard pointers. Previously we'd print an error traces and free the pointers. Behaviour is unchanged in release mode.
3. `hazard_size` (now `hazards.size`) is no longer marked as `wt_shared` as this field is only ever accessed by the session …

WT-11510 Split hazard pointer array fields into their own structure

---

test/suite/test_chunkcache01.py
test/suite/test_chunkcache02.py
test/suite/test_chunkcache03.py
test/suite/test_chunkcache04.py

We have an uninitialised spinlock on macos for the python chunkcache tests. Disable them to be fixed in WT-11865

WT-11864 Disable python chunkcache tests on macos

---

bench/workgen/workgen.cpp

Workgen usually retries an operation after getting a `WT_ROLLBACK` error. However, this may create inconsistencies when mirroring is enabled. When a mirrored table faces a `WT_ROLLBACK` operation, Workgen no longer retries the operation.

WT-11879 Give up mirrored operation when Workgen gets WT_ROLLBACK

---

src/conn/conn_handle.c
test/suite/test_chunkcache01.py
test/suite/test_chunkcache02.py
test/suite/test_chunkcache03.py
test/suite/test_chunkcache04.py

Not sure how this managed to get as far as it did last time around, but oh well. Did a macOS patch build, it's all green now.

WT-11865 Initialise and teardown chunk cache metadata lock

---

test/csuite/CMakeLists.txt
test/evergreen.yml
test/evergreen/evg_cfg.py

The changes done in this pull request aims to clean up the csuite tasks and run them in one task under parallel jobs. I measured the time for the csuite task in the normal and ASAN variant. In the normal variant, the task roughly takes ~30 minutes and for ASAN it takes 90 minutes, to remedy this problem I have made the ASAN variant not running the long running tests and i have updated the long running labels as well, with both the additions i have gotten it down to 24 minutes. 30 minutes is a good target and acceptable for pull request testing.

WT-11671 Compact short csuite tests into one task variant

---

dist/stat_data.py
src/block_cache/block_chunkcache.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

This solution differs from what was initially mentioned in the ticket.
My rationale for this is that in the case of DRAM, we should not limit the behavior by requiring chunk sizes to be multiples of the capacity. This also adds extra complexity to the code.
Additionally, for the FILE case, it should be clear that the inability to allocate more chunks is not due to exceeding the capacity in bytes. Instead, it results from using a configuration with a significantly larger chunk size, which reduces the total number of pre-calculated chunks that can fit into the chunkcache's bitmap. 
Therefore, including a stat in the same location could be useful for future diagnosis.

WT-11873 Add stat if capacity exceeded bitmap

---

bench/wtperf/wtperf.c

Reverts wiredtiger/wiredtiger#9804
Boolean logic was incorrectly transformed in at least one instance `wtperf.c:2344`

Revert "WT-11886 Cleanup expressions using boolean options"

---

src/session/session_prefetch.c

The purpose of this PR is to align with the tech design which states that once prefetching is configured on a session, prefetching will automatically be turned on for all cursors with the session regardless of how beneficial it may be for the particular table that the cursor is open on.

WT-11758 Consider prefetching on the session level instead of cursor level

---

test/evergreen.yml
test/unittest/CMakeLists.txt

Small naming change so that our unit tests explicitly mention catch2 to reduce the naming collision between these tests and the Python `unit-test-bucket*`. We've decided to rename the catch2 tests as they're newer and long running metrics may be impacted by a rename of our python tests.
Once this is in we'll add a new "Catch2 Unit Tests" option in the Jira `Components` field

WT-11898 Rename catch2 unit tests in evergreen to mention catch2

---

dist/api_data.py
src/btree/bt_vrfy.c
src/config/config_def.c
src/include/wiredtiger.in
src/utilities/util_verify.c
test/suite/test_verify.py

WT-9821 Add option to verify to report all data corruption in a file (#8312)
(cherry picked from commit bb2bb7d8b680fe51351d7bce8ccc3f6d66eef770)
WT-10601 Fix wt verify -c failure when first block on page is corrupt (#9209) (#9294)
(cherry picked from commit 28f2aea2b5a703aac9247e136ed32c677336c4a0)
Co-authored-by: jchen <29520270+jiechenbo@users.noreply.github.com>
(cherry picked from commit b5af7beeac8f79612f6302128e03d87a83901b77)

WT-9821 WT-10601 (v6.0 backport)

---

test/evergreen.yml

This was breaking a lot of stuff - none of the options after this one were getting applied. The shell just took the subsequent lines as a command saying `NONSTANDALONE=1 ...`, with no effect.

WT-11938 Allow Evergreen to apply options after ENABLE_TCMALLOC

---

src/block/block_compact.c
src/block_cache/block_mgr.c
src/btree/bt_compact.c
src/include/block.h
src/include/compact.h
src/include/extern.h
src/session/session_compact.c

I've replaced the message counter with a last progress time variable in the `session->compact structure`. Since the `session->compact->begin` was set before the checkpoint, the message counter still had the problem of playing catch up when the first compact checkpoint took a long time.
Alternatively, if we want to keep msg_count, it would have to be initialised in `__session_compact` before the first checkpoint, instead of `__wt_compact` to avoid it being reset to 0 after every iteration. Although this would require passing it into `wt_compact`.

WT-9607 Fix timing of compact progress messages

---

dist/s_string.ok
test/csuite/timestamp_abort/main.c
test/model/CMakeLists.txt
test/model/src/core/data_value.cpp
test/model/src/core/util.cpp
test/model/src/core/verify.cpp
test/model/src/driver/debug_log_parser.cpp
test/model/src/include/model/core.h
test/model/src/include/model/data_value.h
test/model/src/include/model/driver/debug_log_parser.h
test/model/src/include/model/kv_database.h
test/model/src/include/model/kv_table.h
test/model/src/include/model/util.h
test/model/src/include/model/verify.h
test/model/test/CMakeLists.txt
test/model/test/common/include/model/test/wiredtiger_util.h
test/model/test/common/util.cpp
test/model/test/common/wiredtiger_util.cpp
test/model/test/model_basic/main.cpp
test/model/test/model_transaction/main.cpp
test/model/tools/CMakeLists.txt
test/model/tools/model_verify_debug_log/main.cpp

This PR adds support and tooling for parsing the debug log into the model operations, both directly (for efficiency) and via JSON export (for easier debugging).
Don, Will: Let me know if you'd like me to go over these changes with you, as this is also a fairly substantial PR.

WT-11614 Parse the debug log into a set of corresponding functional model operations

---

src/evict/evict_page.c
src/reconcile/rec_visibility.c

WT-11778 Restricting eviction of metadata pages by threads that have active updates on them. Restricting dirty eviction to sessions with snapshot isolation.

WT-11778 Restricting dirty eviction to sessions with snapshot isolation and of metadata pages

---

test/evergreen.yml
test/evergreen/python_version_check.py

CMake obsoleted the non-versioned Python executable/library/include strings, plus the code for explicitly setting those wasn't running for the arm64 variant.

WT-11888 Fix Evergreen Python version detection on macOS

---

test/evergreen.yml
test/evergreen/doc_update.py

In the past, we used a bot account "svc-bot-doc-build" (and a static token) to push document updates to the "wiredtiger.github.com" repo. Now that the bot account needs to be moved out (see WTBUILD-100 for context), we had to switch to using Github App.
A new Github App "doc-build-bot" was created (with credentials provisioned in the Evergreen project). The changes in this PR are to leverage the new Github App token for "git push".

WT-11885 Apply Github Apps for the doc-update task

---

src/session/session_compact.c

During compaction, we perform three checkpoints with the `force=1` configuration which forces the checkpoint on all the btrees. This might generate unnecessary work. We only have to checkpoint the btrees that have been compacted. Since there are two consecutive checkpoints at the end of compaction, mark the compacted btree as dirty to ensure checkpoint runs on them. See the JIRA ticket for more details.

WT-9628 Mark the targeted btree as dirty to avoid forcing checkpoints when compacting

---

test/evergreen.yml

The `doc-update` Evergreen task failed with a different reason after the merge of WT-11971. 
```
[2023/11/14 12:25:55.911] python: can't open file '/data/mci/5a8f72be949b713593899173fb10809e/wiredtiger/test/evergreen/doc_update.py': [Errno 2] No such file or directory
--
[2023/11/14 12:25:55.913] Command 'shell.exec' in function 'update wiredtiger docs' (step 3.2 of 5) failed: shell script encountered problem: exit code 2.
```
It turns out the "compile wiredtiger docs" func (the one called before the failing "update wiredtiger docs" func) has the logic of checking out each of the configured doc_update_branches, which left a branch without the script for the following "update wiredtiger docs" func to work with (and failed). 
The fix is to checkout "develop" branch before calling the Python …

WT-11986 Fix missing script issue for the doc-update task

---

test/suite/test_bug019.py

WT-11953 Make sure pre-allocated log files exist at the start of every

---

src/btree/bt_split.c

cache_inmem_split Statistics perfect,  it should be after "split_parent" sunccess, So we can increase the count

WT-11959 Don't increment cache_inmem_split statistic when split fails

---

test/evergreen.yml

The right tests for the right sanitizers will be evaluated through WT-11989. As it is currently generating random timeouts and blocking other tickets to move on, moving the long-running C tests to the `! Ubuntu 20.04` variant from `! Ubuntu 20.04 MSAN`.

WT-11583 Remove long running C tests from sanitizers

---

test/csuite/CMakeLists.txt
test/evergreen.yml

After [WT-11583](https://jira.mongodb.org/browse/WT-11583):
- Several C tests are not taking that long to run (< 100 seconds)
- Since only a few of them are left, we don't need multiple buckets to run the remaining tests
- A large instance is not necessary either
See the JIRA ticket for the patch build. Please note that these labels might be re-introduced when they will be executed on slower variants, see WT-11989.

WT-11996 Remove long-running label for several C tests

---

src/include/api.h
src/include/session.h
src/include/wt_internal.h
src/session/session_api.c

Code improvements as identified by the PM-3221 code review of the API macros. 
Three changes here:
1. Remove the use of barriers and instead use a lock. This code only runs in diagnostic mode so any possible slowdowns are low impact
2. With the addition of the lock, move the three related variables into a `__wt_thread_check` struct for cleanliness
3. Expand the single letter variables used in our macros to words that describe the fields. The changes were `h -> struct_name` and `n -> func_name`. I've left `s` and `dh` alone as they're commonly used to represent session and dhandle in the codebase.

WT-11806 Replace shared variables in API macro code with a lock, clean up function arguments

---

src/include/btree_inline.h

For example, if cache_size is set to a small value,  btree->maxleafpage may be greater than btree->splitmempage.

WT-11954 Account for the case where the max in-memory page size is smaller than the max on-disk page size

---

bench/workgen/workgen.cpp

Everything is the same as #9876 except the last commit 4eff1ef5052a1e3f7d9cd1694614c3eda30c0e4b which inits the `ret` value as `WT_DECL_RET` would do.
The tests that failed after the first attempt are now passing, see the PR testing.

WT-12009 Add error code in Workgen exceptions

---

test/suite/test_import01.py

Before the suggested changed, we would compare `None` with `None` as `sort()` does not return the sorted list. I have also tried to simplify the information that is unique and that cannot be compared: the `id` and `checkpoint`.

WT-12018 Fix metadata info comparison in test_import_base

---

dist/api_data.py
src/btree/bt_random.c
src/config/config_def.c
src/cursor/cur_file.c
src/evict/evict_lru.c
src/include/cursor.h
src/include/extern.h
src/include/wiredtiger.in

This ticket deals with adding a new config API and adding a RNG state to the cursor structure. The reason is that using the session's RNG can reset the expected outcome of cursor's random operation call and can return back the same records based on if the session is re-open or not. This change makes sure that cursor random operation is truly random regardless of the session re-open.

WT-11532 Fix session reset RNG by using cursor RNG

---

src/session/session_dhandle.c

See ticket comments for patch build results. Will look at backports once this is in.

WT-12036 Add Windows-specific scheduling workaround when locking dhandles

---

test/suite/test_chunkcache05.py
test/suite/test_chunkcache06.py

There were two bugs here:
* `test_chunkcache05` simply had the logic the wrong way around.
* For both of the new tests, we needed to avoid having the chunk cache in the config. It still opens WiredTiger even if we immediately return in the main `test` function, and that's enough to trip the `mmap` sanity check.

WT-12038 Correctly skip chunk cache tests on big-endian platforms

---

src/include/verbose.h
src/support/generation.c

In diagnostic mode WiredTiger will increase the verbosity levels for eviction and checkpoint just before generation drain times out which gives us better insight into what causes the timeout and resulting abort. 
However it's possible that generation drain becomes unstuck after the verbosity levels are increased, but before the timeout occurs. If this happens the original verbosity levels should be restored to prevent noisy traces.

WT-12012 Restore original verbose levels if gen_drain becomes unstuck after increasing verbose levels

---

src/conn/conn_log.c
src/log/log.c

I wanted to get this in before waiting for Acq/rel semantics. Then we can simply rename this barrier.

WT-12042 Adding read ordering when reading log_close_fh

---

test/model/CMakeLists.txt
test/model/src/core/core.cpp
test/model/src/core/kv_database.cpp
test/model/src/core/kv_table.cpp
test/model/src/core/kv_table_item.cpp
test/model/src/core/kv_transaction.cpp
test/model/src/core/kv_transaction_snapshot.cpp
test/model/src/core/util.cpp
test/model/src/core/verify.cpp
test/model/src/driver/debug_log_parser.cpp
test/model/src/include/model/core.h
test/model/src/include/model/driver/debug_log_parser.h
test/model/src/include/model/kv_database.h
test/model/src/include/model/kv_table.h
test/model/src/include/model/kv_table_item.h
test/model/src/include/model/kv_transaction.h
test/model/src/include/model/kv_transaction_snapshot.h
test/model/src/include/model/kv_update.h
test/model/src/include/model/util.h
test/model/src/include/model/verify.h
test/model/test/model_checkpoint/main.cpp
test/model/tools/model_verify_debug_log/main.cpp

This PR extends WT-11615 by adding debug log parsing for checkpoints. It is surprisingly long for what it does to support WiredTiger's transaction IDs, and also because WiredTiger's transaction IDs are not unique across restarts.
Feel free to not scrutinize changes to the model's test code, as this is again just a test for a test.
Thank you!

WT-11616 Extend the debug log parser to support checkpoints

---

src/conn/conn_chunkcache.c

This was segfaulting:
1. The initialisation code would call `__chunkcache_apply_metadata_content` before initialising the the condition variable.
2. The chunk cache would fill up and call eviction.
3. Eviction would attempt to push the removal to the content management queue
4. It then tried to signal the "there's stuff on the queue" condition variable - but that was still null.

WT-12029 Initialise chunk cache condition variable earlier

---

src/conn/conn_compact.c
test/suite/test_compact05.py
test/suite/test_compact06.py

If one tries to reconfigure the background compaction server while it is running with a different exclude list, an error is returned.

WT-12059 Keep the exclude list in the background compaction configuration string

---

test/suite/test_chunkcache01.py
test/suite/test_chunkcache02.py
test/suite/test_chunkcache03.py
test/suite/test_chunkcache04.py
test/suite/test_chunkcache05.py
test/suite/test_chunkcache06.py

This introduces some general infrastructure for avoiding races on statistics. It's pretty dumb right now, but it's mostly abstracted away and could easily be made more sophisticated. I've left this running overnight and it definitely fixes `test_chunkcache05` and `06`, and I strongly suspect it'll also fix `02`.

WT-12053 Resolve a large number of statistics races in chunk cache tests

---

test/csuite/timestamp_abort/smoke.sh

WT-12073 Disable timestamp_abort and backup until fix is complete

---

test/model/src/core/kv_database.cpp
test/model/src/core/kv_table.cpp
test/model/src/core/kv_table_item.cpp
test/model/src/core/kv_transaction.cpp
test/model/src/core/kv_transaction_snapshot.cpp
test/model/src/driver/debug_log_parser.cpp
test/model/src/include/model/driver/debug_log_parser.h
test/model/src/include/model/kv_database.h
test/model/src/include/model/kv_table.h
test/model/src/include/model/kv_table_item.h
test/model/src/include/model/kv_transaction.h
test/model/src/include/model/kv_transaction_snapshot.h
test/model/src/include/model/kv_update.h
test/model/src/include/model/util.h
test/model/test/model_basic/main.cpp
test/model/test/model_checkpoint/main.cpp
test/model/test/model_rts/main.cpp
test/model/test/model_transaction/main.cpp

I added support for non-timestamped tables (tables that use logging), as this is a prerequisite for being able to integrate the test with timestamp_abort. The fix mostly boils down to:
* Changing timestamps to 0 at the top-level API (i.e., in `kv_table`) for non-timestamped tables. If you find the fix to be too ugly, I can switch it to a somewhat more verbose solution that uses "if" statements instead of inline functions to fix the timestamp—if that's better :)
* Adding checkpoint sequence numbers for imported checkpoints, which is unfortunately necessary consequences of how WiredTiger's checkpoint get their snapshots. (Explained in more detail in one of the comments.)
As usual, feel free to skip or just skim changes to the tests. Thank you!

WT-12070 Extend the model to support tables with logging

---

dist/stat_data.py
src/include/stat.h
src/include/wiredtiger.in
src/session/session_prefetch.c
src/support/stat.c

I believe we decided to disable pre-fetching for special operations as it was not expected to work for things like salvage, but would there be any other special operations (apart from verify) which should be using prefetching when possible?

WT-12080 Disable pre-fetching for special operations apart from verify

---

dist/api_data.py
src/config/config_def.c
src/conn/conn_compact.c
src/include/connection.h
src/include/wiredtiger.in
src/session/session_compact.c
test/suite/test_compact06.py

- Added a new configuration item `run_once` for the background compaction
- When configured with `run_once`, the background compaction will go to sleep after a full iteration

WT-12031 Add a new configuration item for background compaction to run once

---

dist/stat_data.py
src/conn/conn_chunkcache.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_chunkcache01.py
test/suite/test_chunkcache05.py
test/suite/test_chunkcache06.py

We do a checkpoint then immediately close the connection (to restart WT), so there wasn't enough time to load the content into the chunk cache, enqueue all of the metadata entries, wake up the metadata thread, and get all of the entries persisted to disk. In this case, there will be nothing to reload, hence the zero stat.
After this change, we'll wait for the number of metadata entries written out to be non-zero before restarting.

WT-12075 Fix stats testings in test_chunkcache05 and 06

---

src/include/extern.h
src/include/txn_inline.h

Originally when this assert was created the prepare state check made sense but a few changes over the year have made it redundant.
I noticed while reviewing the code that this function is exported and accessible from anywhere inside WiredTiger when it is only used within the `txn_inline.h` file so I removed the `__wt`.

WT-11957 Remove prepare state check from assertion

---

test/csuite/CMakeLists.txt
test/evergreen.yml

Tag the longer running csuite tests with `long_running` so they'll be excluded from `csuite-tests-pull-request`. This keeps the runtime of `csuite-tests-pull-request` under 20 minutes for fast PR testing turnaround.

WT-12050 Add long_running label to csuite tests exceeding 20 minutes

---

src/history/hs_conn.c
src/txn/txn_recover.c
test/suite/test_checkpoint31.py

If the database has a history store file, regardless of whether it is read-only or read-write, mark the connection with HS open. This allows access to the data in the history store even while utilising a read-only connection.

WT-12013 Set the connection with HS open flag if it exists in the database.

---

test/csuite/timestamp_abort/main.c
test/model/src/core/verify.cpp
test/model/src/include/model/kv_table_item.h
test/model/src/include/model/verify.h
test/utility/misc.c
test/utility/test_util.h

This PR adds model-based verification to `timestamp_abort`. It does not run automatically, because it takes a long time to run, and enabling it also requires the log remove configuration to be set to false, resulting in many GB's of log files produced even for short runs.
The PR also includes a few small changes to the verifier itself, so that we can get a better error message in the event of a mismatch.

WT-11619 Integrate the RTS model with test/timestamp_abort

---

src/docs/arch-timestamp.dox

WT-12048 Update architecture guide timestamp documentation

---

src/block_cache/block_chunkcache.c

This would previously crash with an assertion in the filesystem layer that the read-only flag must be set on a file handle if the connection is read-only. Having a read-only connection with an on-disk chunk cache doesn't make sense (to me), so it now fails like this:
```
[1701986486:771353][1716541:0x7f2ba8cb0000], connection: [WT_VERB_DEFAULT][ERROR]: __wt_chunkcache_setup, 1241: on-disk chunk cache incompatible with read-only connection: Invalid argument
Re-opening the connection failed Error: Invalid argument
```

WT-12063 Don't permit on-disk chunk cache combined with a read-only connection

---

test/csuite/CMakeLists.txt
test/evergreen.yml

Note this PR is being delivered to the 7.2 branch.
We've gone through a fair few changes to this test recently. Rather than backport all of those tickets this PR updates the definition of `csuite-long-running` and use of the `long_running` label to be identical with the head of develop. This will also be backported to 7.1.
Similar to the head of develop `csuite-long-running` takes 3.5 hours to execute and is well within the 5 hour timeout.

WT-12100 Fix csuite-long-running timeout with MSan

---

test/suite/test_compact06.py

The assertions verify background compaction has done some work, make sure it is the case before turning off background compaction. Once background compaction has processed a file, we can proceed with the remaining part of the test.

WT-12095 Wait for background compaction to process the HS

---

dist/s_python

git ls-files seems to automatically exclude everything in build directory and also git files. Have not implemented a fallback

WT-11248 used git ls-files to exclude all files in build directory

---

src/block/block_addr.c
src/block/block_write.c
src/block_cache/block_mgr.c

One output in decimal and one in hexadecimal, keeping the output format consistent and helping us to understand the code.

WT-12128 Make checksum logging more consistent

---

test/suite/test_salvage01.py

We need to explicitly disable pre-fetching when re-opening the connection because our current logic that skips pre-fetching corrupted contents relies on the `WT_CONN_DATA_CORRUPTION` flag which won't be set anymore because the connection was closed.

WT-12135 Don't re-open connections and sessions with pre-fetching enabled after damaging tables

---

dist/stat_data.py
src/btree/bt_prefetch.c
src/btree/bt_vrfy.c
src/conn/conn_prefetch.c
src/include/error.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

Reverts wiredtiger/wiredtiger#9949
The evergreen failures today meant that PR testing didn't run and a non-American spelling of `optimisation` slipped into develop that's tripping up `s_all`. Reverting to correct the spelling

Revert "WT-11759 Evaluate whether prefetch errors should be passed up to users"

---

bench/tiered/push_pull.c

Coverity reporting values for unchecked return values.
Add `testutil` checks to return values.

WT-10707 Check return values in push_pull.c

---

bench/workgen/workgen.h

Alphabetised variable and function names, excluding some that are already sorted in a specific order i.e. Track struct has getters sorting by duration of time

WT-11481 Alphabetize Workgen variables

---

test/suite/test_compact06.py

Since this test expects compaction to do work and compaction is not supported with tiered storage, disable that scenario.

WT-12061 Skip compact06 with tiered storage

---

test/format/ops.c

To avoid integer overflow, cast a 32 bit unsigned integer to a 64 bit integer.

WT-10592 cast 32 bit uint to 64 bit

---

test/suite/test_import01.py

- Made changes to config_compare
- replaced regex functionality with list comprehension
- created strip_subconfigs helper function to remove the fields that we wont be comparing (id, checkpoints)
- Added named checkpoint test.

WT-12030 Fortify config_compare in test import base and add named checkpoint test

---

src/include/txn_inline.h

The scope of this PR is to implement ordered reads in the two problem areas identified in the ticket. Further work will be made in a following ticket to implement the getter/setter functionality discussed in the ticket.

WT-11469 Missing read barriers when reading the prepared state and durable_ts

---

test/evergreen.yml

(cherry picked from commit 54c99901cb9426245361563b4edb61e963c656a4)

WT-12147 Temporarily disable clang-analyzer (v6.0 backport)

---

test/suite/test_bug010.py

@ddanderson: it look like the file descriptor leak has gone away -- hopefully because the changes to the block manager and file cleanup have addressed it. There's a bit of commentary on the ticket. This PR just re-enables the problematic python test.

WT-11354 Re-enable test_bug010 on tiered storage

---

src/config/config_api.c
src/config/config_check.c
src/session/session_api.c

Ensure `ret` is either `0` or `WT_NOTFOUND` when parsing configuration items.
Note: those warnings were detected after enabling `scan-build` again in WT-12144.

WT-12169 Check ret value when parsing configuration

---

test/csuite/wt8659_reconstruct_database_from_logs/main.c
test/salvage/salvage.c
test/utility/lazyfs.c
test/utility/misc.c
test/utility/test_util.h

WT-10754 replace all instances of ...... testutil_check(system(buf)); with the new testutil_system() function. Unsure about the comment on macros and how I should go about doing it.

WT-10754 replacing certain system() calls with testutil_system() 

---

dist/api_data.py
src/btree/bt_vrfy.c
src/config/config_def.c
src/include/wiredtiger.in
src/utilities/util_verify.c
test/suite/test_verify.py

Note that this PR contains the fallout WT-10601 (Fix wt verify -c failure when first block on page is corrupt)

WT-9821 Add option to verify to report all data corruption in a file (v5.0 backport)

---

dist/s_string.ok
src/checksum/zseries/crc32-s390x.c
test/csuite/wt2695_checksum/main.c

See pinned comment on the ticket for a full description of the bug.
Not sure yet if this needs to go upstream - AFAICT both the "Linux on Z" IBM repo, and Linux itself are broken in the same way. I suspect they aren't checksumming small, misaligned values. And neither were we, until the new tests got merged.
(Adding our interns to the code review since this is kind of an interesting one.)

WT-12077 Fix zSeries checksum code

---

test/format/replay.c

Coverity defect analysis: Out-of-bounds access detected.
In `replay.c`, `replay_committed` function - added `testutil_assert` to avoid out-of-bounds access.
Tracing the error:
1. `tinfo->lane` is initialized to LANE_NONE (i.e. u32_max)
2. `tinfo` passed into `commit_transaction`
3. `tinfo` passed into `replay_committed` where `lane` is assigned to `tinfo->lane` and then an out-of-bounds access attempt occurs at `WT_PUBLISH(g.lanes[lane].in_use, false)`

WT-10593 Add assert in replay_committed to avoid out-of-bounds access

---

test/suite/test_backup18.py

Enhance the scenario in backup18 by simulating a crash and restart once the backup force_stop is invoked.

WT-11578 Improve backup force_stop and full incremental testing

---

test/evergreen.yml

The tests are only tags "pull_request" tasks. They are grouped into three (now two) tasks by test_config value.
* cppsuite-background-compact-default - 1 test, test_config: debug_mode=(background_compact,cursor_copy=true)
* cppsuite-combined-cursor-copy - 11 tests, test_config: debug_mode=(cursor_copy=true)
* cppsuite-combined-blank - 2 tests, test_config not specified - No longer needed. Added to cppsuite-combined-cursor-copy.
The original 9 + 2 = 11 tasks have been deleted as requested by LukeP.

WT-11842 Compact/group all short cppsuite default tests into a few evergreen tasks

---

test/csuite/timestamp_abort/main.c

checkpoint file.
This takes care of the first item in this old ticket. The second item in the ticket (adding a clean shutdown option) is a lot more involved and I don't plan to do it.

WT-3515 Abort the child and exit the parent if child never creates

---

test/utility/tiered.c

Reverts wiredtiger/wiredtiger#10017
Remove incorrect usage of WT_ASSERT to prevent future complications.
Remove the WT_SESSION_IMPL * cast.

Revert "WT-10106 dereference null pointer"

---

dist/s_all

Summary of the change:
* When run in terminal, `s_all` will interactively display the currently running script name or names.
* More robust flags check: will error on unknown flags.
* Display help on `-h`.

WT-12247 Make s_all more interactive

---

test/suite/run.py

wiredtiger/test/suite/run.py parses the --ignore-stdout parameter incorrectly. It should check for -ignore-stdout not --ignore-stdout since one - has been removed already.

WT-12255 Fix parsing the --ignore-stdout param of the WT python test suite.

---

src/docs/arch-backup.dox

Update the WiredTiger backup architecture section to include what the WiredTiger.backup does and how it replaces the WiredTiger.wt file.

WT-11775 Update architecture guide on WiredTiger backup

---

dist/s_release

We removed the dead `-A` flag from `s_all` in WT-12198, but missed one usage in `s_release`. This failure was silently ignored until we fixed up `s_all`'s error reporting in WT-12247, and now this is causing the `package` task to fail on each run.
This PR removes the deprecated use of the `-A` flag in `s_release`

WT-12258 Remove use of deprecated -A flag in s_release

---

src/btree/bt_vrfy.c
src/support/timestamp.c

Have added workgen info to wt-verify dump output.
We have attempted to align the columns for easier reading, it is currently hard coded just as a demonstration to see if this is something that is even wanted (this is not in the ticket scope). Downsides of aligning the columns is mostly that we will be adding unnecessary white space in most columns, which causes the output to wrap on the cmd line (which makes it more difficult to read anyways).

WT-11913 Include write generation information wt verify dump

---

test/evergreen.yml

Fix PATH env variable in hang analyzer to generate python core dump
(cherry picked from commit 6182fab3e84fb35ab918463c5a4dd1770d6b9978)

WT-12211 Fix PATH env variable in hang analyzer to generate python core dump (#10078) (v6.0)

---

test/csuite/schema_abort/main.c

There's a more full explanation of the change in the ticket comments.

WT-11325 test_schema_abort: read stable timestamp before checkpointing

---

src/cursor/cur_file.c
src/evict/evict_page.c

I tried to reproduce this issue but it is too specific and hard to trigger.

WT-11529 Disable reconciliation when reading a checkpoint

---

test/evergreen.yml

The pre-merge testing (Commit Queue patch builds) takes over 50 mins to finish these days, with the longest-running task `make-check-test` (from the "! Ubuntu 20.04 Minimal" builder) taking over 49 mins.  
The changes in this PR are aimed at bringing down the pre-merge testing turnaround time to under 30 mins, which includes:
- Give the existing `csuite-tests-pull-request` task a more generic name to reflect "running time" instead of "where it's used".
- Use the renamed `csuite-tests-pull-request` task to replace the `make-check-test` task in the "! Ubuntu 20.04 Minimal" builder.
As a tradeoff, this solution reduces the test coverage ("csuite tests" is a major part of "make check tests") for the pre-merge testing to achieve faster turnaround time. The full `make-check-test` has been …

WT-12274 Reduce pre-merge testing turnaround time

---

test/suite/test_prefetch02.py

As part of bug fixes for WT-12222 and WT-12229, disable the FLCS scenario as it is the suspected failure mode.

WT-12275 Disable FLCS scenario from test_prefetch02.py

---

src/txn/txn_ckpt.c
test/suite/test_timestamp02.py

This is additional code to ensure applications don't set timestamps in the wrong order before taking a checkpoint:
- Added a check so we never take a checkpoint when the stable timestamp is less than the oldest timestamp, otherwise we could persist invalid data.
- Modified an exiting test as the timestamps were out of order and closing the connection would trigger a checkpoint that would hit the newly added assertion.

WT-12246 Check timestamps are in order when taking a checkpoint

---

src/utilities/util_main.c

Add note - provide a home directory or check provided home directory is correct.
[Prior approach](https://github.com/wiredtiger/wiredtiger/pull/10102) provided usage info for the wt tool commands but was not extensible to some edge cases

WT-12232 Add check home directory message for incorrect wt tool usage

---

examples/c/ex_all.c
src/conn/conn_api.c
src/include/wiredtiger.in

Reverts wiredtiger/wiredtiger#9932
Revert in anticipation of complications with respect to the work on optimizing configuration parsing.

Revert "WT-12083 Extend conn_api.c to support new get_configuration method"

---

test/csuite/timestamp_abort/main.c
test/csuite/timestamp_abort/smoke.sh

(cherry picked from commit 592eea605d234e810c720e302f1aa59ea6e54ef4)

WT-12110 Disable timestamp_abort backup tests in the compatibility mode (#9967)

---

bench/workgen/runner/many-dhandle-stress.py
bench/workgen/runner/skiplist_stress.py
bench/workgen/runner/split_stress.py
test/evergreen.yml
test/suite/test_gc03.py

The JSON format is necessary to process generated stats in T2. While most tests generate stats in the JSON format, a few don't. This PR updates a few tests left behind.

WT-12308 Generate stats in JSON formats in several tests

---

test/evergreen.yml

This is a pretty straight forward change. Most of the work took place on the platform config side.
A while back we updated the `configure wiredtiger` task but missed the `CLANG_C_VERSION` and `CLANG_CXX_VERSION` settings. This meant all of our `compile-clang` tasks defaulted to the mongotoolchain instead of using older clang versions as intended.
During this period where the wrong version of clang was used there we installed more recent versions of gcc on the host. Non-mongotoolchain versions of Clang use the latest version of gcc for the C runtime, and assume we can use the same version for the C++ libraries. Since we had gcc11 on the host they also tried to use `/usr/include/c++/11` libraries, but it wasn't installed and gave us `fatal error: 'algorithm' file not found` errors.
Now that …

WT-11239 Add CLANG_C/CXX_VERSION compile flags to the configure wiredtiger task

---

src/block/block_compact.c

Example:
```
[WT_VERB_COMPACT_PROGRESS][DEBUG_1]: compacting test_compact04-0.wt for 0 seconds; reviewed 2243 pages, rewritten 567 pages (12MB). Approx. 100% of the estimated work done. More work might have been detected since the start of the operation
```

WT-12311 Update compact progress message related to estimated work

---

src/conn/conn_prefetch.c
src/session/session_prefetch.c

Move the check that access `prefetch_prev_ref` to avoid race conditions that could lead to invalid memory access.

WT-12301 Fix invalid memory access of prefetch_prev_ref

---

test/suite/wttest.py

WT-11101 introduced a new abstract class `AbstractWiredTigerTestCase` which implements a new `failed()` method. This is currently being overridden by the existing `failed` method in the class `WiredTigerTestCase`. This results in the `passed` variable being incorrectly set and therefore failing to preserve database files on failure. I've removed the original `failed` method so that the correct method is used.

WT-12261 Fix python test suites failing to preserve files

---

test/checkpoint/test_checkpoint.c
test/utility/test_util.h
test/utility/tiered.c

Second try :-) 
When we run `test_checkpoint` with the `-r` (# of runs) option, it winds up calling `testutil_tiered_begin()` multiple times. But that function checks and asserts that it is only called once. 
This adds a `testutil_tiered_end()` functions to clear the problem flag. It also gives us a matching pair of functions for any future tiered storage state we need to initialize or clear when opening and closing a connection.

WT-12330 Reset testutil tiered storage options when closing connection

---

test/format/wts.c

(cherry picked from commit 8068826997686f2595760d4fa154381c0c0d946f)
Note that I have disabled the failpoint `failpoint_eviction_fail_after_reconciliation` is known to cause trouble on 5.0: WT-12318. See this commit: 235a8f3b79c19a67f5c0eb7a605b39d0afc7f4de.

WT-12316 Fix test/format timing stress options (#10140) (#10143)

---

src/block/block_compact.c

Over time, the file may change, especially if there are concurrent writers. It is worth re-estimating the file once the expected work is done to refresh.

WT-12319 Estimate compaction work again when expected work is done

---

dist/s_string.ok
test/model/CMakeLists.txt
test/model/src/core/kv_table_item.cpp
test/model/src/core/random.cpp
test/model/src/driver/kv_workload_generator.cpp
test/model/src/driver/kv_workload_sequence.cpp
test/model/src/include/model/driver/kv_workload.h
test/model/src/include/model/driver/kv_workload_generator.h
test/model/src/include/model/driver/kv_workload_runner.h
test/model/src/include/model/driver/kv_workload_runner_wt.h
test/model/src/include/model/driver/kv_workload_sequence.h
test/model/src/include/model/kv_table_item.h
test/model/src/include/model/random.h
test/model/src/include/model/util.h
test/model/test/common/util.cpp
test/model/test/model_workload/main.cpp

This PR implements a workload generator using the primitives built into the model. The PR is fairly long and complicated; I'll be happy to jump on Zoom to go over anything.
I tried to explain the generation process in fairly extensive comments in `kv_workload_generator::run`, but here is the TL;DR: It generates a fully sequential workload, then it finds dependencies between transactions, assigns timestamps, and creates a "concurrent" workload schedule with overlapping transactions (that satisfies the dependencies). The main reason for this is that this allows me to generate much more interesting workloads than the "typical" workload generators, which play tricks such as partitioning key space and timestamps between threads.
The PR also includes fixing a bug where calling `get` without a …

WT-11621 Implement a workload generator for the model

---

src/cursor/cur_backup.c
src/session/session_api.c

The original code was a bit weird. By the point of `__session_open_cursor_int` we know our URI and might have a cursor to dupe, making me think that the `or` logic in the if is redundant. 
I also made a change from what was originally suggested and instead of placing this message in `__session_open_cursor_int` I put it in `__wt_curbackup_open`. That made the most sense to me and also means we really don't need a URI comparison to begin with. I then check the cfg isn't null and forgo checking the `dupe` cursor status for the aforementioned reasons.

WT-12157 Moving verbose message into backup cursor creation

---

dist/pygrep.py
dist/s_all
dist/s_define
dist/s_funcs
dist/s_stat
dist/s_string
dist/s_void
dist/s_whitespace

This change improves the run time of `s_all` and `s_fast` on MacOS and improves `s_fast` on all platforms.
Summary of changes:
* Use a python implementation of `grep` on MacOS to mitigate the slow (old) version slowness when matching multiple patterns. Use python grep in the slowest scripts on MacOS: `s_define`, `s_funcs`, `s_stat`, `s_whitespace`.
* Implement "fast" mode in: `s_string`, `s_void`, `s_whitespace` and speed up `s_fast`.
* Improve struct fields parsing in `s_stat`.
* Eliminate the use of temp file for output in: `s_define`, `s_funcs`.

WT-12283 Make s_all and s_fast faster on MacOS

---

src/block/block_compact.c
src/include/block.h

The compact thread can get 'stuck' on a table for too long passing over it many times but failing to reclaim space due to other concurrent operations.
This adds an exit point to compact to stop iterating over a file when the file size grows between iterations.

WT-12328 Stop compacting if a file has grown in size between passes

---

test/unittest/tests/test_prepare_mod_sort.cpp

In Catch2-based unit tests, status should be checked using REQUIRE() which is part of the Catch2 framework, rather than using WT_ASSERT as one would within WiredTiger itself.

WT-12364 Replaced WT_ASSERT() calls in Catch2-based unit test code with REQUIRE()

---

dist/s_typedef
src/conn/conn_api.c
src/include/connection.h
src/include/extern.h
src/include/misc.h
src/include/time_inline.h
src/include/wt_internal.h
src/txn/txn.c
src/txn/txn_recover.c
test/suite/test_recovery01.py

In this backport test/suite/test_recovery01.py has been made a no-op as the test infrastructure required to make it work is not available in v6.0.
* WT-11491 Log the WiredTiger time spent during startup and shutdown (v7.0 backport) (#9710)
* WT-11491 Log the WiredTiger time spent during startup and shutdown (#9524)
(cherry picked from commit 542d756f1d33d9eb1b6f8aaa5ec04a37633e64c6)
---------
Co-authored-by: Jie Chen <jie.chen@mongodb.com>
(cherry picked from commit c77753914ff6da624081436939d27ccfe911cafd)
* WT-11777 Fix units of __wt_timer_evaluate() calls: logging and progress period (#9824) (#9889) (#10016)
(cherry picked from commit a9f8d18ee3e65fb53546e63744d9c10d0b919783) in 7.2
Co-authored-by: tod-johnson-mongodb …

WT-11491 WT-11777 v5.0 group backport

---

dist/log.py
src/log/log_auto.c

Summary of the change:
* ASAN was not happy with `memcpy` using NULL pointer with size = 0.

WT-12382 Fix __pack_encode_WT_ITEM with zero size item

---

test/evergreen.yml

To test this, I've versions of the `checkpoint-stress-test` with tiered storage enabled, both on my workstation and in evergreen. I've also run patch builds to confirm that the new test shows up and is executed successfully in the correct variant. 
I'm open to suggestions of other variants where we should run this test, but I don't think we need to over do it. I picked Arm because that is where tiered storage would most likely be deployed.

WT-9420 Run test_checkpoint on tiered tables in Evergreen

---

dist/s_clang_scan

`s_clang_scan` reports any `clang_scan` warnings that aren't present in our whitelist file `s_clang_scan.diff`, but to do so it strips line numbers of where the warnings occur and then diffs against the whitelist. This means when there are new warnings we report their existence, but not their location in the file.
This change also dumps the original output of `clang_scan`, so when `s_clang_scan` detects a difference it reports both the delta and the original `clang_scan` output letting developers know where the introduced issue occurs. The solution provided in the Jira ticket is good, so I've taken that verbatim.

WT-12206 Add diagnostic output to the Clang analyser task

---

dist/s_string.ok
test/model/src/core/util.cpp
test/model/src/driver/kv_workload.cpp
test/model/src/driver/kv_workload_generator.cpp
test/model/src/driver/kv_workload_runner_wt.cpp
test/model/src/include/model/driver/kv_workload.h
test/model/src/include/model/driver/kv_workload_generator.h
test/model/src/include/model/driver/kv_workload_runner.h
test/model/src/include/model/driver/kv_workload_runner_wt.h
test/model/src/include/model/util.h
test/model/test/model_workload/main.cpp

This PR introduces the "crash" operation to the workload generator, which intentionally crashes WiredTiger to force it to do recovery—and thus to run RTS, as the main goal of this project is to add more RTS testing.
The trick to getting this working with WiredTiger was to run the workload in a child process, so that we can easily crash and restart it. The child process saves its state between crashes using shared memory, and it also uses it to return information back to the controller parent process, e.g., whether the crash was intentional.
Feel free to let me know if you have any questions, or if you'd like me to go over anything via Zoom.

WT-11626 Add failure injection to the workload generator

---

test/evergreen_develop.yml

Per the Jira description increase testing frequency to 4 times daily so we can detect true changepoints - and rule out false changepoints - faster.

WT-12417 Increase performance testing cadence to 4 times daily

---

src/include/hardware.h
src/reconcile/rec_write.c

We have a WT_READ_ONCE but no matching WT_WRITE_ONCE, this PR fixes that and unblocks #10189

WT-11755 Add a write once macro to WiredTiger

---

dist/common_functions.sh
dist/s_all
dist/s_clang_format
dist/s_clang_scan
dist/s_clang_tidy
dist/s_copyright
dist/s_define
dist/s_docs
dist/s_evergreen
dist/s_evergreen_validate
dist/s_export
dist/s_free
dist/s_funcs
dist/s_function
dist/s_getopt
dist/s_install
dist/s_lang
dist/s_longlines
dist/s_mentions
dist/s_python
dist/s_readme
dist/s_stat
dist/s_string
dist/s_style
dist/s_tags
dist/s_test_suite_no_executable
dist/s_typedef
dist/s_visibility_checks
dist/s_void
dist/s_whitespace

Summary of changes:
* Add `common_functions.sh`.
* Use it in every script in `dist/` to locate the repository and sources.
* Since `s_fast` only check files changed since fork, now it checks that it's being run for a proper repo.

WT-12409 Add bash common functions. Tidy up dist scripts.

---

test/evergreen.yml

The PR adds model testing to PR testing. The rationale is explained in the ticket, but TL;DR: If changes to WT result in API-visible changes, e.g., due to a recent change where setting a timestamp can now return EINVAL, it would result in failing this test—which may not be caught until after the PR gets merged.

WT-12360 Add model unit testing to PR testing

---

src/checksum/power8/clang_workaround.h

This fixes an issue that stopped the PPC build from compiling. As we don't run code coverage on PPC, and the file is PPC specific, the WT_INLINE macro wasn't required in this file anyway.

WT-12439 Roll back WT_INLINE to inline in PPC specific file.

---

test/evergreen.yml

This consistently stopped `test_timestamp_abort` timing out for all of the tests I did.

WT-9820 Halve concurrency level for long-running MSAN tests

---

tools/wt_cmp_uri.py

This can be useful when the key contains 100 zeroes and then different numbers.

WT-12445 Show the end of the key in wt_cmp_uri

---

src/history/hs_rec.c

Added a default value check for maximum history store size to ensure file size is only retrieved if it has been defined in the config.

WT-12376 Optimize history store size limiting code

---

src/btree/bt_debug.c

We recently merged a ticket that cleans up the output format of our verify `dump_blocks` and `dump_pages` output, and in doing so removed some code that printed [duplicate information](https://github.com/wiredtiger/wiredtiger/commit/d5be6ac2534fa1df4da5721f5434b31dd0b8a024#diff-eec07b0b03dc98e7eba3b478e28ca13a058753c06c4643ee4595f4887b83e609L687). 
However we missed that this function is also early exiting when the cell is deleted (`WT_CELL_DEL`), and the new changes attempted to print content of a deleted cell.
This PR restores the early return logic but still removes the duplicate debug output.

WT-12437 Don't dump deleted VLCS cells

---

src/conn/conn_prefetch.c

Passed all tests on my machine. The only way I can see this not working is if the thread group doesn't automatically restart threads (since the worker loop can now exit).

WT-11691 Convert prefetch worker threads to wait on condition variable

---

src/block/block_compact.c

Refactored duplicated code for `__wt_block_compact_progress`
Example outputs:
```
[1708408820:180996][1622023:0xffffb6026020], test_compact04.test_compact04.test_compact04, file:test_compact04-0.wt, WT_SESSION.compact: [WT_VERB_COMPACT_PROGRESS][DEBUG_1]: Compacting test_compact04-0.wt for 0 seconds; reviewed 0 pages, rewritten 0 pages (0MB)
[1708408820:181009][1622023:0xffffb6026020], test_compact04.test_compact04.test_compact04, file:test_compact04-0.wt, WT_SESSION.compact: [WT_VERB_COMPACT_PROGRESS][DEBUG_1]: Still collecting information for estimating the progress.
``` 
```
[1708408820:341298][1622023:0xffffb6026020], test_compact04.test_compact04.test_compact04, file:test_compact04-0.wt, WT_SESSION.compact: [WT_VERB_COMPACT_PROGRESS][DEBUG_1]: Compacting test_compact04-0.wt for 0 …
```

WT-12303 Avoid duplicate code in __wt_block_compact_progress

---

src/history/hs_rec.c

This fixes a slight misapplication of the WT-10017 backport. 5.0 incoming once people are happy with this.

WT-12227 Fix history store visibility assertion from previous backport

---

test/evergreen.yml

As part of https://jira.mongodb.org/browse/DEVPROD-257 Bazel is about to be enabled on all platforms by default. This will cause certain targets to be built with Bazel instead of SCons.
Since Bazel uses EngFlow's remote execution system instead of icecream, additional credentials need to be setup to maintain efficient compilation speed.
WT scons.py invocation: https://github.com/10gen/mongo/blob/master/src/third_party/wiredtiger/test/evergreen.yml#L152
The following evergreen function needs to be invoked before the call to SCons above: https://github.com/10gen/mongo/blob/master/etc/evergreen_yml_components/definitions.yml#L178

WT-12515 Enable Bazel Remote Execution in evergreen scons.py invocation

---

bench/workgen/runner/example_dynamic_tables.py
bench/workgen/workgen.cpp
bench/workgen/workgen.h

- Added a new setting `max_num_files` to limit the number of files present in the Workgn database
- Tables are no longer dynamically created if the limit has been reached

WT-12522 Add an option in Workgen to limit the number of files present in the database

---

bench/workgen/workgen.cpp
bench/workgen/workgen_int.h

- Ensure we are performing mirrored operations within a transaction
- Cancel a mirrored operation after facing a `WT_ROLLBACK`

WT-12504 Ensure mirrored operations in Workgen are done within the same transaction

---

src/include/time_inline.h
src/support/rand.c
test/csuite/wt2719_reconfig/main.c
test/suite/test_cursor_random03.py

The error happens where the records are exactly the same because two cursors are opened close together under one thread. In windows machine clock resolution is low, therefore the numbers ts.tv_nsec and ts.tv_sec are the same. If we only changed the rnd.z seed, we get into a problem like the original code, where rnd.w is the same and rnd.z seed is changing. Therefore the solution used all of the 64 bits from RDTSC.

WT-12225 Fix RNG generator weakness around mongodb $sample stage

---

test/evergreen.yml

Fixed this error by assigning the tests that requires more memory to arm64-medium.

WT-12378 Not enough memory error on arm64-small

---

test/suite/test_bug028.py

Skip running the "test_bug028" Python test on PPC machines, which have known I/O bandwidth issue that can take hours for the test to complete.

WT-12454 Skip test_bug028 on PPC machines

---

src/conf/conf_compile.c
test/csuite/wt11126_compile_config/main.c

Add a null case to the benchmark for compiled configs.

WT-12452 Add a fast path for when compiling a null or empty configuration.

---

test/evergreen.yml

(cherry picked from commit 9cce4b9c0e91df6176cd8071fdf1e395fa56aa2d)

WT-11239 Add CLANG_C/CXX_VERSION compile flags to the configure wiredtiger task (#10128) (v7.0 backport)

---

src/btree/bt_discard.c
src/btree/bt_vrfy.c
src/include/btmem.h
src/include/btree_inline.h

(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/248864f3ecbe26aaa00ce6696f46d9cff8f481be)
(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/db2c6172daad8abbb797d79bec240191dc292b63)
Co-authored-by: jchen <29520270+jiechenbo@users.noreply.github.com>
(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/0984a89ae620b63b97e61a0b5b43862f7643d57b)

WT-11062 Safe free the ref addr to allow concurrent access (#9959) (#10117) (#10161) (V6.0 backport)

---

test/evergreen.yml

This didn't make the builds green again, but the Ubuntu PPC CMake variant wasn't green anyway. And it's still an improvement - the only problem now is `test_random_directio`, compared to a pile of things failing on the existing Ubuntu variant.

WT-12438 Move Ubuntu PPC to RHEL PPC

---

test/evergreen.yml

This PR addresses the issues reported in WT-11239, but since `evergreen.yml` has had significant changes between 7.0 and 6.0 this is a new implementation to resolve the same issue. Note that we're targeting the 6.0 branch in this PR.
Now that the host toolchain has been fixed the `compile-clang` tasks for older versions of clang can be re-enabled. As part of this we've also removed the clang 6.0 test since WiredTiger's minimum supported version of clang is now 7.0.1.

WT-12587 Re-enable compile-clang tasks for older versions of clang

---

src/conn/conn_prefetch.c

There was a memory leak caused by WT_RET(EBUSY) in the queue push logic. The calloced `pe` struct would not be freed in the event that we returned an error.

WT-12580 Fix memory leak in prefetch queue push 

---

src/reconcile/rec_col.c

The `OVFL_IGNORE` case only worked because we previously unpacked it into a `WT_ITEM` to handle Huffman encoding.
Instead, separate the overflow and non-overflow cases, where the non-overflow case can simply use the original `vpack` size and data.

WT-12576 Slightly reorganise VLCS reconciliation overflow handling

---

test/model/src/core/util.cpp
test/model/src/driver/kv_workload.cpp
test/model/src/include/model/driver/kv_workload.h
test/model/src/include/model/util.h
test/model/test/common/include/model/test/util.h
test/model/test/common/util.cpp
test/model/test/model_workload/main.cpp
test/model/tools/model_test/main.cpp

The PR adds the ability to parse workload operations from a string, and it also adds a new option to `model_test` to re-run an existing workload that was saved to a file. This is, for example, useful when debugging a failed model-based test.
The PR also adds `operator==` and `operator!=` to all workload operations, so that the test can check whether the operations were parsed correctly.

WT-12545 Import an existing workload file into the model

---

test/evergreen.yml

The `first_run_args` variable is not defined at this point. It looks like a typo, `calibration_run_args` should be used instead. Good catch, @quchenhao.

WT-12322 Use the right variable in schema abort predictable

---

src/btree/bt_discard.c
src/btree/bt_vrfy.c
src/include/btmem.h
src/include/btree_inline.h

This had some merge conflicts and needs some attention. A good comparison is probably the v6.0 backport.
(cherry picked from commit 248864f3ecbe26aaa00ce6696f46d9cff8f481be)

WT-11062 Safe free the ref addr to allow concurrent access (v5.0 backport)

---

src/btree/bt_compact.c

The code now only calls __compact_walk_internal() from __wt_compact() on internal pages, and asserts in __compact_walk_internal() that it is being called on an internal page.
Co-authored-by: Jeremy Thorp <jeremy.thorp@mongodb.com>
(cherry picked from commit 05522bc83f71b61a3d44a5c77d2998d83fc4c0ce)

WT-9057 Address null address read in compact walk. (5.0 backport)

---

dist/common_functions.sh
dist/s_clang_format
test/unittest/tests/test_acquire_release_macros.cpp

Summary of changes:
* Fixed reporting in s_clang_format. The trick is that it's getting called from other scripts like log.py to format the generated code in a temp file. s_clang_format then needs to make a distinction between an actual recursive call vs being called with a file argument.
* Fixed passing of return code from recursive call in do_in_parallel.
* Stopped automatic propagation of `S_RECURSE` down from a "recursive" call. This is useful in case a script will call other scripts.
* Fixed a formatting issue caused by not reporting changes previously. Without it, automatic commit would fail.

WT-12605 Fix reporting in dist scripts

---

src/include/block_chunkcache.h

Updates the datatype for the `valid` flag for `__wt_chunkcache_chunk` struct to allow for some macro conversions in the future.

WT-12603 Convert chunkcache chunk valid flag to a bool

---

bench/wtperf/wtperf_misc.c

This is a Coverity fix. For the other ticket I moved code into one function. No need to free and reallocate the buffer all the time. Just allocate the larger size once and use it.

WT-12620 Coverity buffer management

---

src/cursor/cur_backup.c

Found after restoring ASan builds to use glibc instead of tcmalloc.

WT-12659 Backup cursor memory leaks

---

test/evergreen.yml

Replace with a comment describing why the test is not run for ASan builds.

WT-12679 Remove invalid fixmes

---

test/model/src/core/kv_database.cpp
test/model/src/core/kv_table.cpp
test/model/src/core/kv_table_item.cpp
test/model/src/driver/debug_log_parser.cpp
test/model/src/driver/kv_workload_generator.cpp
test/model/src/driver/kv_workload_runner_wt.cpp
test/model/src/include/model/driver/kv_workload.h
test/model/src/include/model/driver/kv_workload_runner.h
test/model/src/include/model/kv_checkpoint.h
test/model/src/include/model/kv_table.h
test/model/src/include/model/kv_table_item.h
test/model/src/include/model/kv_transaction_snapshot.h
test/model/src/include/model/util.h
test/model/src/include/model/verify.h
test/model/tools/model_test/main.cpp

Fix new performance-related Coverity issues in the model, all of which are due to copying values when they could be moved via `std::move()`. These are all instances of Coverity's rule `COPY_INSTEAD_OF_MOVE`.

WT-12685 Fix new performance Coverity issues in test/model

---

src/block/block_compact.c

Example of output:
```
[1710901899:206528][3983514:0xffff8899a020], test_compact04.test_compact04.test_compact04, file:test_compact04-0.wt, WT_SESSION.compact: [WT_VERB_DEFAULT][ERROR]: __wt_block_compact_start, 22: Compaction already happening on data handle test_compact04-0.wt by session 15: Device or resource busy
```

WT-12680 Add a log when parallel compaction is executed on the same table

---

test/model/src/include/model/util.h

Fix potentially invalid iterator usage in the `config_map`'s `get_` functions, which would dereference an "end" iterator if the key does not exist. (Coverity's `INVALIDATE_ITERATOR` rule.)

WT-12687 Fix invalid iterator usage in test/model's config_map

---

dist/stat_data.py
src/cursor/cur_bulk.c
src/cursor/cur_file.c
src/include/stat.h
src/include/wiredtiger.in
src/lsm/lsm_cursor_bulk.c
src/support/stat.c
test/suite/test_bulk01.py

Co-authored-by: Etienne Petrel <etienne.petrel@mongodb.com>
(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/af8e93273d67ed1709478e8cea85d3bbd38b3103)

WT-12321 Add stat to track how many bulk cursors are opened (#10289) v6.0 backport

---

src/conn/conn_api.c
src/include/cache.h
src/include/extern.h
src/include/misc_inline.h
src/txn/txn_ckpt.c
test/evergreen/tsan_warnings.supp

In doing so we don't have to suppress whole functions like `__conn_close`.

WT-12514 Move eviction target modifications into their own functions to suppress tsan warnings more granularly

---

test/suite/test_compact07.py

It is expected to have parallel compaction in this test, therefore we need to ignore the message that is generated from WiredTiger when this happens.

WT-12702 Handle error message related to parallel compaction in compact07

---

src/btree/bt_handle.c
src/btree/bt_stat.c
src/btree/bt_sync.c
src/conn/conn_cache.c
src/conn/conn_log.c
src/cursor/cur_log.c
src/evict/evict_lru.c
src/include/btree.h
src/include/btree_inline.h
src/include/cache_inline.h
src/include/extern.h
src/include/gcc.h
src/include/log.h
src/include/log_inline.h
src/include/msvc.h
src/include/thread_group.h
src/log/log.c
src/log/log_slot.c
src/meta/meta_ckpt.c
src/support/thread_group.c
src/txn/txn.c
src/txn/txn_log.c
src/txn/txn_recover.c
test/evergreen.yml

Add `ex_encrypt` to `examples-c-tsan` and update WiredTiger to resolve warnings raised by running `ex_encrypt`.
This PR also contain additional changes that aren't required by `ex_encrypt`, but will be needed for the addition of future tests. I've tried to move some changes into this PR to balance the workload with future PRs.

WT-12701 Add ex_encrypt to examples-c-tsan

---

src/include/hardware.h

Update our FLD_*_ATOMIC macros to use relaxed atomic loads. 
Currently we only have these macros for 16bit ints so we don't need to handle the generic case.

WT-12697 Make F_SET/CLR_ATOMIC and FLD_ISSET_ATOMIC relaxed atomics

---

test/evergreen.yml

Fixed this error by assigning the tests that requires more memory to
arm64-medium.
(cherry picked from commit 0e9d25ec4a20da65014e3297476824df7fea1e02)

WT-12378 Not enough memory error on arm64-small (v7.3 backport)

---

dist/stat_data.py
src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_discard.c
src/include/btmem.h
src/include/btree_inline.h
src/include/extern.h
src/include/stat.h
src/include/timestamp_inline.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/include/wt_internal.h
src/reconcile/rec_write.c
src/support/stat.c
test/suite/test_checkpoint32.py

Traversing an in-memory page that contains all the deleted values that are visible to the current transaction led to an increase in latency due to the time spent skipping these deleted values.
By saving the aggregated timestamp information in the ref when the page has all deleted values, this aggregated information can be validated against the transaction snapshot to skip traversing the page completely and improve the latency when there are many deleted pages.
The downside of this approach is that the in-memory size of each ref is increased by 8 more bytes, but this increase shouldn't cause any problem.
(cherry picked from commit d121cca3b711efd1951a36aa48348ec6df5803fe)

WT-10807 Skip in-memory deleted pages as part of the tree walk (v7.3 backport)

---

src/btree/bt_cursor.c

(cherry picked from commit 06f5c6ac6c0664ed71f70552520d7381b33342f7)
Co-authored-by: jchen <29520270+jiechenbo@users.noreply.github.com>
(cherry picked from commit 832185e230d7de80f3830d1adac90e3553fa92cb)

WT-11911 Fix use-after-free with bounded cursor and search_near (#9914) (#10004)

---

test/evergreen.yml

Reverts wiredtiger/wiredtiger#10428

Revert "WT-12554 Treat git clone failures as setup failures in Evergreen"

---

src/include/api.h
src/session/session_api.c
src/txn/txn_ckpt.c

This is a perf improvement between 2-3% for the config microbenchmark (test_wt11126_compile_config).

WT-12784 Avoid building and checking of cfg entries for compiled configs

---

test/format/format_timestamp.c
test/format/ops.c

- We should only be executing `timestamp_once` when timestamps are used as it sets the stable/oldest ts.
- There is one function called `timestamp_teardown` that is called at the end of a run that bumps the stable/oldest ts. It should not be called if timestamps are disabled.

WT-12792 Don't set timestamps in test/format if disabled through the config

---

test/cppsuite/test_harness/test.cxx
test/cppsuite/test_harness/test.h
test/evergreen.yml

cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/92a92da1d173b9252c1bf883446302448787f585

WT-12587 Re-enable compile-clang tasks for older versions of clang (#10302) (v5.0 backport)

---

dist/stat_data.py
src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_discard.c
src/include/btmem.h
src/include/btree_inline.h
src/include/extern.h
src/include/stat.h
src/include/timestamp_inline.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/include/wt_internal.h
src/reconcile/rec_write.c
src/support/stat.c
test/suite/test_checkpoint32.py
test/test_coverage.md

Traversing an in-memory page that contains all the deleted values that
are visible to the current transaction, leading to an increase in latency due
to the time spent skipping these deleted values.
By saving the aggregated timestamp information in the ref when the page
has all deleted values, this aggregated information can be validated
against the transaction snapshot to skip traversing the page completely
and improve the latency when there are many deleted pages.
The downside of this approach is that the in-memory size of each ref is
increased by 8 more bytes, but this increase shouldn't cause any
problem.
(cherry picked from commit d121cca3b711efd1951a36aa48348ec6df5803fe)

WT-10807 Skip in-memory deleted pages as part of the tree walk (7.0 backport)

---

src/btree/col_srch.c
test/suite/test_flcs07.py

When looking for an implicit record in FLCS and a greater valid record exists, ensure `search()` returns the requested record.

WT-11373 Search should return any record below the greatest existing record in FLCS

---

tools/checksum_bitflip/checksum_bitflip.c
tools/wt_binary_decode.py

The wt_binary_decode.py tool is hard coded to assume that a block size larger than 512K indicates a corrupt block – i.e., that the size as stored in the page header is likely corrupt/garbage if it too big. MongoDB supports document sizes up to 16MB, so we can legitimately have blocks at least that big.
This PR increases the cut-off to 17MB, allowing for some slop around a single large document.

WT-12819 Allow larger block sizes with wt_binary_decode.py

---

src/evict/evict_lru.c
src/include/btree.h
test/evergreen.yml

This PR fixes WT-9121 and WT-12643 by enabling eviction server to scan the whole btree.

WT-12643 Fix tree walk algorithm to traverse the whole tree

---

test/evergreen.yml

Disabling the test while we investigate the cause in WT-12812

WT-12829 Disable azure-gcp-tiered-storage-extensions-test on Ubuntu 20.04

---

src/block/block_ext.c

This got mangled by the big clang format commit.

WT-12810 Fix comment alignment in __block_ext_overlap

---

dist/stat_data.py
src/btree/bt_page.c
src/btree/bt_sync.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_scrub_eviction_prepare.py

This pull request has the following changes:
- Mark the page clean after instantiating it with prepared updates.
- A new Btree stat that tracks the number of pages reconciled during reconciliation.
- Python test to verify the fix

WT-12736 Mark the page clean after re-instantiating the page with prepared updates.

---

src/conn/conn_cache.c

Don't allow the updates target to be larger than the eviction target.

WT-12224 Don't allow eviction_updates_target to exceed eviction_target

---

src/evict/evict_lru.c

evict lru walk perfect, evict_candidates can not excced 50% of the entries

WT-12279 Fix evict_candidates can not exceed 50% of the entries

---

src/evict/evict_lru.c

bug fix, when queue full and score is low, we should not Ignore queue empty statistics.

WT-12250 when queue full and score is low, we should not Ignore queue empty statistics.

---

src/btree/bt_sync_obsolete.c

Unavailablity of a dhandle for the checkpoint cleanup utility thread is not a problem, it just skips that dhandle and continue with the next one available. Printing the unavailablity error message in the log file is unnecessarily confusing the applications/users.

WT-12883 Change the dhandle fail error message into verbose message

---

test/model/src/core/random.cpp
test/model/src/driver/kv_workload_generator.cpp
test/model/src/include/model/random.h
test/model/tools/model_test/main.cpp

The PR adds more randomness when initializing and advancing the random seed.
It also fixes a bug in the workload generator, which did not account for `operation::rollback_to_stable` taking a checkpoint.

WT-12890 Fix random seed initialization in the model

---

test/csuite/random_directio/util.c
test/evergreen.yml

Increase `COPY_BUF_SIZE` to 128KB since it must be larger than `sb.st_blksize` and on RHEL8 PPC `st_blksize` is 64KB.

WT-12664 Increase the size of COPY_BUF_SIZE in test_random_directio

---

dist/s_string.ok
test/csuite/wt4105_large_doc_small_upd/main.c
test/evergreen.yml

See the ticket comments for context.
I tried a pile of patch builds with this check added, and none of them timed out. But the original timeout was rare, so it's not clear whether I've managed to prove anything by doing that.

WT-9126 Avoid alarm in ctest for UBSAN builds

---

test/evergreen.yml

Run `poetry install` twice since this resolves dependency ordering issues present in mongo's `poetry.lock` file.

WT-12923 Add workaround for poetry dependency issues in many-collection-tests

---

test/evergreen.yml
test/evergreen/code_change_report/code_change_report.py
test/evergreen/code_change_report/git_diff_tool.py
test/evergreen/code_change_report/push_working_directory.py

Implemented a Python tool to create a diff file that excludes newly-added 0-length files (as they cause issues with pygit2 in the code change report), and switched to using it for the code change report.

WT-12868 Handle 0 length files with git diff for the Code Change Report

---

src/evict/evict_file.c
test/evergreen/code_change_report/code_change_report.py
test/evergreen/code_change_report/git_diff_tool.py

The solution is to avoid performing the percentage calculation if the number of branches is 0.

WT-12925 - Fix divide-by-0 if the branch count is 0 when a Code Change Report attempts to push to a GitHub PR

---

src/btree/bt_sync_obsolete.c
test/suite/test_cc06.py

Accessing the empty or newly created files by checkpoint cleanup leads to marking them dirty unnecessarily and causing problems to open the bulk cursor when these are dirtied tables are processed by the checkpoint thread.

WT-12927 Avoid checkpoint cleanup processing empty or newly created files

---

lang/python/setup_pip.py
test/syscall/syscall.py
test/wt_hang_analyzer/wt_hang_analyzer.py

Remove all use of distuils and replace with appropriate package imports. 
This PR also removes links to compressors in setup_pip.py as they are dependent on distutils. Given the infrequent use of compression in Python, this change will simplify the set up process.

WT-11387 Remove deprecated uses of python package distutils

---

src/btree/bt_compact.c
src/btree/bt_discard.c
src/include/extern.h

Compact operation can rewrite the ref addr to compact the on-disk file. As part of the rewrite operation, it can free the existing address and create a new address for this ref on the disk file. During this time, it is possible that the same ref being accessed in parallel can lead to access the freed addr->addr. To avoid this problem, safe free the addr->addr from the compact operation.

WT-12929 Compact to safe free the addr->addr while replacing ref addr

---

src/btree/bt_compact.c

While traversing entries on an internal page, compact will decide to checkpoint the tree if it sees pages in the WT_REF_DELETED state as checkpoint will delete the underlying blocks, freeing up space for compact to reclaim. However, compact will repeatedly see pages in the WT_REF_DELETED state even after they are freed as the index in the parent page is not updated unless a split occurs. 
The ref address is freed when we free the underlying blocks. Adding a check for the ref address here ensures we only proceed with the compact checkpoint (and another compact pass) if the underlying blocks have not already been freed.

WT-12238 Check ref address when skipping pages in compact

---

src/include/cell_inline.h
test/suite/test_dictionary01.py
test/suite/test_dictionary02.py
test/suite/test_dictionary03.py
test/suite/test_dictionary04.py
test/test_coverage.md

The changes address the issue where `__wt_cell_pack_value_match` would not compare cells correctly as it would not use the right size for the cells to compare when there is no time window validity or RLE information.

WT-12922 Use the right cell size when using dictionary

---

test/evergreen/code_change_report/code_change_report.py
test/evergreen/code_change_report/git_diff_tool.py

[WT-12868](https://jira.mongodb.org/browse/WT-12868) created a workaround for newly added 0-length files, however @bzm-jas 's PR for [WT-12837](https://jira.mongodb.org/browse/WT-12837) also has some deleted 0-length files. Each of these files can generate either a deleted file record in the diff, or it may generate a record moving that file to another location as it sees a match in the (0-length) content.
The solution is to also exclude from the diff output file:
- Any deleted files
- Any moved files where the record includes the path of a 0-length file.

WT-12934 Address remaining issues with zero length files and git diffs in the Code Change Report

---

test/model/src/driver/kv_workload.cpp
test/model/src/driver/kv_workload_generator.cpp
test/model/src/include/model/driver/kv_workload.h
test/model/src/include/model/driver/kv_workload_generator.h
test/model/tools/model_test/main.cpp

Counterexample reduction sometimes produces invalid workloads that do not actually reproduce the failure of the original workload, but instead fail because the reduction process itself generated a malformed workload. So far I've only seen this happening due to producing a workload with invalid use of timestamps—so check for timestamps early and skip testing malformed workloads.

WT-12889 Identify and skip malformed workloads in counterexample reduction

---

src/btree/bt_sync.c

Checkpoint reads only internal pages into the cache for the purpose of removing any obsolete pages as part of the checkpoint cleanup. Evicting these internal pages asap can add an overhead to the next checkpoint to read them back again into the cache. Instead of evicting them asap, evict the internal pages read by the checkpoint like a regular page.
It is unnecessary to remove leaf pages tagged as READ WONT_NEED from the cache by the checkpoint because the checkpoint never reads any pages from the leaf pages (apart from history store pages used for reconciliation).  This will avoid the unnecessary slowdown of the checkpoint by evicting the pages that are not read by the checkpoint.

WT-12609 Improve checkpoint cleanup and page eviction logic (#10324)

---

ext/test/fail_fs/fail_fs.c

It was not possible to hit the race condition before this fix. The `fail_fs->fail_enabled` would only change if the environment variable was changed underneath the caller of the function. Now the change ensures that fail_enabled, allow_reads are only read under a lock.

WT-12897 Fix potential data race condition in fail_fs.c

---

src/reconcile/rec_write.c

A loop returns 0 if the loop goes all the way to the end. This is not needed since the following loop loops over the same range, has the same check within the loop, and also results in return 0 if the first loop would have gone all the way to the end. The first loop is not accomplishing anything.

WT-12974 Delete unneeded loop in __rec_hs_wrapup()

---

src/support/generation.c
tools/litmus_tests/README.md
tools/litmus_tests/generations/gen_drain_arm64.litmus
tools/litmus_tests/generations/gen_drain_x86.litmus
tools/litmus_tests/generations/gen_oldest_arm64.litmus
tools/litmus_tests/generations/gen_oldest_x86.litmus

…03) (#9828) (#9964) (#10171)
* Adding a number of litmus tests to the codebase
* Adding a litmus test readme with style guide
(cherry picked from commit a732cfc0301310e90abd627b35f0d1cf8c07151c)
Co-authored-by: Luke Pearson <luke.pearson@mongodb.com>
(cherry picked from commit bb790d3dba0f32ba587e6b917a10fd34268c981a) (cherry picked from commit 9a121b3a83803791c96bf92a959ca69fe231e6fd) (cherry picked from commit 842d96a785873a5731782d286da2f158331e1d3c) (cherry picked from commit d79240a8f58d3b3b4f92dd4151a54f9133f540cb)

WT-11280 Generation tracking might not be properly synchronized (v4.2 backport)

---

src/conn/conn_prefetch.c
src/evict/evict_lru.c
src/include/extern.h
src/include/time_inline.h
src/txn/txn.c

- Partially reverts WT-12816
- Don't let prefetch threads to be pulled into eviction

WT-12977 Don't let prefetch threads be pulled into eviction

---

src/os_posix/os_fs.c

In WT-11555 I didn't add in the remap boolean for this code path because I thought it couldn't race. I was wrong and it too needs the fix from that ticket. @keitharnoldsmith because you reviewed the other PR. @raviprakashgiri29 because you've been involved in this ticket. I'm going to let it run a while, but I was readily reproducing.

WT-12649 Always send in and check remap boolean.

---

src/conn/conn_compact.c

This `WT_ASSERT` is invalid as background compaction could be enabled and disabled, while this code has not been executed yet.

WT-12989 Remove WT_ASSERT in background compaction related to run_once

---

tools/wt_binary_decode.py

This script (indiscriminantly) walks a `wt` file, parsing as much as it can and printing helpful output for debugging.
Prior to this change it supported printing some information about page + cell metadata, but this wasn't easily machine readable.
This change adds a `--csv` option which will write the respective stats per page to a csv file for later analysis.
We are using this to analyse the ratio of durable history metadata vs key sizes in index files, but there are many other uses for which this may be helpful.

WT-12999 Add csv to wt_binary_decode with durable history metadata stats

---

tools/wt_binary_decode.py

python3 before 3.9 doesn't support this style type hint, make it compatible with all python3 versions

WT-12999 fix python compatibility

---

dist/s_string.ok
test/model/CMakeLists.txt
test/model/src/core/util.cpp
test/model/src/driver/debug_log_parser.cpp
test/model/src/include/model/util.h
test/model/test/model_basic/main.cpp

The JSON library uses UTF-8 encoding, which has the unfortunate consequence of encoding all keys and values from the debug log JSON into UTF-8. As a result, we need to decode keys and values from UTF-8 back to their original bytes before unpacking them via `data_value::unpack`.
I used the `iconv` library to do the work, because it is standard on POSIX systems. I would have preferred to use something like `codecvt` if I could, but it just got deprecated, and I didn't want to add a dependency on a non-standard library. And no, I didn't find a way to get our JSON library to use a different encoding; it looks like UTF-8 is hard-coded in.

WT-12733 Decode JSON strings into the original code points

---

test/evergreen.yml

* Change stress tests back to original distros
(cherry picked from commit 7269d9a3c2f3f11e4d897a5639723b4130558e4f)

WT-11531 Change stress tests back to original distros (#9566) (v7.0 backport)

---

src/conn/conn_compact.c
src/include/connection.h
test/suite/test_compact13.py

If background compaction did not successfully compact a file, it will mark it as inefficient and skip it for some time. Even after turning background compaction off and on, the file won't be checked until the expiry time has been reached. The behaviour is now different with the suggested changes: if background compaction is disabled, its stats are reset and next time background compaction runs, each file will be investigated again.
Changes:
- New flag `BACKGROUND_COMPACT_CLEANUP_OFF` used when background compaction is disabled to cleanup its stats.
- Renamed existing flags

WT-12990 Reset background compaction stats when disabled

---

test/evergreen.yml

(cherry picked from commit 518f22ed709defa8f55fa81c87175832b8bd7953)

WT-11457 Increase timeout to 5 hours for split stress test (#9508) (v7.0 backport)

---

src/cursor/cur_file.c

Background:
At a certain point in time, mongod.log experienced severe jitter, with many second level slow logs, but the write latency of wt did not change much. The reason is that session. modify() did not perform write latency statistics.
mongo shell run:
db.setLogLevel(0, 'storage');
db.adminCommand({setParameter:1, wiredTigerEngineRuntimeConfig:'verbose=[api:2]'})
db.runCommand(    {      findAndModify: "people",      query: { name: "Tom", state: "active", rating: { $gt: 10 } },      sort: { rating: 1 },      update: { $inc: { score: 1 } }    } )
mongod.log as following:
{"t":{"$date":"2024-05-20T21:16:05.513+08:00"},"s":"D1", "c":"WT",       "id":22430,   "ctx":"conn57","msg":"WiredTiger message","attr":{"message":{"ts_sec":1716210965,"ts_usec":513276,"thread":"9599:0x7fb670a2e700","se …

WT-13023 Fix not tracking latency for modify 

---

test/suite/test_verify.py

(cherry picked from commit 33f49b1b91a0d4a75d1073de2fcde0df8ad76de9)

WT-12935 Disable prefetch after corrupting table in test_verify_api_corrupt_first_page (#10550)

---

test/evergreen.yml

1. Update the fetch mongo repo to appear after we fetch the wiredtiger repo, as we need to perform git branch command
2. Utilise `git branch --contains` with the aim to get the checkout'd branch, so we can fetch the correct MongoDB repo
I realise we don't need to configure compile MongoDB (compilation is different v6.0 before and after), because any evergreen patches before 6.0 already compile the old way, and any patches after 6.0 use the new way.

WT-12230 fix many collection tests on older commits

---

dist/stat_data.py
src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_discard.c
src/include/btmem.h
src/include/btree_inline.h
src/include/extern.h
src/include/stat.h
src/include/timestamp_inline.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/include/wt_internal.h
src/reconcile/rec_write.c
src/support/stat.c
test/suite/test_checkpoint32.py

Traversing an in-memory page that contains all the deleted values that are visible to the current transaction, leading to an increase in latency due
to the time spent skipping these deleted values.
By saving the aggregated timestamp information in the ref when the page has all deleted values, this aggregated information can be validated against the transaction snapshot to skip traversing the page completely and improve the latency when there are many deleted pages.
The downside of this approach is that the in-memory size of each ref is increased by 8 more bytes, but this increase shouldn't cause any problem.
(cherry picked from commit d121cca3b711efd1951a36aa48348ec6df5803fe) (cherry picked from commit eed05eb5666400b5874b28e5a7ae416a2a88497d)

WT-10807 Skip in-memory deleted pages as part of the tree walk (6.0 backport)

---

src/txn/txn.c
test/suite/test_txn28.py

Txn log improve
fix bug for some log Missing delimiter
add macro OLDEST_STRICT_THRESHOLD
WT-12961

WT-12961 Txn log improve and add macro OLDEST_STRICT_THRESHOLD

---

test/evergreen/print_stack_trace.py

Add /data/mci to gdb's auto-load paths when running print_stack_trace.py. This resolves the `auto-loading has been declined` warnings reported by gdb.

WT-13040 Add /data/mci to the gdb auto-load paths in print_stack_trace.py

---

src/conn/conn_compact.c
src/include/connection.h
test/suite/test_compact13.py

If background compaction did not successfully compact a file, it will mark it as inefficient and skip it for some time. Even after turning background compaction off and on, the file won't be checked until the expiry time has been reached. The behaviour is now different with the suggested changes: if background compaction is disabled, its stats are reset and next time background compaction runs, each file will be investigated again.
Changes:
- New flag `BACKGROUND_COMPACT_CLEANUP_OFF` used when background compaction is disabled to cleanup its stats.
- Renamed existing flags
(cherry picked from commit 25e532361b0da87ed4a5039889d253cad0e53d39)

WT-12990 Reset background compaction stats when disabled (#10600)

---

CMakeLists.txt
dist/s_string.ok
src/docs/arch-fs-os.dox
src/include/gcc.h
src/include/time_inline.h
src/support/global.c

RISC-V was the only obvious community supported hardware, thanks to it's very nice barrier instruction definitions. For all other community hardwares I have deferred to a `FULL_BARRIER` as we don't support these ourselves.
Also I couldn't drop `s390x` as it turns out that that is a weird name for z/Architecture aka what we call zseries. I did validate that the `BCR 15, 0` was correct though. Per the linux architecture's own definition here: https://github.com/torvalds/linux/blob/2bfcfd584ff5ccc8bb7acde19b42570414bf880b/arch/s390/include/asm/barrier.h#L21.

WT-12201 Update the gcc.h macro definitions for all listed hardwares

---

src/btree/bt_split.c
src/reconcile/rec_visibility.c
test/suite/test_bug033.py

If an update is globally visible it can be evicted and EBUSY should not be returned. Thus the check for EBUSY should be skipped if an update is globally visible. The bug is the check for EBUSY was not skipped if an update is globally visible.
Please review just all commits. There were temporary changes that have been backed out.

WT-12096 Don't validate timestamp against the on-page value if the update is globally visible

---

test/cppsuite/configs/hs_cleanup_stress.txt

The original ticket was closed as a dup of the new ticket, and the FIXME got left.

WT-13101 Change FIXME to correct ticket number.

---

src/conn/conn_prefetch.c

Pre-fetch threads don't need to be so aggressive - let's increase the wait condition timeout from 10ms to 1 second.

WT-13105 Increase prefetch thread condition wait timeout

---

dist/stat_data.py
src/btree/bt_curnext.c
src/btree/bt_curprev.c
src/btree/bt_discard.c
src/include/btmem.h
src/include/btree_inline.h
src/include/extern.h
src/include/stat.h
src/include/timestamp_inline.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/include/wt_internal.h
src/reconcile/rec_write.c
src/support/stat.c
test/suite/test_checkpoint32.py

…
Traversing an in-memory page that contains all the deleted values that are visible to the current transaction, leading to an increase in latency due
to the time spent skipping these deleted values.
By saving the aggregated timestamp information in the ref when the page has all deleted values, this aggregated information can be validated against the transaction snapshot to skip traversing the page completely and improve the latency when there are many deleted pages.
The downside of this approach is that the in-memory size of each ref is increased by 8 more bytes, but this increase shouldn't cause any problem.
(cherry picked from commit d121cca3b711efd1951a36aa48348ec6df5803fe) (cherry picked from commit eed05eb5666400b5874b28e5a7ae416a2a88497d) (cherry picked from commit …

WT-10807 Skip in-memory deleted pages as part of the tree walk (5.0 backport) (#10588)

---

src/btree/bt_discard.c
src/btree/bt_handle.c
src/btree/bt_page.c
src/btree/bt_slvg.c
src/btree/bt_split.c
src/evict/evict_stat.c
src/include/btmem.h
src/reconcile/rec_write.c
test/evergreen/tsan_warnings.supp

Update `WT_INTL_INDEX_GET_SAFE` to add an `ACQUIRE_BARRIER` that pairs with the `RELEASE_BARRIER` already present in `WT_INTL_INDEX_SET`. 
This change also adds a TSan compatible implementation of the `WT_INTL_INDEX_*` macros which use __atomics instead of barriers. The semantics of both implementations are identical, but __atomics can be understood by TSan.

WT-13124 Give WT_INTL_INDEX_GET acquire semantics, add TSan support

---

src/cursor/cur_file.c
test/suite/test_bulk02.py

This PR contains changes (plus associated tests) to:
* Prevent user creating a bulk cursor when a transaction is running
(cherry picked from commit b66c52a0deaf7a2f45ea40100d40b352e2a11ab8)

WT-10994 Prevent user creating a bulk cursor when a transaction is running (#9102) (v7.0 backport)

---

src/session/session_dhandle.c
src/txn/txn_ckpt.c

(cherry picked from commit 4c72e79c73054a9f8f319ff28a3e0fdfb94a5b39)

WT-11109 Improve race detection when opening a checkpoint cursor (#9205)

---

src/docs/arch-schema.dox
src/docs/command-line.dox
src/docs/error-handling.dox
src/docs/transactions_api.dox
test/evergreen/code_coverage/code_coverage_config.json

This reverts commit 15e78573a6d3522cdd46ba050dd449f4718b5538.

Revert "WT-12462 Remove rename api docs and instances (#10355)"

---

CMakeLists.txt
cmake/configs/modes.cmake
dist/s_export
dist/s_string.ok
ext/storage_sources/dir_store/CMakeLists.txt
src/support/msan_fstat_suppression_wrappers.c
test/evergreen/msan_suppression_wrappers.c

Add logic to wrap `*stat()` calls and zero out memory first. This is done to suppress false positives reported by MSan and only applies when building with `CMAKE_BUILD_TYPE=MSan`. It can be removed once our minimum supported LLVM version is 14

WT-11218 Suppress MSan false positives by wrapping *stat functions

---

dist/s_string.ok
src/evict/evict_page.c
src/include/misc.h
src/reconcile/rec_write.c

(cherry picked from commit d6077c58ec931c294738f79bfa2c7fdaeb3b3ff3)

WT-11941 Fix incorrect timing information for reconciliation time (#10029)

---

dist/stat_data.py
src/btree/bt_page.c
src/btree/bt_sync.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_scrub_eviction_prepare.py

This pull request has the following changes:
- Mark the page clean after instantiating it with prepared updates.
- A new Btree stat that tracks the number of pages reconciled during reconciliation.
- Python test to verify the fix
- Skip the new test for hook tiered tests
(cherry picked from commit f24f80110212792c006718503b8517714bcaed3a)

WT-12736 Mark the page clean after re-instantiating the page with prepared updates.(v7.0 backport) (#10503)

---

test/csuite/timestamp_abort/main.c
test/csuite/timestamp_abort/smoke.sh

(cherry picked from commit 592eea605d234e810c720e302f1aa59ea6e54ef4)
Co-authored-by: Peter Macko <peter.macko@mongodb.com>
(cherry picked from commit be4538d91a80cd5dbe3a3a78315ba298a71336f0)

WT-12110 Disable timestamp_abort backup tests in the compatibility mode (v.7.0 backport)

---

test/suite/test_scrub_eviction_prepare.py

The `release_evict` cursor might not guarantee to evict the page from the cache if the cursor is not closed after updates.
Modify `test_scrub_eviction_prepare.py` to ensure the cursor is closed after updates before using release_evict.

WT-13109 Fix test_scrub_eviction_prepare.py to evict the page with release_evict cursor

---

test/evergreen.yml

Change the handling of is_patch to work when it's not set for non-patch builds.

WT-13158 Fix issue with coverage-report-per-test task on non-patch builds

---

src/include/mutex.h
src/support/mtx_rw.c

Add dummy atomic reads/writes in our read/write lock functions that use `__ATOMIC_ACQUIRE` and `__ATOMIC_RELEASE`. Our existing locks are safe, this additional information lets TSan understand that and prevents false positive data races for variables protected by locks.

WT-13166 Instrument __wt_rwlock_* calls to be TSan compatible

---

test/format/format_config.c

WT-11273 Prevent hs_search stress point with pareto and predictable replay
(cherry picked from commit ea440d975974518d1647d8b41e95b9aacabc1de5)

WT-11273 Prevent hs_search stress point with pareto and predictable replay (7.0 backport) (#9408)

---

test/evergreen.yml

Updated to the new MacOS 13 distros, including updating the Python 3.11 path.

WT-13128 - Switch to the new MacOS 13 distros

---

src/docs/arch-schema.dox
src/docs/command-line.dox
src/docs/error-handling.dox
src/docs/transactions_api.dox
test/evergreen/code_coverage/code_coverage_config.json

This reverts commit 15e78573a6d3522cdd46ba050dd449f4718b5538.

Revert "WT-12462 Remove rename api docs and instances (#10355)" (#10719)

---

src/btree/bt_delete.c
src/btree/bt_page.c
src/btree/bt_split.c
src/btree/col_modify.c
src/btree/row_modify.c
src/history/hs_cursor.c
src/include/extern.h
src/rollback_to_stable/rts_btree.c
src/rollback_to_stable/rts_btree_walk.c
src/txn/txn.c

This PR fixes the following three bugs in RTS:
1. A double-free if adding a tombstone via `__wt_update_serial` fails, in which case both `__wt_update_serial` and `__rts_btree_abort_ondisk_kv` would both free the same tombstone. This was fixed by making the `upd_arg` argument of `__wt_col_modify` and `__wt_row_modify` to be a double-star pointer; freeing the update would set the update to NULL, so that the caller would not also try to free it.
2. An error in `__rts_btree_walk` would leave an acquired hazard pointer behind. This was fixed by calling `__wt_page_release` during cleanup.
3. A race condition in `__rts_btree_abort_ondisk_kv`, in which case an RTS pass over the HS could race with `__wti_rec_hs_clear_on_tombstone`. Please refer to the ticket and the block comment in …

WT-12917 Fix a race condtion and a memory corruption in __rts_btree_abort_ondisk_kv

---

src/txn/txn.c
test/suite/test_txn06.py

[1718635584:874036][4903:0x7f4c9ffff700], WT_CONNECTION.set_timestamp: [WT_VERB_TIMESTAMP][DEBUG_1]: Timestamp (0, 1000098713): Updated global stable timestamp
[1718635584:874043][4903:0x7f4cadffb700], eviction-server: [WT_VERB_TIMESTAMP][DEBUG_1]: Timestamp (0, 1000098713): Updated pinned timestamp
[1718635584:874317][4903:0x7f4cadffb700], eviction-server: [WT_VERB_TRANSACTION][DEBUG_1]: current snapshot 65827 old snapshot 65839 pinned in session 20 [WT_CURSOR.insert] with snap_min 65839
current snapshot < old snapshot, The condition is satisfied because a negative number with a signed number is actually a very large positive number.

WT-13169 Re-read the txn_global->current_id prior to logging in case it has updated concurrently

---

dist/stat_data.py
src/conn/conn_compact.c
src/docs/arch-compact.dox
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

Make the background compaction thread sleep if the cache has reached `eviction_trigger` or if dirty eviction is needed.

WT-13080 Pause background compaction in case of cache pressure

---

src/meta/meta_ckpt.c

In backup, compare checkpoint's persisted data from metadata while ignoring checkpoint flags.

Backup:Compare checkpoint metadata while ignoring checkpoint flags.

---

dist/s_string.ok
src/evict/evict_page.c
src/include/misc.h
src/reconcile/rec_write.c

(cherry picked from commit d6077c58ec931c294738f79bfa2c7fdaeb3b3ff3) (cherry picked from commit 9e90cb81494992fe1b85d1f91275c003549509e7)

WT-11941 Fix incorrect timing information for reconciliation time (v6.0 backport)

---

src/meta/meta_ckpt.c

In backup, compare checkpoint's persisted data from metadata while ignoring checkpoint flags.
(cherry picked from commit fa5f9464eb4b89e89fc50aea5f4694883dcd2f4a)

WT-13215 Backup:Compare checkpoint metadata while ignoring checkpoint flags. (#10811) (v8.0 Backport)

---

test/evergreen.yml

In evergreen.yml we were using the same expansion `extra_args` for two different purposes: arguments to ctest and arguments to test/format. 
This change splits `extra_args` into two separate variables and allows us to run tests that take each of these arguments in the same buildvariant.

WT-13233 Fix naming conflict in evergreen.yml expansions

---

dist/s_clang_scan.diff
src/session/session_api.c
test/evergreen/run_model_workloads.sh
test/model/src/driver/kv_workload_generator.cpp
test/suite/test_truncate23.py

This PR removes the use of bounded cursors when positioning cursors for a truncate call. Only some cursor types implement bounding so we need to know which cursor type we're using in `__wt_session_range_truncate`, but this information isn't available at the api layer. Ongoing work has been split out to into WT-13232 to review if there's an alternative approach possible.

WT-13186 Remove bounded cursor support when positioning truncate cursors

---

test/model/src/include/model/driver/kv_workload.h
test/model/tools/model_test/main.cpp

The PR improves test/model's counterexample reduction to find even more minimal workload that reproduces a failure by 1) removing tables that are not necessary for reproducing the issue, and 2) removing individual operations from within transactions. This is on top of the original code, which removes transactions in their entirety.

WT-12973 Remove unnecessary tables and transactional operations in counterexample reduction

---

src/block/block_open.c
src/block/block_read.c
src/block/block_write.c
src/include/wiredtiger.in
src/log/log.c
src/log/log_slot.c
src/reconcile/rec_write.c
src/support/scratch.c

After investigating it seemed like a good idea to keep the usage of scratch buffers despite no longer needing it for alignment; scratch buffers are used in multiple places of our code, and is a convenient way for us to get a buffer in WT code. Instead we have removed alignment relating to direct io in the scratch buffer code itself, and made sure that no other functions using a scratch buffer are relying on this alignment.  We moved any other checks and alignment relating to scratch buffers + direct io here too. WT_ITEM_ALIGN was also removed. 

WT-13227 Remove directio adjacent buffer alignment code

---

tools/hexfiend/Templates/WT/_wtpage.tcl-inc

Make it the same as [__wt_cell_unpack_safe()](https://github.com/wiredtiger/wiredtiger/blob/7461c8be5aef36f185b9b7074f605f0901000c18/src/include/cell_inline.h#L845-L884)

WT-13268 Fix parsing the timestamps

---

test/csuite/schema_abort/main.c

This pull request has the below changes
1. Calculate the time once and use it instead of calculating it every time.
2. Sleep for some milliseconds before checking.
3. Yield to give other threads a chance to move the timestamp.

WT-13265 Improve logging in test_schema_abort

---

test/suite/test_verify.py

There is a bug right now, where it is technically possible that we accidently corrupt the tail of a block. This would overlap into the next block causing two blocks to be corrupt. This PR aims to fix it by making the assert less strict.

WT-13250 Fix test_verify assert to be less strict

---

tools/py_common/btree_format.py
tools/wt_binary_decode.py

The PR fixes `btree_format.Cell._parse_timestamps` to match the order of operations in `__cell_pack_value_validity` and accounts for storing just the differences.

WT-13266 Fix decoding cell timestamps in wt_binary_decode

---

lang/python/wiredtiger/init.py
test/csuite/CMakeLists.txt
test/csuite/wt4105_large_doc_small_upd/main.c
test/csuite/wt4156_metadata_salvage/main.c
test/evergreen.yml
test/fops/CMakeLists.txt
test/suite/test_bug018.py
test/suite/test_checkpoint11.py
test/suite/test_rollback_to_stable38.py

This PR adds a new buildvariant for running TSan tests, but ignoring all warnings raised by TSan. 
This is to catch any compilation or logic errors that might be introduced by changes that are behind an `#ifdef TSAN_BUILD`. 
As tests get added to the `ubuntu2004-tsan` variant we will remove them from this `no-throw` variant.

WT-13201 Create a TSan testing variant in evergreen that doesn't fail on error

---

src/session/session_api.c
test/suite/test_truncate26.py

Check the start and stop cursors passed into `__session_truncate`. If they aren't owned by the current session return EINVAL.

WT-9732 Return EINVAL when truncate uses a cursor not owned by the session

---

dist/api_data.py
dist/stat_data.py
src/btree/bt_sync.c
src/config/config_def.c
src/conn/conn_api.c
src/conn/conn_reconfig.c
src/evict/evict_page.c
src/include/btree.h
src/include/connection.h
src/include/extern.h
src/include/stat.h
src/include/timestamp_inline.h
src/include/wiredtiger.in
src/include/wt_internal.h
src/support/stat.c
test/suite/test_eviction02.py

Before evicting a clean page, mark the page dirty to perform a dirty eviction instead of clean page eviction when the page has obsolete time window.
---------
(cherry picked from commit 7a4dbfa352a895fdaf35f17d65575d833b4003f3)

WT-13092 Perform dirty eviction when the page has obsolete time window (4.4 backport)

---

dist/stat_data.py
src/btree/bt_page.c
src/btree/bt_sync.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_scrub_eviction_prepare.py

This pull request has the following changes:
- Mark the page clean after instantiating it with prepared updates.
- A new Btree stat that tracks the number of pages reconciled during reconciliation.
- Python test to verify the fix
- Skip the new test for hook tiered tests
(cherry picked from commit f24f80110212792c006718503b8517714bcaed3a)

WT-12736 Mark the page clean after re-instantiating the page with prepared updates.(v6.0 backport) (#10503)

---

test/suite/test_scrub_eviction_prepare.py

d704263cc
Co-authored-by: Ravi Giri <56813441+raviprakashgiri29@users.noreply.github.com>
(cherry picked from commit 78ead78cf63cf334493ec2cc179a34996a64ab37)

WT-13109 Fix test_scrub_eviction_prepare.py to evict the page with release_evict cursor (v7.0 backport) (#10789)

---

test/evergreen_develop.yml

We increased the rate of performance testing to 4 times per day during the 8.0 release period. Now the release period is finished restore our testing cadence to once a day.

WT-13300 Restore perf testing cadence to once daily

---

test/evergreen.yml
test/evergreen/code_coverage/code_coverage_config.json
test/evergreen/code_coverage/code_coverage_utils.py
test/evergreen/code_coverage/coverage-report-per-test.sh
test/evergreen/code_coverage/parallel_code_coverage.py
test/evergreen/code_coverage/per_test_code_coverage.py
test/evergreen/code_coverage_analysis.py
test/evergreen_develop.yml

I have optimized all the code coverage task time. The biggest improvements come from two major changes within the script and on Evergreen. 
1. There is a method to merge multiple code coverage reports and combine them into one. To utilise this advantage I have added parallel machines running a subset of the code coverage, and then I merge the code coverage report.
2. We now have the capability on building one directory and copying over the build directory. This allows us to use 16 threads to build WT and now we can just copy it over. 
In making the above two changes, I needed to refactor the python tests to accommodate for the change. The tasks now take 5-8 minutes down from 15 minutes. I will create another ticket to increase the coverage to 15 minutes. I have created a patch build to …

WT-13238 investigate and optimize code coverage

---

test/csuite/CMakeLists.txt
test/evergreen.yml

Remove the `sanitizer_long` tag and use `long_running` instead. This means fewer csuite tests are run in `csuite-tests-fast` on our ubuntu variant, but guarantees we don't hit timeouts on our ASan and TSan variants.

WT-13301 Remove the sanitizer_long flag from evergreen.yml

---

cmake/configs/x86/darwin/config.cmake

After the changes in WT-13012, disable cppsuite on Intel-based Macs as it only runs on linux. WT-13012 had already disabled cppsuite on ARM-based Macs.

WT-13330 Disable cppsuite on Intel-based Macs as it only runs on linux. 

---

src/include/txn_inline.h

If the stress history store search is enabled, then sleep on every random 100th iteration.

WT-13146 In timing stress sleep randomly on every 100th iteration when history store search is enabled.

---

dist/stat.py
dist/stat_data.py

Add `stat_data.py` to the list of files that triggers `stat.py` in fast mode.
This change also removes some dead `group` code in `stat_data.py`

WT-13344 Run stat.py in fast mode when stat_data.py is modified

---

test/cppsuite/configs/hs_cleanup_default.txt
test/cppsuite/configs/hs_cleanup_stress.txt
test/cppsuite/tests/hs_cleanup.cpp
test/evergreen.yml

This pull request has the following changes:
- Increase the test runtime duration to accommodate at least 1 checkpoint cleanup because the checkpoint_cleanup wait time minimum is 60 seconds.
- Enable connection log

WT-13322 Fix hs_cleanup test to pass checkpoint cleanup configuration and enable connection logs

---

src/btree/bt_vrfy.c
src/cursor/cur_dump.c
src/history/hs_rec.c
src/include/btree_inline.h
src/include/misc.h

Explicitly casting to void is not sufficient to suppress the warning. Inverting the value and then casting to void is works for all current mongodb v4 toolchains.

WT-12902 Remove unused temporaries from IGNORE_RET macros

---

examples/c/ex_all.c
src/docs/config-strings.dox
test/evergreen.yml
test/suite/test_checkpoint01.py

* Delete checkpoint target examples (ex_all.c) and tests.
* Replace [JSON quoting example] with a new example not using checkpoint target.
* Change timeout of csuite-long-running from 5 hours to 6 hours.
* Respond to code review on branch off develop.

WT-12492 WT-12492 Checkpoint target option: remove tests and examples

---

test/model/src/core/kv_table.cpp
test/model/src/driver/kv_workload_generator.cpp
test/model/src/include/model/core.h
test/model/src/include/model/kv_table_item.h
test/model/tools/model_test/main.cpp

Add a mechanism for ignoring known bugs and implemented it for WT-13232. The model can now throw an exception if it knows that it's going to trigger a known bug, which then results in the rest of that test being skipped.
This approach works well for the class of bugs that can be modeled during workload execution, such as WT-13232. I chose this approach as it provides a simple mechanism to unblock this project. In the future, we can create the alternative (but much more complicated) mechanism described in WT-13282, which would allow us to skip over bugs that are harder to model. We can come back to it in the future if it becomes necessary.

WT-13282 Add a mechanism to test/model to handle (and skip over) known bugs

---

test/evergreen.yml

Increase the length of test/model runs to better cover the parts of the code that we currently hit with a smaller probability. In particular, we need this to get a more accurate code coverage runs to see what parts of RTS we still do not cover.
This change brings up the code coverage report to 90% lines.

WT-13351 Increase the length of test/model runs

---

test/model/src/driver/kv_workload_generator.cpp

Enable eviction in test/model, except for FLCS until WT-12971 is merged. This is the only remaining ticket that blocks enabling eviction, and there are no other known issues with eviction for other table types.

WT-12972 Enable the eviction operator in the workload generator

---

test/suite/test_compact10.py

Remove redundant turn_on_bg_compact from test_compact10.py as this function is defined in base class compact_util.

WT-13345 Remove turn_on_bg_compact from test_compact10.py

---

src/log/log_slot.c

The code coverage task complains about ```Non-matching opening bracket '{' detected``` which is caused by the preprocessor directives in log_slot.c. Rewrite it to avoid this warning.

WT-13327 Cleanup code in log_slot.c

---

tools/wt_verify/wt_verify.py

Currently if wt_verify.py does not handle the case for empty trees. Add exceptions for both `dump_blocks` and `dump_pages` so a message will be raised when there's no data to parse.

WT-13346 Add exception to wt_verify.py when there's no data to parse

---

src/btree/bt_sync.c

(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/7465e7e9fa01fa69c92dffc0e1d303f20adedf17)
(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/0085ab419b0f049e696f1be752695bdde588488f)

WT-9502 Checkpoint cleanup should not mark a dirty page as obsolete (5.0 Backport)

---

test/model/src/core/kv_table.cpp
test/model/src/driver/kv_workload.cpp
test/model/src/driver/kv_workload_generator.cpp
test/model/src/driver/kv_workload_runner_wt.cpp
test/model/src/include/model/driver/kv_workload.h
test/model/src/include/model/driver/kv_workload_generator.h
test/model/src/include/model/driver/kv_workload_runner.h
test/model/src/include/model/driver/kv_workload_runner_wt.h
test/model/src/include/model/kv_table_item.h
test/model/test/model_workload/main.cpp
test/model/tools/model_test/main.cpp

This PR increases the probability that RTS in the test would see a checkpoint with evicted prepared data. It accomplishes this by adding a delay between when a transaction is prepared and when it is committed or rolled back. It implements this delay by modifying `kv_workload_generator::generate_transaction` to add a number of no-ops (`model::operation::nop`) after `prepare_transaction`, which ultimately causes the commit or rollback operation to come up later in the execution schedule. (The `nop` operation is not actually added to the final workload, but I still implemented it as an actual workload operation as that was more straightforward than doing something one-off).
After introducing these changes, the PR found a new way to reproduce WT-13232 for which `kv_table::truncate` didn't …

WT-13352 Add recovery checkpoints that contain evicted prepared data to test/model

---

tools/wt_verify/wt_verify.py

Add new argument -i/--input_file so wt_verify can accpet output of wt verify command as an input.

WT-13362 Enable wt_verify.py to accept output of wt tool as an input

---

src/include/extern.h
src/session/session_api.c
test/unittest/CMakeLists.txt
test/unittest/tests/test_session_config.cpp

1. Fixed a bug that meant callers could not set cache_max_wait_ms to 0.
2. Implemented a unit test for this functionality.
3. Extended it to all but the prefetch configuration logic which is too special for easy unit testing.

WT-13377 Fix session->reconfigure with respect to cache_max_wait_ms, accept 0

---

test/evergreen/code_change_report/code_change_info.py

Catch GitErrror exceptions too, and use an empty diff if an exception occurs.

WT-13398 Improve handling of PyGit2 exceptions in code_change_info.py

---

src/conn/conn_api.c
src/conn/conn_open.c
src/txn/txn_recover.c
test/suite/test_verbose04.py
tools/rts_verifier/operation.py

Add additional logs in the flow of WiredTiger recovery and also convert the existing logs into INFO logs to log them every time when WiredTiger is performing recovery.

WT-13381 Improve startup logs

---

src/conn/conn_compact.c

The background compaction thread is supposed to clean all its stats when disabled by the application or when `run_once` is configured to `true` and all the files have been parsed. The changes address the second scenario that was missing.

WT-13447 Reset background compaction stats after a full iteration with run_once

---

dist/s_string.ok
src/block/block_ext.c
src/block/block_session.c
src/include/extern.h
test/unittest/tests/block/test_block_session_ext.cpp
test/unittest/tests/block/test_block_session_size.cpp
test/unittest/tests/utils_extlist.cpp

The ticket changes the free functions to pass in double pointers instead. The reason behind this change is for testing purposes.  When we pass in a single pointer reference that is going to be freed, C does a copy-by-value of the pointer and does not clear the original pointer reference. Therefore if we pass in the pointer to the pointer, we can properly clear the original pointer to NULL.

WT-13451 Update free block functions to pass in double pointers and make it consistent with wiredtigers free pattern

---

src/block/block_ext.c

__block_off_remove depends upon the pointer to the memory to be freed not changing.  Due to WT-13451 the pointer to the memory to be freed was zeroed. The fix is to free a copy of the pointer to the memory instead of the original pointer.

WT-13479 __block_off_remove no longer sets el->last = nullptr

---

src/block/block_ext.c
test/unittest/tests/block/test_extent_list_search.cpp

This was found by one of the unit tests in WT-13443 block_ext testing -- Search.
This PR both fixes the bug and enables the unit test that reproduces the problem. It was disabled before so the patch build to merge the unit tests would pass.

WT-13440 __block_off_match() returns true for one empty extent test case

---

src/evict/evict_lru.c

The evict exclusive logs are useful to identify when an eviction server is skipping a particular file, but printing them by default causing too much noise when there are too many files in the database.

WT-13477 Reduce evict exclusive log levels to debug1

---

dist/s_string.ok
test/unittest/CMakeLists.txt
test/unittest/tests/block/test_block_file.cpp
test/unittest/tests/wrappers/config_parser.cpp
test/unittest/tests/wrappers/config_parser.h
test/unittest/tests/wrappers/mock_connection.cpp
test/unittest/tests/wrappers/mock_connection.h
test/unittest/tests/wrappers/mock_session.cpp

This tickets aims to test the block manager flile open. There are a few technical changes I needed to make and would like to get reviews on:
- I have created a config parser that deals with configuring wiredtiger configurations. It would construct the config string and pass it into the first entry in the char ** array.
- I have tried to test all the possible scenarios in the file open.
- There are a few scenarios where it is not possible to test. For example, the function creates a local flag that is not persisted anywhere inside the block struct. I will create a new ticket to address the testability of this. Another case requires the file size to branch into the if statement. This was proven hard to test.
- I currently use `__wti_bm_close_block` to clear the block references.
- I created …

WT-13403 Implement block manager file open unit tests

---

test/evergreen.yml

The code coverage report PR comment recently broke, likely because support for the previous token was removed as part of the move to the dynamic token tooling.

WT-13506 Dynamically generate github token for code coverage comment in PRs

---

test/unittest/README.md

This change fixes a couple inaccuracies in the README file for our unittest directory
- To build the tests you need to specify the `-DHAVE_UNITTEST=1` option to `cmake`
- The name of the executable to run the tests was incorrect
Image of the update text is attached.

WT-13507 Fix README.md for WT unit tests

---

dist/s_string.ok
src/block/block_ext.c
test/unittest/tests/block/test_extent_list_insert_block.cpp
test/unittest/tests/utils_extlist.cpp

Fixed test function get_off_n. Assert in __block_append if not an append because it implements only appends. Added comments explaining stack returned by __block_off_srch_last, how __block_append uses it, and the lazy update of WT_EXTLIST.last.

WT-13456 Fix test function get_off_n. Assert in __block_append if not an append.

---

src/config/config_collapse.c
src/conn/conn_log.c
test/suite/test_reconfig05.py
test/test_coverage.md

This fixes an issue in `__config_merge_scan`, which did not recognize key/value pairs such as `log=(enabled)` to be recognized as structs. This had the unfortunate consequence of merging `log=(enabled=false)` and `log=(enabled)` to still result in `log=(enabled=false)`.
This could, for example, cause `WT_CONNECTION::reconfigure` to not work if the connection was opened with just `log=(enabled)`. In that case, the connection's own config string would still contain `enabled=false` but the connection flags would have `WT_CONN_LOG_ENABLED` set. This mismatch would then cause `__wti_logmgr_config` to fail.

WT-13512 Fix recognizing structs when merging configs

---

dist/s_string.ok
src/block/block_session.c
test/unittest/CMakeLists.txt
test/unittest/tests/block/test_block_session_bms.cpp
test/unittest/tests/block/test_block_session_ext.cpp
test/unittest/tests/block/util_block.h

The ticket here deals with only the block manager session type unit tests. I have added a util_block.h file inside the folder so that I could use the validate function within the unit test file.

WT-13438 Implement block_session bms function unit tests

---

src/block/block_ckpt.c
src/block/block_read.c
src/block_cache/block_cache.c
src/block_cache/block_mgr.c
src/include/extern.h

The __wt_blkcache_open function should live in the block_cache.c file instead of the block_mgr.c file. The other block cache functions in the file are really about block manager operations. Rename them properly.

WT-13528 Move the block cache functions to block_cache.c

---

src/btree/bt_debug.c
src/btree/bt_handle.c
src/btree/bt_slvg.c
src/btree/bt_vrfy.c
src/include/btmem.h
src/include/btree.h
src/include/btree_inline.h
src/include/extern.h
src/include/txn_inline.h
src/reconcile/rec_write.c
src/txn/txn.c
test/suite/test_truncate28.py
test/unittest/tests/block/test_block_addr.cpp

WiredTiger doesn't allow out of order commit timestamp and it return an error whenever an operation is trying to commit with a timestamp less than the existing timestamp on an update. But it missed to verify the truncate commit timestamp.
The WiredTiger timestamp usage check is extended for the truncate operations also doesn't allow an out of order commit timestamp to be performed.

WT-13442 Do not allow out of order truncate commit timestamp

---

src/txn/txn_ckpt.c

This pull request replaces the timestamp category logging with checkpoint category logging since it is in the checkpoint flow.

WT-13492 Review Checkpoint logging

---

src/history/hs_conn.c

The connection's default session is used to save/restore the connection state whenever a connection API is called. The same default session is also used for creating the history store table. After allowing the statistics cursor to be opened during recovery, it is possible that the stats collector thread can interact with the default session while it is creating the history store table.
To avoid these unnecessary interactions with the default session, use the internal history store session while creating the history store table.

WT-13546 Use internal session to create the history store table

---

src/conn/conn_dhandle.c
src/history/hs_conn.c

The changes clean up the `hs_conn.c` file by:
- Removing unnecessary wrappers
- Using the right macros
- And formatting comments following our guidelines

WT-13547 hs_conn.c cleanup

---

lang/python/setup_pip.py
lang/python/wiredtiger.i

The change removes boilerplate checking for the strerror call.  The boilerplate checks assume the result is an int, which is not appropriate for this method.  Even moderate type checking will flag this error (I'm not sure why we've seen it up til now).
The wrapper file (one of the outputs of running SWIG), has this difference after the change:
```
$ diff lang/python/CMakeFiles/wiredtiger_python.dir/wiredtigerPYTHON_wrap.c{.ORIG,}
5808,5825c5808,5810
<     {
<       SWIG_PYTHON_THREAD_BEGIN_ALLOW;
<       result = (char *)(arg1)->strerror(arg2,arg3);
<       SWIG_PYTHON_THREAD_END_ALLOW;
<     }
<     if (result != 0)
<     /*@SWIG:/Users/dda/wt/git/wt-13510-swig-strerror/lang/python/wiredtiger.i,535,SWIG_ERROR_IF_NOT_SET@*/
<     do {
<       if (PyErr_Occurred() == NULL) {
<         /* …
```

WT-13510 Fix WT_SESSION.strerror for SWIG, it shouldn't do "int checking" for its result

---

src/txn/txn_ckpt.c

1c8fa9c91
Co-authored-by: Chenhao Qu <chenhao.qu@mongodb.com>
(cherry picked from commit 25ae7562f345eef2c382ed356ffd1b929a044685)

WT-13409 One ret in __txn_checkpoint is not handled (v8.0 backport) (#11022)

---

src/btree/bt_compact.c
src/btree/bt_cursor.c
src/btree/bt_random.c
src/btree/bt_read.c
src/btree/bt_split.c
src/btree/bt_stat.c
src/btree/bt_sync_obsolete.c
src/btree/bt_walk.c
src/btree/row_modify.c
src/conn/conn_cache_pool.c
src/conn/conn_compact.c
src/conn/conn_prefetch.c
src/evict/evict_inline.h
src/evict/evict_lru.c
src/evict/evict_page.c
src/evict/evict_stat.c
src/history/hs_rec.c
src/include/btree_inline.h
src/include/cursor_inline.h
src/include/extern.h
src/include/misc_inline.h
src/include/txn_inline.h
src/lsm/lsm_tree.c
src/lsm/lsm_work_unit.c
src/txn/txn.c

Now that all the eviction-related files are present in the evict/ folder and there is folder-module mapping, it becomes easier to use the current prefixes as they were originally intended. In this PR, I have done the following:
1. Removed functions (mainly public APIs) that were not part of eviction - 
Functions that were irrelevant to eviction have been removed to clean up the API -  `__wt_page_release_evict` and 
`__wt_page_dirty_and_evict_soon`
3. `__wti_btree_dominating_cache` function is only used in evict_lru.c, so it was relocated to improve modularity.
4. Renamed functions with prefixes starting with __wt_evict in the evict folder (except verbose functions) - After discussions with Etienne, we decided not to rename verbose-related functions yet, as a separate module will be …

WT-13561 Refactor Eviction Public/Private API

---

src/evict/evict_page.c
src/include/btmem.h
src/txn/txn_rollback_to_stable.c

WT-9939. Added entering split generation on eviction to prevent parent from being freed after split.
(cherry picked from commit 5c981e88d873ea0c670ee9f078ded60d4ad6ff2a)

WT-9939 Enter split generation on eviction to prevent split parent free too early (#8799)

---

src/btree/bt_cursor.c
src/btree/col_modify.c
src/btree/row_modify.c
src/include/extern.h
src/include/log_inline.h
src/include/txn_inline.h
src/session/session_api.c

This is an option to reduce the dependency between the session module and the log module.
session invokes __wt_log_op before logging the transaction operation. The usage is as :
```
if (__wt_log_op(session))
WT_ERR(__wt_txn_log_op(session, NULL)); 
```
All the other callers of __wt_log_op have the same above usage pattern.
__wt_log_op indicates whether a transaction operation needs to be logged or not. 
__wt_log_op is an inline function.
For performance reasons, it is better to have the check (__wt_log_op) as inline, and based on the check result, a relatively heavy function __wt_txn_log_op will be invoked.
The thought behind this change suggestion is to, the conditional check to determine whether an operation is required and whether the operation itself, should belong to the same module. …

WT-13521 POC-weaken-session-log-dependency-2

---

src/btree/bt_import.c
src/btree/bt_sync.c
src/btree/bt_sync_obsolete.c
src/meta/meta_ckpt.c
src/txn/txn_ckpt.c
test/suite/test_cc09.py

The Checkpoint verbose category messages `WT_VERB_CHECKPOINT`, `WT_VERB_CHECKPOINT_PROGRESS`, and `WT_VERB_CHECKPOINT_CLEANUP` are configured to log at either the `__wt_verbose_debug1`, `__wt_verbose_debug2`, `__wt_verbose_notice` or `__wt_verbose_info` levels. The `__wt_verbose_worker` function, responsible for handling verbose logging, is invoked from `__wti_ckpt_verbose` and is protected by the `WT_VERBOSE_DEBUG_2` level. All the checkpoint verbose category messages are set to the appropriate vebose levels.

WT-13493 Review Checkpoint logging debug levels

---

src/docs/build-posix.dox
test/compatibility/common/compatibility_common.py
test/evergreen.yml
test/multiversion/wt_multiversion.sh

Replace the existing SSH clones (i.e. git clone git@//github.com/<org>/<repo>) with either HTTP clones or the `github.generate_token` Evergreen project command, to support the deprecation of SSH cloning in Evergreen.
Please note the change will need to be backported to all supported release branches.

WT-13560 Deprecate SSH Cloning of Git repositories

---

dist/prototypes.py
src/include/extern.h
src/include/extern_darwin.h
src/include/extern_linux.h
src/include/extern_posix.h
src/include/extern_win.h

Update the `prototypes.py` script to create dedicated `*.h` and `*_private.h` header files in each component folder.
Previously all function prototypes were defined in `extern.h`. This script allows modules to define all the functions owned by the module in headers inside that module.
The files also support adding content manually. Only code between the `DO NOT EDIT` flags will be automatically updated. this allows developers to place other items (macros, structs) inside the files.
This PR only introduces the changes to allow creation of these files on a per-module basis. Future tickets will enable it for modules by adding them to the `MODULARISED_COMPONENTS` field.

WT-13563 Modify dist/prototypes.py to split public and private functions into separate headers

---

dist/prototypes.py
src/include/extern.h
src/include/extern_darwin.h
src/include/extern_linux.h
src/include/extern_posix.h
src/include/extern_win.h

Reverts wiredtiger/wiredtiger#11064
I found some more s_all scripts that will need updating to handle the case when this script move headers into a module. Reverting to re-deliver with all required s_all changes in one commit.

Revert "WT-13563 Modify dist/prototypes.py to split public and private functions into separate headers"

---

test/suite/test_alter02.py

Fix the `test_alter02` failures. This is an issue with the test, which assumes that table metadata would contain strings such as `log=(enabled=true)`, but since the introduction of `log.oligarch_constituent`, the table metadata instead contain strings such as `log=(enabled=true,oligarch_constituent=false)`.

LABS-1090 Fix test_alter02 failures

---

src/block_disagg/block_disagg_mgr.c
src/block_pantry/block_mgr.c
src/btree/bt_handle.c
src/btree/bt_page.c
src/include/btree.h

Using non-disaggregated objects can currently fail due to:
* The `btree` or the `btree` dhandle being NULL when detecting whether the object is disaggregated.
* The assertion that checks whether page IDs are set is triggered for non-disaggregated objects.

LABS-1089 Fix SIGSEGV & page ID assert for non-disaggregated objects

---

ext/storage_sources/dir_store/dir_store.c
src/block_cache/block_tier.c
test/suite/test_tiered16.py
test/suite/test_tiered18.py

A collection of fixes to get most of our existing tiered tests working again. This PR fixes everything except `test_tiered13`, which doesn't work because we no longer print error messages.
Fixes included in the PR:
* Fixed a double-free if `dir_store_ckpt_load_internal` fails.
* Fixed a segfault if `__wt_block_open` fails.
* Don't load object checkpoints if the file is not an object directory (but rather a regular tiered storage object).
* Account for possible additional fields within the `log` configuration struct.
* Set the dir store `cache` setting explicitly if the test depends on it.

LABS-1096 Get most of the existing tiered tests working again

---

dist/stat_data.py
src/btree/bt_sync_obsolete.c
src/evict/evict_page.c
src/include/extern.h
src/include/stat.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_cc09.py

The checkpoint cleanup thread can now read pages from disk whenever they contain globally visible content.
(cherry picked from commit c31f5590c121f7991ac30a527dd8587beaea2f57)

WT-13234 Read pages with obsolete time window from disk (v8.0) (#10896)

---

src/block_cache/block_cache.c

The existing free in the block cache removal thread is insufficient, as it's guarded by a `while (!blkcache->blkcache_exiting)` clause. Also free this structure on blkcache destruction.

LABS-1097 Free block_meta structure on blkcache shutdown

---

ext/page_log/palm/CMakeLists.txt
ext/page_log/palm/palm.c
ext/page_log/palm/palm_verbose.c
ext/page_log/palm/palm_verbose.h
test/suite/helper_disagg.py

This adds verbose output when the PALM extension is loaded with the "verbose=1" flag set.  The output looks like this:
```
palm_handle_put(plh=0xaaab09c9fa50, page_id=7a, checkpoint_id=0, is_delta=0, buf=
00000000 00000000 16000000 00000000 3c000000 02000000 06200001 00000000
00000000 4e2016fa 01000000 05003820 c09989c0 39c6eae4 278f7e47)
oligarch mgr clearing 2
palm_handle_put(plh=0xaaab09c9fa50, page_id=7b, checkpoint_id=0, is_delta=0, buf=
00000000 00000000 17000000 00000000 3c000000 02000000 06200001 00000000
00000000 e4d4785e 01000000 05003820 c09989c0 39c6eae4 278f7e47)
oligarch watcher started
[.] __wt_block_disagg_checkpoint_load(): 0xc027bce426759f9d
palm_handle_get
palm_handle_get(plh=0xaaab0bd23080, page_id=67, checkpoint_id=0, buf=
fd060000 00000000 00000000 00000000 02000000 …
```

LABS-1100 Add verbose output for PALM.

---

src/conn/conn_api.c
src/txn/txn.c

The newly added/modified logs can improve the WiredTiger shutdown flow where it is spending time as part of the shutdown.

WT-13411 Improve WiredTiger shutdown logs

---

dist/docs_data.py
dist/prototypes.py
src/evict/evict.h
src/evict/evict_private.h
src/include/extern.h
src/include/wt_internal.h

Move the header files relevant to evict/ from src/include into src/evict. This consolidates all of our evict code into a single location.
To do so:
- Add evict to SELF_CONTAINED_MODULES in prototypes.py and run s_all
- Move the contents of src/include/evict.h into the public and private headers.

WT-13623 Move evict's header files into src/evict

---

test/unittest/tests/block/test_block_api_misc.cpp
test/unittest/tests/block/test_block_api_write.cpp
test/unittest/tests/block/util_block.cpp
test/unittest/tests/block/util_block.h

Moved test_and_validate_write_size() to util_block.cpp to fix link issues that occur when HAVE_UNITTEST_ASSERTS is set.
Note that it was necessary to add a parameter to test_and_validate_write_size() to pass in the allocation size rather than rely on a file-scope value.

WT-13646 Fix link issue with catch2-unittest-assertions

---

lang/python/wiredtiger.i

SWIG 4.3.0 version has introduced a couple of incompatibilties and WiredTiger is affected with the SWIG_Python_AppendOutput API.
Change the code to use SWIG_AppendOutput API that internally calls the SWIG_Python_AppendOutput API with the required parameters.

WT-13667 Support compiling WiredTiger with SWIG 4.3.0 version

---

test/format/import.c

Trivial PR to fix a typo (that didn't cause the test to fail).

WT-13676 Fix typo. Extra char at end of config string.

---

src/block_disagg/block_disagg_ckpt.c
src/block_disagg/block_disagg_write.c
src/block_pantry/block_ckpt.c
src/conn/conn_oligarch.c
src/include/extern.h
src/include/meta.h
test/suite/test_oligarch06.py
test/suite/test_oligarch07.py

The PR makes a few changes:
* Use checkpoint ID 1 instead of 0 (until we implement checkpoint IDs for real)
* Use table ID 1 instead of 0 for the metadata
* Use page ID 1 instead of 0 for the main metadata page
* Update the tests accordingly
The PR also starts passing in the current and new block meta arguments to the write as we discussed, albeit currently only still internally within the new BM.

LABS-1171 Start table, checkpoint, and page IDs at 1

---

dist/stat_data.py
src/btree/bt_stat.c
src/conn/conn_cache.c
src/include/btree_inline.h
src/include/cache_inline.h
src/include/extern.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_stat02.py
test/suite/test_stat08.py

Reverts wiredtiger/wiredtiger#11128
MongoDB relies on the `cache_bytes_dirty` for error checks when the cache cannot handle a transaction.
The additional stats need to be added first so that we can change the error check in the server before we can remove `cache_bytes_dirty`.

Revert "WT-13642 Add separate statistics for dirty leaf and internal page bytes"

---

test/evergreen.yml

The many-collections test is running out of space on evergreen due to storing bazel's cache in the home directory instead of the `/data` dir. This is an interim fix to resolve test failures while we pursue a proper fix in WT-13607.

WT-13679 Soft link ~/.cache to the /data folder in many-collections-test

---

dist/stat_data.py
src/btree/bt_stat.c
src/conn/conn_cache.c
src/include/btree_inline.h
src/include/cache_inline.h
src/include/extern.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

We currently expose the tracked number of dirty bytes in the cache as a statistic: `cache_bytes_dirty`
However, this does not differentiate between leaf or internal pages.
This metric is currently incorrectly interpreted in t2 as the reason for the cache being in the `WT_EVICT_CACHE_DIRTY_HARD` state and causing application threads to evict. This is misleading because the dirty hard state is set based on the dirty leaf page bytes not the total dirty bytes.
The dirty leaf and internal bytes are already tracked in the cache structure as:
`bytes_dirty_intl`
`bytes_dirty_leaf`
This PR exposes these as new statistics.

WT-13642 Add separate statistics for dirty leaf and internal page bytes

---

test/model/src/driver/kv_workload.cpp
test/model/src/driver/kv_workload_runner_wt.cpp
test/model/src/include/model/driver/kv_workload.h
test/model/src/include/model/driver/kv_workload_runner.h
test/model/src/include/model/driver/kv_workload_runner_wt.h

The model test replay functionality is incredibly useful to debug issues with deterministic reproducibility. It would be nice to be able to break inside of WiredTiger part way through replaying a workload. This exact functionality was used by me to solve WT-13612. 
This PR adds that functionality.

WT-13678 Add breakpoint functionality to model workload replay

---

src/conn/conn_dhandle.c

Currently only `ckpt_apply`, `ckpt_skip`, `ckpt_apply_time` and `ckpt_skip_time` are set to 0 during checkpoint prepare, and t2 is showing some of the most recent stats incrementally while others are not. We should set them to 0 as well so t2 can have a consistent view for all the `checkpoint most recent `stats.

WT-13638 Set checkpoint most recent stats to 0

---

test/evergreen.yml

Bazel stores its cache in the home folder, but our evergreen spawn hosts don't have enough storage space to handle a mongo compilation. Update `compile mongodb` to instead store bazel output in the evergreen working dir which has a larger backing storage.
This PR removes the temporary fix from WT-13679 and replaces it with a proper .bazelrc solution

WT-13607 Save bazel cache into evergreen workdir instead of home folder

---

src/cursor/cur_oligarch.c
test/suite/test_oligarch10.py

Implement WT_CURSOR::largest_key for Oligarch tables, because it is needed by the Server.
The implementation of `__coligarch_largest_key` is mostly a copy of `__wti_cursor_largest_key`.

LABS-926 Implement WT_CURSOR::largest_key for Oligarch tables

---

src/block_disagg/block_disagg_ckpt.c
src/block_pantry/block_ckpt.c

Close the metadata cursor in the block manager's `checkpoint_resolve`. This causes calling `WT_SESSION::checkpoint` to result in having an active transaction, which would in turn cause the server's `WiredTigerSessionCache::releaseSession` to fail.

LABS-927 Fix resource leak in checkpoint_resolve

---

ext/page_log/palm/palm.c
ext/page_log/palm/palm_kv.c
ext/page_log/palm/palm_kv.h
src/block_disagg/block_disagg_read.c
test/suite/helper_disagg.py
test/suite/test_oligarch10.py
test/suite/test_oligarch11.py

- Fixed retries in block manager, the result_count was not being reset.
- Added a way, with a palm config variable, to emulate materialization delays
- Added a test to confirm that it all works

LABS-1200 Fix retries in block manager and emulate materialization delays in PALM for disagg storage

---

dist/ruff_check.py

The changes improve the error handling when a Ruff binary is found with a version that is not matching the expected one.

WT-13680 Improve error handling when Ruff is not found with the expected version

---

dist/s_docs
src/docs/top/Doxyfile.11
src/docs/top/Doxyfile.9

The "s_docs -l" command run failed because the `doxyfile` variable is not set. The setting is located in the `build` function, which is not called in the command invocation path. 
The solution is to abstract the doxyfile setting and doxygen command checking logic into a new function, and call the function in all paths that doxyfile is needed. Also added 2 symlink files to avoid the doxyfile not found error when running the command with the specific versions of doxygen (9 and 11).

WT-13710 Fix "s_docs -l" run failure

---

dist/stat_data.py
src/btree/bt_import.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_import10.py

MongoDB recently added using import and `repair=true` in a rare/error path. Add a statistic to give signal about how often this call is made (because it has time/performance implications for import).

WT-13713 Add import with repair stat

---

test/evergreen.yml

The change intends to migrate to IBM-hosted Series machines. Currently WT-13690 was created as fallout. I have added a FIXME that would be addressed went the fix came in.

WT-13527 Migrating to new IBM-hosted zSeries hosts

---

test/evergreen.yml

DevProd are migrating our MacOS hosts from MscStadium to AWS so we are making changes in WT evergreen configuration to switch from macos-13-arm64 to macos-14-arm64. Our compilation requires the swig package, which is no longer installed in macos by default. Therefore I have modified the script for configure_wiredtiger and make_wiredtiger to install swig as a temporary workaround. A ticket has been filed to install siwg on our macos-14-arm64 distro and the temporary workaround will be removed after that ticket is completed.

WT-13525 Migrating to AWS-based MacOS hosts

---

src/btree/bt_read.c
src/include/btmem.h
src/include/cell.h
src/include/cell_inline.h
src/include/extern.h
src/reconcile/rec_write.c

Delta can be read back by the same node so it also needs to handle transaction id.

SLS-492 Add transaction id support for deltas

---

src/include/session.h
src/session/session_api.c
src/support/scratch.c

This pull request Implements a locking mechanism to prevent concurrent access to the scratch buffer while using the connections default session.

WT-13640 Implement Locking Mechanism for default session scratch buffer operations

---

src/btree/bt_delete.c
test/suite/test_backup31.py
test/suite/test_bug035.py

The problem described in the ticket is that, since the HS is non-transactional, page_del->committed is not set. This prevents the deletion of the page, causing reconciliation to retain the original version. By treating HS pages that are fast-truncated during selective backup as globally visible (even though they are non-globally visible) and setting page_del to null, we eliminate this issue. This allows us to remove the pages without checking visibility information, which is acceptable because the HS is non-transactional.

WT-13716 Prevent retention of fast truncated history store pages

---

src/block_cache/block_io.c
src/block_disagg/block_disagg_ckpt.c
src/block_disagg/block_disagg_write.c
src/btree/bt_page.c
src/include/extern.h
src/reconcile/rec_write.c

@pmacko86 As discussed in the previous pr, this pr changes to let btree own the responsibility to assign page id and checkpoint id to a page. It also sets the base checkpoint id and backlink checkpoint id of a page.
TODO: fix the checkpoint id assign logic with further discussion.

SLS-488 Set the checkpointids for the page

---

test/evergreen.yml

The code coverage report PR comment recently broke, likely because
support for the previous token was removed as part of the move to the
dynamic token tooling.
(cherry picked from commit 3f506d1aa6e92628677b31badf6233c8cc82ea6a)

WT-13506 Dynamically generate github token for code coverage comment in PRs (#11013) (v8.0 backport)

---

test/evergreen.yml

The code coverage report PR comment recently broke, likely because
support for the previous token was removed as part of the move to the
dynamic token tooling.
(cherry picked from commit 3f506d1aa6e92628677b31badf6233c8cc82ea6a)

WT-13506 Dynamically generate github token for code coverage comment in PRs (#11013) (#11199)

---

src/btree/bt_sync.c
src/include/btmem.h
src/include/btree_inline.h
src/rollback_to_stable/rts_btree_walk.c

This reverts commit bda87786ee50cb98aa03633011f0225068f68f0c.

WT-13745 Revert "WT-13591 Don't leave dirty btrees after RTS/recovery/shutdown(#11061)"

---

src/block_disagg/block_disagg_write.c
src/btree/bt_page.c
src/include/btree_inline.h
src/reconcile/rec_write.c

SLS-486 Don't evict pages that belongs to the next checkpoint

---

dist/prototypes.py
src/include/extern.h
src/include/wt_internal.h
src/reconcile/reconcile.h
src/reconcile/reconcile_private.h

Now the reconcile module has two header files.
1. reconcile.h
2. reconcile_private.h.
The reconcile.h has all the public members and the reconcile_private.h has all the private members of the reconcile module.

WT-13733 Split the reconcile header file into two seperate headers

---

src/btree/bt_split.c
src/reconcile/rec_write.c

Two checks can be replaced by using the __wt_btree_syncing_by_other_session function. It should improve the readability of the code.

WT-13750 Refactor two if checks using a function

---

ext/page_log/palm/palm_kv.c
test/suite/test_oligarch12.py

Allow PALM to properly read pages from previous checkpoints:
* Position the lmdb cursor on a key with the correct checkpoint ID.
* When calling "next," stop when going past the requested checkpoint ID.

SLS-532 Fix reading previous checkpoints in PALM

---

src/btree/bt_split.c
src/reconcile/rec_write.c

We currently skip write the disk image to disk if it's an update restore eviction because it will be written again by the checkpoint later anyway. However, it is not correct if we have delta. We need to ensure the delta is built on a disk image that has been written to disk. Change to always write the disk image even for update restore eviction.

SLS-51 Write disk image for update restore eviction

---

src/btree/bt_sync.c
src/include/btmem.h
src/include/btree_inline.h
src/rollback_to_stable/rts_btree_walk.c

The changes ensure WiredTiger does not leave btrees dirty in specific scenarios such as RTS, recovery and shutdown. In those scenarios, since there should not be other actors using the btrees, checkpoint should be able to process them and mark them clean.

WT-13746 Don't leave dirty btrees after RTS/recovery/shutdown

---

src/txn/txn.c

To avoid unnecessary regressions, skip truncate commit timestamp validation for non-standalone MongoDB builds, as they don't currently use timestamps with truncate operations.

WT-13766 Disable truncate commit timestamp validation for non-standalone builds

---

src/txn/txn.c

Reverts wiredtiger/wiredtiger#11227

Revert "WT-13766 Disable truncate commit timestamp validation for non-standalone builds"

---

src/conn/conn_oligarch.c
src/include/connection.h
src/include/extern.h
src/txn/txn_ckpt.c

We should still advance the checkpoint id in the failure case. This is important for the page service. We may write some pages partially in the failed checkpoint. We need to distinguish them by advancing the checkpoint id.

SLS-558 Handle advancing checkpoint in failure cases

---

test/format/format.sh

127 is a reserved error code indicating "command not found" but we're using it to report an error when test/format. Change this code to the unreserved code 117 instead.

WT-13770 Update test/format not to use error code 127

---

src/conn/conn_oligarch.c
src/support/scratch.c
test/suite/test_bug028.py
test/suite/test_oligarch07.py
test/suite/test_oligarch12.py

It's possible for code to do a WT_CLEAR on the item, so when it gets freed and returned to the scratch buffer pool, it will still have that flag unset. Unfortunately, we previously only set the flag when we allocated a WT_ITEM, so cached items would remain unaligned.
This isn't a problem in develop since they're removing the `WT_ITEM_ALIGNED` flag.
Only one of the two affected tests is properly fixed, as test_oligarch07 hits another bug that's being investigated in a different branch.
This change also removes a leak in `__wt_disagg_get_meta` where we replaced the contents of an allocated item.

SLS-552 Fix test_oligarch{07,12} test failures

---

test/catch2/block/util_block.cpp

The removal of the directIO feature in WT-13227 also removed the flag `WT_ITEM_ALIGNED`. It is no longer necessary to set the flag as no other logic relies on the alignment flag.

WT-13772 Remove use of WT_ITEM_ALIGNED in util_block

---

src/cursor/cur_file.c
src/cursor/cur_oligarch.c
src/cursor/cur_std.c
test/suite/test_oligarch10.py
test/suite/test_oligarch13.py

Fix the implementation of the largest key implementation. The previous implementation only implements the largest visible keys. However, largest key should return the largest key even it's not visibility.
Implement the random cursor function for oligarch table. I borrowed the main implementation from the lsm code. It is not a uniform random solution yet as it doesn't consider the key size of the ingest table and the stable table but it should work for now.
Fix a bug in oligarch search near.

SLS-518 Fix largest key implementation and implement a simple random cursor for oligarch table

---

src/schema/schema_plan.c

The return value from `__find_next_col` can be overwritten by the outer for loop before it's checked. This adds a return value check within the while loop to check the return status of `__find_next_col`.

WT-13783 Fix clang analyzer dead code in schema_plan.c

---

test/suite/test_oligarch15.py

Add a tests that mimics the start of a leader node in mongod and the subsequent restart without local files.
The test includes several short-term workarounds with the corresponding FIXMEs for issues that we have not addressed yet.

SLS-498 Create a test that mimics node start and restart in mongod

---

bench/wtperf/wtperf.c

Improve scan performance report of `wtperf` so that it's possible to assess scanning performance.

WT-13789 wtperf report scan performance in a more useful way

---

ext/page_log/palm/palm.c
src/conn/conn_api.c

Also add a way to set palm config via the environment for easier debugging with mongod.
The changes allow PALM to be "auto-registered" without any shared library loading provided mongod is built with "HAVE_BUILTIN_EXTENSION_PALM=1".  That means that mongod can use "page_log=palm" in place of page_log=pali".

SLS-579 Prepare PALM to be imported into mongod.

---

test/evergreen.yml

Upgrading macos machines from version 10.14 to 11 as 10.14 is getting deprecated.

WT-9102 Migrate WT Mac tests from macOS 10.14 to 11.0 (v6.0 backport)

---

test/evergreen.yml

Upgrading macos machines from version 10.14 to 11 as 10.14 is getting deprecated.

WT-9102 Migrate WT Mac tests from macOS 10.14 to 11.0 (v5.0 backport)

---

test/evergreen.yml

This was fall out from WT-13527, basically `split-stress-test ` was changed to compile with v4 tool chain, and thus needed v4 in it's path when calling tests. I have updated that now.

WT-13801 Update mongodbtoolchain version for ubuntu2004 stress tests

---

src/btree/bt_sync_obsolete.c
src/checkpoint/checkpoint_txn.c
src/conn/conn_api.c
src/conn/conn_open.c
src/include/extern.h

Remove the word "checkpoint" from obsolete cleanup functions.
The PR introduces a new term, "obsolete cleanup" replacing "checkpoint cleanup" and updates some externally visible strings like session name and logs.

WT-13833 Remove the word "checkpoint" from obsolete cleanup functions

---

src/rollback_to_stable/rts_api.c

Removed a duplicate call of `rts->dryrun = false` when rolling back to stable, now it is called exactly once inside the existing `__rollback _to_stable_finalize()` function.
Also moved the call to set `threads_num = 0` inside `__rollback _to_stable_finalize()`.

WT-13753 Remove redundant rollback to stable finalize code

---

src/btree/bt_sync_obsolete.c
src/checkpoint/checkpoint_txn.c
src/conn/conn_api.c
src/conn/conn_open.c
src/include/extern.h

This reverts commit c33617214f566614a74895cf8cb3f55d6b9a9d7e.
The reason for reverting this commit is that this work's scope extends far beyond simply renaming a handful of functions. The term "checkpoint cleanup" is widely used throughout the codebase, including externally visible elements like configuration variables, log strings, verbosity levels, etc.
While renaming is technically feasible, it is likely impractical due to the effort/benefit ratio. Instead, we will rather document it.

Revert "WT-13833 Remove the word "checkpoint" from obsolete cleanup functions (#11285)

---

src/support/err.c

Add a condition to give the user a more informative error message when they try to interact with lsm objects that are no longer supported.

WT-12753 Improve error log message for lsm objects

---

src/include/os.h
src/live_restore/live_restore_fs.c
test/cppsuite/tests/test_live_restore.cpp

Fix 6 minor/trivial Coverity warnings raised after merging in the live restore code.

WT-13841 Fix minor Coverity warnings in live restore

---

dist/api_data.py
src/config/config_def.c
src/conn/conn_api.c
src/include/conf.h
src/include/conf_keys.h
src/include/wiredtiger.in
src/live_restore/live_restore.h
src/live_restore/live_restore_fs.c
src/live_restore/live_restore_private.h
test/cppsuite/tests/test_live_restore.cpp
test/suite/test_live_restore01.py

The PoC live restore configuration relied on an `aux_path` parameter to specify the live restore path, additionally the existence of a path indicated that a live restore was in progress. A better defined API is needed to distinguish live restore from other usages of `aux_path`. To that end the `aux_path` config is removed and a `live_restore` configuration takes its place. 
It accepts the following options:
- `enabled`
- `path`
- `threads_max`

WT-13835 Updating the live restore API configuration

---

src/schema/schema_plan.c

Replaced occurrences of `WT_RET_TEST(ret != WT_NOTFOUND, ret);` with `WT_RET_NOTFOUND_OK(ret);` to update outdated method of dealing with error codes.

WT-13784 Replace WT_RET_TEST with WT_RET_NOTFOUND_OK in schema_plan.c

---

src/include/txn_inline.h
src/txn/txn_timestamp.c

Reverts wiredtiger/wiredtiger#11300
@ajmorton I used the deprecated macro in the pr. Will revert and change that.

Revert "WT-13849 Fix read pinned_timestamp multiple times in __wt_txn_pinned_timestamp"

---

src/support/json.c
test/suite/test_dump05.py

This error occurs when the WT command line tool is used to dump a table in json format (with the `-j` param).
There is a buffer (`buf`) in `json.c` being reused for loading lines of text to be dumped, and in some cases (particularly if subsequent lines are shorter than previous ones) the buffer is underfilled without adding a corresponding null terminator.
This leads to junk values being included at the end of each line in the dump output.
I've added in that null terminator where it's needed, as well as a check that the `bufsz` counter was calculated correctly, such that when it's time to add the closing quotes and null terminator, `bufsz = 2`.
I've also written a test case that creates a table with key/value pairs of varying lengths (this would guarantee the inclusion of junk values in …

WT-11946 Bug Fix for the WT command line tool JSON dump option

---

src/block/block_read.c

After investigating the code logic, it is clear that blk->checksum needs to be cleared for the calculation of the checksum and will remain cleared since it will not be revisited during a B-tree traversal. Therefore, there is no need to reset it to its original value, and no code changes are required.
However, during the investigation, a lot of time was spent understanding the logic of the code and why blk->checksum is cleared and not reset. To avoid similar confusion in the future, I am adding a comment here for reference.

WT-13549 Investigate block checksum getting cleared when performing read()

---

dist/api_data.py
src/conn/conn_api.c
src/evict/evict.h

Wiredtiger calls `__conn_session_size` during `wiredtiger_open` to reserve the session slots that threads can use. Currently for eviction workers and lsm_manager workers, we use the configured max threads value.
Both eviction max worker and lsm_manager max worker can be changed by the **WT_CONNECTION::reconfigure** API, and during the reconfiguration we don't recalculate the number of reserved session slots, causing potential running out of available session slots problem.
For lsm_manager workers I changed the code to use the macro `WT_LSM_MAX_WORKERS` (The max value we can configure for `lsm_manager.worker_thread_max`) to calculate the session slots. I have done the same for eviction, added a `WT_EVICT_MAX_WORKERS` in `evict.h` and used the value to calculate the session slots as well.

WT-13806 Fixed incorrect calculation for number of reserved session slots

---

src/live_restore/live_restore_fs.c

Fix a typo where the tombstone in live restore file system is used to tell us that we will never need to look in the source for this file in the future.

WT-13874 Fix a typo in live restore FS comment

---

src/block_disagg/block_disagg_write.c

Check that the page_log is not NULL before checking its contents, so that we can call __wt_block_disagg_write_internal without the page log being set up.

SLS-745 Allow calling __wt_block_disagg_write_internal without the page log

---

test/evergreen.yml
test/model/src/driver/kv_workload_generator.cpp
test/model/src/include/model/driver/kv_workload_generator.h
test/model/test/model_workload/main.cpp
test/model/tools/model_test/main.cpp

This pull request has the following changes :
- Implement a new feature in the RTS Model workload generator that will allow for the generation of random WiredTiger timing stress configurations, enabling comprehensive testing of various scenarios.
- Added an argument option to the model_test to enable generating the random timing stress configuration.
- Added an evergreen task to run the model test with the new random timing stress configuration.

WT-13798 Implement a random WiredTiger timing stress configuration within workload generator

---

test/cppsuite/tests/test_live_restore.cpp

The `truncate` calls in `test_live_restore.cpp` were broken for multiple reasons. Firstly we were passing both the table URI and a start cursor which is disallowed. Secondly the start cursor wasn't being positioned on the table.
This PR fixes both issues and adds `testutil_check` calls to all WT API calls that were missing them.

WT-13880 Fix truncate calls in test_live_restore.cpp

---

test/evergreen.yml

Upgrading to SWIG version 4.0 as the package "imp" is getting deprecated and version 4.0 and later removes the use of "imp"

WT-12411 Upgrade SWIG to a version that does not use package "imp"

---

src/conn/conn_layered.c
test/suite/test_layered15.py

The bug in SLS-746 was just independently fixed by SLS-649, which, among other things, ensures that WiredTiger always uses the latest version of the shared metadata table after checkpoint pickup. The problem with the previous approach was that subsequent writes to WiredTigerShared were applied to an earlier checkpoint, not the latest checkpoint, even though the checkpoint pickup code saw it.
This PR follows up by updating the test and cleaning up the comment. It also adds a FIXME for a different test failure uncovered by the fix.

SLS-746 Update node restart test to update only some tables

---

dist/s_string.ok
src/support/global.c

This reverts commit 3b2659657cd33a7106f288ca41c790d42ceec674.

Revert "WT-13781 Update __global_calibrate_ticks to take less time (#11298)"

---

dist/api_err.py
src/conn/api_strerror.c
src/docs/error-handling.dox
src/include/wiredtiger.in
test/catch2/CMakeLists.txt
test/catch2/misc_tests/test_strerror.cpp
test/suite/test_strerror01.py
test/test_coverage.md

Updated api_err.py to include functionality to generate sub-level error codes. The design is the same as the current error codes, and the subset of integer codes for the sub-level errors start from -32000

WT-13862 Update to api_err.py to include generation of sub-level error codes

---

.github/CODEOWNERS

The `.github/CODEOWNERS` file introduced in this PR coupled with a newly created [backport-approvers](https://github.com/orgs/wiredtiger/teams/backport-approvers/members) Github team will enable one member of the team to be auto-assigned as a reviewer for backport PRs in a round-robin fashion to guard the PR merge, i.e. backport PRs without approval from one of backport-approvers won't be able to merge. This is in line with the [server backport review & approval policy](https://wiki.corp.mongodb.com/display/KERNEL/Database+SERVER+Backports+Policy+and+Workflow#DatabaseSERVERBackportsPolicyandWorkflow-Approving/DecliningaBackport). 
The code change and Github team configuration have been tested using the [mongodb-8.0-test](https://github.com/wiredtiger/wiredtiger/tree/mongodb-8.0-test) …

WT-13837 Set up code owners to guard backport PRs

---

dist/api_data.py
src/config/config_def.c
src/conn/conn_api.c
src/conn/conn_open.c
src/conn/conn_reconfig.c
src/include/conf.h
src/include/conf_keys.h
src/include/extern.h
src/include/rollback_to_stable.h
src/include/wiredtiger.in
src/rollback_to_stable/rts_api.c
src/txn/txn.c
src/txn/txn_recover.c

1. Add option to configure the number of RTS workers(threads_num) in `wiredtiger_open`.
2. Add option to configure the number of RTS workers(threads_num) in `__conn_reconfigure`.
3. Apply connection level threads_num config on calling `rollback_to_stable` in `__wt_txn_global_shutdown`.
4. Apply connection level threads_num config on calling `rollback_to_stable` in `__wt_txn_recover`.
5. Apply connection level threads_num config on calling `rollback_to_stable` in `__conn_rollback_to_stable` in the following order: first, the API-level configuration; if not provided then the connection-level configuration.
(cherry picked from commit 515e31e0554c7913f39cb8a15380ce5a0a43f4f8)

WT-13592 Provide an option to control the number of RTS worker threads during startup (v8.0) (#11228)

---

dist/stat_data.py
src/btree/bt_import.c
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c
test/suite/test_import10.py

MongoDB recently added using import and `repair=true` in a rare/error path. Add a statistic to give signal about how often this call is made (because it has time/performance implications for import).
(cherry picked from commit 2f94609ca34ad34a24a4ebbbc55ba56e336b65e5)

WT-13713 Add import with repair stat (v8.0) (#11185)

---

src/conn/conn_compact.c

The background compaction thread is supposed to clean all its stats when disabled by the application or when `run_once` is configured to `true` and all the files have been parsed. The changes address the second scenario that was missing.
(cherry picked from commit 56cb49226bc2d639a8192dfbb2d088d281098b7d)

WT-13447 Reset background compaction stats after a full iteration with run_once (v8.0) (#10976)

---

src/btree/bt_compact.c

While traversing entries on an internal page, compact will decide to checkpoint the tree if it sees pages in the WT_REF_DELETED state as checkpoint will delete the underlying blocks, freeing up space for compact to reclaim. However, compact will repeatedly see pages in the WT_REF_DELETED state even after they are freed as the index in the parent page is not updated unless a split occurs.
The ref address is freed when we free the underlying blocks. Adding a check for the ref address here ensures we only proceed with the compact checkpoint (and another compact pass) if the underlying blocks have not already been freed.
(cherry picked from commit bc9d22aafcbe6446e9d6a5800ecffcf36c3b5e7d)

WT-12238 Check ref address when skipping pages in compact (v8.0) (#10538)

---

dist/s_clang_scan.diff
src/session/session_api.c
test/evergreen/run_model_workloads.sh
test/model/src/driver/kv_workload_generator.cpp
test/suite/test_truncate23.py

This PR removes the use of bounded cursors when positioning cursors for
a truncate call. Only some cursor types implement bounding so we need to
know which cursor type we're using in `__wt_session_range_truncate`, but
this information isn't available at the api layer. Ongoing work has been
split out to into WT-13232 to review if there's an alternative approach
possible.
(cherry picked from commit 85af4e3530fa881af2643f7b85504499ee8e39c4)

WT-13186 Remove bounded cursor support when positioning truncate cursors (#10825) (v8.0 backport)

---

src/btree/bt_compact.c
src/session/session_compact.c
test/suite/test_compact16.py

The compact tree walk requires the checkpoint `flush_lock` while it
walks internal pages deciding what pages to rewrite. We currently use
trylock to retrieve the lock and give up the walk if we can't get it.
This prevents us from walking the whole tree when traversing the tree
takes longer than the period between checkpoints.
This moves the handling of EBUSY returned from retrieving the flush_lock
from the session compact layer where we count the passes over a file to
the btree layer where we traverse internal pages. This has the benefit
of not abandoning the tree walk as well as reusing the interrupt check
and cache stuck check that we perform when moving between internal
pages.
(cherry picked from commit https://github.com/wiredtiger/wiredtiger/commit/430071ff616b27374d88fa2958d955bbeaee …

WT-12846 Fix how compact walk handles EBUSY from checkpoint flush_lock (v8.0) (#10929)

---

test/evergreen.yml

Recently the many-collection-test Evergreen task has had a number of failures, where the test has failed to find the mongod binary. It seems that (sometimes at least) a symlink is used to point to the actual location of the mongodb binary, and the code in evergreen.yml was not finding the binary as a result.
The solution is to add the '-L' command line option to `find` to follow symbolic links. This change also prints out the mongod path to assist with future debugging.

WT-13911 Fix configuration related issue in many-collection-test

---

src/include/connection.h
src/live_restore/live_restore.h
src/live_restore/live_restore_private.h
src/live_restore/live_restore_server.c

We could've been a bit more #modular prior when implementing the live restore server. By forward declaring the type and making it a pointer on the connection instead of the full struct we can move the struct definitions inside the `live_restore_private.h` header.

WT-13916 Hide the implementation of the live restore server from the connection

---

src/include/misc.h

Wrap parentheses to str in the `WT_SUFFIX_MATCH` MACRO so it can work when `str` is passed as `*strp`.

WT-13945 Wrap parentheses for str in the MACRO WT_SUFFIX_MATCH

---

dist/s_string.ok
src/include/misc.h
src/live_restore/live_restore_fs.c
test/catch2/CMakeLists.txt
test/catch2/live_restore/api/test_live_restore_fs_directory_list.cpp
test/catch2/live_restore/live_restore_test_env.cpp
test/catch2/live_restore/live_restore_test_env.h
test/catch2/live_restore/utils_live_restore.h

Add catch2 testing for `fs_directory_list` along with a few bug fixes revealed by testing.

WT-13943 Write catch2 tests for live restore fs_directory_list

---

src/conn/conn_compact.c

Background compaction returns `EBUSY` whenever an application interacts with it and a previous background compact command has not been processed yet. In WiredTiger, there are many reasons why an application can get EBUSY, the changes improve the error handling by logging a message whenever the application faces this scenario.

WT-13961 Add a message when background compaction returns EBUSY because of an unprocessed previous command

---

src/log/log.h
src/log/log_private.h

While working on [WT-13958](https://jira.mongodb.org/browse/WT-13958), I identified an inconsistency in the usage of the WT_MAX_LSN_STRING macro. Currently defined in log_private.h, it is being used by other modules (checkpoint & txn). This pull request has the changes to move WT_MAX_LSN_STRING to log.h to ensure proper visibility and usage across modules.

WT-13973 Fix WT_MAX_LSN_STRING macro usage across modules.

---

dist/s_typedef

While working on [WT-13958](https://jira.mongodb.org/browse/WT-13958), I observed that __wti_xxx structures defined in log_private.h were not being included in wt_internal.h. This was due to a limitation in the s_typedef function. This pull request has the changes to modify s_typedef function regular expression to include __wti_xxx structures in wt_internal.h along with __wt_xxx structures..

WT-13972 Fix typedef to include __wti_xxx typedef structs in wt_internal.h

---

test/evergreen.yml

Re-enable Mac compiles on Evergreen, but avoid uploading artefacts (which was causing the problem that stopped Mac builds), or running other tests as there are other issues to be tackled there. This PR will at least ensure that we go back to compiling on Macs and thereby avoid any Mac compiler incompatible code changes being made.
We'll get Mac tests working again, and re-enable artefact uploading, in later tickets.

WT-13977 Re-enable Mac compiles on Evergreen

---

src/checkpoint/checkpoint.h

This is dead code and therefore can be removed.

WT-13991 Remove spin lock from __wt_ckpt_session

---

src/live_restore/live_restore_fs.c

Add assert to check read never encompasses a hole, that is, a read having `start offset < hole start offset` and `end offset > hole end offset`.

WT-13890 Add check to ensure live restore read not enclose a hole

---

.github/CODEOWNERS

The `.github/CODEOWNERS` file introduced in this PR coupled with a newly created
[backport-approvers](https://github.com/orgs/wiredtiger/teams/backport-approvers/members) Github team will enable one member of the team to be auto-assigned as a reviewer for backport PRs in a round-robin fashion to guard the PR merge, i.e. backport PRs without approval from one of backport-approvers won't be able to merge. This is in line with the [server backport review & approval
policy](https://wiki.corp.mongodb.com/display/KERNEL/Database+SERVER+Backports+Policy+and+Workflow#DatabaseSERVERBackportsPolicyandWorkflow-Approving/DecliningaBackport).
(cherry picked from commit 32bae8667150a1c23f9911424793857e4d8ee3b8)

WT-13837 Set up code owners to guard backport PRs (#11340)

---

ext/page_log/palm/palm.c
ext/page_log/palm/palm_kv.c
ext/page_log/palm/palm_kv.h
lang/python/wiredtiger.i
src/block_disagg/block_disagg_ckpt.c
src/conn/conn_layered.c
src/include/connection.h
src/include/wiredtiger.in
src/txn/txn_ckpt.c
test/suite/helper_disagg.py
test/suite/test_layered15.py
test/suite/test_layered17.py

This PR adds the checkpoint timestamp to (1) PALI's {{pl_complete_checkpoint_ext}}, and (2) the disagg. struct in the connection struct. Picking up the checkpoint does NOT set the stable timestamp, as requested by a comment on the ticket.
Note that {{pl_complete_checkpoint}} will be deprecated after the server migrates to using the new variant with a different function signature. (We may also rename {{pl_complete_checkpoint_ext}} back to {{pl_complete_checkpoint}} at some later point.)

SLS-554 Add checkpoint timestamp to PALI and to checkpoint metadata

---

ext/page_log/palm/palm.c
ext/page_log/palm/palm_kv.c
ext/page_log/palm/palm_kv.h
lang/python/wiredtiger.i
src/block_disagg/block_disagg_read.c
src/block_disagg/block_disagg_write.c
src/btree/bt_page.c
src/include/btmem.h
src/include/wiredtiger.in
src/reconcile/rec_write.c
tools/wt_palm_decode.py

Set base and backlink LSNs for pages. I just went to all the places that use or set `base_checkpoint_id` and `backling_checkpoint_id` and updated those.

SLS-913 Set base and backlink checkpoint LSNs during page write

---

test/format/format.h
test/format/format_timestamp.c
test/format/ops.c
test/format/snap.c

To add the basic capability to check ignore_prepare to test format.
This change sets the ignore_prepare setting to transactions randomly and if ignore_prepare is set will ensure only reads are performed as per the transaction semantics.
Changes:
1. function name change to reflect the function logic.
2. Occasionally set ignore_prepare and ensure the transaction will perform only read operations as write operations are forbidden when ignore_prepare is set.

WT-11253 Add basic ignore_prepare to test format.

---

test/suite/test_autoclose.py

The autoclose.py test raises a `TypeError` on MacOS after SWIG has been updated to 4.3, update the expected exceptions.

WT-13893 Convert RuntimeError to TypeError in test_autclose.py for macOS

---

test/suite/test_autoclose.py

Reverts wiredtiger/wiredtiger#11429
Reverting, I found more tests failing for the same reason.

Revert "WT-13893 Convert RuntimeError to TypeError in test_autclose.py for macOS"

---

test/suite/test_autoclose.py
test/suite/test_cursor_compare.py

Same as #11429:
The `autoclose.py` and `test_cursor_compare.py` tests raise a TypeError on MacOS after SWIG has been updated to 4.3 instead of the expected RuneTimeError, update accordingly.

WT-13893 Convert RuntimeError to TypeError in python tests for macOS

---

test/evergreen.yml

The changes enable the MacOS tests on Evergreen.

WT-14007 Update Evergreen to trigger the MacOS tests again

---

dist/modularity/init.sh

For some reason, pip install for layercparse sticks to the current version, so new commits don’t trigger a fresh installation of layercparse. To address this, we need to forcefully reinstall layercparse whenever newer commits are made to the repo. This can be achieved by appending --force-reinstall to the pip install command.

WT-14008 Force reinstall layercparse when using modstat

---

test/evergreen.yml
test/suite/helper_disagg.py
test/suite/hook_disagg.py
test/suite/test_layered01.py
test/suite/test_layered02.py
test/suite/test_layered03.py
test/suite/test_layered04.py
test/suite/test_layered05.py
test/suite/test_layered06.py
test/suite/test_layered07.py
test/suite/test_layered08.py
test/suite/test_layered09.py
test/suite/test_layered10.py
test/suite/test_layered11.py
test/suite/test_layered12.py
test/suite/test_layered13.py
test/suite/test_layered14.py
test/suite/test_layered15.py
test/suite/test_layered16.py
test/suite/test_layered17.py
test/suite/wttest.py

- Created a disagg helper function that ignores the RTS warning
- Changed the hook for wiredtiger_open to call the new helper function.
- Make a minimal disaggregated hook test part of evergreen PR testing.
- Added a class decorator for disagg-only tests that call the new helper.
- Changed all layered tests to use the class decorator to ignore RTS warning.

SLS-984 Ignore RTS message for disaggregated hook.

---

src/block_disagg/block_disagg_read.c
src/conn/conn_layered.c

Derive the value of delta_count from the number of returned results if it's not set.
I did not yet deprecate the delta_count field; this should be done after the Server stops using it.

SLS-1005 Derive delta_count from result_count after calling plh_get

---

ext/page_log/palm/palm.c
src/block_disagg/block_disagg_read.c
tools/wt_palm_decode.py

Improve the consistency of output by using base 10 numbers for page IDs, checkpoint IDs, etc., and hex numbers for checksums.

SLS-1004 Use dec output for page IDs, etc., and hex for checksums for consistency

---

src/evict/evict_lru.c
src/evict/evict_page.c

In disaggregated storage we want to keep recently reconciled pages in cache more aggressively, since there will usually be a delay after the initial write before they are available to be read back in.

SLS-895 Use scrub eviction more often

---

dist/s_all
dist/s_string.ok
dist/s_void
ext/page_log/palm/palm.c
ext/page_log/palm/palm_kv.c
src/block_cache/block_io.c
src/block_disagg/block_disagg_ckpt.c
src/block_disagg/block_disagg_read.c
src/block_disagg/block_disagg_write.c
src/btree/bt_handle.c
src/btree/bt_import.c
src/conn/conn_layered.c
src/cursor/cur_layered.c
src/cursor/cur_version.c
src/include/block.h
src/include/connection.h
src/reconcile/rec_write.c
src/txn/txn_recover.c

The s_void and s_string scripts have been disabled against the disaggregated storage branch - fix accumulated errors and enable them again
ps: I tagged the branch name with SLS-1010, but the right ticket number is SLS-1011

SLS-1011 Enable automated spell checking in WiredTiger disaggregated branch

---

lang/python/wiredtiger.i

SWIG 4.3.0 version has introduced a couple of incompatibilties and WiredTiger is affected with the SWIG_Python_AppendOutput API.
Change the code to use SWIG_AppendOutput API that internally calls the SWIG_Python_AppendOutput API with the required parameters.
(cherry picked from commit eb9b4dcafba665d0cd78af6382b47ff595d741da)

WT-13667 Support compiling WiredTiger with SWIG 4.3.0 version (8.0)

---

src/schema/schema_create.c

My speculative fix from earlier today didn't preserve the config ordering like this change does.

SLS-1023 Add empty config entry to prevent user config getting blatted

---

lang/python/wiredtiger.i

1ac6f25bff
Co-authored-by: Etienne Petrel <77254506+etienneptl@users.noreply.github.com>
(cherry picked from commit fb4019c82e9410791dadf8eb3ca4b86463b47050)

WT-13667 Support compiling WiredTiger with SWIG 4.3.0 version (v6.0 backport) (#11456)

---

ext/page_log/palm/palm.c
src/cursor/cur_layered.c
src/schema/schema_truncate.c
src/support/err.c
test/suite/test_truncate01.py
test/suite/test_truncate02.py

I make test_truncate01 and test_truncate02 to pass. So it can work for basic truncate cases. It currently doesn't support fast truncate for layered table. I'll leave the task to make layered table work for other truncate tests in another ticket. I tried it for test_truncate03 but it failed on layered data store not supporting verify.

SLS-932 Implement truncate for layered table

---

src/live_restore/live_restore_server.c

A small fix to appease Coverity. This code path is single threaded but we should take the lock to be consistent across all accesses to the live restore `work_queue`

WT-14017 Take the queue_lock in live restore's __insert_queue_item

---

test/evergreen.yml

Fully re-enable Mac testing on the Evergreen waterfall, including using artefact uploads again, now that DNS issues preventing uploads have been addressed in the relevant DEVPROD ticket. 
Using artefact uploads again makes a small, but still useful, speedup to the overall test process as less compiles are required.

WT-13951 - Fully re-enable Mac testing on the Evergreen waterfall

---

test/suite/test_eviction02.py

The stats value can be stale, increase the buffer to take this into account.

WT-13926 Increase the margin of error in test_evict02.py for expected stats values

---

dist/api_data.py
dist/stat_data.py
src/evict/evict_conn.c
src/evict/evict_inline.h
src/evict/evict_lru.c
src/include/stat.h
src/include/wiredtiger.in
src/session/session_api.c
src/support/stat.c
test/catch2/misc_tests/test_session_config.cpp
test/csuite/CMakeLists.txt
test/csuite/wt13867_interrupt_eviction_handler/main.c

Add callback for user to abort optional eviction.
The `handle_general` callback is called with the event type `WT_EVENT_EVICTION` whenever a user thread is about to evict a page. If the callback returns an error (nonzero), the eviction helper loop will break as soon as the current page eviction is completed. We never interrupt a page eviction midway but can interrupt the loop that iterates through pages for eviction.
This PR also adds new statistics alongside the existing connection-level stats (`application_cache_ops`, `application_cache_time`) and session-level stats (`cache_time`). The new stats differentiate between "idle" and "busy" modes, which can also be understood as "optional" and "mandatory" eviction:
- Idle/Optional Eviction: When application threads assist eviction workers as …

WT-13867 Add callback for user to abort optional eviction

---

src/include/schema.h

Add a description for how the `WT_WITH_LOCK_*` macros behave. This will save future developers time when investigating false positive Coverity warnings about concurrent modification.

WT-14023 Document the behaviour of WT_WITH_LOCK_WAIT

---

src/cursor/cur_std.c

9d1b71861
(cherry picked from commit cd0aeb5c8ea1fff19110f8e8f942eda218707b72)

WT-13091 Make cursor_copy debug mode more precise (v6.0 backport) (#10848)

---

test/suite/test_autoclose.py
test/suite/test_cursor_compare.py

Same as #11429:
The `autoclose.py` and `test_cursor_compare.py` tests raise a TypeError on MacOS after SWIG has been updated to 4.3 instead of the expected RuneTimeError, update accordingly.
(cherry picked from commit e044b5a6119a91168fedb1a699e49a504a69f3c3)

WT-13893 Convert RuntimeError to TypeError in python tests for macOS (#11434)

---

test/model/src/driver/kv_workload_generator.cpp

Disable testing column stores in test/model, as they are not necessary for disaggregated mongod. The test consistently fails with SLS-1096. This would remove at least some noise from Evergeen's waterfall.

SLS-1097 Disable column store testing in test/model

---

test/format/backup.c
test/utility/backup.c
test/utility/test_util.h

Currently test/format verifies a backup periodically, and does so directly on the BACKUP directory. Change it to use a separate check directory. This changes several things:
1. It lays the foundation for different directory creation (i.e. live restore). 
2. It also makes the need for the BACKUP.copy directory obsolete as the BACKUP directory is never recovered.
3. It means we can check the backup on every iteration instead of periodically.

WT-12505 Have format use a separate backup check directory.

---

src/live_restore/live_restore_fs.c
src/live_restore/live_restore_private.h
src/live_restore/live_restore_server.c
test/catch2/live_restore/live_restore_test_env.cpp
test/suite/test_live_restore02.py

Tombstone is an overloaded term and we are moving away from it by referring to these files as stop files. As in "stop! don't look in the source for this file".

WT-14048 Rename tombstone to stop file

---

src/include/extern.h
src/session/session_api.c
test/unittest/CMakeLists.txt
test/unittest/tests/test_session_config.cpp

1e1d3fa085
---------
Co-authored-by: Luke Pearson <luke.pearson@mongodb.com>
(cherry picked from commit 357fd20c8ba2be720e2af5cfef80758bc8273112)

WT-13377 Reconfiguring a session with cache_max_wait_ms does not accept a value of zero (v7.0 backport) (#11177)

---

src/session/session_helper.c
test/catch2/sub_level_error/unit/test_sub_level_error_session_set_last_error.cpp

`__wt_session_set_last_error` assumes that the session is non-NULL but Coverity has found a handful of cases where this isn't true. An extra check has been added so that the function returns `0` if a null session is passed in.

WT-14019 Add a check for a NULL session in __wt_session_set_last_error

---

test/format/backup.c
test/utility/backup.c
test/utility/test_util.h

Change after revert. All the earlier changes plus the fix to remove all uses of BACKUP.copy.

WT-12505 format backup

---

test/ctest_helpers.cmake
test/evergreen.yml
test/model/src/include/model/kv_database.h
test/model/test/CMakeLists.txt
test/model/tools/CMakeLists.txt

Fix ASAN issues in test/model and enable the relevant tasks in Evergreen.
Fixed ASAN issues:
* Include the test_util library only once. It used to be linked twice, once through the test's "common" test utility library, and once through create_test_executable.
* Fix a memory leak in the model (the details are described in the comment).

WT-14053 Enable test/model in ASAN

---

src/evict/evict_lru.c

This change mitigates BF-35698 where WT-13790 did not completely hide all changes behind the feature flag.
This PR completes that work by flipping the two "goto"s back in place if the new behavior is disabled.
The initial change is done in WT-12644.

WT-14073 Fix the implementation of feature flag for "using soft pointers in eviction server".

---

dist/api_data.py
dist/s_all
dist/s_funcs.list
src/block_disagg/block_disagg_open.c
src/btree/bt_handle.c
src/include/extern.h
src/meta/meta_ckpt.c

The WiredTiger disaggregated storage branch has disabled a few of our regular code cleanliness checks to expedite development. It's time to re-enable those checks.

SLS-1144 Re-enable code cleanliness checks in WiredTiger

---

dist/api_err.py
dist/s_string.ok
src/conn/api_strerror.c
src/docs/error-handling.dox
src/include/schema.h
src/include/wiredtiger.in
test/catch2/sub_level_error/api/test_sub_level_error_strerror.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_drop_conflict.cpp
test/suite/test_error_info03.py
test/suite/test_strerror01.py

This ticket involves reproducing one of the EBUSY drop workflows and making sure that the get_last_error API works as appropriate. The idea is that the API should be able to provide more information on why an EBUSY has been returned from the drop() call. 
The following scenarios have been added, reproduced, handled using `__wt_session_set_last_error`, and tested:
- `EBUSY`, `WT_CONFLICT_CHECKPOINT_LOCK`, another thread has the schema lock

WT-14066 Set sub-level error code and message with python tests for drop EBUSY workflows (checkpoint lock conflict)

---

src/live_restore/live_restore_server.c
src/support/thread_group.c

Here is the change to handle EBUSY. The branch for 14005 running with this change is passing the failing CONFIG.

WT-14069 Handle live restore worker getting EBUSY.

---

src/session/session_helper.c
src/txn/txn.c

Added last record error info to transaction and session verbose dumps, including error code, sub-level error code, and error message. Note that for sessions with an ongoing transaction, the last error info will be the same for the session dump and transaction dump.

WT-14076 Add last error info to verbose dumps

---

test/compatibility/compatibility_test_for_releases.sh

Luke and Ravi - Please review carefully these changes to the compatibility script. How do I test this script change since compatibility tests don't normally run with PR tests? Also how do I test it since backups may or may not randomly get configured in the format run.
My local testing was that I pulled the code out into a small local script:
```
#!/usr/bin/env bash
dir2=./RUNDIR
if [ -e $dir2/BACKUP ]; then
echo "Copying backup directory for older releases"
cp -rp $dir2/BACKUP $dir2/BACKUP.copy
fi
```
and ran the compatibility reproducer I've been using and it succeeded.

WT-14067 Script changes for backup directory and compatibility.

---

src/support/err.c

Minor change to zero pad time. It now looks like this:
```
[1738862523:095470][11633:0x1f6858840], file:WiredTiger.wt, WT_CURSOR.reset: [WT_VERB_API][DEBUG_1]: CALL: WT_CURSOR:reset
[1738862523:100489][11633:0x1f6858840], file:WiredTiger.wt, metadata-ckpt: [WT_VERB_WRITE][DEBUG_2]: write: WT_HOME/WiredTiger.turtle.set, fd=5, offset=0, len=1411
```

WT-14095 Zero pad the usecs in messages.

---

src/log/log_private.h
src/log/log_slot.c
test/evergreen.yml
test/evergreen/tsan_warnings.supp
test/suite/test_checkpoint33.py

We added TSan tests at the end of SPM-3221 but didn't turn them on in waterfall. This ticket fixes some failures in the patch only `TSan (No Throw)` variant and enables `examples-c-tsan` in PR testing.

WT-14097 Add examples-c-tsan to PR testing

---

src/session/session_dhandle.c
test/evergreen.yml
test/suite/hook_disagg.fail
tools/pytest_parallel

Includes a shell script to run python test files in parallel
Includes a small fix that allows us to enable several more tests:
- when looking up a dhandle in disagg via `__wt_session_get_dhandle`, the base config is not always used.
If `force` is not specified, the return from the config lookup is WT_NOTFOUND.  The way the error check is
written, we try to deref a NULL string on WT_NOTFOUND.

SLS-1041 Expand disagg hook coverage

---

src/include/api.h
src/schema/schema_drop.c

In [WT-14030](https://jira.mongodb.org/browse/WT-14030), the `__wt_session_set_last_error function` was updated to no longer overwrite errors that had been stored in the `err_info` struct at a previous point in the current API call.
As a consequence there are several extra checks that can be and now have been safely removed, since they aim to accomplish the same thing, mostly located in `schema_drop.c`.

WT-14099 Remove extra checks before recording error info

---

src/checkpoint/checkpoint.h
src/checkpoint/checkpoint_txn.c
src/cursor/cur_file.c
src/session/session_dhandle.c

The changes introduce a new function `__wt_checkpoint_snapshot_clear` to reset a checkpoint snapshot.

WT-14105 Create function to reset checkpoint snapshot

---

bench/wtperf/runners/500m-btree-50r50u-live-restore-no-server.wtperf
bench/wtperf/runners/500m-btree-50r50u-live-restore.wtperf
test/evergreen.yml

This adds two new perf tests for live restore:
1. Uses live restore with background migration
2. Uses live restore but disables all background migration threads
The tests are currently labelled as `patch_only` and should be enabled in the mainline patches once the project implementation is complete and perf results are stable.
Please see the Jira comments for preliminary results.

WT-14063 Implement a preliminary live restore performance test

---

src/live_restore/live_restore_fs.c

This PR removes the logic of live restore file holes when copying logs across during recovery, it adds a static copy function in live_restore_fs that reads all logs and copy them from source to destination.

WT-14078 Don't depend on hole logic to copy log files across

---

test/evergreen.yml

We are now using Bazel when compiling MongoDB in Evergreen.

WT-14120 Use bazel to compile MongoDB in Evergreen

---

src/block_disagg/block_disagg_ckpt.c
test/suite/test_layered15.py
test/suite/test_layered17.py
test/suite/test_layered25.py

Include relevant metadata when checkpointing a table with "type=layered." Add this table type to a few tests.

SLS-1274 Support tables with type=layered

---

src/conn/conn_api.c
src/live_restore/live_restore.h
src/live_restore/live_restore_fs.c
src/live_restore/live_restore_private.h
src/log/log.c
src/log/log.h
src/log/log_mgr.c
src/log/log_private.h
test/catch2/live_restore/api/test_live_restore_fh_extent_import_export.cpp
test/catch2/live_restore/utils_live_restore.cpp

The log copy stage was added because tracking extents on log files and similar things seemed ugly, and for a while that was valid. During the development of the bitmap change it became clear that a simpler path existed: treat all "regular", i.e. log files and non b-tree files as copy-on-open. That way only b-trees have hole lists that need tracking.
Furthermore to avoid wondering the what the impact of a crash during copy of these files would be the copy has been made atomic by doing a copy followed by rename.

WT-14137 Atomically copy "regular" files on open and remove the log copy stage of live restore.

---

dist/api_err.py
src/conn/api_strerror.c
src/docs/error-handling.dox
src/include/wiredtiger.in
src/session/session_api.c
test/catch2/CMakeLists.txt
test/catch2/sub_level_error/api/test_sub_level_error_strerror.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_drop_conflict.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_live_restore_conflict.cpp
test/suite/test_strerror01.py

This PR is to add logic to ensure live restore is not running when open a backup cursor.

WT-13875 Ensure backups cannot be taken for the duration of a live restore

---

dist/api_data.py
src/include/wiredtiger.in

Fix the `WT_SESSION::create` incorrectly stated that the configuration was validated upon recreating an object with an existing URI. This is outdated and the current implementation silently fails in this situtation.

WT-14150 Fix WT_SESSION::create documentation

---

test/csuite/schema_abort/main.c

This pull request has the changes to fix a bug in the test_schema_abort where two threads incorrectly compares last_oldest_timestamp with current_oldest_timestamp and proceeds to call the set_timestamp API if the difference exceeds 100. However, this difference can sometimes be negative, leading to unintended calls to the set_timestamp API and triggering the observed failure.

WT-13736 Fix test_schema_abort generating out of order oldest timestamp

---

src/btree/bt_sync_obsolete.c

The changes use `conn->cc_cleanup.interval` instead of a hardcoded value of 5 seconds to wake up the obsolete cleanup thread.

WT-14132 Update value to wake up the obsolete cleanup thread

---

src/docs/arch-block.dox
src/docs/arch-checkpoint.dox
src/docs/arch-index.dox

Updating the checkpoint architecture guide with:
1. More stages that checkpoint goes through (previously undocumented in this guide)
2. Extra context
3. Improved layout
4. Links to other docs
5. Updated the diagram on the index page to include the checkpoint subsystem.

WT-13728 Update checkpoint architecture guide

---

cmake/strict/clang_strict.cmake
cmake/strict/strict_flags_helpers.cmake

The default switch statement warning is popping up after we test WiredTiger on the v5 toolchain, this PR adds a flag to ignore the error and we have [WT-14128](https://jira.mongodb.org/browse/WT-14128) to add default statements for our switch cases in the future.

WT-14121 Ignore switch statement (lack of) default warning

---

src/checkpoint/checkpoint_txn.c

[WT-14020](https://jira.mongodb.org/browse/WT-14020): Minor change to remove the unused initialisation of `hs_dhandle = NULL` in `/src/checkpoint/checkpoint_txn.c`. Moved the declaration of `hs_dhandle` to where it is first used in the function.

WT-14020 removed unusued hs_dhandle value

---

test/evergreen.yml

Set the priority of our macOS compile task to 5 by default. 
This task often takes an hour to be scheduled, exceeding our target PR testing time of 30 minutes.
Setting priorities like this should be done very rarely, and only in cases where we know the change won't have negative impacts on other projects getting their tasks scheduled. Since compilation finishes in 2 minutes and potentially improves testing time by 30 minutes this change is considered acceptable.

WT-13994 Reduce PR testing duration

---

test/evergreen.yml

When migrating from mongo's old scons buildscripts to bazel the optimization level changed, causing large drops in our many-collections performance tests. Compile mongo using the optimized profile to return us to our original performance numbers.

WT-14172 Compile many-collections-test with --config=opt

---

test/suite/hook_disagg.fail

SLS-1364 Don't run tests that use unsupported stats with disagg hook.

---

test/evergreen/tcmalloc_install_or_build.sh

Since bazel 8.0, they have disabled using the workspace file by default follow here:
```
WARNING: --enable_bzlmod is set, but no MODULE.bazel file was found at the workspace root. Bazel will create an empty MODULE.bazel file. Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel. For more details, please refer to https://github.com/bazelbuild/bazel/issues/18958.
ERROR: error loading package 'tcmalloc': Unable to find package for @@[unknown repo 'rules_fuzzing' requested from @@]//fuzzing:cc_defs.bzl: The repository '@@[unknown repo 'rules_fuzzing' requested from @@]' could not be resolved: No repository visible as '@rules_fuzzing' from main repository. Was the repository introduced in WORKSPACE? The WORKSPACE file is disabled by default in Bazel 8 (late 2024) …
```

WT-14149 Specify bazel version 7.5.0 when building TCMalloc

---

dist/s_string.ok
src/include/txn_inline.h
src/include/wiredtiger.in
src/session/session_api.c
src/txn/txn.c
test/suite/test_prepare02.py

Allow reconfiguring prepared transactions.
This change allows to call `session->reconfigure` on prepared transactions.
The reason why it was not allowed is to allow to only call `commit` or `rollback` when the transaction is prepared.
This change allows to adjust configuration before doing that to change some vital options like `cache_max_wait_ms`. Reconfiguring transaction-related settings when the transaction is started is still prohibited.
Change details:
1. The "`transactional error logged after transaction was prepared, failing the system`" check is moved from `__wt_txn_err_set()` to `__session_rollback_transaction()` since "__wt_txn_err_set" is also called from other places.
2. `WT_ERR(__wt_txn_context_check(session, false))` from `__session_reconfigure()` moved to …

WT-14156 Allow reconfiguring prepared transactions

---

src/docs/command-line.dox
src/live_restore/live_restore.h
src/live_restore/live_restore_fs.c
src/live_restore/live_restore_private.h
src/meta/meta_ckpt.c
src/utilities/util_main.c
test/suite/test_live_restore02.py
test/suite/test_live_restore04.py

Handle a scenario in live restore that results in a descriptor read error, or potentially other block checksum errors.

WT-14079 Treat nbits -1 as a file completion state & WT-14044 Support the WT util running on a partially live restored database.

---

src/reconcile/rec_write.c

[WT-13647](https://jira.mongodb.org/browse/WT-13647) Removed the `compressed_image` variable to the `__rec_split_write` function, as it was always NULL.

WT-13647 remove compressed_image value to rec_split_write

---

test/compatibility/compatibility_test_for_releases.sh

Determine if the release needs copying in a generic way. Remove BACKUP.copy first and then recopy BACKUP in newer releases for older releases.

WT-14186 Update compat script to remove BACKUP.copy before copying again.

---

test/format/ops.c

The changes update test/format to use up to 10 threads when performing RTS.

WT-14163 Explicitly set the number of RTS threads in test/format

---

dist/s_void
lang/python/wiredtiger.i
src/cursor/cur_version.c
src/evict/evict_lru.c
src/include/extern.h
src/include/txn.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/session/session_api.c
src/txn/txn.c
test/evergreen.yml
test/format/snap.c
test/suite/test_error_info02.py
test/suite/test_error_info04.py
test/suite/test_txn27.py

This reverts commit 48fa5fc2caadca131d7e62314da659a572ff33ec. It is an anti-pattern for us to use MongoDB forks within our codebase.

Revert "WT-13948 Deprecate rollback_reason API  (#11628)"

---

test/suite/hook_disagg.fail
test/suite/test_compact04.py
test/suite/test_prepare28.py
test/suite/test_truncate19.py

LABS-1188 disabled several python tests that were failing on the disagg branch. These were non-disagg tests, run on WT without any disagg capabilities enabled. 
We have not deliberately fixed these tests, but they are now passing consistently in my testing. So I'm re-enabling them.
A side effect of re-enabling these tests is that they are now eligible to run with the disagg hook. Since we don't support prepared transactions, the `prepared28` test had to be explicitly excluded from disagg hook testing by adding it to `hook_disagg.fail`.

SLS-414 Re-enable skipped WT python tests for disaggregated storage

---

dist/s_void
src/live_restore/live_restore_fs.c
src/live_restore/live_restore_private.h
src/live_restore/live_restore_server.c

By dirtying the b-tree we ensure our metadata updates get written out in a timely fashion. This will mean that at most we'd lose about a checkpoint duration worth of background data transfer on crash.

WT-14187 Periodically set the b-tree as modified while restoring a file

---

test/evergreen.yml

Removes the patch only flag from the live restore perf test evergreen tasks.

WT-14209 Run live restore perf tests in all commits

---

test/checkpoint/CMakeLists.txt

This pull request restores a scenario that was previously removed in [SERVER-93028](https://jira.mongodb.org/browse/SERVER-93028)

WT-13349 Improve testing for history store crash recovery

---

src/os_posix/os_fs.c

The  `__wt_log_printf` in  `__posix_fs_rename` was the culprit of all the deadlocks seen in evergreen. I've removed this and the other calls to `__wt_log_printf` in `os_fs.c` as they create similar dependencies. Let me know if you think we should keep the others in `open_file` and `remove`. Alternatively, if we want to keep all of them, we can add
```
if (!F_ISSET(conn, WT_CONN_LIVE_RESTORE_FS))
```
and only print them if we're not in live restore mode.
The deadlock does not reproduce with these removed.

WT-14199 Remove log prints in filesystem calls

---

test/csuite/schema_abort/main.c

Bulk operations should not be used inside transactions. Update schema_abort to avoid trying bulk operations when transactions are enabled.

WT-11271 Don't use transactions with bulk operations in schema_abort test

---

test/evergreen.yml

We are seeing a lot of failures on zSeries machines due to toolchain config issues (see [WT-14194](https://jira.mongodb.org/browse/WT-14194)).
This change uses activate: false to disable the zSeries tasks until [WT-14194](https://jira.mongodb.org/browse/WT-14194) is fixed. Using activate: false means that the tasks are still visible in Evergreen and can be manually launched as required, giving more flexibility compared to commenting them out.

WT-14205 - Disable zSeries tasks (with activate: false) temporarily

---

test/evergreen.yml

Our memory-model test initially had issues when running with the v5 toolchain installation script. Now that the v5 toolchain is pre-installed on our ARM machines, the test is passing successfully. To simplify potential future rollbacks—if we ever need to revert to v4—this PR keeps the change isolated.

WT-14109 Make memory-model-test compatible with the v5 toolchain

---

dist/stat_data.py
src/btree/bt_delete.c
src/btree/bt_page.c
src/btree/bt_split.c
src/btree/row_key.c
src/btree/row_modify.c
src/include/btmem.h
src/include/btree_inline.h
src/include/extern.h
src/include/serial_inline.h
src/include/stat.h
src/include/txn_inline.h
src/include/wiredtiger.in
src/reconcile/rec_track.c
src/reconcile/rec_visibility.c
src/session/session_api.c
src/support/stat.c
src/txn/txn.c
test/suite/test_txn_uncommitted.py

This change adds a counter for total uncommitted updates size for better detection of situations where uncommitted transactions take too much cache space.

WT-14191 Add counter to track total uncommitted updates size

---

test/evergreen.yml
test/evergreen_develop.yml

During the work of [WT-14122](https://jira.mongodb.org/browse/WT-14122), we have found that armv9 machines do not have lz4, snappy compressors installed on the machine. Additionally due to [WT-14149](https://jira.mongodb.org/browse/WT-14149) we have found that TCMalloc fails to build due the mongo-fork repo being outdated. Since then we have been able to get compressors and TCMalloc working on the machine.
This ticket will be enabling the compressor related tests and enabling TCMalloc on all machines.

WT-14152 Enable compressor tests and TCMalloc on ARMV9 machines

---

src/history/hs_rec.c
src/reconcile/rec_write.c

Ensure that the history cursor is positioned on the correct btree in __hs_delete_record.

SLS-1487 Fix assertion failure coming from __hs_delete_record

---

test/evergreen.yml

This pull request has the changes to remove the redundant "csuite smoke test" function from evegreen.yml

WT-14210 Remove redundant csuite smoke test function from evegreen.yml

---

test/packing/packing-test.c

Make the types consistent in the printf() parameters. By changing 0xff to 0xffu it becomes an unsigned int which, when bit-anded with an unsigned char, gives an unsigned int which is what the printf format string is expecting.

WT-14193 Fix type error in printf() in packing-test.c when using the v5 toolchain.

---

cmake/strict/clang_strict.cmake

The v5 toolchain enables pre-c11-compact by default and results in a couple of failures when WT runs with v5, this PR adds an ignore flag for these errors.

WT-14192 Ignore pre-c11-compat errors

---

src/btree/bt_split.c
src/include/btmem.h
src/include/reconcile.h
src/reconcile/rec_write.c

This PR disallows building deltas whenever the pindex is updated for an internal page. This typically occurs during eviction, where we might split a page into multiple pages or perform reverse splits when entries are deleted, requiring an update to the parent page's pindex.
The changes account for all relevant scenarios, including split_multi, split_insert, split_internal, and reverse_split. We simply detect whether the page index was updated and, during reconciliation, skip building deltas for such pages. 
Once reconciliation is complete, we clear the flag in __rec_write_page_status.

SLS-1434 Skip building internal page deltas for splits

---

src/live_restore/live_restore_fs.c
test/catch2/live_restore/api/test_live_restore_fs_open_file.cpp

This change addresses both WT-13971 and WT-13823. 
As we're only opening and migrating file WiredTiger owns we can keep the logic simple. WiredTiger never creates directories so any directory we open must already exist, and files use the default permissions as set in the posix or windows layer which live restore calls into.

WT-13971 Return ENOENT when live restore attempts to open a directory that doesn't exist in the destination

---

src/evict/evict_conn.c
test/suite/test_config12.py

When trying to check the `eviction_updates_trigger` for invalid configuration, the log incorrectly states we set the default value to half of the `eviction_updates_trigger` value instead of the `eviction_dirty_trigger`. Also, found a similar error in the same function in`evict_conn.c`, the error message should say setting to 50% of `eviction_dirty_target` not `eviction_updates_target`. 
Solution: fixed inconsistencies in `__evict_validate_config` config log to reflect the correct metrics and fixed pattern matching error in `test_config12.py`.

WT-14147 Fix the eviction updates trigger config log to reflect correct metric

---

test/evergreen.yml

We've identified an error where live restore reads all-zero pages in WT-14242. This ticket disables the live restore perf tests until we resolve the issue.

WT-14250 Disable live restore perf tests

---

test/evergreen.yml

Re-enable the zSeries tasks by removing 'activate: false' so they run by default in post-merge testing, effectively reversing the changes in [WT-14194](https://jira.mongodb.org/browse/WT-14194) that temporarily disabled the tests, now that the toolchain config issues have been fixed.

WT-14244 Re-enable the zSeries tasks by removing 'activate: false'

---

test/suite/hook_disagg.fail

SLS-1516 Disable test_rollback_to_stable44.py for PR testing

---

src/docs/arch-eviction.dox

Update the `arch-eviction.dox` to more accurately describe the conditions when pages are added to the urgent eviction queue. Pages will only go into the urgent queue if the operation has disabled eviction or splitting, or if the session is preventing reconciliation. Otherwise the page can be evicted by the application thread itself.

WT-14111 Correct the documentation for forced eviction behaviour

---

test/format/alter.c
test/format/backup.c
test/format/bulk.c
test/format/checkpoint.c

Printing the value of `ret` in several places in `test/format` where we write stop messages to the trace database. This would provide helpful info to developers.

WT-13787 Print return value in test/format trace stop messages

---

test/checkpoint/CMakeLists.txt
test/evergreen.yml

We recently added two new tests to checkpoint-test, but their runtimes cause the task to exceed our 25 minute runtime target for PR testing. To fix this move the new tests into a checkpoint-test-long-running task that doesn't run for PR testing.

WT-14255 Remove long running checkpoint tests from PR testing

---

src/conn/conn_reconfig.c
src/include/extern.h
src/live_restore/live_restore.h
src/live_restore/live_restore_state.c
src/meta/meta_table.c
src/meta/meta_turtle.c

This change adds two functions to intercept calls to update or rewrite the turtle file. Ensuring that the live restore state file lock is held before the turtle lock is taken. The consistent order of claiming the two locks removes the possibility of a dead lock when one thread set the live restore at the same time another thread is updating the turtle file.

WT-14243 Fix deadlock between the turtle lock and the live restore state lock

---

src/live_restore/live_restore_fs.c

Remove the set but not used `temp_path` variable from `live_restore_fs.c`to improve code quality.

WT-14060 Coverity analysis defect: remove unused variable in live restore

---

src/cursor/cur_layered.c

The exactp argument in WT_CURSOR::search_near is optional, but using NULL in layered tables causes a crash.

SLS-1542 Fix SIGSEGV in __clayered_search_near

---

src/btree/bt_delete.c
test/suite/test_bug035.py

The problem described in the ticket is that, since the HS is non-transactional, page_del->committed is not set. This prevents the deletion of the page, causing reconciliation to retain the original version. By treating HS pages that are fast-truncated during selective backup as globally visible (even though they are non-globally visible) and setting page_del to null, we eliminate this issue. This allows us to remove the pages without checking visibility information, which is acceptable because the HS is non-transactional.
(cherry picked from commit 472b1d8fd675b1453eecf07642dd88bbf2ed79fa)

WT-13716 Prevent retention of fast truncated history store pages (v8.0)(#11190)

---

src/docs/error-handling.dox
src/include/api.h
src/include/extern.h
src/session/session_api.c
src/session/session_helper.c
test/catch2/sub_level_error/api/test_sub_level_error_session_get_last_error.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_compact.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_drop_conflict.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_rollback.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_session_set_last_error.cpp
test/suite/test_error_info01.py

As part of [PM-3810](https://jira.mongodb.org/browse/SPM-3810) and [WT-13866](https://jira.mongodb.org/browse/WT-13866), we have introduced a performance regression. The performance regression is due to the number of calls calling set last error within each session API call. Currently, we call the set_last_error function to return the session error info structure to the default state before performing the actual session API work. This was done because of the need to have error state clean before we start tracking errors within WiredTiger.
**Solution**
The solution to this problem is to only perform set_last_error if the previous session error info contains a fail error code. In this case it means that we do not need to perform unnecessary resetting to default and only set it back to …

WT-14195 Reduce set_last_error calls in API_INIT

---

dist/filelist
dist/filelist.bzl
dist/s_string.ok
src/block/block_open.c
src/conn/conn_api.c
src/conn/conn_open.c
src/conn/conn_reconfig.c
src/cursor/cur_backup.c
src/live_restore/live_restore_fs.c
src/meta/meta_ckpt.c
src/meta/meta_table.c
src/meta/meta_turtle.c

Previously we needed to #ifdef out live restore code for Windows as live restore used posix-specific libraries such as ioctl fiemap. Now that we persist live restore data to the metadata and turtle files this is no longer necessary and we can clean up the code.
This change only removes pre-processor #ifdefs, live restore is still not supported on Windows.

WT-14257 Remove Windows ifdefs in the live restore code

---

test/evergreen.yml

This ticket adds new compile tasks for currently installed gcc and g++ binaries on the ubuntu machine.

WT-14102 Add Evergreen tests for currently supported GCC and Clang versions 

---

src/evict/evict_lru.c
src/include/misc.h

We currently do check before decrementing `evict_aggressive_score` to ensure it won't drop below zero. However the check then decrement operations are not implemented atomically which causes race condition. This PR is to apply the compare-and-swap operation to the code to avoid the value drops to -1(which is `int_max` as `evict_aggressive_score` is an unsigned int).
(cherry picked from commit 4a0a6109f05468cdfb1a7964e98bcfb4c351aa88)

WT-13283 Fix the cache aggressive mode not to show the garbage value (8.0) (#11622)

---

src/live_restore/live_restore_fs.c
src/live_restore/live_restore_server.c

This change avoids locking once the migration is complete, effectively for any file that is "complete" the performance will be identical to that of the regular WT.

WT-14229 Fast path reads and writes once the destination is complete

---

src/btree/row_key.c
src/include/api.h

Code inside a WT_ASSERT will only run when we compile in HAVE_DIAGNOSTIC mode. In release mode it's entirely compiled out. This carries a risk when the code inside the assert has some side effect, for example setting a field in a struct.
This ticket removes the few cases where we do this. They're already inside of an #ifdef HAVE_DIAGNOSTIC so there's no functional impact, but it protects against the possibility of ever using this code outside of HAVE_DIAGNOSTIC.

WT-10234 Don't run code with side effects inside asserts

---

dist/api_data.py
src/config/config_def.c
src/include/wiredtiger.in
test/suite/test_cc01.py
test/suite/test_cc10.py

The changes make it possible to trigger the obsolete cleanup thread more often. The current minimum value is 60 seconds, the changes set this limit to 1 second.
(cherry picked from commit 47e5efc0ca77bd34adbd43aa2d7ae765246a4027)

WT-13884 Update obsolete cleanup min value (v8.0) (#11571)

---

test/model/src/core/kv_database.cpp
test/model/src/core/util.cpp
test/model/src/driver/kv_workload_runner_wt.cpp
test/model/src/include/model/kv_database.h
test/model/src/include/model/util.h
test/model/tools/model_test/main.cpp

SLS-1568 deprecated the `shutdown_checkpoint` config option and changed WiredTiger's semantics so that only leaders take checkpoints on shutdown. Modify test/model accordingly.

SLS-1609 Remove the use of "shutdown_checkpoint" from test/model

---

src/live_restore/live_restore_fs.c

This change removes an assertion that checked whether the source file was open when importing a bitmap. This was incorrect as it could have been opened then the live restore completed concurrently.

WT-14262 Remove assertion which fires incorrectly when live restore completes concurrently with a file open call

---

src/checkpoint/checkpoint_txn.c
src/live_restore/live_restore_fs.c

This forces checkpoints to run on all files when in live restore mode. We previously dirtied trees that required checkpointing to write their live restore metadata entires, however, this was problematic for newly created tables that took "fake" checkpoints. See [SERVER-99614](https://jira.mongodb.org/browse/SERVER-99614) for further details.

WT-14276 Force checkpoints in live restore mode

---

test/catch2/sub_level_error/unit/test_sub_level_error_drop_uncommitted_dirty.cpp

Inside the `_wt_conn_dhandle_close` we are specifically testing a visibility check performed by `_wt_txn_visible_all`. Within the test, we hardcode the max_upd_txn to equal 3 with the assumption that the oldest transaction ID doesn't move. However since WT finds no active transaction on the system, it can freely move forward the oldest ID forward. Therefore the test becomes flaky as oldest ID can be more than 3. The fix will be instead setting the value to 100

WT-14207 Fix Uncommitted data unit test scenario

---

src/include/extern.h
src/live_restore/live_restore.h
src/live_restore/live_restore_state.c
src/meta/meta_table.c
src/meta/meta_turtle.c

Similar to how we intercept turtle file writes, make sure we always take the live restore state lock before taking the turtle lock on the read path. 
I originally only intercepted writes since they call `get_state` to write the live restore state to the turtle file, but the read path can also hit a deadlock since we call `__wti_live_restore_migration_complete` from `__live_restore_setup_lr_fh_file` while opening the turtle file.

WT-14277 Intercept turtle_read calls to take the live restore state lock first

---

src/live_restore/live_restore_fs.c

The destination file size is the cannonical file size but we have no guarantee we won't crash between creating a file in the destination and setting its size. This change ensures that the file creation and file size setting are atomic by renaming a temporary file.
I did manage to reproduce this failure using failpoints and some code editing but I don't see the point committing a failpoint that will only enable a single test.
Interestingly the following check was disabled to get my test to pass: 
```
// for (uint32_t i = 0; i < num_dest_files; ++i) {
//     if (WT_PREFIX_MATCH(dirlist_dest[i], WT_WIREDTIGER) ||
//       WT_SUFFIX_MATCH(dirlist_dest[i], ".wt"))
//         WT_ERR_MSG(session, EINVAL,
//           "Attempting to begin a live restore on a directory that already contains "
// …
```

WT-14235 Atomically set the destination file size

---

src/evict/evict_conn.c

We've been caught in previous PRs (see the Jira ticket) by moving `__evict_config_abs_to_pct` earlier in the code to a point before we set `conn->cache_size`, resulting in incorrect configurations. This is because the dependency of `__evict_config_abs_to_pct` on `conn->cache_size` is not obvious.
By passing `conn->cache_size` as an argument instead of fetching it from the connection, `__evict_config_abs_to_pct` becomes a pure function which makes it easier to reason about the value returned and harder to accidentally call it before `conn->cache` has been configured.

WT-13161 Pass cache_size into __cache_config_abs_to_pct as an argument

---

test/suite/test_tiered07.py

Remove an outdated FIXME for WT-8897 in test_tiered07.py.
We closed the Jira ticket as Won't Do since tiered storage is now deprecated.

WT-14294 Remove outdated fixme in test_tiered07.py

---

src/checkpoint/checkpoint_txn.c
src/live_restore/live_restore_fs.c

This reverts commit 7a0234ff0171a7323fea1f8bb98f7f19a0e7d12a.
Reverting due to test fallout. Checkpoints are mistakenly taken during verify.

Revert "WT-14276 Force checkpoints in live restore mode (#11725)"

---

test/model/tools/model_test/main.cpp

Run the database verification in test/model in a subprocess to protect the test runner from WiredTiger crashes during verification, which allows the counter-example reduction to proceed.

WT-13369 Open WiredTiger in a child process during test/model verification

---

src/conn/conn_layered.c
test/suite/test_layered36.py

During node step-up, check whether any shared stable tables are missing and create them if they don't.
The PR does the table creation explicitly, because (1) it eliminates any chances of race conditions, even as this is protected via the reconfig_lock, and (2) it handles empty tables correctly.

SLS-1623 Create missing stable tables during step-up

---

src/live_restore/live_restore_fs.c
src/live_restore/live_restore_state.c
test/catch2/live_restore/live_restore_test_env.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_live_restore_conflict.cpp
test/cppsuite/tests/test_live_restore.cpp
test/suite/test_live_restore01.py
test/suite/test_live_restore02.py
test/suite/test_live_restore03.py
test/suite/test_live_restore04.py
test/suite/test_live_restore05.py
test/suite/test_live_restore06.py
test/suite/test_live_restore07.py

Reverts wiredtiger/wiredtiger#11757
This commit didn't update wtperf so all perf tests are failing with `Source directory is not a valid backup directory`

Revert "WT-14278 Clean up live restore bitmap metadata on backup open, not on backup close"

---

src/evict/evict_lru.c
src/include/cache_inline.h
src/include/misc.h

WT-12280 converts evict_aggressive_score to use atomic operations
WT-13283 applies the compare-and-swap operation to the code to avoid
the value drops to -1.

WT-12280 and WT-13283 backport (7.0)

---

src/live_restore/live_restore_fs.c

Remove the layer parameter and instead pass the layer type we are interested in, additionally pass the lr_fs itself and reorder the arguments. 
Remove the unneeded dest_home param which is guaranteed to exist on the lr_fs.

WT-14299 Cleanup __live_restore_fs_backing_filename

---

test/cppsuite/src/main/test.cpp
test/cppsuite/src/storage/connection_manager.cpp
test/cppsuite/tests/csuite_style_example_test.cpp

I ran into this a few times when implementing a prior live restore test. connection_manager::create will silently delete any existing folder of the same name, so when a destination folder hasn't been copied across to the source it makes it harder to diagnose what went wrong when the eventually crashes. Add a quick safety check to prevent this from happening in future.

WT-14151 Don't clobber existing directories in cppsuite's connection_manager::create

---

test/catch2/CMakeLists.txt
test/catch2/live_restore/api/test_live_restore_fh_lock_close_sync.cpp

This is a relatively trivial change to get some line coverage of very minor APIs.

WT-14220 Test some minimal file handle APIs

---

test/evergreen.yml
test/format/CONFIG.live_restore

Turn on additional testing for live restore for the final weeks of the project.
We're writing additional unit tests for live restore, but to help improve confidence in code correctness bump up the amount stress testing for live restore. This change adds approximately 10 hours of additional live restore testing per commit in waterfall.
This increase in testing is temporary. These tests will be removed again at the end of the project to save on compute.

WT-14311 Add heavy testing for live restore

---

test/evergreen_develop.yml

We're currently writing both the ARM and ARMv9 perf results to the one collection, so results in our Atlas perf charts are combined into a single graph.
We should write them to their own collections to avoid polluting the data set.

WT-14139 Write ARM v9 perf results to their own Atlas charts collection

---

dist/s_string.ok
src/include/intpack_inline.h
src/utilities/util_load_json.c

We encountered compiler bugs when testing v5 toolchain. This ticket aims to fix two compilation issues:
- Inside intpack_inline.h, there is a known gcc bug as follows https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107842. I have applied a mitigation tactic.
- Fixed possible NULL issue inside util_json.c

WT-14282 Fix release build compilation errors in V5 toolchain

---

test/evergreen/code_coverage/code_coverage_config.json
test/evergreen/code_coverage/code_coverage_config_catch2.json
test/evergreen/code_coverage/per_test_code_coverage.py
test/evergreen/code_coverage_analysis.sh

The pull request fixes code coverage reports for the v5 toolchain. There were two main problems:
- Fix **ValueError: invalid literal for int() with base 10: 'executed'.** error with adding **--gcov-ignore-parse-errors**.
- Fix code coverage report 0% as code coverage via specifying a mongodbtoolchain when building WT.
To verify these changes I have posted a patch build on the ticket with V5 toolchain enabled.

WT-14410 Fix code coverage report for v5 toolchain

---

test/evergreen/code_coverage/code_coverage_config.json
test/evergreen/code_coverage/code_coverage_config_catch2.json
test/evergreen/code_coverage/per_test_code_coverage.py
test/evergreen/code_coverage_analysis.sh

The pull request fixes code coverage reports for the v5 toolchain. There were two main problems:
- Fix **ValueError: invalid literal for int() with base 10: 'executed'.** error with adding **--gcov-ignore-parse-errors**.
- Fix code coverage report 0% as code coverage via specifying a mongodbtoolchain when building WT.
To verify these changes I have posted a patch build on the ticket with V5 toolchain enabled.

WT-14110 Fix code coverage report for v5 toolchain

---

test/format/CONFIG.live_restore
test/live_restore/long_test.sh

Reduce the maximum number of operations performed in our live restore stress tests to reduce disk usage and the risk of hitting an ENOSPC error.

WT-14326 Reduce disk space usage in live restore stress testing

---

src/live_restore/live_restore_fs.c
src/live_restore/live_restore_private.h
test/catch2/live_restore/unit/test_live_restore_bitmap_encode_decode.cpp

The assert I added should remain regardless of whether we choose to handle the truncate case, personally I think it is low priority and it adds untestable complexity to the code. So I have opted to not resolve that scenario.

WT-13813 Cleanup the live restore truncate path and crash if we detect bitmap corruption

---

test/evergreen.yml
test/evergreen/code_coverage/code_coverage_utils.py
test/evergreen/code_coverage/parallel_code_coverage.py
test/evergreen/code_coverage/per_test_code_coverage.py

This change adds support for checking result codes from code coverage tests, and then exiting testing if a failure result occurs. 
Note this is only being used for Catch2 based tests for now, as several Python-based test return errors code when being used for code coverage. 
Some code tidying up was done at the same time.

WT-14072 Make code coverage fail if Catch2 tests crash

---

test/suite/test_live_restore02.py
test/suite/test_live_restore03.py
test/suite/test_live_restore04.py
test/suite/test_live_restore05.py
test/suite/test_live_restore06.py

This adds a checkpoint after the populate phase for each live restore test to ensure the populated data is persisted to disk before taking the backup that is used for live restore.

WT-14333 Fix live restore python tests to checkpoint tables

---

src/include/verbose.h
src/include/wt_internal.h

We often pass `WT_VERB_RECOVERY_RTS` into the `__wt_verbose_multi_*` macros as the `multi_category` argument, but `WT_VERB_RECOVERY_RTS` is a ternary under the hood so when we substitute `multi_category` into the macro we've evaluating the ternary in three separate locations. 
clang-analyzer raises a warning about this, as when `WT_VERB_RECOVERY_RTS` evaluates differently in different locations we can attempt a read past the end of the array. In the following code
```c
for (__v_idx = 0; __v_idx < multi_category.cnt; __v_idx++) {
if (WT_VERBOSE_LEVEL_ISSET(session, multi_category.categories[__v_idx], level)) {
```
if `multi_category` first evaluates to a struct with two categories (`cnt == 2`) then `__v_idx` will iterate up to a value of 1. Then if `multi_category` evaluates to a …

WT-14327 Evaluate __wt_verbose_multi_* macro arguments once

---

src/docs/error-handling.dox
src/include/api.h
src/include/extern.h
src/session/session_api.c
src/session/session_helper.c
test/catch2/sub_level_error/api/test_sub_level_error_session_get_last_error.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_compact.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_drop_conflict.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_rollback.cpp
test/catch2/sub_level_error/unit/test_sub_level_error_session_set_last_error.cpp
test/suite/test_error_info01.py

As part of [PM-3810](https://jira.mongodb.org/browse/SPM-3810) and [WT-13866](https://jira.mongodb.org/browse/WT-13866), we have introduced a performance regression. The performance regression is due to the number of calls calling set last error within each session API call. Currently, we call the set_last_error function to return the session error info structure to the default state before performing the actual session API work. This was done because of the need to have error state clean before we start tracking errors within WiredTiger.
**Solution**
The solution to this problem is to only perform set_last_error if the previous session error info contains a fail error code. In this case it means that we do not need to perform unnecessary resetting to default and only set it back to …

WT-14195 Reduce set_last_error calls in API_INIT (v8.1 backport)

---

src/live_restore/live_restore_fs.c
src/live_restore/live_restore_state.c

WiredTiger annotates almost all of its functions with `WT_GCC_FUNC_DECL_ATTRIBUTE((warn_unused_result))` to make sure the compiler warns us when a function returns a value but we don't use or check that value.
However, we can't add this attribute to static functions and don't get warnings for mis-use of these functions.
This change is a manual review of all static functions in `src/live_restore` to properly check error returns for non-void static functions.

WT-14119 Make sure all static functions in live restore check their return values

---

bench/workgen/runner/prepare_stress.py

The prepare-stress workload generates 250 threads altogether to perform CRUD operations. The *table_logging** debugging option, explicity triggers all CRUD operations to write to log for debugging purposes. The 250 threads will all write to the logging subsystem. This creates contention within the logging system.
The fix is to disable table_logging, it is only used for debugging purposes and should not be enabled as part of a performance test.

WT-14268 Disable table_logging for prepare_stress.py

---

test/syscall/CMakeLists.txt
test/syscall/syscall.py

Currently running simple `ctest` command on a non-preconfigured macOS system reports `test_syscall` failure because of Apple SIP system (enabled by default since OSX El Capitan) which restricts tracing system calls using `dtrace` tool.
The solution is to mark this test as "skipped" in this case instead of "failed" since generally speaking it is not a test failure (like detection of unexpected system call) but rather an absence of testing due to lack of required permissions. This commit also shows a message about the reason of the test being skipped.
<details>
<summary>This is how it looked like before:</summary>
```
ivan.kochin@M-KXJQD73J73 build % ctest -R test_syscall                                                          
Test project /Users/ivan.kochin/work/git/wiredtiger/build …
```

WT-14325 Skip syscall test if env issues detected

---

src/utilities/util.h
src/utilities/util_dump.c
src/utilities/util_list.c
src/utilities/util_misc.c
test/suite/test_util11.py

Implementation of `-f` option for `wt list` tool to provide the ability to redirect output to specified file similar to `wt dump -f`. It helps separate the tool output and WT notice logs.

WT-13584 Add custom output file option for wt list

---

src/conn/conn_sweep.c
test/suite/test_sweep06.py

This pull request has the changes to enhance sweep server's expiration logic, it will skip marking table dhandles for expiration if corresponding file dhandles exist, after verifying it's a simple table type.

WT-14140 Unnecessary schema lock taken for active file: dhandles that are not swept

---

src/docs/command-line.dox

`wt list -f` option was added by https://github.com/wiredtiger/wiredtiger/pull/11811. 
This PR is created to document this option on WT docs site.
That's how it looks like in built docs:

WT-14354 Add documentation for wt list -f

---

test/csuite/timestamp_abort/main.c

WT-3515 introduces this and I was able to reproduce from that commit. The original intention of why that code was added is because of this:
```
The child checkpoint thread got the error on the first checkpoint and never created the file that parent is looking for. So the parent hung. One fix is to have the parent wait up to MAX_TIME for that file to appear and error if it doesn't appear by then.
```
For the checkpoint file to be created it needs to first perform a checkpoint and the stable timestamp has been moved at least once. The expected 40 seconds is too strict when there are 200 threads are multiple intentional delays done inside the test. Here is a breakdown of all things that can slow down the first checkpoint or the setting the stable timestamp:
* Timing stress for …

WT-12806 Increase wait time for checkpoint file creation timestamp_abort

---

src/checkpoint/checkpoint_txn.c
src/conn/conn_dhandle.c
src/evict/evict_file.c
src/include/connection.h
src/session/session_api.c
src/txn/txn_log.c

Currently we have BFs that occur due to an EBUSY error code returned from conn->close(). The ticket aims to add diagnostic information for when an EBUSY error code happens again. A new macro has been introduced which will check if the connection is closing and check if the return value is non-zero. If both conditions are met, we abort in an attempt to narrow down where the EBUSY could come from. In the pull request I have identified key areas that the new macro could catch an EBUSY error.

WT-14317 Create macro which aborts when conn->close() returns an error code

---

src/live_restore/live_restore.h
src/live_restore/live_restore_fs.c
src/live_restore/live_restore_private.h
src/live_restore/live_restore_state.c
src/session/session_api.c
test/suite/test_live_restore06.py

This PR did below changes:
1. Allow opening a backup cursor when live restore is in the complete stage.
2. Allow taking backup in `__wt_live_restore_clean_metadata_string()`.
3. Change `__wti_live_restore_migration_complete()` to `__wt_live_restore_migration_complete()` as it is used externally.
4. Add a testing for taking backups when live restore in the COMPLETE phase for `test_live_restore06.py`.

WT-14231 Support taking a backup when live restore is in the complete stage

---

src/utilities/util_list.c

I missed this comma in the previous PR. Thanks Coverity for noticing this.

WT-14364 Add missing comma to wt list -f description

---

src/block_disagg/block_disagg_write.c
src/include/btree_inline.h
src/txn/txn_ckpt.c

My brain explodes when thinking about this. I feel what I do is still not enough.
I believe __wt_gen and WT_SESSION_BTREE_SYNC(session) should also use an acquire read internally. However, that will be a bigger change.

SLS-1908 Fix read ordering for eviction check

---

dist/s_string.ok
src/support/rand.c
test/csuite/random_session/main.c

This is a follow-up to **WT-13310**, addressing two key issues:
* Lack of randomness in the seed, which could lead to predictable or poor-quality sequences.
* Insufficient randomness in the low bits of the generated numbers, which affects randomness of selection via modulo.
Multiple tests were performed and added in this PR to ensure:
* Good randomness of each sequence
* Good randomness across sessions
* Good randomness across executions
* Good randomness in low bits (modulo 2048, 256, etc)

WT-14360 Fixup random generator (follow-up WT-13310)

---

tools/wt_cmp_dir

Currently, if some log output occurs during the execution of the wt_cmp_dir script, the script fails because it mixes the output of the `wt list` internal call and the log output. This PR fixes it by redirecting `wt list` output to the specified file and redirecting all the unrelated output during these checks to `/dev/null`.
The original issue doesn't reproduce on the default CI. Please see the corresponding Jira ticket for testing proofs.

WT-13585 wt_cmp_dir - fix handling WT logs output during check execution

---

src/live_restore/live_restore_fs.c

This PR is to replace existing `strstr` logic with `WT_PREFIX_MATCH` to check if the file name having a prefix of `destination.home` in live restore.

WT-14384 Use prefix match macro to assert name in live restore backing file name

---

test/evergreen/build_windows.ps1

Our windows machines have been updated and removed the old vcvard64.bat path on our Windows hosts. This uses the new path

WT-14387 Update vcvars64.bat path in Windows buildscript

---

test/evergreen/find_cmake.sh

Currently `find_cmake.sh` script contains `set -o errexit` setting which causes exit of the whole script if any issue occurs during its execution. This script is intended to be used in sourcing mode (e.g. . ./find_cmake.sh) and because of that, this setting is not a good choice for this script for two reasons:
- In this mode if any issue occurs this setting exits not only the script, but the shell that was executing this script
- Even if execution was successful this setting is propagated to the shell that was executing this script and stays enabled there even after script execution which causes exit from this shell on the next issue (any unsuccessful shell command).
This is current solution that is represented in this PR. AFAIK it provides similar effect of exiting from the function but …

WT-14385 Avoid propagating error on exit setting from find_cmake.sh

---

src/include/verbose.h
src/support/generation.c

(cherry picked from commit 8b909411846e25fd119431d57bd990d03e7ba45a)

WT-12012 Restore original verbose levels if gen_drain becomes unstuck after increasing verbose levels (v7.0 backport)

---

test/evergreen/build_windows.ps1

Reverts wiredtiger/wiredtiger#11853
We made this change to fix some platform issues on our Evergreen Windows hosts. Those changes have been reverted so we need to revert back to the original path.

Revert "WT-14387 Update vcvars64.bat path in Windows buildscript"

---

test/evergreen/evg_cfg.py

The check for `wiredtiger/wiredtiger` in `evg_cfg.py` causes this script to fail on forks of the wiredtiger repo, as the git remote.origin.url does not contain the correct string. 
This fix removes the check for the specific wiredtiger name, and instead uses the location of the `test/evergreen/evg_cfg.py` file to find the wiredtiger root folder.

WT-14372 Remove check that prevents evergreen script from running on forked branches

---

src/docs/statistics.dox

Fix the Statistics Logging documentation to use the correct name for its output files.

WT-14396 Fix file name used for statistics logging

---

src/include/extern.h
src/txn/txn.c
src/txn/txn_log.c

[WT-14334](https://jira.mongodb.org/browse/WT-14334) This change removes the unused variable `cfg` from `__wti_txn_log_commit`.

WT-14334 remove unused variable from txn_log

---

src/conn/conn_dhandle.c
test/suite/test_drop03.py

Updating the oldest_id transaction before a drop prevents unnecessary EBUSY errors, even when no older transactions exist below the table's last modified transaction.

WT-14455 Update the oldest_id before the drop table active transaction check

---

src/reconcile/rec_row.c

[WT-12244](https://jira.mongodb.org/browse/WT-12244) ticket was to investigate whether the `__rec_row_zero_len` function can be simplified by removing a check. 
While logically the extra check is not required as `__wt_txn_tw_start_visible_all` check covers it, it is an early exit to the function and can allow the method to skip evaluating the more expensive visible_all check. This pull request adds a comment explaining this. We can keep the code as is close the ticket as won't do.

WT-12244 Add comment on rec_row_zero_len

---

src/live_restore/live_restore_fs.c

This PR is to remove the partial logic and rewrite the function `__live_restore_can_service_read`. The main changes include:
1. Rewrite the logic to check varies scenarios during the iteration from `read_start_bit` to `read_end_bit`.
2. Remove the PARTIAL logic, now the read is either read from source or dest. The reason behind that is since wiredtiger always read/write one page at a time, when a read range is partial, it means there's an in progress background migration on that page but there are no writes on the page yet, thus read the entire page from source should be safe.

WT-14403 Remove the partial logic and rewrite __live_restore_can_service_read

---

test/csuite/incr_backup/main.c

The `incr_backup` csuite test no longer leaves enormous amounts of test artefacts when the `-p` preserve flag is not set.
This is avoided by saving the starting directory into `cwd_start` and `chdir` into it at the end so that we delete the top directory of the nested test artefacts.
Prior to this change, we retain nested artefacts:
```
(venv) ubuntu in ~/wiredtiger/build on (WT-14355-inc-backup-to-clean-test-artefacts)
$ du -ah /home/ubuntu/wiredtiger | sort -rh | head -n 40
...
1.2G    /home/ubuntu/wiredtiger/build/test/csuite
1.1G    /home/ubuntu/wiredtiger/build/test/csuite/incr_backup/WT_TEST.incr_backup
1.1G    /home/ubuntu/wiredtiger/build/test/csuite/incr_backup
...
637M    /home/ubuntu/wiredtiger/build/test/csuite/incr_backup/WT_TEST.incr_backup/WT_TEST.incr_backup
450M …
```

WT-14355 inc backup csuite test no longer leaves test artefacts

---

src/conn/conn_dhandle.c

I wasn't able to get to the bottom of this in the day or so I set aside. It's not happening very often so I figured adding an assertion would at least make it a bit more obvious.

SLS-2861 Add assertion for dhandle existence

---

src/conn/conn_compact.c
src/include/connection.h

The field `consecutive_unsuccessful_attempts` in `WT_BACKGROUND_COMPACT_STAT` struct is set but never read.
This field is dead code and should be deleted.

WT-13661 Remove dead consecutive_unsuccessful_attempts variable code

---

src/include/intpack_inline.h
test/checkpoint/test_checkpoint.c

The `-Warray-bounds` thing appears to have been fixed in GCC 15, so I removed the message.
There's also a new "unterminated string" warning when a string doesn't have a terminating null. test/checkpoint hit this, but it's OK because we don't actually use it as a string, just an array of characters. The alternative to removing the digit count would have been to mark it with `__attribute((nonstring))` or however it's spelled.

WT-14561 Build fixes for GCC 15

---

test/csuite/random_abort/main.c
test/csuite/schema_abort/main.c
test/csuite/timestamp_abort/main.c

The verify only mode for our random_abort test should not copy the database to a save directory, therefore adding a guard to avoid copying the database for -v mode.

WT-13368 random_abort shouldn't save in verify-only mode

---

src/reconcile/rec_write.c
src/reconcile/reconcile_private.h

There's two instantiated values in `__rec_init` that are not being read by anything. This PR cleans up the code and removes the unused values from `__rec_init` and from the definition of `__wti_reconcile`.

WT-12800 remove dead code in reconciliation

---

test/catch2/CMakeLists.txt

Add explicit dependency on wiredtiger_dir_store to the catch2 unittests to ensure that CMake will always build wiredtiger_dir_store when building the Catch2 unit tests. 
When running the Catch2 unit tests using CLion on my Macbook Pro M3 Max running MacOS 15.4.1 the following error frequently occurs:
```
/Users/jeremy.thorp/Git/wiredtiger/test/catch2/sub_level_error/unit/test_sub_level_error_drop_conflict.cpp:100: Failure:
due to unexpected exception with message:
Error result is 2
```
in 
`SECTION("Test WT_CONFLICT_DHANDLE with tiered storage")`
The error is caused by a missing dynamically loaded library, libwiredtiger_dir_store.so, that the test depends on. This library may, or may not, be available depending on how WT has been built. 
Note, the issue was initially thought to be Mac …

WT-14551 Add explicit dependency on wiredtiger_dir_store to the catch2 unittests

---

test/compatibility/compatibility_test_for_releases.sh

Recently a toolchain file for compatibility tests was switched from `mongodbtoolchain_v4_gcc.cmake` to `mongodbtoolchain_stable_gcc.cmake`. Later it turned out that some branches that are randomly picked for a compatibility testing don't contain this file.
This patch fixes it by using the stable toolchain only if it exists.

WT-14568 Compat tests: handle absence of stable toolchain file

---

test/cppsuite/tests/bounded_cursor_stress.cpp

WT-14323 Fix assert in bounded_cursor_stress test, to allow for the case where the range cursor operations returns WT_ROLLBACK.
In the bounded cursor stress test, multiple threads are adding, removing and updating random keys, while 'normal' cursors and range bounded cursors access that data. The test checks that the results between the normal and bounded cursor results are consistent. 
The test case already handled the case where the normal cursor returned WT_ROLLBACK. However, the test did not handle the case where the normal cursor returns WT_NOTFOUND and the bounded cursor returns WT_ROLLBACK which is possible due to those simultaneous add/remove/update operations. In this scenario an assert is triggered which is what happened in this Build Failure.
The fix is to update the expression …

WT-14323 Fix assert in bounded_cursor_stress test, to allow for WT_ROLLBACK result

---

.github/CODEOWNERS

As part of the wider effort to add code-ownership for compliance and tooling across all of our shipped codebases we need to set this up.
For the time being, I would prefer if we didn't reach for codeowners to create more internal barriers within WT, since I think we're actually in a pretty good place, but this note shouldn't preclude us considering that if/when the time is right.

WT-14577 add codeowners file

---

.github/CODEOWNERS

Because codeowners auto-assigns reviewers, and that comes with email notifications we need to include a service account in the code ownership rules so that we can exclude the team from auto assignment and silence the notifications.
When new users are onboarded, we have to make sure they are included in the list of users excluded from auto assignment here: https://github.com/orgs/wiredtiger/teams/storage-engines/edit/review_assignment
This is unfortunate, but seemingly the best option per https://github.com/orgs/community/discussions/35673

WT-14603 update codeowners to include svc-bot-sebb

---

.github/CODEOWNERS

This reverts commit 08d3ad73febac1d784b3a9a4e0d936de043bb54d.
It seems that we can solve this problem by taking advantage of the mana bot being in the storage-engines group and having it auto assign to that user.

Revert "WT-14603 update codeowners to include svc-bot-sebb (#11952)"

---

dist/stat_data.py
src/cache/cache.c
src/evict/evict_lru.c
src/include/cache.h
src/include/stat.h
src/include/wiredtiger.in
src/support/stat.c

Tracking the dirty and update bytes of the history store can show us its effect on the cache and eviction processes.

WT-14336 Track the dirty and update bytes of the history store

---

src/btree/bt_sync.c
src/checkpoint/checkpoint_txn.c
src/include/btree_inline.h
src/include/txn.h
src/include/txn_inline.h
src/reconcile/rec_visibility.c
src/reconcile/rec_write.c
src/reconcile/reconcile_private.h
src/session/session_api.c
src/txn/txn.c

The WT_TXNID_LT and WT_TXNID_LE used to contain special handling for transaction IDs like WT_TXN_ABORTED and WT_TXN_NONE, however these days they just evaluate to `a < b` and `a <= b` respectively. 
This change removed `WT_TXNID_LE` macro entirely in the codebase, and while `WT_TXNID_LT` is still kept, I've removed all usage of it except for the one in `WT_INSERTION_SORT` [here](https://github.com/wiredtiger/wiredtiger/blob/develop/src/include/misc.h#L247) for sorting an array.

WT-12808 remove transaction macro WT_TXNID_LT and WT_TXNID_LE

---

src/evict/evict_lru.c
src/evict/evict_page.c
test/suite/test_scrub_eviction_conditions.py

This change updates the code for scrub eviction, to avoid double evicting a page when the cache is under pressure. It is currently possible for a dirty page to be scrub evicted and read back in the cache, then clean evicted afterwards. To avoid this, a condition has been added to skip scrub eviction unless either clean eviction threshold has not been reached, or the page has high read generation. If we're over the clean eviction threshold and the page's read generation is low, we just evict the page.

WT-14039 avoid double eviction with scrub eviction

---

src/conn/conn_compact.c

In `wt_background_compact_end`, add log info to let users know when background compaction has compacted a file and how much space it has recovered.

WT-13671 Add info log once background compact completes

---

test/suite/test_stat12.py

The tests for eviction trigger statistics are non-deterministic as it's hard to control which pages get evicted. We can change the test to check that any eviction happens and increments related stats instead of checking that specific kinds of eviction happens. This should make the test more consistent and still check that eviction related stats are incrementing as they should be when eviction thresholds are met.

WT-14676 Change eviction stats tests to be more consistent
